/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/
// Some portions generated by Claude Code (Opus 5).

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_api.h                                            PORTABLE C      */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This file defines the Eclipse ThreadX ZoneX public interface: the   */
/*    language capability macros, the version identification, and the     */
/*    fundamental types every other ZoneX header builds on.               */
/*                                                                        */
/*    ZoneX is a partitioning hypervisor.  Phase 0 targets Armv8-R        */
/*    AArch32, where BOTH stages of address control are region-based      */
/*    MPUs (PMSAv8-R).  There are no page tables (zx-terminology-allow)   */
/*    anywhere on this target, and nothing in this interface should be    */
/*    read as implying one.                                               */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_API_H
#define ZX_API_H

#ifdef __cplusplus
extern "C" {
#endif

/* Language capability macros -- do not use __STDC_VERSION__ elsewhere in this
   header.

   NOTE: [[...]] attribute syntax is C23 (202311L).  C17 defines NO standard
   attributes, so C17 builds deliberately fall through to the GNU/MSVC forms.
   ZoneX is built to C17 with CMAKE_C_EXTENSIONS OFF and -Wpedantic in force,
   and under those a C17 branch spelling [[nodiscard]] is rejected outright:
   "ISO C does not support [[ attributes before C23".

   ZX_NORETURN is the same question with a different answer: C17 does have a
   standard spelling, the _Noreturn keyword from C11, and C23 deprecates it in
   favour of the [[noreturn]] attribute.  So the C17 branch here is a standard
   construct rather than a GNU fallback, and it is still reached through the
   macro for the same reason as the others.

   ZX_NOINLINE has no standard spelling in any C, which is why it is here
   rather than written out: it exists so that a function whose only purpose is
   to BE a symbol -- a place for a hardware breakpoint to land, on a target
   with no other way to report -- cannot be optimised into its caller and
   leave the debugger with nothing to break on.

   The macros are the contract, not their spelling.  Always write
   ZX_NODISCARD; never [[nodiscard]] directly.  That way moving ZoneX to C23
   is a change to this one block rather than churn across every header.  */
#if __STDC_VERSION__ >= 202311L  /* C23 */
#  define ZX_NODISCARD       [[nodiscard]]
#  define ZX_DEPRECATED(msg) [[deprecated(msg)]]
#  define ZX_MAYBE_UNUSED    [[maybe_unused]]
#  define ZX_NORETURN        [[noreturn]]
#  define ZX_NOINLINE        __attribute__((noinline))
#elif defined(__GNUC__) || defined(__clang__)
#  define ZX_NODISCARD       __attribute__((warn_unused_result))
#  define ZX_DEPRECATED(msg) __attribute__((deprecated(msg)))
#  define ZX_MAYBE_UNUSED    __attribute__((unused))
#  define ZX_NORETURN        _Noreturn
#  define ZX_NOINLINE        __attribute__((noinline))
#elif defined(_MSC_VER)
#  define ZX_NODISCARD       _Check_return_
#  define ZX_DEPRECATED(msg) __declspec(deprecated(msg))
#  define ZX_MAYBE_UNUSED
#  define ZX_NORETURN        _Noreturn
#  define ZX_NOINLINE        __declspec(noinline)
#else
#  define ZX_NODISCARD
#  define ZX_DEPRECATED(msg)
#  define ZX_MAYBE_UNUSED
#  define ZX_NORETURN
#  define ZX_NOINLINE
#endif

/* stdint.h and stddef.h are part of the freestanding C library, which C17
   requires every conforming implementation to provide.  They are not an
   external dependency in the sense CONTRIBUTING.md forbids.  */
#include <stdint.h>
#include <stddef.h>

/* Version identification.  ZoneX follows the suite-wide scheme described in
   CONTRIBUTING.md, "Release model and support".  Phase 0 is pre-release and
   carries a 0 major deliberately: the interfaces below are expected to change
   until the demonstrator is complete.  */
#define ZX_MAJOR_VERSION    0
#define ZX_MINOR_VERSION    1
#define ZX_PATCH_VERSION    0

/**************************************************************************/
/*                          Fundamental types                             */
/**************************************************************************/

/* The suite's integer type names, deliberately identical to the eight
   typedefs every ThreadX port carries in its own tx_port.h.

   ZoneX does not link ThreadX (docs/decisions.md D9), so it cannot reach
   tx_port.h for them -- and should not: a manifest has to be readable with no
   ThreadX checkout in sight, which is also what lets the host suite build
   with none present.  ZoneX therefore keeps its own copy.

   Copying rather than respelling them in <stdint.h> terms is the deliberate
   choice, and the suite-wide C17 upgrade is what settles it.  That upgrade
   changes no struct layout, no calling convention and no type name; it
   regression-tests that a C99 application still compiles against the new
   headers.  These names are load-bearing for that promise and therefore
   permanent, so adopting them costs nothing later.  A manifest written in
   uint8_t would make ZoneX the one component of the suite whose user-facing
   contract used a different vocabulary, for no gain.

   Identical typedef redeclaration is legal from C11 onwards, so an
   application including both tx_api.h and zx_api.h is well-formed.  The
   coupling that remains is the real cost: a port that ever respelled one of
   these -- ULONG as unsigned long long, say -- would conflict with this copy
   at the point of inclusion.  That is deliberately left unguarded, because a
   hard error at the include is the outcome worth having; an #ifndef around
   the block would hide the divergence instead.

   VOID is not copied.  ThreadX spells it as a macro rather than a typedef,
   ZoneX writes plain void and has no use for it, and an uncopied macro cannot
   collide.

   Addresses are NOT spelled with these -- see zx_addr_t below, and D5.  ULONG
   is unsigned long, which is not pointer-width on every ABI the suite
   targets; the suite's own C17 plan adds a static assertion to each
   tx_port.h precisely to catch that mismatch.  */
typedef char            CHAR;
typedef unsigned char   UCHAR;
typedef int             INT;
typedef unsigned int    UINT;
typedef long            LONG;
typedef unsigned long   ULONG;
typedef short           SHORT;
typedef unsigned short  USHORT;

/* An address in a partition manifest or in an MPU region descriptor.
   Deliberately a width-correct typedef rather than a bare unsigned long: the
   manifest is a data structure ZoneX means to keep across ports, and Armv8-R
   AArch32 is not the last architecture it will describe.  See
   docs/decisions.md D5.

   uintptr_t rather than a fixed width, so that a 64-bit port -- RISC-V with
   the hypervisor extension, or Armv8-R AArch64 (R82) -- widens this with the
   pointer instead of needing every declaration revisited.  The one case this
   does not cover is a machine whose physical address space is wider than its
   pointers; ZoneX has no such target, and adding one means revisiting this
   typedef rather than working around it at each use.  */
typedef uintptr_t zx_addr_t;

/* A length, in bytes, of a region of memory described by a manifest.  Paired
   with zx_addr_t so that a base and a size are always the same width, which is
   what makes (base + size - 1) safe to compute as a limit.  */
typedef uintptr_t zx_size_t;

/* PMSAv8-R programs a region as a base and an inclusive limit, both of which
   must be aligned to the 64-byte granule.  An under-aligned base does not
   fault: its low bits land on the SH, AP and XN fields of HPRBAR and silently
   change the region's attributes.  An unmasked limit is worse -- (base + size
   - 1) ends in 0x3F, which lands on HPRLAR's AttrIndx field and selects an
   unwritten MAIR byte.  Both traps were paid for at EL1 during the
   Cortex-R52 Modules port work, and are repeated here because they apply
   unchanged at stage 2.  */
#define ZX_MPU_GRANULE      64U

/* The C17 baseline is a project decision (docs/decisions.md D12), not an
   accident of whichever compiler happens to be installed.  Asserting it here
   means a build that quietly fell back to an older standard fails at the first
   header rather than at whichever construct it first cannot parse.  */
_Static_assert(sizeof(zx_addr_t) >= 4U,
               "zx_addr_t must be at least 32 bits wide");
_Static_assert(sizeof(zx_addr_t) == sizeof(zx_size_t),
               "zx_addr_t and zx_size_t must be the same width");

#ifdef __cplusplus
}
#endif

#endif /* ZX_API_H */
