/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_console.h                                         PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The hypervisor's own console, as an interface rather than a         */
/*    driver.  It is declared in common/ rather than in the port because  */
/*    core/ needs it: a fault record that cannot be printed is not a      */
/*    fault report, and the code that formats one is architecture-        */
/*    independent.  See docs/decisions.md D8.                             */
/*                                                                        */
/*    Three implementations exist, and which one is linked is a build     */
/*    decision, never a run-time one:                                     */
/*                                                                        */
/*      * semihosting, on the Armv8-R AEM FVP -- no peripheral, so it     */
/*        cannot be broken by a wrong memory map, which is what makes it  */
/*        usable before the MPU is trusted;                               */
/*      * a board UART, on silicon, reached through the zx_board_console_ */
/*        hooks below;                                                    */
/*      * a capture buffer, in the host unit tests, which is what lets    */
/*        the fault report's text be asserted on rather than eyeballed.   */
/*                                                                        */
/*    Everything here is polled and re-entrant enough to be called from   */
/*    a fault handler, because that is where it is needed most.           */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_CONSOLE_H
#define ZX_CONSOLE_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Write a NUL-terminated string.  A null pointer writes nothing rather than
   faulting: this is called from the fault handler, and a console that can
   itself fault turns one diagnosable problem into none.  */

void zx_console_puts(const char *string_ptr);

/* Write value as 0x-prefixed, zero-padded 32-bit hexadecimal.  Every register
   ZoneX reports is 32 bits wide on this target and is reported at full width,
   so that two values can be compared by eye without counting digits.  */

void zx_console_puthex(uint32_t value);

/* Write value in decimal, no padding.  Used for counts -- region numbers,
   fault counts -- where hexadecimal would be harder to read, not easier.  */

void zx_console_putdec(uint32_t value);

/* Terminate the run.  On the FVP this is the semihosting SYS_EXIT that stops
   the model; on silicon there is nothing to stop, so it parks in a loop at a
   symbol the gdb harness breaks on.  Either way the PASS or FAIL verdict has
   already been PRINTED: the AArch32 SYS_EXIT parameter is a reason code and
   not an exit status, so the console text is what a run is judged on.  */

ZX_NORETURN void zx_console_exit(uint32_t failures);

/* Does nothing, and is the point.  A target with no semihosting has nothing
   to stop, so a run there ends by parking -- and the only way to read the
   result is a debugger.  A breakpoint on zx_console_exit lands BEFORE it
   stores the verdict, so the harness would read whatever the variable held
   beforehand and report that the run never finished, on a run that finished
   perfectly.  Measured, on the S32Z280, against a console that said ALL
   CHECKS PASSED.

   This is called after every global is settled, so it is the symbol a
   hardware breakpoint should be placed on.  ZX_NOINLINE because a function
   that got inlined would leave the debugger with no symbol to break on and
   the same silent misreport.  */

ZX_NOINLINE void zx_console_run_parked(void);

/* The board's own console, when one is linked instead of semihosting.
   Declared here rather than in the port because the port is the Armv8-R
   architecture and a LINFlexD is not part of it -- the board example provides
   these two functions, and platform/cortex_r52/src/zx_console.c calls them
   when ZX_CONSOLE_BOARD is defined.  */

#ifdef ZX_CONSOLE_BOARD
void zx_board_console_init(void);
void zx_board_console_putc(char character);
#endif

#ifdef __cplusplus
}
#endif

#endif /* ZX_CONSOLE_H */
