/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/
// Some portions generated by Claude Code (Opus 5).

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_console.c                                         Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The hypervisor's own console.  ZoneX needs one before it needs      */
/*    anything else: on the Armv8-R AEM FVP there is no debugger seam at  */
/*    all -- an Iris server and no GDB stub -- so a model regression can  */
/*    only report through a channel the image carries itself.             */
/*                                                                        */
/*    Two backends, chosen at build time and never at run time:           */
/*                                                                        */
/*      * semihosting, the default.  HLT 0xF000 is the Armv8 AArch32       */
/*        semihosting trap, and the model implements it with no           */
/*        peripheral configuration at all -- which is exactly why it is   */
/*        the right console to bring up BEFORE the MPU is trusted.  A     */
/*        UART console can be broken by a wrong memory map; this cannot.  */
/*                                                                        */
/*      * ZX_CONSOLE_BOARD, where the board example supplies              */
/*        zx_board_console_init and zx_board_console_putc.  The board's    */
/*        UART is not part of the Armv8-R architecture, so its driver      */
/*        lives with the board rather than in this port.                  */
/*                                                                        */
/*    How the console is shared once there are two partitions is an open  */
/*    decision, docs/decisions.md D8, deliberately left to the step that  */
/*    first has two guests wanting it.                                    */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                    */
/*                                                                        */
/*    Directive 4.3 -- the single asm statement is alone in                */
/*      zx_semihost_call and appears nowhere else in this file.            */
/*    Rule 1.1 / 1.2 -- register-asm bindings and inline assembly are      */
/*      unavoidable to invoke a semihosting trap; no standard C construct  */
/*      expresses it.                                                      */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"

/* Number of hexadecimal digits in a 32-bit value.  */

#define ZX_HEX_DIGITS   8U

/* The verdict, published as an object as well as printed.  On the FVP the
   printed line is what the runner judges; on silicon there is no console
   capture inside the image's own control, so the gdb harness reads this.
   Both, rather than either, because a run whose console was not captured
   still has to be judgeable -- and a run whose memory says PASS while its
   console says FAIL is a finding in itself.  */

uint32_t zx_run_failures = 0xFFFFFFFFU;


#ifndef ZX_CONSOLE_BOARD

/**************************************************************************/
/*  zx_semihost_call                                                      */
/*                                                                        */
/*  One semihosting operation.  The only assembly in this file.           */
/**************************************************************************/

static uint32_t zx_semihost_call(uint32_t operation, const void *argument_ptr)
{
    register uint32_t    result   __asm__("r0") = operation;
    register const void *argument __asm__("r1") = argument_ptr;

    __asm__ volatile("hlt 0xf000"
                     : "+r"(result)
                     : "r"(argument)
                     : "memory");

    return result;
}

#endif /* !ZX_CONSOLE_BOARD */


/**************************************************************************/
/*  zx_console_puts                                                       */
/**************************************************************************/

void zx_console_puts(const char *string_ptr)
{
    if (string_ptr == (const char *)0)
    {
        return;
    }

#ifdef ZX_CONSOLE_BOARD

    {
        const char *cursor = string_ptr;

        /* Initialised on first use rather than from zx_board_init, so that a
           message emitted before the board hook ran still appears.  The
           first thing worth printing is often the reason the boot did not
           get as far as initialising anything.  */

        static uint32_t initialised = 0U;

        if (initialised == 0U)
        {
            initialised = 1U;
            zx_board_console_init();
        }

        while (*cursor != '\0')
        {
            zx_board_console_putc(*cursor);
            cursor++;
        }
    }

#else

    (void) zx_semihost_call(ZX_SYS_WRITE0, string_ptr);

#endif
}


/**************************************************************************/
/*  zx_console_puthex                                                     */
/*                                                                        */
/*  Always eight digits.  Zero padding is not cosmetic here: the report    */
/*  puts HPFAR next to HDFAR so that a reader can compare them by eye, and */
/*  two values of different printed widths do not line up.                */
/**************************************************************************/

void zx_console_puthex(uint32_t value)
{
    static const char digits[] = "0123456789abcdef";
    char              buffer[3U + ZX_HEX_DIGITS];   /* "0x" + digits + NUL  */
    uint32_t          index;

    buffer[0] = '0';
    buffer[1] = 'x';

    for (index = 0U; index < ZX_HEX_DIGITS; index++)
    {
        uint32_t shift = (ZX_HEX_DIGITS - 1U - index) * 4U;

        buffer[2U + index] = digits[(value >> shift) & 0xFU];
    }

    buffer[2U + ZX_HEX_DIGITS] = '\0';

    zx_console_puts(buffer);
}


/**************************************************************************/
/*  zx_console_putdec                                                     */
/**************************************************************************/

void zx_console_putdec(uint32_t value)
{
    char     buffer[11];        /* 4294967295 plus NUL                      */
    uint32_t index = sizeof(buffer) - 1U;
    uint32_t work  = value;

    buffer[index] = '\0';

    do
    {
        index--;
        buffer[index] = (char)('0' + (char)(work % 10U));
        work /= 10U;
    } while ((work != 0U) && (index > 0U));

    zx_console_puts(&buffer[index]);
}


/**************************************************************************/
/*  zx_console_exit                                                       */
/*                                                                        */
/*  The end of every run, and the symbol the silicon gdb harness breaks    */
/*  on.  The verdict has already been printed by the caller: on AArch32    */
/*  the SYS_EXIT parameter is a REASON code and not an exit status, so a   */
/*  run is judged on its console text and not on what the model returns.   */
/*  Both reasons are passed anyway, so that a run stopping for the wrong   */
/*  reason is distinguishable in the model's own trace.                    */
/**************************************************************************/

/**************************************************************************/
/*  zx_console_run_parked                                                 */
/*                                                                        */
/*  The symbol a silicon debug harness breaks on.  See zx_console.h.      */
/**************************************************************************/

ZX_NOINLINE void zx_console_run_parked(void)
{
    /* The empty asm keeps the body from being optimised away entirely; the
       function has to exist as an address, not merely as a name.  */

    __asm__ volatile("" ::: "memory");
}


ZX_NORETURN void zx_console_exit(uint32_t failures)
{
    zx_run_failures = failures;

    __asm__ volatile("dsb" ::: "memory");

    /* Everything is settled: the verdict has been printed and stored.  A
       hardware breakpoint here reads the real result.  */

    zx_console_run_parked();

#ifndef ZX_CONSOLE_BOARD

    {
        uint32_t reason = (failures == 0U) ? ZX_ADP_STOPPED_APPLICATION_EXIT
                                           : ZX_ADP_STOPPED_RUN_TIME_ERROR;

        (void) zx_semihost_call(ZX_SYS_EXIT, (const void *)reason);
    }

#endif

    /* Reached on silicon always, and on the model only if a host or debug
       configuration ignored the semihosting exit.  Parking rather than
       returning: zx_console_exit is declared not to return, and a run that
       carried on past its own verdict would print a second one.  */

    for (;;)
    {
        /* Intentionally empty.  */
    }
}
