/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_console.c                                         Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The hypervisor's own console.  ZoneX needs one before it needs      */
/*    anything else: on the Armv8-R AEM FVP there is no debugger seam at  */
/*    all -- an Iris server and no GDB stub -- so a model regression can  */
/*    only report through a channel the image carries itself.             */
/*                                                                        */
/*    How the console is shared once there are two partitions is an open  */
/*    decision, docs/decisions.md D8, deliberately left to the step that  */
/*    first has two guests wanting it.                                    */
/*                                                                        */
/*    This translation unit is deliberately empty of implementation.      */
/*    See docs/armv8r-el2-reference.md for the verified register sheet    */
/*    the code that lands here must be written against.                   */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"
