/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_cache.c                                           Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Making a copied guest image executable.                             */
/*                                                                        */
/*  WHY THIS FILE EXISTS AT ALL, GIVEN THAT ZONEX RUNS WITH CACHES OFF    */
/*                                                                        */
/*    Because "it works today" is exactly how this defect survives.       */
/*                                                                        */
/*    A guest image arrives in its window through DATA writes and is then */
/*    FETCHED as instructions.  On this core the instruction side is not  */
/*    coherent with the data cache, so an image copied and not            */
/*    synchronised is only executable by luck: a cold instruction cache   */
/*    over an address nothing has executed happens to miss, fetch from    */
/*    memory, and work.  It stops working when an eviction lands          */
/*    differently -- which is to say, when something unrelated changes.   */
/*    The Cortex-R52 Modules port work had a two-address module test      */
/*    passing before this maintenance was added to it.                    */
/*                                                                        */
/*    ZoneX at EL2 clears HSCTLR.C and HSCTLR.I in its reset path, so     */
/*    right now both sides go to memory and the sequence below is         */
/*    genuinely redundant.  It is here anyway, and it is here NOW rather  */
/*    than when caches are switched on, because the change that switches  */
/*    them on will be a one-line change to the reset path made by         */
/*    somebody who has no reason to think about the loader.               */
/*                                                                        */
/*  WHY A RANGE CLEAN AND NOT A CLEAN-ALL                                 */
/*                                                                        */
/*    The Cortex-R52 board support cleans the whole data cache by         */
/*    set/way, because what it needs is for EVERYTHING this image wrote   */
/*    to be visible to a debugger.  A loader needs something narrower and */
/*    can say exactly what: the bytes it just wrote.  Cleaning by virtual */
/*    address to the point of coherency costs one operation per cache     */
/*    line of the IMAGE rather than one per line of the CACHE, and it     */
/*    does not write back unrelated dirty lines belonging to the          */
/*    hypervisor.                                                         */
/*                                                                        */
/*    The instruction side goes the other way: ICIALLU invalidates the    */
/*    whole instruction cache in ONE operation, which is cheaper than a   */
/*    per-line sweep of the image and strictly safer -- an image copied   */
/*    into a window that previously held a DIFFERENT guest may have stale */
/*    lines anywhere in it, including addresses the new image does not    */
/*    happen to occupy.                                                   */
/*                                                                        */
/*  WHY THERE IS ONE ENTRY POINT AND NOT TWO                              */
/*                                                                        */
/*    Because the failure mode is doing one half.  A caller that cleaned  */
/*    the data side and forgot the instruction side gets an image that    */
/*    works until it does not, and there is no diagnostic anywhere that   */
/*    would say so.  Exposing the halves separately would make that       */
/*    mistake available for no benefit: nothing in ZoneX wants one        */
/*    without the other.                                                  */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Directive 4.3 (assembly shall be encapsulated and isolated) --      */
/*      observed rather than violated: every asm statement below is one   */
/*      coprocessor operation inside a one-line static function.          */
/*    Rule 1.1 / 1.2 -- inline assembly is unavoidable for CP15; no       */
/*      standard C construct reaches a cache maintenance operation.       */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"

/* CTR, the Cache Type Register: p15, 0, c0, c0, 1.
 *
 * DminLine and IminLine are the LOG2 OF THE NUMBER OF WORDS in the smallest
 * line of each side, not of the number of bytes.  A loop that strode by
 * (1 << DminLine) rather than (4 << DminLine) would step a quarter of a line
 * at a time -- four times the work, still correct -- while one that took the
 * field as bytes directly would stride four times too far and leave three
 * lines in four untouched.  The second is the dangerous reading and it is
 * the one that looks right.
 *
 * The minimum across all levels is what these fields report, which is
 * exactly what a virtual-address maintenance loop needs: striding by the
 * smallest line means no line at any level is skipped.  */

#define ZX_CTR_IMINLINE_SHIFT   0U
#define ZX_CTR_DMINLINE_SHIFT   16U
#define ZX_CTR_MINLINE_MASK     0xFU


static uint32_t zx_read_ctr(void)
{
    uint32_t value;

    __asm__ volatile("mrc p15, 0, %0, c0, c0, 1" : "=r"(value));

    return value;
}


/* DCCMVAC: clean data cache line by virtual address, to the point of
   coherency.  p15, 0, c7, c10, 1.  */

static void zx_dccmvac(zx_addr_t address)
{
    __asm__ volatile("mcr p15, 0, %0, c7, c10, 1"
                     : : "r"((uint32_t)address) : "memory");
}


/* ICIALLU: invalidate all instruction caches to the point of unification.
   p15, 0, c7, c5, 0.  The operand is ignored and must still be written.  */

static void zx_iciallu(void)
{
    uint32_t zero = 0U;

    __asm__ volatile("mcr p15, 0, %0, c7, c5, 0"
                     : : "r"(zero) : "memory");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_cache_dcache_line_bytes                           Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The smallest data cache line, in bytes, across every level.         */
/*                                                                        */
/*    Exposed so that the boot report can PRINT the stride the loader      */
/*    used.  A maintenance loop that strode wrongly does not fail; it      */
/*    leaves lines untouched and the image runs until it does not, so the  */
/*    stride is worth putting in a log where somebody can compare it       */
/*    against the part's documented line size.                             */
/*                                                                        */
/**************************************************************************/

uint32_t zx_cache_dcache_line_bytes(void)
{
    uint32_t ctr = zx_read_ctr();
    uint32_t words_log2 = (ctr >> ZX_CTR_DMINLINE_SHIFT) & ZX_CTR_MINLINE_MASK;

    return 4U << words_log2;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_cache_icache_line_bytes                           Cortex-R52     */
/*                                                                        */
/**************************************************************************/

uint32_t zx_cache_icache_line_bytes(void)
{
    uint32_t ctr = zx_read_ctr();
    uint32_t words_log2 = (ctr >> ZX_CTR_IMINLINE_SHIFT) & ZX_CTR_MINLINE_MASK;

    return 4U << words_log2;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_cache_sync_after_load                             Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Makes freshly written bytes fetchable as instructions.               */
/*                                                                        */
/*    THE ORDER IS THE WHOLE CONTENT OF THIS FUNCTION:                     */
/*                                                                        */
/*      1.  clean every data cache line the image occupies, so the bytes   */
/*          reach memory;                                                  */
/*      2.  DSB, so those cleans have completed before anything depends on  */
/*          them -- an instruction cache invalidate issued before the       */
/*          cleans retire can refill from memory that is still stale;       */
/*      3.  invalidate the instruction cache, so no stale line for these    */
/*          addresses survives;                                            */
/*      4.  DSB, so the invalidate has completed;                          */
/*      5.  ISB, so the fetch of the next instruction cannot have been      */
/*          made before any of it.                                         */
/*                                                                        */
/*    Steps 2 and 4 are the two that get dropped, and neither drop fails   */
/*    where it is made.                                                    */
/*                                                                        */
/*    The base is rounded DOWN to a line boundary and the end rounded UP,   */
/*    because maintenance is per line and a partly covered line at either   */
/*    end would otherwise be left dirty.  A guest window is granule        */
/*    aligned and a granule is 64 bytes, so on both ZoneX targets the       */
/*    rounding changes nothing -- which is precisely why it is written      */
/*    rather than assumed: the first target whose line exceeds a granule    */
/*    would silently lose the ends of every image.                         */
/*                                                                        */
/**************************************************************************/

void zx_cache_sync_after_load(zx_addr_t base, zx_size_t length)
{
    uint32_t  line = zx_cache_dcache_line_bytes();
    zx_addr_t address;
    zx_addr_t end;

    if (length == 0U)
    {
        /* Nothing was copied, so there is nothing to make fetchable.  The
           caller should not have got here -- an empty image is refused by
           the manifest validator and again by the loader -- and this returns
           rather than sweeping the whole address space from a length that
           underflowed.  */
        return;
    }

    /* Round the base down and the end up to whole lines.  The end is
       computed as a LAST BYTE rather than a one-past-the-end address, so
       that an image finishing at the top of the address space does not wrap
       to zero and turn a five-line clean into a sweep of everything.  */

    address = base & ~(zx_addr_t)(line - 1U);
    end     = (base + (length - 1U)) | (zx_addr_t)(line - 1U);

    for (;;)
    {
        zx_dccmvac(address);

        if (address >= (end - (zx_addr_t)(line - 1U)))
        {
            break;
        }

        address += (zx_addr_t)line;
    }

    __asm__ volatile("dsb" ::: "memory");

    zx_iciallu();

    __asm__ volatile("dsb" ::: "memory");
    __asm__ volatile("isb" ::: "memory");
}
