/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_context.c                                         Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The half of a partition switch that does not have to be assembly:   */
/*    the banked EL1 registers, the EL1 system registers, the guest's own */
/*    virtual timer, its per-partition CNTVOFF, and the whole EL1 MPU     */
/*    region set.                                                        */
/*                                                                        */
/*  WHY THIS IS C AND NOT A PAGE OF MCR/MRC PAIRS                         */
/*                                                                        */
/*    Because at EL2 it can be.  AArch32 Hyp mode banks only SP, LR and    */
/*    SPSR, so at the instant the hypervisor takes control, everything    */
/*    below is STILL IN THE MACHINE and reachable with the ordinary       */
/*    banked-register and coprocessor forms.  Only r0-r12, ELR_hyp and    */
/*    SPSR_hyp have to be captured before the first C instruction runs,   */
/*    and those fifteen words are zx_context.S's whole job.               */
/*                                                                        */
/*    That split is worth its explanation because the plan this work came */
/*    from expected the opposite -- one large assembly routine doing all  */
/*    of it.  The dominant cost here is the EL1 MPU: twenty regions on    */
/*    the S32Z280, two registers each, selected through a third.  As a    */
/*    loop it is eight lines that a reader can check against the region   */
/*    count the part reported.  Unrolled in assembly it is a hundred and  */
/*    twenty coprocessor moves in which a single transposed operand is    */
/*    invisible and hands one partition another's memory permissions.     */
/*                                                                        */
/*    Nothing is given up.  The loop's trip count is read from MPUIR once */
/*    at boot and does not depend on anything a guest did, so the switch  */
/*    is still one number rather than a distribution -- which is the only */
/*    property a worst-case-execution-time argument actually needs.       */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Directive 4.3 -- every banked-register and coprocessor access below */
/*      has no C equivalent.  They are confined to this file's accessor    */
/*      macros and to the MPU loop, and each names the register it        */
/*      touches in a comment beside it.                                    */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"
#include <stddef.h>

/* THE OFFSETS ZX_CONTEXT.S INDEXES BY, checked against the structure they
   are meant to describe.  A field inserted above zx_ctx_elr would otherwise
   move it silently, and the assembly would store a guest's return address
   over one of its general-purpose registers -- a partition resumed at a
   plausible-looking address in the middle of its own data.  Nothing would
   fault and nothing would say why.  */

_Static_assert(offsetof(ZX_GUEST_CONTEXT, zx_ctx_r) == ZX_ASM_CTX_OFF_R0,
               "zx_context.S stores r0 at the wrong offset");
_Static_assert(offsetof(ZX_GUEST_CONTEXT, zx_ctx_r[12])
                   == ZX_ASM_CTX_OFF_R12,
               "zx_context.S stores r12 at the wrong offset");
_Static_assert(offsetof(ZX_GUEST_CONTEXT, zx_ctx_elr) == ZX_ASM_CTX_OFF_ELR,
               "zx_context.S stores ELR_hyp at the wrong offset");
_Static_assert(offsetof(ZX_GUEST_CONTEXT, zx_ctx_spsr) == ZX_ASM_CTX_OFF_SPSR,
               "zx_context.S stores SPSR_hyp at the wrong offset");

/* And that the thirteen shared registers really are contiguous, because
   the capture is one STM.  */
_Static_assert(sizeof(((ZX_GUEST_CONTEXT *)0)->zx_ctx_r) == 13U * 4U,
               "the shared-register array is no longer thirteen words");

/* HCR's three routing bits are FMO, IMO, AMO going UP from bit 3, and this
   port had FMO and AMO the other way round until the first image that SET
   one of them.  The mnemonic order a reader reaches for is alphabetical --
   AMO first -- and IMO is bit 4 either way, which is exactly why the
   mistake survived: every use of the three until then was a single BIC of
   all three at once, where swapping two of them changes nothing.

   What it cost: routing FIQ to EL2 set bit 5, which is AMO, so a
   partition's window never ended.  The comparator expired, the GIC made the
   interrupt pending, and the guest's own PSTATE.F then masked it as an
   ordinary EL1 FIQ.  The run printed a flawless set-up and then went quiet.

   Asserted here rather than in the header because everything above the
   __ASSEMBLER__ guard in zx_port.h is read by the assembler as well, and an
   assembler cannot read a _Static_assert.  TRM Table 3-70.  */

_Static_assert(ZX_HCR_FMO == 0x8U,  "HCR.FMO is bit 3 (TRM Table 3-70)");
_Static_assert(ZX_HCR_IMO == 0x10U, "HCR.IMO is bit 4 (TRM Table 3-70)");
_Static_assert(ZX_HCR_AMO == 0x20U, "HCR.AMO is bit 5 (TRM Table 3-70)");

/* CNTV_CTL, the guest's virtual timer control.  Stopping a partition's
   timer clears BOTH bits: masking alone leaves the comparator running with
   ISTATUS set, so a guest re-entered later finds a timer it never armed
   already expired.  */
#define ZX_CNTV_CTL_ENABLE      ZX_BIT(0)
#define ZX_CNTV_CTL_IMASK       ZX_BIT(1)

/* MPUIR keeps the EL1 region count in bits [15:8].  HMPUIR keeps the EL2
   count in bits [7:0] -- different registers, different fields, and exactly
   the sort of detail that is wrong once and then copied.  */
#define ZX_MPUIR_EL1_COUNT_SHIFT    8U
#define ZX_MPUIR_EL1_COUNT_MASK     0xFFU

static uint32_t zx_el1_regions;
static uint32_t zx_el1_regions_clamped;


/**************************************************************************/
/*                        Banked-register accessors                       */
/*                                                                        */
/*  MRS/MSR (banked register) is how Hyp mode reaches another mode's SP,   */
/*  LR and SPSR without changing mode.  The alternative -- CPS into each    */
/*  mode, read the registers, CPS back -- would work at EL1 and cannot be  */
/*  used here at all: entering an EL1 mode from Hyp is not a mode change,  */
/*  it is an exception return.                                            */
/*                                                                        */
/*  User and System SHARE SP and LR, so SP_usr covers both.  There is no   */
/*  SPSR_usr, because User mode cannot take an exception into itself.      */
/**************************************************************************/

#define ZX_SAVE_BANKED(field, reg)                                          \
    __asm__ volatile("mrs %0, " #reg : "=r"(context_ptr->field))

#define ZX_LOAD_BANKED(field, reg)                                          \
    __asm__ volatile("msr " #reg ", %0" : : "r"(context_ptr->field))


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_context_probe_el1_regions                         Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Reads how many EL1 MPU regions this part has, ONCE, at boot.        */
/*                                                                        */
/*    Once, because the count is fixed for the life of the run and a      */
/*    coprocessor read inside the switch would put a cost on the path     */
/*    this whole step exists to measure -- for an answer that cannot      */
/*    change.                                                             */
/*                                                                        */
/*    CLAMPED, AND THE CLAMPING IS REPORTED.  The Armv8-R AEM FVP claims  */
/*    thirty-two EL1 regions, which is not an architecturally legal       */
/*    Cortex-R52 value; the S32Z280 has twenty.  A part claiming more     */
/*    than the context block can hold would have its highest regions      */
/*    silently left out of every save -- so the outgoing partition's last */
/*    windows would stay programmed and the incoming one would inherit    */
/*    them.  That is an isolation failure at stage ONE, invisible to      */
/*    every stage-2 check in this suite, so the fact that anything was    */
/*    clamped is a value a run can assert is zero.                        */
/*                                                                        */
/**************************************************************************/

void zx_context_probe_el1_regions(void)
{
    uint32_t mpuir;

    __asm__ volatile("mrc p15, 0, %0, c0, c0, 4" : "=r"(mpuir));

    zx_el1_regions = (mpuir >> ZX_MPUIR_EL1_COUNT_SHIFT)
                     & ZX_MPUIR_EL1_COUNT_MASK;

    if (zx_el1_regions > ZX_MAX_EL1_REGIONS)
    {
        zx_el1_regions_clamped = zx_el1_regions - ZX_MAX_EL1_REGIONS;
        zx_el1_regions         = ZX_MAX_EL1_REGIONS;
    }
    else
    {
        zx_el1_regions_clamped = 0U;
    }
}


uint32_t zx_context_el1_regions(void)
{
    return zx_el1_regions;
}


uint32_t zx_context_el1_regions_clamped(void)
{
    return zx_el1_regions_clamped;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_context_init                                      Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The state a partition that has never run is entered with.           */
/*                                                                        */
/*    IT STARTS BY SAVING THE MACHINE, and that is not a shortcut -- it   */
/*    is the only defensible template.  A context block is restored        */
/*    WHOLESALE: every banked register, every MPU region, every EL1        */
/*    system register.  So whatever this function leaves in it is what     */
/*    the partition's very first entry programs, and that is the one       */
/*    entry where there is nothing to compare the result against.          */
/*                                                                        */
/*    ZEROING IT ALL WAS THE OBVIOUS ANSWER AND IT IS WRONG.  SCTLR has    */
/*    RES1 bits on this architecture, and writing zero to a RES1 bit is    */
/*    CONSTRAINED UNPREDICTABLE -- so a partition entered from a zeroed    */
/*    block starts with a system control register no reset would ever      */
/*    produce.  The same argument covers CPACR, MAIR and AMAIR: their      */
/*    reset values are the part's to choose and are not zero.              */
/*                                                                        */
/*    What the machine holds when this is called IS the reset state --     */
/*    ZoneX's own reset path has cleared SCTLR.M, .TE, .C and .I and       */
/*    touched nothing else at EL1 -- so snapshotting it gives every fresh  */
/*    partition exactly the EL1 the single-partition images hand their     */
/*    guest.  Two partitions then start identically, which is also what    */
/*    makes their later divergence attributable to the schedule.           */
/*                                                                        */
/*    The REGISTERS are zeroed over the top of that snapshot, because a    */
/*    guest's banked stack pointers are its own reset path's to set and    */
/*    inheriting the hypervisor's idea of them would be worse than         */
/*    inheriting nothing.                                                  */
/*                                                                        */
/*    THE MASKS IN SPSR ARE THE ONES A RESET PATH EXPECTS.  A, I and F     */
/*    set, SVC mode, exactly as zx_el2_run_payload hands a payload the     */
/*    machine -- a kernel opens its own interrupts when it has vectors     */
/*    for them.  PSTATE.T is left CLEAR, because the entry point is the    */
/*    A32 branch at a fixed offset in the window; a guest that switches    */
/*    to T32 later carries the T bit back in its own saved SPSR and this   */
/*    file never has to know.                                              */
/*                                                                        */
/*    F IS SET AND IT NO LONGER MEANS ANYTHING, which is the point of the  */
/*    design: with HCR.FMO set, PSTATE.F is IGNORED at EL0 and EL1.  It is */
/*    written anyway so that the value a partition starts with is the      */
/*    value it would have had, rather than one chosen to depend on a       */
/*    hypervisor configuration bit.                                        */
/*                                                                        */
/**************************************************************************/

void zx_context_init(ZX_GUEST_CONTEXT *context_ptr, zx_addr_t entry)
{
    uint32_t index;

    if (context_ptr == (ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    /* The EL1 reset state, as the machine holds it right now.  Everything
       below overwrites the parts a fresh guest owns and leaves the rest --
       the system registers whose reset values are the part's.  */

    zx_context_save(context_ptr);

    for (index = 0U; index < 13U; index++)
    {
        context_ptr->zx_ctx_r[index] = 0U;
    }

    for (index = 0U; index < 5U; index++)
    {
        context_ptr->zx_ctx_r_fiq[index] = 0U;
    }

    context_ptr->zx_ctx_elr  = (uint32_t)entry;
    context_ptr->zx_ctx_spsr = ZX_PSR_A | ZX_PSR_I | ZX_PSR_F | ZX_MODE_SVC;

    context_ptr->zx_ctx_sp_usr    = 0U;
    context_ptr->zx_ctx_lr_usr    = 0U;
    context_ptr->zx_ctx_sp_svc    = 0U;
    context_ptr->zx_ctx_lr_svc    = 0U;
    context_ptr->zx_ctx_spsr_svc  = 0U;
    context_ptr->zx_ctx_sp_irq    = 0U;
    context_ptr->zx_ctx_lr_irq    = 0U;
    context_ptr->zx_ctx_spsr_irq  = 0U;
    context_ptr->zx_ctx_sp_abt    = 0U;
    context_ptr->zx_ctx_lr_abt    = 0U;
    context_ptr->zx_ctx_spsr_abt  = 0U;
    context_ptr->zx_ctx_sp_und    = 0U;
    context_ptr->zx_ctx_lr_und    = 0U;
    context_ptr->zx_ctx_spsr_und  = 0U;
    context_ptr->zx_ctx_sp_fiq    = 0U;
    context_ptr->zx_ctx_lr_fiq    = 0U;
    context_ptr->zx_ctx_spsr_fiq  = 0U;

    /* SCTLR, CPACR, MAIR, AMAIR, TPIDR*, CONTEXTIDR, PRSELR and the whole
       EL1 MPU come from the snapshot above and are deliberately NOT
       overwritten here.  See the note on RES1 bits in this function's
       description; the short version is that zero is not a reset value.

       The TIMER is zeroed, because it is the one piece of EL1 state a
       fresh partition must not inherit: an armed comparator belongs to
       whoever armed it, and a guest re-entered with somebody else's
       deadline takes a tick it never scheduled as its first act.  */

    context_ptr->zx_ctx_cntv_ctl   = 0U;
    context_ptr->zx_ctx_cntv_cval  = 0U;

    context_ptr->zx_ctx_cntvoff        = 0U;
    context_ptr->zx_ctx_suspended_at   = 0U;
    context_ptr->zx_ctx_resumed_at     = 0U;
    context_ptr->zx_ctx_virtual_at_stop = 0U;
    context_ptr->zx_ctx_time_on_core   = 0U;

    context_ptr->zx_ctx_entries     = 0U;
    context_ptr->zx_ctx_preemptions = 0U;
    context_ptr->zx_ctx_started     = 0U;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_context_save                                      Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Everything a partition owns that the vector did not have to take.   */
/*                                                                        */
/*    THE ORDER IS SMALLEST-FIRST AND IT IS NOT ARBITRARY.  The banked     */
/*    registers and the system registers are a fixed handful; the EL1 MPU  */
/*    is twenty regions and dominates.  Putting the MPU last means the      */
/*    breakdown a measurement wants -- "how much of the switch is the      */
/*    region set" -- is the difference between two counter readings taken  */
/*    around one contiguous block, rather than a sum of fragments.         */
/*                                                                        */
/*    THE GUEST'S TIMER IS SAVED AND THEN STOPPED, in that order, and      */
/*    both halves matter.  Saved, because CNTV_CVAL is a deadline in the   */
/*    partition's OWN time and a switch that dropped it would hand the     */
/*    next partition this one's deadline.  Stopped, because the generic    */
/*    timer asserts a LEVEL: a comparator left armed and expired holds the */
/*    PPI asserted at the GIC, and INTID 27 is the same INTID the next     */
/*    partition is about to be given.  The incoming partition would take   */
/*    an interrupt its own kernel never armed, at an instant it did not    */
/*    choose, and would service it perfectly correctly.                    */
/*                                                                        */
/**************************************************************************/

void zx_context_save(ZX_GUEST_CONTEXT *context_ptr)
{
    uint32_t control;
    uint32_t low;
    uint32_t high;

    if (context_ptr == (ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    /* ---- banked SPs, LRs and SPSRs ---------------------------------- */

    ZX_SAVE_BANKED(zx_ctx_sp_usr,   SP_usr);
    ZX_SAVE_BANKED(zx_ctx_lr_usr,   LR_usr);
    ZX_SAVE_BANKED(zx_ctx_sp_svc,   SP_svc);
    ZX_SAVE_BANKED(zx_ctx_lr_svc,   LR_svc);
    ZX_SAVE_BANKED(zx_ctx_spsr_svc, SPSR_svc);
    ZX_SAVE_BANKED(zx_ctx_sp_irq,   SP_irq);
    ZX_SAVE_BANKED(zx_ctx_lr_irq,   LR_irq);
    ZX_SAVE_BANKED(zx_ctx_spsr_irq, SPSR_irq);
    ZX_SAVE_BANKED(zx_ctx_sp_abt,   SP_abt);
    ZX_SAVE_BANKED(zx_ctx_lr_abt,   LR_abt);
    ZX_SAVE_BANKED(zx_ctx_spsr_abt, SPSR_abt);
    ZX_SAVE_BANKED(zx_ctx_sp_und,   SP_und);
    ZX_SAVE_BANKED(zx_ctx_lr_und,   LR_und);
    ZX_SAVE_BANKED(zx_ctx_spsr_und, SPSR_und);
    ZX_SAVE_BANKED(zx_ctx_sp_fiq,   SP_fiq);
    ZX_SAVE_BANKED(zx_ctx_lr_fiq,   LR_fiq);
    ZX_SAVE_BANKED(zx_ctx_spsr_fiq, SPSR_fiq);

    /* FIQ MODE BANKS r8 TO r12 AS WELL, and they are the registers most
       easily forgotten because every other mode shares them.  A partition
       whose kernel takes an FIQ would be using them -- and a partition here
       cannot take one, because Group 0 goes to EL2 and a guest is granted
       nothing in it.  They are saved anyway: "the guest cannot be using
       these" is a claim about a hypervisor configuration bit, and a context
       switch that is correct only while one bit stays set is a trap for
       whoever changes it.  */

    ZX_SAVE_BANKED(zx_ctx_r_fiq[0], R8_fiq);
    ZX_SAVE_BANKED(zx_ctx_r_fiq[1], R9_fiq);
    ZX_SAVE_BANKED(zx_ctx_r_fiq[2], R10_fiq);
    ZX_SAVE_BANKED(zx_ctx_r_fiq[3], R11_fiq);
    ZX_SAVE_BANKED(zx_ctx_r_fiq[4], R12_fiq);

    /* ---- EL1 system registers --------------------------------------- */

    __asm__ volatile("mrc p15, 0, %0, c1, c0, 0"
                     : "=r"(context_ptr->zx_ctx_sctlr));      /* SCTLR     */
    __asm__ volatile("mrc p15, 0, %0, c12, c0, 0"
                     : "=r"(context_ptr->zx_ctx_vbar));       /* VBAR      */
    __asm__ volatile("mrc p15, 0, %0, c1, c0, 2"
                     : "=r"(context_ptr->zx_ctx_cpacr));      /* CPACR     */
    __asm__ volatile("mrc p15, 0, %0, c13, c0, 1"
                     : "=r"(context_ptr->zx_ctx_contextidr));
    __asm__ volatile("mrc p15, 0, %0, c13, c0, 2"
                     : "=r"(context_ptr->zx_ctx_tpidrurw));
    __asm__ volatile("mrc p15, 0, %0, c13, c0, 3"
                     : "=r"(context_ptr->zx_ctx_tpidruro));
    __asm__ volatile("mrc p15, 0, %0, c13, c0, 4"
                     : "=r"(context_ptr->zx_ctx_tpidrprw));
    __asm__ volatile("mrc p15, 0, %0, c10, c2, 0"
                     : "=r"(context_ptr->zx_ctx_mair0));
    __asm__ volatile("mrc p15, 0, %0, c10, c2, 1"
                     : "=r"(context_ptr->zx_ctx_mair1));
    __asm__ volatile("mrc p15, 0, %0, c10, c3, 0"
                     : "=r"(context_ptr->zx_ctx_amair0));
    __asm__ volatile("mrc p15, 0, %0, c10, c3, 1"
                     : "=r"(context_ptr->zx_ctx_amair1));

    /* ---- the guest's own virtual timer ------------------------------ */

    __asm__ volatile("mrc p15, 0, %0, c14, c3, 1" : "=r"(control));
    __asm__ volatile("mrrc p15, 3, %0, %1, c14"
                     : "=r"(low), "=r"(high));                /* CNTV_CVAL */

    context_ptr->zx_ctx_cntv_ctl  = control;
    context_ptr->zx_ctx_cntv_cval = ((uint64_t)high << 32) | (uint64_t)low;

    /* And DISARMED, both bits, before the next partition can inherit an
       asserted level on the INTID it is about to be given.  */

    control &= ~(uint32_t)(ZX_CNTV_CTL_ENABLE | ZX_CNTV_CTL_IMASK);
    __asm__ volatile("mcr p15, 0, %0, c14, c3, 1"
                     : : "r"(control) : "memory");
    __asm__ volatile("isb" ::: "memory");

    /* ---- the EL1 MPU: the dominant cost ----------------------------- */

    zx_context_save_mpu(context_ptr);
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_context_save_mpu                                  Cortex-R52     */
/*    zx_context_restore_mpu                                             */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The EL1 MPU region set, on its own.                                 */
/*                                                                        */
/*    SEPARATE FUNCTIONS BECAUSE THE MEASUREMENT NEEDS THEM SEPARATE.     */
/*    "How much of a partition switch is the guest's MPU" is the question */
/*    this step exists to answer, and the honest way to answer it is to   */
/*    time the same code the switch runs rather than a copy of it written */
/*    for the measurement.  A second loop maintained beside the first     */
/*    would agree until the day it did not, and the day it did not is the */
/*    day the published number stops describing the shipped switch.       */
/*                                                                        */
/*    The cost of the split is one call each way on the switch path.  It  */
/*    is included in every figure this suite prints, because it is        */
/*    included in every switch it performs.                                */
/*                                                                        */
/*    TWENTY REGIONS ON THE S32Z280, TWO REGISTERS EACH, selected through */
/*    a third.  The trip count comes from MPUIR, read once at boot, so it */
/*    depends on the PART and never on anything a guest did.              */
/*                                                                        */
/**************************************************************************/

void zx_context_save_mpu(ZX_GUEST_CONTEXT *context_ptr)
{
    uint32_t index;

    __asm__ volatile("mrc p15, 0, %0, c6, c2, 1"
                     : "=r"(context_ptr->zx_ctx_prselr));     /* PRSELR    */

    for (index = 0U; index < zx_el1_regions; index++)
    {
        __asm__ volatile("mcr p15, 0, %0, c6, c2, 1"
                         : : "r"(index) : "memory");
        __asm__ volatile("isb");
        __asm__ volatile("mrc p15, 0, %0, c6, c3, 0"
                         : "=r"(context_ptr->zx_ctx_prbar[index]));
        __asm__ volatile("mrc p15, 0, %0, c6, c3, 1"
                         : "=r"(context_ptr->zx_ctx_prlar[index]));
    }
}


void zx_context_restore_mpu(const ZX_GUEST_CONTEXT *context_ptr)
{
    uint32_t index;

    for (index = 0U; index < zx_el1_regions; index++)
    {
        __asm__ volatile("mcr p15, 0, %0, c6, c2, 1"
                         : : "r"(index) : "memory");
        __asm__ volatile("isb");
        __asm__ volatile("mcr p15, 0, %0, c6, c3, 0"
                         : : "r"(context_ptr->zx_ctx_prbar[index])
                         : "memory");
        __asm__ volatile("mcr p15, 0, %0, c6, c3, 1"
                         : : "r"(context_ptr->zx_ctx_prlar[index])
                         : "memory");
    }

    __asm__ volatile("mcr p15, 0, %0, c6, c2, 1"
                     : : "r"(context_ptr->zx_ctx_prselr) : "memory");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_context_restore                                   Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The mirror, and the ORDER IS NOT THE MIRROR.                        */
/*                                                                        */
/*    The EL1 MPU regions go back BEFORE SCTLR, so that the bit which      */
/*    turns the guest's own MPU on is written when the regions it governs  */
/*    are already the incoming partition's.  Written the other way round   */
/*    there is a window in which stage 1 is enabled over the OUTGOING      */
/*    partition's region set -- harmless today, because no EL1 access      */
/*    happens between here and the ERET, and exactly the kind of ordering  */
/*    that stops being harmless when somebody adds one.                    */
/*                                                                        */
/*    ONE BARRIER PAIR, AT THE END, NOT ONE PER REGION.  The barriers      */
/*    dominate: the Cortex-R52 Modules port work measured 434-470 cycles   */
/*    for a region written directly at EL1 with its own barriers, and most */
/*    of that was the closing DSB/ISB rather than the write.  Forty region */
/*    writes with forty barrier pairs would be forty times a cost that     */
/*    only has to be paid once, because nothing between the first write    */
/*    and the ERET depends on the new permissions.  The ISB before the     */
/*    ERET is what makes them take effect, and there is exactly one.       */
/*                                                                        */
/*    The PRSELR write inside the loop is different and does need its ISB: */
/*    the very next instruction reads PRBAR THROUGH it, so the selection   */
/*    has to be in effect.  That is a dependency within the loop, not a    */
/*    dependency on the region set, and it is the one barrier that cannot  */
/*    be hoisted out.                                                     */
/*                                                                        */
/**************************************************************************/

void zx_context_restore(const ZX_GUEST_CONTEXT *context_ptr)
{
    uint32_t low;
    uint32_t high;

    if (context_ptr == (const ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    /* ---- the EL1 MPU, first ----------------------------------------- */

    zx_context_restore_mpu(context_ptr);

    /* ---- EL1 system registers --------------------------------------- */

    __asm__ volatile("mcr p15, 0, %0, c12, c0, 0"
                     : : "r"(context_ptr->zx_ctx_vbar) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c1, c0, 2"
                     : : "r"(context_ptr->zx_ctx_cpacr) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c13, c0, 1"
                     : : "r"(context_ptr->zx_ctx_contextidr) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c13, c0, 2"
                     : : "r"(context_ptr->zx_ctx_tpidrurw) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c13, c0, 3"
                     : : "r"(context_ptr->zx_ctx_tpidruro) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c13, c0, 4"
                     : : "r"(context_ptr->zx_ctx_tpidrprw) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c10, c2, 0"
                     : : "r"(context_ptr->zx_ctx_mair0) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c10, c2, 1"
                     : : "r"(context_ptr->zx_ctx_mair1) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c10, c3, 0"
                     : : "r"(context_ptr->zx_ctx_amair0) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c10, c3, 1"
                     : : "r"(context_ptr->zx_ctx_amair1) : "memory");

    /* SCTLR LAST of the system registers, because it carries M -- the bit
       that makes every region written above start being consulted.  */

    __asm__ volatile("mcr p15, 0, %0, c1, c0, 0"
                     : : "r"(context_ptr->zx_ctx_sctlr) : "memory");

    /* ---- banked SPs, LRs and SPSRs ---------------------------------- */

    ZX_LOAD_BANKED(zx_ctx_sp_usr,   SP_usr);
    ZX_LOAD_BANKED(zx_ctx_lr_usr,   LR_usr);
    ZX_LOAD_BANKED(zx_ctx_sp_svc,   SP_svc);
    ZX_LOAD_BANKED(zx_ctx_lr_svc,   LR_svc);
    ZX_LOAD_BANKED(zx_ctx_spsr_svc, SPSR_svc);
    ZX_LOAD_BANKED(zx_ctx_sp_irq,   SP_irq);
    ZX_LOAD_BANKED(zx_ctx_lr_irq,   LR_irq);
    ZX_LOAD_BANKED(zx_ctx_spsr_irq, SPSR_irq);
    ZX_LOAD_BANKED(zx_ctx_sp_abt,   SP_abt);
    ZX_LOAD_BANKED(zx_ctx_lr_abt,   LR_abt);
    ZX_LOAD_BANKED(zx_ctx_spsr_abt, SPSR_abt);
    ZX_LOAD_BANKED(zx_ctx_sp_und,   SP_und);
    ZX_LOAD_BANKED(zx_ctx_lr_und,   LR_und);
    ZX_LOAD_BANKED(zx_ctx_spsr_und, SPSR_und);
    ZX_LOAD_BANKED(zx_ctx_sp_fiq,   SP_fiq);
    ZX_LOAD_BANKED(zx_ctx_lr_fiq,   LR_fiq);
    ZX_LOAD_BANKED(zx_ctx_spsr_fiq, SPSR_fiq);
    ZX_LOAD_BANKED(zx_ctx_r_fiq[0], R8_fiq);
    ZX_LOAD_BANKED(zx_ctx_r_fiq[1], R9_fiq);
    ZX_LOAD_BANKED(zx_ctx_r_fiq[2], R10_fiq);
    ZX_LOAD_BANKED(zx_ctx_r_fiq[3], R11_fiq);
    ZX_LOAD_BANKED(zx_ctx_r_fiq[4], R12_fiq);

    /* ---- and the guest's own virtual timer, LAST -------------------- */

    /* THE COMPARATOR BEFORE THE CONTROL, because writing CNTV_CTL.ENABLE
       is what makes the comparison start being made.  Written the other
       way round, the timer is enabled for the few cycles it takes to write
       CVAL while the comparator still holds the OUTGOING partition's
       deadline -- which is in this partition's past, so the level asserts,
       and the incoming guest takes a tick before its own deadline as its
       first act.  */

    low  = (uint32_t)(context_ptr->zx_ctx_cntv_cval & 0xFFFFFFFFU);
    high = (uint32_t)(context_ptr->zx_ctx_cntv_cval >> 32);

    __asm__ volatile("mcrr p15, 3, %0, %1, c14"
                     : : "r"(low), "r"(high) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c14, c3, 1"
                     : : "r"(context_ptr->zx_ctx_cntv_ctl) : "memory");

    /* ONE barrier pair, for everything above.  See the note in the block
       comment: the ISB is what lets the ERET's target be fetched under the
       incoming partition's permissions.  */

    __asm__ volatile("dsb" ::: "memory");
    __asm__ volatile("isb" ::: "memory");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_context_time_reset                                Cortex-R52     */
/*    zx_context_time_suspend                                            */
/*    zx_context_time_resume                                             */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    CNTVOFF, PER PARTITION, which is the whole of temporal partitioning  */
/*    as a partition can observe it.                                      */
/*                                                                        */
/*    A partition reads time through the virtual counter, which is the     */
/*    physical one MINUS CNTVOFF, and CNTVOFF is writable only at EL2.     */
/*    With one partition the gap being closed was the hypervisor's own     */
/*    work between two excursions.  With two it is THE OTHER PARTITION'S   */
/*    WINDOW, and that is what makes the two clocks independent rather     */
/*    than merely offset: each partition's own time advances by exactly    */
/*    the counts it spent on the core and by none of the counts it did     */
/*    not.                                                                */
/*                                                                        */
/*    THE OFFSET IS IN THE CONTEXT BLOCK AND NOT IN A REGISTER BETWEEN     */
/*    WINDOWS.  There is one CNTVOFF and there are several partitions, so  */
/*    the register holds the running partition's value and the others'     */
/*    live here.  suspend takes it out, resume puts it back with the       */
/*    elapsed interval added.                                             */
/*                                                                        */
/*    WHERE THE MEASUREMENT HAS TO BE TAKEN, because the obvious place is  */
/*    wrong.  CNTVOFF is a STATIC offset: while a partition is suspended   */
/*    the physical counter moves and the offset does not, so the           */
/*    subtraction drifts for exactly as long as the partition is away.     */
/*    What closes the gap is the write on RESUME.  Sampling the virtual    */
/*    counter anywhere in between measures the drift and not the           */
/*    correction, and looks precisely like a broken freeze.  The two       */
/*    instants recorded below are the ones the MECHANISM took, so a check  */
/*    built from them is not measuring the cost of measuring -- which on   */
/*    the S32Z280 is 93 counts of real time per handful of CNTPCT reads.   */
/*                                                                        */
/**************************************************************************/

static uint64_t zx_read_cntvoff_reg(void)
{
    uint32_t low;
    uint32_t high;

    __asm__ volatile("mrrc p15, 4, %0, %1, c14" : "=r"(low), "=r"(high));

    return ((uint64_t)high << 32) | (uint64_t)low;
}


static void zx_write_cntvoff_reg(uint64_t value)
{
    uint32_t low  = (uint32_t)(value & 0xFFFFFFFFU);
    uint32_t high = (uint32_t)(value >> 32);

    __asm__ volatile("mcrr p15, 4, %0, %1, c14"
                     : : "r"(low), "r"(high) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


void zx_context_time_reset(ZX_GUEST_CONTEXT *context_ptr)
{
    uint64_t now;

    if (context_ptr == (ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    now = zx_read_cntpct();

    /* Its own clock starts at zero, which is what makes two runs of one
       guest comparable at all: a partition whose time began wherever the
       board's counter happened to be would report a different number every
       power cycle.  */

    context_ptr->zx_ctx_cntvoff         = now;
    context_ptr->zx_ctx_suspended_at    = now;
    context_ptr->zx_ctx_resumed_at      = now;
    context_ptr->zx_ctx_virtual_at_stop = 0U;
    context_ptr->zx_ctx_time_on_core    = 0U;

    /* AND THE FREEZE IS ON, established HERE rather than left to the
       caller.  Every image calls this; an image that had to remember to
       switch the freeze on would be an image that could forget, and a
       forgotten freeze is a partition that can see its neighbour's time
       while every other check in the suite stays green.  The one build
       that wants it off clears the field after this returns, deliberately
       and visibly.  */

    context_ptr->zx_ctx_credit_time     = 1U;
}


void zx_context_time_suspend(ZX_GUEST_CONTEXT *context_ptr)
{
    uint64_t now;
    uint64_t offset;

    if (context_ptr == (ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    now    = zx_read_cntpct();
    offset = zx_read_cntvoff_reg();

    context_ptr->zx_ctx_cntvoff         = offset;
    context_ptr->zx_ctx_suspended_at    = now;
    context_ptr->zx_ctx_virtual_at_stop = now - offset;

    /* HOW LONG THIS PARTITION HAS ACTUALLY HAD THE CORE, accumulated across
       every window it has been given.  It is the number the whole temporal
       claim reduces to: a guest's own clock must equal this and nothing
       else, and a guest that can see a larger number has seen its
       neighbour's time.  Accumulated here because this is the only place
       that knows both ends of a window.  */

    if (now > context_ptr->zx_ctx_resumed_at)
    {
        context_ptr->zx_ctx_time_on_core +=
            now - context_ptr->zx_ctx_resumed_at;
    }
}


void zx_context_time_resume(ZX_GUEST_CONTEXT *context_ptr)
{
    uint64_t now;
    uint64_t offset;

    if (context_ptr == (ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    now    = zx_read_cntpct();
    offset = context_ptr->zx_ctx_cntvoff;

    /* The elapsed interval is ADDED rather than the offset being recomputed,
       because "how much time has this partition been given" is cumulative.
       Recomputing it would silently reset the partition's clock on every
       entry -- which looks exactly like a working freeze and is in fact a
       partition whose time never advances at all.  */

    if ((context_ptr->zx_ctx_credit_time != 0U)
        && (now > context_ptr->zx_ctx_suspended_at))
    {
        offset += now - context_ptr->zx_ctx_suspended_at;
    }

    zx_write_cntvoff_reg(offset);

    context_ptr->zx_ctx_cntvoff     = offset;
    context_ptr->zx_ctx_resumed_at  = now;
    context_ptr->zx_ctx_suspended_at = now;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_context_report                                    Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    One partition's context, printed.                                   */
/*                                                                        */
/*    The entry and preemption counts are the pair that says what          */
/*    happened without a log to read: a partition entered eight times and  */
/*    preempted eight times ran out its window every time, and one         */
/*    entered eight times and preempted twice yielded six of them.  Those  */
/*    are different systems and a single "it ran" would call them the      */
/*    same.                                                               */
/*                                                                        */
/**************************************************************************/

void zx_context_report(const ZX_GUEST_CONTEXT *context_ptr,
                       const char *name_ptr)
{
    if (context_ptr == (const ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    zx_console_puts("  context: ");
    zx_console_puts((name_ptr != (const char *)0) ? name_ptr : "(unnamed)");
    zx_console_puts("\n");

    zx_console_puts("    entries ");
    zx_console_putdec(context_ptr->zx_ctx_entries);
    zx_console_puts(", preempted at a boundary ");
    zx_console_putdec(context_ptr->zx_ctx_preemptions);
    zx_console_puts("\n");

    zx_console_puts("    resumed at PC ");
    zx_console_puthex(context_ptr->zx_ctx_elr);
    zx_console_puts(", SPSR ");
    zx_console_puthex(context_ptr->zx_ctx_spsr);
    zx_console_puts("\n");

    zx_console_puts("    CNTVOFF ");
    zx_console_puthex((uint32_t)(context_ptr->zx_ctx_cntvoff & 0xFFFFFFFFU));
    zx_console_puts(", counts on the core ");
    zx_console_putdec((uint32_t)(context_ptr->zx_ctx_time_on_core
                                 & 0xFFFFFFFFU));
    zx_console_puts("\n");

    zx_console_puts("    its own clock when last stopped ");
    zx_console_putdec((uint32_t)(context_ptr->zx_ctx_virtual_at_stop
                                 & 0xFFFFFFFFU));
    zx_console_puts("\n");

    if (context_ptr->zx_ctx_violations != 0U)
    {
        zx_console_puts("    stage-2 violations it was RESUMED past ");
        zx_console_putdec(context_ptr->zx_ctx_violations);
        zx_console_puts("\n");
    }

    if (context_ptr->zx_ctx_period_samples != 0U)
    {
        zx_console_puts("    window period, counts: min ");
        zx_console_putdec((uint32_t)(context_ptr->zx_ctx_period_min
                                     & 0xFFFFFFFFU));
        zx_console_puts(" mean ");
        zx_console_putdec((uint32_t)(zx_context_period_mean(context_ptr)
                                     & 0xFFFFFFFFU));
        zx_console_puts(" max ");
        zx_console_putdec((uint32_t)(context_ptr->zx_ctx_period_max
                                     & 0xFFFFFFFFU));
        zx_console_puts(" over ");
        zx_console_putdec(context_ptr->zx_ctx_period_samples);
        zx_console_puts(" periods\n");
    }
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_context_period_note                               Cortex-R52     */
/*    zx_context_period_reset                                             */
/*    zx_context_period_mean                                              */
/*    zx_context_period_jitter                                            */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    How often a partition's window came round, from the timestamps the   */
/*    switch already takes.  The rationale is beside the fields in         */
/*    zx_port.h; two properties are worth restating where they are         */
/*    implemented.                                                        */
/*                                                                        */
/*    THE FIRST ENTRY YIELDS NO PERIOD, and it must not be allowed to.  A  */
/*    partition's first window has no predecessor, so the difference       */
/*    against zx_ctx_period_prev would be the interval since the CONTEXT   */
/*    WAS INITIALISED -- a number with no meaning that is smaller than a   */
/*    real period and would therefore become the minimum, and the reported */
/*    jitter would be a whole frame wide on every run.  The sample count   */
/*    guards it.                                                          */
/*                                                                        */
/*    AND THE JITTER OF ONE SAMPLE IS ZERO RATHER THAN max - min.  With    */
/*    one period recorded the min and the max are the same reading, and    */
/*    reporting their difference as "no jitter" would be the most          */
/*    flattering possible description of a run too short to say anything.  */
/*    Zero samples and one sample both report zero, and the sample count   */
/*    is printed next to it so that a reader can tell which.              */
/*                                                                        */
/**************************************************************************/

void zx_context_period_note(ZX_GUEST_CONTEXT *context_ptr, uint64_t now)
{
    if (context_ptr == (ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    if (context_ptr->zx_ctx_period_prev != 0U)
    {
        uint64_t period = now - context_ptr->zx_ctx_period_prev;

        if ((context_ptr->zx_ctx_period_samples == 0U)
            || (period < context_ptr->zx_ctx_period_min))
        {
            context_ptr->zx_ctx_period_min = period;
        }

        if (period > context_ptr->zx_ctx_period_max)
        {
            context_ptr->zx_ctx_period_max = period;
        }

        context_ptr->zx_ctx_period_total += period;
        context_ptr->zx_ctx_period_samples++;
    }

    context_ptr->zx_ctx_period_prev = now;
}


void zx_context_period_reset(ZX_GUEST_CONTEXT *context_ptr)
{
    if (context_ptr == (ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    /* THE PREVIOUS TIMESTAMP GOES WITH THEM, so that the next period
       measured begins a fresh chain and every sample a phase records lies
       entirely inside it.  See zx_port.h for why the first version of this
       kept it and why that was backwards: an absolute-deadline schedule
       answers one late entry with one short correction, and keeping the
       timestamp put the correction in the following phase.  */

    context_ptr->zx_ctx_period_prev    = 0U;

    context_ptr->zx_ctx_period_min     = 0U;
    context_ptr->zx_ctx_period_max     = 0U;
    context_ptr->zx_ctx_period_total   = 0U;
    context_ptr->zx_ctx_period_samples = 0U;
}


uint64_t zx_context_period_mean(const ZX_GUEST_CONTEXT *context_ptr)
{
    uint64_t mean = 0U;

    if ((context_ptr != (const ZX_GUEST_CONTEXT *)0)
        && (context_ptr->zx_ctx_period_samples != 0U))
    {
        mean = context_ptr->zx_ctx_period_total
               / (uint64_t)context_ptr->zx_ctx_period_samples;
    }

    return mean;
}


uint64_t zx_context_period_jitter(const ZX_GUEST_CONTEXT *context_ptr)
{
    uint64_t jitter = 0U;

    if ((context_ptr != (const ZX_GUEST_CONTEXT *)0)
        && (context_ptr->zx_ctx_period_samples > 1U))
    {
        jitter = context_ptr->zx_ctx_period_max
                 - context_ptr->zx_ctx_period_min;
    }

    return jitter;
}
