/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_el2_cpu.c                                         Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The CP15 identity and capability reads, and the objects the EL2      */
/*    assembly and the C code share.                                      */
/*                                                                        */
/*    Every accessor here is one MRC and nothing else.  They are           */
/*    deliberately not macros: a macro that pastes an encoding is a        */
/*    macro whose expansion nobody reads, and the encodings are the one    */
/*    thing in this port that must be checkable against                    */
/*    docs/armv8r-el2-reference.md line by line.  Each carries its         */
/*    CRn, opc1, CRm, opc2 in the comment beside it for exactly that.      */
/*                                                                        */
/*    Two register-count details are wrong once and then copied for ever,  */
/*    so they are separated into named functions rather than left at       */
/*    their call sites: the EL1 count lives in MPUIR[15:8] and the EL2     */
/*    count in HMPUIR[7:0].  Different registers, different fields.        */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                    */
/*                                                                        */
/*    Directive 4.3 (assembly shall be encapsulated and isolated) --       */
/*      observed rather than violated: every asm statement in this file is */
/*      alone in a function that does nothing else.                        */
/*    Rule 1.1 / 1.2 (language extensions) -- inline assembly is the only  */
/*      way to reach a coprocessor register; no standard C construct       */
/*      expresses MRC.                                                     */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"

/**************************************************************************/
/*                     Objects shared with the assembly                   */
/**************************************************************************/

/* Written by zx_trap_handler.S, at the ZX_ASM_FAULT_OFF_* offsets, before
   anything else runs after an exception.  Read by zx_fault_report.  */

zx_fault_record_t zx_el2_fault_storage;

/* Incremented by the HVC #0 path in zx_trap_handler.S.  */

uint32_t zx_el2_hypercall_counter;

/* Written once by zx_el2_entry.S, from registers, before .bss is zeroed --
   which is why these live in .data and are not merely uninitialised.  Zero
   would be a plausible reading of every one of them, so a value that never
   arrived must not look like a value that did.  */

uint32_t zx_reset_hsctlr = 0xFFFFFFFFU;
uint32_t zx_reset_sctlr  = 0xFFFFFFFFU;
uint32_t zx_reset_cpsr   = 0xFFFFFFFFU;
uint32_t zx_reset_hprenr = 0xFFFFFFFFU;

/* Not 0xFFFFFFFF as its unwritten value: all-ones is a PLAUSIBLE answer here
   -- it is what a 32-region implementation reports -- so a value that never
   arrived must not look like one that did.  0xDEADBEEF cannot be mistaken for
   a set of implemented enable bits.  */

uint32_t zx_hprenr_implemented_bits = 0xDEADBEEFU;

/**************************************************************************/
/*                     Identity and capability registers                  */
/**************************************************************************/

uint32_t zx_read_midr(void)
{
    uint32_t value;

    /* MIDR: p15, 0, c0, c0, 0 */
    __asm__ volatile("mrc p15, 0, %0, c0, c0, 0" : "=r"(value));

    return value;
}


uint32_t zx_read_mpidr(void)
{
    uint32_t value;

    /* MPIDR: p15, 0, c0, c0, 5 */
    __asm__ volatile("mrc p15, 0, %0, c0, c0, 5" : "=r"(value));

    return value;
}


uint32_t zx_read_cntfrq(void)
{
    uint32_t value;

    /* CNTFRQ: p15, 0, c14, c0, 0 */
    __asm__ volatile("mrc p15, 0, %0, c14, c0, 0" : "=r"(value));

    return value;
}


uint32_t zx_read_mpuir(void)
{
    uint32_t value;

    /* MPUIR: p15, 0, c0, c0, 4 */
    __asm__ volatile("mrc p15, 0, %0, c0, c0, 4" : "=r"(value));

    return value;
}


uint32_t zx_read_hmpuir(void)
{
    uint32_t value;

    /* HMPUIR: p15, 4, c0, c0, 4 */
    __asm__ volatile("mrc p15, 4, %0, c0, c0, 4" : "=r"(value));

    return value;
}


uint32_t zx_read_hsctlr(void)
{
    uint32_t value;

    /* HSCTLR: p15, 4, c1, c0, 0 */
    __asm__ volatile("mrc p15, 4, %0, c1, c0, 0" : "=r"(value));

    return value;
}


uint32_t zx_read_hcr(void)
{
    uint32_t value;

    /* HCR: p15, 4, c1, c1, 0 */
    __asm__ volatile("mrc p15, 4, %0, c1, c1, 0" : "=r"(value));

    return value;
}


uint32_t zx_read_hsr(void)
{
    uint32_t value;

    /* HSR: p15, 4, c5, c2, 0 */
    __asm__ volatile("mrc p15, 4, %0, c5, c2, 0" : "=r"(value));

    return value;
}


uint32_t zx_read_hvbar(void)
{
    uint32_t value;

    /* HVBAR: p15, 4, c12, c0, 0 */
    __asm__ volatile("mrc p15, 4, %0, c12, c0, 0" : "=r"(value));

    return value;
}


uint32_t zx_read_ich_vtr(void)
{
    uint32_t value;

    /* ICH_VTR: p15, 4, c12, c11, 1.  ListRegs is bits [4:0], and holds the
       number of List Registers MINUS ONE -- the Cortex-R52 resets it to
       0x90180003, which is four registers, ICH_LR0 to ICH_LR3.  Recorded
       because interrupt injection being AVAILABLE on this part corrects an
       assumption the roadmap carried; see docs/armv8r-el2-reference.md.  */
    __asm__ volatile("mrc p15, 4, %0, c12, c11, 1" : "=r"(value));

    return value;
}


uint32_t zx_read_cpsr(void)
{
    uint32_t value;

    __asm__ volatile("mrs %0, cpsr" : "=r"(value));

    return value;
}


/**************************************************************************/
/*  zx_el1_region_count -- MPUIR[15:8].                                   */
/**************************************************************************/

uint32_t zx_el1_region_count(void)
{
    return (zx_read_mpuir() >> 8U) & 0xFFU;
}


/**************************************************************************/
/*  zx_el2_region_count -- HMPUIR[7:0].                                   */
/*                                                                        */
/*  NOT [15:8].  The two type registers keep their counts in different    */
/*  fields, and reading HMPUIR the way MPUIR is read gives zero -- which   */
/*  is a LEGAL value meaning "no EL2-controlled MPU regions", so the       */
/*  mistake produces a believable answer rather than an obvious one.       */
/**************************************************************************/

uint32_t zx_el2_region_count(void)
{
    return zx_read_hmpuir() & 0xFFU;
}


/**************************************************************************/
/*  zx_el2_region_count_is_legal                                          */
/*                                                                        */
/*  TRM Table 3-79 permits 0, 16, 20 or 24 and nothing else.  The Armv8-R  */
/*  AEM FVP reports 32, which no Cortex-R52 can have, so this returning    */
/*  false is an EXPECTED outcome on the model rather than a broken read.   */
/*  What matters is that it is said out loud: a green model run proves     */
/*  nothing about any real part's region budget.                           */
/**************************************************************************/

uint32_t zx_el2_region_count_is_legal(uint32_t count)
{
    return ((count == 0U) || (count == 16U) || (count == 20U)
            || (count == 24U)) ? 1U : 0U;
}


/**************************************************************************/
/*  zx_el2_fault_record / zx_el2_hypercall_count                          */
/**************************************************************************/

zx_fault_record_t *zx_el2_fault_record(void)
{
    return &zx_el2_fault_storage;
}


uint32_t zx_el2_hypercall_count(void)
{
    return zx_el2_hypercall_counter;
}
