/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_el2_fault_path.c                                  Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Where the vectors that cannot be resumed end up.                    */
/*                                                                        */
/*    Two of them, and the difference between them is the point:          */
/*                                                                        */
/*      zx_el2_hypervisor_fault   HVBAR + 0x0C or + 0x10.  ZoneX faulted  */
/*        on its OWN access -- HSR.EC 0x21 or 0x25.  This is a hypervisor */
/*        bug.  It gets its own message and its own exit code, and it is  */
/*        never folded in with a guest violation, because a Phase-0 run   */
/*        that reported ZoneX faulting on itself as "the guest was        */
/*        stopped at the boundary" would pass while proving nothing.      */
/*                                                                        */
/*      zx_el2_unexpected_vector  reset, undefined instruction, SVC from  */
/*        Hyp, IRQ or FIQ at EL2.  Each means an assumption in the reset  */
/*        path is false: HCR.IMO and HCR.FMO are cleared there, so an IRQ */
/*        arriving at EL2 means something set them.                       */
/*                                                                        */
/*    Neither resumes.  There is nothing safe to resume to: whatever      */
/*    invariant the saved EL2 context assumed may already be false, and   */
/*    carrying on would turn a diagnosable bug into a corrupted run.      */
/*                                                                        */
/*    Both are reached by BL from the vector, so the fault record has      */
/*    already been captured by the time they run.  That ordering is not   */
/*    an implementation detail: a handler that prints before it captures  */
/*    can lose the syndrome to its own console driver faulting.           */
/*                                                                        */
/*  AND NEITHER MAY BE ALLOWED TO RECURSE                                 */
/*                                                                        */
/*    Everything below this point is code that runs AFTER ZoneX has       */
/*    already failed once, so the ordinary assumption -- that the         */
/*    hypervisor's own memory and its own console work -- is the          */
/*    assumption most in doubt.  If reporting the first fault takes a     */
/*    second one, the vector captures again and calls back in here, and   */
/*    a path whose entire purpose is to be unmistakable becomes a loop     */
/*    that says nothing.  That is the same failure the trap handler's     */
/*    header warns about from the other side: a vector that falls through */
/*    is how a fault becomes a hang.                                       */
/*                                                                        */
/*    So the depth is counted, in .bss, and the SECOND entry does not     */
/*    print at all.  It stores a verdict and parks, which is the one      */
/*    action left that cannot itself fault: the console is the most       */
/*    likely thing to have failed and is certainly the most likely thing  */
/*    to fail again.  The exit code says so, so that a silicon harness    */
/*    reading zx_run_failures with no console at all can tell "ZoneX      */
/*    faulted at EL2" from "ZoneX faulted at EL2 while reporting a fault  */
/*    at EL2" -- which are different bugs and point at different code.     */
/*                                                                        */
/*    The vector also puts SP_hyp back to the top of the Hyp stack before  */
/*    calling either of these, so that a stack that had run away is not    */
/*    the stack the report runs on.  See ZX_FATAL_STACK in                 */
/*    zx_trap_handler.S.                                                   */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"

/* Distinct exit codes.  The FVP runner judges a run on its printed text, so
   these matter mostly on silicon, where the gdb harness reads zx_run_failures
   -- and there the difference between "a guest was stopped" and "ZoneX broke"
   has to survive without a console.  */

#define ZX_EXIT_HYPERVISOR_FAULT    0x5AU
#define ZX_EXIT_UNEXPECTED_VECTOR   0x5BU
#define ZX_EXIT_FAULT_WHILE_FAULTING 0x5CU

/* HOW DEEP INTO THE UNRESUMABLE PATH THIS RUN IS.  In .bss, so it is zero
   before anything can read it and no initialiser has to be trusted -- the
   same argument the fault-continue policy is built on.  Shared by both
   functions below rather than one each: a data abort taken while reporting
   an unexpected VECTOR is the same problem as one taken while reporting a
   data abort, and counting them separately would let the pair alternate for
   ever.  */

static uint32_t zx_el2_fault_path_depth;


/**************************************************************************/
/*  zx_el2_fault_path_enter                                               */
/*                                                                        */
/*  Returns non-zero on the FIRST entry, when reporting is still worth     */
/*  attempting.  On any later entry it does not return at all: it parks    */
/*  with the verdict that says the report itself faulted.                  */
/**************************************************************************/

static uint32_t zx_el2_fault_path_enter(void)
{
    if (zx_el2_fault_path_depth != 0U)
    {
        /* NOT ONE CHARACTER IS PRINTED HERE.  Reaching this line means
           something between the vector and here has already faulted once,
           and the console driver is both the largest part of that and a
           polled device write on silicon.  zx_console_exit stores the
           verdict, executes a DSB and parks on the symbol a debug harness
           breaks on; none of that touches a device.  */

        zx_console_exit(ZX_EXIT_FAULT_WHILE_FAULTING);
    }

    zx_el2_fault_path_depth++;

    return 1U;
}


/**************************************************************************/
/*  zx_el2_hypervisor_fault                                               */
/**************************************************************************/

ZX_NORETURN void zx_el2_hypervisor_fault(void)
{
    (void) zx_el2_fault_path_enter();

    zx_console_puts("\n"
        "=========================================================\n"
        " ZONEX FAULTED AT EL2.  This is a HYPERVISOR bug.\n"
        "\n"
        " The exception arrived at an EL2 vector reserved for faults\n"
        " taken FROM Hyp mode, so the access that failed was ZoneX's\n"
        " own -- not a guest's.  Nothing below describes a partition\n"
        " being stopped at its boundary.\n"
        "=========================================================\n");

    zx_fault_report(zx_el2_fault_record());

    zx_console_puts("\nZONEX RESULT: FAILED -- ZoneX faulted at EL2\n");
    zx_console_exit(ZX_EXIT_HYPERVISOR_FAULT);
}


/**************************************************************************/
/*  zx_el2_unexpected_vector                                              */
/**************************************************************************/

ZX_NORETURN void zx_el2_unexpected_vector(void)
{
    (void) zx_el2_fault_path_enter();

    zx_console_puts("\n"
        "=========================================================\n"
        " UNEXPECTED EL2 VECTOR.  An exception nothing was expecting\n"
        " reached EL2, which means an assumption in the reset path is\n"
        " false.  The vector named below says which one.\n"
        "\n"
        " Read the VECTOR, not HSR.  Reset, undefined instruction, SVC\n"
        " from Hyp, IRQ and FIQ do not update HSR at all, so the\n"
        " syndrome printed below may be left over from an earlier\n"
        " exception.  ELR_hyp is the address that faulted and is the\n"
        " one useful number in that case -- disassemble it.\n"
        "=========================================================\n");

    zx_fault_report(zx_el2_fault_record());

    zx_console_puts("\nZONEX RESULT: FAILED -- unexpected EL2 vector\n");
    zx_console_exit(ZX_EXIT_UNEXPECTED_VECTOR);
}
