/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_frame.c                                           Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The major frame: the loop that runs a static schedule, and the      */
/*    boundary handler that ends one partition's window and begins the    */
/*    next one's.                                                        */
/*                                                                        */
/*    This is the file that makes ZoneX a hypervisor rather than a        */
/*    loader.  Everything under it was already true with one partition --  */
/*    a guest confined by stage 2, granted an interrupt, with a clock the  */
/*    hypervisor freezes.  What is here is the thing one partition cannot  */
/*    demonstrate: that a partition's window ENDS whether the partition    */
/*    agrees or not, and that the next one resumes exactly where it was.   */
/*                                                                        */
/*  THE TWO PATHS, AND WHY THEY ARE NOT THE SAME PATH                     */
/*                                                                        */
/*    A window can end in two ways and they are genuinely different       */
/*    events, so they are handled in different places:                    */
/*                                                                        */
/*      THE BOUNDARY, zx_el2_window_boundary.  An FIQ, taken at EL2       */
/*      because HCR.FMO routes it there, regardless of what the partition */
/*      had masked.  It never returns to the hypervisor's C: it saves the */
/*      outgoing partition, restores the incoming one, and ERETs from      */
/*      inside the exception path.  A boundary that came back to C and     */
/*      was re-entered would put a return, a dispatch and a call on the    */
/*      path whose cost is the subject of this whole step.                */
/*                                                                        */
/*      A GUEST LEAVING EARLY, in zx_frame_run.  A yield or a fault comes  */
/*      back through the ordinary resume path, and the hypervisor then     */
/*      has a decision to make rather than a switch to perform: this       */
/*      partition is done, its window is not, and neither fact may be      */
/*      allowed to disturb the schedule.                                   */
/*                                                                        */
/*    Both use the same two helpers to leave and to enter, so there is one */
/*    definition of what a partition switch IS and two callers of it.     */
/*                                                                        */
/*  WHAT AN IDLE PARTITION COSTS, AND WHY IT IS NOT A BUG                 */
/*                                                                        */
/*    A partition that yields burns the rest of its window.  The core sits */
/*    at EL2 watching a counter until the boundary it would have been      */
/*    preempted at, and then the frame carries on.                        */
/*                                                                        */
/*    That is not a missing optimisation.  Handing the remainder to the    */
/*    next partition -- which is what trapping WFI would buy -- makes one  */
/*    partition's start time depend on its neighbour's behaviour, and the  */
/*    independence of those two things is the entire purchase of temporal  */
/*    partitioning.  A later phase may offer it as an option; Phase 0      */
/*    declines it, and says so where the code is.                         */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Rule 8.9 -- the frame pointer below is file-scope because the        */
/*      boundary handler is reached from a VECTOR, which is called by      */
/*      hardware and can be passed nothing.                                */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"
#include "zx_guest_console.h"

/* THE FRAME THE BOUNDARY HANDLER IS RUNNING, and the partition it is
   running.  Both are file-scope for the same reason: an exception arrives
   with nothing but the machine, so a vector reaches its state by name or
   not at all.  zx_el2_current_context is named directly by zx_context.S --
   it is what the capture stores through -- which is why it is declared in
   zx_port.h rather than hidden here.  */

ZX_GUEST_CONTEXT *zx_el2_current_context;
uint32_t          zx_el2_frame_result;

static ZX_FRAME  *zx_frame_active;

/* The priority the hypervisor's own tick is given.
 *
 * NUMERICALLY LOWER IS HIGHER PRIORITY, and both targets implement only the
 * top FIVE bits of the byte -- so two values differing below bit 3 are the
 * same priority to the hardware, and equal priorities do not preempt.
 *
 * 0x20 against the partitions' 0xA0 leaves four implemented steps between
 * them, which is not a margin that needs to be large: it needs to be
 * non-zero and to survive the bits the part does not implement.  A tick
 * that could not preempt a partition's own timer handler would let a guest
 * defer the end of its window by taking a long interrupt, which is the
 * masking hole in a different disguise.  */

#define ZX_HYP_TICK_PRIORITY    0x20U

/* How many boundaries may be missed before the run is stopped and says so.
 *
 * A missed deadline means a window was shorter than its own partition
 * switch: the comparator is armed with a count already in the past, the
 * interrupt is pending again immediately, and the frame keeps turning with
 * every window longer than declared.  Nothing breaks, which is exactly the
 * problem -- a run full of them looks like a working demonstrator, only
 * slower, and nobody times a demonstrator.
 *
 * A handful rather than one, because the FIRST boundary of a run legitimately
 * competes with a cold instruction path, and a limit of one would turn a
 * cold start into a failure.  A handful rather than many, because the point
 * is to stop rather than to accumulate.  */

#define ZX_FRAME_MISS_LIMIT     8U


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_frame_configure                                   Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Records what the boundary handler will need and arms nothing.       */
/*                                                                        */
/*    Separate from starting the frame so that a caller can build the      */
/*    whole system -- manifest, layout, contexts, guests loaded -- and     */
/*    then commit to running it in one place.  A configure that also       */
/*    started would make "everything is ready" and "we are now             */
/*    time-partitioned" the same instant, and the second is the one that   */
/*    must not happen before the first is checked.                         */
/*                                                                        */
/**************************************************************************/

void zx_frame_configure(ZX_FRAME *frame_ptr,
                        ZX_SCHEDULE *schedule_ptr,
                        ZX_GUEST_CONTEXT *contexts_ptr,
                        const ZX_MM_LAYOUT *layout_ptr,
                        const ZX_MANIFEST *manifest_ptr,
                        UINT partition_count)
{
    if ((frame_ptr == (ZX_FRAME *)0)
        || (schedule_ptr == (ZX_SCHEDULE *)0)
        || (contexts_ptr == (ZX_GUEST_CONTEXT *)0)
        || (layout_ptr == (const ZX_MM_LAYOUT *)0))
    {
        return;
    }

    frame_ptr->zx_frame_schedule     = schedule_ptr;
    frame_ptr->zx_frame_contexts     = contexts_ptr;
    frame_ptr->zx_frame_layout       = layout_ptr;
    frame_ptr->zx_frame_manifest     = manifest_ptr;
    frame_ptr->zx_frame_partitions   = partition_count;
    frame_ptr->zx_frame_stopped_mask = 0U;
    frame_ptr->zx_frame_result       = ZX_RUN_FRAME_DONE;
    frame_ptr->zx_frame_switches     = 0U;
    frame_ptr->zx_frame_timed        = 0U;
    frame_ptr->zx_frame_switch_min   = 0xFFFFFFFFU;
    frame_ptr->zx_frame_switch_max   = 0U;
    frame_ptr->zx_frame_switch_last  = 0U;
    frame_ptr->zx_frame_switch_total = 0U;
    frame_ptr->zx_frame_spurious     = 0U;
    frame_ptr->zx_frame_stopped_index = ZX_MANIFEST_NO_INDEX;
    frame_ptr->zx_frame_stop_outcome  = ZX_RUN_FRAME_DONE;
    frame_ptr->zx_frame_hook          = (ZX_FRAME_HOOK_FN)0;
    frame_ptr->zx_frame_hook_argument = (void *)0;
    frame_ptr->zx_frame_hook_frames   = 0UL;

    zx_frame_active        = frame_ptr;
    zx_el2_current_context = (ZX_GUEST_CONTEXT *)0;
    zx_el2_frame_result    = ZX_RUN_FRAME_DONE;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_frame_console_release                             Cortex-R52     */
/*    zx_frame_console_claim                                             */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Whose console lines are these?                                      */
/*                                                                        */
/*    The tag on a forwarded character comes from the partition ZoneX      */
/*    SCHEDULED and never from the guest, or a partition could claim to    */
/*    be its neighbour and every line of a captured log would be evidence  */
/*    of nothing.  With one partition that was one attach around the whole */
/*    excursion; with a frame it has to follow the frame, because the      */
/*    partition that owns the console changes several times a second.      */
/*                                                                        */
/*    THEY ARE CALLED FROM OUTSIDE THE MEASURED SPAN, DELIBERATELY, and    */
/*    that is not a way of making the number look better.  Releasing the   */
/*    console CLOSES A PARTIAL LINE, which on silicon is characters        */
/*    through a polled UART -- thousands of cycles, and only on the        */
/*    switches that happen to leave a partition mid-sentence.  Left inside */
/*    the measurement it made the published switch cost depend on what a   */
/*    guest had been printing: min 5,928 cycles against max 15,490 on the  */
/*    S32Z280, a spread of 2.6x where the model showed ten cycles.         */
/*                                                                        */
/*    A partition switch in a product has no console in it at all.  The    */
/*    tag is a demonstration facility, so it is outside the number that    */
/*    describes the switch -- and the fact that it is outside is stated    */
/*    here rather than left for a reader to discover from the code.        */
/*                                                                        */
/**************************************************************************/

static void zx_frame_console_release(const ZX_FRAME *frame_ptr)
{
    if (frame_ptr->zx_frame_manifest != (const ZX_MANIFEST *)0)
    {
        zx_guest_console_detach();
    }
}


static void zx_frame_console_claim(const ZX_FRAME *frame_ptr, UINT index)
{
    if (frame_ptr->zx_frame_manifest != (const ZX_MANIFEST *)0)
    {
        const ZX_PARTITION *declaration =
            &frame_ptr->zx_frame_manifest->zx_manifest_partitions[index];

        zx_guest_console_attach(declaration->zx_partition_id,
                                declaration->zx_partition_name);
    }
}


/**************************************************************************/
/*  zx_frame_stopped -- has this partition left its window for good?      */
/**************************************************************************/

/**************************************************************************/
/*  zx_frame_current_partition -- whose window is this?                   */
/*                                                                        */
/*  THROUGH THE SCHEDULE, NOT THROUGH THE CONTEXT POINTER.  A caller could */
/*  compare zx_el2_current_context against the contexts array and get the */
/*  same answer nearly always -- and disagree exactly once, at a boundary  */
/*  where one has been changed and the other has not.  The fault log's     */
/*  attribution and the frame's own report then name different partitions  */
/*  for one event, which is the least useful moment for two sources of     */
/*  truth to exist.  One source: the schedule.                            */
/**************************************************************************/

UINT zx_frame_current_partition(void)
{
    if (zx_frame_active == (ZX_FRAME *)0)
    {
        return ZX_MANIFEST_NO_INDEX;
    }

    return zx_schedule_current_partition(zx_frame_active->zx_frame_schedule);
}


/**************************************************************************/
/*  zx_frame_set_frame_hook                                               */
/**************************************************************************/

void zx_frame_set_frame_hook(ZX_FRAME *frame_ptr, ZX_FRAME_HOOK_FN hook_fn,
                             void *argument)
{
    if (frame_ptr == (ZX_FRAME *)0)
    {
        return;
    }

    frame_ptr->zx_frame_hook          = hook_fn;
    frame_ptr->zx_frame_hook_argument = argument;
    frame_ptr->zx_frame_hook_frames   = 0UL;
}


/**************************************************************************/
/*  zx_frame_after_switch -- the bookkeeping that is NOT a switch.        */
/*                                                                        */
/*  CALLED AFTER THE CYCLE COUNTER HAS BEEN READ THE SECOND TIME, always, */
/*  and that placement is a requirement rather than a tidiness.  Both      */
/*  things below are here because a determinism regression needs them and  */
/*  a partition switch does not, and putting either inside the timed       */
/*  bracket would add its cost to every switch figure this repository has  */
/*  published -- so a measurement taken with this code present would stop  */
/*  being comparable with the silicon figures taken before it existed.     */
/*                                                                        */
/*  THE PERIOD IS UNAFFECTED BY BEING MEASURED LATE.  It is the difference */
/*  between two consecutive entry timestamps, and the offset between "the  */
/*  core was given to the partition" and "the timestamp was taken" is the  */
/*  same on both -- so it cancels.  That is what makes moving this out of  */
/*  the bracket free rather than merely cheap, and it is why the timestamp */
/*  used is the one the time freeze already took rather than a fresh read. */
/**************************************************************************/

static void zx_frame_after_switch(ZX_FRAME *frame_ptr, UINT index)
{
    ULONG frames;

    zx_context_period_note(&frame_ptr->zx_frame_contexts[index],
                           frame_ptr->zx_frame_contexts[index]
                               .zx_ctx_resumed_at);

    if (frame_ptr->zx_frame_hook == (ZX_FRAME_HOOK_FN)0)
    {
        return;
    }

    /* ONCE PER COMPLETED MAJOR FRAME, and the comparison is against the
       count the hook was last called at rather than a modulo of the
       boundary number.  A frame in which a partition was stopped takes
       fewer boundaries per frame, so counting boundaries would drift out of
       step with the schedule exactly on the runs where a phase change
       matters most.  */

    frames = frame_ptr->zx_frame_schedule->zx_schedule_frames;

    if (frames != frame_ptr->zx_frame_hook_frames)
    {
        frame_ptr->zx_frame_hook_frames = frames;
        frame_ptr->zx_frame_hook(frame_ptr->zx_frame_hook_argument, frames);
    }
}


static uint32_t zx_frame_stopped(const ZX_FRAME *frame_ptr, UINT index)
{
    return ((frame_ptr->zx_frame_stopped_mask
             & ((uint32_t)1U << index)) != 0U) ? 1U : 0U;
}


static uint32_t zx_frame_all_stopped(const ZX_FRAME *frame_ptr)
{
    uint32_t all = ((uint32_t)1U << frame_ptr->zx_frame_partitions) - 1U;

    return ((frame_ptr->zx_frame_stopped_mask & all) == all) ? 1U : 0U;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_frame_leave                                       Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Take the core from whichever partition has it.                      */
/*                                                                        */
/*    The fifteen shared words are already in the context block -- the     */
/*    vector put them there, before any C could destroy them -- so this is */
/*    everything else: the banked registers, the EL1 system registers, the */
/*    guest's virtual timer (saved and then disarmed), the whole EL1 MPU   */
/*    set, and the freeze.                                                */
/*                                                                        */
/*    THE FREEZE COMES LAST, and that ordering is the measurement's.  It   */
/*    records the physical count at the instant the partition stopped, and */
/*    everything before it is work the partition is still, correctly,      */
/*    being charged for: saving a guest's registers happens on the         */
/*    outgoing partition's time because it is the outgoing partition that  */
/*    made it necessary.  Freezing first would charge that work to whoever */
/*    comes next, which is precisely the coupling a static frame removes.  */
/*                                                                        */
/**************************************************************************/

static void zx_frame_leave(void)
{
    ZX_GUEST_CONTEXT *out = zx_el2_current_context;

    if (out == (ZX_GUEST_CONTEXT *)0)
    {
        return;
    }

    zx_context_save(out);
    zx_context_time_suspend(out);

    zx_el2_current_context = (ZX_GUEST_CONTEXT *)0;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_frame_enter                                       Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Give the core to a partition, up to but not including the ERET.     */
/*                                                                        */
/*    THE ORDER IS THE WHOLE FUNCTION:                                    */
/*                                                                        */
/*      1  the stage-2 region set, ONE HPRENR write.  First, because      */
/*         everything after it is a write the incoming partition will      */
/*         depend on and nothing after it reads the outgoing partition's   */
/*         memory.                                                        */
/*      2  its EL1 state, including its own MPU.                          */
/*      3  its clock, unfrozen: CNTVOFF advanced by exactly the interval   */
/*         it was away, so from inside no time passed.                     */
/*      4  the next boundary, as an ABSOLUTE deadline.                    */
/*                                                                        */
/*    THE DEADLINE IS ARMED LAST AND THAT IS DELIBERATE.  Everything above */
/*    it is the switch, and the switch happens on the OUTGOING partition's */
/*    time -- the boundary that ends the incoming window was computed from */
/*    the frame's epoch before any of this ran, so the incoming partition  */
/*    gets the window it was promised and not that window minus a switch.  */
/*                                                                        */
/*    Returns zero when the deadline it armed had already gone by.  The    */
/*    caller records it and decides; this function does not, because the   */
/*    schedule that has to count it belongs to the caller.                 */
/*                                                                        */
/**************************************************************************/

static uint32_t zx_frame_enter(ZX_FRAME *frame_ptr, UINT index)
{
    ZX_GUEST_CONTEXT *in = &frame_ptr->zx_frame_contexts[index];

    zx_stage2_enable_set(zx_mm_partition_mask(frame_ptr->zx_frame_layout,
                                              index));

    zx_context_restore(in);
    zx_context_time_resume(in);

    in->zx_ctx_entries++;
    in->zx_ctx_started = 1U;

    zx_el2_current_context = in;

    return zx_el2_hyp_timer_arm(
        zx_schedule_deadline(frame_ptr->zx_frame_schedule));
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_frame_next                                        Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Advance the schedule to the next window that has a partition        */
/*    willing to run in it, SPENDING every window it passes over.         */
/*                                                                        */
/*    A partition that has stopped still owns its slot.  The core sits at  */
/*    EL2 watching the counter until the boundary that window would have   */
/*    ended at, and only then does the schedule move on.  Giving that time */
/*    to the next partition would be the throughput answer and it would    */
/*    make one partition's start time a function of another's behaviour,   */
/*    which is the coupling temporal partitioning is bought to remove.     */
/*                                                                        */
/*    THE LOOP TERMINATES, and it is worth saying how, because a loop      */
/*    inside a partition switch is the one thing a WCET argument cannot    */
/*    have unbounded.  Each iteration either returns or waits out one      */
/*    whole window on the physical counter, so it cannot spin: it costs    */
/*    real time by construction.  And it is cut short by the check below   */
/*    -- once every partition has stopped there is nothing left to         */
/*    schedule, so the frame ends rather than idling to its limit.         */
/*                                                                        */
/*    It is also NOT on the hot path.  With every partition running, the   */
/*    first advance returns and the loop body never executes -- which is   */
/*    why the switch measurements in a healthy run are untouched by any of */
/*    this.                                                                */
/*                                                                        */
/*    Sets *burned_ptr when it waited out at least one window, so that the */
/*    caller can leave that boundary out of its TIMING.  A boundary that   */
/*    had to spend a dead partition's window is a switch PLUS a wait, and  */
/*    a figure averaging the two describes neither: on the cross-partition */
/*    build it turned a switch of a few thousand cycles into one of three  */
/*    million and reported the difference as jitter.                       */
/*                                                                        */
/*    Returns ZX_MANIFEST_NO_INDEX when the frame is over.                */
/*                                                                        */
/**************************************************************************/

static UINT zx_frame_next(ZX_FRAME *frame_ptr, uint32_t *burned_ptr)
{
    UINT index;

    *burned_ptr = 0U;

    if (zx_frame_all_stopped(frame_ptr) != 0U)
    {
        return ZX_MANIFEST_NO_INDEX;
    }

    for (;;)
    {
        index = zx_schedule_advance(frame_ptr->zx_frame_schedule);

        if (index == ZX_MANIFEST_NO_INDEX)
        {
            return ZX_MANIFEST_NO_INDEX;
        }

        if (zx_frame_stopped(frame_ptr, index) == 0U)
        {
            return index;
        }

        /* Its window, spent where it was declared to be spent.  And
           REPORTED, because a caller that is timing a partition switch must
           not count it: waiting out a whole window is not a switch, and a
           figure that averaged the two together would describe neither.  */

        *burned_ptr = 1U;

        zx_el2_dwell_until(
            zx_schedule_deadline(frame_ptr->zx_frame_schedule));

        if (zx_frame_all_stopped(frame_ptr) != 0U)
        {
            return ZX_MANIFEST_NO_INDEX;
        }
    }
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_window_boundary                               Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    THE PARTITION SWITCH.  Called from the FIQ vector with the outgoing  */
/*    partition's fifteen shared words already captured, and returning the */
/*    context the vector should ERET into.                                */
/*                                                                        */
/*    THE ORDER, AND WHAT EACH STEP IS PROTECTING:                        */
/*                                                                        */
/*      ACKNOWLEDGE FIRST.  Reading ICC_IAR0 raises the running priority,  */
/*      so nothing can preempt the switch itself.  It also identifies      */
/*      what arrived: only the hypervisor's own timer should be here, and  */
/*      anything else is counted rather than acted on.                     */
/*                                                                        */
/*      SAVE AND FREEZE, on the outgoing partition's time, because it is   */
/*      the outgoing partition that made the work necessary.               */
/*                                                                        */
/*      ADVANCE, AND RE-ARM BEFORE THE END-OF-INTERRUPT.  The generic      */
/*      timer asserts a LEVEL: until the comparator holds a deadline in    */
/*      the future the PPI is still asserted at the GIC, and an EOI given  */
/*      before that makes the interrupt pending again immediately.  That   */
/*      is not a glitch, it is a storm -- the hypervisor would take a       */
/*      boundary per instruction and no partition would ever run.          */
/*                                                                        */
/*      RESTORE LAST, so the incoming partition's permissions and          */
/*      registers are in force for as little time as possible before the   */
/*      ERET that starts using them.                                       */
/*                                                                        */
/*    MEASURED END TO END, in cycles, because "how long does a partition   */
/*    switch take" is the question this step exists to answer and the      */
/*    honest answer is the one taken from the switch that actually ran.    */
/*    Min and max are kept as well as the total: a safety audience reads   */
/*    the maximum, and a mean quoted alone hides exactly the excursion     */
/*    they are asking about.                                              */
/*                                                                        */
/**************************************************************************/

ZX_GUEST_CONTEXT *zx_el2_window_boundary(void)
{
    ZX_FRAME *frame_ptr = zx_frame_active;
    uint32_t  start;
    uint32_t  spent;
    uint32_t  intid;
    uint32_t  burned;
    UINT      index;

    if (frame_ptr == (ZX_FRAME *)0)
    {
        zx_el2_frame_result = ZX_RUN_TRAPPED;

        return (ZX_GUEST_CONTEXT *)0;
    }

    intid = zx_gic_el2_acknowledge();

    /* The console is handed back BEFORE the measurement starts.  See
       zx_frame_console_release: closing a partial line is a polled-UART
       write on silicon, and a switch cost that included it would depend on
       what a guest had been printing.  */

    zx_frame_console_release(frame_ptr);

    start = zx_pmu_cycles();

    if (zx_el2_hyp_timer_fired() == 0U)
    {
        frame_ptr->zx_frame_spurious++;
    }

    if (zx_el2_current_context != (ZX_GUEST_CONTEXT *)0)
    {
        zx_el2_current_context->zx_ctx_preemptions++;
    }

    zx_frame_leave();

    index = zx_frame_next(frame_ptr, &burned);

    if (index == ZX_MANIFEST_NO_INDEX)
    {
        zx_el2_hyp_timer_stop();

        /* Nobody owns the console now, and the hypervisor is about to
           speak.  Released above, and not claimed again.  */

        if (intid != ZX_INTID_SPURIOUS)
        {
            zx_gic_el2_end_of_interrupt(intid);
        }

        frame_ptr->zx_frame_result =
            (zx_schedule_is_running(frame_ptr->zx_frame_schedule) != 0U)
                ? ZX_RUN_YIELDED : ZX_RUN_FRAME_DONE;
        zx_el2_frame_result = frame_ptr->zx_frame_result;

        return (ZX_GUEST_CONTEXT *)0;
    }

    if (zx_frame_enter(frame_ptr, index) == 0U)
    {
        zx_schedule_note_missed(frame_ptr->zx_frame_schedule);
    }

    /* The level is deasserted now that the comparator holds a future
       deadline, so the end-of-interrupt cannot re-pend it.  A spurious
       INTID is NOT given one: the running priority was never raised, and
       dropping a priority that was never raised corrupts the GIC's
       priority stack rather than merely being redundant.  */

    if (intid != ZX_INTID_SPURIOUS)
    {
        zx_gic_el2_end_of_interrupt(intid);
    }

    spent = zx_pmu_cycles() - start;

    /* And claimed again AFTER it stops, for the same reason.  */

    zx_frame_console_claim(frame_ptr, index);

    /* A BOUNDARY THAT HAD TO BURN A DEAD PARTITION'S WINDOW IS NOT TIMED.
       It is a switch plus a wait of up to a whole window, and averaging the
       two together describes neither -- on the cross-partition build it
       turned a switch of a few thousand cycles into one of three million
       and reported the difference as jitter.  The boundary still COUNTS, so
       "every window ended at a boundary" stays true; only its cost is left
       out, and it is left out because it is not the cost of a switch.  */

    frame_ptr->zx_frame_switches++;

    if (burned == 0U)
    {
        frame_ptr->zx_frame_timed++;
        frame_ptr->zx_frame_switch_last   = spent;
        frame_ptr->zx_frame_switch_total += (uint64_t)spent;

        if (spent < frame_ptr->zx_frame_switch_min)
        {
            frame_ptr->zx_frame_switch_min = spent;
        }

        if (spent > frame_ptr->zx_frame_switch_max)
        {
            frame_ptr->zx_frame_switch_max = spent;
        }
    }

    /* THE PERIOD AND THE PHASE HOOK, both of them after the cycle counter
       has been read for the second time.  Neither is part of a switch and
       neither may be allowed to cost one -- see zx_frame_after_switch.  */

    zx_frame_after_switch(frame_ptr, index);

    if (frame_ptr->zx_frame_schedule->zx_schedule_missed
            >= (ULONG)ZX_FRAME_MISS_LIMIT)
    {
        zx_el2_hyp_timer_stop();
        frame_ptr->zx_frame_result = ZX_RUN_OVERRUN;
        zx_el2_frame_result        = ZX_RUN_OVERRUN;

        return (ZX_GUEST_CONTEXT *)0;
    }

    return zx_el2_current_context;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_frame_run                                         Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The frame, from the hypervisor's side.                              */
/*                                                                        */
/*    It looks like a loop that runs partitions and it is not: the loop    */
/*    body executes once per partition that LEAVES ITS WINDOW EARLY, which */
/*    in a healthy run is never.  Every ordinary window boundary happens   */
/*    inside zx_el2_enter_partition and is invisible here.                 */
/*                                                                        */
/*    WHAT A YIELD MEANS IN A STATIC FRAME, and it is worth being precise  */
/*    because two reasonable answers are wrong.  It does not mean "give    */
/*    the rest of my window to somebody else" -- that couples two          */
/*    partitions' timing.  It does not mean "start me again next window"   */
/*    either: a guest that has finished would then be re-entered at        */
/*    whatever instruction followed its own hypercall, for ever.  It means */
/*    the partition is DONE.  Its window is spent, its slot stays in the   */
/*    frame, and its neighbours are unaffected -- which is the whole       */
/*    claim, demonstrated by a partition doing the least cooperative thing */
/*    available to it.                                                     */
/*                                                                        */
/*    A FAULT IS THE SAME DECISION FOR A DIFFERENT REASON.  Phase 0 does   */
/*    not restart a faulted partition: supervised restart is an explicitly */
/*    deferred later phase, and a hypervisor that quietly re-entered a     */
/*    partition that had just violated its boundary would be doing the     */
/*    easy half of it.  The fault record is kept, the partition is         */
/*    stopped, and the run reports it.                                     */
/*                                                                        */
/**************************************************************************/

uint32_t zx_frame_run(ZX_FRAME *frame_ptr)
{
    UINT     index;
    uint32_t outcome;
    uint32_t burned = 0U;

    if (frame_ptr == (ZX_FRAME *)0)
    {
        return ZX_RUN_TRAPPED;
    }

    /* THE EPOCH, taken here and nowhere else.  Every boundary for the rest
       of the run is one exact multiple of the tick away from this reading,
       which is what makes the frame immune to the switch's own latency.
       Taken immediately before the first entry, so the first window is not
       the only short one in the run.  */

    zx_schedule_start(frame_ptr->zx_frame_schedule, zx_read_cntpct());

    index = zx_schedule_current_partition(frame_ptr->zx_frame_schedule);

    if (index == ZX_MANIFEST_NO_INDEX)
    {
        return ZX_RUN_TRAPPED;
    }

    for (;;)
    {
        if (zx_frame_enter(frame_ptr, index) == 0U)
        {
            zx_schedule_note_missed(frame_ptr->zx_frame_schedule);
        }

        /* THE COLD START AND EVERY RE-ENTRY AFTER AN EARLY DEPARTURE.  This
           loop body runs once per partition that LEFT ITS WINDOW EARLY, and
           once at the beginning; every ordinary boundary is handled in the
           vector and never comes back here.  Both paths have to record the
           entry, or the first period of the run and every period after a
           yield would be missing -- and the periods either side of a gap
           are the ones a reader looks at first.  */

        zx_frame_after_switch(frame_ptr, index);

        zx_frame_console_claim(frame_ptr, index);

        outcome = zx_el2_enter_partition(zx_el2_current_context);

        zx_frame_console_release(frame_ptr);

        /* Control is back at EL2.  Either the frame ended inside the
           boundary handler -- in which case it has already stopped the
           timer and said why -- or the partition left its window early.  */

        if ((outcome == ZX_RUN_FRAME_DONE) || (outcome == ZX_RUN_OVERRUN))
        {
            return outcome;
        }

        /* A yield or a fault, inside a window that is not over.  */

        zx_el2_hyp_timer_stop();

        index = zx_schedule_current_partition(frame_ptr->zx_frame_schedule);

        if (index == ZX_MANIFEST_NO_INDEX)
        {
            frame_ptr->zx_frame_result = outcome;

            return outcome;
        }

        zx_frame_leave();

        frame_ptr->zx_frame_stopped_mask |= (uint32_t)1U << index;

        /* WHICH partition and WHY, kept for the report.  Only the FIRST is
           recorded: a frame in which two partitions left early has stopped
           being a demonstration of anything and the first departure is what
           a reader has to understand before the second makes sense.  */

        if (frame_ptr->zx_frame_stopped_index == ZX_MANIFEST_NO_INDEX)
        {
            frame_ptr->zx_frame_stopped_index = index;
            frame_ptr->zx_frame_stop_outcome  = outcome;
        }

        /* The rest of this partition's window, spent.  */

        zx_el2_dwell_until(
            zx_schedule_deadline(frame_ptr->zx_frame_schedule));

        index = zx_frame_next(frame_ptr, &burned);

        if (index == ZX_MANIFEST_NO_INDEX)
        {
            frame_ptr->zx_frame_result =
                (zx_schedule_is_running(frame_ptr->zx_frame_schedule) != 0U)
                    ? outcome : ZX_RUN_FRAME_DONE;

            return frame_ptr->zx_frame_result;
        }
    }
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_frame_measure_switch                              Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The switch, broken down by group, measured with the code the switch  */
/*    runs.                                                               */
/*                                                                        */
/*    THREE DISCIPLINES, ALL OF THEM PAID FOR BY EARLIER MISTAKES IN THIS  */
/*    SUITE:                                                              */
/*                                                                        */
/*    THE COUNTER READ IS MEASURED AND SUBTRACTED.  Reading PMCCNTR costs  */
/*    cycles, and a group whose real cost is small is otherwise reported   */
/*    as mostly the cost of asking.                                       */
/*                                                                        */
/*    THE TWO CONTEXTS ALTERNATE.  An implementation is entitled to make   */
/*    writing the value already in a register cheap, in a way a real       */
/*    switch is not.  The same rule was needed when the stage-2 region     */
/*    mask was first measured, and it is why that figure alternates        */
/*    between two masks.                                                   */
/*                                                                        */
/*    A WARM-UP ROUND IS RUN AND DISCARDED.  The first execution of        */
/*    anything on a real core is not comparable to the second; a pair      */
/*    that differs in ORDER as well as in the thing under test measures    */
/*    neither.  That is not a caution, it is a result: this suite once     */
/*    published stage 2 as 28% FASTER than no stage 2 on exactly that      */
/*    error.                                                              */
/*                                                                        */
/*    WHAT THE NUMBERS ARE NOT.  On the Armv8-R AEM FVP they are not       */
/*    timing at all -- it is a functional model.  They are produced there  */
/*    anyway so that the measurement path is exercised on every run,       */
/*    including on a machine with no board attached.                       */
/*                                                                        */
/**************************************************************************/

void zx_frame_measure_switch(ZX_GUEST_CONTEXT *scratch_a,
                             ZX_GUEST_CONTEXT *scratch_b,
                             uint32_t mask_a, uint32_t mask_b,
                             uint32_t rounds,
                             ZX_SWITCH_COST *cost_ptr)
{
    uint32_t round;
    uint32_t start;
    uint32_t total;

    if ((scratch_a == (ZX_GUEST_CONTEXT *)0)
        || (scratch_b == (ZX_GUEST_CONTEXT *)0)
        || (cost_ptr == (ZX_SWITCH_COST *)0)
        || (rounds == 0U))
    {
        return;
    }

    cost_ptr->zx_cost_el1_regions = zx_context_el1_regions();

    /* BOTH SCRATCH BLOCKS ARE FILLED FROM THE MACHINE FIRST, and this is
       not tidiness.  The loops below alternate between them so that no
       iteration restores the state already in force -- and an alternation
       whose second block had never been SAVED into would restore a block of
       zeros into SCTLR, the EL1 MPU and MAIR.  SCTLR has RES1 bits, so zero
       is not a value the architecture defines a meaning for; the
       measurement would have destroyed the machine it was measuring.  */

    zx_context_save(scratch_a);
    zx_context_save(scratch_b);

    /* Warm up, and throw it away.  The first execution of anything on a real
       core is not comparable to the second.  */

    zx_context_restore(scratch_a);

    /* What it costs to ask.  Subtracted from every row below.  */

    start = zx_pmu_cycles();

    for (round = 0U; round < rounds; round++)
    {
        total = zx_pmu_cycles();
    }

    total = zx_pmu_cycles() - start;
    cost_ptr->zx_cost_counter_read = total / rounds;

    /* ---- the full save ---------------------------------------------- */

    start = zx_pmu_cycles();

    for (round = 0U; round < rounds; round++)
    {
        zx_context_save(((round & 1U) == 0U) ? scratch_a : scratch_b);
    }

    total = (zx_pmu_cycles() - start) / rounds;
    cost_ptr->zx_cost_save_full =
        (total > cost_ptr->zx_cost_counter_read)
            ? (total - cost_ptr->zx_cost_counter_read) : 0U;

    /* ---- the full restore ------------------------------------------- */

    start = zx_pmu_cycles();

    for (round = 0U; round < rounds; round++)
    {
        zx_context_restore(((round & 1U) == 0U) ? scratch_a : scratch_b);
    }

    total = (zx_pmu_cycles() - start) / rounds;
    cost_ptr->zx_cost_restore_full =
        (total > cost_ptr->zx_cost_counter_read)
            ? (total - cost_ptr->zx_cost_counter_read) : 0U;

    /* ---- the EL1 MPU alone, both directions ------------------------- */

    start = zx_pmu_cycles();

    for (round = 0U; round < rounds; round++)
    {
        zx_context_save_mpu(((round & 1U) == 0U) ? scratch_a : scratch_b);
    }

    total = (zx_pmu_cycles() - start) / rounds;
    cost_ptr->zx_cost_save_mpu =
        (total > cost_ptr->zx_cost_counter_read)
            ? (total - cost_ptr->zx_cost_counter_read) : 0U;

    start = zx_pmu_cycles();

    for (round = 0U; round < rounds; round++)
    {
        zx_context_restore_mpu(((round & 1U) == 0U) ? scratch_a : scratch_b);
    }

    total = (zx_pmu_cycles() - start) / rounds;
    cost_ptr->zx_cost_restore_mpu =
        (total > cost_ptr->zx_cost_counter_read)
            ? (total - cost_ptr->zx_cost_counter_read) : 0U;

    /* ---- the stage-2 region set: one HPRENR write ------------------- */

    start = zx_pmu_cycles();

    for (round = 0U; round < rounds; round++)
    {
        zx_stage2_enable_set(((round & 1U) == 0U) ? mask_a : mask_b);
    }

    total = (zx_pmu_cycles() - start) / rounds;
    cost_ptr->zx_cost_region_mask =
        (total > cost_ptr->zx_cost_counter_read)
            ? (total - cost_ptr->zx_cost_counter_read) : 0U;

    /* ---- the freeze: a suspend and a resume, which is CNTVOFF ------- */

    start = zx_pmu_cycles();

    for (round = 0U; round < rounds; round++)
    {
        ZX_GUEST_CONTEXT *which = ((round & 1U) == 0U) ? scratch_a : scratch_b;

        zx_context_time_suspend(which);
        zx_context_time_resume(which);
    }

    total = (zx_pmu_cycles() - start) / rounds;
    cost_ptr->zx_cost_time_freeze =
        (total > cost_ptr->zx_cost_counter_read)
            ? (total - cost_ptr->zx_cost_counter_read) : 0U;

    /* ---- arming the next boundary ----------------------------------- */

    {
        uint64_t far_away = zx_read_cntpct() + 0x40000000U;
        uint32_t armed     = 0U;

        start = zx_pmu_cycles();

        for (round = 0U; round < rounds; round++)
        {
            armed = zx_el2_hyp_timer_arm(far_away + (uint64_t)round);
        }

        total = (zx_pmu_cycles() - start) / rounds;
        cost_ptr->zx_cost_deadline =
            (total > cost_ptr->zx_cost_counter_read)
                ? (total - cost_ptr->zx_cost_counter_read) : 0U;

        /* Consumed rather than discarded: every deadline above is far in
           the future, so `armed` is non-zero by construction, and reading
           it here is what keeps a ZX_NODISCARD return from being silently
           thrown away in the one place where throwing it away is correct. */

        if (armed == 0U)
        {
            cost_ptr->zx_cost_deadline = 0U;
        }
    }

    zx_el2_hyp_timer_stop();
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_frame_hyp_tick_priority                           Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The priority the hypervisor's tick is given, so that an image can    */
/*    print it and check it against what the GIC read back.  A constant    */
/*    an image restated for itself would be a second source of truth for   */
/*    the one number that decides whether a window can be ended at all.    */
/*                                                                        */
/**************************************************************************/

uint32_t zx_frame_hyp_tick_priority(void)
{
    return ZX_HYP_TICK_PRIORITY;
}
