/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_fault_continue.c                                  Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    What happens after a partition's stage-2 violation has been         */
/*    recorded: it is STOPPED, which is the shipping policy, or -- in an  */
/*    image that configured the test-only alternative -- it is resumed    */
/*    past the access, so that one image can sweep a whole matrix of      */
/*    violations.                                                         */
/*                                                                        */
/*  WHY A TEST-ONLY CONTINUE MODE EXISTS AT ALL                           */
/*                                                                        */
/*    Phase 0's specified behaviour is stage-2 fault, log, halt, and that */
/*    is right: a hypervisor that quietly re-entered a partition which    */
/*    had just violated its boundary would be doing the easy half of      */
/*    supervised restart.  But a regression with a dozen violation cases  */
/*    would then need a dozen images and a dozen runs, which on silicon   */
/*    is most of a working day and on a functional model is minutes of    */
/*    simulation per case.  The isolation matrix is fourteen cases.       */
/*                                                                        */
/*    So the mode exists, and four things keep it honest.                 */
/*                                                                        */
/*    IT IS DECIDED AT BUILD TIME BY THE IMAGE, and cannot be reached by  */
/*    a manifest, a mailbox word or a partition.  The policy arrives      */
/*    through zx_el2_fault_continue_configure, which an image calls with  */
/*    a value taken from its own compile-time definition -- and the       */
/*    default is HALT because the variable holding it lives in .bss, so   */
/*    an image that configures nothing gets the value of zeroed memory.   */
/*                                                                        */
/*    IT WAS AN #ifdef IN THIS FILE FIRST, AND IT COULD NOT WORK.  ZoneX  */
/*    is a LIBRARY, built once per build tree and linked into every image */
/*    in it, so a compile definition on one image's target never reaches  */
/*    the hypervisor's own translation units: the option was set, the     */
/*    library was built without it, and the regression dutifully reported */
/*    every partition STOPPED while claiming to be in continue mode.  The */
/*    definition now lives where the build variants live -- on the image  */
/*    -- which is where every other positive and negative variant in this */
/*    suite has always been defined.                                      */
/*                                                                        */
/*    THE SHIPPING PATH IS THE SAME CODE.  There is no #ifdef in the      */
/*    vector: every build calls this function on every guest violation    */
/*    and this function decides.  A continue mode that took a DIFFERENT   */
/*    route through the trap handler would leave the shipping route the   */
/*    less exercised of the two, which is the wrong way round for the     */
/*    path that matters.                                                  */
/*                                                                        */
/*    THE IMAGE SAYS SO IN ITS OWN OUTPUT, from this file rather than     */
/*    from its own macro, so that a log cannot be mistaken for one from a */
/*    shipping build -- and so that the two ends cannot disagree, which   */
/*    is exactly what they did the first time.                            */
/*                                                                        */
/*    AND HALT IS STILL TESTED RATHER THAN ASSUMED.  A build of the same  */
/*    image without the definition attempts one case and must halt, on    */
/*    both targets, so the shipping policy has a run of its own.          */
/*                                                                        */
/*  WHY A PREFETCH ABORT IS NOT RESUMED THE SAME WAY                      */
/*                                                                        */
/*    "Step over the faulting instruction" needs the instruction, and for */
/*    a prefetch abort there is none: the FETCH is what failed.  Resuming */
/*    at ELR + 4 would resume INSIDE the neighbour's window and fault     */
/*    again on the next word, and again, for the rest of the window -- a  */
/*    partition walking through its neighbour's code taking one exception */
/*    per instruction, which is a livelock wearing the costume of a test. */
/*                                                                        */
/*    So the GUEST names where it wants to be put back, before it         */
/*    branches, and this file asks the image for that address through a   */
/*    hook rather than reading a mailbox itself.  The mailbox layout is   */
/*    an example's business; the hypervisor's business is that an address */
/*    it was not given means the partition is stopped.                    */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"
#include "zx_fault_log.h"

/* Where violations are recorded, and who to ask for a branch's resume
   point.  BOTH SUPPLIED BY THE IMAGE, and neither is allocated here.
 *
 * The log is 896 bytes of .bss and only one image needs it; a hypervisor
 * that carried it unconditionally would be charging every shipping build
 * for a regression's evidence.  The hook is the image's because the
 * mailbox layout is the image's -- see the file header.  */

static ZX_FAULT_LOG       *zx_fault_continue_log;
static ZX_FAULT_RESUME_FN  zx_fault_continue_resume;

/* THE POLICY, AND ITS DEFAULT IS THE VALUE OF ZEROED MEMORY.  In .bss, so
   an image that never calls configure -- which is every shipping image and
   every other image in this suite -- gets HALT without having asked for it.
   A default that has to be written down somewhere is a default somebody can
   write down wrongly.  */

static uint32_t            zx_fault_continue_policy;


/**************************************************************************/
/*  zx_el2_fault_continue_configure                                       */
/**************************************************************************/

void zx_el2_fault_continue_configure(ZX_FAULT_LOG *log_ptr,
                                     ZX_FAULT_RESUME_FN resume_fn,
                                     uint32_t continue_past_violations)
{
    zx_fault_continue_log    = log_ptr;
    zx_fault_continue_resume = resume_fn;
    zx_fault_continue_policy = continue_past_violations;
}


/**************************************************************************/
/*  zx_el2_fault_continue_enabled                                         */
/*                                                                        */
/*  A FUNCTION AND NOT THE IMAGE'S OWN MACRO.  What an image prints about */
/*  its own fault policy has to come from the translation unit that ACTS  */
/*  on it, or the two can disagree -- an image that tested its own        */
/*  definition and then failed to pass it in would print "continue" and   */
/*  halt.  That is not hypothetical: this seam was an #ifdef in this file */
/*  first, and the two ends disagreed the other way round.  One value, set*/
/*  once, read by both the policy and the report.                         */
/**************************************************************************/

uint32_t zx_el2_fault_continue_enabled(void)
{
    return (zx_fault_continue_policy != 0U) ? 1U : 0U;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_fault_continue                                Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Called from the Hyp trap vector once a guest violation has been     */
/*    captured, on EVERY build.  Returns the context to resume, or a null */
/*    pointer to stop the partition -- which is what the shipping policy  */
/*    returns, always.                                                    */
/*                                                                        */
/*    RECORDING HAPPENS IN BOTH POLICIES.  The single fault record holds  */
/*    the LAST capture and is overwritten by the next one, so a halting   */
/*    build gains nothing from a log of one entry -- except that the      */
/*    logging code is then the same code in both, and the report an image */
/*    prints is the same report.  A logger only the test build ran would  */
/*    be a logger only the test build had ever been seen to work in.      */
/*                                                                        */
/**************************************************************************/

ZX_GUEST_CONTEXT *zx_el2_fault_continue(void)
{
    const zx_fault_record_t *record_ptr = zx_el2_fault_record();
    ZX_GUEST_CONTEXT        *context_ptr = zx_el2_current_context;
    UINT                     partition   = zx_frame_current_partition();
    uint32_t                 ec;
    uint32_t                 resumed = ZX_FAULT_RESUMED_STOPPED;
    uint32_t                 resume_pc = 0U;

    ec = zx_fault_ec(record_ptr->zx_fault_hsr);

    /* WHAT WOULD HAPPEN, DECIDED BEFORE ANYTHING IS RECORDED, so that the
       log entry says how the partition was actually let go rather than how
       it usually is.  An entry claiming a resume that did not happen is
       worse than no entry: it is evidence pointing the wrong way.  */

    if ((zx_el2_fault_continue_enabled() != 0U)
        && (context_ptr != (ZX_GUEST_CONTEXT *)0))
    {
        if (ec == ZX_EC_DABT_ROUTED)
        {
            /* HSR.IL gives the faulting instruction's length: set for a
               32-bit instruction, clear for a 16-bit one.  A guest in T32
               would otherwise be resumed two bytes into a wide instruction,
               which is not a fault -- it is an arbitrary instruction, and
               the run would go wrong somewhere else entirely.  */

            resume_pc = context_ptr->zx_ctx_elr
                        + (((record_ptr->zx_fault_hsr & ZX_HSR_IL_MASK) != 0U)
                               ? 4U : 2U);
            resumed   = ZX_FAULT_RESUMED_SKIPPED;
        }
        else if (ec == ZX_EC_PABT_ROUTED)
        {
            /* The guest's own published resume point, via the image.  Zero
               means it published none, and a partition that asked to be
               resumed nowhere is stopped -- the shipping behaviour, which
               is the right default for a path with no answer.  */

            if (zx_fault_continue_resume != (ZX_FAULT_RESUME_FN)0)
            {
                resume_pc = zx_fault_continue_resume(partition);
            }

            if (resume_pc != 0U)
            {
                resumed = ZX_FAULT_RESUMED_REDIRECTED;
            }
        }
        else
        {
            /* Some other class routed to EL2.  Not a stage-2 violation, so
               not something this path has any business resuming past.  */
        }
    }

    zx_fault_log_add(zx_fault_continue_log, partition, record_ptr, resumed);

    if (resumed == ZX_FAULT_RESUMED_STOPPED)
    {
        return (ZX_GUEST_CONTEXT *)0;
    }

    context_ptr->zx_ctx_elr = resume_pc;

    /* AND ITS FAULT IS COUNTED AGAINST IT.  A partition resumed past a
       violation has still violated, and a run has to be able to say how
       many times: the determinism phase in which one partition faults on
       every iteration of its own loop is a claim about that count.  */

    context_ptr->zx_ctx_violations++;

    return context_ptr;
}
