/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_gic.c                                             Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    GICv3 bring-up for EL2, and the routing of guest interrupts.        */
/*                                                                        */
/*    The Cortex-R52 does implement the GICv3 virtual CPU interface --    */
/*    ICH_HCR, ICH_VTR and four List Registers, ICH_LR0 to ICH_LR3 -- so  */
/*    interrupt injection is available.  Phase 0 still keeps interrupt    */
/*    handling deliberately simple; that is a scope decision rather than  */
/*    a hardware limitation, and it is recorded as one so a later phase   */
/*    does not rediscover the List Registers from scratch.                */
/*                                                                        */
/*    This translation unit is deliberately empty of implementation.      */
/*    See docs/armv8r-el2-reference.md for the verified register sheet    */
/*    the code that lands here must be written against.                   */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"
