/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_stage2_mpu.c                                      Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Stage-2 MPU programming: HPRSELR/HPRBAR/HPRLAR region descriptors,  */
/*    HPRENR bulk enable, HMAIR0/HMAIR1 attributes, and the HCR.VM plus   */
/*    HSCTLR.M pair that turns stage 2 on.                                */
/*                                                                        */
/*    Three facts shape everything written here.  There is exactly ONE    */
/*    EL2 region set and it does two jobs -- the hypervisor's own mapping */
/*    and every guest's stage-2 mapping compete for the same 16, 20 or 24 */
/*    regions.  HSCTLR.BR=1 relieves most of that pressure: EL2's own     */
/*    accesses that hit no region fall back to the background map, while  */
/*    EL0/EL1 accesses that hit no region fault regardless of BR --       */
/*    deny-all for guests, and no region spent on ordinary hypervisor     */
/*    code and data.  But BR grants permission, not attributes.  The      */
/*    background map is Normal cacheable below 0x60000000, so an MMIO     */
/*    device the hypervisor owns -- its console, the GIC -- is reachable  */
/*    there with cacheable attributes and still needs a Device-attributed */
/*    EL2 region of its own.  On the FVP those devices happen to sit in   */
/*    the Device band, so the FVP cannot show you that.  See              */
/*    docs/decisions.md D2.                                               */
/*                                                                        */
/*    This translation unit is deliberately empty of implementation.      */
/*    See docs/armv8r-el2-reference.md for the verified register sheet    */
/*    the code that lands here must be written against.                   */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"
