/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/
// Some portions generated by Claude Code (Opus 5).

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_stage2_mpu.c                                      Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Stage-2 MPU programming: HPRSELR/HPRBAR/HPRLAR region descriptors,  */
/*    HPRENR bulk enable, HMAIR0/HMAIR1 attributes, and the HCR.VM plus   */
/*    HSCTLR.M pair that turns stage 2 on.                                */
/*                                                                        */
/*    Three facts shape everything written here.  There is exactly ONE    */
/*    EL2 region set and it does two jobs -- the hypervisor's own mapping */
/*    and every guest's stage-2 mapping compete for the same 16, 20 or 24 */
/*    regions.  HSCTLR.BR=1 relieves most of that pressure: EL2's own     */
/*    accesses that hit no region fall back to the background map, while  */
/*    EL0/EL1 accesses that hit no region fault regardless of BR --       */
/*    deny-all for guests, and no region spent on ordinary hypervisor     */
/*    code and data.  But BR grants permission, not attributes.  The      */
/*    background map is Normal cacheable below 0x60000000, so an MMIO     */
/*    device the hypervisor owns -- its console, the GIC -- is reachable  */
/*    there with cacheable attributes and still needs a Device-attributed */
/*    EL2 region of its own.  On the FVP those devices happen to sit in   */
/*    the Device band, so the FVP cannot show you that.  See              */
/*    docs/decisions.md D2.                                               */
/*                                                                        */
/*    Two traps are paid for here once so that no caller pays them again, */
/*    and both were first paid at EL1 during the Cortex-R52 Modules port  */
/*    work, where the field layouts are identical:                        */
/*                                                                        */
/*      * an under-aligned BASE does not fault.  Its low bits land on SH, */
/*        AP and XN and silently change the region's attributes.          */
/*      * an unmasked LIMIT is worse.  base + size - 1 ends in 0x3F, and  */
/*        those bits land on HPRLAR.AttrIndx and select an unwritten HMAIR */
/*        byte -- which reads as Device-nGnRnE, so the region still       */
/*        "works" well enough to pass a careless test.                    */
/*                                                                        */
/*    Both are masked in zx_region_bar/zx_region_lar below, which is why  */
/*    programming a region is a function call and not two stores.         */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                    */
/*                                                                        */
/*    Directive 4.3 -- every asm statement below is alone in a function    */
/*      that does nothing else.                                           */
/*    Rule 1.1 / 1.2 -- inline assembly is the only way to reach a         */
/*      coprocessor register.                                             */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"

/**************************************************************************/
/*     The mirrored assembly constants, checked against their originals   */
/**************************************************************************/

/* zx_port.h mirrors a handful of constants without integer suffixes so that
   the assembler can read them.  These assertions are what makes the mirror
   safe: change one side and the build stops here, naming the pair.

   The structure offsets matter most.  zx_trap_handler.S writes HSR, HPFAR,
   HDFAR, HIFAR, ELR_hyp and SPSR_hyp through fixed offsets into
   zx_fault_record_t, so a field inserted into that structure would silently
   move every subsequent register into the wrong slot -- and the resulting
   fault report would be internally consistent, plausible, and wrong.  */

_Static_assert(ZX_ASM_EC_SHIFT == (int)ZX_HSR_EC_SHIFT,
               "ZX_ASM_EC_SHIFT and ZX_HSR_EC_SHIFT have drifted apart");
_Static_assert(ZX_ASM_EC_HVC == (int)ZX_EC_HVC,
               "ZX_ASM_EC_HVC and ZX_EC_HVC have drifted apart");
_Static_assert(ZX_ASM_EC_PABT_ROUTED == (int)ZX_EC_PABT_ROUTED,
               "ZX_ASM_EC_PABT_ROUTED and ZX_EC_PABT_ROUTED have drifted apart");
_Static_assert(ZX_ASM_EC_DABT_ROUTED == (int)ZX_EC_DABT_ROUTED,
               "ZX_ASM_EC_DABT_ROUTED and ZX_EC_DABT_ROUTED have drifted apart");

_Static_assert(ZX_ASM_HVC_IMM_NOP == (int)ZX_HVC_NOP,
               "ZX_ASM_HVC_IMM_NOP and ZX_HVC_NOP have drifted apart");
_Static_assert(ZX_ASM_HVC_IMM_YIELD == (int)ZX_HVC_YIELD,
               "ZX_ASM_HVC_IMM_YIELD and ZX_HVC_YIELD have drifted apart");

_Static_assert(ZX_ASM_VEC_RESET == (int)ZX_VECTOR_RESET,
               "ZX_ASM_VEC_RESET and ZX_VECTOR_RESET have drifted apart");
_Static_assert(ZX_ASM_VEC_UNDEF == (int)ZX_VECTOR_UNDEF,
               "ZX_ASM_VEC_UNDEF and ZX_VECTOR_UNDEF have drifted apart");
_Static_assert(ZX_ASM_VEC_SVC == (int)ZX_VECTOR_SVC,
               "ZX_ASM_VEC_SVC and ZX_VECTOR_SVC have drifted apart");
_Static_assert(ZX_ASM_VEC_PABT_HYP == (int)ZX_VECTOR_PABT_HYP,
               "ZX_ASM_VEC_PABT_HYP and ZX_VECTOR_PABT_HYP have drifted apart");
_Static_assert(ZX_ASM_VEC_DABT_HYP == (int)ZX_VECTOR_DABT_HYP,
               "ZX_ASM_VEC_DABT_HYP and ZX_VECTOR_DABT_HYP have drifted apart");
_Static_assert(ZX_ASM_VEC_HYP_TRAP == (int)ZX_VECTOR_HYP_TRAP,
               "ZX_ASM_VEC_HYP_TRAP and ZX_VECTOR_HYP_TRAP have drifted apart");
_Static_assert(ZX_ASM_VEC_IRQ == (int)ZX_VECTOR_IRQ,
               "ZX_ASM_VEC_IRQ and ZX_VECTOR_IRQ have drifted apart");
_Static_assert(ZX_ASM_VEC_FIQ == (int)ZX_VECTOR_FIQ,
               "ZX_ASM_VEC_FIQ and ZX_VECTOR_FIQ have drifted apart");

_Static_assert(ZX_ASM_FAULT_OFF_CAPTURES
                   == (int)offsetof(zx_fault_record_t, zx_fault_captures),
               "zx_fault_record_t has moved under zx_trap_handler.S");
_Static_assert(ZX_ASM_FAULT_OFF_VECTOR
                   == (int)offsetof(zx_fault_record_t, zx_fault_vector),
               "zx_fault_record_t has moved under zx_trap_handler.S");
_Static_assert(ZX_ASM_FAULT_OFF_HSR
                   == (int)offsetof(zx_fault_record_t, zx_fault_hsr),
               "zx_fault_record_t has moved under zx_trap_handler.S");
_Static_assert(ZX_ASM_FAULT_OFF_HPFAR
                   == (int)offsetof(zx_fault_record_t, zx_fault_hpfar),
               "zx_fault_record_t has moved under zx_trap_handler.S");
_Static_assert(ZX_ASM_FAULT_OFF_HDFAR
                   == (int)offsetof(zx_fault_record_t, zx_fault_hdfar),
               "zx_fault_record_t has moved under zx_trap_handler.S");
_Static_assert(ZX_ASM_FAULT_OFF_HIFAR
                   == (int)offsetof(zx_fault_record_t, zx_fault_hifar),
               "zx_fault_record_t has moved under zx_trap_handler.S");
_Static_assert(ZX_ASM_FAULT_OFF_ELR
                   == (int)offsetof(zx_fault_record_t, zx_fault_elr),
               "zx_fault_record_t has moved under zx_trap_handler.S");
_Static_assert(ZX_ASM_FAULT_OFF_SPSR
                   == (int)offsetof(zx_fault_record_t, zx_fault_spsr),
               "zx_fault_record_t has moved under zx_trap_handler.S");

/**************************************************************************/
/*                  Descriptor words, with the masking done               */
/**************************************************************************/

/* HPRBAR: BASE[31:6] | SH[4:3] | AP[2:1] | XN[0].  */

static uint32_t zx_region_bar(const zx_region_t *region_ptr)
{
    return (((uint32_t)region_ptr->zx_region_base & ZX_REGION_ADDR_MASK)
            | ((region_ptr->zx_region_sh & 0x3U) << ZX_HPRBAR_SH_SHIFT)
            | ((region_ptr->zx_region_ap & 0x3U) << ZX_HPRBAR_AP_SHIFT)
            | (region_ptr->zx_region_xn & ZX_HPRBAR_XN));
}


/* HPRLAR: LIMIT[31:6] | AttrIndx[3:1] | EN[0].

   The limit written here is the INCLUSIVE last byte with its low six bits
   masked off.  The hardware postfixes 0x3F to LIMIT[31:6] (the TRM's own
   words), so masking down and letting the hardware fill the low bits back in
   reproduces the caller's inclusive limit exactly -- while keeping those bits
   away from AttrIndx, which is the trap this masking exists for.  */

static uint32_t zx_region_lar(const zx_region_t *region_ptr, uint32_t enable)
{
    return (((uint32_t)region_ptr->zx_region_limit & ZX_REGION_ADDR_MASK)
            | ((region_ptr->zx_region_attrindx & 0x7U)
               << ZX_HPRLAR_ATTRINDX_SHIFT)
            | ((enable != 0U) ? ZX_HPRLAR_EN : 0U));
}


/**************************************************************************/
/*                     The register writes themselves                     */
/**************************************************************************/

static void zx_write_hprselr(uint32_t region)
{
    /* HPRSELR: p15, 4, c6, c2, 1.  REGION is [3:0] on a 16-region
       implementation and [4:0] on 20 or 24 (TRM Tables 3-84, 3-85).  Writing
       a value at or above the implemented count is UNPREDICTABLE, which is
       why every caller checks the count first rather than checking here --
       a check here could only fail after the fact.  */
    __asm__ volatile("mcr p15, 4, %0, c6, c2, 1" : : "r"(region) : "memory");
    __asm__ volatile("isb");
}


static void zx_write_hprbar(uint32_t value)
{
    /* HPRBAR, indirect: p15, 4, c6, c3, 0 */
    __asm__ volatile("mcr p15, 4, %0, c6, c3, 0" : : "r"(value) : "memory");
}


static void zx_write_hprlar(uint32_t value)
{
    /* HPRLAR, indirect: p15, 4, c6, c3, 1 */
    __asm__ volatile("mcr p15, 4, %0, c6, c3, 1" : : "r"(value) : "memory");
}


static uint32_t zx_read_hprbar(void)
{
    uint32_t value;

    __asm__ volatile("mrc p15, 4, %0, c6, c3, 0" : "=r"(value));

    return value;
}


static uint32_t zx_read_hprlar(void)
{
    uint32_t value;

    __asm__ volatile("mrc p15, 4, %0, c6, c3, 1" : "=r"(value));

    return value;
}


/**************************************************************************/
/*  zx_mair_program                                                       */
/*                                                                        */
/*  Must run before HSCTLR.M is set: a region whose AttrIndx selects an    */
/*  unprogrammed HMAIR byte gets Device-nGnRnE, which is conservative      */
/*  enough to look like it works and wrong enough to matter once caches    */
/*  are on.                                                                */
/**************************************************************************/

void zx_mair_program(void)
{
    uint32_t mair0 = ZX_HMAIR0_VALUE;
    uint32_t mair1 = ZX_HMAIR1_VALUE;

    /* HMAIR0: p15, 4, c10, c2, 0 -- HMAIR1: p15, 4, c10, c2, 1 */
    __asm__ volatile("mcr p15, 4, %0, c10, c2, 0" : : "r"(mair0) : "memory");
    __asm__ volatile("mcr p15, 4, %0, c10, c2, 1" : : "r"(mair1) : "memory");
    __asm__ volatile("isb");
}


/**************************************************************************/
/*  zx_stage2_region_program -- the indirect path, any region index.       */
/*                                                                        */
/*  BASE is written before LIMIT because LIMIT carries the enable bit.     */
/*  Writing LIMIT first would enable the region for the few cycles before  */
/*  BASE arrives, against whatever base the register happened to hold --   */
/*  and on a part with no region priority, one stray enabled region        */
/*  overlapping another is CONSTRAINED UNPREDICTABLE and aborts.           */
/**************************************************************************/

void zx_stage2_region_program(uint32_t index, const zx_region_t *region_ptr)
{
    if (region_ptr == (const zx_region_t *)0)
    {
        return;
    }

    zx_write_hprselr(index);
    zx_write_hprbar(zx_region_bar(region_ptr));
    zx_write_hprlar(zx_region_lar(region_ptr, 1U));
    __asm__ volatile("dsb");
    __asm__ volatile("isb");
}


/**************************************************************************/
/*  zx_stage2_region_read -- read one region back, indirect path.          */
/**************************************************************************/

void zx_stage2_region_read(uint32_t index, uint32_t *base_ptr,
                           uint32_t *limit_ptr)
{
    zx_write_hprselr(index);

    if (base_ptr != (uint32_t *)0)
    {
        *base_ptr = zx_read_hprbar();
    }

    if (limit_ptr != (uint32_t *)0)
    {
        *limit_ptr = zx_read_hprlar();
    }
}


/**************************************************************************/
/*  zx_stage2_region_program_direct16 / zx_stage2_region_read_direct16     */
/*                                                                        */
/*  Region 16 through the direct encoding: opc1 = 5, CRm = c8 + rrr where  */
/*  rrr = (16 - 16)[3:1] = 0, op2 = 0 for the even base and 1 for the even */
/*  limit (TRM 8.4).                                                       */
/*                                                                        */
/*  This exists to settle a contradiction in the TRM rather than because   */
/*  region 16 is special.  Section 3.3.48's prose says direct access is    */
/*  provided for HPRBAR0-HPRBAR15 only; section 8.4 and the c6 register    */
/*  summary both list HPRBAR16-HPRBAR24 at opc1 = 5.  If 8.4 is right the  */
/*  whole 20-region budget is directly addressable and the EL2 MPU escapes */
/*  the penalty measured at EL1 for reaching a high region through the     */
/*  selection register -- 542-604 cycles against 434-470 for a direct      */
/*  write.  That is a worst-case-execution-time fact, so it is settled by  */
/*  writing the encoding and reading it back through the OTHER path, which */
/*  is what the read-back below is for.                                    */
/*                                                                        */
/*  Only region 16 is implemented directly.  Generalising to 17-24 before  */
/*  the encoding is known to work would be building on the thing under     */
/*  test; that is step 3's job, once the answer is in.                     */
/**************************************************************************/

void zx_stage2_region_program_direct16(const zx_region_t *region_ptr)
{
    uint32_t bar;
    uint32_t lar;

    if (region_ptr == (const zx_region_t *)0)
    {
        return;
    }

    bar = zx_region_bar(region_ptr);
    lar = zx_region_lar(region_ptr, 1U);

    /* HPRBAR16: p15, 5, c6, c8, 0 -- HPRLAR16: p15, 5, c6, c8, 1 */
    __asm__ volatile("mcr p15, 5, %0, c6, c8, 0" : : "r"(bar) : "memory");
    __asm__ volatile("mcr p15, 5, %0, c6, c8, 1" : : "r"(lar) : "memory");
    __asm__ volatile("dsb");
    __asm__ volatile("isb");
}


void zx_stage2_region_read_direct16(uint32_t *base_ptr, uint32_t *limit_ptr)
{
    uint32_t bar;
    uint32_t lar;

    __asm__ volatile("mrc p15, 5, %0, c6, c8, 0" : "=r"(bar));
    __asm__ volatile("mrc p15, 5, %0, c6, c8, 1" : "=r"(lar));

    if (base_ptr != (uint32_t *)0)
    {
        *base_ptr = bar;
    }

    if (limit_ptr != (uint32_t *)0)
    {
        *limit_ptr = lar;
    }
}


/**************************************************************************/
/*                                HPRENR                                  */
/**************************************************************************/

uint32_t zx_hprenr_read(void)
{
    uint32_t value;

    /* HPRENR: p15, 4, c6, c1, 1 */
    __asm__ volatile("mrc p15, 4, %0, c6, c1, 1" : "=r"(value));

    return value;
}


void zx_hprenr_write(uint32_t value)
{
    __asm__ volatile("mcr p15, 4, %0, c6, c1, 1" : : "r"(value) : "memory");
    __asm__ volatile("dsb");
    __asm__ volatile("isb");
}


void zx_hprenr_enable(uint32_t index)
{
    zx_hprenr_write(zx_hprenr_read() | (1U << index));
}


void zx_hprenr_disable(uint32_t index)
{
    zx_hprenr_write(zx_hprenr_read() & ~(1U << index));
}


/**************************************************************************/
/*  zx_el2_mpu_enable                                                     */
/*                                                                        */
/*  HSCTLR.BR and HSCTLR.M: the EL2-controlled MPU, governing EL2's OWN    */
/*  accesses.  Stage 2 for EL0/EL1 is a separate bit and a separate        */
/*  function; see zx_stage2_enable below.                                 */
/*                                                                        */
/*  BR is set in the same write as M, deliberately.  With M set and BR     */
/*  clear, EL2's own accesses to its code, data and stack would hit no     */
/*  programmable region and fault -- the hypervisor would abort on its own */
/*  next instruction fetch, which is the least debuggable failure this     */
/*  file can produce.  BR does NOT relax anything for EL0/EL1, which fault */
/*  on a miss regardless of it; that asymmetry is decision D2.             */
/*                                                                        */
/*  WHY THIS IS CALLED BEFORE THE CONSOLE.  BR grants permission, not      */
/*  attributes.  The background map is Normal cacheable below 0x60000000,  */
/*  and Normal memory permits gathering and reordering even with caches    */
/*  off -- which corrupts a polled UART's register protocol.  On the       */
/*  S32Z280 the console sits at 0x42980000, inside that band, and the      */
/*  first version of this port printed its whole identity block as         */
/*  legible-but-wrong text: characters intermittently corrupted, looking   */
/*  for all the world like a marginal baud rate.  Programming the          */
/*  console's Device-attributed region and setting M before the first      */
/*  print is the fix.  The FVP cannot show you any of this -- its console  */
/*  is semihosting, and even its UART is in the Device band.               */
/**************************************************************************/

void zx_el2_mpu_enable(void)
{
    uint32_t hsctlr;

    __asm__ volatile("dsb");

    hsctlr = zx_read_hsctlr();
    hsctlr |= (ZX_HSCTLR_BR | ZX_HSCTLR_M);
    __asm__ volatile("mcr p15, 4, %0, c1, c0, 0" : : "r"(hsctlr) : "memory");
    __asm__ volatile("isb");
}


/**************************************************************************/
/*  zx_stage2_enable                                                      */
/*                                                                        */
/*  HCR.VM, which is what makes the EL2 region set apply to EL0/EL1 as     */
/*  stage 2.  The order is the whole content of this function:             */
/*                                                                        */
/*    DSB          every region write must be complete first.             */
/*    HCR.VM       stage 2 for EL0/EL1.                                   */
/*    ISB                                                                  */
/*                                                                        */
/*  HSCTLR.M is asserted rather than set here: reaching this with the EL2  */
/*  MPU still disabled would mean HCR.VM took effect against a region set  */
/*  the hardware is not consulting, and the payload would run with no      */
/*  protection at all while every check appeared to pass.  So it refuses.  */
/*                                                                        */
/*  Setting HCR.VM with no region covering the payload's code faults at    */
/*  the ERET target.  That presents as "the guest never started" and looks */
/*  nothing like a memory-protection problem, which is why the region      */
/*  writes are a precondition of calling this rather than part of it.      */
/**************************************************************************/

void zx_stage2_enable(void)
{
    uint32_t hcr;

    if ((zx_read_hsctlr() & ZX_HSCTLR_M) == 0U)
    {
        zx_console_puts(
            "\n  *** REFUSING to set HCR.VM: the EL2 MPU (HSCTLR.M) is still\n"
            "  *** disabled, so stage 2 would apply a region set the hardware\n"
            "  *** is not consulting.  The payload would run UNPROTECTED while\n"
            "  *** every check appeared to pass.  Call zx_el2_mpu_enable first.\n");
        return;
    }

    __asm__ volatile("dsb");

    hcr = zx_read_hcr();
    hcr |= ZX_HCR_VM;
    __asm__ volatile("mcr p15, 4, %0, c1, c1, 0" : : "r"(hcr) : "memory");
    __asm__ volatile("isb");
}


/**************************************************************************/
/*  zx_stage2_disable -- the reverse order, for the same reason.           */
/**************************************************************************/

void zx_stage2_disable(void)
{
    uint32_t hsctlr;
    uint32_t hcr;

    __asm__ volatile("dsb");

    hcr = zx_read_hcr();
    hcr &= ~(uint32_t)ZX_HCR_VM;
    __asm__ volatile("mcr p15, 4, %0, c1, c1, 0" : : "r"(hcr) : "memory");
    __asm__ volatile("isb");

    hsctlr = zx_read_hsctlr();
    hsctlr &= ~(uint32_t)(ZX_HSCTLR_BR | ZX_HSCTLR_M);
    __asm__ volatile("mcr p15, 4, %0, c1, c0, 0" : : "r"(hsctlr) : "memory");
    __asm__ volatile("isb");
}
