/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_timer.c                                           Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The generic timer at EL2.  Three timer interrupts arrive as PPIs:   */
/*    physical 30, virtual 27, hypervisor 26.                             */
/*                                                                        */
/*    ZoneX drives the partition tick from the HYPERVISOR timer (PPI 26)  */
/*    and leaves the virtual timer (PPI 27) to guests, giving each        */
/*    partition its own CNTVOFF so that guest time freezes while the      */
/*    partition is descheduled.  See docs/decisions.md D7.                */
/*                                                                        */
/*    This translation unit is deliberately empty of implementation.      */
/*    See docs/armv8r-el2-reference.md for the verified register sheet    */
/*    the code that lands here must be written against.                   */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"
