/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_timer.c                                           Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The generic timer at EL2.  Three timer interrupts arrive as PPIs:   */
/*    physical 30, virtual 27, hypervisor 26.                             */
/*                                                                        */
/*    ZoneX drives the partition tick from the HYPERVISOR timer (PPI 26)  */
/*    and leaves the virtual timer (PPI 27) to guests, giving each        */
/*    partition its own CNTVOFF so that guest time freezes while the      */
/*    partition is descheduled.  See docs/decisions.md D7.                */
/*                                                                        */
/*    Two jobs, and they are not the same kind of thing.                  */
/*                                                                        */
/*      zx_el2_prepare_guest_el1  the EL2-only configuration a guest       */
/*                                needs and cannot perform itself.        */
/*      the CNTVOFF bookkeeping   the mechanism that makes a descheduled   */
/*                                partition's clock FROZEN rather than     */
/*                                merely unread.                          */
/*                                                                        */
/*    THE PARTITION TICK IS NOW HERE TOO: CNTHP, the hypervisor's own      */
/*    timer on PPI 26, armed with an ABSOLUTE deadline in CNTHP_CVAL.      */
/*    It does NOT need HCR.IMO, which would route every guest IRQ to EL2   */
/*    as well.  Routing is by exception TYPE, so the tick goes in GROUP 0, */
/*    arrives as an FIQ, and HCR.FMO alone brings it to EL2 while guest    */
/*    IRQs stay with EL1.  With FMO set, PSTATE.F is IGNORED at EL1, so a  */
/*    partition cannot mask the interrupt that ends its own window.        */
/*    See docs/decisions.md D24 and D25.                                   */
/*                                                                        */
/*    THE PER-PARTITION HALF OF THE CNTVOFF BOOKKEEPING MOVED OUT.  The    */
/*    statics below are one partition's worth and serve the images that    */
/*    launch a single guest.  Once there is more than one partition, "when */
/*    did this partition stop" is partition state and belongs in its       */
/*    context block; zx_context.c holds that version, using the same       */
/*    arithmetic against the same register.                                */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Directive 4.3 -- each asm statement below is one coprocessor        */
/*      operation in a function that does nothing else.                   */
/*                                                                        */
/**************************************************************************/

#include "zx_port.h"

/* HCPTR.TCP10 and TCP11 trap EL1 and EL0 access to CP10 and CP11 -- the
   floating-point unit -- to EL2.  Both reset SET.  */

#define ZX_HCPTR_TCP        (ZX_C32(0x3) << 10)

/* CNTV_CTL, which is EL1's register and is written from here only to STOP a
   partition's timer.  ENABLE and IMASK are both cleared: masking alone would
   leave the comparator running and its ISTATUS set, so a guest re-entered
   later would find a timer it had not armed already expired.  */

#define ZX_CNTV_CTL_ENABLE  ZX_BIT(0)
#define ZX_CNTV_CTL_IMASK   ZX_BIT(1)

/* CNTHP_CTL, the HYPERVISOR timer's control register, whose three bits sit
   in the same places as the virtual timer's.  ISTATUS is READ-ONLY and says
   whether the comparator has been reached: it is the difference between "the
   window boundary has arrived" and "some other FIQ did", which is worth
   asking rather than assuming when a single vector serves both.  */

#define ZX_CNTHP_CTL_ISTATUS    ZX_BIT(2)

/* How long to spin looking for the physical counter to move.  The counter
   runs at 8 MHz on one target and 100 MHz on the other, so a counter that is
   running advances within a handful of iterations at either; the bound is
   generous because its only job is to be FINITE.  */

#define ZX_COUNTER_MOVE_GUARD   100000U

/* And the bound on a deliberate dwell.  Generous, because its only job is
   to be finite: the caller has already been told whether the counter runs,
   and a dwell that fell out here would mean it stopped in between.  */

#define ZX_DWELL_GUARD          100000000U

/* Where the partition's virtual time was when it was last frozen.  One
   partition's worth, because ZoneX runs one at a time and
   zx_el2_run_payload cannot nest -- the same constraint, in the same place,
   and when it becomes an array indexed by partition this does too.  */

static uint64_t zx_guest_time_frozen_at;

/* And what the partition's OWN clock read at that instant.
 *
 * The pair is what makes the freeze checkable rather than merely done.
 * CNTVOFF is a STATIC offset, so while a partition is suspended the physical
 * counter moves and the offset does not: the subtraction drifts for exactly
 * as long as the partition is away, and only the write on RESUME closes it.
 * Sampling the virtual counter anywhere in between therefore measures the
 * drift and not the correction -- which is how the first version of the
 * preemptive image reported a partition's clock advancing by the whole gap
 * on a run where the freeze was working perfectly.
 *
 * So the instant a partition STOPPED is recorded here, in the same breath as
 * the physical count, and the invariant a caller can check is exact: the
 * partition's virtual count after a resume equals this.  */

static uint64_t zx_guest_virtual_at_freeze;

/* And where the physical counter was when the partition was given the core
   back.  The pair (suspended_at, resumed_at) is the interval the partition
   was excluded from, as the MECHANISM measured it -- which is what CNTVOFF
   is credited with, and therefore what a check of the freeze has to compare
   the offset's movement against.

   Reading the counter again from outside instead does NOT give the same
   number, and the difference is not noise to be ignored: on the S32Z280 a
   CNTPCT read crosses into an 8 MHz clock domain, so the handful of reads
   between the resume and the check cost 64 counts of real time.  A check
   built on that would be comparing the freeze against the cost of measuring
   the freeze.  */

static uint64_t zx_guest_time_resumed_at;


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_prepare_guest_el1                             Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The EL2-only configuration a guest needs and cannot perform itself.  */
/*                                                                        */
/*    WHY THIS FUNCTION EXISTS AT ALL.  A standalone Cortex-R52 kernel     */
/*    resets INTO EL2 and does this work in its own boot path.  Built as a */
/*    guest it skips that block entirely -- which is the whole point of    */
/*    the port's TX_R52_BOOT_AT_EL1 option -- so the work does not stop    */
/*    being necessary, it changes owner.  This is that list, and it is     */
/*    deliberately short:                                                  */
/*                                                                        */
/*      HCPTR.TCP10/TCP11  cleared, so a guest may use its FPU without     */
/*                         every access trapping to EL2.                   */
/*      CNTFRQ             programmed, because it is writable only at the  */
/*                         highest implemented exception level and reads   */
/*                         ZERO out of reset on both ZoneX targets.  Any   */
/*                         guest computing a tick interval from it would   */
/*                         divide by zero.                                 */
/*                                                                        */
/*    AND ONE THING DELIBERATELY NOT DONE.  CNTHCTL.PL1PCTEN and PL1PCEN   */
/*    stay CLEAR, so EL1 cannot reach the physical counter or the physical */
/*    timer.  A standalone kernel opens both; a partition must not have    */
/*    them, because a partition's PHYSICAL time keeps running while it is  */
/*    descheduled and a guest reading it can therefore observe that it was */
/*    not running.  That observation is the temporal-determinism claim,    */
/*    lost.  Guests get the VIRTUAL timer with a per-partition CNTVOFF     */
/*    instead, which is what freezes a descheduled partition's clock --    */
/*    see docs/decisions.md D7.  The virtual counter needs no enable here. */
/*                                                                        */
/*    FLOATING POINT IS NOT YET PARTITION STATE.  Clearing the traps lets  */
/*    a guest use the FPU; nothing in ZoneX saves or restores FPEXC, FPSCR */
/*    or the D-registers across a partition switch.  With one partition    */
/*    that is exactly correct and with two it is a defect, so it is        */
/*    written down here rather than discovered by two guests sharing a     */
/*    register bank.                                                       */
/*                                                                        */
/**************************************************************************/

void zx_el2_prepare_guest_el1(uint32_t counter_hz)
{
    uint32_t hcptr;

    __asm__ volatile("mrc p15, 4, %0, c1, c1, 2" : "=r"(hcptr));
    hcptr &= ~(uint32_t)ZX_HCPTR_TCP;
    __asm__ volatile("mcr p15, 4, %0, c1, c1, 2" : : "r"(hcptr) : "memory");
    __asm__ volatile("isb");

    __asm__ volatile("mcr p15, 0, %0, c14, c0, 0"
                     : : "r"(counter_hz) : "memory");
    __asm__ volatile("isb");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_read_cntpct                                       Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The PHYSICAL counter, which no partition can reach.                 */
/*                                                                        */
/*    64-bit, so in AArch32 it is an MRRC into a register pair rather      */
/*    than an MRC.  The pair is not atomic across the halves on every      */
/*    implementation, which is why the low half is read first and the      */
/*    high half checked for a carry -- a naive read that caught the low    */
/*    half wrapping would produce a value roughly four billion counts in   */
/*    the past, and every interval computed from it would be nonsense.     */
/*                                                                        */
/**************************************************************************/

uint64_t zx_read_cntpct(void)
{
    uint32_t low;
    uint32_t high;
    uint32_t settled;

    /* Read until two consecutive reads agree about the HIGH half.  When they
       do, the low half that came with the second one belongs to it.  */

    __asm__ volatile("mrrc p15, 0, %0, %1, c14" : "=r"(low), "=r"(high));

    for (;;)
    {
        settled = high;

        __asm__ volatile("mrrc p15, 0, %0, %1, c14" : "=r"(low), "=r"(high));

        if (high == settled)
        {
            break;
        }
    }

    return ((uint64_t)high << 32) | (uint64_t)low;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_counter_is_running                                Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Whether the system counter is actually COUNTING.                    */
/*                                                                        */
/*    PROGRAMMING CNTFRQ DOES NOT START THE COUNTER, and the two are so    */
/*    easily confused that this function exists mostly to keep them apart. */
/*    CNTFRQ is a software-declared constant: nothing in either ZoneX      */
/*    target reports its own counter frequency, so CNTFRQ says only what   */
/*    somebody wrote there.  Whether the counter moves is a different      */
/*    question with a different answer, and on the Armv8-R AEM FVP the     */
/*    answer out of reset is NO -- the model leaves its counter stopped    */
/*    and documents that firmware is expected to start it.                 */
/*                                                                        */
/*    The consequence of not checking is the worst kind of failure this    */
/*    suite can produce: a guest that arms a timer, blocks waiting for it, */
/*    and is killed by a harness timeout that names nothing.  So the       */
/*    counter is read twice, with a BOUND, and a target whose counter is   */
/*    stopped produces a reported check failure instead.                   */
/*                                                                        */
/**************************************************************************/

uint32_t zx_counter_is_running(void)
{
    uint64_t first = zx_read_cntpct();
    uint32_t guard;

    for (guard = 0U; guard < ZX_COUNTER_MOVE_GUARD; guard++)
    {
        if (zx_read_cntpct() != first)
        {
            return 1U;
        }
    }

    return 0U;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_dwell                                         Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Spend a known interval at EL2, measured on the physical counter.    */
/*                                                                        */
/*    WHY A HYPERVISOR WOULD EVER DELIBERATELY WAIT.  It would not.  This */
/*    exists to make one claim MEASURABLE, and the claim is that a        */
/*    partition's clock does not advance while the partition is not       */
/*    running.  Checking that needs an interval in which the partition is */
/*    not running -- and the interval has to be REAL, or the check passes */
/*    for the wrong reason.                                               */
/*                                                                        */
/*    That is not hypothetical.  The first version of the preemptive      */
/*    image measured the gap across a block of console output, on the     */
/*    grounds that a polled UART is millions of cycles.  It is -- on      */
/*    SILICON.  On the Armv8-R AEM FVP the console is semihosting, which  */
/*    costs the model no simulated time at all, so the physical counter   */
/*    advanced by ZERO across the gap and the virtual counter advanced by */
/*    zero for that reason rather than because anything was frozen.  The  */
/*    check was green and the build that DELIBERATELY BREAKS the freeze   */
/*    was green with it.                                                  */
/*                                                                        */
/*    So the gap is made explicitly, in counter counts, and the image     */
/*    also asserts that the physical counter DID advance -- because a     */
/*    check whose subject did not happen is not a check.                  */
/*                                                                        */
/*    Bounded twice over: by the counter reaching its target, and by an   */
/*    iteration count, so that a stopped counter cannot turn this into a  */
/*    hang.  The caller has already been told whether the counter runs.   */
/*                                                                        */
/**************************************************************************/

void zx_el2_dwell(uint32_t counts)
{
    uint64_t target = zx_read_cntpct() + (uint64_t)counts;
    uint32_t guard;

    for (guard = 0U; guard < ZX_DWELL_GUARD; guard++)
    {
        if (zx_read_cntpct() >= target)
        {
            break;
        }
    }
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_guest_time_reset                              Cortex-R52     */
/*    zx_el2_guest_time_suspend                                           */
/*    zx_el2_guest_time_resume                                            */
/*    zx_el2_guest_time_offset                                            */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    CNTVOFF, which is the whole of temporal partitioning as a partition  */
/*    can observe it.                                                     */
/*                                                                        */
/*    A partition reads time through the VIRTUAL counter, and the virtual  */
/*    counter is defined as the physical one MINUS CNTVOFF.  CNTVOFF is    */
/*    writable only at EL2.  So the hypervisor can decide, exactly, what   */
/*    time a partition believes it is:                                    */
/*                                                                        */
/*      RESET    CNTVOFF = the physical count now, so the partition's own  */
/*               clock reads zero.  Done when a partition is loaded, so    */
/*               that every excursion of a guest begins from the same      */
/*               point on its own clock -- which is what makes two runs    */
/*               of one guest comparable at all.                          */
/*      SUSPEND  record where the physical counter was.  The partition's   */
/*               clock is now unchanging in the only sense that matters,   */
/*               because nothing of the partition is executing to read it. */
/*      RESUME   add everything that elapsed since to CNTVOFF.  The        */
/*               virtual counter therefore reads exactly what it read when */
/*               the partition stopped: from inside, no time passed.       */
/*                                                                        */
/*    WHY THE PHYSICAL TIMER COULD NOT DO THIS, which is D7 stated as      */
/*    mechanism rather than as policy: there is no CNTPOFF on this         */
/*    architecture.  Physical time is the system's and cannot be given a   */
/*    per-partition origin, so a guest on the physical timer would see the */
/*    gaps -- and a partition that can observe that it was not running is  */
/*    a partition whose worst-case execution time cannot be argued about   */
/*    from the inside.  ZoneX therefore leaves CNTHCTL.PL1PCTEN and        */
/*    PL1PCEN clear (D23) and hands out the virtual timer instead.         */
/*                                                                        */
/*    WITH ONE PARTITION THE GAP BEING CLOSED IS THE HYPERVISOR'S OWN      */
/*    WORK -- printing a report between two excursions, which on a polled  */
/*    UART is millions of cycles.  That is a small demonstration of a      */
/*    mechanism whose real use is the next one: with two partitions the    */
/*    gap is the other partition's window, and closing it is what makes    */
/*    the two clocks independent.                                         */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Directive 4.3 -- CNTVOFF is reachable only through a 64-bit          */
/*      coprocessor transfer, and every such access is encapsulated in     */
/*      one of the two one-line accessors below.                           */
/*                                                                        */
/**************************************************************************/

static uint64_t zx_read_cntvoff(void)
{
    uint32_t low;
    uint32_t high;

    __asm__ volatile("mrrc p15, 4, %0, %1, c14" : "=r"(low), "=r"(high));

    return ((uint64_t)high << 32) | (uint64_t)low;
}


static void zx_write_cntvoff(uint64_t value)
{
    uint32_t low  = (uint32_t)(value & 0xFFFFFFFFU);
    uint32_t high = (uint32_t)(value >> 32);

    __asm__ volatile("mcrr p15, 4, %0, %1, c14"
                     : : "r"(low), "r"(high) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


void zx_el2_guest_time_reset(void)
{
    uint64_t now = zx_read_cntpct();

    zx_write_cntvoff(now);
    zx_guest_time_frozen_at    = now;
    zx_guest_time_resumed_at   = now;
    zx_guest_virtual_at_freeze = 0U;
}


void zx_el2_guest_time_suspend(void)
{
    zx_guest_time_frozen_at    = zx_read_cntpct();
    zx_guest_virtual_at_freeze = zx_guest_time_frozen_at - zx_read_cntvoff();
}


static void zx_el2_guest_time_resume_inner(uint32_t credit)
{
    uint64_t now = zx_read_cntpct();

    /* The elapsed time is ADDED rather than the offset being recomputed from
       scratch, because "how much time has this partition been given" is
       cumulative and recomputing it would silently reset the partition's
       clock on every entry -- which would look like a working freeze and
       would in fact be a partition whose time never advances at all.

       A resume that was never preceded by a suspend adds nothing: both were
       set together by the reset above, so the subtraction is zero.  */

    if ((credit != 0U) && (now > zx_guest_time_frozen_at))
    {
        zx_write_cntvoff(zx_read_cntvoff() + (now - zx_guest_time_frozen_at));
    }

    /* THE BOOKKEEPING HAPPENS EITHER WAY, and that is the whole reason the
       uncredited variant exists rather than the caller simply not calling.
       These two words are what a check of the freeze is measured against; a
       path that left them stale would make the MEASUREMENT undefined instead
       of making the MECHANISM wrong, and a negative build has to do the
       second.  The first version of the broken build skipped the call
       outright, and its "the partition could not observe the gap" check then
       passed -- comparing a real interval against the time since boot.  */

    zx_guest_time_resumed_at = now;
    zx_guest_time_frozen_at  = now;
}


void zx_el2_guest_time_resume(void)
{
    zx_el2_guest_time_resume_inner(1U);
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_guest_time_resume_uncredited                  Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    A resume that does NOT give the partition back the time it spent    */
/*    descheduled.  It exists so that the freeze can be seen to fail.     */
/*                                                                        */
/*    A claim whose pass condition is "the guest could not tell it was    */
/*    descheduled" has to be capable of failing, or a green run shows     */
/*    only that the arithmetic did not crash.  This is the defect, made   */
/*    reproducible: everything else about the partition is identical, and */
/*    its clock counts every cycle the hypervisor spent between two       */
/*    windows.                                                            */
/*                                                                        */
/*    It keeps the BOOKKEEPING, which is what makes it a broken mechanism */
/*    rather than a missing one.  Simply not resuming would leave the     */
/*    recorded instants stale, and the observable check would then be     */
/*    comparing a real interval against the time since boot -- passing    */
/*    for a reason that has nothing to do with the freeze.  That was      */
/*    observed before this function existed.                              */
/*                                                                        */
/**************************************************************************/

void zx_el2_guest_time_resume_uncredited(void)
{
    zx_el2_guest_time_resume_inner(0U);
}


uint64_t zx_el2_guest_time_offset(void)
{
    return zx_read_cntvoff();
}


uint64_t zx_el2_guest_virtual_count(void)
{
    return zx_read_cntpct() - zx_read_cntvoff();
}


uint64_t zx_el2_guest_time_suspended_at(void)
{
    return zx_guest_time_frozen_at;
}


uint64_t zx_el2_guest_virtual_when_suspended(void)
{
    return zx_guest_virtual_at_freeze;
}


uint64_t zx_el2_guest_time_resumed_at(void)
{
    return zx_guest_time_resumed_at;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_guest_timer_stop                              Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Disarm a partition's virtual timer, from EL2.                       */
/*                                                                        */
/*    WHY THE HYPERVISOR DOES THIS AND NOT THE GUEST.  A partition can be  */
/*    taken from at any instant -- by a stage-2 violation, and later by a  */
/*    window expiring -- including with its timer armed.  The generic      */
/*    timer asserts a LEVEL, so an expired comparator holds the PPI        */
/*    asserted at the GIC indefinitely.  Nothing bad happens while the     */
/*    hypervisor is running, because EL2 keeps PSTATE.I set and could not  */
/*    take it anyway; the damage is at the NEXT ERET into a guest, which   */
/*    would be interrupted before it had reinitialised its own kernel.     */
/*                                                                        */
/*    BOTH BITS ARE CLEARED, not just ENABLE.  Setting IMASK alone leaves  */
/*    the comparator running and its ISTATUS set, so a guest re-entered    */
/*    later would find a timer it never armed already expired -- which is  */
/*    a tick it did not schedule, arriving at a moment it did not choose.  */
/*                                                                        */
/*    THIS IS PER-GUEST STATE and it is named here as such, because the    */
/*    same is true of CNTV_CVAL and CNTV_TVAL: a partition switch that     */
/*    saved neither would hand the next partition the previous one's       */
/*    deadline.  Stopping the timer makes that harmless for one partition  */
/*    and does not make it correct for two.                                */
/*                                                                        */
/**************************************************************************/

void zx_el2_guest_timer_stop(void)
{
    uint32_t control;

    /* Read-modify-write rather than a store of zero.  ISTATUS is read-only
       and the other twenty-nine bits are reserved today, so the two are the
       same instruction sequence with the same effect -- and a store would
       stop being equivalent the day the architecture defines one of them.
       Naming the two bits being cleared is also what makes the paragraph
       above checkable against the code.  */

    __asm__ volatile("mrc p15, 0, %0, c14, c3, 1" : "=r"(control));
    control &= ~(uint32_t)(ZX_CNTV_CTL_ENABLE | ZX_CNTV_CTL_IMASK);
    __asm__ volatile("mcr p15, 0, %0, c14, c3, 1"
                     : : "r"(control) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_hyp_timer_arm                                 Cortex-R52     */
/*    zx_el2_hyp_timer_stop                                              */
/*    zx_el2_hyp_timer_fired                                             */
/*    zx_el2_hyp_timer_deadline                                          */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    CNTHP, the hypervisor's own timer, and the interrupt that ends a    */
/*    partition's window.                                                 */
/*                                                                        */
/*    CNTHP_CVAL AND NOT CNTHP_TVAL, and the difference is the whole       */
/*    determinism claim.  TVAL is a 32-bit DOWN-COUNT loaded relative to   */
/*    now: re-arming it inside the handler adds the handler's own latency  */
/*    to every window, so a frame declared as 10 ms becomes 10 ms plus     */
/*    the switch, cumulatively, for the life of the run.  The schedule     */
/*    still looks fixed, the windows stay in the right proportion, and     */
/*    the frame slowly stops being the length it was declared to be.       */
/*    CVAL is a 64-bit ABSOLUTE comparison against the physical counter,   */
/*    so the switch's own cost comes out of the window it happens in.      */
/*                                                                        */
/*    The one place TVAL would have been simpler is the reason it is       */
/*    worth naming: re-arming a guest's virtual timer inside its own       */
/*    handler IS one TVAL write with no counter read and no 64-bit         */
/*    arithmetic, which is why the guest side of this suite uses it.  The  */
/*    hypervisor's frame is the opposite case and needs the opposite       */
/*    register.                                                           */
/*                                                                        */
/*    AGAINST THE PHYSICAL COUNTER, which is what makes the frame          */
/*    something no partition can move.  A partition can be given any       */
/*    virtual time the hypervisor likes; it cannot touch CNTPCT, and       */
/*    CNTHCTL.PL1PCTEN is left clear so it cannot even read it.            */
/*                                                                        */
/*    THE RETURN VALUE IS NOT DECORATION.  Arming a comparator with a      */
/*    count already in the past leaves the interrupt permanently pending:  */
/*    the window was shorter than its own partition switch.  Nothing       */
/*    breaks -- the schedule keeps turning and every frame takes longer    */
/*    than declared -- which is exactly why it has to be reported rather   */
/*    than absorbed.  The caller decides what to do about it, because the  */
/*    caller is the one holding the schedule that has to record it.        */
/*                                                                        */
/*    THE COUNTER IS READ ONCE, AFTER THE WRITE.  On the S32Z280 a CNTPCT  */
/*    read crosses into an 8 MHz clock domain and costs about 93 counts of */
/*    real time, so reading it twice to "check" the arming would report a  */
/*    miss that the checking itself caused.  One read, taken after the     */
/*    comparator is set, is both the cheapest and the only honest answer.  */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Directive 4.3 -- CNTHP_CVAL is reachable only through a 64-bit       */
/*      coprocessor transfer, encapsulated here.                           */
/*                                                                        */
/**************************************************************************/

static uint64_t zx_hyp_timer_armed_for;


uint32_t zx_el2_hyp_timer_arm(uint64_t deadline)
{
    uint32_t low  = (uint32_t)(deadline & 0xFFFFFFFFU);
    uint32_t high = (uint32_t)(deadline >> 32);
    uint32_t control;

    /* The comparator FIRST, then the enable.  Written the other way round
       the timer is enabled for the few cycles it takes to write CVAL while
       the comparator still holds the PREVIOUS deadline -- which has already
       passed, so the level asserts and the interrupt is taken again
       immediately.  On a level-triggered PPI that is a storm rather than a
       glitch.  */

    __asm__ volatile("mcrr p15, 6, %0, %1, c14"
                     : : "r"(low), "r"(high) : "memory");     /* CNTHP_CVAL */

    control = ZX_CNTV_CTL_ENABLE;
    __asm__ volatile("mcr p15, 4, %0, c14, c2, 1"
                     : : "r"(control) : "memory");            /* CNTHP_CTL  */
    __asm__ volatile("isb" ::: "memory");

    zx_hyp_timer_armed_for = deadline;

    return (zx_read_cntpct() < deadline) ? 1U : 0U;
}


void zx_el2_hyp_timer_stop(void)
{
    uint32_t control;

    /* BOTH bits, for the same reason a guest's timer is stopped with both:
       masking alone leaves the comparator running with ISTATUS set, so the
       next thing to enable it finds a deadline it never chose already
       expired.  */

    __asm__ volatile("mrc p15, 4, %0, c14, c2, 1" : "=r"(control));
    control &= ~(uint32_t)(ZX_CNTV_CTL_ENABLE | ZX_CNTV_CTL_IMASK);
    __asm__ volatile("mcr p15, 4, %0, c14, c2, 1"
                     : : "r"(control) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


uint32_t zx_el2_hyp_timer_fired(void)
{
    uint32_t control;

    __asm__ volatile("mrc p15, 4, %0, c14, c2, 1" : "=r"(control));

    return ((control & (uint32_t)ZX_CNTHP_CTL_ISTATUS) != 0U) ? 1U : 0U;
}


uint64_t zx_el2_hyp_timer_deadline(void)
{
    return zx_hyp_timer_armed_for;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_route_fiq                                     Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    HCR.FMO: physical FIQ to EL2, physical IRQ left with EL1.           */
/*                                                                        */
/*    THE ONE BIT THE WHOLE OF TIME PARTITIONING RESTS ON.  With FMO set,  */
/*    PSTATE.F is IGNORED at EL0 and EL1 -- a partition cannot mask the    */
/*    interrupt that ends its own window, whatever its kernel does with    */
/*    its own masks and however tight a loop it is in.  A tick delivered   */
/*    as an IRQ could be deferred by any guest that disabled interrupts,   */
/*    which is precisely the property temporal partitioning is bought to   */
/*    have.                                                               */
/*                                                                        */
/*    ROUTING IS BY EXCEPTION TYPE AND NOT BY INTID, which is what makes   */
/*    this two register writes rather than a rewrite.  The hypervisor's    */
/*    own timer goes in GIC Group 0, which the GIC delivers as an FIQ, and */
/*    arrives here; every partition interrupt stays Group 1, stays an IRQ, */
/*    and is still delivered STRAIGHT to EL1 with no injection and no List */
/*    Register.  The guest side of the arrangement needed no change        */
/*    whatever.  See docs/decisions.md D24 and D25.                        */
/*                                                                        */
/*    HCR.IMO STAYS CLEAR, deliberately, and HCR.AMO with it.  AMO would   */
/*    route asynchronous aborts to EL2 -- where they arrive at the vector  */
/*    that today means "ZoneX faulted on its own access", so setting it    */
/*    without reworking that vector would report a guest's abort as a      */
/*    hypervisor bug.  Neither is needed for a window to end.              */
/*                                                                        */
/**************************************************************************/

void zx_el2_route_fiq(void)
{
    uint32_t hcr;

    __asm__ volatile("mrc p15, 4, %0, c1, c1, 0" : "=r"(hcr));
    hcr |= (uint32_t)ZX_HCR_FMO;
    __asm__ volatile("mcr p15, 4, %0, c1, c1, 0" : : "r"(hcr) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_deny_guest_fp                                 Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    HCPTR.TCP10/TCP11 SET, so a guest's floating-point access traps.    */
/*                                                                        */
/*    THE EXACT OPPOSITE OF WHAT zx_el2_prepare_guest_el1 DOES, and the    */
/*    reason is that the two functions serve systems with different        */
/*    numbers of partitions.                                              */
/*                                                                        */
/*    D23 recorded the consequence of opening the FPU before there was a   */
/*    second partition to make it matter: nothing in ZoneX saves or        */
/*    restores FPEXC, FPSCR or the D-registers across a switch.  With one  */
/*    partition that is exactly correct -- there is nobody to share the    */
/*    bank with.  With two it is two guests reading each other's           */
/*    registers, and the failure mode is a WRONG ANSWER rather than a      */
/*    fault: no exception, no log line, and a number that is somebody      */
/*    else's.                                                             */
/*                                                                        */
/*    ZoneX therefore DENIES the FPU to a time-partitioned system rather   */
/*    than saving it.  A guest that touches floating point takes an        */
/*    exception to EL2 with a syndrome naming the cause, which is a        */
/*    diagnosis; sharing the bank silently is not.  Saving the bank is a   */
/*    later-phase option and it is a real one -- sixteen double registers  */
/*    are two instructions -- but it needs the register file's width read  */
/*    from MVFR0 rather than assumed, and a partition switch is not the    */
/*    place to add an assumption about how many registers a part has.      */
/*                                                                        */
/*    Both bits, not one.  TCP10 and TCP11 gate the two coprocessor        */
/*    numbers the VFP and Advanced SIMD are reached through, and a guest   */
/*    that found one open would use it.                                    */
/*                                                                        */
/**************************************************************************/

void zx_el2_deny_guest_fp(void)
{
    uint32_t hcptr;

    __asm__ volatile("mrc p15, 4, %0, c1, c1, 2" : "=r"(hcptr));
    hcptr |= (uint32_t)ZX_HCPTR_TCP;
    __asm__ volatile("mcr p15, 4, %0, c1, c1, 2" : : "r"(hcptr) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_dwell_until                                   Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Spend counter counts at EL2 until an ABSOLUTE deadline.             */
/*                                                                        */
/*    The sibling of zx_el2_dwell, and the difference between them is the */
/*    difference between a measurement and a schedule.  zx_el2_dwell waits */
/*    for a DURATION, because a check of the freeze needs a gap of a known */
/*    size.  This one waits for an INSTANT, because a window that a        */
/*    partition handed back early has to end exactly where it would have   */
/*    ended -- at the boundary the frame's epoch already decided, not at   */
/*    "however long is left" computed from a counter read taken somewhere  */
/*    in the middle of a switch.                                          */
/*                                                                        */
/*    THIS IS WHAT AN IDLE PARTITION COSTS, and it is deliberate.  A       */
/*    static frame does not give a yielding partition's remaining time to  */
/*    its neighbour: doing so would make one partition's start time depend */
/*    on another's behaviour, which is the coupling temporal partitioning  */
/*    is bought to remove.  Trapping WFI to reclaim it is a later-phase    */
/*    option that trades determinism for throughput, and Phase 0 declines  */
/*    it.                                                                  */
/*                                                                        */
/*    Bounded twice over: by the deadline, and by an iteration count, so   */
/*    that a counter which stopped cannot turn a burned window into a      */
/*    hang.  A deadline already in the past returns immediately, which is  */
/*    the right answer -- there is nothing left of that window to spend.   */
/*                                                                        */
/**************************************************************************/

void zx_el2_dwell_until(uint64_t deadline)
{
    uint32_t guard;

    for (guard = 0U; guard < ZX_DWELL_GUARD; guard++)
    {
        if (zx_read_cntpct() >= deadline)
        {
            break;
        }
    }
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_el2_allow_guest_fp                                Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    HCPTR.TCP10/TCP11 cleared again, once no partition is running.      */
/*                                                                        */
/*    THIS EXISTS BECAUSE OF A MEASURED PROPERTY OF THE DEBUG CONNECTION,  */
/*    and it is worth the paragraph because the symptom names nothing.     */
/*                                                                        */
/*    With the floating-point traps SET, the S32Z280's debug probe cannot  */
/*    read the core's register file: gdb reports "Could not read           */
/*    registers; remote failure reply '01'" and the harness around it      */
/*    exits non-zero on a run whose own console said ALL CHECKS PASSED.    */
/*    Measured by comparison, on the board: an image that stops BEFORE the */
/*    traps are set produces no such error, and the same image stopping    */
/*    AFTER produces two.  The debugger reads the VFP registers as part of */
/*    the register file, and a trapped coprocessor is a coprocessor it     */
/*    cannot reach.                                                        */
/*                                                                        */
/*    THE ANSWER IS NOT TO STOP DENYING THE FPU.  The traps exist because  */
/*    nothing saves the register bank across a partition switch, so two    */
/*    guests would share it and the failure mode would be a wrong ANSWER   */
/*    rather than a fault.  What they protect is the interval in which     */
/*    PARTITIONS RUN, and that interval ends when the frame does.  So the  */
/*    traps are lifted once the last window has closed and before the      */
/*    hypervisor parks -- no partition can be sharing anything by then,    */
/*    and the machine is handed to whoever is reading it in the state they */
/*    can read.                                                            */
/*                                                                        */
/*    A harness that reports a passing run as a failure is the one         */
/*    outcome a regression must never have, in either direction: the same  */
/*    argument that put the verdict check inside the gdb script rather     */
/*    than in the shell around it.                                         */
/*                                                                        */
/**************************************************************************/

void zx_el2_allow_guest_fp(void)
{
    uint32_t hcptr;

    __asm__ volatile("mrc p15, 4, %0, c1, c1, 2" : "=r"(hcptr));
    hcptr &= ~(uint32_t)ZX_HCPTR_TCP;
    __asm__ volatile("mcr p15, 4, %0, c1, c1, 2" : : "r"(hcptr) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_pmu_core_hz                                       Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    What the CORE clock runs at, measured against the system counter.   */
/*                                                                        */
/*    WHY A CYCLE COUNT NEEDS THIS TO MEAN ANYTHING TO A READER.  Every    */
/*    figure this suite publishes about a partition switch is in CORE     */
/*    CYCLES, because cycles are the unit a worst-case-execution-time     */
/*    argument is made in and because CNTFRQ reads zero out of reset on   */
/*    both targets.  That is the right unit and it is not a self-         */
/*    contained one: "5,715 cycles" cannot be turned into a duration by   */
/*    anybody who does not know what the core is clocked at, and this     */
/*    part reports that nowhere.  A number a reader cannot convert is a   */
/*    number they cannot argue with, which is not the same as one they    */
/*    should accept.                                                      */
/*                                                                        */
/*    MEASURED, NOT LOOKED UP, and measured against the one frequency in  */
/*    this system that IS established: the counter's, which on the        */
/*    S32Z280 was pinned three independent ways -- against host wall      */
/*    clock over thirty-two seconds, from the RTU divider, and from the   */
/*    crystal the boot ROM's baud divisors confirm.  Reading a clock-tree */
/*    register instead would be reporting what somebody programmed rather */
/*    than what the core is doing.                                        */
/*                                                                        */
/*    ONE MILLISECOND OF COUNTER TIME by default, which is short enough   */
/*    that PMCCNTR cannot wrap -- it is 32 bits, so a core would have to  */
/*    exceed four terahertz -- and long enough that the two counter reads */
/*    at each end, which cost about 93 counts on this part, are a         */
/*    thousandth of the interval rather than a part of it.                */
/*                                                                        */
/*    Returns zero when the counter did not move or the cycle counter did */
/*    not advance, which are the two ways this can be asked of a machine  */
/*    that cannot answer -- and a zero a caller must check, because a     */
/*    frequency of zero would otherwise divide.                           */
/*                                                                        */
/**************************************************************************/

uint32_t zx_pmu_core_hz(uint32_t counter_hz, uint32_t counts)
{
    uint64_t started;
    uint64_t ended;
    uint32_t cycles_at_start;
    uint32_t cycles;
    uint64_t elapsed;

    if ((counter_hz == 0U) || (counts == 0U))
    {
        return 0U;
    }

    started         = zx_read_cntpct();
    cycles_at_start = zx_pmu_cycles();

    zx_el2_dwell_until(started + (uint64_t)counts);

    cycles = zx_pmu_cycles() - cycles_at_start;
    ended  = zx_read_cntpct();

    if (ended <= started)
    {
        return 0U;
    }

    elapsed = ended - started;

    /* cycles / elapsed x counter_hz, with the multiplication FIRST so that
       an integer division does not throw the ratio away before it is
       scaled.  In 64-bit throughout: the product reaches 10^13 on this
       part, which a 32-bit intermediate would wrap without any sign that
       it had.  */

    return (uint32_t)(((uint64_t)cycles * (uint64_t)counter_hz) / elapsed);
}
