/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_board.c                                        S32Z280-594EVB   */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    What the S32Z280-594EVB supplies to the shared stage-2 probe: a     */
/*    console on LINFlexD_9, and the two Device-attributed EL2 regions    */
/*    that the hypervisor's own MMIO needs because HSCTLR.BR grants       */
/*    permission and not attributes.                                     */
/*                                                                        */
/*    THE ORDER PROBLEM, and it is the interesting thing about this file. */
/*                                                                        */
/*    ZoneX prints its identity block BEFORE it programs any region, so   */
/*    the console has to work with no region covering it -- which it does */
/*    only because HSCTLR.BR=1 permits the access through the background  */
/*    map.  The attributes are wrong there (Normal Write-Through, from    */
/*    TRM Table 8-4) and the console works anyway while EL2's caches are  */
/*    off, which they are in this image.  So the Device region programmed */
/*    below is not what makes the console work today; it is what makes it */
/*    keep working once caches are turned on for the timing               */
/*    measurements.  Programming it now, and reporting that it was        */
/*    programmed, is what stops that from being discovered then.         */
/*                                                                        */
/*  BAUD RATE                                                             */
/*                                                                        */
/*    LINFlexD_9 is clocked by P5_LIN_BAUD_CLK, driven by MC_CGM_5 MUX 2. */
/*    Read from the board: MUX_2_CSS selects source 2 with the divider at */
/*    1, and the EVB carries a 40 MHz crystal (UG10268 3.3.1.1):          */
/*                                                                        */
/*        LFDIV   = 40000000 / (16 * 115200) = 21.7014                    */
/*        LINIBRR = 21                                                    */
/*        LINFBRR = round(0.7014 * 16) = 11                               */
/*        actual  = 40000000 / (16 * 21.6875) = 115274 baud, 0.06% error  */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Rule 11.4/11.6 -- casting integer addresses to volatile pointers is */
/*      inherent to memory-mapped device access; confined to ZX_REG32.    */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"
#include "zx_platform.h"

/* Register offsets, from the S32Z2 Reference Manual section 75.5.1.  */

#define ZX_LINFLEXD_LINCR1      0x00U
#define ZX_LINFLEXD_LINSR       0x08U
#define ZX_LINFLEXD_UARTCR      0x10U
#define ZX_LINFLEXD_UARTSR      0x14U
#define ZX_LINFLEXD_LINFBRR     0x24U
#define ZX_LINFLEXD_LINIBRR     0x28U
#define ZX_LINFLEXD_BDRL        0x38U

#define ZX_LINCR1_INIT          0x00000001U     /* initialisation mode       */

/* UARTCR.  PCE at bit 2 and TxEn at bit 4 are the two that matter here and
   are easy to transpose.

   ZX_UARTCR_PCE IS DEFINED AND NEVER USED, and that is deliberate.  MISRA
   C:2012 Rule 2.5 (advisory) says a project should contain no unused macro
   declaration; -Wunused-macros reports this one.  The deviation is taken
   because the bit's ABSENCE from the value written below is the decision --
   the BootROM leaves parity enabled and this console has to clear it (see
   the note at the write) -- and a bit that has to be off is worth naming at
   the same place as the bits that have to be on.  Naming it here is also
   what makes the transposition this comment warns about visible: PCE at
   bit 2 next to TXEN at bit 4, in one list, in register order.  */

#define ZX_UARTCR_UART          0x00000001U     /* UART rather than LIN mode */
#define ZX_UARTCR_WL0           0x00000002U     /* with WL1 clear: 8-bit     */
#define ZX_UARTCR_PCE           0x00000004U     /* parity enable -- see above */
#define ZX_UARTCR_TXEN          0x00000010U
#define ZX_UARTCR_RXEN          0x00000020U

#define ZX_UARTSR_DTF           0x00000002U     /* transmit complete, w1c    */

/* LINSR[15:12] is the LIN state; 0x1 is initialisation mode.  */

#define ZX_LINSR_LINS_MASK      0x0000F000U
#define ZX_LINSR_LINS_INIT      0x00001000U

/* Bounded rather than infinite: a console that hangs the boot is worse than
   one that reports it could not configure itself.  */

#define ZX_LINFLEXD_GUARD       100000U

#define ZX_LINFLEXD_IBRR_115200 21U
#define ZX_LINFLEXD_FBRR_115200 11U

#define ZX_CONSOLE_BASE         ZX_S32Z_LINFLEX_9_BASE

/* How many MMIO regions this board's hypervisor needs.  See the file
   header and docs/decisions.md D2.  */

#define ZX_S32Z_MMIO_REGIONS    2U

/**************************************************************************/
/*  zx_linflexd_configure_once                                            */
/*                                                                        */
/*  One full pass of the configuration sequence.  Called twice; see        */
/*  zx_board_console_init for why.                                        */
/**************************************************************************/

static void zx_linflexd_configure_once(void)
{
    uint32_t guard;
    uint32_t wanted;

    /* Enter initialisation mode and WAIT until the module reports it.  Most
       of UARTCR is writable only in initialisation mode, and the module does
       not enter it in the same cycle as the LINCR1 write.  Configuring
       without waiting silently HALF-works: bits being set take effect while
       bits being cleared do not, so PCE stays enabled and the line runs 8E1
       against a host expecting 8N1 -- which corrupts only those characters
       whose parity bit happens to be 0 and leaves the rest readable, looking
       for all the world like a marginal baud rate.  */

    ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_LINCR1) = ZX_LINCR1_INIT;

    guard = ZX_LINFLEXD_GUARD;
    while ((((ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_LINSR)
              & ZX_LINSR_LINS_MASK) != ZX_LINSR_LINS_INIT))
           && (guard > 0U))
    {
        guard--;
    }

    /* The UART bit gates writes to the rest of UARTCR, so it has to be set
       before the fields that depend on it, not alongside them.  */

    ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_UARTCR) = ZX_UARTCR_UART;

    /* 8N1, transmit and receive.  PCE deliberately left CLEAR: the BootROM
       enables parity for serial boot, and a host on 8N1 would see framing
       errors.  Inheriting the BootROM's register state would also make this
       image's behaviour depend on how the board was last booted.  */

    wanted = ZX_UARTCR_UART | ZX_UARTCR_WL0 | ZX_UARTCR_TXEN | ZX_UARTCR_RXEN;
    ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_UARTCR) = wanted;

    ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_LINFBRR) = ZX_LINFLEXD_FBRR_115200;
    ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_LINIBRR) = ZX_LINFLEXD_IBRR_115200;

    /* Leave initialisation mode; the module starts operating.  */

    ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_LINCR1) = 0U;
}


/**************************************************************************/
/*  zx_board_console_init                                                 */
/**************************************************************************/

void zx_board_console_init(void)
{
    /* The sequence runs TWICE, and one pass is genuinely not enough.  A
       single pass gives a working console at -O0 and a corrupted one at -O2:
       every character partially wrong, while UARTCR, LINIBRR and LINFBRR all
       read back exactly the values written.  The registers are right and the
       line is wrong, so the failure is invisible to the caller -- the worst
       property a console can have, and here the console IS the test method.

       The mechanism is not understood.  Tested and rejected during the
       Cortex-R52 port work: a bound 100x larger on the initialisation-mode
       wait, settling delays before the first LINSR read and after leaving
       initialisation mode, a barrier and read-back between the two UARTCR
       writes, and waiting for LINSR to report the exit from initialisation
       mode.  None of those makes a single pass work at -O2.  A second pass
       does, reliably, at both optimisation levels.  Verified on the
       S32Z280-594EVB.  If the underlying behaviour is ever identified,
       revisit this.  */

    zx_linflexd_configure_once();
    zx_linflexd_configure_once();
}


/**************************************************************************/
/*  zx_board_console_putc                                                 */
/**************************************************************************/

void zx_board_console_putc(char character)
{
    uint32_t guard;

    if (character == '\n')
    {
        zx_board_console_putc('\r');
    }

    /* Start the byte, wait for completion, clear the flag, then wait for the
       clear to actually take effect.

       The last step is the subtle one.  DTF is write-one-to-clear and does
       not de-assert in the same cycle as the clearing write, so without it
       the NEXT byte's poll can observe this byte's flag, conclude the line is
       free while it is still busy, and have its write silently dropped by the
       transmitter.  That cost exactly one character after every "\r\n" pair
       -- the only place two bytes go out back to back -- and showed up as the
       first letter of every line going missing.

       Clearing BEFORE the write instead does not fix it and is worse: the
       write then lands while the previous byte is still shifting and is
       dropped, and the poll afterwards sees the previous byte's completion,
       so most of the output disappears.  Order matters in both directions.  */

    ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_BDRL) =
        (uint32_t)(unsigned char)character;

    /* Polled on purpose: this console runs before any interrupt controller
       is configured, and it must work inside a fault handler.  */

    while ((ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_UARTSR) & ZX_UARTSR_DTF)
           == 0U)
    {
        /* wait for this byte to go out */
    }

    ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_UARTSR) = ZX_UARTSR_DTF;

    guard = ZX_LINFLEXD_GUARD;
    while (((ZX_REG32(ZX_CONSOLE_BASE + ZX_LINFLEXD_UARTSR) & ZX_UARTSR_DTF)
            != 0U) && (guard > 0U))
    {
        guard--;
    }
}


/**************************************************************************/
/*  zx_board_init                                                         */
/**************************************************************************/

void zx_board_init(void)
{
    /* Nothing beyond the console, which zx_console_puts brings up on first
       use.  The TCMs are deliberately left alone: this image places nothing
       in them, and a TCM whose region registers have been programmed but
       whose locations have not been written is a location that FAULTS on
       first read, because ECC is enabled on this part (Cortex-R52 TRM
       6.2.2).  Touching them would add a failure mode to an image whose
       whole purpose is to isolate one.  */

    zx_board_console_init();
}


/**************************************************************************/
/*  zx_board_mmio_region_count                                            */
/**************************************************************************/

uint32_t zx_board_mmio_region_count(void)
{
    return ZX_S32Z_MMIO_REGIONS;
}


/**************************************************************************/
/*  zx_board_program_mmio_regions                                         */
/*                                                                        */
/*  AP is ZX_AP_EL2_RW_GUEST_NONE -- 0b00 -- so a guest cannot reach       */
/*  either device.  That is the one thing AP at EL2 can usefully do: it    */
/*  cannot deny EL2, but it can deny EL0/EL1, and denying a partition the  */
/*  hypervisor's own console and the GIC is exactly what Phase 0 wants.    */
/**************************************************************************/

void zx_board_program_mmio_regions(uint32_t first_index)
{
    ZX_REGION region;
    uint32_t    console_index = first_index;
    uint32_t    gic_index     = first_index + 1U;

    /* LINFlexD_9, the hypervisor's console.  */

    region.zx_region_base     = (zx_addr_t)ZX_S32Z_LINFLEX_9_BASE;
    region.zx_region_limit    = (zx_addr_t)((ZX_S32Z_LINFLEX_9_BASE
                                             + ZX_S32Z_LINFLEX_9_SIZE) - 1UL);
    region.zx_region_ap       = ZX_AP_EL2_RW_GUEST_NONE;
    region.zx_region_xn       = ZX_XN_NEVER;
    region.zx_region_sh       = ZX_SH_NON_SHAREABLE;
    region.zx_region_attr_index = ZX_ATTR_DEVICE;
    zx_stage2_region_program(console_index, &region);

    /* The GIC.  Phase 0 configures no interrupts, and this region exists
       anyway: with the GIC region Normal, or unmapped with caches on, an
       access to it stalls this core outright -- no abort, no handler, and the
       debug connection drops.  Mapping it correctly from the first image is
       cheaper than diagnosing that later.  */

    region.zx_region_base     = (zx_addr_t)ZX_S32Z_GIC_BASE;
    region.zx_region_limit    = (zx_addr_t)((ZX_S32Z_GIC_BASE
                                             + ZX_S32Z_GIC_SIZE) - 1UL);
    region.zx_region_ap       = ZX_AP_EL2_RW_GUEST_NONE;
    region.zx_region_xn       = ZX_XN_NEVER;
    region.zx_region_sh       = ZX_SH_NON_SHAREABLE;
    region.zx_region_attr_index = ZX_ATTR_DEVICE;
    zx_stage2_region_program(gic_index, &region);

    /* NOTHING IS PRINTED HERE, deliberately.  This function runs BEFORE the
       EL2 MPU is enabled -- it is what makes enabling it useful -- so the
       console is still being reached through the background map as Normal
       memory, and anything written now comes out corrupted.  The first
       version of this file printed the two region indices here and they
       arrived as garbage in the middle of an otherwise clean log, which is
       the same bug reported as a defect in its own diagnosis.

       zx_probe_main.c names the index range once the console is trustworthy,
       and zx_board_report gives the two addresses.  */
}


/**************************************************************************/
/*  zx_board_report                                                       */
/**************************************************************************/

void zx_board_report(void)
{
    zx_console_puts(
        "\n--- what this target is ---\n"
        "  console: LINFlexD_9 at 0x42980000, polled, 115200 8N1.  LIN9 is\n"
        "           the instance wired to the daughtercard USB-UART through\n"
        "           jumper J248; LINFlexD_0 reaches no connector here.\n"
        "  code:    RTU0 code SRAM at 0x79900000, which is also this core's\n"
        "           reset address, so _start is linked first.\n"
        "  data:    RTU-local data SRAM at 0x31780000 (DRAM0+DRAM1, both at\n"
        "           full core speed).  RTU-local traffic never leaves the RTU.\n"
        "  NOTE:    this is REAL SILICON, and the numbers below are a part's\n"
        "           rather than a model's.  In particular HSCTLR.TE and\n"
        "           SCTLR.TE reset SET here, so an A32 vector table would\n"
        "           never run and every fault would present as a hang.\n"
        "  NOTE:    the console at 0x42980000 and the GIC at 0x47800000 both\n"
        "           fall in the NORMAL WRITE-THROUGH band of the background\n"
        "           map (TRM Table 8-4), not the Device band.  Each therefore\n"
        "           costs a Device-attributed EL2 region out of this part's\n"
        "           20 -- the constraint the FVP cannot show you.\n");
}


/**************************************************************************/
/*  zx_board_counter_hz                                                   */
/*                                                                        */
/*  See the note on ZX_S32Z_SYSTEM_COUNTER_HZ in zx_platform.h: measured    */
/*  three ways and cross-checked, because CNTFRQ is a software-declared    */
/*  constant that reads zero out of reset on this part.                    */
/**************************************************************************/

uint32_t zx_board_counter_hz(void)
{
    return (uint32_t)ZX_S32Z_SYSTEM_COUNTER_HZ;
}


/**************************************************************************/
/*  zx_board_counter_start                                                */
/*                                                                        */
/*  NOTHING TO DO, AND THE EMPTINESS IS THE FACT.                         */
/*                                                                        */
/*  This part's generic-timer counter is already running when ZoneX gets   */
/*  the core.  It is clocked by CNTCLKEN, which the RTU derives from a     */
/*  cluster clock through CFG_CNTDV -- a divider whose reset value is 4,   */
/*  so the divider is 5 and the 40 MHz crystal gives 8 MHz.  There is no   */
/*  counter control frame for a hypervisor to enable: the clock tree does  */
/*  it, before any software runs.                                          */
/*                                                                        */
/*  The Armv8-R AEM FVP is the opposite -- its counter is stopped at reset */
/*  and one register write starts it -- which is exactly why this is a     */
/*  board hook rather than something the shared code decides.  It is also  */
/*  why the CHECK is separate: zx_counter_is_running asks whether the      */
/*  counter moved, which is answered the same way on both boards and is    */
/*  the question a guest about to block on a timer actually cares about.   */
/**************************************************************************/

void zx_board_counter_start(void)
{
    /* Intentionally empty.  See above: this part has no counter control
       frame, and its counter is running before ZoneX exists.  */
}


/**************************************************************************/
/*  zx_board_gic_layout                                                   */
/*                                                                        */
/*  The three frames inside the 2 MB GIC window this board already maps    */
/*  Device-nGnRnE for EL2 only.  Naming them here rather than in the       */
/*  Cortex-R52 layer is what keeps that layer free of board addresses:     */
/*  the offsets inside a GICv3 are architectural and live there, the base  */
/*  is a board fact and lives here.                                        */
/**************************************************************************/

void zx_board_gic_layout(ZX_GIC_LAYOUT *layout_ptr)
{
    if (layout_ptr == (ZX_GIC_LAYOUT *)0)
    {
        return;
    }

    layout_ptr->zx_gic_dist_base = (zx_addr_t)ZX_S32Z_GICD_BASE;
    layout_ptr->zx_gic_rd_base   = (zx_addr_t)ZX_S32Z_GICR_RD_BASE;
    layout_ptr->zx_gic_sgi_base  = (zx_addr_t)ZX_S32Z_GICR_SGI_BASE;
}


/**************************************************************************/
/*  zx_board_describe_mmio_regions                                        */
/*                                                                        */
/*  The same two regions zx_board_program_mmio_regions writes, described   */
/*  so the validator can see them.  The duplication is deliberate and      */
/*  bounded: the programmer runs before the console exists and cannot      */
/*  report anything, while the validator runs later and needs the          */
/*  geometry as data.  Both read the same ZX_S32Z_* constants, so the one  */
/*  thing that could drift -- the addresses -- cannot.                     */
/**************************************************************************/

void zx_board_describe_mmio_regions(ZX_REGION *region_ptr)
{
    if (region_ptr == (ZX_REGION *)0)
    {
        return;
    }

    region_ptr[0].zx_region_base       = (zx_addr_t)ZX_S32Z_LINFLEX_9_BASE;
    region_ptr[0].zx_region_limit      = (zx_addr_t)((ZX_S32Z_LINFLEX_9_BASE
                                          + ZX_S32Z_LINFLEX_9_SIZE) - 1UL);
    region_ptr[0].zx_region_ap         = ZX_AP_EL2_RW_GUEST_NONE;
    region_ptr[0].zx_region_xn         = ZX_XN_NEVER;
    region_ptr[0].zx_region_sh         = ZX_SH_NON_SHAREABLE;
    region_ptr[0].zx_region_attr_index = (UCHAR)ZX_ATTR_DEVICE;

    region_ptr[1].zx_region_base       = (zx_addr_t)ZX_S32Z_GIC_BASE;
    region_ptr[1].zx_region_limit      = (zx_addr_t)((ZX_S32Z_GIC_BASE
                                          + ZX_S32Z_GIC_SIZE) - 1UL);
    region_ptr[1].zx_region_ap         = ZX_AP_EL2_RW_GUEST_NONE;
    region_ptr[1].zx_region_xn         = ZX_XN_NEVER;
    region_ptr[1].zx_region_sh         = ZX_SH_NON_SHAREABLE;
    region_ptr[1].zx_region_attr_index = (UCHAR)ZX_ATTR_DEVICE;
}
