/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_platform.h                                     S32Z280-594EVB   */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Memory map and peripheral addresses for the NXP S32Z280-594EVB,     */
/*    RTU0 core 0 (R52_0_0).                                              */
/*                                                                        */
/*    Every address below was either read out of the S32Z2 Reference      */
/*    Manual (S32Z27RM Rev. 5.1) or confirmed on the board during the     */
/*    Cortex-R52 port work, and the distinction matters: this part        */
/*    differs from the Armv8-R AEM FVP in ways that are SILENT rather     */
/*    than loud.  An address that is merely wrong tends to read back      */
/*    zero instead of faulting.                                          */
/*                                                                        */
/*  WHY THIS TARGET NEEDS TWO HYPERVISOR MMIO REGIONS AND THE FVP NEEDS   */
/*  NONE                                                                  */
/*                                                                        */
/*    HSCTLR.BR=1 lets EL2's own accesses fall back to the background     */
/*    map, which costs no region -- but BR grants PERMISSION, not         */
/*    ATTRIBUTES.  The background map is Normal, Write-Through cacheable  */
/*    from 0x40000000 to 0x5FFFFFFF (Cortex-R52 TRM Table 8-4), and both  */
/*    of this board's devices that ZoneX owns land in it:                 */
/*                                                                        */
/*      LINFlexD_9, the console      0x42980000                           */
/*      GIC                          0x47800000                           */
/*                                                                        */
/*    Reaching a memory-mapped device with cacheable attributes is not a  */
/*    working device; it is a bug that appears intermittently.  So each   */
/*    needs a Device-attributed EL2 region, and each one comes straight   */
/*    out of the 20-region budget the hypervisor shares with every        */
/*    partition.  On the FVP the same two devices sit in the Device band  */
/*    and the background map is accidentally correct, which is exactly    */
/*    why the model cannot validate this.  See docs/decisions.md D2.      */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_PLATFORM_H
#define ZX_PLATFORM_H

#define ZX_PLATFORM_NAME    "NXP S32Z280-594EVB, RTU0 core 0 (R52_0_0)"

/* Code SRAM, instruction-fetch view.  7 MB.  This is where the core resets
   to -- MC_ME_PRTN0_CORE0_ADDR reads 0x79900000 on this board -- so whatever
   lands at the start of it is what executes, and _start has to be there.
   [verified on board]  */

#define ZX_S32Z_CODE_SRAM_BASE      0x79900000UL
#define ZX_S32Z_CODE_SRAM_SIZE      0x00700000UL

/* The same physical SRAM seen as data, 0x32100000.  Recorded because a
   flash-booted image would have to be written through it; a debugger-loaded
   image does not need it, since the fetch window is writable over the debug
   AXI port even though NXP's memory map declares it read-only.
   [verified on board]  */

#define ZX_S32Z_CODE_SRAM_DATA_ALIAS 0x32100000UL

/* RTU-local data SRAM.  DRAM0 and DRAM1 are contiguous and both run at full
   core speed, which is what makes them the right home for .data, .bss, the
   Hyp stack and the payload's areas.  DRAM2 at 0x31800000 is half speed and
   unused here.  [S32Z27RM 6.3.6, confirmed on board]  */

#define ZX_S32Z_DATA_SRAM_BASE      0x31780000UL
#define ZX_S32Z_DATA_SRAM_SIZE      0x00080000UL    /* 512 KB */

/* Console.  LINFlexD_9, because the EVB user guide (UG10268) dedicates LIN9
   to the daughtercard USB-UART through jumper J248.  NOT LINFlexD_0: that is
   simply the first instance in the Reference Manual's list and reaches no
   connector on this board.  [RM + board]  */

/* What the system counter runs at, in Hz.
 *
 * NOT A GUESS, AND NOT READ FROM ANYWHERE.  CNTFRQ is a software-declared
 * constant: it reads zero out of reset on this silicon exactly as it does on
 * the model, and nothing in the part reports the frequency.  The number below
 * was established three ways during the Cortex-R52 port work and all three
 * agree: the counter was measured against host wall-clock time at 8.0227 MHz
 * over a 32-second interval; RTU.GPR CFG_CNTDV reads 4, so the divider is
 * (4 + 1) = 5; and the board's FXOSC is 40 MHz, itself confirmed
 * independently by the LINFlexD baud divisors the boot ROM left behind.
 * 40 / 5 = 8.
 *
 * It is here rather than in the port because it is a BOARD fact.  ZoneX
 * programs CNTFRQ from it before entering a guest, because CNTFRQ is writable
 * only at the highest implemented exception level -- so a guest built to boot
 * at EL1 cannot program it and would otherwise read zero.  */

#define ZX_S32Z_SYSTEM_COUNTER_HZ   8000000UL

#define ZX_S32Z_LINFLEX_9_BASE      0x42980000UL

/* The window ZoneX maps for it.  16 KB covers the register block with room
   to spare, is a whole number of 64-byte granules, and is small enough that
   nothing else the hypervisor might later want to map can collide with it --
   PMSAv8-R has no region priority, and two enabled regions matching one
   address abort on this part.  */

#define ZX_S32Z_LINFLEX_9_SIZE      0x00004000UL

/* GICv3 for this R52 cluster.  IMP_CBAR reports the distributor base in bits
   [31:21] and reads 0x47800000 on this board, which confirms NXP's map from
   the hardware -- the SoC reference manual gives no GIC address at all.
   Frame layout from Cortex-R52 TRM Table 9-1.  [verified on board]

   Mapped Device-nGnRnE.  With the region Normal, or with the MPU disabled, an
   access to it STALLS THE CORE outright on this part: no abort, no fault
   handler, and the debug connection drops.  That is the most expensive
   version of the D2 problem and it is the reason this region exists even
   though Phase 0 configures no interrupts.  */

#define ZX_S32Z_GIC_BASE            0x47800000UL
#define ZX_S32Z_GIC_SIZE            0x00200000UL    /* 2 MB */

/* The three frames inside it, at the offsets Cortex-R52 TRM Table 9-1 gives:
   the distributor at the base, then a redistributor made of TWO consecutive
   64 KB frames per core -- RD, which carries GICR_WAKER, and SGI, which
   carries the enable, group, priority and configuration bits for INTIDs 0 to
   31.  The same offsets as the Armv8-R AEM FVP's, which is not a coincidence:
   they are architectural, and only the base differs.

   ALL THREE STAY AT ZX_AP_EL2_RW_GUEST_NONE.  A partition reaches its own
   interrupt through system registers and needs none of this mapped -- and it
   must not have the SGI frame, which holds the enable bit for the
   hypervisor's own timer as well as its own.  See docs/decisions.md D24.  */

#define ZX_S32Z_GICD_BASE           (ZX_S32Z_GIC_BASE + 0x000000UL)
#define ZX_S32Z_GICR_RD_BASE        (ZX_S32Z_GIC_BASE + 0x100000UL)
#define ZX_S32Z_GICR_SGI_BASE       (ZX_S32Z_GIC_BASE + 0x110000UL)

/* Memory-mapped register access.
   MISRA C:2012 Rule 11.4/11.6 deviation: casting an integer address to a
   volatile pointer is inherent to memory-mapped device access.  */

#define ZX_REG32(address)   (*(volatile uint32_t *)(uintptr_t)(address))


/* How many hypervisor MMIO region descriptors the example has to be able
   to hold.  LINFlexD_9 and the GIC.  Must match zx_board_mmio_region_count().  */
#define ZX_BOARD_MAX_MMIO_REGIONS   2U

#endif /* ZX_PLATFORM_H */
