#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Entry point for the ZoneX NXP S32Z280-594EVB target.
#
#   run.sh build    cross-configure and build every image
#   run.sh test     build, then run on the board through the gdb harness
#
# "test" needs silicon.  A hosted CI runner has none, so this target is
# build-only in CI and "test" is a bench activity.  Two things that cost time
# on this board and are worth reading before running anything on it:
#
#   * On silicon the Windows-side CCS must be the process listening on 41475.
#     ss inside WSL2 cannot see it, so "nothing is listening" from inside WSL
#     is not evidence that nothing is.
#
#   * Never pipe a run through tail or head.  Redirect to a file and read the
#     file; the pipe truncates exactly the part that matters when a run hangs.
#
# STATUS: there are no images yet.  See test/fvp/run.sh for the same note.

set -euo pipefail

readonly ROOT="$(cd "$(dirname "$(realpath "$0")")/../.." && pwd)"
readonly BUILD="${ROOT}/build/s32z280"

command="${1:-build}"

configure() {
    cmake -S "${ROOT}" -B "${BUILD}" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="${ROOT}/cmake/cortex_r52.cmake" \
        -DCMAKE_BUILD_TYPE=Debug \
        -DZX_BUILD_FVP_EXAMPLE=OFF \
        -DZX_BUILD_S32Z280_EXAMPLE=ON
}

images() {
    ninja -C "${BUILD}" -t targets all 2>/dev/null \
        | grep -oE '^[A-Za-z0-9_]+\.elf' \
        | grep -v '^cmake_' | sort -u || true
}

case "${command}" in
    build|test)
        configure
        cmake --build "${BUILD}"

        image_list="$(images)"
        if [ -z "${image_list}" ]; then
            echo "ZoneX: no S32Z280 images exist yet."
            echo "ZoneX: the hypervisor libraries were built; nothing was flashed."
            exit 0
        fi

        # shellcheck disable=SC2086
        cmake --build "${BUILD}" --target ${image_list}

        if [ "${command}" = "test" ]; then
            echo "ZoneX: running on the S32Z280 needs the board and the gdb harness," >&2
            echo "ZoneX: which arrives with the first image." >&2
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 [build|test]" >&2
        exit 1
        ;;
esac
