/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_board.c                                       Armv8-R AEM FVP   */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    What the Armv8-R AEM FVP needs from the shared stage-2 probe, which */
/*    is almost nothing -- and the almost-nothing is the point.           */
/*                                                                        */
/*    zx_board_mmio_region_count returns 0 here and 2 on the S32Z280.     */
/*    The function exists on both so that the SAME probe program asks the */
/*    question on both targets, rather than the model's build quietly not */
/*    having the code path that silicon needs.                            */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"
#include "zx_platform.h"


/**************************************************************************/
/*  zx_board_init                                                         */
/*                                                                        */
/*  Nothing to do.  The console is semihosting (docs/decisions.md D8),    */
/*  which needs no peripheral and therefore cannot be broken by a wrong   */
/*  memory map -- which is exactly why it is the console to bring up      */
/*  BEFORE the MPU is trusted.                                           */
/**************************************************************************/

void zx_board_init(void)
{
    /* Intentionally empty.  */
}


/**************************************************************************/
/*  zx_board_mmio_region_count                                            */
/**************************************************************************/

uint32_t zx_board_mmio_region_count(void)
{
    return 0U;
}


/**************************************************************************/
/*  zx_board_program_mmio_regions                                         */
/**************************************************************************/

void zx_board_program_mmio_regions(uint32_t first_index)
{
    (void) first_index;

    /* Not reached: the count above is zero.  Present because the seam is
       shared with the board that does need it, and an empty implementation
       that says why is better than a link error on one target.  */
}


/**************************************************************************/
/*  zx_board_report                                                       */
/**************************************************************************/

void zx_board_report(void)
{
    zx_console_puts(
        "\n--- what this target is, and is not ---\n"
        "  console: semihosting (HLT 0xF000).  No peripheral, so it cannot\n"
        "           be broken by a wrong memory map.\n"
        "  image:   linked into low DRAM at 0x00000000.  The upper 2 GB half\n"
        "           of the BaseR map is peripherals and is execute-never in\n"
        "           the background map.\n"
        "  NOTE:    this model is an Architecture Envelope Model, not a\n"
        "           Cortex-R52.  It reported 32 EL1 MPU regions during the\n"
        "           Cortex-R52 port work -- not an architecturally legal\n"
        "           value -- and its MIDR part number is not an R52's.  Read\n"
        "           every count below as the MODEL's, never as a part's.\n"
        "  NOTE:    its UART (0x9C090000) and GIC (0xAF000000) fall in the\n"
        "           Device-nGnRE band of the background map, so HSCTLR.BR\n"
        "           gives them the right attributes BY ACCIDENT.  On the\n"
        "           S32Z280 the same devices sit in a Normal cacheable band\n"
        "           and each costs an EL2 region.  This model therefore\n"
        "           cannot show you that those regions are needed.\n");
}


/**************************************************************************/
/*  zx_board_describe_mmio_regions                                        */
/*                                                                        */
/*  Nothing to describe: this model's console and GIC already sit in the   */
/*  Device band of the background map, so the hypervisor spends no region  */
/*  on them and there is no geometry a partition window could collide      */
/*  with.  The parameter is unused for exactly that reason, and the        */
/*  function exists anyway so that the shared example code does not need   */
/*  to know which kind of board it is running on.                          */
/**************************************************************************/

void zx_board_describe_mmio_regions(ZX_REGION *region_ptr)
{
    (void)region_ptr;
}
