/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_board.c                                       Armv8-R AEM FVP   */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    What the Armv8-R AEM FVP needs from the shared stage-2 probe, which */
/*    is almost nothing -- and the almost-nothing is the point.           */
/*                                                                        */
/*    zx_board_mmio_region_count returns 0 here and 2 on the S32Z280.     */
/*    The function exists on both so that the SAME probe program asks the */
/*    question on both targets, rather than the model's build quietly not */
/*    having the code path that silicon needs.                            */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"
#include "zx_platform.h"


/**************************************************************************/
/*  zx_board_init                                                         */
/*                                                                        */
/*  Nothing to do.  The console is semihosting (docs/decisions.md D8),    */
/*  which needs no peripheral and therefore cannot be broken by a wrong   */
/*  memory map -- which is exactly why it is the console to bring up      */
/*  BEFORE the MPU is trusted.                                           */
/**************************************************************************/

void zx_board_init(void)
{
    /* Intentionally empty.  */
}


/**************************************************************************/
/*  zx_board_mmio_region_count                                            */
/**************************************************************************/

uint32_t zx_board_mmio_region_count(void)
{
    return 0U;
}


/**************************************************************************/
/*  zx_board_program_mmio_regions                                         */
/**************************************************************************/

void zx_board_program_mmio_regions(uint32_t first_index)
{
    (void) first_index;

    /* Not reached: the count above is zero.  Present because the seam is
       shared with the board that does need it, and an empty implementation
       that says why is better than a link error on one target.  */
}


/**************************************************************************/
/*  zx_board_deny_console_writes                                          */
/**************************************************************************/

uint32_t zx_board_deny_console_writes(uint32_t first_index)
{
    (void) first_index;

    /* NOTHING TO DENY.  This console is semihosting -- an HLT that the model
       interprets -- so it is not memory, no EL2 region covers it, and no
       access permission can be made to refuse it.  Returning zero is the
       honest answer and the caller reports the build as unprovokable here
       rather than as passing.  */

    return 0U;
}


/**************************************************************************/
/*  zx_board_report                                                       */
/**************************************************************************/

void zx_board_report(void)
{
    zx_console_puts(
        "\n--- what this target is, and is not ---\n"
        "  console: semihosting (HLT 0xF000).  No peripheral, so it cannot\n"
        "           be broken by a wrong memory map.\n"
        "  image:   linked into low DRAM at 0x00000000.  The upper 2 GB half\n"
        "           of the BaseR map is peripherals and is execute-never in\n"
        "           the background map.\n"
        "  NOTE:    this model is an Architecture Envelope Model, not a\n"
        "           Cortex-R52.  It reported 32 EL1 MPU regions during the\n"
        "           Cortex-R52 port work -- not an architecturally legal\n"
        "           value -- and its MIDR part number is not an R52's.  Read\n"
        "           every count below as the MODEL's, never as a part's.\n"
        "  NOTE:    its UART (0x9C090000) and GIC (0xAF000000) fall in the\n"
        "           Device-nGnRE band of the background map, so HSCTLR.BR\n"
        "           gives them the right attributes BY ACCIDENT.  On the\n"
        "           S32Z280 the same devices sit in a Normal cacheable band\n"
        "           and each costs an EL2 region.  This model therefore\n"
        "           cannot show you that those regions are needed.\n");
}


/**************************************************************************/
/*  zx_board_counter_hz                                                   */
/*                                                                        */
/*  The model resets CNTFRQ to zero and leaves the system counter STOPPED  */
/*  -- bp.refcounter.non_arch_start_at_default=0, documented as "firmware  */
/*  is expected to enable the timer at boot time".  The value below is     */
/*  CNTFID0 read back from the counter control frame during the            */
/*  Cortex-R52 port work, so it is what the counter WOULD run at once      */
/*  something starts it.                                                   */
/*                                                                        */
/*  ZoneX programs CNTFRQ from this so that a guest reading it gets a      */
/*  number rather than a zero.  STARTING the counter is a separate hook,   */
/*  zx_board_counter_start below, and on this model it is not optional.    */
/**************************************************************************/

uint32_t zx_board_counter_hz(void)
{
    return (uint32_t)ZX_FVP_SYSTEM_COUNTER_HZ;
}


/**************************************************************************/
/*  zx_board_counter_start                                                */
/*                                                                        */
/*  ONE REGISTER, AND IT IS THE DIFFERENCE BETWEEN A PREEMPTIVE GUEST AND  */
/*  A HARNESS TIMEOUT.                                                    */
/*                                                                        */
/*  This model's system counter is STOPPED at reset and the model says so  */
/*  in its own parameters: bp.refcounter.non_arch_start_at_default=0,      */
/*  documented as "firmware is expected to enable the timer at boot time". */
/*  So a guest granted the virtual timer here, on a run where nobody wrote */
/*  CNTCR, arms a comparator against a counter that will never reach it    */
/*  and blocks for ever.                                                  */
/*                                                                        */
/*  Read-modify-write rather than a plain store, because CNTCR carries     */
/*  more than EN -- HDBG and the frequency-change fields -- and a run that */
/*  had been started under a debugger with any of them set would have them */
/*  quietly cleared by a store.                                            */
/*                                                                        */
/*  The frame is reachable with no EL2 region because it sits in the       */
/*  Device-nGnRE band of this model's background map.  On a board where it */
/*  did not, this function would need a region first -- which is the same  */
/*  ordering problem the console has on the S32Z280, and the reason        */
/*  zx_board_program_mmio_regions runs before anything is printed.         */
/**************************************************************************/

void zx_board_counter_start(void)
{
    ZX_REG32(ZX_FVP_CNT_CONTROL_BASE + ZX_FVP_CNTCR) |=
        (uint32_t)ZX_FVP_CNTCR_EN;
}


/**************************************************************************/
/*  zx_board_gic_layout                                                   */
/*                                                                        */
/*  A redistributor is TWO consecutive 64 KB frames per core, and they are */
/*  named separately because swapping them writes plausible values into    */
/*  the wrong registers and reads back zero -- a GIC that was configured   */
/*  and does nothing, with no fault to point at it.                        */
/*                                                                        */
/*  Both addresses were confirmed in-model by reading GICD_PIDR2 and       */
/*  GICR_PIDR2 during the Cortex-R52 port work; both read 0x3B, which is   */
/*  GICv3.                                                                 */
/**************************************************************************/

void zx_board_gic_layout(ZX_GIC_LAYOUT *layout_ptr)
{
    if (layout_ptr == (ZX_GIC_LAYOUT *)0)
    {
        return;
    }

    layout_ptr->zx_gic_dist_base = (zx_addr_t)ZX_FVP_GICD_BASE;
    layout_ptr->zx_gic_rd_base   = (zx_addr_t)ZX_FVP_GICR_RD_BASE;
    layout_ptr->zx_gic_sgi_base  = (zx_addr_t)ZX_FVP_GICR_SGI_BASE;
}


/**************************************************************************/
/*  zx_board_describe_mmio_regions                                        */
/*                                                                        */
/*  Nothing to describe: this model's console and GIC already sit in the   */
/*  Device band of the background map, so the hypervisor spends no region  */
/*  on them and there is no geometry a partition window could collide      */
/*  with.  The parameter is unused for exactly that reason, and the        */
/*  function exists anyway so that the shared example code does not need   */
/*  to know which kind of board it is running on.                          */
/**************************************************************************/

void zx_board_describe_mmio_regions(ZX_REGION *region_ptr)
{
    (void)region_ptr;
}
