/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_platform.h                                    Armv8-R AEM FVP   */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Memory map for the Armv8-R AEM FVP (FVP_BaseR_AEMv8R).              */
/*                                                                        */
/*    Every address here was verified in-model during the Cortex-R52 port */
/*    work rather than taken from documentation.  The BaseR map is the    */
/*    Base platform map with its two 2 GB halves swapped, so a Base       */
/*    peripheral at X below 0x80000000 appears at X + 0x80000000, and     */
/*    each base was then confirmed by reading its identification          */
/*    register.                                                          */
/*                                                                        */
/*  WHY THIS TARGET NEEDS NO HYPERVISOR MMIO REGION                       */
/*                                                                        */
/*    ZoneX's console here is semihosting, which is a debug trap and      */
/*    touches no memory at all.  Even if it used the PL011, the UART at   */
/*    0x9C090000 and the GIC at 0xAF000000 both fall in the Device-nGnRE  */
/*    band of the background map, where HSCTLR.BR gives the right         */
/*    attributes by accident.                                            */
/*                                                                        */
/*    That is a property of this model, not of the architecture, and it   */
/*    is the reason the model cannot validate the region budget: on the   */
/*    S32Z280 the same two devices sit in a Normal cacheable band and     */
/*    each costs a region.  See docs/decisions.md D2.                     */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_PLATFORM_H
#define ZX_PLATFORM_H

#define ZX_PLATFORM_NAME    "Armv8-R AEM FVP (FVP_BaseR_AEMv8R), BaseR platform"

/* PL011 UART0.  Unused by ZoneX -- the console is semihosting, per
   docs/decisions.md D8 -- and recorded because its ADDRESS is the evidence
   for the paragraph above.  */

#define ZX_FVP_PL011_UART0_BASE     0x9C090000UL

/* GICv3.  A redistributor is two consecutive 64 KB frames per core.  */

#define ZX_FVP_GICD_BASE            0xAF000000UL
#define ZX_FVP_GICR_RD_BASE         0xAF100000UL
#define ZX_FVP_GICR_SGI_BASE        0xAF110000UL

/* The model resets CNTFRQ to zero and leaves the system counter stopped, so
   the value below is what the Cortex-R52 BSP programs -- CNTFID0 read back
   from the counter control frame.  The stage-2 probe does not use the timer
   and deliberately does not program CNTFRQ: it REPORTS it, so that a zero
   here is visible as the model's own state rather than hidden by ZoneX
   having written over it.  The timer matters once time partitioning
   arrives.  */

#define ZX_FVP_SYSTEM_COUNTER_HZ    100000000UL

/* Low DRAM, where the image is linked.  The 0x80000000-0xFFFFFFFF half holds
   peripherals and is execute-never in the background map, so linking code
   there produces a silent fault loop with no output.  */

#define ZX_FVP_DRAM_BASE            0x00000000UL
#define ZX_FVP_DRAM_SIZE            0x08000000UL    /* 128 MB */


/* How many hypervisor MMIO region descriptors the example has to be able
   to hold.  This model needs none, and a zero-length array is not valid C -- one
   entry that nothing writes costs 12 bytes and keeps the shared example
   code free of a board conditional.  */
#define ZX_BOARD_MAX_MMIO_REGIONS   1U

#endif /* ZX_PLATFORM_H */
