/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  GUEST APPLICATION                                      DESCRIPTION    */
/*                                                                        */
/*    zx_guest_app.c                                       GUEST          */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    A real ThreadX kernel, running at EL1 inside a stage-2 confined     */
/*    partition that ZoneX loaded and launched.                           */
/*                                                                        */
/*    Two threads, a queue and a semaphore between them, a counter        */
/*    published where the hypervisor can read it, and a verdict.  That is */
/*    deliberately unambitious: what is being demonstrated is not the     */
/*    application, it is that an UNMODIFIED kernel boots and schedules    */
/*    under a hypervisor's stage-2 MPU with its own stage-1 MPU live      */
/*    underneath.                                                         */
/*                                                                        */
/*  WHY IT IS COOPERATIVE                                                 */
/*                                                                        */
/*    There is no tick.  This guest takes no interrupts at all, so it     */
/*    uses tx_thread_relinquish and tx_queue_send/receive with            */
/*    TX_NO_WAIT; tx_thread_sleep would hang and time slicing would do    */
/*    nothing.                                                            */
/*                                                                        */
/*    That is a sub-milestone rather than a limitation of the design.  A   */
/*    guest with no interrupts fails FAST and CHEAPLY when something is    */
/*    wrong with the launch path -- and the launch path is what has never  */
/*    been run before.  Adding a timer and an interrupt controller at the  */
/*    same time would mean a silent guest with three plausible causes.     */
/*    The preemptive guest is the next thing, and it needs the hypervisor  */
/*    to take the GIC distributor and hand out a virtual timer.            */
/*                                                                        */
/*  WHAT PROVES WHAT                                                      */
/*                                                                        */
/*    Each progress bit is a milestone the one before it cannot fake:     */
/*                                                                        */
/*      BSP_MAIN         the ERET landed and the port's boot path ran     */
/*      KERNEL_ENTERED   tx_kernel_enter initialised and called back      */
/*      THREADS_RAN      the ported context switch works under stage 2    */
/*      QUEUE_OK         every item sent was received, in order           */
/*      SEMAPHORE_OK     a get/put pair handed off between threads        */
/*      FINISHED         the guest reached a verdict of its own           */
/*                                                                        */
/*    The hypervisor reads them out of the mailbox afterwards and does     */
/*    not have to trust the guest's own printed claim -- which is the      */
/*    point, since a guest that printed "PASSED" and set no bits would    */
/*    otherwise pass.                                                     */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"

#include "zx_guest_abi.h"
#include "zx_guest_bsp.h"

/* Static everything.  No byte pool, and therefore no allocator between the
   kernel and the thing under test: a guest that failed to start because its
   pool did not fit its window would look exactly like a guest that failed to
   start because the loader put it in the wrong place.  */

#define GUEST_STACK_SIZE        1024
#define GUEST_ITERATIONS        4U
#define GUEST_QUEUE_MESSAGES    4U

static TX_THREAD    thread_producer;
static TX_THREAD    thread_consumer;
static TX_QUEUE     work_queue;
static TX_SEMAPHORE handover;

static ULONG        producer_stack[GUEST_STACK_SIZE / sizeof(ULONG)];
static ULONG        consumer_stack[GUEST_STACK_SIZE / sizeof(ULONG)];

/* One ULONG per message, so TX_1_ULONG.  */
static ULONG        queue_storage[GUEST_QUEUE_MESSAGES];

static volatile ULONG   producer_slices;
static volatile ULONG   consumer_slices;
static volatile ULONG   messages_carried;
static volatile ULONG   queue_faults;
static volatile ULONG   semaphore_faults;


/**************************************************************************/
/*  publish -- push the counters into the mailbox and reseal it.          */
/*                                                                        */
/*  Called from a thread rather than at the end, so that a guest which     */
/*  stops half-way has still reported how far it got.  A report written    */
/*  only at the end tells a reader nothing about a run that never reached  */
/*  the end -- which is the run worth reading about.                       */
/**************************************************************************/

static void publish(ULONG progress_bits)
{
    guest_mailbox_write(ZX_GD_THREAD_A, producer_slices);
    guest_mailbox_write(ZX_GD_THREAD_B, consumer_slices);
    guest_mailbox_write(ZX_GD_MESSAGES, messages_carried);
    guest_mailbox_write(ZX_GD_TICKS, tx_time_get());

    guest_report(progress_bits);
}


/**************************************************************************/
/*  producer_entry                                                        */
/**************************************************************************/

static void producer_entry(ULONG thread_input)
{
    ULONG index;

    (void) thread_input;

    for (index = 0UL; index < (ULONG) GUEST_ITERATIONS; index++)
    {
        ULONG message = 0xC0DE0000UL + index;

        producer_slices++;

        console_puts("producer sending ");
        console_puthex(message);
        console_puts("\n");

        /* TX_NO_WAIT, because there is no tick: a thread that blocked with a
           timeout would wait forever.  The queue is sized to hold every
           message this loop sends, so a full queue here is a real failure
           rather than back-pressure, and it is counted as one.  */

        if (tx_queue_send(&work_queue, &message, TX_NO_WAIT) != TX_SUCCESS)
        {
            queue_faults++;
        }

        /* Hand the CPU over explicitly.  With no tick, this is the only
           thing that makes the consumer run at all -- which is exactly why
           the alternation is worth checking: it proves the ported context
           switch really switched rather than returning to the caller.  */

        tx_thread_relinquish();
    }

    publish(ZX_GP_THREADS_RAN);
}


/**************************************************************************/
/*  consumer_entry                                                        */
/*                                                                        */
/*  Drains the queue, checks each message is the one the producer sent in  */
/*  that order, exercises the semaphore, and produces the verdict.         */
/*                                                                        */
/*  CHECKING THE VALUE AND NOT MERELY THE COUNT.  A queue that delivered   */
/*  four messages in the wrong order, or four copies of one message,       */
/*  would satisfy a count and would mean the kernel's queue was broken     */
/*  under stage 2.  The sequence is what catches that.                     */
/**************************************************************************/

static void consumer_entry(ULONG thread_input)
{
    ULONG expected = 0xC0DE0000UL;
    ULONG progress = 0UL;

    (void) thread_input;

    while (messages_carried < (ULONG) GUEST_ITERATIONS)
    {
        ULONG message = 0UL;

        consumer_slices++;

        if (tx_queue_receive(&work_queue, &message, TX_NO_WAIT) == TX_SUCCESS)
        {
            if (message != expected)
            {
                queue_faults++;
            }

            expected++;
            messages_carried++;

            console_puts("consumer received ");
            console_puthex(message);
            console_puts("\n");
        }
        else if (producer_slices >= (ULONG) GUEST_ITERATIONS)
        {
            /* The producer has finished and the queue is empty, so nothing
               more will ever arrive.  Without this the loop would spin
               forever: there is no tick, so nothing would interrupt it and
               the run would end in a timeout rather than in a report.

               THE TEST USES THE RESULT OF THE RECEIVE ABOVE and does not
               perform one of its own.  An earlier version called
               tx_queue_receive a second time here to ask whether the queue
               was empty -- which CONSUMED a message and threw it away, so
               the run reported two messages carried out of four and one of
               them out of order.  A question that changes the thing it is
               asking about is not a question.  */
            break;
        }
        else
        {
            /* Empty, but the producer is still going: let it run.  */
        }

        tx_thread_relinquish();
    }

    if (queue_faults == 0UL)
    {
        progress |= (ULONG) ZX_GP_QUEUE_OK;
    }

    /* The semaphore.  Created with a count of one, so the first get
       succeeds and the second must fail with TX_NO_WAIT -- both halves are
       checked, because a semaphore that granted everything would pass a test
       that only took it once.  */

    if (tx_semaphore_get(&handover, TX_NO_WAIT) != TX_SUCCESS)
    {
        semaphore_faults++;
    }

    if (tx_semaphore_get(&handover, TX_NO_WAIT) == TX_SUCCESS)
    {
        semaphore_faults++;
    }

    if (tx_semaphore_put(&handover) != TX_SUCCESS)
    {
        semaphore_faults++;
    }

    if (semaphore_faults == 0UL)
    {
        progress |= (ULONG) ZX_GP_SEMAPHORE_OK;
    }

    console_puts("threads ran, producer/consumer slices = ");
    console_putdec(producer_slices);
    console_puts(" / ");
    console_putdec(consumer_slices);
    console_puts("\n");
    console_puts("messages carried = ");
    console_putdec(messages_carried);
    console_puts(", queue faults = ");
    console_putdec(queue_faults);
    console_puts(", semaphore faults = ");
    console_putdec(semaphore_faults);
    console_puts("\n");

    /* THE PROBE, if the hypervisor asked for one.
     *
     * The address comes from the mailbox rather than from a build option, so
     * ONE guest image serves every case the hypervisor wants to demonstrate:
     * an address outside the partition window (a stage-2 violation), the
     * guest's own code (permitted by stage 2 and refused by the guest's own
     * MPU -- a STAGE-1 fault, which never reaches EL2 at all), and an
     * address the guest is genuinely granted (which must SURVIVE, and is how
     * the check is proved able to fail).
     *
     * That matters for more than build time.  A separate guest binary per
     * case is a set of binaries that can drift apart, and the one that
     * demonstrates isolation would then no longer be the one that
     * demonstrates the kernel running.  Here they are the same bytes.
     *
     * PROBE_SURVIVED is set only AFTER the write completes, so its absence
     * is the evidence that the access was stopped -- by whichever stage
     * stopped it.  A check whose pass condition is the absence of something
     * has to be able to fail, which is what the granted-address build is
     * for.  */

    if (guest_mailbox_read(ZX_GD_TARGET) != 0UL)
    {
        volatile ULONG *target =
            (volatile ULONG *)(void *)(unsigned long)
                guest_mailbox_read(ZX_GD_TARGET);

        unsigned long address = guest_mailbox_read(ZX_GD_TARGET);

        console_puts("probing ");
        console_puthex(address);
        console_puts("\n");

        /* If the guest's own MPU does not already cover the address, grant
           it -- otherwise STAGE 1 denies the access and the fault is taken
           to EL1, and a stage-2 violation could never be demonstrated from
           a real kernel at all.  When it IS already covered, granting again
           would create an overlap, which is CONSTRAINED UNPREDICTABLE.  */

        if (guest_grant_probe_region(address) != 0U)
        {
            console_puts("my own MPU did not cover it, so I granted myself\n"
                         "that granule -- stage 2 has the last word\n");
        }
        else
        {
            console_puts("my own MPU already covers it\n");
        }

        guest_mailbox_write(ZX_GD_PROBED, 0UL);
        publish(0UL);

        *target = (ULONG) ZX_GUEST_SENTINEL_A;

        guest_mailbox_write(ZX_GD_PROBED, (unsigned long) *target);
        progress |= (ULONG) ZX_GP_PROBE_SURVIVED;

        console_puts("the probe SURVIVED, so nothing denied it\n");
    }

    /* The verdict, written into the mailbox BEFORE it is printed.  A guest
       that printed a verdict it had not published would let a reader believe
       something the hypervisor cannot confirm.  */

    if ((messages_carried == (ULONG) GUEST_ITERATIONS)
        && (queue_faults == 0UL)
        && (semaphore_faults == 0UL))
    {
        guest_mailbox_write(ZX_GD_VERDICT, (unsigned long) ZX_GV_PASSED);
        progress |= (ULONG) ZX_GP_FINISHED;
        publish(progress);
        console_puts("GUEST RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        guest_mailbox_write(ZX_GD_VERDICT, (unsigned long) ZX_GV_FAILED);
        progress |= (ULONG) ZX_GP_FINISHED;
        publish(progress);
        console_puts("GUEST RESULT: FAILED\n");
    }

    /* Back to the hypervisor, on purpose.  A guest that simply returned from
       its last thread would leave the kernel idling forever inside a
       partition nothing would ever take back, and the run would time out
       rather than report.  */

    guest_yield();
}


/**************************************************************************/
/*  tx_application_define                                                 */
/**************************************************************************/

void tx_application_define(void *first_unused_memory)
{
    (void) first_unused_memory;

    publish((ULONG) ZX_GP_KERNEL_ENTERED);

    (void) tx_queue_create(&work_queue, "work", TX_1_ULONG,
                           queue_storage, sizeof(queue_storage));

    (void) tx_semaphore_create(&handover, "handover", 1UL);

    /* EQUAL PRIORITIES, and that is what makes this a context-switch test.
       tx_thread_relinquish yields to the next ready thread OF THE SAME
       priority; between threads of different priorities it does nothing
       observable, and the higher one simply runs to completion.  An earlier
       version created the consumer one priority lower and the two never
       interleaved at all -- which still delivered every message, and
       therefore still would have passed a weaker check than the one here.

       Creation order then decides who runs first, which is what keeps the
       message ordering deterministic without a tick to arbitrate.  */

    (void) tx_thread_create(&thread_producer, "producer", producer_entry, 0UL,
                            producer_stack, sizeof(producer_stack),
                            16U, 16U, TX_NO_TIME_SLICE, TX_AUTO_START);

    (void) tx_thread_create(&thread_consumer, "consumer", consumer_entry, 0UL,
                            consumer_stack, sizeof(consumer_stack),
                            16U, 16U, TX_NO_TIME_SLICE, TX_AUTO_START);
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 from the port's own boot path.             */
/*                                                                        */
/*  THE ORDER HERE MATTERS AND IS SHORT ENOUGH TO STATE IN FULL:          */
/*                                                                        */
/*    REPORT BSP_MAIN, before anything that can fail.  If the guest dies   */
/*    from here on, the hypervisor still knows the ERET landed and the     */
/*    port's boot path completed -- which rules out the entire loader.     */
/*                                                                        */
/*    INSTALL THE GUEST'S OWN VECTORS, so that a fault from here onwards   */
/*    is reported rather than fatal.  This comes second and not first on   */
/*    purpose: installing vectors before the mailbox write would mean a    */
/*    fault during the install itself had nowhere to report to, and the    */
/*    mailbox write is the cheaper of the two to get right.                */
/*                                                                        */
/*    ENABLE THE GUEST'S OWN MPU.  After this the guest is confined by     */
/*    stage 1 as well as stage 2, and a mistake in either shows up         */
/*    immediately -- which is the point of doing it before the kernel      */
/*    rather than after.                                                   */
/*                                                                        */
/*    ENTER THE KERNEL.                                                    */
/**************************************************************************/

void bsp_main(void)
{
    unsigned int regions;

    publish((ULONG) ZX_GP_BSP_MAIN);

    /* Before the first print, so that a quiet run really is quiet.  See the
       note on ZX_GO_QUIET in zx_guest_abi.h: the measured passes cost
       nothing on the console and the demonstration pass shows everything,
       from the same image.  */

    console_set_quiet(((guest_mailbox_read(ZX_GD_OPTIONS)
                        & (unsigned long) ZX_GO_QUIET) != 0UL) ? 1U : 0U);

    guest_vectors_install();

    console_puts("ThreadX guest at EL1, inside a ZoneX partition\n");
    console_puts("mailbox sentinel from the hypervisor = ");
    console_puthex(guest_mailbox_read(ZX_GD_SCRATCH));
    console_puts("\n");

    regions = guest_mpu_init();

    if (regions == 0U)
    {
        console_puts("this part has too few EL1 regions for this guest;\n"
                     "refusing to enable stage 1 rather than programming a\n"
                     "region index the implementation does not have\n");
        guest_mailbox_write(ZX_GD_VERDICT, (unsigned long) ZX_GV_FAILED);
        publish((ULONG) ZX_GP_FINISHED);
        guest_yield();
        return;
    }

    console_puts("stage-1 MPU on: ");
    console_putdec(regions);
    console_puts(" EL1 regions, SCTLR.M = ");
    console_putdec(guest_mpu_is_enabled());
    console_puts("\n");
    console_puts("every one of them lies inside this partition's stage-2\n"
                 "window, or the guest would fault on memory its own MPU\n"
                 "says it owns -- the stricter of the two stages wins\n");

    tx_kernel_enter();
}
