/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  GUEST APPLICATION                                      DESCRIPTION    */
/*                                                                        */
/*    zx_guest_app.c                                       GUEST          */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    A real ThreadX kernel, running at EL1 inside a stage-2 confined     */
/*    partition that ZoneX loaded and launched.                           */
/*                                                                        */
/*    Two threads, a queue and a semaphore between them, a counter        */
/*    published where the hypervisor can read it, and a verdict.  That is */
/*    deliberately unambitious: what is being demonstrated is not the     */
/*    application, it is that an UNMODIFIED kernel boots and schedules    */
/*    under a hypervisor's stage-2 MPU with its own stage-1 MPU live      */
/*    underneath.                                                         */
/*                                                                        */
/*  ONE IMAGE, TWO EXPERIMENTS, AND THE DIFFERENCE IS A WORD IN THE        */
/*  MAILBOX                                                               */
/*                                                                        */
/*    With ZX_GO_TICK clear this guest is COOPERATIVE: it takes no        */
/*    interrupts at all, arms no timer, and touches no interrupt          */
/*    controller, so it uses tx_thread_relinquish and TX_NO_WAIT          */
/*    everywhere.  With ZX_GO_TICK set the hypervisor has granted it the  */
/*    virtual timer, and it goes on to prove the things only a kernel     */
/*    with a tick can prove.                                              */
/*                                                                        */
/*    THE TWO ARE THE SAME BYTES, deliberately.  A separate binary for    */
/*    the preemptive case would be a binary that can drift from the one   */
/*    demonstrating isolation, and the one still being quoted would then  */
/*    no longer be the one that was tested.  Here the run that shows a    */
/*    kernel confined by stage 2 and the run that shows it preempted      */
/*    under stage 2 are the same image, loaded twice.                     */
/*                                                                        */
/*    The cooperative case came first for a reason worth keeping: a guest */
/*    with no interrupts fails FAST and CHEAPLY when something is wrong   */
/*    with the launch path, and bringing up a timer and an interrupt      */
/*    controller at the same time as a loader would have meant a silent   */
/*    guest with three plausible causes.                                  */
/*                                                                        */
/*  WHAT PROVES WHAT                                                      */
/*                                                                        */
/*    Each progress bit is a milestone the one before it cannot fake:     */
/*                                                                        */
/*      BSP_MAIN         the ERET landed and the port's boot path ran     */
/*      KERNEL_ENTERED   tx_kernel_enter initialised and called back      */
/*      THREADS_RAN      the ported context switch works under stage 2    */
/*      QUEUE_OK         every item sent was received, in order           */
/*      SEMAPHORE_OK     a get/put pair handed off between threads        */
/*      FINISHED         the guest reached a verdict of its own           */
/*                                                                        */
/*    and, when a tick was granted:                                       */
/*                                                                        */
/*      COUNTING         the partition's own virtual counter ADVANCES.    */
/*                       Checked before anything blocks, because the      */
/*                       alternative to checking is a hang: the Armv8-R   */
/*                       AEM FVP leaves its system counter stopped, and a */
/*                       guest that slept on a stopped counter would be   */
/*                       killed by a harness timeout naming nothing.      */
/*      TICKING          tx_time_get() advanced, so the virtual timer PPI */
/*                       was delivered to EL1 and _tx_timer_interrupt ran */
/*      PREEMPTED        a thread that never yields was DISPLACED         */
/*      TIMESLICED       two equal-priority threads that never yield both */
/*                       advanced                                         */
/*                                                                        */
/*    The hypervisor reads them out of the mailbox afterwards and does     */
/*    not have to trust the guest's own printed claim -- which is the      */
/*    point, since a guest that printed "PASSED" and set no bits would    */
/*    otherwise pass.                                                     */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"

#include "zx_guest_abi.h"
#include "zx_guest_bsp.h"

/* Static everything.  No byte pool, and therefore no allocator between the
   kernel and the thing under test: a guest that failed to start because its
   pool did not fit its window would look exactly like a guest that failed to
   start because the loader put it in the wrong place.  */

#define GUEST_STACK_SIZE        1024
#define GUEST_ITERATIONS        4U
#define GUEST_QUEUE_MESSAGES    4U

/* THE PRIORITIES ARE THE EXPERIMENT, so they are named rather than pasted.
 *
 * The producer and the consumer share one priority: tx_thread_relinquish
 * yields to the next ready thread OF THE SAME priority, so between threads of
 * different priorities it does nothing observable and the higher one simply
 * runs to completion.  That was found the hard way -- see the note in
 * tx_application_define.
 *
 * The two spinners share a LOWER one, and both halves of that matter.  Lower
 * than the consumer, so that they run only while the consumer is asleep and
 * the cooperative phase is completely unaffected by their existence.  Equal
 * to each other, so that the only thing that can make both of them advance is
 * the kernel's TIME SLICE -- neither ever yields, and at different priorities
 * the higher one would simply own the core.  */

#define GUEST_WORKER_PRIORITY   16U
#define GUEST_SPIN_PRIORITY     20U

/* Two ticks, so that a slice boundary falls inside the window the consumer
   sleeps for.  A slice equal to the sleep would leave whether the second
   spinner ever ran to the order the two happened to start in.  */

#define GUEST_SPIN_SLICE        2U

/* Three ticks of sleep.  Long enough to contain at least one slice boundary
   for each spinner, short enough that a functional model is not asked to
   simulate more time than the claim needs.  */

#define GUEST_SLEEP_TICKS       3U

/* How long to wait for the FIRST tick, in iterations of a busy loop.  This is
   a bound and not a duration: its only job is to be finite, so that a tick
   that never arrives becomes a reported failure instead of a hang.  */

#define GUEST_TICK_GUARD        2000000UL

/* And the bound on a spinner, for the same reason one level down.  It is
   never reached on a run where the tick works, which is the only run that
   gets this far -- the counter and the first tick are both checked before
   anything sleeps.  */

#define GUEST_SPIN_GUARD        2000000UL

static TX_THREAD    thread_producer;
static TX_THREAD    thread_consumer;
static TX_THREAD    thread_spin_a;
static TX_THREAD    thread_spin_b;
static TX_QUEUE     work_queue;
static TX_SEMAPHORE handover;

static ULONG        producer_stack[GUEST_STACK_SIZE / sizeof(ULONG)];
static ULONG        consumer_stack[GUEST_STACK_SIZE / sizeof(ULONG)];
static ULONG        spin_a_stack[GUEST_STACK_SIZE / sizeof(ULONG)];
static ULONG        spin_b_stack[GUEST_STACK_SIZE / sizeof(ULONG)];

/* One ULONG per message, so TX_1_ULONG.  */
static ULONG        queue_storage[GUEST_QUEUE_MESSAGES];

static volatile ULONG   producer_slices;
static volatile ULONG   consumer_slices;
static volatile ULONG   messages_carried;
static volatile ULONG   queue_faults;
static volatile ULONG   semaphore_faults;

/* The preemptive phase's state.  volatile because it is written by one thread
   and read by another with no synchronisation between them -- which is the
   whole method here: the spinners never yield and never take a lock, so what
   the consumer reads is whatever they had reached at the instant the tick
   took the core away from them.  */

static volatile ULONG   spin_a_loops;
static volatile ULONG   spin_b_loops;
static volatile ULONG   spin_stop;
static volatile ULONG   guest_tick_granted;


/**************************************************************************/
/*  publish -- push the counters into the mailbox and reseal it.          */
/*                                                                        */
/*  Called from a thread rather than at the end, so that a guest which     */
/*  stops half-way has still reported how far it got.  A report written    */
/*  only at the end tells a reader nothing about a run that never reached  */
/*  the end -- which is the run worth reading about.                       */
/**************************************************************************/

static void publish(ULONG progress_bits)
{
    guest_mailbox_write(ZX_GD_THREAD_A, producer_slices);
    guest_mailbox_write(ZX_GD_THREAD_B, consumer_slices);
    guest_mailbox_write(ZX_GD_MESSAGES, messages_carried);
    guest_mailbox_write(ZX_GD_TICKS, tx_time_get());

    guest_report(progress_bits);
}


/**************************************************************************/
/*  producer_entry                                                        */
/**************************************************************************/

static void producer_entry(ULONG thread_input)
{
    ULONG index;

    (void) thread_input;

    for (index = 0UL; index < (ULONG) GUEST_ITERATIONS; index++)
    {
        ULONG message = 0xC0DE0000UL + index;

        producer_slices++;

        console_puts("producer sending ");
        console_puthex(message);
        console_puts("\n");

        /* TX_NO_WAIT, because there is no tick: a thread that blocked with a
           timeout would wait forever.  The queue is sized to hold every
           message this loop sends, so a full queue here is a real failure
           rather than back-pressure, and it is counted as one.  */

        if (tx_queue_send(&work_queue, &message, TX_NO_WAIT) != TX_SUCCESS)
        {
            queue_faults++;
        }

        /* Hand the CPU over explicitly.  With no tick, this is the only
           thing that makes the consumer run at all -- which is exactly why
           the alternation is worth checking: it proves the ported context
           switch really switched rather than returning to the caller.  */

        tx_thread_relinquish();
    }

    publish(ZX_GP_THREADS_RAN);
}


/**************************************************************************/
/*  spin_entry -- a thread that never yields.                             */
/*                                                                        */
/*  THE POINT OF THIS THREAD IS EVERYTHING IT DOES NOT DO.  It makes no    */
/*  kernel call in its loop: no relinquish, no sleep, no queue, no         */
/*  semaphore.  There is therefore no point at which the kernel could      */
/*  take the core away from it COOPERATIVELY.  If anything else ever runs  */
/*  while this thread is between its own iterations, the only thing that   */
/*  can have caused it is an interrupt.                                    */
/*                                                                        */
/*  Two of these exist and they share a priority, which turns the same     */
/*  loop into a second and different claim: neither can yield to the       */
/*  other, so the only way BOTH counters can advance is the kernel's time  */
/*  slice -- _tx_timer_interrupt counting down tx_thread_time_slice and    */
/*  rotating the ready list.                                               */
/*                                                                        */
/*  The counter is published into the mailbox on every iteration rather    */
/*  than at the end, and that is not an accident of style.  A thread that  */
/*  was DISPLACED and never resumed -- because the run ended, or because   */
/*  the partition was taken by a fault -- has still reported how far it    */
/*  got, and how far it got is the evidence.                               */
/*                                                                        */
/*  The bound exists so this cannot be the thing that hangs a run.  It is  */
/*  unreachable on any run that gets here: the consumer has already        */
/*  proved the counter moves and that a tick arrived.                      */
/**************************************************************************/

static void spin_entry(ULONG thread_input)
{
    volatile ULONG *loops = (thread_input == 0UL) ? &spin_a_loops
                                                  : &spin_b_loops;
    ULONG offset = (thread_input == 0UL) ? (ULONG) ZX_GD_SPIN_A
                                         : (ULONG) ZX_GD_SPIN_B;
    ULONG guard;

    for (guard = 0UL; guard < (ULONG) GUEST_SPIN_GUARD; guard++)
    {
        if (spin_stop != 0UL)
        {
            break;
        }

        *loops = *loops + 1UL;
        guest_mailbox_write(offset, *loops);
    }
}


/**************************************************************************/
/*  wait_for_first_tick                                                   */
/*                                                                        */
/*  BUSY, NOT BLOCKING, AND THAT IS THE WHOLE FUNCTION.                    */
/*                                                                        */
/*  tx_thread_sleep is the natural way to wait for a tick and it is the    */
/*  one thing that must not be used to find out WHETHER there is one: a    */
/*  sleep with no tick behind it never returns, and the run ends in a      */
/*  harness timeout -- the single least informative outcome this suite     */
/*  can produce, and one that looks identical to a broken loader, a        */
/*  broken context switch and a broken interrupt controller.               */
/*                                                                        */
/*  So the first tick is waited for with interrupts ENABLED and the thread */
/*  RUNNABLE, polling tx_time_get() a bounded number of times.  A tick     */
/*  that arrives advances it; a tick that never arrives runs the loop out  */
/*  and the guest reports that instead.                                    */
/**************************************************************************/

static UINT wait_for_first_tick(void)
{
    ULONG started = tx_time_get();
    ULONG guard;

    for (guard = 0UL; guard < (ULONG) GUEST_TICK_GUARD; guard++)
    {
        if (tx_time_get() != started)
        {
            return TX_TRUE;
        }
    }

    return TX_FALSE;
}


/**************************************************************************/
/*  preemptive_phase -- what only a kernel with a tick can demonstrate.   */
/*                                                                        */
/*  THREE CLAIMS, IN THE ORDER THAT MAKES EACH ONE SAFE TO MAKE.           */
/*                                                                        */
/*    1.  THE COUNTER MOVES.  Read twice, bounded, before anything blocks. */
/*        Programming CNTFRQ does not start a system counter and on one of */
/*        the two targets it is stopped at reset, so this is the check     */
/*        that stands between a granted timer and a timeout.  It asks      */
/*        about the VIRTUAL counter, which is the one this partition can   */
/*        see -- the hypervisor's own check, of the physical counter, is a */
/*        different register reached past CNTVOFF.                         */
/*                                                                        */
/*    2.  A TICK ARRIVES.  Busy-waited, so that a GIC that was configured  */
/*        and delivers nothing is a report rather than a hang.  This is    */
/*        the first thing in the whole run that proves the interrupt path  */
/*        end to end: the hypervisor enabled the PPI in a redistributor    */
/*        this guest cannot reach, the guest enabled its own CPU           */
/*        interface, the GIC delivered to EL1 rather than to EL2, the      */
/*        guest's own vector table sent it into the port's context save,   */
/*        and _tx_timer_interrupt ran.                                     */
/*                                                                        */
/*    3.  PREEMPTION AND TIME SLICING, measured in one sleep.  The         */
/*        consumer records both spinners' counters, sleeps, and looks      */
/*        again:                                                           */
/*                                                                        */
/*          the consumer WOKE AT ALL          the timeout list ran, so the */
/*                                            tick reaches the scheduler   */
/*                                            and not merely a counter     */
/*          a spinner ADVANCED                it was genuinely running --   */
/*                                            and it never yields, so the  */
/*                                            consumer running again now   */
/*                                            means the tick DISPLACED it  */
/*          BOTH spinners advanced            neither can yield to the     */
/*                                            other, so the only thing     */
/*                                            that can have interleaved    */
/*                                            them is the time slice       */
/*                                                                        */
/*  WHY THE TWO ARE SEPARATE BITS.  Preemption and time slicing are        */
/*  different parts of _tx_timer_interrupt -- the timeout list and the     */
/*  slice countdown -- and they fail separately.  A kernel whose slice     */
/*  counter was wrong would still wake a sleeper, and reporting one bit    */
/*  for both would call that a pass.                                       */
/**************************************************************************/

static ULONG preemptive_phase(void)
{
    ULONG progress = 0UL;
    ULONG before_a;
    ULONG before_b;
    ULONG after_a;
    ULONG after_b;

    if (guest_counter_is_moving() == 0U)
    {
        console_puts("this partition's virtual counter is NOT advancing, so\n"
                     "the system counter was never started.  Refusing to\n"
                     "block on a timer that cannot expire -- a guest that\n"
                     "slept here would end this run in a timeout naming\n"
                     "nothing at all\n");
        return (ULONG) ZX_GP_NO_CLOCK;
    }

    progress |= (ULONG) ZX_GP_COUNTING;

    console_puts("virtual counter is advancing; waiting for the first tick\n");

    if (wait_for_first_tick() == TX_FALSE)
    {
        console_puts("no tick arrived.  The counter moves, so the timer was\n"
                     "armed against a running counter and the interrupt did\n"
                     "not reach this partition -- which is the GIC or the\n"
                     "vector table, and not the clock\n");
        return progress | (ULONG) ZX_GP_NO_CLOCK;
    }

    progress |= (ULONG) ZX_GP_TICKING;

    console_puts("the tick arrived: INTID ");
    console_putdec(guest_mailbox_read(ZX_GD_TIMER_INTID));
    console_puts(", interrupts serviced so far = ");
    console_putdec(guest_mailbox_read(ZX_GD_IRQ_COUNT));
    console_puts("\n");

    /* Both counters are read BEFORE the sleep and both after it.  Reading
       one, sleeping, and reading the other would compare two different
       instants and could report a slice that never happened.  */

    before_a = spin_a_loops;
    before_b = spin_b_loops;

    tx_thread_sleep((ULONG) GUEST_SLEEP_TICKS);

    after_a = spin_a_loops;
    after_b = spin_b_loops;

    if ((after_a > before_a) || (after_b > before_b))
    {
        /* A spinner was running, and it never yields.  This thread is
           running again.  Something took the core from a thread that did not
           give it up, and the only thing that can is an interrupt.  */

        progress |= (ULONG) ZX_GP_PREEMPTED;
    }

    if ((after_a > before_a) && (after_b > before_b))
    {
        progress |= (ULONG) ZX_GP_TIMESLICED;
    }

    /* Let the spinners finish, so the kernel is not left with two runnable
       threads when this one hands the machine back.  */

    spin_stop = 1UL;

    guest_mailbox_write(ZX_GD_WAKES, guest_mailbox_read(ZX_GD_WAKES) + 1UL);

    console_puts("slept ");
    console_putdec((ULONG) GUEST_SLEEP_TICKS);
    console_puts(" ticks; spinner loops ");
    console_putdec(after_a - before_a);
    console_puts(" / ");
    console_putdec(after_b - before_b);
    console_puts(" -- neither of them yields, so both of those are the\n"
                 "kernel's own time slice, and this thread running again is\n"
                 "a lower-priority thread having been DISPLACED\n");

    return progress;
}


/**************************************************************************/
/*  THE ISOLATION MATRIX -- one sweep, every case, inside one window.     */
/*                                                                        */
/*  WHAT THIS CAN AND CANNOT SAY, because getting that wrong is how a      */
/*  swept matrix passes while proving nothing.                            */
/*                                                                        */
/*  IT CANNOT REPORT THAT A CASE WAS DENIED.  Under the hypervisor's       */
/*  test-only continue mode a faulting partition is resumed PAST the       */
/*  faulting instruction, so the very next store -- the one that would     */
/*  have recorded "this case survived" -- executes anyway, one instruction */
/*  later, on a case that was refused.  A guest is not conscious of having */
/*  been refused.  Every "it faulted" judgement therefore belongs to EL2   */
/*  and comes out of its fault log, matched by ADDRESS, which is why every */
/*  case below aims at an address of its own.                              */
/*                                                                        */
/*  WHAT IT CAN SAY HONESTLY IS WHAT IT ATTEMPTED, and EL2 cannot know     */
/*  that: a case the guest refused to run and a case stage 2 denied both   */
/*  leave the hypervisor with no fault to look at.  Only the guest can     */
/*  tell those two apart.  So it publishes the attempted set and the       */
/*  refused set and leaves the judging alone.                              */
/*                                                                        */
/*  AND ONE CASE IS THE OTHER WAY ROUND.  Its own window must SUCCEED, and */
/*  success is something a guest CAN demonstrate: distinct marks written   */
/*  into distinct granules and read back.  It runs LAST, deliberately, so  */
/*  that what the marks say is "this partition still owned every byte of   */
/*  its own window after being refused six times".                        */
/*                                                                        */
/*  EVERY ADDRESS IS HANDED OVER RATHER THAN COMPUTED, and that is the     */
/*  point rather than an inconvenience.  A guest deriving its neighbour's  */
/*  window from its own base would be a guest that had been TOLD the       */
/*  layout; a guest handed an address it could not have derived is a guest */
/*  being asked to reach somewhere it has no business knowing about, which */
/*  is the situation the isolation claim is actually about.                */
/**************************************************************************/

/* THE MARKS.  Written all of them, then read back all of them -- never one
   at a time.  A region whose BASE is wrong accepts every store and puts
   them all somewhere else, so a write-then-check of one granule reads its
   own store back from the same wrong place and agrees.  Distinct marks at
   distinct addresses, checked only after the last one is written, is what
   makes the readback mean "these are five different extents".  */

static ULONG matrix_write_marks(void)
{
    unsigned long base     = guest_mailbox_read(ZX_GD_M_MARK_BASE);
    unsigned long count    = guest_mailbox_read(ZX_GD_M_MARK_COUNT);
    unsigned long sentinel = guest_mailbox_read(ZX_GD_SCRATCH);
    unsigned long index;
    ULONG         agreed   = 1UL;

    if ((base == 0UL) || (count == 0UL))
    {
        guest_mailbox_write(ZX_GD_M_MARKS_WRITTEN, 0UL);
        guest_mailbox_write(ZX_GD_M_MARKS_OK, 0UL);

        return 0UL;
    }

    if (guest_owns_range(base, count * 64UL) == 0U)
    {
        console_puts("REFUSING to mark: the range I was handed is not inside\n"
                     "the writable part of my own window\n");
        guest_mailbox_write(ZX_GD_M_MARKS_WRITTEN, 0UL);
        guest_mailbox_write(ZX_GD_M_MARKS_OK, 0UL);

        return 0UL;
    }

    for (index = 0UL; index < count; index++)
    {
        volatile ULONG *granule =
            (volatile ULONG *)(void *)(base + (index * 64UL));

        *granule = (ULONG) ZX_MARK_FOR(sentinel, index);
    }

    /* PUBLISHED BEFORE THE READBACK, so that a partition stopped between
       the two is recorded as having written them rather than as having
       written nothing.  */

    guest_mailbox_write(ZX_GD_M_MARKS_WRITTEN, count);

    for (index = 0UL; index < count; index++)
    {
        volatile const ULONG *granule =
            (volatile const ULONG *)(const void *)(base + (index * 64UL));

        if (*granule != (ULONG) ZX_MARK_FOR(sentinel, index))
        {
            agreed = 0UL;
        }
    }

    guest_mailbox_write(ZX_GD_M_MARKS_OK, (unsigned long) agreed);

    console_puts("marked ");
    console_putdec(count);
    console_puts(" granules of my own window, each with a different value,\n"
                 "and read every one of them back: ");
    console_puts((agreed != 0UL) ? "all agreed\n"
                                 : "*** ONE DISAGREED ***\n");

    return (ULONG) ZX_MC_OWN_MARKS;
}


/* One denial case: grant the granule at stage 1, then touch it.
 *
 * THE GRANT IS THE HALF THAT MAKES THIS A STAGE-2 TEST AT ALL.  Without it
 * stage 1 refuses first, the abort is taken to EL1, and the hypervisor
 * never hears about it -- so the run would demonstrate the guest's own MPU
 * working and would say nothing whatever about the partition boundary.
 *
 * Returns the case's bit when the access may be attempted, and ORs a reason
 * into *refused_ptr when it may not.  */

static ULONG matrix_grant(unsigned long address, ULONG bit,
                          unsigned int executable, ULONG *refused_ptr)
{
    unsigned int granted;

    if (address == 0UL)
    {
        *refused_ptr |= (ULONG) ZX_MR_NO_ADDRESS;

        return 0UL;
    }

    granted = guest_grant_scratch_region(address, executable);

    if (granted == ZX_GRANT_ALREADY)
    {
        /* The hypervisor pointed this case at memory the guest genuinely
           owns.  Reported rather than run: an access that succeeds because
           it was always permitted is not evidence about anything, and a
           sweep counting it as a pass would be counting its own mistake.  */

        *refused_ptr |= (ULONG) ZX_MR_INSIDE_ITSELF;

        return 0UL;
    }

    if (granted == ZX_GRANT_NO_REGION)
    {
        *refused_ptr |= (ULONG) ZX_MR_NO_REGION;

        return 0UL;
    }

    return bit;
}


static ULONG isolation_matrix(void)
{
    ULONG cases     = (ULONG) guest_mailbox_read(ZX_GD_M_CASES);
    ULONG attempted = 0UL;
    ULONG refused   = 0UL;
    ULONG progress  = 0UL;

    if (cases == 0UL)
    {
        return 0UL;
    }

    console_puts("\nTHE ISOLATION MATRIX.  For every address below I grant\n"
                 "MYSELF the granule in my own MPU first, so stage 1 permits\n"
                 "the access and I genuinely believe I own the memory.\n"
                 "Stage 2 has the last word, and I am not able to tell you\n"
                 "whether it took it -- only the hypervisor can.\n");

    /* CASE 1 -- the neighbour's data, READ.
     *
     * THE POISON GOES IN FIRST, AND IT IS NOT ENOUGH.  A denied load never
     * writes its destination register -- but under the continue mode the
     * hypervisor resumes this guest at the instruction AFTER the load, and
     * that instruction is the store of the loaded value.  So the mailbox
     * gets written with whatever the compiler happened to leave in that
     * register, which on a real run was the number one.  The poison is
     * still written because a word nobody wrote is worse than a word
     * written with rubbish, but it CANNOT be what the check tests against.
     *
     * The hypervisor tests the reported value against what is REALLY at
     * that address, which it can read and this guest cannot.  That is the
     * claim anyway -- the neighbour's data did not reach this partition --
     * rather than the proxy for it.  */

    if ((cases & (ULONG) ZX_MC_NEIGHBOUR_READ) != 0UL)
    {
        unsigned long address = guest_mailbox_read(ZX_GD_M_NEIGHBOUR);
        ULONG         bit     = matrix_grant(address,
                                             (ULONG) ZX_MC_NEIGHBOUR_READ,
                                             0U, &refused);

        if (bit != 0UL)
        {
            volatile const ULONG *target =
                (volatile const ULONG *)(const void *)address;

            guest_mailbox_write(ZX_GD_M_READ_VALUE,
                                (unsigned long) ZX_READ_POISON);
            attempted |= bit;
            guest_mailbox_write(ZX_GD_M_ATTEMPTED, (unsigned long) attempted);

            console_puts("  reading my neighbour's data at ");
            console_puthex(address);
            console_puts("\n");

            guest_mailbox_write(ZX_GD_M_READ_VALUE, (unsigned long) *target);
        }
    }

    /* CASE 2 -- the neighbour's data, WRITTEN.  A DIFFERENT WORD of the same
       granule, so that this case has an address of its own and the fault log
       can name it.  Two cases sharing one address would be two log entries
       the hypervisor could not tell apart -- and "the read was refused and
       the write was not" is exactly the asymmetry worth being able to see,
       since a region set with the wrong AP grants one and denies the
       other.  */

    if ((cases & (ULONG) ZX_MC_NEIGHBOUR_WRITE) != 0UL)
    {
        unsigned long neighbour = guest_mailbox_read(ZX_GD_M_NEIGHBOUR);
        unsigned long address   = (neighbour != 0UL) ? (neighbour + 4UL) : 0UL;
        ULONG         bit       = matrix_grant(address,
                                               (ULONG) ZX_MC_NEIGHBOUR_WRITE,
                                               0U, &refused);

        if (bit != 0UL)
        {
            volatile ULONG *target = (volatile ULONG *)(void *)address;

            attempted |= bit;
            guest_mailbox_write(ZX_GD_M_ATTEMPTED, (unsigned long) attempted);

            console_puts("  writing into my neighbour's data at ");
            console_puthex(address);
            console_puts("\n");

            *target = (ULONG) ZX_GUEST_SENTINEL_A;
        }
    }

    /* CASE 4 -- the ADJACENT ungranted granule, which is the case that
       catches a region limit out by ONE granule.  That is the defect class
       which otherwise reads as a working system: an address far from every
       grant proves only that unmapped memory faults, and two region sets a
       whole kilobyte apart would pass a test that only touched the
       neighbour's data.  */

    if ((cases & (ULONG) ZX_MC_HOLE_WRITE) != 0UL)
    {
        unsigned long address = guest_mailbox_read(ZX_GD_M_HOLE);
        ULONG         bit     = matrix_grant(address, (ULONG) ZX_MC_HOLE_WRITE,
                                             0U, &refused);

        if (bit != 0UL)
        {
            volatile ULONG *target = (volatile ULONG *)(void *)address;

            attempted |= bit;
            guest_mailbox_write(ZX_GD_M_ATTEMPTED, (unsigned long) attempted);

            console_puts("  writing into the granule immediately next door\n"
                         "  to my own window, at ");
            console_puthex(address);
            console_puts(", which belongs to nobody\n");

            *target = (ULONG) ZX_GUEST_SENTINEL_A;
        }
    }

    /* CASE 5 -- the HYPERVISOR'S OWN memory, read and then written.  The
       case a safety reviewer asks about first, and the one an "everything
       is mapped, the guest just is not supposed to look" design fails.
       Read BEFORE write, so that a denied read stepped over by the continue
       path still leaves the write to be attempted.
     *
       THE READ LANDS IN ZX_GD_PROBE_SCRATCH, which is the word that exists
       to be written by a probe and read by nobody.  It is there so the load
       cannot be optimised away, and it is that word rather than any other
       because a probe writing into a word something reports through was a
       real defect once: the sentinel landed on the progress bits and the
       seal then certified them.  */

    if ((cases & (ULONG) ZX_MC_HYP_DATA) != 0UL)
    {
        unsigned long address = guest_mailbox_read(ZX_GD_M_HYP_DATA);
        ULONG         bit     = matrix_grant(address, (ULONG) ZX_MC_HYP_DATA,
                                             0U, &refused);

        if (bit != 0UL)
        {
            volatile ULONG *target = (volatile ULONG *)(void *)address;

            attempted |= bit;
            guest_mailbox_write(ZX_GD_M_ATTEMPTED, (unsigned long) attempted);

            console_puts("  reading and then writing the HYPERVISOR'S own\n"
                         "  memory at ");
            console_puthex(address);
            console_puts("\n");

            guest_mailbox_write(ZX_GD_PROBE_SCRATCH, (unsigned long) *target);
            *(target + 1) = (ULONG) ZX_GUEST_SENTINEL_A;
        }
    }

    /* CASE 6 -- hypervisor MMIO.  A partition that could reach the console
       could print as its neighbour; one that could reach the interrupt
       controller could switch off the interrupt that ends its own window.  */

    if ((cases & (ULONG) ZX_MC_HYP_MMIO) != 0UL)
    {
        unsigned long address = guest_mailbox_read(ZX_GD_M_HYP_MMIO);
        ULONG         bit     = matrix_grant(address, (ULONG) ZX_MC_HYP_MMIO,
                                             0U, &refused);

        if (bit != 0UL)
        {
            volatile ULONG *target = (volatile ULONG *)(void *)address;

            attempted |= bit;
            guest_mailbox_write(ZX_GD_M_ATTEMPTED, (unsigned long) attempted);

            console_puts("  writing to hypervisor MMIO at ");
            console_puthex(address);
            console_puts("\n");

            *target = (ULONG) ZX_GUEST_SENTINEL_A;
        }
    }

    /* CASE 3 -- EXECUTE the neighbour's code.  Last of the denials, and the
       only one whose continuation depends on the resume point the helper
       publishes: a prefetch abort cannot be stepped over, because the
       instruction that would be stepped over is the one that could not be
       fetched.  Running it after the data cases means a defect in that path
       costs the sweep one case rather than all of them.
     *
       THE GRANT IS EXECUTABLE HERE.  A branch into memory the guest's own
       MPU marks execute-never is refused by STAGE 1, at EL1, and never
       reaches the hypervisor -- so an execute case run through an ordinary
       data grant would report a stage-1 fault and prove nothing at all
       about stage 2.  */

    if ((cases & (ULONG) ZX_MC_NEIGHBOUR_EXEC) != 0UL)
    {
        unsigned long address = guest_mailbox_read(ZX_GD_M_NEIGHBOUR_CODE);
        ULONG         bit     = matrix_grant(address,
                                             (ULONG) ZX_MC_NEIGHBOUR_EXEC,
                                             1U, &refused);

        if (bit != 0UL)
        {
            attempted |= bit;
            guest_mailbox_write(ZX_GD_M_ATTEMPTED, (unsigned long) attempted);

            console_puts("  BRANCHING into my neighbour's code at ");
            console_puthex(address);
            console_puts("\n");

            if (guest_branch_probe(address,
                                   guest_mailbox_slot(ZX_GD_M_RESUME)) != 0UL)
            {
                console_puts("  *** the branch SUCCEEDED and returned.  I\n"
                             "  *** executed my neighbour's code.\n");
            }
        }
    }

    /* THE SCRATCH GRANT COMES OFF HERE, before the case that must succeed.
       A stage-1 permission left standing after the sweep is a partition
       carrying a grant nothing gave it into every window that follows, and
       every later claim in the run would then be about a machine nobody
       described.  */

    guest_release_scratch_region();

    /* CASE 7 -- ITS OWN WINDOW, and this one must SUCCEED.  A regression
       that only proved things fault would pass with every region
       disabled.  */

    if ((cases & (ULONG) ZX_MC_OWN_MARKS) != 0UL)
    {
        if (matrix_write_marks() != 0UL)
        {
            attempted |= (ULONG) ZX_MC_OWN_MARKS;
            progress  |= (ULONG) ZX_GP_MARKS_OK;
        }
    }

    guest_mailbox_write(ZX_GD_M_ATTEMPTED, (unsigned long) attempted);
    guest_mailbox_write(ZX_GD_M_REFUSED, (unsigned long) refused);

    console_puts("the sweep is over.  I attempted ");
    console_puthex((unsigned long) attempted);
    console_puts(" and refused ");
    console_puthex((unsigned long) refused);
    console_puts("\n");

    return progress;
}


/**************************************************************************/
/*  endless_phase -- what a partition does when it has finished but the   */
/*                   frame has not.                                       */
/*                                                                        */
/*  WHY A GUEST WOULD REFUSE TO HAND THE MACHINE BACK.                     */
/*                                                                        */
/*  A guest that yields is a guest that has finished, and with one         */
/*  partition that was exactly the right ending.  Under a MAJOR FRAME it   */
/*  is the wrong one: a schedule can only be shown to preempt partitions   */
/*  that are still trying to run, and a partition that stopped after its   */
/*  first window would spend every later window being idled through.       */
/*  Nothing about the demonstration would be false; it would simply stop   */
/*  demonstrating the thing.                                              */
/*                                                                        */
/*  So this loop keeps the partition runnable and keeps republishing two   */
/*  numbers the hypervisor cannot obtain for itself: this partition's OWN  */
/*  tick count, and its OWN virtual counter.  Those are what the temporal  */
/*  claim is checked against from the inside -- ZoneX knows how much of    */
/*  the physical counter each partition was given, and only the guest can  */
/*  say what its own clock did over the same span.                        */
/*                                                                        */
/*  THE HOG VARIANT MASKS INTERRUPTS AND THAT IS THE POINT.  With          */
/*  ZX_GO_HOG the loop first disables IRQ and FIQ at EL1 and then never    */
/*  makes another kernel call.  A partition doing this is as               */
/*  uncooperative as an EL1 program can be: it cannot be descheduled by    */
/*  its own kernel, because its own kernel has stopped ticking, and it     */
/*  asks the hypervisor for nothing.                                       */
/*                                                                        */
/*  It must be preempted anyway.  With HCR.FMO set, PSTATE.F is IGNORED    */
/*  at EL0 and EL1, so the FIQ that ends this window reaches EL2 whatever  */
/*  this thread has masked.  All the masking costs is this partition's own */
/*  tick -- which is visible, because ZX_GD_TICKS_NOW stops moving while   */
/*  ZX_GD_LIVE keeps going, and that pair is the evidence.                 */
/*                                                                        */
/*  NO SEAL AND NO CHECKSUM IN HERE, deliberately.  The verdict was        */
/*  published before this was entered, so a run stopped at any point       */
/*  below still carries a complete sealed report; resealing on every       */
/*  iteration would spend the partition's window computing a checksum      */
/*  nobody reads.  These words are outside the seal and zx_guest_abi.h     */
/*  says so.                                                              */
/*                                                                        */
/*  AND IT IS STEERABLE, WHICH IS WHAT MAKES THE DETERMINISM RUN ONE RUN.  */
/*                                                                        */
/*  ZX_GD_M_BEHAVIOUR is re-read on every iteration, so the hypervisor can */
/*  change what this partition is DOING between phases of a single run:    */
/*  quiet, then computing, then computing with its interrupts masked, then */
/*  storming the console, then violating its boundary over and over.  Each */
/*  is one row of the determinism table, and the critical partition's      */
/*  period is measured continuously across all of them.                    */
/*                                                                        */
/*  SIX BUILDS WOULD HAVE BEEN THE OBVIOUS SHAPE AND IT IS THE WEAKER ONE. */
/*  Six images is six boots, six epochs and six sets of switch             */
/*  measurements, so comparing the critical partition's period across them */
/*  compares RUNS rather than phases -- and a difference between two runs  */
/*  has a dozen explanations that a difference between two phases of one   */
/*  run does not.  It is also a sixth of the model time.                   */
/*                                                                        */
/*  RE-READING COSTS NOTHING THE MEASUREMENT CARES ABOUT.  It is one load  */
/*  from a granule this partition already owns: no hypercall, no kernel    */
/*  call, and nothing the masked phase could not do with its interrupts    */
/*  off -- which is what lets the hypervisor steer a partition OUT of a    */
/*  phase it entered by disabling interrupts.  A design that needed an     */
/*  interrupt to end the masked phase could not have one.                  */
/**************************************************************************/

/* How much arithmetic one pass of a compute phase does.
 *
 * A BOUND AND NOT A DURATION.  Its only job is to be long enough that the
 * partition is genuinely computing for a useful fraction of its window and
 * short enough that the behaviour word is re-read often enough to steer.
 * Nothing rests on the number: the phase is ended by the hypervisor
 * changing the word, never by this loop finishing.  */

#define GUEST_COMPUTE_PASS      4000UL

static ULONG endless_compute(ULONG seed)
{
    ULONG index;
    ULONG value = seed;

    /* Arithmetic on a volatile-free local, so the compiler keeps it: a
       compute phase optimised away would leave a partition that looked
       busy in the log and was idle on the core, which is the one thing
       this phase must not be.  The accumulator is returned and published
       for the same reason.  */

    for (index = 0UL; index < (ULONG) GUEST_COMPUTE_PASS; index++)
    {
        value = (value * 1103515245UL) + 12345UL;
        value ^= (value >> 7);
    }

    return value;
}


/* _Noreturn, AND IT IS A CLAIM RATHER THAN A HINT.  The loop below has no
   exit: a partition that reached its window's end and stopped being runnable
   would spend every later window being idled through, and the schedule would
   have nothing left to demonstrate.  ATfE clang proved the function cannot
   return and asked for the declaration (-Wmissing-noreturn); GCC did not.
   Saying it out loud makes a future edit that adds an exit fail to compile
   instead of quietly ending the phase.

   The spelling is the C keyword and not ZX_NORETURN: this file is guest code
   compiled into a ThreadX image and does not include zx_api.h -- see the
   header of zx_guest_bsp.h.  */

static _Noreturn void endless_phase(ULONG options)
{
    ULONG live      = 0UL;
    ULONG work      = 1UL;
    ULONG seen      = 0UL;
    ULONG masked    = 0UL;
    ULONG behaviour = (ULONG) ZX_GB_QUIET;

    /* A VALUE NO BEHAVIOUR TAKES, so that the FIRST pass through the loop
       counts as a change and the opening behaviour is acknowledged like
       every other one.  Initialising this to ZX_GB_QUIET instead left the
       quiet phase unacknowledged -- the hypervisor's check that B had
       obeyed every behaviour it was given saw four of five and failed,
       which is the check working: a phase nobody entered and a phase
       nobody recorded are the same thing from EL2.  */

    ULONG previous  = 0xFFFFFFFFUL;

    guest_mailbox_write(ZX_GD_VCT_START, guest_virtual_count());

    if ((options & (ULONG) ZX_GO_HOG) != 0UL)
    {
        console_puts("HOGGING: masking IRQ and FIQ at EL1 and spinning for\n"
                     "ever.  My own kernel will stop ticking.  The window\n"
                     "must end anyway, because PSTATE.F is ignored at EL1\n"
                     "while the hypervisor routes FIQ to itself -- and I\n"
                     "cannot reach the bit that would change that.\n");

        /* Both masks.  IRQ is this kernel's own tick; F is the one that
           does nothing, and it is set precisely so that the run
           demonstrates it doing nothing.

           ZX_GO_HOG MASKS FOR THE WHOLE RUN and is not a phase.  It is the
           build that turns the central design claim into a test result, so
           it must not be steerable: a hog the hypervisor could talk out of
           hogging would be proving something weaker.  */

        __asm__ volatile("cpsid if" ::: "memory");
        masked = 1UL;
    }
    else
    {
        console_puts("finished, and staying runnable so that the frame has\n"
                     "something to preempt.  My tick count and my own\n"
                     "virtual counter keep going into the mailbox, and I do\n"
                     "whatever the hypervisor's behaviour word asks of me.\n");
    }

    for (;;)
    {
        live++;

        /* THE THREE WORDS FIRST, on every iteration and in every phase.
           They are what the temporal claim is checked against from the
           inside, and a phase that stopped publishing them would look
           exactly like a partition that had stopped running.  Three stores
           into a granule this partition owns: no hypercall, no kernel call,
           and nothing the masked phase cannot do.  */

        guest_mailbox_write(ZX_GD_LIVE, live);
        guest_mailbox_write(ZX_GD_VCT_NOW, guest_virtual_count());
        guest_mailbox_write(ZX_GD_TICKS_NOW, tx_time_get());

        if ((options & (ULONG) ZX_GO_HOG) != 0UL)
        {
            /* The hog build does its own thing and is not steered.  */
            work = endless_compute(work);

            continue;
        }

        behaviour = (ULONG) guest_mailbox_read(ZX_GD_M_BEHAVIOUR);

        if (behaviour != previous)
        {
            /* LEAVING a phase, before entering the next one.  Each of the
               three phases that changes the machine's state undoes it here
               rather than at the point of entry, so that the state a phase
               establishes is exactly the state that phase is measured
               under -- and so that no two phases can ever be half in force
               at once.  */

            if ((previous == (ULONG) ZX_GB_MASKED) && (masked != 0UL))
            {
                __asm__ volatile("cpsie if" ::: "memory");
                masked = 0UL;
            }

            if (previous == (ULONG) ZX_GB_STORM)
            {
                console_set_quiet(1U);
            }

            if (previous == (ULONG) ZX_GB_FAULT)
            {
                guest_release_scratch_region();
            }

            /* ENTERING the next one.  */

            if (behaviour == (ULONG) ZX_GB_MASKED)
            {
                __asm__ volatile("cpsid if" ::: "memory");
                masked = 1UL;
            }

            if (behaviour == (ULONG) ZX_GB_STORM)
            {
                console_set_quiet(0U);
            }

            if (behaviour == (ULONG) ZX_GB_FAULT)
            {
                /* THE GRANT IS WHAT MAKES THIS A STAGE-2 FAULT.  Without
                   it the guest's own MPU refuses first, the abort is taken
                   to EL1, and the hypervisor is never involved -- so the
                   phase would measure a partition faulting on ITSELF,
                   which costs its neighbour nothing for an entirely
                   different reason.  */

                (void) guest_grant_scratch_region(
                    guest_mailbox_read(ZX_GD_M_NEIGHBOUR), 0U);
            }

            seen |= (ULONG) 1U << behaviour;
            guest_mailbox_write(ZX_GD_M_PHASE_SEEN, (unsigned long) seen);
            previous = behaviour;
        }

        if (behaviour == (ULONG) ZX_GB_STORM)
        {
            /* A hypercall per character, which on silicon is the slowest
               thing a partition can do to itself.  Its neighbour must not
               notice.  */

            console_puts("B is talking, and talking, and talking, which is\n"
                         "one hypercall per character through a console it\n"
                         "does not own.\n");
        }
        else if (behaviour == (ULONG) ZX_GB_FAULT)
        {
            unsigned long address = guest_mailbox_read(ZX_GD_M_NEIGHBOUR);

            if (address != 0UL)
            {
                volatile ULONG *target = (volatile ULONG *)(void *)address;

                *target = (ULONG) ZX_GUEST_SENTINEL_A;
            }
        }
        else if (behaviour != (ULONG) ZX_GB_QUIET)
        {
            /* SPIN and MASKED both compute; the difference between them is
               the mask, which was set above and is the whole point.  */

            work = endless_compute(work);
        }
        else
        {
            /* Quiet: the three words above and nothing else.  */
        }
    }
}


/**************************************************************************/
/*  consumer_entry                                                        */
/*                                                                        */
/*  Drains the queue, checks each message is the one the producer sent in  */
/*  that order, exercises the semaphore, and produces the verdict.         */
/*                                                                        */
/*  CHECKING THE VALUE AND NOT MERELY THE COUNT.  A queue that delivered   */
/*  four messages in the wrong order, or four copies of one message,       */
/*  would satisfy a count and would mean the kernel's queue was broken     */
/*  under stage 2.  The sequence is what catches that.                     */
/**************************************************************************/

static void consumer_entry(ULONG thread_input)
{
    ULONG expected = 0xC0DE0000UL;
    ULONG progress = 0UL;

    (void) thread_input;

    while (messages_carried < (ULONG) GUEST_ITERATIONS)
    {
        ULONG message = 0UL;

        consumer_slices++;

        if (tx_queue_receive(&work_queue, &message, TX_NO_WAIT) == TX_SUCCESS)
        {
            if (message != expected)
            {
                queue_faults++;
            }

            expected++;
            messages_carried++;

            console_puts("consumer received ");
            console_puthex(message);
            console_puts("\n");
        }
        else if (producer_slices >= (ULONG) GUEST_ITERATIONS)
        {
            /* The producer has finished and the queue is empty, so nothing
               more will ever arrive.  Without this the loop would spin
               forever: there is no tick, so nothing would interrupt it and
               the run would end in a timeout rather than in a report.

               THE TEST USES THE RESULT OF THE RECEIVE ABOVE and does not
               perform one of its own.  An earlier version called
               tx_queue_receive a second time here to ask whether the queue
               was empty -- which CONSUMED a message and threw it away, so
               the run reported two messages carried out of four and one of
               them out of order.  A question that changes the thing it is
               asking about is not a question.  */
            break;
        }
        else
        {
            /* Empty, but the producer is still going: let it run.  */
        }

        tx_thread_relinquish();
    }

    if (queue_faults == 0UL)
    {
        progress |= (ULONG) ZX_GP_QUEUE_OK;
    }

    /* The semaphore.  Created with a count of one, so the first get
       succeeds and the second must fail with TX_NO_WAIT -- both halves are
       checked, because a semaphore that granted everything would pass a test
       that only took it once.  */

    if (tx_semaphore_get(&handover, TX_NO_WAIT) != TX_SUCCESS)
    {
        semaphore_faults++;
    }

    if (tx_semaphore_get(&handover, TX_NO_WAIT) == TX_SUCCESS)
    {
        semaphore_faults++;
    }

    if (tx_semaphore_put(&handover) != TX_SUCCESS)
    {
        semaphore_faults++;
    }

    if (semaphore_faults == 0UL)
    {
        progress |= (ULONG) ZX_GP_SEMAPHORE_OK;
    }

    /* THE PREEMPTIVE PHASE, if the hypervisor granted this partition a
       clock.  It comes BEFORE the probe on purpose: the probe may end the
       excursion at a stage-2 boundary, and a claim that was never reached
       is indistinguishable from one that failed.  */

    if (guest_tick_granted != 0UL)
    {
        progress |= preemptive_phase();
    }

    console_puts("threads ran, producer/consumer slices = ");
    console_putdec(producer_slices);
    console_puts(" / ");
    console_putdec(consumer_slices);
    console_puts("\n");
    console_puts("messages carried = ");
    console_putdec(messages_carried);
    console_puts(", queue faults = ");
    console_putdec(queue_faults);
    console_puts(", semaphore faults = ");
    console_putdec(semaphore_faults);
    console_puts("\n");

    /* THE PROBE, if the hypervisor asked for one.
     *
     * The address comes from the mailbox rather than from a build option, so
     * ONE guest image serves every case the hypervisor wants to demonstrate:
     * an address outside the partition window (a stage-2 violation), the
     * guest's own code (permitted by stage 2 and refused by the guest's own
     * MPU -- a STAGE-1 fault, which never reaches EL2 at all), and an
     * address the guest is genuinely granted (which must SURVIVE, and is how
     * the check is proved able to fail).
     *
     * That matters for more than build time.  A separate guest binary per
     * case is a set of binaries that can drift apart, and the one that
     * demonstrates isolation would then no longer be the one that
     * demonstrates the kernel running.  Here they are the same bytes.
     *
     * PROBE_SURVIVED is set only AFTER the write completes, so its absence
     * is the evidence that the access was stopped -- by whichever stage
     * stopped it.  A check whose pass condition is the absence of something
     * has to be able to fail, which is what the granted-address build is
     * for.  */

    /* THE SWEEP, if the hypervisor asked for one.  It and the single probe
       below are alternatives rather than a sequence: the probe aims one
       access at one address and ENDS the excursion when stage 2 refuses it,
       which is the shipping fault policy and the right shape for an image
       demonstrating one violation.  The sweep needs the hypervisor's
       test-only continue mode to get past its first case at all, so an
       image that set both would run the sweep and then have its probe cut
       short by whichever case happened to be last.  The hypervisor sets one
       or the other; this is where they part.  */

    progress |= isolation_matrix();

    if (guest_mailbox_read(ZX_GD_TARGET) != 0UL)
    {
        /* READ ONCE, THEN CAST THE VALUE.  The mailbox was read three times
           here -- once for the test above and twice more to build these two
           -- and the address the guest probed was therefore not provably the
           address it printed.  The hypervisor does not rewrite the mailbox
           under a running partition today, so the three reads did agree;
           "did agree" is not the property this line needs.

           And casting the READ rather than the CALL is what -Wbad-function-
           cast asks for, which is MISRA C:2012 Rule 11.4's territory: an
           integer-to-pointer conversion is worth a name and a line of its
           own, not a cast stack in the middle of an initialiser.  */

        unsigned long   address = guest_mailbox_read(ZX_GD_TARGET);
        volatile ULONG *target  = (volatile ULONG *)(void *)address;

        console_puts("probing ");
        console_puthex(address);
        console_puts("\n");

        /* If the guest's own MPU does not already cover the address, grant
           it -- otherwise STAGE 1 denies the access and the fault is taken
           to EL1, and a stage-2 violation could never be demonstrated from
           a real kernel at all.  When it IS already covered, granting again
           would create an overlap, which is CONSTRAINED UNPREDICTABLE.  */

        if (guest_grant_probe_region(address) != 0U)
        {
            console_puts("my own MPU did not cover it, so I granted myself\n"
                         "that granule -- stage 2 has the last word\n");
        }
        else
        {
            console_puts("my own MPU already covers it\n");
        }

        guest_mailbox_write(ZX_GD_PROBED, 0UL);
        publish(0UL);

        *target = (ULONG) ZX_GUEST_SENTINEL_A;

        guest_mailbox_write(ZX_GD_PROBED, (unsigned long) *target);
        progress |= (ULONG) ZX_GP_PROBE_SURVIVED;

        console_puts("the probe SURVIVED, so nothing denied it\n");
    }

    /* The verdict, written into the mailbox BEFORE it is printed.  A guest
       that printed a verdict it had not published would let a reader believe
       something the hypervisor cannot confirm.
     *
     * WHAT A PASS MEANS DEPENDS ON WHAT WAS GRANTED, and the guest is the
     * only party that can apply that rule.  The hypervisor knows what it
     * ASKED for; only the guest knows what it MANAGED.  A partition given a
     * clock must have used it -- reporting PASSED on a run where the tick
     * never arrived would be a guest quietly downgrading its own verdict to
     * whatever it happened to achieve, and the hypervisor reading a sealed
     * PASSED back has no way to know that is what it means.  */

    if ((guest_tick_granted != 0UL)
        && ((progress & (ULONG) (ZX_GP_COUNTING | ZX_GP_TICKING
                                 | ZX_GP_PREEMPTED | ZX_GP_TIMESLICED))
            != (ULONG) (ZX_GP_COUNTING | ZX_GP_TICKING
                        | ZX_GP_PREEMPTED | ZX_GP_TIMESLICED)))
    {
        guest_mailbox_write(ZX_GD_VERDICT, (unsigned long) ZX_GV_FAILED);
        progress |= (ULONG) ZX_GP_FINISHED;
        publish(progress);
        console_puts("GUEST RESULT: FAILED -- a clock was granted and this\n"
                     "partition did not get everything a clock is for\n");
    }
    else if ((messages_carried == (ULONG) GUEST_ITERATIONS)
             && (queue_faults == 0UL)
             && (semaphore_faults == 0UL))
    {
        guest_mailbox_write(ZX_GD_VERDICT, (unsigned long) ZX_GV_PASSED);
        progress |= (ULONG) ZX_GP_FINISHED;
        publish(progress);
        console_puts("GUEST RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        guest_mailbox_write(ZX_GD_VERDICT, (unsigned long) ZX_GV_FAILED);
        progress |= (ULONG) ZX_GP_FINISHED;
        publish(progress);
        console_puts("GUEST RESULT: FAILED\n");
    }

    /* AND THEN ONE OF TWO ENDINGS, chosen by the hypervisor rather than by
       the build.
     *
       Back to the hypervisor, on purpose, is the right ending for an image
       that runs one partition: a guest that simply returned from its last
       thread would leave the kernel idling inside a partition nothing would
       ever take back, and the run would time out rather than report.
     *
       Under a major frame it is the wrong ending, because a schedule can
       only be shown to preempt partitions that are still trying to run.
       ZX_GO_FOREVER keeps this one runnable; see endless_phase.  */

    if ((guest_mailbox_read(ZX_GD_OPTIONS)
         & (unsigned long) ZX_GO_FOREVER) != 0UL)
    {
        endless_phase((ULONG) guest_mailbox_read(ZX_GD_OPTIONS));
    }

    guest_yield();
}


/**************************************************************************/
/*  tx_application_define                                                 */
/**************************************************************************/

void tx_application_define(void *first_unused_memory)
{
    (void) first_unused_memory;

    publish((ULONG) ZX_GP_KERNEL_ENTERED);

    (void) tx_queue_create(&work_queue, "work", TX_1_ULONG,
                           queue_storage, sizeof(queue_storage));

    (void) tx_semaphore_create(&handover, "handover", 1UL);

    /* EQUAL PRIORITIES, and that is what makes this a context-switch test.
       tx_thread_relinquish yields to the next ready thread OF THE SAME
       priority; between threads of different priorities it does nothing
       observable, and the higher one simply runs to completion.  An earlier
       version created the consumer one priority lower and the two never
       interleaved at all -- which still delivered every message, and
       therefore still would have passed a weaker check than the one here.

       Creation order then decides who runs first, which is what keeps the
       message ordering deterministic without a tick to arbitrate.  */

    (void) tx_thread_create(&thread_producer, "producer", producer_entry, 0UL,
                            producer_stack, sizeof(producer_stack),
                            GUEST_WORKER_PRIORITY, GUEST_WORKER_PRIORITY,
                            TX_NO_TIME_SLICE, TX_AUTO_START);

    (void) tx_thread_create(&thread_consumer, "consumer", consumer_entry, 0UL,
                            consumer_stack, sizeof(consumer_stack),
                            GUEST_WORKER_PRIORITY, GUEST_WORKER_PRIORITY,
                            TX_NO_TIME_SLICE, TX_AUTO_START);

    /* THE TWO SPINNERS EXIST ONLY WHEN A CLOCK WAS GRANTED, and that is
       what keeps a cooperative excursion of this image the same program it
       was before a tick existed.  Created, they would never run -- they sit
       below the worker priority and the workers only ever relinquish, which
       yields within a priority -- but they would still cost two thread
       control blocks, two stacks and two passes of the scheduler's ready
       list, and the cooperative pass is one half of a measured pair.

       TX_TIMESLICE and not TX_NO_TIME_SLICE, obviously, and the value is
       what the second claim rests on: two threads at ONE priority, neither
       of which ever yields, can only interleave because the kernel counts
       their slice down on a tick.  */

    if (guest_tick_granted != 0UL)
    {
        (void) tx_thread_create(&thread_spin_a, "spin A", spin_entry, 0UL,
                                spin_a_stack, sizeof(spin_a_stack),
                                GUEST_SPIN_PRIORITY, GUEST_SPIN_PRIORITY,
                                GUEST_SPIN_SLICE, TX_AUTO_START);

        (void) tx_thread_create(&thread_spin_b, "spin B", spin_entry, 1UL,
                                spin_b_stack, sizeof(spin_b_stack),
                                GUEST_SPIN_PRIORITY, GUEST_SPIN_PRIORITY,
                                GUEST_SPIN_SLICE, TX_AUTO_START);
    }
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 from the port's own boot path.             */
/*                                                                        */
/*  THE ORDER HERE MATTERS AND IS SHORT ENOUGH TO STATE IN FULL:          */
/*                                                                        */
/*    REPORT BSP_MAIN, before anything that can fail.  If the guest dies   */
/*    from here on, the hypervisor still knows the ERET landed and the     */
/*    port's boot path completed -- which rules out the entire loader.     */
/*                                                                        */
/*    INSTALL THE GUEST'S OWN VECTORS, so that a fault from here onwards   */
/*    is reported rather than fatal.  This comes second and not first on   */
/*    purpose: installing vectors before the mailbox write would mean a    */
/*    fault during the install itself had nowhere to report to, and the    */
/*    mailbox write is the cheaper of the two to get right.                */
/*                                                                        */
/*    ENABLE THE GUEST'S OWN MPU.  After this the guest is confined by     */
/*    stage 1 as well as stage 2, and a mistake in either shows up         */
/*    immediately -- which is the point of doing it before the kernel      */
/*    rather than after.                                                   */
/*                                                                        */
/*    ENTER THE KERNEL.                                                    */
/**************************************************************************/

void bsp_main(void)
{
    unsigned int regions;

    publish((ULONG) ZX_GP_BSP_MAIN);

    /* Before the first print, so that a quiet run really is quiet.  See the
       note on ZX_GO_QUIET in zx_guest_abi.h: the measured passes cost
       nothing on the console and the demonstration pass shows everything,
       from the same image.  */

    console_set_quiet(((guest_mailbox_read(ZX_GD_OPTIONS)
                        & (unsigned long) ZX_GO_QUIET) != 0UL) ? 1U : 0U);

    /* WHETHER THIS PARTITION HAS A CLOCK, read ONCE and kept.  The mailbox
       is the hypervisor's to write and a guest that re-read it per decision
       could find it changed halfway through a run -- so the answer is taken
       at the top, in the same breath as the console option, and everything
       downstream asks this variable.

       The port's board support has already read the same word, in board_init
       during tx_kernel_enter, and decided whether to arm anything.  Reading
       it twice is right rather than redundant: the two readers want the same
       fact at two moments a partition switch could fall between, and neither
       can ask the other.  */

    guest_tick_granted = ((guest_mailbox_read(ZX_GD_OPTIONS)
                           & (unsigned long) ZX_GO_TICK) != 0UL) ? 1UL : 0UL;

    guest_vectors_install();

    console_puts("ThreadX guest at EL1, inside a ZoneX partition\n");
    console_puts("mailbox sentinel from the hypervisor = ");
    console_puthex(guest_mailbox_read(ZX_GD_SCRATCH));
    console_puts("\n");

    regions = guest_mpu_init();

    if (regions == 0U)
    {
        console_puts("this part has too few EL1 regions for this guest;\n"
                     "refusing to enable stage 1 rather than programming a\n"
                     "region index the implementation does not have\n");
        guest_mailbox_write(ZX_GD_VERDICT, (unsigned long) ZX_GV_FAILED);
        publish((ULONG) ZX_GP_FINISHED);
        guest_yield();
        return;
    }

    console_puts("stage-1 MPU on: ");
    console_putdec(regions);
    console_puts(" EL1 regions, SCTLR.M = ");
    console_putdec(guest_mpu_is_enabled());
    console_puts("\n");
    console_puts("every one of them lies inside this partition's stage-2\n"
                 "window, or the guest would fault on memory its own MPU\n"
                 "says it owns -- the stricter of the two stages wins\n");

    if (guest_tick_granted != 0UL)
    {
        console_puts("this partition was granted a CLOCK: the virtual timer\n"
                     "on PPI ");
        console_putdec((ULONG) ZX_GUEST_TIMER_INTID);
        console_puts(", enabled for me in a redistributor I cannot\n"
                     "reach.  CNTFRQ reads ");
        console_putdec(guest_counter_frequency());
        console_puts(" Hz, programmed by the\n"
                     "hypervisor because it is writable only above me.  I\n"
                     "bring up my own CPU interface, which is system\n"
                     "registers and touches no device at all.\n");
    }
    else
    {
        console_puts("no clock was granted, so this partition takes no\n"
                     "interrupts: cooperative scheduling only, and\n"
                     "tx_thread_sleep would never return.\n");
    }

    tx_kernel_enter();
}
