/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  GUEST SUPPORT                                          DESCRIPTION    */
/*                                                                        */
/*    zx_guest_bsp.h                                       GUEST          */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    What a ThreadX guest running inside a ZoneX partition needs from    */
/*    its own board support, which is very little -- and the "very        */
/*    little" is the interesting part of this whole step.                 */
/*                                                                        */
/*    A partition owns no device.  It has no UART, no interrupt           */
/*    controller and no timer of its own; the hypervisor holds all three. */
/*    So the board support here is a console that ASKS, a stage-1 MPU     */
/*    confined to the partition's own window, and a mailbox.  Everything  */
/*    else an ordinary Cortex-R52 board file does is either the           */
/*    hypervisor's job now or does not exist.                             */
/*                                                                        */
/*  THIS IS GUEST CODE, NOT ZONEX CODE                                    */
/*                                                                        */
/*    It is compiled into the guest image by the guest's own toolchain     */
/*    invocation and links against ThreadX, not against ZoneX.  It uses    */
/*    ThreadX's type names and C99 conventions rather than ZoneX's, which  */
/*    is why nothing here spells ZX_NODISCARD or includes zx_api.h.  The   */
/*    only header shared across the boundary is zx_guest_abi.h, which is   */
/*    the contract itself.                                                */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_GUEST_BSP_H
#define ZX_GUEST_BSP_H

/**************************************************************************/
/*                              The console                               */
/**************************************************************************/

/* Write through the hypervisor, one character per hypercall.
 *
 * WHY THE GUEST DOES NOT OWN A UART.  There is one console device and there
 * will be more than one partition.  Mapping the device into every partition
 * would put MMIO in every partition's stage-2 region set and lengthen the
 * isolation claim the whole component exists to make; giving it to one
 * partition would leave the other mute.  So the guest asks and the
 * hypervisor writes, and the hypervisor tags the line with the partition it
 * scheduled -- which is also why the guest cannot lie about who it is.
 *
 * THE COST IS REAL AND IS NOT HIDDEN.  A trap per character is the slowest
 * thing this guest does, and it sits on the critical path of the
 * partition's time window.  A partition that is printing is not a partition
 * whose timing should be measured.  */

void console_puts(const char *string_ptr);
void console_puthex(unsigned long value);
void console_putdec(unsigned long value);

/* Suppress the console for this run.
 *
 * NOT a debugging convenience.  One hypercall per character through a polled
 * UART is, on silicon, three orders of magnitude more work than everything
 * else this guest does -- so a run with the console on can only BOUND the
 * cost of stage 2 from above, and cannot resolve it.  The hypervisor
 * therefore measures quiet passes and demonstrates a loud one, from the same
 * guest image, so that the run being measured is the run being shown.  */

void console_set_quiet(unsigned int quiet);

/* Hand the machine back to the hypervisor on purpose, as opposed to being
   taken from it by a fault.  The distinction is what lets a run say "the
   guest finished" rather than only "the guest is no longer running".  */

void guest_yield(void);

/**************************************************************************/
/*              What the PORT calls, and the guest supplies               */
/*                                                                        */
/*  These four are not part of ZoneX's design; they are the Cortex-R52     */
/*  port's board-support contract, and the guest implements them because   */
/*  it is the board.  entry.S calls bsp_main, _tx_initialize_low_level     */
/*  calls board_init, and the EL1 IRQ and FIQ vectors call the other two.  */
/*                                                                        */
/*  DECLARED HERE RATHER THAN BY INCLUDING THE PORT'S board.h, which does  */
/*  declare all four.  The two boards' copies of that header differ --     */
/*  one carries an identity structure, the other a set of interrupt-       */
/*  nesting counters -- and the files that implement these are SHARED      */
/*  between the two boards, so including it would make one source depend   */
/*  on two different headers depending on which board it was compiled for. */
/*                                                                        */
/*  They are declared at all because a definition with no prototype is a   */
/*  MISRA Rule 8.4 finding, and because a function nothing declares is a   */
/*  function nothing checks the signature of.  The caller is assembly,     */
/*  which cannot be checked against either -- so the declaration is worth  */
/*  no less for that, and the port's own board files carry it for the same */
/*  reason.                                                                */
/**************************************************************************/

void bsp_main(void);
void board_init(void);
void board_irq_handler(void);
void board_fiq_handler(void);

/**************************************************************************/
/*                    The clock a partition is granted                    */
/*                                                                        */
/*  A partition owns no timer device.  What it has is the VIRTUAL timer    */
/*  and the virtual counter, whose zero point the hypervisor moves with    */
/*  CNTVOFF so that time does not pass while the partition is not running. */
/*  Every one of these is a system-register access; none of them touches a */
/*  device, and none of them can be denied to EL1 -- it is the PHYSICAL    */
/*  counter that ZoneX keeps out of a partition's reach.                   */
/*                                                                        */
/*  board_init below decides whether the timer is armed at all, from a     */
/*  word the hypervisor left in the mailbox.  These are separate from it   */
/*  so that the guest APPLICATION can ask its own questions -- above all   */
/*  "is this counter moving?", which is what stands between a target whose */
/*  system counter was never started and a run that ends in a timeout.     */
/**************************************************************************/

/* CNTFRQ, which only the hypervisor can have written.  Zero means nobody
   did, and dividing by it is a divide by zero rather than a slow tick.  */

unsigned long guest_counter_frequency(void);

/* The low half of CNTVCT.  Enough to answer "is it moving"; deliberately
   not enough to be mistaken for a wall clock.  */

unsigned long guest_virtual_count(void);

/* Restart the down-count, which also deasserts the timer's level output.
   Called on every tick from inside the interrupt handler.  */

void guest_tick_reload(void);

/* Read the virtual counter twice, bounded, and say whether it moved.  The
   bound is what makes this a check rather than a second way to hang.  */

unsigned int guest_counter_is_moving(void);

/**************************************************************************/
/*                            The stage-1 MPU                             */
/**************************************************************************/

/* Program the guest's own EL1 regions and enable SCTLR.M.
 *
 * A partition's own MPU is not decoration.  Stage 2 confines the partition
 * to its window; stage 1 confines the guest's THREADS within that window,
 * which is the protection a kernel is expected to provide and which stage 2
 * cannot express -- stage 2 sees one window, not the code and data inside
 * it.
 *
 * THE STRICTER OF THE TWO STAGES WINS, at both permissions and attributes.
 * Every EL1 region programmed here lies inside the partition's stage-2
 * window, or the guest would fault on memory its own MPU says it owns --
 * which reads as a kernel bug and is not one.  The linker script asserts
 * the geometry that makes that true.
 *
 * Returns the number of regions programmed, or zero when the part has too
 * few to hold them.  Refusing is the difference between a clear message and
 * a region programmed at an index the implementation does not have, which is
 * UNPREDICTABLE and presents as a hang.  */

unsigned int guest_mpu_init(void);

unsigned int guest_mpu_region_count(void);
unsigned int guest_mpu_is_enabled(void);

/* Make one granule reachable at EL1, if the guest's own regions do not
 * already cover it.
 *
 * THIS EXISTS SO THAT A STAGE-2 VIOLATION IS REACHABLE FROM A REAL KERNEL.
 * Both stages are checked and the stricter wins, so an address outside the
 * guest's own EL1 regions is denied by STAGE 1 -- and a stage-1 fault is
 * taken to EL1 and never reaches the hypervisor.  A guest whose own MPU
 * stops at its window boundary therefore cannot demonstrate that stage 2
 * stops anything: stage 1 gets there first.
 *
 * So when the hypervisor asks the guest to probe an address its own MPU does
 * not cover, the guest GRANTS ITSELF that granule and then probes.  Its own
 * MPU now says it owns memory the manifest never gave it, which is exactly
 * the configuration worth demonstrating: stage 2 refuses anyway.
 *
 * A target the guest ALREADY covers gets no new region, and that is not an
 * optimisation.  Two enabled regions matching one address is CONSTRAINED
 * UNPREDICTABLE at either stage and aborts on the S32Z280, so overlapping an
 * existing region to "make sure" would break the very run it was meant to
 * enable.
 *
 * Returns non-zero when a region was added.  */

unsigned int guest_grant_probe_region(unsigned long target);

/* Install the guest's own EL1 vector table.  Called before anything can
   fault at EL1 with an opinion worth recording.  */

void guest_vectors_install(void);

/**************************************************************************/
/*                              The mailbox                               */
/**************************************************************************/

/* Publish everything the guest has to report, in the order that makes a
   torn update detectable.  See the note on the readback convention in
   zx_guest_abi.h.  */

void guest_report(unsigned long progress_bits);

/* Read one word the hypervisor left for the guest, and write one the guest
   wants reported.
 *
 * The reported fields are written through here and the SEQUENCE and CHECKSUM
 * only by guest_report, which is what keeps the ordering rule in one place:
 * a caller that wrote its own checksum would be free to write it first.  */

unsigned long guest_mailbox_read(unsigned long offset);
void guest_mailbox_write(unsigned long offset, unsigned long value);

#endif /* ZX_GUEST_BSP_H */
