/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  GUEST SUPPORT                                          DESCRIPTION    */
/*                                                                        */
/*    zx_guest_bsp.c                                       GUEST          */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Board support for a ThreadX guest inside a ZoneX partition: a       */
/*    console that hypercalls, an EL1 MPU confined to the partition's own */
/*    window, and the readback mailbox.                                   */
/*                                                                        */
/*  THREE THINGS A STANDALONE BSP DOES THAT A PARTITION MUST NOT          */
/*                                                                        */
/*    Each of these is marked where it would have gone, so that whoever   */
/*    adds the second partition finds them rather than rediscovers them:  */
/*                                                                        */
/*      1.  IT OWNS THE CONSOLE DEVICE.  Two partitions cannot both drive */
/*          one UART.  Resolved here: the guest hypercalls and the        */
/*          hypervisor writes.  See console_putc below.                   */
/*                                                                        */
/*      2.  IT INITIALISES THE GIC DISTRIBUTOR AND THE REDISTRIBUTOR.     */
/*          Both are shared: there is one distributor for the system and  */
/*          one redistributor per CORE, and every partition on this core  */
/*          shares that redistributor.  Resolved here by NOT DOING IT AT  */
/*          ALL.  The hypervisor owns every byte of GIC memory-mapped     */
/*          state and enables a partition's timer PPI on its behalf; the  */
/*          guest brings up only its own CPU INTERFACE, which on this     */
/*          part is system registers and touches no device.  See          */
/*          guest_interrupts_init below.                                  */
/*                                                                        */
/*      3.  IT USES THE PHYSICAL TIMER.  A partition's physical time      */
/*          keeps running while it is descheduled, so a guest on the      */
/*          physical timer can observe that it was not running -- which   */
/*          is exactly the temporal-determinism claim, lost.  Resolved    */
/*          here: this guest arms the VIRTUAL timer, whose counter the    */
/*          hypervisor freezes with CNTVOFF while the partition is not    */
/*          running.  The guest cannot reach the physical counter at all: */
/*          CNTHCTL.PL1PCTEN and PL1PCEN are left clear at EL2 on         */
/*          purpose.  See docs/decisions.md D7 and D23.                   */
/*                                                                        */
/*    All three are now answered, and the shape of each answer is the     */
/*    same: the guest keeps what is PER-THREAD or PER-CORE-INTERFACE and  */
/*    gives up what is SHARED.  A partition may acknowledge an interrupt  */
/*    and read a clock; it may not decide which interrupts exist or how   */
/*    fast time runs.                                                     */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Directive 4.3 -- every asm statement below is one hypercall or one  */
/*      coprocessor operation, in a function that does nothing else.      */
/*    Rule 11.4 -- casting a linker symbol's address to an integer is     */
/*      inherent to describing memory to an MPU.                          */
/*                                                                        */
/**************************************************************************/

/* tx_api.h is here for ONE constant: TX_TIMER_TICKS_PER_SECOND, which the
   virtual timer's interval is derived from.  The kernel and its board
   support have to agree about how long a tick is, and taking the number
   from the kernel's own header is the only way that agreement cannot
   drift.  */

#include "tx_api.h"

#include "zx_guest_abi.h"
#include "zx_guest_bsp.h"

/* The window geometry, from the guest's own linker script.  Declared as
   arrays of unknown size, which is the portable way to name a linker symbol
   whose ADDRESS is the value wanted.  */

extern char zx_guest_mailbox[];
extern char zx_guest_vectors[];

extern char __zx_guest_window_base[];
extern char __zx_guest_window_end[];
extern char __zx_guest_code_start[];
extern char __zx_guest_code_end[];
extern char __zx_guest_data_start[];

/* SCTLR bits this file touches.  */

#define SCTLR_M             (1UL << 0)
#define SCTLR_BR            (1UL << 17)

/* PRBAR/PRLAR field positions, EL1.  These are the EL1 encodings and NOT the
   stage-2 ones: at EL1, AP[2:1] means "read-only" and "unprivileged access",
   which is a different question from the one stage 2 asks.  Getting the two
   confused produces a region that programs cleanly and grants the wrong
   thing, so they are spelled out here rather than shared with anything.  */

/* Named for WHAT THEY GRANT rather than for the level they grant it at, and
   the level does not end the name.  A macro ending in _EL1 reads as an
   AArch64 system-register spelling, which does not exist on this target at
   all -- scripts/check_terminology.sh rejects the shape in CI, and it is
   right to: the whole class of mistake it guards against is code written
   against the wrong architecture that reads plausibly.  */

#define EL1_AP_PRIV_RW      0x0UL   /* 00: RW at EL1, no EL0 access         */
#define EL1_AP_ANY_RW       0x1UL   /* 01: RW at EL1 and EL0                */
#define EL1_AP_PRIV_RO      0x2UL   /* 10: RO at EL1, no EL0 access         */
#define EL1_AP_ANY_RO       0x3UL   /* 11: RO at EL1 and EL0                */

#define EL1_SH_NON          0x0UL

/* MAIR indices this guest programs.  Index 0 is Normal write-back and index
   1 is Device; index 1 is written explicitly even though it is unused,
   because an UNWRITTEN MAIR byte reads as zero -- which is Device-nGnRnE,
   memory that works slowly with nothing to fault on.  A wrong index should
   produce a wrong attribute, not a plausible one.  */

#define ATTR_NORMAL_WB      0UL
#define ATTR_DEVICE         1UL

#define MAIR0_VALUE         0x000000FFUL    /* byte 0 = 0xFF, byte 1 = 0x00 */
#define MAIR1_VALUE         0x00000000UL

#define GRANULE_MASK        0xFFFFFFC0UL

/* HVC takes a literal immediate, not a register, so the constant has to be
   pasted into the instruction text.  Two levels, because the argument is
   itself a macro and one level would stringify its NAME.  */

#define ZX_GUEST_STRINGIFY_1(value) #value
#define ZX_GUEST_STRINGIFY(value)   ZX_GUEST_STRINGIFY_1(value)

static unsigned int guest_mpu_regions_used;

/* Whether the console is suppressed for this run.  Read ONCE, out of the
   mailbox, rather than consulted per character: the whole point of the quiet
   run is that a character costs nothing, and a mailbox read per character
   would put a load back on the path the measurement is trying to empty.  */

static unsigned int guest_console_quiet;


/**************************************************************************/
/*  read_mpuir / region availability                                      */
/**************************************************************************/

unsigned int guest_mpu_region_count(void)
{
    unsigned long value;

    __asm__ volatile("mrc p15, 0, %0, c0, c0, 4" : "=r"(value));

    /* MPUIR keeps the EL1 region count in bits [15:8].  HMPUIR keeps the EL2
       count in bits [7:0].  Two different registers with the field in two
       different places is exactly the kind of detail that is wrong once and
       then copied, so it is written here and nowhere else in the guest.  */

    return (unsigned int)((value >> 8) & 0xFFUL);
}


unsigned int guest_mpu_is_enabled(void)
{
    unsigned long sctlr;

    __asm__ volatile("mrc p15, 0, %0, c1, c0, 0" : "=r"(sctlr));

    return ((sctlr & SCTLR_M) != 0UL) ? 1U : 0U;
}


/**************************************************************************/
/*  program_region -- one EL1 region, left enabled.                       */
/*                                                                        */
/*  BOTH ADDRESSES ARE MASKED TO THE GRANULE BEFORE ANYTHING IS ORED IN.  */
/*  An under-aligned base does not fault: its low bits land on SH, AP and  */
/*  XN and silently change what the region grants.  An unmasked limit is   */
/*  worse -- a limit computed as base + size - 1 ends in 0x3F, which lands */
/*  on AttrIndx and selects a MAIR byte nobody wrote.  Both traps were     */
/*  paid for at EL1 during the Cortex-R52 port work; they are repeated     */
/*  here because a guest programs its own MPU with exactly the same        */
/*  registers.                                                            */
/**************************************************************************/

static void program_region(unsigned int index, unsigned long base,
                           unsigned long limit, unsigned long ap,
                           unsigned long execute_never, unsigned long attr)
{
    unsigned long prbar = (base & GRANULE_MASK)
                        | ((EL1_SH_NON & 0x3UL) << 3)
                        | ((ap & 0x3UL) << 1)
                        | (execute_never & 0x1UL);

    unsigned long prlar = (limit & GRANULE_MASK)
                        | ((attr & 0x7UL) << 1)
                        | 0x1UL;                    /* EN */

    __asm__ volatile("mcr p15, 0, %0, c6, c2, 1" : : "r"((unsigned long)index));
    __asm__ volatile("isb");
    __asm__ volatile("mcr p15, 0, %0, c6, c3, 0" : : "r"(prbar));
    __asm__ volatile("mcr p15, 0, %0, c6, c3, 1" : : "r"(prlar));
    __asm__ volatile("isb");
}


/**************************************************************************/
/*  guest_mpu_init                                                        */
/*                                                                        */
/*  THREE REGIONS, AND THE MAILBOX IS ONE OF THEM ON PURPOSE.             */
/*                                                                        */
/*    0  the mailbox      RW, execute-never                               */
/*    1  code and rodata  READ-ONLY, executable                           */
/*    2  data, bss and every stack   RW, execute-never                    */
/*                                                                        */
/*  The mailbox needs a region of its own precisely because it is WRITABLE */
/*  and sits at the front of a window whose next section is read-only      */
/*  code.  PMSAv8-R has no region priority, so it cannot be carved out of  */
/*  the code region by overlapping it -- two enabled regions on one        */
/*  address is CONSTRAINED UNPREDICTABLE and aborts on the S32Z280.       */
/*                                                                        */
/*  CACHES STAY OFF, and that is a decision rather than an omission.  A    */
/*  guest with a write-back data cache leaves its mailbox DIRTY IN CACHE   */
/*  where the hypervisor reading it from EL2 -- with EL2's own caches off  */
/*  -- would see stale words and report a guest that never got anywhere.   */
/*  Turning guest caches on therefore needs either a non-cacheable         */
/*  attribute on the mailbox granule or an explicit clean before every     */
/*  report, and that belongs with the timing work rather than with the     */
/*  first launch.  One variable at a time.                                 */
/*                                                                        */
/*  SCTLR.BR IS LEFT CLEAR, so an EL1 access that hits no region FAULTS    */
/*  rather than falling back to a background map.  That is the entire      */
/*  point of the guest having an MPU at all: without it the three regions  */
/*  above would be advisory.                                              */
/**************************************************************************/

unsigned int guest_mpu_init(void)
{
    unsigned int available = guest_mpu_region_count();
    unsigned int index;
    unsigned long sctlr;

    guest_mpu_regions_used = 3U;

    if (available < guest_mpu_regions_used)
    {
        guest_mpu_regions_used = 0U;
        return 0U;
    }

    /* MAIR before any region, because a region whose AttrIndx selects an
       unwritten byte gets Device-nGnRnE and works -- slowly, with nothing to
       fault on.  */

    __asm__ volatile("mcr p15, 0, %0, c10, c2, 0" : : "r"(MAIR0_VALUE));
    __asm__ volatile("mcr p15, 0, %0, c10, c2, 1" : : "r"(MAIR1_VALUE));
    __asm__ volatile("isb");

    program_region(0U,
                   (unsigned long)(unsigned char *)zx_guest_mailbox,
                   ((unsigned long)(unsigned char *)zx_guest_mailbox
                        + ZX_GD_WINDOW_SIZE) - 1UL,
                   EL1_AP_PRIV_RW, 1UL, ATTR_NORMAL_WB);

    program_region(1U,
                   (unsigned long)(unsigned char *)__zx_guest_code_start,
                   (unsigned long)(unsigned char *)__zx_guest_code_end - 1UL,
                   EL1_AP_PRIV_RO, 0UL, ATTR_NORMAL_WB);

    program_region(2U,
                   (unsigned long)(unsigned char *)__zx_guest_data_start,
                   (unsigned long)(unsigned char *)__zx_guest_window_end - 1UL,
                   EL1_AP_PRIV_RW, 1UL, ATTR_NORMAL_WB);

    /* Every region the implementation has but this guest does not use is
       DISABLED explicitly.  Their bases and limits are UNKNOWN out of reset,
       and an enabled region with an unknown base can overlap one of the
       three above -- which is the CONSTRAINED UNPREDICTABLE case again, and
       it would present as a guest that faults on its own memory.  */

    for (index = guest_mpu_regions_used; index < available; index++)
    {
        unsigned long zero = 0UL;

        __asm__ volatile("mcr p15, 0, %0, c6, c2, 1"
                         : : "r"((unsigned long)index));
        __asm__ volatile("isb");
        __asm__ volatile("mcr p15, 0, %0, c6, c3, 1" : : "r"(zero)); /* EN=0 */
        __asm__ volatile("isb");
    }

    __asm__ volatile("dsb" ::: "memory");

    /* M without BR: a miss faults.  Caches deliberately left alone -- see
       the note above.  */

    __asm__ volatile("mrc p15, 0, %0, c1, c0, 0" : "=r"(sctlr));
    sctlr |= SCTLR_M;
    sctlr &= ~SCTLR_BR;
    __asm__ volatile("mcr p15, 0, %0, c1, c0, 0" : : "r"(sctlr) : "memory");

    __asm__ volatile("dsb" ::: "memory");
    __asm__ volatile("isb" ::: "memory");

    return guest_mpu_regions_used;
}


/**************************************************************************/
/*                    THE PARTITION'S OWN CPU INTERFACE                   */
/*                                                                        */
/*  WHAT A PARTITION IS ALLOWED TO TOUCH, AND WHY IT IS SO LITTLE.         */
/*                                                                        */
/*  A GICv3 interrupt reaches a thread through three pieces of state, and  */
/*  they belong to three different owners:                                 */
/*                                                                        */
/*    the DISTRIBUTOR    one per system.  Decides which interrupts exist,  */
/*                       where they are routed, and at what priority.      */
/*    the REDISTRIBUTOR  one per CORE.  Holds the enable, group, priority  */
/*                       and edge/level bits for the 32 SGIs and PPIs of   */
/*                       that core -- INCLUDING every partition's, and     */
/*                       including the hypervisor's own.                   */
/*    the CPU INTERFACE  per exception level, and on this part it is       */
/*                       entirely SYSTEM REGISTERS.  Priority mask, group  */
/*                       enable, acknowledge, end-of-interrupt.            */
/*                                                                        */
/*  Only the third is a partition's.  The first two are memory-mapped and  */
/*  the hypervisor keeps them at ZX_AP_EL2_RW_GUEST_NONE, so this file     */
/*  could not reach them even if it tried -- and the reason is sharper     */
/*  than "they are shared".  The redistributor's SGI frame holds the       */
/*  enable bit for PPI 26, the hypervisor's OWN timer, which is what ends  */
/*  a partition's window.  A partition with a writable mapping of that     */
/*  frame could clear that bit and never be descheduled again.  That is    */
/*  not a memory-isolation leak; it is the temporal-determinism claim,     */
/*  gone, and no amount of stage-2 region programming would show it.       */
/*                                                                        */
/*  So the hypervisor enables this partition's timer PPI on its behalf,    */
/*  before the ERET, and the guest does the four system-register writes    */
/*  below.  Nothing here is a device access.                               */
/*                                                                        */
/*  ICC_SRE.SRE IS ALREADY SET.  ZoneX's reset path sets ICC_HSRE.SRE and  */
/*  ICC_HSRE.Enable, and the second of those is what makes an EL1 access   */
/*  to ICC_SRE legal rather than a trap to EL2.  Without SRE every other   */
/*  ICC_* register is UNDEFINED and reading one takes an undefined-        */
/*  instruction exception -- measured at EL2 during this work, and it      */
/*  would present at EL1 as a guest dying in its own board support.  It is */
/*  read-modify-written here anyway rather than assumed, because "somebody */
/*  else set it" is the kind of dependency that is true until a boot path  */
/*  is reordered.                                                          */
/**************************************************************************/

#define ICC_SRE_SRE             0x1UL
#define ICC_IGRPEN1_ENABLE      0x1UL
#define ICC_PMR_UNMASK_ALL      0xFFUL


static unsigned long read_icc_sre(void)
{
    unsigned long value;
    __asm__ volatile("mrc p15, 0, %0, c12, c12, 5" : "=r"(value));
    return value;
}


static unsigned long read_icc_iar1(void)
{
    unsigned long value;
    __asm__ volatile("mrc p15, 0, %0, c12, c12, 0" : "=r"(value));
    return value;
}


static void write_icc_eoir1(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c12, c12, 1" : : "r"(value) : "memory");
}


static void guest_interrupts_init(void)
{
    unsigned long sre = read_icc_sre() | ICC_SRE_SRE;

    __asm__ volatile("mcr p15, 0, %0, c12, c12, 5" : : "r"(sre) : "memory");
    __asm__ volatile("isb" ::: "memory");

    /* Priority mask wide open, no subpriority grouping, Group 1 enabled.
       The partition's interrupts are all Group 1 -- Group 0 is delivered as
       FIQ and this partition is granted none -- so IGRPEN0 is deliberately
       left alone rather than enabled "for symmetry": a group a partition has
       no interrupt in is a group it has no business enabling.  */

    __asm__ volatile("mcr p15, 0, %0, c4, c6, 0"
                     : : "r"(ICC_PMR_UNMASK_ALL) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c12, c12, 3" : : "r"(0UL) : "memory");
    __asm__ volatile("mcr p15, 0, %0, c12, c12, 7"
                     : : "r"(ICC_IGRPEN1_ENABLE) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


/**************************************************************************/
/*                      THE PARTITION'S OWN CLOCK                         */
/*                                                                        */
/*  CNTV, not CNTP, and the difference is the whole of temporal            */
/*  partitioning.  The physical counter keeps running while a partition is */
/*  descheduled, so a guest reading it could observe that it was not       */
/*  running.  The virtual counter is the physical one minus CNTVOFF, and   */
/*  CNTVOFF is the hypervisor's: it advances it by exactly the time the    */
/*  partition spent off the core, so from inside, time simply did not pass */
/*  while the partition was not running.  See docs/decisions.md D7.        */
/*                                                                        */
/*  The guest needs no permission for any of this.  EL1 access to the      */
/*  virtual timer is not gated by anything -- it is the PHYSICAL one that  */
/*  CNTHCTL.PL1PCTEN and PL1PCEN gate, and ZoneX leaves both CLEAR, so a   */
/*  partition that tried CNTP would trap to EL2 rather than get an answer. */
/*                                                                        */
/*  TVAL AND NOT CVAL, deliberately.  TVAL is a 32-bit down-count loaded   */
/*  relative to now, so re-arming is one register write with no 64-bit     */
/*  arithmetic and no read of the counter -- which matters because the     */
/*  re-arm happens inside the interrupt handler on every tick.  Writing    */
/*  TVAL is also what deasserts the timer's LEVEL output; a handler that   */
/*  acknowledged the interrupt without re-arming would take it again the   */
/*  instant interrupts were re-enabled, for ever.                          */
/**************************************************************************/

#define CNTV_CTL_ENABLE         0x1UL
#define CNTV_CTL_IMASK          0x2UL

static unsigned long guest_tick_interval;


unsigned long guest_counter_frequency(void)
{
    unsigned long value;
    __asm__ volatile("mrc p15, 0, %0, c14, c0, 0" : "=r"(value));
    return value;
}


unsigned long guest_virtual_count(void)
{
    unsigned long low;
    unsigned long high;

    /* CNTVCT is 64-bit and comes back as a register pair.  Only the low
       half is returned: this is used to answer "is the counter moving at
       all", and a 32-bit answer at 8 MHz wraps in nine minutes, which is
       three orders of magnitude longer than the question needs.  */

    __asm__ volatile("mrrc p15, 1, %0, %1, c14" : "=r"(low), "=r"(high));
    (void) high;

    return low;
}


void guest_tick_reload(void)
{
    __asm__ volatile("mcr p15, 0, %0, c14, c3, 0"
                     : : "r"(guest_tick_interval) : "memory");
}


/**************************************************************************/
/*  guest_counter_is_moving                                               */
/*                                                                        */
/*  THE PRE-FLIGHT THAT EXISTS BECAUSE THE ALTERNATIVE IS A HANG.          */
/*                                                                        */
/*  Programming CNTFRQ does not start the system counter, and on the       */
/*  Armv8-R AEM FVP the counter is left STOPPED at reset -- the model      */
/*  documents that firmware is expected to start it.  A guest that armed   */
/*  its timer and went straight to tx_thread_sleep on a target whose       */
/*  counter never started would wait for ever, and the run would end in a  */
/*  harness timeout: the one failure mode that names nothing at all and    */
/*  looks identical to a broken loader, a broken context switch and a      */
/*  broken GIC.                                                            */
/*                                                                        */
/*  So the guest reads its own counter twice before it blocks on anything. */
/*  The bound is what makes this a check rather than a second hang.  A     */
/*  counter that is running advances on the first spin at either target's  */
/*  frequency; one that is stopped never will, and the guest reports that  */
/*  and hands the machine back.                                            */
/*                                                                        */
/*  The hypervisor checks the same thing before it hands over, and both    */
/*  checks are worth having: ZoneX's says the counter it STARTED is        */
/*  running, and this one says the counter the PARTITION can see is --     */
/*  which is a different register, reached through CNTVOFF.                */
/**************************************************************************/

unsigned int guest_counter_is_moving(void)
{
    unsigned long first = guest_virtual_count();
    unsigned long guard;

    for (guard = 0UL; guard < 100000UL; guard++)
    {
        if (guest_virtual_count() != first)
        {
            return 1U;
        }
    }

    return 0U;
}


/**************************************************************************/
/*  board_init -- called by the port's _tx_initialize_low_level.          */
/*                                                                        */
/*  The port calls this because the guest is built with                    */
/*  TX_R52_USE_THREADX_IRQ, which is also what routes the port's EL1 IRQ   */
/*  vector into _tx_thread_context_save.  It runs with interrupts still    */
/*  MASKED -- _tx_thread_schedule is what opens them -- so arming the      */
/*  timer here cannot deliver a tick before the kernel can service one.    */
/*                                                                        */
/*  WHETHER A PARTITION HAS A CLOCK AT ALL IS THE HYPERVISOR'S DECISION,   */
/*  and it arrives as a word in the mailbox rather than as a build option. */
/*  With ZX_GO_TICK clear this function touches nothing: no CPU interface, */
/*  no timer, no GIC.  That is what keeps a cooperative excursion of this  */
/*  image byte-for-byte the same program as before it had a tick, so the   */
/*  two are comparable -- and it means the run that demonstrates isolation */
/*  and the run that demonstrates preemption are the same binary.          */
/**************************************************************************/

void board_init(void)
{
    unsigned long frequency;

    if ((guest_mailbox_read(ZX_GD_OPTIONS) & (unsigned long) ZX_GO_TICK) == 0UL)
    {
        return;
    }

    guest_interrupts_init();

    /* CNTFRQ is a software-declared constant that the HYPERVISOR programmed:
       it is writable only at the highest implemented exception level and
       reads zero out of reset on both targets, so a guest booting at EL1
       cannot write it.  Dividing by it without checking would be a divide by
       zero on any target where ZoneX had not, which is why the guard is here
       rather than a comment saying it cannot happen.  */

    frequency = guest_counter_frequency();

    if (frequency == 0UL)
    {
        guest_tick_interval = 0UL;
        return;
    }

    guest_tick_interval = frequency / (unsigned long) TX_TIMER_TICKS_PER_SECOND;

    guest_tick_reload();

    __asm__ volatile("mcr p15, 0, %0, c14, c3, 1"
                     : : "r"(CNTV_CTL_ENABLE) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


/**************************************************************************/
/*  board_irq_handler -- the partition's whole interrupt service.          */
/*                                                                        */
/*  Called from the port's __tx_irq_processing_return, which means         */
/*  _tx_thread_context_save has already saved the interrupted context and  */
/*  interrupts are still masked.  It RETURNS -- the port branches to       */
/*  _tx_thread_context_restore afterwards, and that is what turns a tick   */
/*  into a thread switch.  An earlier version of this function yielded to  */
/*  the hypervisor instead, which was right while a partition had no       */
/*  interrupts and would now discard a thread's context on every tick.     */
/*                                                                        */
/*  THE ORDER IS THE WHOLE FUNCTION.                                       */
/*                                                                        */
/*    ACKNOWLEDGE FIRST.  Reading ICC_IAR1 raises the running priority to  */
/*    this interrupt's own, which masks it and everything of equal or      */
/*    lower priority.  Nothing else may happen before it.                  */
/*                                                                        */
/*    THE SPURIOUS INTID IS NOT AN INTERRUPT.  1023 means nothing was      */
/*    actually pending, and it must NOT be given an end-of-interrupt: the  */
/*    priority was never raised, so dropping it would corrupt the GIC's    */
/*    running-priority stack rather than merely be redundant.              */
/*                                                                        */
/*    RE-ARM BEFORE SERVICING.  Writing CNTV_TVAL restarts the down-count  */
/*    and DEASSERTS the timer's level output.  The generic timer asserts a */
/*    level, not an edge, so a handler that ended the interrupt without    */
/*    re-arming would be re-entered the instant interrupts reopened, and   */
/*    again, until the stack was gone.                                     */
/*                                                                        */
/*    _tx_timer_interrupt LAST, because it is the part that can change     */
/*    which thread runs next.                                             */
/*                                                                        */
/*  EVERY COUNTER HERE IS WRITTEN THROUGH THE MAILBOX rather than kept in  */
/*  a static and copied out later.  A handler that stashed its counts in   */
/*  .bss would lose all of them if the guest were taken by a fault, which  */
/*  is precisely the run whose interrupt history is worth having.          */
/**************************************************************************/

extern void _tx_timer_interrupt(void);

void board_irq_handler(void)
{
    unsigned long intid = read_icc_iar1() & 0xFFFFFFUL;

    if (intid == (unsigned long) ZX_GUEST_SPURIOUS_INTID)
    {
        return;
    }

    if (intid == (unsigned long) ZX_GUEST_TIMER_INTID)
    {
        guest_mailbox_write(ZX_GD_TIMER_INTID, intid);
        guest_mailbox_write(ZX_GD_IRQ_COUNT,
                            guest_mailbox_read(ZX_GD_IRQ_COUNT) + 1UL);

        guest_tick_reload();

        write_icc_eoir1(intid);

        _tx_timer_interrupt();

        return;
    }

    /* Something the hypervisor never granted this partition.  Recorded by
       INTID rather than as a flag, because "an interrupt arrived" sends a
       reader nowhere and "INTID 26 arrived" says the hypervisor's own timer
       was delivered to a guest.  ZX_GS_IRQ is set as well, so a run that
       reports nothing else still says an unexpected interrupt happened.  */

    guest_mailbox_write(ZX_GD_ODD_INTID, intid);
    guest_mailbox_write(ZX_GD_STAGE1,
                        guest_mailbox_read(ZX_GD_STAGE1) | ZX_GS_IRQ);

    write_icc_eoir1(intid);
}


/**************************************************************************/
/*  board_fiq_handler                                                     */
/*                                                                        */
/*  A partition is granted no Group 0 interrupt, so nothing can deliver an */
/*  FIQ to it: the guest never enables ICC_IGRPEN0, and the hypervisor     */
/*  puts its timer PPI in Group 1.  This exists because the port's board   */
/*  support references it, and an unresolved symbol would fail the LINK    */
/*  rather than the run.                                                   */
/*                                                                        */
/*  Reaching it anyway means an assumption above is wrong, so it records   */
/*  that and hands the machine back rather than returning into a context   */
/*  with no reason to be sound.  Yielding is right HERE and would be wrong */
/*  in the IRQ handler above, and the difference is that an IRQ is         */
/*  expected: an unexpected FIQ has no re-arm, no acknowledge and no       */
/*  handler behind it, so returning would leave it asserted and turn one   */
/*  interrupt into a storm.                                                */
/**************************************************************************/

void board_fiq_handler(void)
{
    guest_mailbox_write(ZX_GD_STAGE1,
                        guest_mailbox_read(ZX_GD_STAGE1) | ZX_GS_OTHER);
    guest_yield();
}


/**************************************************************************/
/*  guest_grant_probe_region                                              */
/*                                                                        */
/*  The containment test is done against the three regions this file       */
/*  programmed rather than by reading the MPU back, because what matters   */
/*  is whether an OVERLAP would be created and the three bases and limits  */
/*  are right here.  Reading them back would also work and would make the  */
/*  test depend on the register decode being right, which is a second      */
/*  thing to get wrong for no gain.                                        */
/**************************************************************************/

static unsigned int within(unsigned long address, const char *base,
                           const char *end)
{
    unsigned long low  = (unsigned long)(const unsigned char *)base;
    unsigned long high = (unsigned long)(const unsigned char *)end;

    return ((address >= low) && (address < high)) ? 1U : 0U;
}


unsigned int guest_grant_probe_region(unsigned long target)
{
    unsigned long granule_base = target & GRANULE_MASK;

    if (within(target, zx_guest_mailbox,
               &zx_guest_mailbox[ZX_GD_WINDOW_SIZE]) != 0U)
    {
        return 0U;
    }

    if (within(target, __zx_guest_code_start, __zx_guest_code_end) != 0U)
    {
        return 0U;
    }

    if (within(target, __zx_guest_data_start, __zx_guest_window_end) != 0U)
    {
        return 0U;
    }

    if (guest_mpu_region_count() <= guest_mpu_regions_used)
    {
        return 0U;
    }

    program_region(guest_mpu_regions_used, granule_base,
                   granule_base + 63UL,
                   EL1_AP_PRIV_RW, 1UL, ATTR_NORMAL_WB);

    guest_mpu_regions_used++;

    __asm__ volatile("dsb" ::: "memory");
    __asm__ volatile("isb" ::: "memory");

    return 1U;
}


/**************************************************************************/
/*  guest_vectors_install                                                 */
/*                                                                        */
/*  VBAR is per-guest state a guest owns, which is the point as much as    */
/*  the mechanism: the port's own EL1 vectors report through semihosting   */
/*  and then halt, which stops the model with no way for the hypervisor to */
/*  learn what happened.  A partition replaces them so that a stage-1      */
/*  fault becomes a message instead of a hang.                             */
/*                                                                        */
/*  A partition switch will have to save and restore this.                 */
/**************************************************************************/

void guest_vectors_install(void)
{
    unsigned long vbar = (unsigned long)(unsigned char *)zx_guest_vectors;

    __asm__ volatile("mcr p15, 0, %0, c12, c0, 0" : : "r"(vbar) : "memory");
    __asm__ volatile("isb" ::: "memory");
}


/**************************************************************************/
/*  console_putc -- one character, through the hypervisor.                */
/*                                                                        */
/*  The character is in r0 and the HVC immediate says what to do with it,  */
/*  which is why there is no function id to load: a console backend        */
/*  receives its character in r0 under AAPCS already, so this is the whole  */
/*  call.  An id in a register would cost two more instructions on the      */
/*  slowest path this guest has.                                           */
/**************************************************************************/

void console_set_quiet(unsigned int quiet)
{
    guest_console_quiet = quiet;
}


static void console_putc(char character)
{
    /* The register binding is not decoration: the hypervisor reads the
       character out of r0 specifically, so the compiler has to be told which
       register to put it in rather than left to choose.  */

    register unsigned long value __asm__("r0") = (unsigned long)
        (unsigned char)character;

    __asm__ volatile("hvc #" ZX_GUEST_STRINGIFY(ZX_HVC_GUEST_PUTC)
                     : "+r"(value)
                     :
                     : "memory");
}


/**************************************************************************/
/*  console_puts / console_puthex / console_putdec                        */
/*                                                                        */
/*  Deliberately the same three names the Cortex-R52 board support uses,   */
/*  so that a demo written against a standalone board builds unchanged     */
/*  inside a partition.  The BACKEND is what changed, and only the         */
/*  backend.                                                              */
/**************************************************************************/

void console_puts(const char *string_ptr)
{
    unsigned int index = 0U;

    if ((string_ptr == 0) || (guest_console_quiet != 0U))
    {
        return;
    }

    while (string_ptr[index] != '\0')
    {
        console_putc(string_ptr[index]);
        index++;
    }
}


void console_puthex(unsigned long value)
{
    static const char digits[] = "0123456789abcdef";
    unsigned int index;

    if (guest_console_quiet != 0U)
    {
        return;
    }

    console_putc('0');
    console_putc('x');

    for (index = 0U; index < 8U; index++)
    {
        unsigned int shift = (7U - index) * 4U;

        console_putc(digits[(value >> shift) & 0xFUL]);
    }
}


void console_putdec(unsigned long value)
{
    char buffer[11];
    unsigned int index = 0U;

    if (guest_console_quiet != 0U)
    {
        return;
    }

    if (value == 0UL)
    {
        console_putc('0');
        return;
    }

    while ((value != 0UL) && (index < 10U))
    {
        buffer[index] = (char)('0' + (char)(value % 10UL));
        value /= 10UL;
        index++;
    }

    while (index > 0U)
    {
        index--;
        console_putc(buffer[index]);
    }
}


/**************************************************************************/
/*  guest_yield                                                           */
/**************************************************************************/

void guest_yield(void)
{
    __asm__ volatile("dsb" ::: "memory");
    __asm__ volatile("hvc #" ZX_GUEST_STRINGIFY(ZX_HVC_GUEST_YIELD)
                     : : : "memory");
}


/**************************************************************************/
/*                              The mailbox                               */
/**************************************************************************/

static volatile unsigned long *mailbox_word(unsigned long offset)
{
    return (volatile unsigned long *)
        (void *)&zx_guest_mailbox[offset];
}


unsigned long guest_mailbox_read(unsigned long offset)
{
    return *mailbox_word(offset);
}


void guest_mailbox_write(unsigned long offset, unsigned long value)
{
    *mailbox_word(offset) = value;
}


/**************************************************************************/
/*  guest_report                                                          */
/*                                                                        */
/*  THE ORDER IS THE WHOLE FUNCTION.  Every reported field is written      */
/*  before the sequence, and the sequence before the checksum, so that a   */
/*  guest torn off mid-update -- descheduled, or faulted -- leaves a set   */
/*  of words that FAILS the checksum rather than one that is individually  */
/*  valid and jointly nonsense.  A reader that saw the new sequence with   */
/*  the old fields would have no way to know.                             */
/*                                                                        */
/*  The sentinel the hypervisor left in the mailbox is folded into the     */
/*  checksum, which is what makes a report read out of the WRONG           */
/*  partition's window detectable rather than merely unlucky.              */
/**************************************************************************/

void guest_report(unsigned long progress_bits)
{
    unsigned long sentinel = guest_mailbox_read(ZX_GD_SCRATCH);
    unsigned long progress = guest_mailbox_read(ZX_GD_PROGRESS) | progress_bits;
    unsigned long sequence = guest_mailbox_read(ZX_GD_SEQUENCE) + 1UL;
    unsigned long ticks    = guest_mailbox_read(ZX_GD_TICKS);
    unsigned long thread_a = guest_mailbox_read(ZX_GD_THREAD_A);
    unsigned long thread_b = guest_mailbox_read(ZX_GD_THREAD_B);
    unsigned long messages = guest_mailbox_read(ZX_GD_MESSAGES);
    unsigned long verdict  = guest_mailbox_read(ZX_GD_VERDICT);

    *mailbox_word(ZX_GD_PROGRESS) = progress;

    __asm__ volatile("dsb" ::: "memory");

    *mailbox_word(ZX_GD_SEQUENCE) = sequence;

    __asm__ volatile("dsb" ::: "memory");

    *mailbox_word(ZX_GD_CHECKSUM) =
        zx_guest_report_checksum(sentinel, progress, sequence, ticks,
                                 thread_a, thread_b, messages, verdict);

    __asm__ volatile("dsb" ::: "memory");
}
