#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Entry point for the ZoneX host unit-test target.
#
#   run.sh build    configure and build
#   run.sh test     build, then run through CTest
#   run.sh coverage build instrumented, test, and write a gcovr report
#
# scripts/build_host.sh and scripts/test_host.sh are thin wrappers over this,
# following the convention every Eclipse ThreadX repository uses, so that a
# contributor moving between them does not have to relearn where the entry
# point is.

set -euo pipefail

readonly ROOT="$(cd "$(dirname "$(realpath "$0")")/../.." && pwd)"
readonly BUILD="${ROOT}/build/host"

command="${1:-test}"

coverage=OFF
if [ "${command}" = "coverage" ]; then
    coverage=ON
fi

configure() {
    cmake -S "${ROOT}" -B "${BUILD}" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="${ROOT}/cmake/host.cmake" \
        -DCMAKE_BUILD_TYPE=Debug \
        -DZX_BUILD_HOST_TESTS=ON \
        -DZX_COVERAGE="${coverage}"
}

case "${command}" in
    build)
        configure
        cmake --build "${BUILD}"
        ;;
    test)
        configure
        cmake --build "${BUILD}"
        # --output-on-failure, because a host test reports what went wrong on
        # its own stdout and CTest hides that by default.  A summary line
        # saying "1 test failed" and nothing else is not a bug report.
        ctest --test-dir "${BUILD}" --output-on-failure
        ;;
    coverage)
        configure
        cmake --build "${BUILD}"
        ctest --test-dir "${BUILD}" --output-on-failure
        # Rooted at the repository so the report names files the way the
        # repository does.  gcovr writes its intermediate .gcov files into the
        # directory it is rooted at, so two of these must never run
        # concurrently from the same root -- they delete each other's output,
        # and the symptom is a SanityCheckError naming a file that "doesn't
        # exist but no error from GCOV detected".  ThreadX paid for that one.
        mkdir -p "${ROOT}/coverage_report"
        gcovr --root "${ROOT}" \
              --filter "${ROOT}/core/" \
              --filter "${ROOT}/common/" \
              --html-details "${ROOT}/coverage_report/index.html" \
              --xml "${ROOT}/coverage_report/coverage.xml" \
              --print-summary
        ;;
    *)
        echo "Usage: $0 [build|test|coverage]" >&2
        exit 1
        ;;
esac
