#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Entry point for the ZoneX host unit-test target.
#
#   run.sh build    configure and build
#   run.sh test     build, then run through CTest
#   run.sh coverage build instrumented, test, and write a gcovr report
#
# scripts/build_host.sh and scripts/test_host.sh are thin wrappers over this,
# following the convention every Eclipse ThreadX repository uses, so that a
# contributor moving between them does not have to relearn where the entry
# point is.

set -euo pipefail

readonly ROOT="$(cd "$(dirname "$(realpath "$0")")/../.." && pwd)"
readonly BUILD="${ROOT}/build/host"

command="${1:-test}"

coverage=OFF
if [ "${command}" = "coverage" ]; then
    coverage=ON
fi

configure() {
    cmake -S "${ROOT}" -B "${BUILD}" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="${ROOT}/cmake/host.cmake" \
        -DCMAKE_BUILD_TYPE=Debug \
        -DZX_BUILD_HOST_TESTS=ON \
        -DZX_COVERAGE="${coverage}"
}

case "${command}" in
    build)
        configure
        cmake --build "${BUILD}"
        ;;
    test)
        configure
        cmake --build "${BUILD}"
        # --output-on-failure, because a host test reports what went wrong on
        # its own stdout and CTest hides that by default.  A summary line
        # saying "1 test failed" and nothing else is not a bug report.
        ctest --test-dir "${BUILD}" --output-on-failure
        ;;
    coverage)
        configure
        cmake --build "${BUILD}"

        # DELETE THE COUNTERS FIRST, or the report is a lie.
        #
        # gcov ACCUMULATES: a .gcda file left from an earlier run is added to
        # by the next one, never replaced.  So a second coverage run over the
        # same build tree reports the union of both, and coverage can only
        # ever appear to go up.  A line whose only test was just deleted still
        # reads as covered, and the floor below cannot fail.
        #
        # This was measured, not feared: disabling one rule's tests and
        # re-running still reported 100%, and the floor passed.  CI never sees
        # it because every run starts from a fresh checkout, which is exactly
        # why it survives -- the machine that gets the wrong answer is the
        # contributor's, checking whether their own change dropped coverage.
        find "${BUILD}" -name '*.gcda' -delete

        ctest --test-dir "${BUILD}" --output-on-failure
        # Rooted at the repository so the report names files the way the
        # repository does.  gcovr writes its intermediate .gcov files into the
        # directory it is rooted at, so two of these must never run
        # concurrently from the same root -- they delete each other's output,
        # and the symptom is a SanityCheckError naming a file that "doesn't
        # exist but no error from GCOV detected".  ThreadX paid for that one.
        mkdir -p "${ROOT}/coverage_report"
        gcovr --root "${ROOT}" \
              --filter "${ROOT}/core/" \
              --filter "${ROOT}/common/" \
              --html-details "${ROOT}/coverage_report/index.html" \
              --xml "${ROOT}/coverage_report/coverage.xml" \
              --print-summary

        # THE FLOOR, and it is deliberately narrow.
        #
        # A repository-wide threshold cannot work here: much of core/ is only
        # true on the model or on silicon and the host suite cannot reach it,
        # which is why ZoneX does not hold the suite's usual figure over the
        # whole tree (docs/decisions.md D11).  A floor set to whatever the
        # tree happens to measure today would mean nothing either -- it says
        # "no worse than when somebody set it" and not one thing about the
        # code.
        #
        # So the floor is set where a real number is defensible: the manifest
        # validator, which is a pure function with no hardware in it and no
        # excuse for an unreached line.  100% is not aspirational -- it is
        # what it measures, on lines and on branches both.  A rule added
        # without a case that fails it will drop this and fail the build,
        # which is the entire point: a validator rule nothing has ever seen
        # reject anything is not a rule, it is a comment.
        #
        # Reported separately from the report above so that the number being
        # enforced is visible next to the failure, rather than the build
        # dying with a threshold the reader has to go and look up.
        echo ""
        echo "Enforcing the coverage floor on the manifest validator:"
        gcovr --root "${ROOT}" \
              --filter "${ROOT}/core/src/zx_manifest_verify.c" \
              --txt - \
              --fail-under-line 100 \
              --fail-under-branch 100
        ;;
    *)
        echo "Usage: $0 [build|test|coverage]" >&2
        exit 1
        ;;
esac
