/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    test_zx_fault_log.c                                  HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Covers core/src/zx_fault_log.c: the many-fault log the isolation    */
/*    matrix is judged from.                                              */
/*                                                                        */
/*    This file exists because the log's two most important properties     */
/*    are the ones a target run cannot demonstrate cheaply.                */
/*                                                                        */
/*      IT KEEPS THE FIRST ENTRIES AND NOT THE LAST.  Showing that on a   */
/*      board means provoking more than thirty-two faults and then        */
/*      arguing about which ones survived.  Here it is four lines.        */
/*                                                                        */
/*      A PREFETCH ABORT'S ADDRESS COMES FROM HIFAR AND A DATA ABORT'S    */
/*      FROM HDFAR.  Get that wrong and the whole matrix still passes on  */
/*      a target -- because HDFAR after a prefetch abort holds a STALE    */
/*      address from the previous data abort, and the previous data abort  */
/*      in the sweep was aimed at the same partition.  A plausible wrong  */
/*      answer, in other words, and exactly the class of defect a host    */
/*      test catches for nothing.                                         */
/*                                                                        */
/*    The register values are the ones measured on the two targets and    */
/*    already quoted in test_zx_fault.c, so a change to the decode has to */
/*    disagree with real hardware output rather than with an expectation. */
/*                                                                        */
/**************************************************************************/

#include "zx_fault_log.h"
#include "zx_console_capture.h"
#include "zx_test.h"

/* Measured on the Armv8-R AEM FVP, 2 September 2026, by the stage-2 probe:
   a guest violation is EC 0x24, DFSC 0x04 (a stage-2 MISS), on a write.  */

#define ZX_LOG_HSR_DABT_MISS_WRITE  0x93810044U

/* The same class with DFSC 0x0C, a stage-2 PERMISSION failure: a region DID
   cover the address and its AP refused.  That is the syndrome a read-only
   shared granule produces, and telling it from a miss is the difference
   between two distinct claims.  */

#define ZX_LOG_HSR_DABT_PERM_WRITE  0x9381004CU

/* And on a READ -- ISS[6], WnR, clear.  */

#define ZX_LOG_HSR_DABT_MISS_READ   0x93810004U

/* A prefetch abort routed to EL2: EC 0x20.  Its faulting address is in
   HIFAR and there is no DFSC to decode.  */

#define ZX_LOG_HSR_PABT_ROUTED      0x82000004U

/* A prefetch abort taken FROM Hyp: EC 0x21.  ZoneX faulting on its own
   instruction fetch, which must never be counted as a guest violation.  */

#define ZX_LOG_HSR_PABT_FROM_HYP    0x86000004U

/* A data abort taken FROM Hyp: EC 0x25.  Measured on the FVP.  */

#define ZX_LOG_HSR_DABT_FROM_HYP    0x9600004CU

#define ZX_PART_A                   0U
#define ZX_PART_B                   1U

static ZX_FAULT_LOG       zx_log;
static zx_fault_record_t  zx_record;


/**************************************************************************/
/*  zx_make -- one capture, built rather than measured.                   */
/**************************************************************************/

static void zx_make(uint32_t hsr, uint32_t hdfar, uint32_t hifar)
{
    zx_fault_record_reset(&zx_record);

    zx_record.zx_fault_vector = ZX_VECTOR_HYP_TRAP;
    zx_record.zx_fault_hsr    = hsr;
    zx_record.zx_fault_hdfar  = hdfar;
    zx_record.zx_fault_hifar  = hifar;
    zx_record.zx_fault_elr    = 0x02001234U;
    zx_record.zx_fault_spsr   = 0x000001D3U;
}


ZX_TEST_MAIN("zx_fault_log", {

    /* ---------------------------------------------------------------- */
    /*  Every entry point survives a null pointer.  A hypervisor that    */
    /*  crashed inside its own fault logger would replace a diagnosable  */
    /*  violation with an undiagnosable one.                             */
    /* ---------------------------------------------------------------- */

    zx_fault_log_reset((ZX_FAULT_LOG *)0);
    zx_make(ZX_LOG_HSR_DABT_MISS_WRITE, 0x02000000U, 0U);
    zx_fault_log_add((ZX_FAULT_LOG *)0, ZX_PART_A, &zx_record,
                     ZX_FAULT_RESUMED_SKIPPED);

    ZX_CHECK_EQ(zx_fault_log_entry_address((const ZX_FAULT_LOG_ENTRY *)0), 0U);
    ZX_CHECK(zx_fault_log_find((const ZX_FAULT_LOG *)0, ZX_PART_A, 0U)
             == (const ZX_FAULT_LOG_ENTRY *)0);
    ZX_CHECK_EQ(zx_fault_log_count_at((const ZX_FAULT_LOG *)0, ZX_PART_A, 0U),
                0U);
    ZX_CHECK_EQ(zx_fault_log_partition_total((const ZX_FAULT_LOG *)0,
                                             ZX_PART_A), 0U);
    ZX_CHECK_EQ(zx_fault_log_all_guest_violations((const ZX_FAULT_LOG *)0),
                0U);

    zx_capture_reset();
    zx_fault_log_report((const ZX_FAULT_LOG *)0);
    ZX_CHECK_EQ(zx_capture_contains("no fault log to report"), 1U);

    /* ---------------------------------------------------------------- */
    /*  A fresh log.                                                    */
    /* ---------------------------------------------------------------- */

    zx_fault_log_reset(&zx_log);

    ZX_CHECK_EQ(zx_log.zx_log_kept, 0U);
    ZX_CHECK_EQ(zx_log.zx_log_total, 0U);
    ZX_CHECK_EQ(zx_log.zx_log_dropped, 0U);
    ZX_CHECK_EQ(zx_log.zx_log_entries[0].zx_log_partition,
                (UINT)ZX_MANIFEST_NO_INDEX);

    /* AN EMPTY LOG IS NOT "all entries are guest violations".  That is
       vacuously true and it would pass on a run in which the entire matrix
       was skipped, which is the single most likely way a sweep goes
       wrong.  */

    ZX_CHECK_EQ(zx_fault_log_all_guest_violations(&zx_log), 0U);

    /* A null RECORD is refused too, and it must not move the totals: a
       counter bumped for a capture that carried nothing would report a
       fault nobody can look at.  */

    zx_fault_log_add(&zx_log, ZX_PART_A, (const zx_fault_record_t *)0,
                     ZX_FAULT_RESUMED_SKIPPED);
    ZX_CHECK_EQ(zx_log.zx_log_total, 0U);

    /* ---------------------------------------------------------------- */
    /*  Two directions, two addresses: the shape of the matrix.          */
    /* ---------------------------------------------------------------- */

    zx_make(ZX_LOG_HSR_DABT_MISS_READ, 0x02040100U, 0U);
    zx_fault_log_add(&zx_log, ZX_PART_A, &zx_record,
                     ZX_FAULT_RESUMED_SKIPPED);

    zx_make(ZX_LOG_HSR_DABT_MISS_WRITE, 0x02000100U, 0U);
    zx_fault_log_add(&zx_log, ZX_PART_B, &zx_record,
                     ZX_FAULT_RESUMED_SKIPPED);

    ZX_CHECK_EQ(zx_log.zx_log_kept, 2U);
    ZX_CHECK_EQ(zx_log.zx_log_total, 2U);
    ZX_CHECK_EQ(zx_fault_log_partition_total(&zx_log, ZX_PART_A), 1U);
    ZX_CHECK_EQ(zx_fault_log_partition_total(&zx_log, ZX_PART_B), 1U);
    ZX_CHECK_EQ(zx_fault_log_all_guest_violations(&zx_log), 1U);

    /* ATTRIBUTION IS BY PARTITION AND ADDRESS TOGETHER.  Each of the four
       combinations below is asked for, because a finder that matched on
       only one of the two would satisfy the two positive cases and would
       call the two negative ones hits -- and a matrix judged that way
       would pass with every case aimed in one direction.  */

    ZX_CHECK(zx_fault_log_find(&zx_log, ZX_PART_A, 0x02040100U)
             != (const ZX_FAULT_LOG_ENTRY *)0);
    ZX_CHECK(zx_fault_log_find(&zx_log, ZX_PART_B, 0x02000100U)
             != (const ZX_FAULT_LOG_ENTRY *)0);
    ZX_CHECK(zx_fault_log_find(&zx_log, ZX_PART_A, 0x02000100U)
             == (const ZX_FAULT_LOG_ENTRY *)0);
    ZX_CHECK(zx_fault_log_find(&zx_log, ZX_PART_B, 0x02040100U)
             == (const ZX_FAULT_LOG_ENTRY *)0);

    ZX_CHECK_EQ(zx_fault_log_count_at(&zx_log, ZX_PART_A, 0x02040100U), 1U);
    ZX_CHECK_EQ(zx_fault_log_count_at(&zx_log, ZX_PART_A, 0x02000100U), 0U);

    /* A CASE THAT FAULTED TWICE.  The count exists to catch it: a
       partition resumed onto the same instruction faults again, and that
       is a defect in the continue path rather than in isolation.  */

    zx_make(ZX_LOG_HSR_DABT_MISS_READ, 0x02040100U, 0U);
    zx_fault_log_add(&zx_log, ZX_PART_A, &zx_record,
                     ZX_FAULT_RESUMED_SKIPPED);
    ZX_CHECK_EQ(zx_fault_log_count_at(&zx_log, ZX_PART_A, 0x02040100U), 2U);

    /* ---------------------------------------------------------------- */
    /*  HIFAR, NOT HDFAR, FOR A PREFETCH ABORT.                          */
    /*                                                                  */
    /*  HDFAR is given a DIFFERENT, plausible value here on purpose. A   */
    /*  decode that read HDFAR would find that address instead and the   */
    /*  matrix would pass, because on a target HDFAR after a prefetch    */
    /*  abort holds whatever the sweep's previous data abort left in it. */
    /* ---------------------------------------------------------------- */

    zx_make(ZX_LOG_HSR_PABT_ROUTED, 0xDEADBEEFU, 0x02040080U);
    zx_fault_log_add(&zx_log, ZX_PART_A, &zx_record,
                     ZX_FAULT_RESUMED_REDIRECTED);

    ZX_CHECK(zx_fault_log_find(&zx_log, ZX_PART_A, 0x02040080U)
             != (const ZX_FAULT_LOG_ENTRY *)0);
    ZX_CHECK(zx_fault_log_find(&zx_log, ZX_PART_A, 0xDEADBEEFU)
             == (const ZX_FAULT_LOG_ENTRY *)0);

    /* And the same rule for a prefetch abort taken FROM Hyp, which is
       ZoneX's own bug rather than a guest's -- so the log must stop
       claiming every entry is a guest violation.  */

    zx_make(ZX_LOG_HSR_PABT_FROM_HYP, 0xDEADBEEFU, 0x00001234U);
    zx_fault_log_add(&zx_log, ZX_PART_A, &zx_record,
                     ZX_FAULT_RESUMED_STOPPED);

    ZX_CHECK(zx_fault_log_find(&zx_log, ZX_PART_A, 0x00001234U)
             != (const ZX_FAULT_LOG_ENTRY *)0);
    ZX_CHECK_EQ(zx_fault_log_all_guest_violations(&zx_log), 0U);

    /* ---------------------------------------------------------------- */
    /*  A fault nobody can place.  It counts, and it does not index.     */
    /* ---------------------------------------------------------------- */

    zx_fault_log_reset(&zx_log);
    zx_make(ZX_LOG_HSR_DABT_MISS_WRITE, 0x02000100U, 0U);
    zx_fault_log_add(&zx_log, (UINT)ZX_MANIFEST_NO_INDEX, &zx_record,
                     ZX_FAULT_RESUMED_STOPPED);

    ZX_CHECK_EQ(zx_log.zx_log_total, 1U);
    ZX_CHECK_EQ(zx_log.zx_log_kept, 1U);
    ZX_CHECK_EQ(zx_fault_log_partition_total(&zx_log, ZX_PART_A), 0U);
    ZX_CHECK_EQ(zx_fault_log_partition_total(&zx_log, ZX_MAX_PARTITIONS), 0U);

    /* ---------------------------------------------------------------- */
    /*  THE ARRAY FILLS AND THEN STOPS TAKING ENTRIES, while the totals  */
    /*  keep rising.  This is the property a ring buffer would not have  */
    /*  and the reason for choosing one over the other: the determinism  */
    /*  run's fault phase would otherwise evict the matrix.              */
    /* ---------------------------------------------------------------- */

    zx_fault_log_reset(&zx_log);

    {
        uint32_t index;

        /* The first entry names an address nothing later uses, so that
           finding it AFTER the flood is the assertion.  */

        zx_make(ZX_LOG_HSR_DABT_MISS_WRITE, 0x02040100U, 0U);
        zx_fault_log_add(&zx_log, ZX_PART_B, &zx_record,
                         ZX_FAULT_RESUMED_SKIPPED);

        for (index = 0U; index < (ZX_FAULT_LOG_ENTRIES * 4U); index++)
        {
            zx_make(ZX_LOG_HSR_DABT_MISS_WRITE, 0x02000200U, 0U);
            zx_fault_log_add(&zx_log, ZX_PART_B, &zx_record,
                             ZX_FAULT_RESUMED_SKIPPED);
        }
    }

    ZX_CHECK_EQ(zx_log.zx_log_kept, ZX_FAULT_LOG_ENTRIES);
    ZX_CHECK_EQ(zx_log.zx_log_total, (ZX_FAULT_LOG_ENTRIES * 4U) + 1U);
    ZX_CHECK_EQ(zx_log.zx_log_dropped,
                ((ZX_FAULT_LOG_ENTRIES * 4U) + 1U) - ZX_FAULT_LOG_ENTRIES);
    ZX_CHECK_EQ(zx_fault_log_partition_total(&zx_log, ZX_PART_B),
                (ZX_FAULT_LOG_ENTRIES * 4U) + 1U);

    /* The evidence recorded FIRST is still there, which is the whole
       point.  A ring buffer would have thrown it away.  */

    ZX_CHECK(zx_fault_log_find(&zx_log, ZX_PART_B, 0x02040100U)
             == &zx_log.zx_log_entries[0]);

    /* ---------------------------------------------------------------- */
    /*  The report.                                                     */
    /* ---------------------------------------------------------------- */

    zx_fault_log_reset(&zx_log);
    zx_capture_reset();
    zx_fault_log_report(&zx_log);

    ZX_CHECK_EQ(zx_capture_contains("kept 0 of 0 total"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("The FIRST entries are kept"), 1U);

    zx_make(ZX_LOG_HSR_DABT_MISS_WRITE, 0x02040100U, 0U);
    zx_fault_log_add(&zx_log, ZX_PART_B, &zx_record,
                     ZX_FAULT_RESUMED_SKIPPED);
    zx_make(ZX_LOG_HSR_DABT_PERM_WRITE, 0x02080000U, 0U);
    zx_fault_log_add(&zx_log, ZX_PART_B, &zx_record,
                     ZX_FAULT_RESUMED_SKIPPED);
    zx_make(ZX_LOG_HSR_DABT_MISS_READ, 0x02000100U, 0U);
    zx_fault_log_add(&zx_log, ZX_PART_A, &zx_record,
                     ZX_FAULT_RESUMED_STOPPED);
    zx_make(ZX_LOG_HSR_PABT_ROUTED, 0U, 0x02040080U);
    zx_fault_log_add(&zx_log, ZX_PART_A, &zx_record,
                     ZX_FAULT_RESUMED_REDIRECTED);
    zx_make(ZX_LOG_HSR_DABT_FROM_HYP, 0x00006940U, 0U);
    zx_fault_log_add(&zx_log, ZX_PART_A, &zx_record, 0xFFU);

    zx_capture_reset();
    zx_fault_log_report(&zx_log);

    /* THE TWO DFSC VALUES MUST READ DIFFERENTLY IN THE LOG.  A report that
       called a permission failure and a region miss the same thing would
       make case 8's two halves indistinguishable, which is the one place
       the difference carries the whole claim.  */

    ZX_CHECK_EQ(zx_capture_contains("no enabled region covered it"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("its AP refused"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("on a WRITE"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("on a READ"), 1U);

    /* Every resume disposition has a name, including one this build has no
       name for -- a log entry reading as a blank is worse than one reading
       as an admission.  */

    ZX_CHECK_EQ(zx_capture_contains("STOPPED (the shipping policy)"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("past the faulting instruction"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("the address the guest named"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("does not have a name for"), 1U);

    ZX_CHECK_EQ(zx_capture_contains("partition 0 faulted 3 times"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("partition 1 faulted 2 times"), 1U);

    /* A prefetch abort has no DFSC line of its own, and the address it
       reports is HIFAR's.  */

    ZX_CHECK_EQ(zx_capture_contains("prefetch abort"), 1U);
    ZX_CHECK_EQ(zx_capture_overflowed(), 0U);
})
