/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    test_zx_partition.c                                  HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The partition manager: where an image is decided to go, and what    */
/*    state a partition ends up in.                                       */
/*                                                                        */
/*    Two things here are worth more than the rest.                       */
/*                                                                        */
/*    The load record is asserted AFTER A FAILURE as well as after a      */
/*    success.  The whole reason the record is filled in before the       */
/*    search that can fail is so that a failure leaves a description of   */
/*    what was attempted; a test that only checked the success path would */
/*    let that ordering be reversed by anyone tidying the function, and   */
/*    the cost would land on whoever next read a boot log full of zeros.  */
/*                                                                        */
/*    The outcome classification is driven from SYNDROME VALUES rather    */
/*    than from a caller's opinion, so each case here spells an HSR the   */
/*    hardware would really produce.  A yield and a stage-2 violation     */
/*    must not be able to become each other, and a fault taken from Hyp   */
/*    mode -- a ZoneX bug -- must not be counted as a partition           */
/*    overstepping its boundary: that would let a hypervisor defect read  */
/*    as the demonstrator working.                                        */
/*                                                                        */
/**************************************************************************/

#include "zx_partition.h"
#include "zx_console_capture.h"
#include "zx_test.h"

/* Syndromes as the hardware presents them: HSR.EC is bits [31:26].  */

#define HSR_OF(ec)              ((uint32_t)(ec) << 26U)

#define WINDOW_BASE             0x00100000U
#define WINDOW_LIMIT            0x0011FFFFU     /* 128 KB, inclusive        */
#define DATA_BASE               0x00200000U
#define DATA_LIMIT              0x0020FFFFU
#define TINY_BASE               0x00300000U
#define TINY_LIMIT              0x0030003FU     /* one granule             */

#define IMAGE_START             0x80000000U
#define IMAGE_END               0x80008000U     /* 32 KB                    */

static ZX_REGION        regions[4];
static ZX_PARTITION     declaration;
static ZX_PARTITION_CB  cb;

static void set_region(ZX_REGION *region_ptr, zx_addr_t base, zx_addr_t limit,
                       UCHAR xn)
{
    region_ptr->zx_region_base       = base;
    region_ptr->zx_region_limit      = limit;
    region_ptr->zx_region_ap         = ZX_AP_EL2_RW_GUEST_RW;
    region_ptr->zx_region_xn         = xn;
    region_ptr->zx_region_sh         = ZX_SH_NON_SHAREABLE;
    region_ptr->zx_region_attr_index = 0U;
}

/* The known-good partition, rebuilt before every case.  Region 0 is
   deliberately NOT the code window: the loader has to SEARCH for the region
   holding the entry, and a table whose first region is the answer would let
   a loader that ignored the entry point pass every case here.  */
static void reset_declaration(void)
{
    set_region(&regions[0], DATA_BASE, DATA_LIMIT, ZX_XN_NEVER);
    set_region(&regions[1], TINY_BASE, TINY_LIMIT, ZX_XN_EXECUTABLE);
    set_region(&regions[2], WINDOW_BASE, WINDOW_LIMIT, ZX_XN_EXECUTABLE);

    declaration.zx_partition_id           = 3U;
    declaration.zx_partition_name         = "guest A";
    declaration.zx_partition_image_start  = IMAGE_START;
    declaration.zx_partition_image_end    = IMAGE_END;
    declaration.zx_partition_entry        = WINDOW_BASE;
    declaration.zx_partition_regions      = regions;
    declaration.zx_partition_region_count = 3U;
    declaration.zx_partition_window_ticks = 5U;

    zx_partition_reset(&cb, &declaration);
}


static void test_reset(void)
{
    reset_declaration();

    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_DECLARED);
    ZX_CHECK_EQ(cb.zx_partition_entries, 0U);
    ZX_CHECK_EQ(cb.zx_partition_faults, 0U);

    /* Not zero.  Zero is a valid region index, so a zeroed field would be
       indistinguishable from "the window is this partition's region 0" --
       the same ambiguity ZX_MANIFEST_NO_INDEX exists to remove.  */
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_region_index,
                ZX_MANIFEST_NO_INDEX);

    /* A null control block must be survivable: this is called from a boot
       path with no allocator and no way to report.  */
    zx_partition_reset((ZX_PARTITION_CB *)0, &declaration);
}


static void test_prepare_locates_the_window(void)
{
    reset_declaration();

    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_PREPARED);

    /* Region 2, not region 1.  Region 1 is executable and comes first, and a
       loader that stopped at the first executable region would load the
       image into a 64-byte window and report success.  */
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_region_index, 2U);
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_window_base,
                (zx_addr_t)WINDOW_BASE);
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_window_limit,
                (zx_addr_t)WINDOW_LIMIT);
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_image_source,
                (zx_addr_t)IMAGE_START);
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_image_length,
                (zx_size_t)(IMAGE_END - IMAGE_START));
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_entry, (zx_addr_t)WINDOW_BASE);

    /* An entry part-way into the window is normal -- a kernel's reset
       symbol is not at its window base unless something puts it there -- so
       the search must accept it and must still name the window's BASE as
       where the image goes.  */
    reset_declaration();
    declaration.zx_partition_entry = WINDOW_BASE + 0x40U;
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_window_base,
                (zx_addr_t)WINDOW_BASE);

    /* The last byte of the window is inside it.  An inclusive limit
       compared with the wrong operator rejects exactly this.  */
    reset_declaration();
    declaration.zx_partition_entry = WINDOW_LIMIT;
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_region_index, 2U);
}


static void test_prepare_refuses(void)
{
    /* Null everything.  Each of the three is a separate pointer a caller
       could get wrong, and none of them may be dereferenced.  */
    ZX_CHECK_EQ(zx_partition_prepare((ZX_PARTITION_CB *)0),
                ZX_MANIFEST_NULL_POINTER);

    reset_declaration();
    zx_partition_reset(&cb, (const ZX_PARTITION *)0);
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_NULL_POINTER);

    reset_declaration();
    declaration.zx_partition_regions = (const ZX_REGION *)0;
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_NULL_POINTER);

    /* A reversed image range.  */
    reset_declaration();
    declaration.zx_partition_image_end = IMAGE_START - 1U;
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_IMAGE_RANGE_INVALID);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_DECLARED);

    /* An EMPTY image: what a linker input pattern that matched nothing
       produces.  The loader would copy zero bytes and ERET into whatever
       the window held, and a NOLOAD window holds uninitialised memory.  */
    reset_declaration();
    declaration.zx_partition_image_end = IMAGE_START;
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_IMAGE_EMPTY);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_DECLARED);

    /* An entry in a region the partition owns, but not an executable one.  */
    reset_declaration();
    declaration.zx_partition_entry = DATA_BASE;
    ZX_CHECK_EQ(zx_partition_prepare(&cb),
                ZX_MANIFEST_ENTRY_NOT_EXECUTABLE);

    /* BELOW every executable region, and ABOVE every executable region.
       Both sides of the containment test need a case of their own, or one
       of the two comparisons is never seen to reject anything.  */
    reset_declaration();
    declaration.zx_partition_entry = TINY_BASE - 0x1000U;
    ZX_CHECK_EQ(zx_partition_prepare(&cb),
                ZX_MANIFEST_ENTRY_NOT_EXECUTABLE);

    reset_declaration();
    declaration.zx_partition_entry = WINDOW_LIMIT + 1U;
    ZX_CHECK_EQ(zx_partition_prepare(&cb),
                ZX_MANIFEST_ENTRY_NOT_EXECUTABLE);

    /* THE RECORD AFTER A FAILURE.  This is the assertion the ordering of
       zx_partition_prepare exists for: the fields derivable from the
       manifest are there, describing what was attempted, and only the
       window -- which is what could not be worked out -- is absent.  */
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_image_source,
                (zx_addr_t)IMAGE_START);
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_image_length,
                (zx_size_t)(IMAGE_END - IMAGE_START));
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_entry,
                (zx_addr_t)(WINDOW_LIMIT + 1U));

    /* An image too large for the window the ENTRY is in, while fitting the
       other executable region -- which here is the smaller one, so the
       geometry is the reverse of the manifest validator's case and catches
       a loader that measured the wrong region.  */
    reset_declaration();
    declaration.zx_partition_entry     = TINY_BASE;
    declaration.zx_partition_image_end = IMAGE_START + 0x100U;
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_IMAGE_TOO_LARGE);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_DECLARED);

    /* And the window named in the record is the one that was too small,
       which is what a reader needs in order to fix it.  */
    ZX_CHECK_EQ(cb.zx_partition_load.zx_load_window_base,
                (zx_addr_t)TINY_BASE);
}


static void test_image_exactly_fills_the_window(void)
{
    /* The boundary the inclusive limit makes easy to get wrong: a window of
       64 bytes holds an image of exactly 64 bytes and not one of 65.  Both
       cases, because an off-by-one here is a copy that overruns the window
       by a byte -- into the next partition, which is the failure the whole
       component exists to prevent.  */

    reset_declaration();
    declaration.zx_partition_entry     = TINY_BASE;
    declaration.zx_partition_image_end = IMAGE_START + ZX_MPU_GRANULE;
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);

    reset_declaration();
    declaration.zx_partition_entry     = TINY_BASE;
    declaration.zx_partition_image_end = IMAGE_START + ZX_MPU_GRANULE + 1U;
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_IMAGE_TOO_LARGE);
}


static void test_lifecycle(void)
{
    zx_fault_record_t record;

    /* Nothing may be entered before it is loaded.  */
    reset_declaration();
    ZX_CHECK_EQ(zx_partition_enter(&cb), 0U);

    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    ZX_CHECK_EQ(zx_partition_enter(&cb), 0U);

    zx_partition_loaded(&cb);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_LOADED);

    ZX_CHECK_EQ(zx_partition_enter(&cb), 1U);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_RUNNING);
    ZX_CHECK_EQ(cb.zx_partition_entries, 1U);

    /* A yield: HSR.EC = 0x12, an HVC.  */
    record.zx_fault_captures     = 1U;
    record.zx_fault_vector       = ZX_VECTOR_HYP_TRAP;
    record.zx_fault_hsr          = HSR_OF(ZX_EC_HVC) | 1U;
    record.zx_fault_hpfar        = 0U;
    record.zx_fault_hdfar        = 0U;
    record.zx_fault_hifar        = 0U;
    record.zx_fault_elr          = WINDOW_BASE + 0x80U;
    record.zx_fault_spsr         = 0U;

    zx_partition_returned(&cb, &record);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_YIELDED);
    ZX_CHECK_EQ(cb.zx_partition_faults, 0U);
    ZX_CHECK_EQ(cb.zx_partition_last_guest_pc, WINDOW_BASE + 0x80U);

    /* A yielded partition may be entered again; that is what makes a time
       window a window rather than a single shot.  */
    ZX_CHECK_EQ(zx_partition_enter(&cb), 1U);
    ZX_CHECK_EQ(cb.zx_partition_entries, 2U);

    /* A stage-2 violation.  */
    record.zx_fault_hsr   = HSR_OF(ZX_EC_DABT_ROUTED);
    record.zx_fault_hdfar = DATA_BASE;
    zx_partition_returned(&cb, &record);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_FAULTED);
    ZX_CHECK_EQ(cb.zx_partition_faults, 1U);
    ZX_CHECK_EQ(cb.zx_partition_last_address, DATA_BASE);

    /* And a faulted partition is NOT re-entered.  Whatever it broke to get
       there is still broken.  */
    ZX_CHECK_EQ(zx_partition_enter(&cb), 0U);
    ZX_CHECK_EQ(cb.zx_partition_entries, 2U);

    /* zx_partition_loaded refuses to advance a partition that is not
       PREPARED, so a second call cannot move a faulted one back.  */
    zx_partition_loaded(&cb);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_FAULTED);
}


static void test_outcomes_are_not_conflated(void)
{
    zx_fault_record_t record;

    record.zx_fault_captures = 1U;
    record.zx_fault_vector   = ZX_VECTOR_DABT_HYP;
    record.zx_fault_hpfar    = 0U;
    record.zx_fault_hdfar    = 0U;
    record.zx_fault_hifar    = 0U;
    record.zx_fault_elr      = 0U;
    record.zx_fault_spsr     = 0U;

    /* A data abort taken FROM Hyp mode is a ZoneX bug.  It stops the
       partition, and it must NOT be counted as the partition overstepping:
       a run that reported a hypervisor defect as a boundary violation would
       pass while proving nothing.  */
    reset_declaration();
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    zx_partition_loaded(&cb);
    ZX_CHECK_EQ(zx_partition_enter(&cb), 1U);

    record.zx_fault_hsr = HSR_OF(ZX_EC_DABT_FROM_HYP);
    zx_partition_returned(&cb, &record);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_STOPPED);
    ZX_CHECK_EQ(cb.zx_partition_faults, 0U);

    /* Something nobody expected -- here a trapped WFI.  Also STOPPED, also
       not a fault.  */
    reset_declaration();
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    zx_partition_loaded(&cb);
    ZX_CHECK_EQ(zx_partition_enter(&cb), 1U);

    record.zx_fault_hsr = HSR_OF(ZX_EC_WFI_WFE);
    zx_partition_returned(&cb, &record);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_STOPPED);
    ZX_CHECK_EQ(cb.zx_partition_faults, 0U);

    /* A prefetch abort routed to Hyp IS a guest violation: a partition that
       tried to FETCH outside its window overstepped exactly as much as one
       that tried to read.  */
    reset_declaration();
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    zx_partition_loaded(&cb);
    ZX_CHECK_EQ(zx_partition_enter(&cb), 1U);

    record.zx_fault_hsr = HSR_OF(ZX_EC_PABT_ROUTED);
    zx_partition_returned(&cb, &record);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_FAULTED);
    ZX_CHECK_EQ(cb.zx_partition_faults, 1U);

    /* A return with NO syndrome.  Not a yield: nothing is known about why
       control came back, and calling it clean would invent the one fact the
       caller failed to supply.  */
    reset_declaration();
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    zx_partition_loaded(&cb);
    ZX_CHECK_EQ(zx_partition_enter(&cb), 1U);
    zx_partition_returned(&cb, (const zx_fault_record_t *)0);
    ZX_CHECK_EQ(cb.zx_partition_state, ZX_PARTITION_STOPPED);

    /* Null control blocks, on both of the run-time entry points.  */
    ZX_CHECK_EQ(zx_partition_enter((ZX_PARTITION_CB *)0), 0U);
    zx_partition_returned((ZX_PARTITION_CB *)0, &record);
    zx_partition_loaded((ZX_PARTITION_CB *)0);
}


static void test_state_names(void)
{
    /* Every state has a name, and the name says what the state MEANS rather
       than repeating its spelling: a log line reading "FAULTED" is only
       useful to somebody who already knows the difference between that and
       STOPPED.  */
    ZX_CHECK(zx_capture_contains("") != 0U);

    ZX_CHECK_EQ((int)(zx_partition_state_name(ZX_PARTITION_DECLARED)[0]),
                (int)'D');
    ZX_CHECK_EQ((int)(zx_partition_state_name(ZX_PARTITION_PREPARED)[0]),
                (int)'P');
    ZX_CHECK_EQ((int)(zx_partition_state_name(ZX_PARTITION_LOADED)[0]),
                (int)'L');
    ZX_CHECK_EQ((int)(zx_partition_state_name(ZX_PARTITION_RUNNING)[0]),
                (int)'R');
    ZX_CHECK_EQ((int)(zx_partition_state_name(ZX_PARTITION_YIELDED)[0]),
                (int)'Y');
    ZX_CHECK_EQ((int)(zx_partition_state_name(ZX_PARTITION_FAULTED)[0]),
                (int)'F');
    ZX_CHECK_EQ((int)(zx_partition_state_name(ZX_PARTITION_STOPPED)[0]),
                (int)'S');

    /* A state nobody defined.  Named as a ZoneX bug rather than reported as
       one of the legal ones, because a report that silently rounded an
       impossible value to a plausible one is worse than no report.  */
    zx_capture_reset();
    ZX_CHECK(zx_capture_contains("") != 0U);
    {
        const CHAR *name = zx_partition_state_name(99U);

        ZX_CHECK_EQ((int)(name[0]), (int)'a');
    }
}


static void test_report(void)
{
    /* A report with no control block at all says so.  It is called from a
       failure path, and a null pointer there must not become a second
       failure on top of the first.  */
    zx_capture_reset();
    zx_partition_report((const ZX_PARTITION_CB *)0);
    ZX_CHECK(zx_capture_contains("no partition control block") != 0U);

    /* The full report, after a load and a fault.  What a reader needs from
       it is the window, the entry, the guest PC and the two counters --
       every one of them is asserted, because this text is the only thing
       that turns a guest PC into a line in a map file.  */
    reset_declaration();
    ZX_CHECK_EQ(zx_partition_prepare(&cb), ZX_MANIFEST_SUCCESS);
    zx_partition_loaded(&cb);
    ZX_CHECK_EQ(zx_partition_enter(&cb), 1U);

    {
        zx_fault_record_t record;

        record.zx_fault_captures = 1U;
        record.zx_fault_vector   = ZX_VECTOR_HYP_TRAP;
        record.zx_fault_hsr      = HSR_OF(ZX_EC_DABT_ROUTED);
        record.zx_fault_hpfar    = 0U;
        record.zx_fault_hdfar    = DATA_BASE;
        record.zx_fault_hifar    = 0U;
        record.zx_fault_elr      = WINDOW_BASE + 0x1234U;
        record.zx_fault_spsr     = 0U;

        zx_partition_returned(&cb, &record);
    }

    zx_capture_reset();
    zx_partition_report(&cb);

    ZX_CHECK(zx_capture_contains("guest A") != 0U);
    ZX_CHECK(zx_capture_contains("FAULTED") != 0U);
    ZX_CHECK(zx_capture_contains("0x00100000") != 0U);   /* window base     */
    ZX_CHECK(zx_capture_contains("0x0011ffff") != 0U);   /* window limit    */
    ZX_CHECK(zx_capture_contains("0x00200000") != 0U);   /* HDFAR           */
    ZX_CHECK(zx_capture_contains("0x00101234") != 0U);   /* the guest PC    */
    ZX_CHECK(zx_capture_contains(".map") != 0U);
    ZX_CHECK_EQ(zx_capture_overflowed(), 0U);

    /* An unnamed partition.  A name is a convenience; the id is what the
       manifest and every region index are keyed on, so the report has to
       work without one.  */
    reset_declaration();
    declaration.zx_partition_name = (const CHAR *)0;
    zx_capture_reset();
    zx_partition_report(&cb);
    ZX_CHECK(zx_capture_contains("--- partition 3 ---") != 0U);

    /* A control block with no declaration behind it.  Reachable only
       through a caller error, and it says which caller error it is.  */
    zx_partition_reset(&cb, (const ZX_PARTITION *)0);
    zx_capture_reset();
    zx_partition_report(&cb);
    ZX_CHECK(zx_capture_contains("NO declaration") != 0U);

    /* And a partition that has never been entered prints no syndrome at
       all, rather than printing a zeroed one as though it meant something.  */
    ZX_CHECK(zx_capture_contains("last HSR") == 0U);
}

ZX_TEST_MAIN("test_zx_partition",
    test_reset();
    test_prepare_locates_the_window();
    test_prepare_refuses();
    test_image_exactly_fills_the_window();
    test_lifecycle();
    test_outcomes_are_not_conflated();
    test_state_names();
    test_report();
)
