/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    test_zx_manifest.c                                   HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The manifest validator, rule by rule.                               */
/*                                                                        */
/*    Shape: one known-good manifest, rebuilt from scratch before every   */
/*    case, and each case breaks exactly one thing.  That is what makes a */
/*    failure informative -- if a case fails, the rule it names is the    */
/*    rule that changed, because nothing else about the manifest did.     */
/*                                                                        */
/*    Every case asserts the reported INDICES as well as the status.  A   */
/*    validator that returns the right code about the wrong region is     */
/*    worse than one that returns nothing, because it sends the reader to */
/*    a line that is fine.                                                */
/*                                                                        */
/*    The arithmetic cases at the end matter as much as the rule cases.   */
/*    Adjacent regions that touch are legal and must not be rejected; a   */
/*    region ending at the top of the address space must not wrap; a      */
/*    region of exactly one granule is the smallest legal one and is the  */
/*    shape every shared range takes.  Those are the edges where an       */
/*    overlap test written with a subtraction gets the wrong answer.      */
/*                                                                        */
/**************************************************************************/

#include "zx_manifest.h"
#include "zx_test.h"

/* File scope, not inside ZX_TEST_MAIN.  A braced initialiser in the macro
   body is read as one argument per element -- see the note in zx_test.h.  */

#define P0_ID               1U
#define P1_ID               2U

#define P0_CODE_BASE        0x00100000U
#define P0_CODE_LIMIT       0x0010FFFFU
#define P0_DATA_BASE        0x00200000U
#define P0_DATA_LIMIT       0x0020FFFFU
#define P1_CODE_BASE        0x00400000U
#define P1_CODE_LIMIT       0x0040FFFFU
#define P1_DATA_BASE        0x00500000U
#define P1_DATA_LIMIT       0x0050FFFFU

#define SHARED_BASE         0x00300000U
#define SHARED_LIMIT        0x0030003FU

#define MMIO_BASE           0x42980000U
#define MMIO_LIMIT          0x4298003FU

#define IMAGE_START         0x80000000U
#define IMAGE_END           0x80001000U

#define ATTR_NORMAL         0U
#define ATTR_DEVICE         1U
#define ATTR_UNWRITTEN      5U

static ZX_REGION            p0_regions[ZX_MAX_REGIONS_PER_PARTITION];
static ZX_REGION            p1_regions[ZX_MAX_REGIONS_PER_PARTITION];
static ZX_REGION            mmio_regions[1];
static ZX_SHARED            shared_ranges[ZX_MAX_SHARED_RANGES];
static ZX_PARTITION         partitions[ZX_MAX_PARTITIONS];
static ZX_MANIFEST          manifest;
static ZX_MANIFEST_ENV      env;
static ZX_MANIFEST_FAULT    fault;

static void set_region(ZX_REGION *region_ptr, zx_addr_t base, zx_addr_t limit,
                       UCHAR ap, UCHAR xn, UCHAR attr)
{
    region_ptr->zx_region_base       = base;
    region_ptr->zx_region_limit      = limit;
    region_ptr->zx_region_ap         = ap;
    region_ptr->zx_region_xn         = xn;
    region_ptr->zx_region_sh         = ZX_SH_NON_SHAREABLE;
    region_ptr->zx_region_attr_index = attr;
}

/* The known-good system: two partitions, each with its own code and data,
   plus one read-only granule published by partition 0.  Rebuilt in full
   before every case so no case can leak into the next.  */
static void reset_manifest(void)
{
    set_region(&p0_regions[0], P0_CODE_BASE, P0_CODE_LIMIT,
               ZX_AP_EL2_RW_GUEST_RW, ZX_XN_EXECUTABLE, ATTR_NORMAL);
    set_region(&p0_regions[1], P0_DATA_BASE, P0_DATA_LIMIT,
               ZX_AP_EL2_RW_GUEST_RW, ZX_XN_NEVER, ATTR_NORMAL);
    set_region(&p0_regions[2], SHARED_BASE, SHARED_LIMIT,
               ZX_AP_EL2_RW_GUEST_RW, ZX_XN_NEVER, ATTR_NORMAL);

    set_region(&p1_regions[0], P1_CODE_BASE, P1_CODE_LIMIT,
               ZX_AP_EL2_RW_GUEST_RW, ZX_XN_EXECUTABLE, ATTR_NORMAL);
    set_region(&p1_regions[1], P1_DATA_BASE, P1_DATA_LIMIT,
               ZX_AP_EL2_RW_GUEST_RW, ZX_XN_NEVER, ATTR_NORMAL);
    set_region(&p1_regions[2], SHARED_BASE, SHARED_LIMIT,
               ZX_AP_EL2_RO_GUEST_RO, ZX_XN_NEVER, ATTR_NORMAL);

    set_region(&mmio_regions[0], MMIO_BASE, MMIO_LIMIT,
               ZX_AP_EL2_RW_GUEST_NONE, ZX_XN_NEVER, ATTR_DEVICE);

    shared_ranges[0].zx_shared_base         = SHARED_BASE;
    shared_ranges[0].zx_shared_limit        = SHARED_LIMIT;
    shared_ranges[0].zx_shared_publisher_id = P0_ID;

    partitions[0].zx_partition_id           = P0_ID;
    partitions[0].zx_partition_name         = "critical";
    partitions[0].zx_partition_image_start  = IMAGE_START;
    partitions[0].zx_partition_image_end    = IMAGE_END;
    partitions[0].zx_partition_entry        = P0_CODE_BASE;
    partitions[0].zx_partition_regions      = p0_regions;
    partitions[0].zx_partition_region_count = 3U;
    partitions[0].zx_partition_window_ticks = 7U;

    partitions[1].zx_partition_id           = P1_ID;
    partitions[1].zx_partition_name         = "best-effort";
    partitions[1].zx_partition_image_start  = IMAGE_START;
    partitions[1].zx_partition_image_end    = IMAGE_END;
    partitions[1].zx_partition_entry        = P1_CODE_BASE;
    partitions[1].zx_partition_regions      = p1_regions;
    partitions[1].zx_partition_region_count = 3U;
    partitions[1].zx_partition_window_ticks = 3U;

    manifest.zx_manifest_partitions         = partitions;
    manifest.zx_manifest_partition_count    = 2U;
    manifest.zx_manifest_shared             = shared_ranges;
    manifest.zx_manifest_shared_count       = 1U;
    manifest.zx_manifest_major_frame_ticks  = 10U;

    env.zx_env_mmio_regions      = mmio_regions;
    env.zx_env_mmio_region_count = 1U;
    /* Indices 0, 1 and 2 written; 3 upwards are not.  */
    env.zx_env_attr_written_mask = 0x07U;
    env.zx_env_region_budget     = 20U;
}

/* Every case is "reset, break one thing, expect this status here".  */
#define EXPECT(expected_status, expected_partition, expected_region)          \
    do {                                                                     \
        UINT actual = zx_manifest_verify(&manifest, &env, &fault);            \
        ZX_CHECK_EQ(actual, (expected_status));                               \
        ZX_CHECK_EQ(fault.zx_fault_status, (expected_status));                \
        ZX_CHECK_EQ(fault.zx_fault_partition, (UINT)(expected_partition));    \
        ZX_CHECK_EQ(fault.zx_fault_region, (UINT)(expected_region));          \
    } while (0)

#define EXPECT_STATUS(expected_status)                                        \
    do {                                                                      \
        UINT actual = zx_manifest_verify(&manifest, &env, &fault);            \
        ZX_CHECK_EQ(actual, (expected_status));                               \
    } while (0)

static void test_good_manifest(void)
{
    reset_manifest();
    EXPECT(ZX_MANIFEST_SUCCESS, ZX_MANIFEST_NO_INDEX, ZX_MANIFEST_NO_INDEX);

    /* And with no fault storage at all: a caller wanting only the status
       must not have to supply somewhere to put the rest.  */
    reset_manifest();
    ZX_CHECK_EQ(zx_manifest_verify(&manifest, &env, (ZX_MANIFEST_FAULT *)0),
                ZX_MANIFEST_SUCCESS);
}

static void test_null_pointers(void)
{
    reset_manifest();
    ZX_CHECK_EQ(zx_manifest_verify((const ZX_MANIFEST *)0, &env, &fault),
                ZX_MANIFEST_NULL_POINTER);

    reset_manifest();
    ZX_CHECK_EQ(zx_manifest_verify(&manifest, (const ZX_MANIFEST_ENV *)0,
                                   &fault),
                ZX_MANIFEST_NULL_POINTER);

    reset_manifest();
    manifest.zx_manifest_partitions = (const ZX_PARTITION *)0;
    EXPECT_STATUS(ZX_MANIFEST_NULL_POINTER);

    /* A shared count with no array, and an MMIO count with no array: both
       are caller bugs rather than empty lists, and both are reachable by
       forgetting to set one field of two.  */
    reset_manifest();
    manifest.zx_manifest_shared = (const ZX_SHARED *)0;
    EXPECT_STATUS(ZX_MANIFEST_NULL_POINTER);

    reset_manifest();
    env.zx_env_mmio_regions = (const ZX_REGION *)0;
    EXPECT_STATUS(ZX_MANIFEST_NULL_POINTER);

    reset_manifest();
    partitions[1].zx_partition_regions = (const ZX_REGION *)0;
    EXPECT(ZX_MANIFEST_NULL_POINTER, 1U, ZX_MANIFEST_NO_INDEX);
}

static void test_partition_structure(void)
{
    reset_manifest();
    manifest.zx_manifest_partition_count = 0U;
    EXPECT_STATUS(ZX_MANIFEST_NO_PARTITIONS);

    reset_manifest();
    manifest.zx_manifest_partition_count = ZX_MAX_PARTITIONS + 1U;
    EXPECT_STATUS(ZX_MANIFEST_TOO_MANY_PARTITIONS);

    reset_manifest();
    partitions[1].zx_partition_id = P0_ID;
    EXPECT(ZX_MANIFEST_DUPLICATE_ID, 0U, ZX_MANIFEST_NO_INDEX);

    reset_manifest();
    partitions[0].zx_partition_region_count = 0U;
    EXPECT(ZX_MANIFEST_NO_REGIONS, 0U, ZX_MANIFEST_NO_INDEX);

    reset_manifest();
    partitions[0].zx_partition_region_count =
        ZX_MAX_REGIONS_PER_PARTITION + 1U;
    EXPECT(ZX_MANIFEST_TOO_MANY_REGIONS, 0U, ZX_MANIFEST_NO_INDEX);
}

static void test_region_alignment(void)
{
    /* One byte past a granule boundary.  This is the bug that does not
       fault: the low bits land on SH, AP and XN.  */
    reset_manifest();
    p0_regions[1].zx_region_base = P0_DATA_BASE + 1U;
    EXPECT(ZX_MANIFEST_BASE_UNALIGNED, 0U, 1U);

    /* A limit that is not the last byte of a granule.  This one lands on
       AttrIndx and picks an unwritten MAIR byte.  */
    reset_manifest();
    p0_regions[1].zx_region_limit = P0_DATA_LIMIT - 1U;
    EXPECT(ZX_MANIFEST_LIMIT_UNALIGNED, 0U, 1U);

    /* Transposed endpoints, both correctly aligned for their own field, so
       that the alignment rules pass and the ordering rule is what fires.  */
    reset_manifest();
    p1_regions[1].zx_region_base  = P1_DATA_BASE;
    p1_regions[1].zx_region_limit = P0_DATA_BASE + (ZX_MPU_GRANULE - 1U);
    EXPECT(ZX_MANIFEST_LIMIT_BELOW_BASE, 1U, 1U);
}

static void test_region_attributes(void)
{
    reset_manifest();
    p0_regions[0].zx_region_ap = (UCHAR)(ZX_AP_EL2_RO_GUEST_RO + 1U);
    EXPECT(ZX_MANIFEST_BAD_AP, 0U, 0U);

    reset_manifest();
    p0_regions[0].zx_region_xn = (UCHAR)(ZX_XN_NEVER + 1U);
    EXPECT(ZX_MANIFEST_BAD_XN, 0U, 0U);

    /* SH 0b01 is UNPREDICTABLE for Normal memory, so it is rejected even
       though it is inside the field's range.  */
    reset_manifest();
    p0_regions[0].zx_region_sh = 0x01U;
    EXPECT(ZX_MANIFEST_BAD_SH, 0U, 0U);

    reset_manifest();
    p0_regions[0].zx_region_sh = (UCHAR)(ZX_SH_INNER_SHAREABLE + 1U);
    EXPECT(ZX_MANIFEST_BAD_SH, 0U, 0U);

    reset_manifest();
    p0_regions[0].zx_region_attr_index = (UCHAR)ZX_ATTR_INDEX_COUNT;
    EXPECT(ZX_MANIFEST_ATTR_OUT_OF_RANGE, 0U, 0U);

    /* In range, but the hypervisor never wrote that MAIR byte.  Nothing
       faults on this: the region gets Device-nGnRnE and works, slowly.  */
    reset_manifest();
    p0_regions[0].zx_region_attr_index = ATTR_UNWRITTEN;
    EXPECT(ZX_MANIFEST_ATTR_NOT_WRITTEN, 0U, 0U);
}

static void test_overlaps(void)
{
    /* Within one partition.  */
    reset_manifest();
    p0_regions[1].zx_region_base = P0_CODE_BASE;
    EXPECT(ZX_MANIFEST_SELF_OVERLAP, 0U, 0U);
    ZX_CHECK_EQ(fault.zx_fault_other_partition, 0U);
    ZX_CHECK_EQ(fault.zx_fault_other_region, 1U);

    /* Against the hypervisor's own MMIO, which stays enabled while a
       partition runs.  */
    reset_manifest();
    p1_regions[1].zx_region_base  = MMIO_BASE;
    p1_regions[1].zx_region_limit = MMIO_LIMIT;
    EXPECT(ZX_MANIFEST_MMIO_OVERLAP, 1U, 1U);
    ZX_CHECK_EQ(fault.zx_fault_other_region, 0U);

    /* Between two partitions: the isolation claim itself.  */
    reset_manifest();
    p1_regions[1].zx_region_base  = P0_DATA_BASE;
    p1_regions[1].zx_region_limit = P0_DATA_LIMIT;
    EXPECT(ZX_MANIFEST_PARTITION_OVERLAP, 0U, 1U);
    ZX_CHECK_EQ(fault.zx_fault_other_partition, 1U);
    ZX_CHECK_EQ(fault.zx_fault_other_region, 1U);

    /* A region that COVERS the shared granule but is not exactly it must
       still be rejected.  This is the case that would turn one published
       granule into a licence to overlap around it -- the shared exception
       is for an exact match and nothing else.  */
    reset_manifest();
    p1_regions[2].zx_region_base  = SHARED_BASE;
    p1_regions[2].zx_region_limit = SHARED_LIMIT + ZX_MPU_GRANULE;
    EXPECT_STATUS(ZX_MANIFEST_PARTITION_OVERLAP);

    /* And the mirror: partition 0's copy is not the declared range while
       partition 1's is, so the pair does not match one declaration.  */
    reset_manifest();
    p0_regions[2].zx_region_base  = SHARED_BASE - ZX_MPU_GRANULE;
    p0_regions[2].zx_region_limit = SHARED_LIMIT;
    p0_regions[2].zx_region_ap    = ZX_AP_EL2_RW_GUEST_RW;
    shared_ranges[0].zx_shared_publisher_id = P1_ID;
    p1_regions[2].zx_region_ap    = ZX_AP_EL2_RW_GUEST_RW;
    EXPECT_STATUS(ZX_MANIFEST_PARTITION_OVERLAP);
}

static void test_runnability(void)
{
    reset_manifest();
    p0_regions[0].zx_region_xn = ZX_XN_NEVER;
    EXPECT(ZX_MANIFEST_NO_EXECUTABLE_REGION, 0U, ZX_MANIFEST_NO_INDEX);

    reset_manifest();
    p1_regions[0].zx_region_ap = ZX_AP_EL2_RO_GUEST_RO;
    p1_regions[1].zx_region_ap = ZX_AP_EL2_RO_GUEST_RO;
    p1_regions[2].zx_region_ap = ZX_AP_EL2_RO_GUEST_RO;
    EXPECT(ZX_MANIFEST_NO_WRITABLE_REGION, 1U, ZX_MANIFEST_NO_INDEX);

    /* Four bytes outside the code region.  Invisible in a manifest, and it
       costs a hardware session to find without this rule.  */
    reset_manifest();
    partitions[0].zx_partition_entry = P0_CODE_LIMIT + 1U;
    EXPECT(ZX_MANIFEST_ENTRY_NOT_EXECUTABLE, 0U, ZX_MANIFEST_NO_INDEX);

    /* An entry inside a region the partition owns, but a NON-executable
       one.  The rule is about executable regions, not about any region.  */
    reset_manifest();
    partitions[0].zx_partition_entry = P0_DATA_BASE;
    EXPECT(ZX_MANIFEST_ENTRY_NOT_EXECUTABLE, 0U, ZX_MANIFEST_NO_INDEX);

    /* BELOW the code region, not above it.  Both sides of the containment
       test need a case: the two above are both at or past the base, so
       without this one the "entry >= base" comparison is never seen to be
       false and an entry pointing below a partition's code would be
       accepted by a rule nothing had exercised.  */
    reset_manifest();
    partitions[0].zx_partition_entry = P0_CODE_BASE - ZX_MPU_GRANULE;
    EXPECT(ZX_MANIFEST_ENTRY_NOT_EXECUTABLE, 0U, ZX_MANIFEST_NO_INDEX);

    reset_manifest();
    partitions[1].zx_partition_image_end = IMAGE_START - 1U;
    EXPECT(ZX_MANIFEST_IMAGE_RANGE_INVALID, 1U, ZX_MANIFEST_NO_INDEX);

    reset_manifest();
    partitions[1].zx_partition_image_end = IMAGE_START + 0x200000U;
    EXPECT(ZX_MANIFEST_IMAGE_TOO_LARGE, 1U, ZX_MANIFEST_NO_INDEX);
}

static void test_time_partitioning(void)
{
    reset_manifest();
    partitions[1].zx_partition_window_ticks = 0U;
    EXPECT(ZX_MANIFEST_ZERO_WINDOW, 1U, ZX_MANIFEST_NO_INDEX);

    /* The frame is carried AND checked, so that it can disagree.  */
    reset_manifest();
    manifest.zx_manifest_major_frame_ticks = 11U;
    EXPECT_STATUS(ZX_MANIFEST_FRAME_MISMATCH);
}

static void test_shared_ranges(void)
{
    reset_manifest();
    manifest.zx_manifest_shared_count = ZX_MAX_SHARED_RANGES + 1U;
    EXPECT_STATUS(ZX_MANIFEST_TOO_MANY_SHARED);

    reset_manifest();
    shared_ranges[0].zx_shared_base  = SHARED_BASE + 1U;
    p0_regions[2].zx_region_base     = SHARED_BASE + 1U;
    p1_regions[2].zx_region_base     = SHARED_BASE + 1U;
    EXPECT_STATUS(ZX_MANIFEST_BASE_UNALIGNED);

    /* Aligned, but larger than one granule.  Phase 0 bounds how much
       memory the isolation claim is qualified by, and enforces the bound
       rather than describing it.  */
    reset_manifest();
    shared_ranges[0].zx_shared_limit = SHARED_LIMIT + ZX_MPU_GRANULE;
    p0_regions[2].zx_region_limit    = SHARED_LIMIT + ZX_MPU_GRANULE;
    p1_regions[2].zx_region_limit    = SHARED_LIMIT + ZX_MPU_GRANULE;
    EXPECT_STATUS(ZX_MANIFEST_SHARED_NOT_ONE_GRANULE);

    /* An unaligned declaration that no region matches, so the per-region
       rules cannot fire first.  */
    reset_manifest();
    shared_ranges[0].zx_shared_base  = SHARED_BASE + 1U;
    shared_ranges[0].zx_shared_limit = SHARED_LIMIT + 1U;
    EXPECT_STATUS(ZX_MANIFEST_SHARED_NOT_ONE_GRANULE);

    /* Nobody publishes it: almost certainly a wrong publisher id, and the
       result is memory two partitions can read and nothing writes.  */
    reset_manifest();
    shared_ranges[0].zx_shared_publisher_id = 99U;
    p0_regions[2].zx_region_ap = ZX_AP_EL2_RO_GUEST_RO;
    EXPECT_STATUS(ZX_MANIFEST_SHARED_NO_PUBLISHER);

    /* The publisher cannot write what it publishes.  */
    reset_manifest();
    p0_regions[2].zx_region_ap = ZX_AP_EL2_RO_GUEST_RO;
    EXPECT(ZX_MANIFEST_SHARED_BAD_AP, 0U, 2U);

    /* A reader given write access.  The declaration says one-way and the
       regions say two-way, and nothing at run time would ever say so:
       both partitions would simply work.  */
    reset_manifest();
    p1_regions[2].zx_region_ap = ZX_AP_EL2_RW_GUEST_RW;
    EXPECT(ZX_MANIFEST_SHARED_BAD_AP, 1U, 2U);

    /* No sharing at all is a legal system, and the commonest one.  */
    reset_manifest();
    manifest.zx_manifest_shared_count       = 0U;
    partitions[0].zx_partition_region_count = 2U;
    partitions[1].zx_partition_region_count = 2U;
    EXPECT_STATUS(ZX_MANIFEST_SUCCESS);
}

static void test_region_budget(void)
{
    /* One region short of what the manifest needs: 1 MMIO + 3 + 3.  */
    reset_manifest();
    env.zx_env_region_budget = 6U;
    EXPECT_STATUS(ZX_MANIFEST_REGION_BUDGET);

    /* Exactly enough must pass.  An off-by-one here would either reject a
       manifest that fits or accept one that does not, and only one of
       those is visible on hardware.  */
    reset_manifest();
    env.zx_env_region_budget = 7U;
    EXPECT_STATUS(ZX_MANIFEST_SUCCESS);

    /* The hypervisor's own MMIO counts against the budget.  On the model
       it is zero regions and on silicon it is two, which is why this is
       checked against the register and not against a constant.  */
    reset_manifest();
    env.zx_env_mmio_region_count = 0U;
    env.zx_env_region_budget     = 6U;
    EXPECT_STATUS(ZX_MANIFEST_SUCCESS);
}

/**************************************************************************/
/*  The arithmetic.  These are the cases an overlap test written with a   */
/*  subtraction gets wrong, and they are all legal manifests.             */
/**************************************************************************/

static void test_overlap_arithmetic(void)
{
    /* Disjoint, in both argument orders.  */
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1000U, 0x103FU,
                                           0x2000U, 0x203FU), 0U);
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x2000U, 0x203FU,
                                           0x1000U, 0x103FU), 0U);

    /* Touching but not overlapping: a.limit + 1 == b.base.  This is how a
       partition's code and data windows sit next to each other, so a test
       that called it an overlap would reject every real manifest.  */
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1000U, 0x103FU,
                                           0x1040U, 0x107FU), 0U);
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1040U, 0x107FU,
                                           0x1000U, 0x103FU), 0U);

    /* Sharing exactly one byte, at each end.  */
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1000U, 0x1040U,
                                           0x1040U, 0x107FU), 1U);
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1040U, 0x107FU,
                                           0x1000U, 0x1040U), 1U);

    /* Identical, and fully nested both ways round.  */
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1000U, 0x103FU,
                                           0x1000U, 0x103FU), 1U);
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1000U, 0x1FFFU,
                                           0x1400U, 0x143FU), 1U);
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1400U, 0x143FU,
                                           0x1000U, 0x1FFFU), 1U);

    /* A single-byte range against itself, which is the degenerate case a
       length-based test divides by nothing on.  */
    ZX_CHECK_EQ(zx_manifest_ranges_overlap(0x1000U, 0x1000U,
                                           0x1000U, 0x1000U), 1U);

    /* The top of the address space.  A test computing (limit + 1) or
       (limit - base + 1) wraps to zero here and reports no overlap for two
       ranges that plainly do -- a hole in the isolation rules at the one
       address least likely to be tested.  Width-correct so this is the real
       top on a 32-bit target and on a 64-bit host alike.  */
    {
        const zx_addr_t top = ~(zx_addr_t)0;
        const zx_addr_t last_granule = top - (zx_addr_t)(ZX_MPU_GRANULE - 1U);

        ZX_CHECK_EQ(zx_manifest_ranges_overlap(last_granule, top,
                                               last_granule, top), 1U);
        ZX_CHECK_EQ(zx_manifest_ranges_overlap(last_granule, top,
                                               top, top), 1U);
        ZX_CHECK_EQ(zx_manifest_ranges_overlap(0U, 0x3FU,
                                               last_granule, top), 0U);
    }
}

static void test_region_edges(void)
{
    /* A region of exactly one granule is legal and is the shape every
       shared range takes.  */
    reset_manifest();
    p0_regions[1].zx_region_base  = P0_DATA_BASE;
    p0_regions[1].zx_region_limit = P0_DATA_BASE + (ZX_MPU_GRANULE - 1U);
    EXPECT_STATUS(ZX_MANIFEST_SUCCESS);

    /* Adjacent regions that touch: legal, and must not be rejected.  */
    reset_manifest();
    p0_regions[1].zx_region_base  = P0_CODE_LIMIT + 1U;
    p0_regions[1].zx_region_limit = P0_CODE_LIMIT + ZX_MPU_GRANULE;
    EXPECT_STATUS(ZX_MANIFEST_SUCCESS);

    /* A region ending at the very top of the address space.  The limit
       rule is written as "the low bits are all set" rather than "limit + 1
       is aligned" precisely so that this case is decided rather than
       arrived at by a wrap that happens to give the right answer.  */
    reset_manifest();
    p1_regions[1].zx_region_base  = ~(zx_addr_t)0
                                    - (zx_addr_t)(ZX_MPU_GRANULE - 1U);
    p1_regions[1].zx_region_limit = ~(zx_addr_t)0;
    EXPECT_STATUS(ZX_MANIFEST_SUCCESS);

    /* One partition, no sharing: the smallest legal system.  */
    reset_manifest();
    manifest.zx_manifest_partition_count    = 1U;
    manifest.zx_manifest_shared_count       = 0U;
    manifest.zx_manifest_major_frame_ticks  = 7U;
    partitions[0].zx_partition_region_count = 2U;
    EXPECT_STATUS(ZX_MANIFEST_SUCCESS);
}

ZX_TEST_MAIN("test_zx_manifest",
    test_good_manifest();
    test_null_pointers();
    test_partition_structure();
    test_region_alignment();
    test_region_attributes();
    test_overlaps();
    test_runnability();
    test_time_partitioning();
    test_shared_ranges();
    test_region_budget();
    test_overlap_arithmetic();
    test_region_edges();
)
