/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    test_zx_mm.c                                         HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The region-index layout and the HPRENR masks it produces.           */
/*                                                                        */
/*    Worth testing on a workstation to this depth for one reason: the    */
/*    masks decide, at run time, which memory a partition can reach.  A   */
/*    mask with one bit too many is a partition that can read its         */
/*    neighbour, and it does not fault, and it does not print anything.   */
/*    On hardware the symptom of a wrong mask is that everything works.   */
/*                                                                        */
/*    So the cases here assert the exact bit patterns, and then assert    */
/*    the property behind them -- that no two partitions' masks share a   */
/*    bit outside the always-on hypervisor block.  The bit patterns catch */
/*    an arithmetic slip; the property catches a redesign that is         */
/*    internally consistent and wrong.                                    */
/*                                                                        */
/**************************************************************************/

#include "zx_mm.h"
#include "zx_console_capture.h"
#include "zx_test.h"

static ZX_REGION    p_regions[ZX_MAX_PARTITIONS][ZX_MAX_REGIONS_PER_PARTITION];
static ZX_PARTITION partitions[ZX_MAX_PARTITIONS];
static ZX_MANIFEST  manifest;
static ZX_MM_LAYOUT layout;

/* Only the fields the planner reads.  A plan does not look at bases, limits
   or attributes -- it counts regions -- and a fixture that filled them in
   would suggest otherwise to the next reader.  */
static void reset_manifest(UINT partition_count, UINT regions_each)
{
    UINT index;

    for (index = 0U; index < ZX_MAX_PARTITIONS; index++)
    {
        partitions[index].zx_partition_id           = index + 1U;
        partitions[index].zx_partition_name         = "p";
        partitions[index].zx_partition_regions      = p_regions[index];
        partitions[index].zx_partition_region_count = regions_each;
        partitions[index].zx_partition_window_ticks = 1U;
    }

    manifest.zx_manifest_partitions        = partitions;
    manifest.zx_manifest_partition_count   = partition_count;
    manifest.zx_manifest_shared            = (const ZX_SHARED *)0;
    manifest.zx_manifest_shared_count      = 0U;
    manifest.zx_manifest_major_frame_ticks = partition_count;
}

static void test_plan_with_mmio(void)
{
    /* Two hypervisor MMIO regions -- the silicon case -- and two
       partitions of three regions each.  */
    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_SUCCESS);

    ZX_CHECK_EQ(layout.zx_layout_mmio_count, 2U);
    ZX_CHECK_EQ(layout.zx_layout_always_mask, 0x00000003U);

    /* Partition 0 owns 2, 3, 4 -- and can still reach the console.  */
    ZX_CHECK_EQ(layout.zx_layout_partition_first[0], 2U);
    ZX_CHECK_EQ(layout.zx_layout_partition_count[0], 3U);
    ZX_CHECK_EQ(layout.zx_layout_partition_mask[0], 0x0000001FU);

    /* Partition 1 owns 5, 6, 7.  */
    ZX_CHECK_EQ(layout.zx_layout_partition_first[1], 5U);
    ZX_CHECK_EQ(layout.zx_layout_partition_mask[1], 0x000000E3U);

    ZX_CHECK_EQ(layout.zx_layout_regions_used, 8U);
    ZX_CHECK_EQ(layout.zx_layout_partitions, 2U);
}

static void test_plan_without_mmio(void)
{
    /* Zero MMIO regions -- the model case.  Every partition's block shifts
       down, which is exactly why the layout is printed at boot: region 3
       is a different window on the two targets.  */
    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 0U, 32U, &layout),
                ZX_MANIFEST_SUCCESS);

    ZX_CHECK_EQ(layout.zx_layout_always_mask, 0U);
    ZX_CHECK_EQ(layout.zx_layout_partition_first[0], 0U);
    ZX_CHECK_EQ(layout.zx_layout_partition_mask[0], 0x00000007U);
    ZX_CHECK_EQ(layout.zx_layout_partition_first[1], 3U);
    ZX_CHECK_EQ(layout.zx_layout_partition_mask[1], 0x00000038U);
    ZX_CHECK_EQ(layout.zx_layout_regions_used, 6U);
}

static void test_masks_are_disjoint(void)
{
    UINT first;
    UINT second;

    /* The property, not the pattern.  Two partitions' masks may share only
       the always-on hypervisor bits; a bit shared anywhere else is a
       partition that can reach its neighbour's memory while it runs, which
       faults nothing and prints nothing.  */
    reset_manifest(ZX_MAX_PARTITIONS, 2U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 32U, &layout),
                ZX_MANIFEST_SUCCESS);

    for (first = 0U; first < layout.zx_layout_partitions; first++)
    {
        /* Every mask carries the always-on block.  A partition switch that
           dropped it would blind the hypervisor's own console, and the
           symptom would be a silent board.  */
        ZX_CHECK_EQ(layout.zx_layout_partition_mask[first]
                        & layout.zx_layout_always_mask,
                    layout.zx_layout_always_mask);

        for (second = first + 1U; second < layout.zx_layout_partitions;
             second++)
        {
            uint32_t shared = layout.zx_layout_partition_mask[first]
                              & layout.zx_layout_partition_mask[second];

            ZX_CHECK_EQ(shared, layout.zx_layout_always_mask);
        }
    }
}

static void test_plan_rejections(void)
{
    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan((const ZX_MANIFEST *)0, 2U, 20U, &layout),
                ZX_MANIFEST_NULL_POINTER);

    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, (ZX_MM_LAYOUT *)0),
                ZX_MANIFEST_NULL_POINTER);

    reset_manifest(2U, 3U);
    manifest.zx_manifest_partitions = (const ZX_PARTITION *)0;
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_NULL_POINTER);

    reset_manifest(0U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_NO_PARTITIONS);

    reset_manifest(ZX_MAX_PARTITIONS + 1U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_TOO_MANY_PARTITIONS);

    reset_manifest(2U, 0U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_NO_REGIONS);

    reset_manifest(2U, ZX_MAX_REGIONS_PER_PARTITION + 1U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_TOO_MANY_REGIONS);
}

static void test_budget(void)
{
    /* 2 MMIO + 3 + 3 = 8.  Exactly enough must pass and one short must not:
       an off-by-one either rejects a manifest that fits or programs a
       region at an index the part does not have, and only the first of
       those is visible without hardware.  */
    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 8U, &layout),
                ZX_MANIFEST_SUCCESS);

    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 7U, &layout),
                ZX_MANIFEST_REGION_BUDGET);

    /* The model's 32 EL2 regions are not an architecturally legal
       Cortex-R52 value, so a plan that fits the model can still be too big
       for silicon.  Same manifest, two budgets, two answers.  */
    reset_manifest(ZX_MAX_PARTITIONS, ZX_MAX_REGIONS_PER_PARTITION);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 32U, &layout),
                ZX_MANIFEST_SUCCESS);

    reset_manifest(ZX_MAX_PARTITIONS, ZX_MAX_REGIONS_PER_PARTITION);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_REGION_BUDGET);

    /* HPRENR has 32 bits, so an index with no enable bit is refused even
       when a caller claims a larger budget.  A region that cannot be
       enabled is a hole in the memory map with no diagnostic.  */
    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 33U, 64U, &layout),
                ZX_MANIFEST_REGION_BUDGET);

    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 30U, 64U, &layout),
                ZX_MANIFEST_REGION_BUDGET);
}

static void test_partition_mask_lookup(void)
{
    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_SUCCESS);

    ZX_CHECK_EQ(zx_mm_partition_mask(&layout, 0U), 0x0000001FU);
    ZX_CHECK_EQ(zx_mm_partition_mask(&layout, 1U), 0x000000E3U);

    /* Out of range and null both give zero, which disables every region.
       At EL0 and EL1 a miss faults regardless of HSCTLR.BR, so this stops
       the guest rather than leaving the previous partition's mask in
       force -- the failure that would be silent.  */
    ZX_CHECK_EQ(zx_mm_partition_mask(&layout, 2U), 0U);
    ZX_CHECK_EQ(zx_mm_partition_mask(&layout, ZX_MANIFEST_NO_INDEX), 0U);
    ZX_CHECK_EQ(zx_mm_partition_mask((const ZX_MM_LAYOUT *)0, 0U), 0U);
}

static void test_report(void)
{
    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_SUCCESS);

    zx_capture_reset();
    zx_mm_report(&layout, &manifest);

    /* The report has to name the indices, or a later fault naming region 7
       cannot be mapped back to a window.  */
    ZX_CHECK_EQ(zx_capture_contains("region layout"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("hypervisor MMIO"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("2..4"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("5..7"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("regions used"), 1U);

    /* On a board with none, say so rather than printing "0..-1".  */
    reset_manifest(2U, 3U);
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 0U, 20U, &layout),
                ZX_MANIFEST_SUCCESS);

    zx_capture_reset();
    zx_mm_report(&layout, &manifest);
    ZX_CHECK_EQ(zx_capture_contains("no hypervisor MMIO regions"), 1U);

    /* An unnamed partition must not print a null pointer.  */
    reset_manifest(2U, 3U);
    partitions[1].zx_partition_name = (const CHAR *)0;
    ZX_CHECK_EQ(zx_mm_plan(&manifest, 2U, 20U, &layout),
                ZX_MANIFEST_SUCCESS);

    zx_capture_reset();
    zx_mm_report(&layout, &manifest);
    ZX_CHECK_EQ(zx_capture_contains("(unnamed)"), 1U);

    /* And neither pointer may be trusted.  */
    zx_mm_report((const ZX_MM_LAYOUT *)0, &manifest);
    zx_mm_report(&layout, (const ZX_MANIFEST *)0);
}

ZX_TEST_MAIN("test_zx_mm",
    test_plan_with_mmio();
    test_plan_without_mmio();
    test_masks_are_disjoint();
    test_plan_rejections();
    test_budget();
    test_partition_mask_lookup();
    test_report();
)
