/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    test_zx_api.c                                        HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Covers what the repository foundation actually delivers: the        */
/*    contents of common/inc/zx_api.h.                                    */
/*                                                                        */
/*    Most of what matters about that header is checked at compile time   */
/*    rather than here -- a capability macro that expands to nothing      */
/*    usable, or a zx_addr_t of the wrong width, fails the build.  This   */
/*    file exists for the parts that do not: that the macros can be       */
/*    APPLIED to a real declaration, and that the granule constant means  */
/*    what the rest of ZoneX will assume it means.                        */
/*                                                                        */
/*    The suite grows when the manifest validator and the first           */
/*    substantial body of host-testable logic arrive.                     */
/*                                                                        */
/**************************************************************************/

#include "zx_api.h"
#include "zx_test.h"

/* The capability macros are exercised by being used, not by being inspected.
   ZX_NODISCARD in particular expands to a compiler attribute whose placement
   is only validated when it sits on a real declaration; a version of the block
   that compiled but produced an attribute the compiler silently ignored would
   pass any test that only checked the macro was defined.  */
ZX_NODISCARD static zx_addr_t zx_test_align_down_to_granule(zx_addr_t address);

static zx_addr_t zx_test_align_down_to_granule(zx_addr_t address)
{
    return address & ~(zx_addr_t)(ZX_MPU_GRANULE - 1U);
}

static void zx_test_unused_is_accepted(ZX_MAYBE_UNUSED int ignored)
{
}

ZX_TEST_MAIN("zx_api",
{
    /* The 64-byte granule is not a tunable.  PMSAv8-R lays HPRBAR out as
       BASE[31:6] with SH, AP and XN in the low bits, so a base that is not a
       multiple of 64 does not fault -- it silently rewrites the region's
       attributes.  If this constant is ever not 64, every mask in the port is
       wrong.  */
    ZX_CHECK_EQ(ZX_MPU_GRANULE, 64U);
    ZX_CHECK_EQ(ZX_MPU_GRANULE & (ZX_MPU_GRANULE - 1U), 0U);

    /* Alignment behaves as the region programming will need it to: an aligned
       base is left alone, and an under-aligned one is brought down rather
       than up.  Down, because a region must not start before the memory the
       manifest declared.  */
    ZX_CHECK_EQ(zx_test_align_down_to_granule((zx_addr_t)0x80000000U),
                (zx_addr_t)0x80000000U);
    ZX_CHECK_EQ(zx_test_align_down_to_granule((zx_addr_t)0x8000003FU),
                (zx_addr_t)0x80000000U);
    ZX_CHECK_EQ(zx_test_align_down_to_granule((zx_addr_t)0x80000040U),
                (zx_addr_t)0x80000040U);

    /* zx_addr_t and zx_size_t must be able to express a limit computed as
       base + size - 1 without wrapping for any region the manifest can
       describe.  The static assertions in zx_api.h cover the widths; this
       covers the arithmetic actually being unsigned.  */
    ZX_CHECK((zx_addr_t)0U - (zx_addr_t)1U > (zx_addr_t)0U);

    zx_test_unused_is_accepted(0);

    /* The version macros exist and are ordered as a pre-release: Phase 0 is
       deliberately 0.x, and something that bumped the major without meaning
       to should be visible here rather than only in a release note.  */
    ZX_CHECK_EQ(ZX_MAJOR_VERSION, 0);
})
