/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    test_zx_fault.c                                      HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Covers core/src/zx_fault.c: the HSR decode, the HPFAR arithmetic,   */
/*    and the text of the fault report.                                   */
/*                                                                        */
/*    This is the part of the trap path that CAN be tested without a      */
/*    model or a board, and it is worth testing there because the         */
/*    alternative is testing a fault decoder by provoking faults -- which */
/*    can only reach the cases the hardware happens to produce.  The      */
/*    cases that matter most are the ones nobody wants to provoke: a      */
/*    vector that disagrees with its syndrome, an HPFAR reporting an      */
/*    address above 4 GB, an exception class the TRM does not define.     */
/*                                                                        */
/*  WHERE THE REGISTER VALUES BELOW COME FROM                             */
/*                                                                        */
/*    The stage-2 syndromes are not invented.  They were MEASURED on the  */
/*    Armv8-R AEM FVP on 2 September 2026 by the stage-2 probe image, and */
/*    are quoted here so that a change to the decode has to disagree with */
/*    real hardware output rather than merely with an expectation:        */
/*                                                                        */
/*      guest violation   HSR 0x93810044  HDFAR 0x000065C0  HPFAR 0x60    */
/*                        vector +0x14, EC 0x24, DFSC 0x04, on a write    */
/*      hypervisor fault  HSR 0x9600004C  HDFAR 0x00006940  HPFAR 0x00    */
/*                        vector +0x10, EC 0x25, DFSC 0x0C, on a write    */
/*                                                                        */
/*    The DFSC pair is itself a finding: 0x04 is what a stage-2 MISS       */
/*    reports and 0x0C what a stage-2 PERMISSION failure reports.         */
/*                                                                        */
/**************************************************************************/

#include "zx_fault.h"
#include "zx_console_capture.h"
#include "zx_test.h"

/* Measured on the FVP, 2 September 2026 -- see the header.  */

#define ZX_MEASURED_GUEST_HSR       0x93810044U
#define ZX_MEASURED_GUEST_HDFAR     0x000065C0U
#define ZX_MEASURED_GUEST_HPFAR     0x00000060U
#define ZX_MEASURED_HYP_HSR         0x9600004CU
#define ZX_MEASURED_HYP_HDFAR       0x00006940U

/* The same guest violation, measured on S32Z280-594EVB SILICON on
   2 September 2026.  HPFAR is NOT the same register here: it holds the
   faulting address itself with its low four bits RES0, where the FVP holds
   FIPA[39:12] at [31:4].  Both values are kept so that a change to the
   decode has to disagree with one of two real parts, and so that the
   divergence itself is pinned down by a test rather than only by a note.  */

#define ZX_SILICON_GUEST_HSR        0x93810044U
#define ZX_SILICON_GUEST_HDFAR      0x31781200U
#define ZX_SILICON_GUEST_HPFAR      0x31781200U

/* Composes an HSR from an exception class and an ISS, which is what the
   negative cases need: the hardware will not produce them on request.  */

static uint32_t zx_hsr_of(uint32_t ec, uint32_t iss)
{
    return ((ec & ZX_HSR_EC_MASK) << ZX_HSR_EC_SHIFT) | (iss & ZX_HSR_ISS_MASK);
}


/* Every exception class TRM Table 3-88 documents.  At file scope, not inside
   ZX_TEST_MAIN, and that is not a style choice: the preprocessor separates
   macro arguments on commas at paren depth zero and BRACES DO NOT PROTECT
   THEM, so a braced initialiser list written inside the test body is read as
   seventeen extra arguments to a two-argument macro.  The error names the
   closing brace of the body, dozens of lines away from the cause.  */

static const uint32_t zx_documented_ec[] = {
    ZX_EC_UNKNOWN, ZX_EC_WFI_WFE, ZX_EC_MCR_MRC_CP15, ZX_EC_MCRR_MRRC_CP15,
    ZX_EC_MCR_MRC_CP14, ZX_EC_LDC_STC_CP14, ZX_EC_SIMD_FP, ZX_EC_VMRS,
    ZX_EC_MCRR_MRRC_CP14, ZX_EC_ILLEGAL_STATE, ZX_EC_SVC, ZX_EC_HVC,
    ZX_EC_PABT_ROUTED, ZX_EC_PABT_FROM_HYP, ZX_EC_PC_ALIGNMENT,
    ZX_EC_DABT_ROUTED, ZX_EC_DABT_FROM_HYP
};

#define ZX_DOCUMENTED_EC_COUNT \
    (sizeof(zx_documented_ec) / sizeof(zx_documented_ec[0]))


static void zx_fill_measured_guest_record(zx_fault_record_t *record)
{
    zx_fault_record_reset(record);
    record->zx_fault_captures = 5U;
    record->zx_fault_vector   = ZX_VECTOR_HYP_TRAP;
    record->zx_fault_hsr      = ZX_MEASURED_GUEST_HSR;
    record->zx_fault_hdfar    = ZX_MEASURED_GUEST_HDFAR;
    record->zx_fault_hpfar    = ZX_MEASURED_GUEST_HPFAR;
    record->zx_fault_hifar    = 0U;
    record->zx_fault_elr      = 0x00006400U;
    record->zx_fault_spsr     = 0x000001D3U;    /* mode 0x13, Supervisor */
}


ZX_TEST_MAIN("zx_fault",
{
    zx_fault_record_t record;

    /* ---------------------------------------------------------------- */
    /*  Field extraction.                                              */
    /* ---------------------------------------------------------------- */

    ZX_CHECK_EQ(zx_fault_ec(ZX_MEASURED_GUEST_HSR), ZX_EC_DABT_ROUTED);
    ZX_CHECK_EQ(zx_fault_ec(ZX_MEASURED_HYP_HSR), ZX_EC_DABT_FROM_HYP);
    ZX_CHECK_EQ(zx_fault_ec(0xFFFFFFFFU), 0x3FU);
    ZX_CHECK_EQ(zx_fault_ec(0x00000000U), 0x00U);

    /* ISS is [24:0], so bit 25 -- IL -- must NOT leak into it.  The
       measured guest syndrome has IL set, which is what makes it a useful
       value to check this with.  */
    ZX_CHECK_EQ(zx_fault_iss(ZX_MEASURED_GUEST_HSR), 0x01810044U);
    ZX_CHECK_EQ(zx_fault_iss(ZX_HSR_IL_MASK), 0U);

    /* ---------------------------------------------------------------- */
    /*  Classification.  The routed and taken-from pairs differ by one  */
    /*  bit of EC, and conflating them would let a run report a         */
    /*  hypervisor bug as a partition being stopped at its boundary.    */
    /* ---------------------------------------------------------------- */

    ZX_CHECK_EQ(zx_fault_classify(ZX_MEASURED_GUEST_HSR),
                ZX_FAULT_GUEST_VIOLATION);
    ZX_CHECK_EQ(zx_fault_classify(ZX_MEASURED_HYP_HSR),
                ZX_FAULT_HYPERVISOR_BUG);
    ZX_CHECK_EQ(zx_fault_classify(zx_hsr_of(ZX_EC_PABT_ROUTED, 0U)),
                ZX_FAULT_GUEST_VIOLATION);
    ZX_CHECK_EQ(zx_fault_classify(zx_hsr_of(ZX_EC_PABT_FROM_HYP, 0U)),
                ZX_FAULT_HYPERVISOR_BUG);
    ZX_CHECK_EQ(zx_fault_classify(zx_hsr_of(ZX_EC_HVC, 0U)),
                ZX_FAULT_HYPERCALL);
    ZX_CHECK_EQ(zx_fault_classify(zx_hsr_of(ZX_EC_WFI_WFE, 0U)),
                ZX_FAULT_UNEXPECTED_TRAP);
    ZX_CHECK_EQ(zx_fault_classify(zx_hsr_of(ZX_EC_SVC, 0U)),
                ZX_FAULT_UNEXPECTED_TRAP);
    ZX_CHECK_EQ(zx_fault_classify(zx_hsr_of(0x3FU, 0U)),
                ZX_FAULT_UNEXPECTED_TRAP);

    /* ---------------------------------------------------------------- */
    /*  Names.  Every documented class must have one, and an            */
    /*  UNdocumented value must not be silently given a plausible one:  */
    /*  a report naming EC 0x1F as some real exception would send a     */
    /*  reader looking for a cause that does not exist.                 */
    /* ---------------------------------------------------------------- */

    {
        size_t index;

        for (index = 0U; index < ZX_DOCUMENTED_EC_COUNT; index++)
        {
            const char *name = zx_fault_ec_name(zx_documented_ec[index]);

            ZX_CHECK(name[0] != '\0');
            /* Not the fallback text: every documented class is named.  */
            ZX_CHECK(name != zx_fault_ec_name(0x1FU));
        }
    }

    ZX_CHECK(zx_fault_ec_name(0x1FU)[0] != '\0');
    ZX_CHECK(zx_fault_ec_name(0x02U)[0] != '\0');

    ZX_CHECK(zx_fault_class_name(ZX_FAULT_GUEST_VIOLATION)[0] != '\0');
    ZX_CHECK(zx_fault_class_name(ZX_FAULT_HYPERVISOR_BUG)[0] != '\0');
    ZX_CHECK(zx_fault_class_name(ZX_FAULT_HYPERCALL)[0] != '\0');
    ZX_CHECK(zx_fault_class_name(ZX_FAULT_UNEXPECTED_TRAP)[0] != '\0');
    ZX_CHECK(zx_fault_class_name((zx_fault_class_t)99)[0] != '\0');

    ZX_CHECK(zx_fault_vector_name(ZX_VECTOR_RESET)[0] != '\0');
    ZX_CHECK(zx_fault_vector_name(ZX_VECTOR_UNDEF)[0] != '\0');
    ZX_CHECK(zx_fault_vector_name(ZX_VECTOR_SVC)[0] != '\0');
    ZX_CHECK(zx_fault_vector_name(ZX_VECTOR_PABT_HYP)[0] != '\0');
    ZX_CHECK(zx_fault_vector_name(ZX_VECTOR_DABT_HYP)[0] != '\0');
    ZX_CHECK(zx_fault_vector_name(ZX_VECTOR_HYP_TRAP)[0] != '\0');
    ZX_CHECK(zx_fault_vector_name(ZX_VECTOR_IRQ)[0] != '\0');
    ZX_CHECK(zx_fault_vector_name(ZX_VECTOR_FIQ)[0] != '\0');
    ZX_CHECK(zx_fault_vector_name(0x99U)[0] != '\0');

    /* ---------------------------------------------------------------- */
    /*  Vector versus syndrome.                                        */
    /* ---------------------------------------------------------------- */

    ZX_CHECK_EQ(zx_fault_vector_has_syndrome(ZX_VECTOR_PABT_HYP), 1U);
    ZX_CHECK_EQ(zx_fault_vector_has_syndrome(ZX_VECTOR_DABT_HYP), 1U);
    ZX_CHECK_EQ(zx_fault_vector_has_syndrome(ZX_VECTOR_HYP_TRAP), 1U);
    ZX_CHECK_EQ(zx_fault_vector_has_syndrome(ZX_VECTOR_RESET), 0U);
    ZX_CHECK_EQ(zx_fault_vector_has_syndrome(ZX_VECTOR_UNDEF), 0U);
    ZX_CHECK_EQ(zx_fault_vector_has_syndrome(ZX_VECTOR_SVC), 0U);
    ZX_CHECK_EQ(zx_fault_vector_has_syndrome(ZX_VECTOR_IRQ), 0U);
    ZX_CHECK_EQ(zx_fault_vector_has_syndrome(ZX_VECTOR_FIQ), 0U);

    /* The two measured records agree with themselves.  */
    ZX_CHECK_EQ(zx_fault_vector_agrees(ZX_VECTOR_HYP_TRAP,
                                       ZX_MEASURED_GUEST_HSR), 1U);
    ZX_CHECK_EQ(zx_fault_vector_agrees(ZX_VECTOR_DABT_HYP,
                                       ZX_MEASURED_HYP_HSR), 1U);
    ZX_CHECK_EQ(zx_fault_vector_agrees(ZX_VECTOR_PABT_HYP,
                                       zx_hsr_of(ZX_EC_PABT_FROM_HYP, 0U)), 1U);

    /* And the swaps do not.  A guest fault must never be reported as
       having arrived at a Hyp-mode fault vector, or vice versa.  */
    ZX_CHECK_EQ(zx_fault_vector_agrees(ZX_VECTOR_DABT_HYP,
                                       ZX_MEASURED_GUEST_HSR), 0U);
    ZX_CHECK_EQ(zx_fault_vector_agrees(ZX_VECTOR_HYP_TRAP,
                                       ZX_MEASURED_HYP_HSR), 0U);
    ZX_CHECK_EQ(zx_fault_vector_agrees(ZX_VECTOR_HYP_TRAP,
                                       zx_hsr_of(ZX_EC_PABT_FROM_HYP, 0U)), 0U);
    ZX_CHECK_EQ(zx_fault_vector_agrees(ZX_VECTOR_IRQ,
                                       zx_hsr_of(ZX_EC_HVC, 0U)), 0U);

    /* ---------------------------------------------------------------- */
    /*  Data-abort syndrome fields, against the measured values.       */
    /* ---------------------------------------------------------------- */

    ZX_CHECK_EQ(zx_fault_dabt_dfsc(ZX_MEASURED_GUEST_HSR), 0x04U);
    ZX_CHECK_EQ(zx_fault_dabt_dfsc(ZX_MEASURED_HYP_HSR), 0x0CU);
    ZX_CHECK_EQ(zx_fault_dabt_is_write(ZX_MEASURED_GUEST_HSR), 1U);
    ZX_CHECK_EQ(zx_fault_dabt_is_write(ZX_MEASURED_HYP_HSR), 1U);

    /* 0x93810004 is the same guest fault on a READ, also measured.  */
    ZX_CHECK_EQ(zx_fault_dabt_is_write(0x93810004U), 0U);
    ZX_CHECK_EQ(zx_fault_dabt_dfsc(0x93810004U), 0x04U);

    /* ---------------------------------------------------------------- */
    /*  HVC immediates.  The two ZoneX uses mean opposite things, so a  */
    /*  decode that confused them would turn "the payload handed        */
    /*  control back" into "the payload asked for nothing".            */
    /* ---------------------------------------------------------------- */

    ZX_CHECK_EQ(zx_fault_hvc_immediate(zx_hsr_of(ZX_EC_HVC, ZX_HVC_NOP)),
                ZX_HVC_NOP);
    ZX_CHECK_EQ(zx_fault_hvc_immediate(zx_hsr_of(ZX_EC_HVC, ZX_HVC_YIELD)),
                ZX_HVC_YIELD);
    ZX_CHECK_EQ(zx_fault_hvc_immediate(zx_hsr_of(ZX_EC_HVC, 0x0017U)), 0x0017U);
    /* Only [15:0].  A bit above the immediate field must not appear in it. */
    ZX_CHECK_EQ(zx_fault_hvc_immediate(zx_hsr_of(ZX_EC_HVC, 0x00FF0001U)),
                0x0001U);

    /* ---------------------------------------------------------------- */
    /*  HPFAR.  This is the arithmetic the FVP run measured, and the    */
    /*  reason the measurement was needed: the TRM's figure and the     */
    /*  table row beside it describe two different shifts.              */
    /* ---------------------------------------------------------------- */

    ZX_CHECK_EQ(zx_fault_hpfar_page(ZX_MEASURED_GUEST_HPFAR), 0x00006000U);
    ZX_CHECK_EQ(zx_fault_hpfar_high(ZX_MEASURED_GUEST_HPFAR), 0U);
    ZX_CHECK_EQ(zx_fault_hpfar_matches_hdfar(ZX_MEASURED_GUEST_HPFAR,
                                             ZX_MEASURED_GUEST_HDFAR), 1U);

    /* HPFAR[3:0] is RES0.  It reads zero today, and masking it away means a
       part that ever used those bits cannot contribute them to an address.  */
    ZX_CHECK_EQ(zx_fault_hpfar_page(ZX_MEASURED_GUEST_HPFAR | 0xFU),
                0x00006000U);

    /* FIPA[39:32] non-zero: an address above 4 GB, which no ZoneX target
       has.  The page decode truncates it, and hpfar_high is how a report
       can say so instead of printing a plausible wrong address.  */
    ZX_CHECK_EQ(zx_fault_hpfar_high(0x12000060U), 0x12U);
    ZX_CHECK_EQ(zx_fault_hpfar_matches_hdfar(0x12000060U, 0x00006000U), 0U);

    /* A genuine mismatch, which is what a wrong HPFAR reading would look
       like: the same raw value read as HDFAR[31:4] gives 0x60, not
       0x6000.  */
    ZX_CHECK_EQ(zx_fault_hpfar_matches_hdfar(ZX_MEASURED_GUEST_HPFAR,
                                             0x00000060U), 0U);

    /* The whole 4 KB page maps to one HPFAR value, which is the finding that
       matters for the region work: HPFAR resolves to 4 KB, NOT to the
       64-byte MPU granule, so it cannot say which granule faulted.  */
    ZX_CHECK_EQ(zx_fault_hpfar_matches_hdfar(ZX_MEASURED_GUEST_HPFAR,
                                             0x00006000U), 1U);
    ZX_CHECK_EQ(zx_fault_hpfar_matches_hdfar(ZX_MEASURED_GUEST_HPFAR,
                                             0x00006FFFU), 1U);
    ZX_CHECK_EQ(zx_fault_hpfar_matches_hdfar(ZX_MEASURED_GUEST_HPFAR,
                                             0x00007000U), 0U);

    /* ---------------------------------------------------------------- */
    /*  The two readings, and which one a target implements.  This is    */
    /*  the finding of the whole step: the model and the silicon         */
    /*  implement DIFFERENT ones of the TRM's two descriptions.          */
    /* ---------------------------------------------------------------- */

    ZX_CHECK_EQ(zx_fault_hpfar_as_address(ZX_SILICON_GUEST_HPFAR),
                0x31781200U);
    ZX_CHECK_EQ(zx_fault_hpfar_as_address(0x3178120FU), 0x31781200U);
    ZX_CHECK_EQ(zx_fault_hpfar_matches_as_address(ZX_SILICON_GUEST_HPFAR,
                                                  ZX_SILICON_GUEST_HDFAR), 1U);
    ZX_CHECK_EQ(zx_fault_hpfar_matches_as_address(ZX_MEASURED_GUEST_HPFAR,
                                                  ZX_MEASURED_GUEST_HDFAR), 0U);

    /* The FVP's record reads as FIPA and NOT as an address; the S32Z280's
       reads as an address and NOT as FIPA.  Each excludes the other, which
       is what makes each measurement conclusive.  */
    ZX_CHECK_EQ(zx_fault_hpfar_reading(ZX_MEASURED_GUEST_HPFAR,
                                       ZX_MEASURED_GUEST_HDFAR),
                ZX_HPFAR_AS_FIPA);
    ZX_CHECK_EQ(zx_fault_hpfar_reading(ZX_SILICON_GUEST_HPFAR,
                                       ZX_SILICON_GUEST_HDFAR),
                ZX_HPFAR_AS_ADDRESS);

    /* A faulting address whose low twelve bits are zero satisfies BOTH
       readings, so it proves nothing -- and the classifier must say so
       rather than pick one.  This is why the probe faults on an address it
       chose to be granule-aligned but not page-aligned.  */
    ZX_CHECK_EQ(zx_fault_hpfar_reading(0x00000000U, 0x00000000U),
                ZX_HPFAR_AMBIGUOUS);

    ZX_CHECK_EQ(zx_fault_hpfar_reading(0xDEADBEE0U, 0x00006000U),
                ZX_HPFAR_UNRECOGNISED);

    ZX_CHECK(zx_fault_hpfar_reading_name(ZX_HPFAR_AS_FIPA)[0] != '\0');
    ZX_CHECK(zx_fault_hpfar_reading_name(ZX_HPFAR_AS_ADDRESS)[0] != '\0');
    ZX_CHECK(zx_fault_hpfar_reading_name(ZX_HPFAR_AMBIGUOUS)[0] != '\0');
    ZX_CHECK(zx_fault_hpfar_reading_name(ZX_HPFAR_UNRECOGNISED)[0] != '\0');
    ZX_CHECK(zx_fault_hpfar_reading_name((zx_hpfar_reading_t)99)[0] != '\0');

    /* ---------------------------------------------------------------- */
    /*  The record.                                                    */
    /* ---------------------------------------------------------------- */

    zx_fill_measured_guest_record(&record);
    zx_fault_record_reset(&record);
    ZX_CHECK_EQ(record.zx_fault_captures, 0U);
    ZX_CHECK_EQ(record.zx_fault_vector, 0U);
    ZX_CHECK_EQ(record.zx_fault_hsr, 0U);
    ZX_CHECK_EQ(record.zx_fault_hpfar, 0U);
    ZX_CHECK_EQ(record.zx_fault_hdfar, 0U);
    ZX_CHECK_EQ(record.zx_fault_hifar, 0U);
    ZX_CHECK_EQ(record.zx_fault_elr, 0U);
    ZX_CHECK_EQ(record.zx_fault_spsr, 0U);

    /* A null pointer must be tolerated: this is called from a fault
       handler, and a reporter that faults turns one diagnosable problem
       into none.  */
    zx_fault_record_reset(NULL);

    /* ---------------------------------------------------------------- */
    /*  The report's TEXT.  What is asserted here is what somebody      */
    /*  reading a captured log actually needs to find in it.           */
    /* ---------------------------------------------------------------- */

    zx_capture_reset();
    zx_fault_report(NULL);
    ZX_CHECK_EQ(zx_capture_contains("no fault record"), 1U);

    zx_capture_reset();
    zx_fill_measured_guest_record(&record);
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_overflowed(), 0U);
    ZX_CHECK_EQ(zx_capture_contains("GUEST VIOLATION"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("data abort ROUTED to Hyp"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("+0x14"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("0x93810044"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("0x00000024"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("on a WRITE"), 1U);
    /* HPFAR raw AND decoded.  Printing only the decode would make the
       decode unfalsifiable from a log.  */
    ZX_CHECK_EQ(zx_capture_contains("0x00000060"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("0x00006000"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("0x000065c0"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("HPFAR reads as"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("FIPA[39:12] at HPFAR[31:4]"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("no\n[FAULT]   portable decode"), 1U);
    /* No spurious disagreement warning on a self-consistent record.  */
    ZX_CHECK_EQ(zx_capture_contains("DISAGREE"), 0U);

    /* THE SAME VIOLATION ON A READ, because the report has to say which and
       a report that only ever printed one of the two would be indetectable
       from any run that only ever provoked one.  The isolation matrix
       provokes both against the same address on purpose -- a region set
       that denied writes and permitted reads would pass a write-only
       sweep -- so the two words in this report carry a claim rather than
       decoration.  ISS[6] is WnR; clearing it is the whole difference.  */

    zx_capture_reset();
    zx_fill_measured_guest_record(&record);
    record.zx_fault_hsr &= ~ZX_ISS_WNR_MASK;
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_contains("on a READ"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("on a WRITE"), 0U);
    ZX_CHECK_EQ(zx_capture_contains("data abort ROUTED to Hyp"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("CARRIES NO SYNDROME"), 0U);

    /* The hypervisor fault must read as a DIFFERENT event.  */
    zx_capture_reset();
    zx_fault_record_reset(&record);
    record.zx_fault_vector = ZX_VECTOR_DABT_HYP;
    record.zx_fault_hsr    = ZX_MEASURED_HYP_HSR;
    record.zx_fault_hdfar  = ZX_MEASURED_HYP_HDFAR;
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_contains("ZONEX FAULTED AT EL2"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("GUEST VIOLATION"), 0U);
    ZX_CHECK_EQ(zx_capture_contains("+0x10"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("TAKEN FROM Hyp"), 1U);
    /* HPFAR is not updated for a fault taken from Hyp, so the report must
       NOT claim any reading of it against HDFAR.  */
    ZX_CHECK_EQ(zx_capture_contains("HPFAR reads as"), 0U);

    /* A vector that carries no syndrome: the report must say the HSR is
       stale rather than accuse the hardware of disagreeing with itself.
       This is the case the FVP produced when ICH_VTR was read with
       ICC_HSRE.SRE clear.  */
    zx_capture_reset();
    zx_fault_record_reset(&record);
    record.zx_fault_vector = ZX_VECTOR_UNDEF;
    record.zx_fault_hsr    = 0x0FE33017U;   /* left over, measured */
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_contains("CARRIES NO SYNDROME"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("DISAGREE"), 0U);
    ZX_CHECK_EQ(zx_capture_contains("+0x04"), 1U);

    /* A vector that DOES carry a syndrome, disagreeing with it.  Here the
       warning is correct and must appear.  */
    zx_capture_reset();
    zx_fault_record_reset(&record);
    record.zx_fault_vector = ZX_VECTOR_DABT_HYP;
    record.zx_fault_hsr    = ZX_MEASURED_GUEST_HSR;   /* EC 0x24, wrong here */
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_contains("DISAGREE"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("CARRIES NO SYNDROME"), 0U);

    /* A hypercall record, so the HVC branch of the ISS decode is covered. */
    zx_capture_reset();
    zx_fault_record_reset(&record);
    record.zx_fault_vector = ZX_VECTOR_HYP_TRAP;
    record.zx_fault_hsr    = zx_hsr_of(ZX_EC_HVC, ZX_HVC_YIELD);
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_contains("HYPERCALL"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("HVC immediate"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("0x00000001"), 1U);

    /* A class with no ISS decode at all, so the third arm is covered.  */
    zx_capture_reset();
    zx_fault_record_reset(&record);
    record.zx_fault_vector = ZX_VECTOR_HYP_TRAP;
    record.zx_fault_hsr    = zx_hsr_of(ZX_EC_WFI_WFE, 0U);
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_contains("UNEXPECTED TRAP"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("trapped WFI/WFE"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("DFSC"), 0U);
    ZX_CHECK_EQ(zx_capture_contains("HVC immediate"), 0U);

    /* An HPFAR above 4 GB, which the report must flag as truncated.  */
    zx_capture_reset();
    zx_fault_record_reset(&record);
    record.zx_fault_vector = ZX_VECTOR_HYP_TRAP;
    record.zx_fault_hsr    = ZX_MEASURED_GUEST_HSR;
    record.zx_fault_hpfar  = 0x12000060U;
    record.zx_fault_hdfar  = ZX_MEASURED_GUEST_HDFAR;
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_contains("TRUNCATED"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("NEITHER documented reading"), 1U);

    /* The silicon record must read as the OTHER reading, from the same
       report code, with no edit.  This is the assertion that would catch a
       "simplification" of the decode back to one reading.  */
    zx_capture_reset();
    zx_fault_record_reset(&record);
    record.zx_fault_vector = ZX_VECTOR_HYP_TRAP;
    record.zx_fault_hsr    = ZX_SILICON_GUEST_HSR;
    record.zx_fault_hpfar  = ZX_SILICON_GUEST_HPFAR;
    record.zx_fault_hdfar  = ZX_SILICON_GUEST_HDFAR;
    zx_fault_report(&record);

    ZX_CHECK_EQ(zx_capture_contains("the TRM's Table 3-69 row"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("FIPA[39:12] at HPFAR[31:4]"), 0U);

    /* The capture console itself: a test that silently lost its output
       would assert the ABSENCE of text for the wrong reason.  */
    ZX_CHECK_EQ(zx_capture_contains(NULL), 0U);
    ZX_CHECK_EQ(zx_capture_exit_status(), 0xFFFFFFFFU);
})
