/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    test_zx_schedule.c                                   HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The static major frame: which partition owns which slot, and where  */
/*    on the physical counter each boundary falls.                        */
/*                                                                        */
/*  WHY THIS BELONGS ON A WORKSTATION AND NOT ON A BOARD                  */
/*                                                                        */
/*    The property the whole component exists to guarantee is that a      */
/*    frame does not DRIFT, and drift is invisible in any run short       */
/*    enough for a person to read.  A schedule that added the handler's   */
/*    own latency to every window would look perfect for a second, be     */
/*    a millisecond out after a minute, and be wrong by a whole window    */
/*    after an hour -- with every partition still taking its turn, in     */
/*    order, in the right proportion.                                     */
/*                                                                        */
/*    So the central case here runs TEN THOUSAND FRAMES and asserts that  */
/*    the last boundary is exactly the epoch plus the total tick count    */
/*    times the tick length.  That is a millisecond on a workstation and  */
/*    it is the assertion no amount of watching a board would make.       */
/*                                                                        */
/*    The second reason is arithmetic width.  The physical counter is     */
/*    64-bit and a boundary is a product, so a schedule that computed it  */
/*    in 32 bits would be correct for the first nine minutes on the       */
/*    S32Z280 and then wrap.  A test can start the epoch just below the   */
/*    32-bit boundary and see that immediately.                           */
/*                                                                        */
/**************************************************************************/

#include "zx_schedule.h"
#include "zx_console_capture.h"
#include "zx_test.h"

/* The board fact the schedule needs, as both targets report it.  The
   S32Z280's counter runs at 8 MHz and the model's at 100 MHz, so a tick of
   10 ms -- ThreadX's own default rate -- is 80,000 counts on one and
   1,000,000 on the other.  Both appear below, because a schedule that
   happened to work at one frequency and not the other would be a defect
   visible on exactly one of the two boards.  */
#define S32Z_TICK_COUNTS    80000U
#define FVP_TICK_COUNTS     1000000U

static ZX_PARTITION partitions[ZX_MAX_PARTITIONS];
static ZX_MANIFEST  manifest;
static ZX_SCHEDULE  schedule;

/* Only the fields the builder reads: an identity, a name for the report, and
   a window.  A fixture that filled in regions and images would suggest the
   schedule looked at them.  */
static void reset_manifest(UINT partition_count, ULONG ticks_each)
{
    UINT  index;
    ULONG total = 0UL;

    for (index = 0U; index < ZX_MAX_PARTITIONS; index++)
    {
        partitions[index].zx_partition_id           = index + 1U;
        partitions[index].zx_partition_name         = "p";
        partitions[index].zx_partition_window_ticks = ticks_each;

        if (index < partition_count)
        {
            total += ticks_each;
        }
    }

    manifest.zx_manifest_partitions        = partitions;
    manifest.zx_manifest_partition_count   = partition_count;
    manifest.zx_manifest_shared            = (const ZX_SHARED *)0;
    manifest.zx_manifest_shared_count      = 0U;
    manifest.zx_manifest_major_frame_ticks = total;
}


static void test_build(void)
{
    reset_manifest(2U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);

    ZX_CHECK_EQ(schedule.zx_schedule_window_count, 2U);
    ZX_CHECK_EQ(schedule.zx_schedule_frame_ticks, 10UL);
    ZX_CHECK_EQ(schedule.zx_schedule_windows[0].zx_window_partition, 0U);
    ZX_CHECK_EQ(schedule.zx_schedule_windows[1].zx_window_partition, 1U);
    ZX_CHECK_EQ(schedule.zx_schedule_windows[0].zx_window_ticks, 5UL);

    /* A built schedule is NOT a started one.  The epoch is a counter
       reading the caller has yet to take, and a schedule that reported
       itself running before it had one would put every boundary at zero --
       which is a deadline in the past, and therefore a hypervisor timer
       firing continuously.  */
    ZX_CHECK_EQ(zx_schedule_is_running(&schedule), 0U);
    ZX_CHECK_EQ(zx_schedule_current_partition(&schedule),
                ZX_MANIFEST_NO_INDEX);
    ZX_CHECK_EQ(zx_schedule_deadline(&schedule), 0U);

    /* Slots of DIFFERENT lengths, which is the asymmetry the whole
       demonstration rests on: a partition given a quarter of the frame must
       come out with a quarter of the frame, not with a quarter of the
       windows.  */
    reset_manifest(2U, 0UL);
    partitions[0].zx_partition_window_ticks = 7UL;
    partitions[1].zx_partition_window_ticks = 3UL;
    manifest.zx_manifest_major_frame_ticks  = 10UL;
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);
    ZX_CHECK_EQ(schedule.zx_schedule_windows[0].zx_window_ticks, 7UL);
    ZX_CHECK_EQ(schedule.zx_schedule_windows[1].zx_window_ticks, 3UL);
}


static void test_build_rejections(void)
{
    reset_manifest(2U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build((const ZX_MANIFEST *)0, S32Z_TICK_COUNTS,
                                  0UL, &schedule),
                ZX_MANIFEST_NULL_POINTER);

    reset_manifest(2U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  (ZX_SCHEDULE *)0),
                ZX_MANIFEST_NULL_POINTER);

    reset_manifest(2U, 5UL);
    manifest.zx_manifest_partitions = (const ZX_PARTITION *)0;
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_NULL_POINTER);

    reset_manifest(0U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_NO_PARTITIONS);

    reset_manifest(2U, 5UL);
    manifest.zx_manifest_partition_count = ZX_MAX_PARTITIONS + 1U;
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_TOO_MANY_PARTITIONS);

    /* A TICK OF NO LENGTH.  Every boundary would then be the epoch, so the
       hypervisor timer would be permanently expired and the run would hang
       inside EL2 with no output and no fault to point at.  Refused where it
       can be named.  */
    reset_manifest(2U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, 0U, 0UL, &schedule),
                ZX_MANIFEST_ZERO_WINDOW);

    /* A partition declared with no window is a partition that never runs.
       The manifest validator has the same rule; it is repeated here because
       the schedule is built from the manifest and a frame with an invisible
       member is worse than a refusal.  */
    reset_manifest(2U, 5UL);
    partitions[1].zx_partition_window_ticks = 0UL;
    manifest.zx_manifest_major_frame_ticks  = 5UL;
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_ZERO_WINDOW);

    /* THE FRAME MUST EQUAL THE SUM OF ITS PARTS.  The manifest carries the
       total explicitly precisely so that it can disagree -- a computed
       field could never be wrong and would check nothing -- and a
       disagreement means somebody changed a window and not the total.  */
    reset_manifest(2U, 5UL);
    manifest.zx_manifest_major_frame_ticks = 11UL;
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_FRAME_MISMATCH);

    /* A REFUSED BUILD LEAVES NOTHING RUNNABLE.  Every rejection above
       returns before the window count is set, so a caller that ignored the
       status would find a schedule with no windows rather than one holding
       whatever the last successful build left -- which is the failure that
       would enter the wrong partition.  */
    ZX_CHECK_EQ(schedule.zx_schedule_window_count, 0U);
    ZX_CHECK_EQ(zx_schedule_is_running(&schedule), 0U);
}


/**************************************************************************/
/*  advance_for_its_side_effect                                           */
/*                                                                        */
/*  zx_schedule_advance is ZX_NODISCARD, and a (void) cast does NOT       */
/*  silence GCC's warn_unused_result -- deliberately, because an          */
/*  attribute that a cast could switch off would not be worth having.     */
/*  Three tests below turn the schedule over for its effect on the FRAME  */
/*  -- the drift arithmetic, the frame count, the frame limit -- and have */
/*  no business asserting which partition comes next; the ones that do    */
/*  assert it call zx_schedule_advance directly, a few lines above.       */
/*                                                                        */
/*  So the value is consumed here, once, where the reason is written      */
/*  down, rather than four times where it would read as an oversight.     */
/**************************************************************************/

static void advance_for_its_side_effect(ZX_SCHEDULE *schedule_ptr)
{
    UINT next = zx_schedule_advance(schedule_ptr);

    (void) next;
}


static void test_round_robin(void)
{
    UINT index;

    reset_manifest(2U, 0UL);
    partitions[0].zx_partition_window_ticks = 7UL;
    partitions[1].zx_partition_window_ticks = 3UL;
    manifest.zx_manifest_major_frame_ticks  = 10UL;

    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);

    zx_schedule_start(&schedule, 1000U);

    ZX_CHECK_EQ(zx_schedule_is_running(&schedule), 1U);
    ZX_CHECK_EQ(zx_schedule_current_partition(&schedule), 0U);

    /* The first boundary is seven ticks past the epoch, not seven ticks past
       "now": the epoch IS now, and the distinction only becomes visible at
       the second boundary.  */
    ZX_CHECK_EQ(zx_schedule_deadline(&schedule),
                1000U + (7U * (uint64_t)S32Z_TICK_COUNTS));

    ZX_CHECK_EQ(zx_schedule_advance(&schedule), 1U);
    ZX_CHECK_EQ(zx_schedule_deadline(&schedule),
                1000U + (10U * (uint64_t)S32Z_TICK_COUNTS));
    ZX_CHECK_EQ(schedule.zx_schedule_frames, 0UL);

    /* The wrap.  Back to partition 0, and one frame complete.  */
    ZX_CHECK_EQ(zx_schedule_advance(&schedule), 0U);
    ZX_CHECK_EQ(schedule.zx_schedule_frames, 1UL);
    ZX_CHECK_EQ(zx_schedule_deadline(&schedule),
                1000U + (17U * (uint64_t)S32Z_TICK_COUNTS));

    /* Four partitions of one tick each, to see the index wrap somewhere
       other than at two.  A modulus written as a comparison is right for
       two windows whichever way it is written.  */
    reset_manifest(4U, 1UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, FVP_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);
    zx_schedule_start(&schedule, 0U);

    for (index = 0U; index < 4U; index++)
    {
        ZX_CHECK_EQ(zx_schedule_current_partition(&schedule), index);
        ZX_CHECK_EQ(zx_schedule_deadline(&schedule),
                    (uint64_t)(index + 1U) * FVP_TICK_COUNTS);
        advance_for_its_side_effect(&schedule);
    }

    ZX_CHECK_EQ(zx_schedule_current_partition(&schedule), 0U);
    ZX_CHECK_EQ(schedule.zx_schedule_frames, 1UL);
}


static void test_no_drift_over_many_frames(void)
{
    /* THE CENTRAL CASE, AND THE ONE NO BOARD RUN WOULD MAKE.
     *
     * Ten thousand frames of a two-window schedule.  The last boundary must
     * be EXACTLY the epoch plus the total tick count times the tick length
     * -- not approximately, and not within a window.
     *
     * A schedule that re-armed a relative countdown at each boundary would
     * pass every other test in this file and fail this one, because its
     * error is per-boundary and only shows up multiplied.  On the S32Z280
     * ten thousand frames of this schedule is two minutes of wall clock; a
     * partition switch of a few thousand cycles added to each of twenty
     * thousand boundaries would put the last one nearly a second late, and
     * nothing about the run would look wrong.
     *
     * The epoch is deliberately NOT zero.  An arithmetic slip that dropped
     * the epoch entirely is invisible when the epoch is zero, and that is
     * exactly the sort of test that passes on a fixture and fails on a
     * board where the counter has been running since reset.  */

    ULONG    frame;
    uint64_t expected;

    reset_manifest(2U, 0UL);
    partitions[0].zx_partition_window_ticks = 7UL;
    partitions[1].zx_partition_window_ticks = 3UL;
    manifest.zx_manifest_major_frame_ticks  = 10UL;

    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);

    zx_schedule_start(&schedule, 0x12345678U);

    for (frame = 0UL; frame < 10000UL; frame++)
    {
        advance_for_its_side_effect(&schedule);
        advance_for_its_side_effect(&schedule);
    }

    ZX_CHECK_EQ(schedule.zx_schedule_frames, 10000UL);
    ZX_CHECK_EQ(schedule.zx_schedule_ticks_spent, 100000U);

    expected = 0x12345678U
               + (((uint64_t)100000U + 7U) * (uint64_t)S32Z_TICK_COUNTS);

    ZX_CHECK_EQ(zx_schedule_deadline(&schedule), expected);

    /* And nothing about the run reported a missed deadline, because
       advancing a schedule cannot miss one -- only a caller comparing a
       boundary against a real counter can.  */
    ZX_CHECK_EQ(schedule.zx_schedule_missed, 0UL);
}


static void test_boundaries_are_64_bit(void)
{
    /* AN EPOCH JUST BELOW THE 32-BIT BOUNDARY.
     *
     * The physical counter is 64-bit and it has been running since the board
     * was reset, so a hypervisor started ten minutes in is already past
     * 0xFFFFFFFF at the S32Z280's 8 MHz.  A boundary computed in 32 bits
     * would wrap to a small number, land in the past, and turn the frame
     * into a continuous storm of expired timer interrupts -- which presents
     * as a hang inside EL2 rather than as an arithmetic bug.
     *
     * Nine minutes of uptime is not an exotic condition on a bench.  This is
     * the case that costs nothing here and a debugging session there.  */

    uint64_t epoch = 0xFFFFFF00U;

    reset_manifest(2U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);

    zx_schedule_start(&schedule, epoch);

    ZX_CHECK_EQ(zx_schedule_deadline(&schedule),
                epoch + (5U * (uint64_t)S32Z_TICK_COUNTS));
    ZX_CHECK(zx_schedule_deadline(&schedule) > 0xFFFFFFFFU);

    /* And the tick product itself must not be truncated: a frame of 100000
       ticks at 80000 counts is 8x10^9, past 32 bits on its own.  */
    reset_manifest(2U, 50000UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);
    zx_schedule_start(&schedule, 0U);
    ZX_CHECK_EQ(zx_schedule_deadline(&schedule),
                (uint64_t)50000U * (uint64_t)S32Z_TICK_COUNTS);
}


static void test_frame_limit(void)
{
    /* A BOUNDED RUN, which is what a ctest can assert on.
     *
     * The limit is checked after the wrap, so a limit of two frames means
     * every window of frames 0 and 1 runs and nothing of frame 2 does.  The
     * advance that completes the last frame returns NO_INDEX, which is the
     * signal to stop entering partitions rather than a partition index a
     * caller might enter by mistake.  */

    reset_manifest(2U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 2UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);

    zx_schedule_start(&schedule, 0U);

    ZX_CHECK_EQ(zx_schedule_advance(&schedule), 1U);    /* frame 0, w1 */
    ZX_CHECK_EQ(zx_schedule_advance(&schedule), 0U);    /* frame 1, w0 */
    ZX_CHECK_EQ(zx_schedule_advance(&schedule), 1U);    /* frame 1, w1 */
    ZX_CHECK_EQ(zx_schedule_is_running(&schedule), 1U);

    ZX_CHECK_EQ(zx_schedule_advance(&schedule), ZX_MANIFEST_NO_INDEX);
    ZX_CHECK_EQ(schedule.zx_schedule_frames, 2UL);
    ZX_CHECK_EQ(zx_schedule_is_running(&schedule), 0U);

    /* A FINISHED SCHEDULE STAYS FINISHED, and says so in every way a caller
       might ask.  A stopped schedule that still returned a partition index
       would be entered once more, after its own limit, which is the whole
       thing a bounded run is for.  */
    ZX_CHECK_EQ(zx_schedule_advance(&schedule), ZX_MANIFEST_NO_INDEX);
    ZX_CHECK_EQ(zx_schedule_current_partition(&schedule),
                ZX_MANIFEST_NO_INDEX);
    ZX_CHECK_EQ(zx_schedule_deadline(&schedule), 0U);

    /* An unlimited schedule does not stop, however many frames pass.  The
       demonstration wants this and a regression must not have it.  */
    reset_manifest(2U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);
    zx_schedule_start(&schedule, 0U);

    {
        ULONG step;

        for (step = 0UL; step < 1000UL; step++)
        {
            advance_for_its_side_effect(&schedule);
        }
    }

    ZX_CHECK_EQ(zx_schedule_is_running(&schedule), 1U);
    ZX_CHECK_EQ(schedule.zx_schedule_frames, 500UL);
}


static void test_null_and_unstarted(void)
{
    /* Every entry point takes a pointer a caller could get wrong, and every
       one of them is on the partition-switch path where a fault is a
       hypervisor crash rather than a diagnosis.  */

    ZX_CHECK_EQ(zx_schedule_deadline((const ZX_SCHEDULE *)0), 0U);
    ZX_CHECK_EQ(zx_schedule_current_partition((const ZX_SCHEDULE *)0),
                ZX_MANIFEST_NO_INDEX);
    ZX_CHECK_EQ(zx_schedule_advance((ZX_SCHEDULE *)0), ZX_MANIFEST_NO_INDEX);
    ZX_CHECK_EQ(zx_schedule_is_running((const ZX_SCHEDULE *)0), 0U);

    zx_schedule_start((ZX_SCHEDULE *)0, 0U);
    zx_schedule_note_missed((ZX_SCHEDULE *)0);
    zx_schedule_report((const ZX_SCHEDULE *)0, &manifest);
    zx_schedule_report(&schedule, (const ZX_MANIFEST *)0);

    /* STARTING A SCHEDULE THAT WAS NEVER BUILT MUST NOT MAKE IT RUN.  A
       build that was refused leaves no windows, and a start that ignored
       that would produce a running schedule whose current window is a
       zeroed structure -- so the first ERET would go to partition
       NO_INDEX's entry point.  */
    reset_manifest(2U, 5UL);
    manifest.zx_manifest_major_frame_ticks = 99UL;
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_FRAME_MISMATCH);
    zx_schedule_start(&schedule, 1234U);
    ZX_CHECK_EQ(zx_schedule_is_running(&schedule), 0U);
}


static void test_missed_deadlines(void)
{
    reset_manifest(2U, 5UL);
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);
    zx_schedule_start(&schedule, 0U);

    ZX_CHECK_EQ(schedule.zx_schedule_missed, 0UL);

    zx_schedule_note_missed(&schedule);
    zx_schedule_note_missed(&schedule);

    ZX_CHECK_EQ(schedule.zx_schedule_missed, 2UL);

    /* A miss does not stop the schedule, and that is deliberate.  The frame
       keeps its order and its proportions and simply takes longer than it
       was declared to, which is a condition worth REPORTING rather than one
       worth halting on: halting would turn a slow demonstrator into a dead
       one, and the number is what a test asserts against.  */
    ZX_CHECK_EQ(zx_schedule_is_running(&schedule), 1U);
    ZX_CHECK_EQ(zx_schedule_advance(&schedule), 1U);
}


static void test_report(void)
{
    reset_manifest(2U, 0UL);
    partitions[0].zx_partition_name         = "critical";
    partitions[1].zx_partition_name         = "untrusted";
    partitions[0].zx_partition_window_ticks = 7UL;
    partitions[1].zx_partition_window_ticks = 3UL;
    manifest.zx_manifest_major_frame_ticks  = 10UL;

    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);

    zx_capture_reset();
    zx_schedule_report(&schedule, &manifest);

    /* The frame, both partitions by name, and each window in BOTH units.
       A count without its board means nothing -- the two targets' counters
       differ by a factor of twelve -- and a tick without its counts cannot
       be checked against a measured run.  */
    ZX_CHECK_EQ(zx_capture_contains("major frame"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("critical"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("untrusted"), 1U);
    ZX_CHECK_EQ(zx_capture_contains("560000"), 1U);     /* 7 x 80000 */
    ZX_CHECK_EQ(zx_capture_contains("240000"), 1U);     /* 3 x 80000 */
    ZX_CHECK_EQ(zx_capture_contains("WRAPS for ever"), 1U);

    /* A bounded run says so, because the difference decides whether a
       reader should expect the log to end.  */
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 4UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);
    zx_capture_reset();
    zx_schedule_report(&schedule, &manifest);
    ZX_CHECK_EQ(zx_capture_contains("stopping after"), 1U);

    /* An unnamed partition must not print a null pointer, and neither must
       a window whose partition index is outside the manifest it is being
       reported against -- which cannot happen from a successful build and
       is exactly why it must not crash the report that would say so.  */
    partitions[1].zx_partition_name = (const CHAR *)0;
    ZX_CHECK_EQ(zx_schedule_build(&manifest, S32Z_TICK_COUNTS, 0UL,
                                  &schedule),
                ZX_MANIFEST_SUCCESS);
    zx_capture_reset();
    zx_schedule_report(&schedule, &manifest);
    ZX_CHECK_EQ(zx_capture_contains("(unnamed)"), 1U);

    schedule.zx_schedule_windows[1].zx_window_partition = ZX_MAX_PARTITIONS;
    zx_capture_reset();
    zx_schedule_report(&schedule, &manifest);
    ZX_CHECK_EQ(zx_capture_contains("(unnamed)"), 1U);
}


ZX_TEST_MAIN("test_zx_schedule",
    test_build();
    test_build_rejections();
    test_round_robin();
    test_no_drift_over_many_frames();
    test_boundaries_are_64_bit();
    test_frame_limit();
    test_null_and_unstarted();
    test_missed_deadlines();
    test_report();
)
