/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    test_zx_guest_console.c                              HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The guest console's tagging rules, asserted as TEXT.                */
/*                                                                        */
/*    This is a file whose entire output is read by a person, usually one */
/*    with a board on the bench and two partitions interleaving their     */
/*    output, so the properties worth testing are properties of the       */
/*    characters: that a tag opens every line and no more than every      */
/*    line, that a line nobody terminated does not swallow the            */
/*    hypervisor's next message, and that the identity in the tag is the  */
/*    one the hypervisor SCHEDULED rather than one a guest supplied.      */
/*                                                                        */
/*    Asserting that on a workstation is far better than reading a model  */
/*    log by eye, and it is the reason the capture console exists.        */
/*                                                                        */
/**************************************************************************/

#include "zx_guest_console.h"
#include "zx_console_capture.h"
#include "zx_test.h"

/* Feed a whole string through the one-character-at-a-time interface, which
   is what the hypercall path really does: one trap per character.  */
static void guest_says(const char *text)
{
    UINT index = 0U;

    while (text[index] != '\0')
    {
        zx_guest_console_putc((CHAR)text[index]);
        index++;
    }
}


static void test_one_tag_per_line(void)
{
    zx_guest_console_reset();
    zx_capture_reset();

    zx_guest_console_attach(1U, "guest A");
    guest_says("hello\nagain\n");
    zx_guest_console_detach();

    /* Both lines tagged, and the tag carries the id as well as the name --
       the name is what a reader recognises, the id is what the manifest and
       every region index are keyed on.  */
    ZX_CHECK(zx_capture_contains("[P1 guest A] hello\n") != 0U);
    ZX_CHECK(zx_capture_contains("[P1 guest A] again\n") != 0U);

    /* And NOT a third, dangling tag after the final newline.  The prefix is
       emitted on the first character of a line rather than after the
       newline that ended the previous one, precisely so that a guest which
       stops printing leaves no orphan tag -- which reads as output lost.  */
    ZX_CHECK(zx_capture_contains("[P1 guest A] [") == 0U);
    ZX_CHECK_EQ(zx_guest_console_characters(), 12U);
    ZX_CHECK_EQ(zx_guest_console_orphans(), 0U);
}


static void test_the_id_is_enough(void)
{
    zx_guest_console_reset();
    zx_capture_reset();

    /* A partition with no name.  The id alone identifies it in a manifest,
       so the console must not require a name to tag with.  */
    zx_guest_console_attach(2U, (const CHAR *)0);
    guest_says("terse\n");
    zx_guest_console_detach();

    ZX_CHECK(zx_capture_contains("[P2] terse\n") != 0U);
}


static void test_the_guest_cannot_choose_its_own_tag(void)
{
    zx_guest_console_reset();
    zx_capture_reset();

    /* A guest printing what LOOKS like another partition's tag.  It comes
       out tagged with the partition that was scheduled, with the guest's
       claim visible inside the line as ordinary text -- which is exactly
       what a reader needs to see.  A console that let the guest write the
       prefix would make every line of a captured log evidence of nothing.  */
    zx_guest_console_attach(1U, "guest A");
    guest_says("[P2 guest B] I am partition 2\n");
    zx_guest_console_detach();

    ZX_CHECK(zx_capture_contains("[P1 guest A] [P2 guest B] I am partition 2\n")
             != 0U);

    /* The forged tag never appears at the start of a line.  */
    ZX_CHECK(zx_capture_contains("\n[P2 guest B]") == 0U);
}


static void test_an_unterminated_line_is_closed(void)
{
    zx_guest_console_reset();
    zx_capture_reset();

    /* The case this rule exists for: a guest faults mid-sentence, which is
       when a log is read most carefully.  Without the newline that detach
       adds, the hypervisor's fault report would be appended to the guest's
       unfinished line and read as part of it.  */
    zx_guest_console_attach(1U, "guest A");
    guest_says("about to fau");
    zx_guest_console_detach();

    ZX_CHECK(zx_capture_contains("[P1 guest A] about to fau\n") != 0U);

    /* Detaching twice must not emit a second newline: a blank line in a
       fault report is a reader wondering what was lost.  */
    zx_capture_reset();
    zx_guest_console_detach();
    ZX_CHECK_EQ((int)(zx_capture_text()[0]), (int)'\0');
}


static void test_attaching_over_a_partial_line(void)
{
    zx_guest_console_reset();
    zx_capture_reset();

    /* Attaching a second partition while the first is mid-line is a caller
       error, and the honest response is to keep the two partitions' text on
       separate lines rather than to refuse: two partitions sharing one
       physical line would be a log that attributes text to the wrong
       guest.  */
    zx_guest_console_attach(1U, "guest A");
    guest_says("unfinished");
    zx_guest_console_attach(2U, "guest B");
    guest_says("mine\n");
    zx_guest_console_detach();

    ZX_CHECK(zx_capture_contains("[P1 guest A] unfinished\n") != 0U);
    ZX_CHECK(zx_capture_contains("[P2 guest B] mine\n") != 0U);
}


static void test_carriage_return_is_dropped(void)
{
    zx_guest_console_reset();
    zx_capture_reset();

    /* A UART-oriented guest ends its lines CR LF, which is entirely
       reasonable of it.  Forwarded, the CR would sit immediately before the
       next line's tag and overprint it on a terminal -- so a captured log
       and a live console would disagree about whether the tag was there at
       all.  Dropping it loses nothing: the newline is what ends a line
       here.  */
    zx_guest_console_attach(1U, "guest A");
    guest_says("first\r\nsecond\r\n");
    zx_guest_console_detach();

    ZX_CHECK(zx_capture_contains("[P1 guest A] first\n") != 0U);
    ZX_CHECK(zx_capture_contains("[P1 guest A] second\n") != 0U);
    ZX_CHECK(zx_capture_contains("\r") == 0U);

    /* Counted anyway.  The count answers "did the guest print through the
       hypervisor", and a character the console chose not to forward was
       still a character the guest asked to print.  */
    ZX_CHECK_EQ(zx_guest_console_characters(), 15U);
}


static void test_an_orphan_character_is_named(void)
{
    zx_guest_console_reset();
    zx_capture_reset();

    /* A console call reaching EL2 with no partition attached.  There is no
       innocent reason for it: the run loop and the console disagree about
       what is executing, and that is a ZoneX bug rather than a guest one.
       So it is tagged as such and counted SEPARATELY, where it cannot hide
       inside the total.  */
    guest_says("who am I\n");

    ZX_CHECK(zx_capture_contains("[guest, UNATTACHED -- a ZoneX bug] who am I\n")
             != 0U);
    ZX_CHECK_EQ(zx_guest_console_orphans(), 9U);
    ZX_CHECK_EQ(zx_guest_console_characters(), 9U);

    /* Reset really resets, so one image can run several experiments and
       each one's counts mean only its own.  */
    zx_guest_console_reset();
    ZX_CHECK_EQ(zx_guest_console_orphans(), 0U);
    ZX_CHECK_EQ(zx_guest_console_characters(), 0U);
}

ZX_TEST_MAIN("test_zx_guest_console",
    test_one_tag_per_line();
    test_the_id_is_enough();
    test_the_guest_cannot_choose_its_own_tag();
    test_an_unterminated_line_is_closed();
    test_attaching_over_a_partial_line();
    test_carriage_return_is_dropped();
    test_an_orphan_character_is_named();
)
