/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_console_capture.h                                 HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The host suite's console: a buffer instead of a UART.               */
/*                                                                        */
/*    This is what makes the fault report testable at all.  A fault       */
/*    report is a body of TEXT that somebody reads at three in the        */
/*    morning with a board on the bench, and the properties that matter   */
/*    about it -- that it names the exception class, that it prints HPFAR */
/*    raw as well as decoded, that it says so when the vector and the     */
/*    syndrome disagree -- are properties of the text.  Asserting on them */
/*    on a workstation is far better than provoking real faults and       */
/*    reading a log by eye.                                              */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_CONSOLE_CAPTURE_H
#define ZX_CONSOLE_CAPTURE_H

#include "zx_api.h"

/* Big enough for the longest fault report several times over.  A capture
   that silently truncated would make an assertion about absent text pass
   for the wrong reason, so zx_capture_overflowed reports it instead.  */

#define ZX_CAPTURE_SIZE 16384U

void zx_capture_reset(void);
const char *zx_capture_text(void);
uint32_t zx_capture_overflowed(void);

/* Substring search, because that is the only question the tests ask.  */

uint32_t zx_capture_contains(const char *needle);

/* The failure count the last zx_console_exit was given, or 0xFFFFFFFF if it
   has not been called.  */

uint32_t zx_capture_exit_status(void);

#endif /* ZX_CONSOLE_CAPTURE_H */
