/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_console_capture.c                                 HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The third implementation of common/inc/zx_console.h.  The other     */
/*    two are semihosting and a board UART, both in the Cortex-R52 port;  */
/*    this one keeps the bytes so a test can look at them.               */
/*                                                                        */
/*    The formatting is deliberately IDENTICAL to the port's, digit for   */
/*    digit -- eight zero-padded hexadecimal digits with an 0x prefix,    */
/*    decimal with no padding.  A capture that formatted differently      */
/*    would let a test assert on text no target ever prints, which is a   */
/*    worse outcome than having no test.                                 */
/*                                                                        */
/**************************************************************************/

#include "zx_console.h"
#include "zx_console_capture.h"

#include <stdlib.h>
#include <string.h>

#define ZX_HEX_DIGITS   8U

static char     zx_capture_buffer[ZX_CAPTURE_SIZE];
static size_t   zx_capture_used;
static uint32_t zx_capture_lost;
static uint32_t zx_capture_status = 0xFFFFFFFFU;


void zx_capture_reset(void)
{
    zx_capture_buffer[0] = '\0';
    zx_capture_used      = 0U;
    zx_capture_lost      = 0U;
    zx_capture_status    = 0xFFFFFFFFU;
}


const char *zx_capture_text(void)
{
    return zx_capture_buffer;
}


uint32_t zx_capture_overflowed(void)
{
    return zx_capture_lost;
}


uint32_t zx_capture_contains(const char *needle)
{
    if (needle == NULL)
    {
        return 0U;
    }

    return (strstr(zx_capture_buffer, needle) != NULL) ? 1U : 0U;
}


uint32_t zx_capture_exit_status(void)
{
    return zx_capture_status;
}


void zx_console_puts(const char *string_ptr)
{
    size_t length;

    if (string_ptr == NULL)
    {
        return;
    }

    length = strlen(string_ptr);

    if ((zx_capture_used + length + 1U) > ZX_CAPTURE_SIZE)
    {
        zx_capture_lost = 1U;
        return;
    }

    memcpy(&zx_capture_buffer[zx_capture_used], string_ptr, length + 1U);
    zx_capture_used += length;
}


void zx_console_puthex(uint32_t value)
{
    static const char digits[] = "0123456789abcdef";
    char              buffer[3U + ZX_HEX_DIGITS];
    uint32_t          index;

    buffer[0] = '0';
    buffer[1] = 'x';

    for (index = 0U; index < ZX_HEX_DIGITS; index++)
    {
        uint32_t shift = (ZX_HEX_DIGITS - 1U - index) * 4U;

        buffer[2U + index] = digits[(value >> shift) & 0xFU];
    }

    buffer[2U + ZX_HEX_DIGITS] = '\0';

    zx_console_puts(buffer);
}


void zx_console_putdec(uint32_t value)
{
    char     buffer[11];
    uint32_t index = (uint32_t)sizeof(buffer) - 1U;
    uint32_t work  = value;

    buffer[index] = '\0';

    do
    {
        index--;
        buffer[index] = (char)('0' + (char)(work % 10U));
        work /= 10U;
    } while ((work != 0U) && (index > 0U));

    zx_console_puts(&buffer[index]);
}


ZX_NORETURN void zx_console_exit(uint32_t failures)
{
    zx_capture_status = failures;

    /* The host suite has no image to stop, and a test that called this would
       otherwise take its own process down mid-run.  exit is honest about
       what the declaration promises; the tests simply never call it.  */

    exit((int)(failures == 0U ? 0U : 1U));
}
