/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_test.h                                            HOST TESTS     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The whole of the ZoneX host unit-test harness.                      */
/*                                                                        */
/*    It is this small on purpose.  External dependencies are forbidden   */
/*    by project policy, so a third-party framework is not an option,     */
/*    and a hand-rolled one large enough to need testing itself would be  */
/*    a liability in a repository whose point is a certifiable            */
/*    hypervisor.  What is here is what CTest actually needs: a way to    */
/*    check a condition, a count of failures, and a process exit status   */
/*    that is non-zero when any check failed.                             */
/*                                                                        */
/*    A test binary that crashes or exits before printing its summary is  */
/*    a failure, never a pass -- the summary line is what the run is      */
/*    judged on, the same rule the FVP runner follows on the target side. */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_TEST_H
#define ZX_TEST_H

#include <stdio.h>

/* Not static: the checking macros below update it from any translation unit
   linked into a test binary, and ZX_TEST_MAIN defines it exactly once.  */
extern unsigned int zx_test_failures;
extern unsigned int zx_test_checks;

#define ZX_CHECK(condition)                                                   \
    do {                                                                      \
        zx_test_checks++;                                                     \
        if (!(condition)) {                                                   \
            zx_test_failures++;                                               \
            (void)printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #condition); \
        }                                                                     \
    } while (0)

#define ZX_CHECK_EQ(actual, expected)                                         \
    do {                                                                      \
        zx_test_checks++;                                                     \
        if ((actual) != (expected)) {                                         \
            zx_test_failures++;                                               \
            (void)printf("FAIL %s:%d: %s == %s\n",                            \
                         __FILE__, __LINE__, #actual, #expected);             \
        }                                                                     \
    } while (0)

/* Defines the counters and a main() that reports and returns a status CTest
   can read.  Exactly one translation unit per test binary uses it.  */
#define ZX_TEST_MAIN(suite_name, body)                                        \
    unsigned int zx_test_failures = 0U;                                       \
    unsigned int zx_test_checks   = 0U;                                       \
    int main(void)                                                            \
    {                                                                         \
        body                                                                  \
        (void)printf("%s: %u checks, %u failures\n",                          \
                     (suite_name), zx_test_checks, zx_test_failures);         \
        return (zx_test_failures == 0U) ? 0 : 1;                              \
    }

#endif /* ZX_TEST_H */
