/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_fault_log.c                                       PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Many faults, kept and attributed.  The rationale for keeping the    */
/*    FIRST entries rather than the last, and for attributing by          */
/*    partition and address, is in core/inc/zx_fault_log.h.               */
/*                                                                        */
/*    Arithmetic and storage only, so the host suite covers all of it.    */
/*                                                                        */
/**************************************************************************/

#include "zx_fault_log.h"
#include "zx_console.h"

/**************************************************************************/
/*  zx_fault_log_reset                                                    */
/**************************************************************************/

void zx_fault_log_reset(ZX_FAULT_LOG *log_ptr)
{
    uint32_t index;

    if (log_ptr == (ZX_FAULT_LOG *)0)
    {
        return;
    }

    for (index = 0U; index < ZX_FAULT_LOG_ENTRIES; index++)
    {
        log_ptr->zx_log_entries[index].zx_log_hsr       = 0U;
        log_ptr->zx_log_entries[index].zx_log_hdfar     = 0U;
        log_ptr->zx_log_entries[index].zx_log_hifar     = 0U;
        log_ptr->zx_log_entries[index].zx_log_elr       = 0U;
        log_ptr->zx_log_entries[index].zx_log_spsr      = 0U;
        log_ptr->zx_log_entries[index].zx_log_partition = ZX_MANIFEST_NO_INDEX;
        log_ptr->zx_log_entries[index].zx_log_resumed   =
            ZX_FAULT_RESUMED_STOPPED;
    }

    log_ptr->zx_log_kept    = 0U;
    log_ptr->zx_log_total   = 0U;
    log_ptr->zx_log_dropped = 0U;

    for (index = 0U; index < ZX_MAX_PARTITIONS; index++)
    {
        log_ptr->zx_log_partition_total[index] = 0U;
    }
}


/**************************************************************************/
/*  zx_fault_log_add                                                      */
/*                                                                        */
/*  THE TOTALS ARE UPDATED WHETHER OR NOT THE ENTRY IS KEPT, and that is  */
/*  the whole reason the two numbers are separate.  A run whose array     */
/*  filled must still be able to say how many faults there were, because  */
/*  "this partition faulted eleven thousand times and its neighbour's     */
/*  period did not move" is a claim about the count and not about the     */
/*  syndromes.                                                            */
/**************************************************************************/

void zx_fault_log_add(ZX_FAULT_LOG *log_ptr, UINT partition,
                      const zx_fault_record_t *record_ptr,
                      uint32_t resumed)
{
    if ((log_ptr == (ZX_FAULT_LOG *)0)
        || (record_ptr == (const zx_fault_record_t *)0))
    {
        return;
    }

    log_ptr->zx_log_total++;

    /* Guarded because it indexes.  An unattributable fault still counts in
       the total above -- discarding it would make a fault the frame could
       not place disappear, which is the opposite of what a log is for.  */

    if (partition < ZX_MAX_PARTITIONS)
    {
        log_ptr->zx_log_partition_total[partition]++;
    }

    if (log_ptr->zx_log_kept >= ZX_FAULT_LOG_ENTRIES)
    {
        log_ptr->zx_log_dropped++;

        return;
    }

    {
        ZX_FAULT_LOG_ENTRY *entry_ptr =
            &log_ptr->zx_log_entries[log_ptr->zx_log_kept];

        entry_ptr->zx_log_hsr       = record_ptr->zx_fault_hsr;
        entry_ptr->zx_log_hdfar     = record_ptr->zx_fault_hdfar;
        entry_ptr->zx_log_hifar     = record_ptr->zx_fault_hifar;
        entry_ptr->zx_log_elr       = record_ptr->zx_fault_elr;
        entry_ptr->zx_log_spsr      = record_ptr->zx_fault_spsr;
        entry_ptr->zx_log_partition = partition;
        entry_ptr->zx_log_resumed   = resumed;
    }

    log_ptr->zx_log_kept++;
}


/**************************************************************************/
/*  zx_fault_log_entry_address                                            */
/*                                                                        */
/*  HIFAR for a prefetch abort, HDFAR for everything else.  Reading HDFAR */
/*  after a prefetch abort returns whatever the last DATA abort left in   */
/*  it, which is stale rather than wrong -- and stale reads exactly like  */
/*  a plausible answer, which is what makes it worth one function.        */
/**************************************************************************/

uint32_t zx_fault_log_entry_address(const ZX_FAULT_LOG_ENTRY *entry_ptr)
{
    uint32_t address = 0U;

    if (entry_ptr != (const ZX_FAULT_LOG_ENTRY *)0)
    {
        uint32_t ec = zx_fault_ec(entry_ptr->zx_log_hsr);

        if ((ec == ZX_EC_PABT_ROUTED) || (ec == ZX_EC_PABT_FROM_HYP))
        {
            address = entry_ptr->zx_log_hifar;
        }
        else
        {
            address = entry_ptr->zx_log_hdfar;
        }
    }

    return address;
}


/**************************************************************************/
/*  zx_fault_log_find                                                     */
/**************************************************************************/

const ZX_FAULT_LOG_ENTRY *zx_fault_log_find(const ZX_FAULT_LOG *log_ptr,
                                            UINT partition, uint32_t address)
{
    const ZX_FAULT_LOG_ENTRY *found = (const ZX_FAULT_LOG_ENTRY *)0;
    uint32_t                  index;

    if (log_ptr == (const ZX_FAULT_LOG *)0)
    {
        return found;
    }

    for (index = 0U; (index < log_ptr->zx_log_kept) &&
                     (found == (const ZX_FAULT_LOG_ENTRY *)0); index++)
    {
        const ZX_FAULT_LOG_ENTRY *entry_ptr = &log_ptr->zx_log_entries[index];

        if ((entry_ptr->zx_log_partition == partition)
            && (zx_fault_log_entry_address(entry_ptr) == address))
        {
            found = entry_ptr;
        }
    }

    return found;
}


/**************************************************************************/
/*  zx_fault_log_count_at                                                 */
/**************************************************************************/

uint32_t zx_fault_log_count_at(const ZX_FAULT_LOG *log_ptr, UINT partition,
                               uint32_t address)
{
    uint32_t matches = 0U;
    uint32_t index;

    if (log_ptr == (const ZX_FAULT_LOG *)0)
    {
        return matches;
    }

    for (index = 0U; index < log_ptr->zx_log_kept; index++)
    {
        const ZX_FAULT_LOG_ENTRY *entry_ptr = &log_ptr->zx_log_entries[index];

        if ((entry_ptr->zx_log_partition == partition)
            && (zx_fault_log_entry_address(entry_ptr) == address))
        {
            matches++;
        }
    }

    return matches;
}


/**************************************************************************/
/*  zx_fault_log_partition_total                                          */
/**************************************************************************/

uint32_t zx_fault_log_partition_total(const ZX_FAULT_LOG *log_ptr,
                                      UINT partition)
{
    uint32_t total = 0U;

    if ((log_ptr != (const ZX_FAULT_LOG *)0)
        && (partition < ZX_MAX_PARTITIONS))
    {
        total = log_ptr->zx_log_partition_total[partition];
    }

    return total;
}


/**************************************************************************/
/*  zx_fault_log_all_guest_violations                                     */
/*                                                                        */
/*  An EMPTY log answers NO.  "Every entry is a guest violation" is        */
/*  vacuously true of no entries, and a check written to accept that would */
/*  pass on a run in which the whole matrix was skipped -- which is the    */
/*  single most likely way a sweep goes wrong.                             */
/**************************************************************************/

uint32_t zx_fault_log_all_guest_violations(const ZX_FAULT_LOG *log_ptr)
{
    uint32_t all = 1U;
    uint32_t index;

    if ((log_ptr == (const ZX_FAULT_LOG *)0) || (log_ptr->zx_log_kept == 0U))
    {
        return 0U;
    }

    for (index = 0U; index < log_ptr->zx_log_kept; index++)
    {
        if (zx_fault_classify(log_ptr->zx_log_entries[index].zx_log_hsr)
                != ZX_FAULT_GUEST_VIOLATION)
        {
            all = 0U;
        }
    }

    return all;
}


/**************************************************************************/
/*  zx_fault_resumed_name                                                 */
/**************************************************************************/

const char *zx_fault_resumed_name(uint32_t resumed)
{
    const char *name;

    switch (resumed)
    {
    case ZX_FAULT_RESUMED_STOPPED:
        name = "the partition was STOPPED (the shipping policy)";
        break;

    case ZX_FAULT_RESUMED_SKIPPED:
        name = "resumed past the faulting instruction (test-only)";
        break;

    case ZX_FAULT_RESUMED_REDIRECTED:
        name = "resumed at the address the guest named (test-only)";
        break;

    default:
        name = "resumed in a way this build does not have a name for";
        break;
    }

    return name;
}


/**************************************************************************/
/*  zx_fault_log_report                                                   */
/*                                                                        */
/*  One line per entry, not a full zx_fault_report each: twelve of those  */
/*  is four hundred lines of console through a polled UART, and the whole */
/*  value of the log is that a reader can see the MATRIX rather than one  */
/*  fault at a time.  The last capture is still reported in full          */
/*  elsewhere, so no detail is lost -- only repeated.                     */
/**************************************************************************/

void zx_fault_log_report(const ZX_FAULT_LOG *log_ptr)
{
    uint32_t index;

    if (log_ptr == (const ZX_FAULT_LOG *)0)
    {
        zx_console_puts("[FAULTLOG] there is no fault log to report\n");

        return;
    }

    zx_console_puts("\n--- every violation this run provoked, in order ---\n");
    zx_console_puts("  kept ");
    zx_console_putdec(log_ptr->zx_log_kept);
    zx_console_puts(" of ");
    zx_console_putdec(log_ptr->zx_log_total);
    zx_console_puts(" total, ");
    zx_console_putdec(log_ptr->zx_log_dropped);
    zx_console_puts(" dropped once the array was full.\n");
    zx_console_puts("  The FIRST entries are kept, never the last: a phase\n"
                    "  that faults on every iteration would otherwise evict\n"
                    "  the matrix it was supposed to run after.\n\n");

    for (index = 0U; index < log_ptr->zx_log_kept; index++)
    {
        const ZX_FAULT_LOG_ENTRY *entry_ptr = &log_ptr->zx_log_entries[index];
        uint32_t                  ec        =
            zx_fault_ec(entry_ptr->zx_log_hsr);

        zx_console_puts("  [");
        zx_console_putdec(index);
        zx_console_puts("] partition ");
        zx_console_putdec(entry_ptr->zx_log_partition);
        zx_console_puts("  at ");
        zx_console_puthex(zx_fault_log_entry_address(entry_ptr));
        zx_console_puts("  EC ");
        zx_console_puthex(ec);
        zx_console_puts(" = ");
        zx_console_puts(zx_fault_ec_name(ec));

        if ((ec == ZX_EC_DABT_ROUTED) || (ec == ZX_EC_DABT_FROM_HYP))
        {
            zx_console_puts("\n       DFSC ");
            zx_console_puthex(zx_fault_dabt_dfsc(entry_ptr->zx_log_hsr));
            zx_console_puts(
                (zx_fault_dabt_dfsc(entry_ptr->zx_log_hsr)
                     == ZX_DFSC_MPU_PERMISSION)
                    ? " = a region COVERED it and its AP refused"
                    : " = no enabled region covered it");
            zx_console_puts(
                zx_fault_dabt_is_write(entry_ptr->zx_log_hsr) != 0U
                    ? ", on a WRITE" : ", on a READ");
        }
        else
        {
            /* A prefetch abort has no DFSC to decode, and the address
               above already came from HIFAR.  */
        }

        zx_console_puts("\n       PC ");
        zx_console_puthex(entry_ptr->zx_log_elr);
        zx_console_puts("  ");
        zx_console_puts(zx_fault_resumed_name(entry_ptr->zx_log_resumed));
        zx_console_puts("\n");
    }

    zx_console_puts("\n  by partition:\n");

    for (index = 0U; index < ZX_MAX_PARTITIONS; index++)
    {
        if (log_ptr->zx_log_partition_total[index] != 0U)
        {
            zx_console_puts("    partition ");
            zx_console_putdec(index);
            zx_console_puts(" faulted ");
            zx_console_putdec(log_ptr->zx_log_partition_total[index]);
            zx_console_puts(" times\n");
        }
    }
}
