/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/
// Some portions generated by Claude Code (Opus 5).

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_fault.c                                           PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Fault classification and reporting, driven by HSR.EC and, for a     */
/*    stage-2 violation, the faulting address in HPFAR.                   */
/*                                                                        */
/*    Everything here is arithmetic on words the port captured, so the    */
/*    host suite can exercise it without a model or a board -- which      */
/*    matters more for this file than for most, because the alternative   */
/*    is testing a fault decoder by provoking faults.                     */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Rule 15.5 (single point of exit) -- deviated in the two name        */
/*      lookups below, which return from inside a switch.  The           */
/*      alternative is a local pointer assigned in every case and         */
/*      returned once, which adds a variable and a store per lookup and   */
/*      makes a missing case harder to see, not easier.  Rule 16.1's      */
/*      requirement that every switch be well formed is observed: each    */
/*      clause is a single return and there is a default.                 */
/*                                                                        */
/**************************************************************************/

#include "zx_fault.h"
#include "zx_console.h"

/**************************************************************************/
/*  zx_fault_ec -- HSR.EC, bits [31:26].                                  */
/**************************************************************************/

uint32_t zx_fault_ec(uint32_t hsr)
{
    return (hsr >> ZX_HSR_EC_SHIFT) & ZX_HSR_EC_MASK;
}


/**************************************************************************/
/*  zx_fault_iss -- HSR.ISS, bits [24:0].                                 */
/**************************************************************************/

uint32_t zx_fault_iss(uint32_t hsr)
{
    return hsr & ZX_HSR_ISS_MASK;
}


/**************************************************************************/
/*  zx_fault_classify                                                     */
/*                                                                        */
/*  Which of the four things that can reach EL2 this is.  The routed and  */
/*  taken-from pairs differ by exactly one bit of EC, which is precisely  */
/*  why they are matched by name here rather than by masking: a mask that */
/*  lost that bit would report a hypervisor bug as a guest violation, and */
/*  a Phase-0 run would then "pass" on ZoneX faulting on itself.          */
/**************************************************************************/

zx_fault_class_t zx_fault_classify(uint32_t hsr)
{
    uint32_t         ec = zx_fault_ec(hsr);
    zx_fault_class_t result;

    if ((ec == ZX_EC_DABT_ROUTED) || (ec == ZX_EC_PABT_ROUTED))
    {
        result = ZX_FAULT_GUEST_VIOLATION;
    }
    else if ((ec == ZX_EC_DABT_FROM_HYP) || (ec == ZX_EC_PABT_FROM_HYP))
    {
        result = ZX_FAULT_HYPERVISOR_BUG;
    }
    else if (ec == ZX_EC_HVC)
    {
        result = ZX_FAULT_HYPERCALL;
    }
    else
    {
        result = ZX_FAULT_UNEXPECTED_TRAP;
    }

    return result;
}


/**************************************************************************/
/*  zx_fault_ec_name                                                      */
/**************************************************************************/

const char *zx_fault_ec_name(uint32_t ec)
{
    switch (ec)
    {
    case ZX_EC_UNKNOWN:        return "unknown reason";
    case ZX_EC_WFI_WFE:        return "trapped WFI/WFE";
    case ZX_EC_MCR_MRC_CP15:   return "trapped MCR/MRC, coproc 15";
    case ZX_EC_MCRR_MRRC_CP15: return "trapped MCRR/MRRC, coproc 15";
    case ZX_EC_MCR_MRC_CP14:   return "trapped MCR/MRC, coproc 14";
    case ZX_EC_LDC_STC_CP14:   return "trapped LDC/STC, coproc 14";
    case ZX_EC_SIMD_FP:        return "SIMD/floating-point access trapped by HCPTR";
    case ZX_EC_VMRS:           return "trapped VMRS";
    case ZX_EC_MCRR_MRRC_CP14: return "trapped MCRR/MRRC, coproc 14";
    case ZX_EC_ILLEGAL_STATE:  return "illegal state exception";
    case ZX_EC_SVC:            return "SVC taken to Hyp mode";
    case ZX_EC_HVC:            return "HVC executed";
    case ZX_EC_PABT_ROUTED:    return "prefetch abort ROUTED to Hyp";
    case ZX_EC_PABT_FROM_HYP:  return "prefetch abort TAKEN FROM Hyp";
    case ZX_EC_PC_ALIGNMENT:   return "PC alignment fault";
    case ZX_EC_DABT_ROUTED:    return "data abort ROUTED to Hyp";
    case ZX_EC_DABT_FROM_HYP:  return "data abort TAKEN FROM Hyp";
    default:                   return "not a documented exception class";
    }
}


/**************************************************************************/
/*  zx_fault_class_name                                                   */
/**************************************************************************/

const char *zx_fault_class_name(zx_fault_class_t fault_class)
{
    switch (fault_class)
    {
    case ZX_FAULT_GUEST_VIOLATION:
        return "GUEST VIOLATION -- a partition overstepped its stage-2 regions";
    case ZX_FAULT_HYPERVISOR_BUG:
        return "ZONEX FAULTED AT EL2 -- this is a hypervisor bug, not a guest one";
    case ZX_FAULT_HYPERCALL:
        return "HYPERCALL -- an intentional entry to EL2";
    case ZX_FAULT_UNEXPECTED_TRAP:
        return "UNEXPECTED TRAP -- routed to EL2 and not handled";
    default:
        return "not a ZoneX fault class";
    }
}


/**************************************************************************/
/*  zx_fault_vector_name                                                  */
/**************************************************************************/

const char *zx_fault_vector_name(uint32_t vector)
{
    switch (vector)
    {
    case ZX_VECTOR_RESET:     return "+0x00 reset";
    case ZX_VECTOR_UNDEF:     return "+0x04 undefined instruction, from Hyp";
    case ZX_VECTOR_SVC:       return "+0x08 SVC, from Hyp";
    case ZX_VECTOR_PABT_HYP:  return "+0x0C prefetch abort, from Hyp";
    case ZX_VECTOR_DABT_HYP:  return "+0x10 data abort, from Hyp";
    case ZX_VECTOR_HYP_TRAP:  return "+0x14 Hyp trap entry, from EL0/EL1";
    case ZX_VECTOR_IRQ:       return "+0x18 IRQ";
    case ZX_VECTOR_FIQ:       return "+0x1C FIQ";
    default:                  return "not an EL2 vector offset";
    }
}


/**************************************************************************/
/*  zx_fault_vector_agrees                                                */
/*                                                                        */
/*  Cross-check the vector that was taken against what HSR.EC claims.     */
/*  Anything routed to EL2 from EL0/EL1 arrives at +0x14; a fault taken   */
/*  FROM Hyp arrives at its own vector, +0x0C or +0x10.  Disagreement     */
/*  means one of the two is not what it is documented to be, which is     */
/*  worth reporting rather than quietly preferring one of them.           */
/**************************************************************************/

uint32_t zx_fault_vector_agrees(uint32_t vector, uint32_t hsr)
{
    uint32_t ec     = zx_fault_ec(hsr);
    uint32_t agrees;

    if (ec == ZX_EC_DABT_FROM_HYP)
    {
        agrees = (vector == ZX_VECTOR_DABT_HYP) ? 1U : 0U;
    }
    else if (ec == ZX_EC_PABT_FROM_HYP)
    {
        agrees = (vector == ZX_VECTOR_PABT_HYP) ? 1U : 0U;
    }
    else
    {
        agrees = (vector == ZX_VECTOR_HYP_TRAP) ? 1U : 0U;
    }

    return agrees;
}


/**************************************************************************/
/*  zx_fault_vector_has_syndrome                                          */
/**************************************************************************/

uint32_t zx_fault_vector_has_syndrome(uint32_t vector)
{
    return ((vector == ZX_VECTOR_PABT_HYP) || (vector == ZX_VECTOR_DABT_HYP)
            || (vector == ZX_VECTOR_HYP_TRAP)) ? 1U : 0U;
}


/**************************************************************************/
/*  zx_fault_dabt_dfsc / zx_fault_dabt_is_write                           */
/**************************************************************************/

uint32_t zx_fault_dabt_dfsc(uint32_t hsr)
{
    return zx_fault_iss(hsr) & ZX_ISS_DFSC_MASK;
}


uint32_t zx_fault_dabt_is_write(uint32_t hsr)
{
    return ((zx_fault_iss(hsr) & ZX_ISS_WNR_MASK) != 0U) ? 1U : 0U;
}


/**************************************************************************/
/*  zx_fault_hvc_immediate                                                */
/**************************************************************************/

uint32_t zx_fault_hvc_immediate(uint32_t hsr)
{
    return zx_fault_iss(hsr) & ZX_HSR_HVC_IMM_MASK;
}


/**************************************************************************/
/*  zx_fault_hpfar_page                                                   */
/*                                                                        */
/*  HPFAR[31:4] is FIPA[39:12], so the 4 KB page it names is that field   */
/*  shifted up to bit 12 -- a net left shift of 8 -- with the RES0 bits    */
/*  that land in [11:8] masked away.  Masking is not belt and braces:     */
/*  HPFAR[3:0] is RES0 and reads as zero today, but a future part that    */
/*  used those bits for anything would otherwise contribute them to the   */
/*  address and produce a plausible wrong answer.                         */
/**************************************************************************/

uint32_t zx_fault_hpfar_page(uint32_t hpfar)
{
    return (hpfar << 8U) & ~(uint32_t)(ZX_HPFAR_PAGE_SIZE - 1U);
}


/**************************************************************************/
/*  zx_fault_hpfar_high                                                   */
/*                                                                        */
/*  FIPA[39:32], which no 32-bit address can carry.  Non-zero means the   */
/*  faulting address is above 4 GB and zx_fault_hpfar_page has truncated  */
/*  it -- impossible on any ZoneX target so far, and the point of         */
/*  reporting it is that a target where it is possible says so.           */
/**************************************************************************/

uint32_t zx_fault_hpfar_high(uint32_t hpfar)
{
    return hpfar >> 24U;
}


/**************************************************************************/
/*  zx_fault_hpfar_as_address                                             */
/*                                                                        */
/*  The other reading: the faulting address itself, with the low four      */
/*  bits RES0.  This is what the S32Z280 implements, and what TRM Table    */
/*  3-69's row -- "Bits [31:4] of the faulting address" -- describes.      */
/**************************************************************************/

uint32_t zx_fault_hpfar_as_address(uint32_t hpfar)
{
    return hpfar & 0xFFFFFFF0U;
}


/**************************************************************************/
/*  zx_fault_hpfar_matches_hdfar / zx_fault_hpfar_matches_as_address       */
/**************************************************************************/

uint32_t zx_fault_hpfar_matches_hdfar(uint32_t hpfar, uint32_t hdfar)
{
    uint32_t hdfar_page = hdfar & ~(uint32_t)(ZX_HPFAR_PAGE_SIZE - 1U);

    return ((zx_fault_hpfar_high(hpfar) == 0U)
            && (zx_fault_hpfar_page(hpfar) == hdfar_page)) ? 1U : 0U;
}


uint32_t zx_fault_hpfar_matches_as_address(uint32_t hpfar, uint32_t hdfar)
{
    return (zx_fault_hpfar_as_address(hpfar)
            == (hdfar & 0xFFFFFFF0U)) ? 1U : 0U;
}


/**************************************************************************/
/*  zx_fault_hpfar_reading                                                */
/*                                                                        */
/*  Which of the TRM's two mutually exclusive descriptions of HPFAR this   */
/*  target implements.  Both are tested rather than one being assumed,     */
/*  because the two ZoneX targets answer differently -- and reporting      */
/*  AMBIGUOUS when a particular faulting address cannot tell them apart is */
/*  the difference between a measurement and a coincidence.  An address    */
/*  in the first 4 KB, or one whose low twelve bits are zero, satisfies    */
/*  both readings and proves nothing.                                     */
/**************************************************************************/

zx_hpfar_reading_t zx_fault_hpfar_reading(uint32_t hpfar, uint32_t hdfar)
{
    uint32_t as_fipa    = zx_fault_hpfar_matches_hdfar(hpfar, hdfar);
    uint32_t as_address = zx_fault_hpfar_matches_as_address(hpfar, hdfar);
    zx_hpfar_reading_t result;

    if ((as_fipa != 0U) && (as_address != 0U))
    {
        result = ZX_HPFAR_AMBIGUOUS;
    }
    else if (as_fipa != 0U)
    {
        result = ZX_HPFAR_AS_FIPA;
    }
    else if (as_address != 0U)
    {
        result = ZX_HPFAR_AS_ADDRESS;
    }
    else
    {
        result = ZX_HPFAR_UNRECOGNISED;
    }

    return result;
}


/**************************************************************************/
/*  zx_fault_hpfar_reading_name                                           */
/**************************************************************************/

const char *zx_fault_hpfar_reading_name(zx_hpfar_reading_t reading)
{
    switch (reading)
    {
    case ZX_HPFAR_AS_FIPA:
        return "FIPA[39:12] at HPFAR[31:4] -- the TRM's Figure 3-32, and the "
               "A-profile shape";
    case ZX_HPFAR_AS_ADDRESS:
        return "the faulting address itself, [3:0] RES0 -- the TRM's Table "
               "3-69 row";
    case ZX_HPFAR_AMBIGUOUS:
        return "BOTH readings fit this address, so it cannot tell them apart "
               "-- fault on an address whose low 12 bits are not zero";
    case ZX_HPFAR_UNRECOGNISED:
        return "NEITHER documented reading explains the value";
    default:
        return "not a ZoneX HPFAR reading";
    }
}


/**************************************************************************/
/*  zx_fault_record_reset                                                 */
/**************************************************************************/

void zx_fault_record_reset(zx_fault_record_t *record_ptr)
{
    if (record_ptr != (zx_fault_record_t *)0)
    {
        record_ptr->zx_fault_captures  = 0U;
        record_ptr->zx_fault_vector = 0U;
        record_ptr->zx_fault_hsr    = 0U;
        record_ptr->zx_fault_hpfar  = 0U;
        record_ptr->zx_fault_hdfar  = 0U;
        record_ptr->zx_fault_hifar  = 0U;
        record_ptr->zx_fault_elr    = 0U;
        record_ptr->zx_fault_spsr   = 0U;
    }
}


/**************************************************************************/
/*  zx_fault_report                                                       */
/*                                                                        */
/*  Print everything the record holds, and print HPFAR both raw and       */
/*  decoded next to HDFAR.  Printing the decode without the raw value     */
/*  would make the decode unfalsifiable from a log, and the HPFAR         */
/*  relationship is one of the two documentary ambiguities the EL2        */
/*  bring-up work exists to close.                                        */
/**************************************************************************/

void zx_fault_report(const zx_fault_record_t *record_ptr)
{
    uint32_t         hsr;
    uint32_t         ec;
    zx_fault_class_t fault_class;

    if (record_ptr == (const zx_fault_record_t *)0)
    {
        zx_console_puts("[FAULT] no fault record was captured -- nothing to report\n");
        return;
    }

    hsr         = record_ptr->zx_fault_hsr;
    ec          = zx_fault_ec(hsr);
    fault_class = zx_fault_classify(hsr);

    zx_console_puts("\n[FAULT] ");
    zx_console_puts(zx_fault_class_name(fault_class));
    zx_console_puts("\n[FAULT] vector       ");
    zx_console_puts(zx_fault_vector_name(record_ptr->zx_fault_vector));

    if (zx_fault_vector_has_syndrome(record_ptr->zx_fault_vector) == 0U)
    {
        zx_console_puts("\n[FAULT] *** THIS VECTOR CARRIES NO SYNDROME.  Only +0x0C, +0x10\n"
                        "[FAULT] *** and +0x14 update HSR, so the HSR below is whatever the\n"
                        "[FAULT] *** last syndrome-bearing exception left in it -- STALE, not\n"
                        "[FAULT] *** wrong.  The VECTOR is the witness here.");
    }
    else if (zx_fault_vector_agrees(record_ptr->zx_fault_vector, hsr) == 0U)
    {
        zx_console_puts("\n[FAULT] *** the vector taken and HSR.EC DISAGREE, and this vector\n"
                        "[FAULT] *** does carry a syndrome -- so one of the two registers is\n"
                        "[FAULT] *** not what it is documented to be.  Do not trust either\n"
                        "[FAULT] *** until that is understood.");
    }
    else
    {
        /* They agree, which is the ordinary case and needs no line of its
           own: the report is read when something went wrong, and noise in
           it costs more than the reassurance is worth.  */
    }

    zx_console_puts("\n[FAULT] HSR          ");
    zx_console_puthex(hsr);
    zx_console_puts("  EC ");
    zx_console_puthex(ec);
    zx_console_puts(" = ");
    zx_console_puts(zx_fault_ec_name(ec));

    zx_console_puts("\n[FAULT] HSR.ISS      ");
    zx_console_puthex(zx_fault_iss(hsr));

    if ((ec == ZX_EC_DABT_ROUTED) || (ec == ZX_EC_DABT_FROM_HYP))
    {
        zx_console_puts("  DFSC ");
        zx_console_puthex(zx_fault_dabt_dfsc(hsr));
        zx_console_puts(zx_fault_dabt_is_write(hsr) != 0U ? "  on a WRITE"
                                                          : "  on a READ");
    }
    else if (ec == ZX_EC_HVC)
    {
        zx_console_puts("  HVC immediate ");
        zx_console_puthex(zx_fault_hvc_immediate(hsr));
    }
    else
    {
        /* No ISS decode is defined for this class; the raw value above is
           all there is to say, and saying more would be inventing it.  */
    }

    zx_console_puts("\n[FAULT] HDFAR        ");
    zx_console_puthex(record_ptr->zx_fault_hdfar);
    zx_console_puts("   <- the full faulting virtual address");
    zx_console_puts("\n[FAULT] HIFAR        ");
    zx_console_puthex(record_ptr->zx_fault_hifar);

    zx_console_puts("\n[FAULT] HPFAR        ");
    zx_console_puthex(record_ptr->zx_fault_hpfar);
    zx_console_puts("   raw");
    zx_console_puts("\n[FAULT]   as FIPA    ");
    zx_console_puthex(zx_fault_hpfar_page(record_ptr->zx_fault_hpfar));
    zx_console_puts("   if HPFAR[31:4] is FIPA[39:12]");
    zx_console_puts("\n[FAULT]   as address ");
    zx_console_puthex(zx_fault_hpfar_as_address(record_ptr->zx_fault_hpfar));
    zx_console_puts("   if HPFAR[31:4] is the address itself");

    if (fault_class == ZX_FAULT_GUEST_VIOLATION)
    {
        zx_console_puts("\n[FAULT] HPFAR reads as\n[FAULT]   ");
        zx_console_puts(zx_fault_hpfar_reading_name(
            zx_fault_hpfar_reading(record_ptr->zx_fault_hpfar,
                                   record_ptr->zx_fault_hdfar)));
        zx_console_puts("\n[FAULT]   The TRM describes HPFAR both ways and the two ZoneX\n"
                        "[FAULT]   targets implement DIFFERENT ones, so there is no\n"
                        "[FAULT]   portable decode.  Use HDFAR.");

        if (zx_fault_hpfar_high(record_ptr->zx_fault_hpfar) != 0U)
        {
            zx_console_puts("\n[FAULT] *** Under the FIPA reading HPFAR would report\n"
                            "[FAULT] *** FIPA[39:32] = ");
            zx_console_puthex(zx_fault_hpfar_high(record_ptr->zx_fault_hpfar));
            zx_console_puts(", above 4 GB, so the \"as FIPA\"\n"
                            "[FAULT] *** line above is TRUNCATED.");
        }
    }

    zx_console_puts("\n[FAULT] ELR_hyp      ");
    zx_console_puthex(record_ptr->zx_fault_elr);
    zx_console_puts("   <- the instruction that faulted");
    zx_console_puts("\n[FAULT] SPSR_hyp     ");
    zx_console_puthex(record_ptr->zx_fault_spsr);
    zx_console_puts("   mode ");
    zx_console_puthex(record_ptr->zx_fault_spsr & 0x1FU);
    zx_console_puts("\n[FAULT] captures     ");
    zx_console_putdec(record_ptr->zx_fault_captures);
    zx_console_puts("   every entry to EL2 is captured, yields included,\n"
                    "[FAULT]                   so this is not a fault count");
    zx_console_puts("\n");
}
