/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_guest_console.c                                   PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Tags and forwards one guest character at a time.  See the header    */
/*    for why the hypervisor owns the console and why the tag is applied   */
/*    at this end.                                                        */
/*                                                                        */
/*    Nothing here touches hardware or guest memory: the character        */
/*    arrives in a register and leaves through zx_console_puts, which the */
/*    port or the host suite provides.  That is what makes the tagging    */
/*    rules -- where a prefix goes, what happens to a line nobody         */
/*    terminated -- testable on a workstation, which is where text is     */
/*    worth testing.                                                      */
/*                                                                        */
/*  ONE PARTITION AT A TIME                                               */
/*                                                                        */
/*    The state below is a single set of variables rather than an array    */
/*    per partition, and that is a deliberate match to the rest of        */
/*    Phase 0: the excursion to EL1 cannot nest (see the note on          */
/*    zx_el2_resume_context in the port's trap handler), so exactly one   */
/*    partition can be mid-print.  A later phase that buffers each        */
/*    partition's output to keep the console off the critical path needs  */
/*    an array here, and it needs a bound on it.                          */
/*                                                                        */
/**************************************************************************/

#include "zx_guest_console.h"
#include "zx_console.h"

/* Which partition's output is being tagged, and whether one is attached at
   all.  Two variables rather than a sentinel id, because every UINT is a
   legal partition id -- including zero -- and a sentinel would make the id
   0xFFFFFFFF mean "nobody" in a system where a manifest may legitimately
   use it.  */

static UINT        zx_console_guest_attached;
static UINT        zx_console_guest_id;
static const CHAR *zx_console_guest_name;

/* Whether the next character starts a line.  The prefix is emitted lazily,
   on the first character of a line rather than after the newline that ended
   the previous one, so that a guest which prints nothing more produces no
   dangling tag.  A trailing "[P1] " with nothing after it reads as output
   that was lost.  */

static UINT        zx_console_guest_at_line_start = 1U;

/* AND WHETHER A LINE IS STILL OWED A NEWLINE.  Set by
   zx_guest_console_release when a partition hands the console back
   mid-sentence; cleared by whoever next writes, which pays for it.

   THIS EXISTS FOR A TIMING REASON AND NOT A FORMATTING ONE, and it is the
   one number in this file that was measured on silicon.  Closing the line
   EAGERLY, at the window boundary, was two characters -- CR and LF -- into
   a polled UART, on the switch path, at EL2, with FIQ masked.  Two
   characters back to back is also the exact case the board driver's
   DTF-clear guard exists for, so the pair is the write most likely to spin
   there.  With the untrusted partition storming the console, the CRITICAL
   partition's window period moved by 24,000 counts of an 8 MHz counter --
   two and a half per cent of a major frame -- while that same partition
   violating its boundary a hundred and seventeen thousand times moved it by
   sixty-nine.  Nothing a partition did through the SCHEDULE reached its
   neighbour; the hypervisor's own console driver did.

   Deferring the newline costs the same two characters, but charges them to
   whoever writes next -- inside a window that party owns -- and takes the
   console off the boundary path entirely.

   THE CHARACTER STREAM IS UNCHANGED, and that is what makes this safe: the
   newline still appears in exactly the same place relative to every other
   character, because the only thing that can follow it is a tag or a
   hypervisor message, and both go through code that closes the line first.
   What moves is WHEN it is written, not WHERE it appears.  */

static UINT        zx_console_guest_line_owed;

static UINT        zx_console_guest_characters;
static UINT        zx_console_guest_orphans;


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_guest_console_tag                                 PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Emits the prefix that says who is speaking.                         */
/*                                                                        */
/*    The id is printed even when a name is available, and in that order.  */
/*    A name is what a reader recognises; the id is what the manifest,    */
/*    the region layout and every fault report use.  Printing only the    */
/*    name would leave a reader holding a log with no way back to the     */
/*    declaration that produced it.                                       */
/*                                                                        */
/**************************************************************************/

static void zx_guest_console_close_owed_line(void)
{
    if (zx_console_guest_line_owed != 0U)
    {
        zx_console_guest_line_owed = 0U;
        zx_console_puts("\n");
    }
}


static void zx_guest_console_tag(void)
{
    /* THE DEBT IS PAID BEFORE THE TAG, by the party about to speak.  A
       partition that handed the console back mid-sentence left a line open;
       whoever opens the next one closes it first, so no two partitions ever
       share a physical line and no tag is ever written into the middle of
       one.  Same characters, same order -- and none of them on the switch
       path.  */

    zx_guest_console_close_owed_line();

    if (zx_console_guest_attached == 0U)
    {
        /* Not a formatting choice.  A character arriving with no partition
           attached means the run loop and this file disagree about what is
           executing, so the line says so instead of guessing an id.  */
        zx_console_puts("[guest, UNATTACHED -- a ZoneX bug] ");
        return;
    }

    zx_console_puts("[P");
    zx_console_putdec(zx_console_guest_id);

    if (zx_console_guest_name != (const CHAR *)0)
    {
        zx_console_puts(" ");
        zx_console_puts(zx_console_guest_name);
    }

    zx_console_puts("] ");
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_guest_console_attach                              PORTABLE C     */
/*                                                                        */
/**************************************************************************/

void zx_guest_console_attach(UINT partition_id, const CHAR *name_ptr)
{
    /* Any partial line belongs to whoever was attached before, so it is
       closed here as well as in detach.  Attaching twice without detaching
       is a caller error, and the honest response to it is to keep the two
       partitions' text on separate lines rather than to refuse.

       A line left owed by zx_guest_console_release is NOT closed here.  It
       is closed by the tag, on the incoming partition's first character --
       so a partition that is scheduled and prints nothing costs nothing,
       and the newline is charged to the window whose output needs it.  */

    if (zx_console_guest_at_line_start == 0U)
    {
        zx_console_guest_line_owed     = 0U;
        zx_console_guest_at_line_start = 1U;
        zx_console_puts("\n");
    }

    zx_console_guest_attached = 1U;
    zx_console_guest_id       = partition_id;
    zx_console_guest_name     = name_ptr;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_guest_console_detach                              PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Closes a partial line and stops tagging.                            */
/*                                                                        */
/*    A guest that faults mid-line is the normal case here rather than an */
/*    exotic one -- it is exactly when a log is read most carefully -- and */
/*    without this the hypervisor's fault report would be appended to the */
/*    guest's unfinished sentence and read as part of it.                  */
/*                                                                        */
/**************************************************************************/

void zx_guest_console_detach(void)
{
    if (zx_console_guest_at_line_start == 0U)
    {
        zx_console_guest_line_owed     = 0U;
        zx_console_guest_at_line_start = 1U;
        zx_console_puts("\n");
    }
    else
    {
        /* Nothing is open now, but an earlier RELEASE may have left a line
           owed -- and the hypervisor is the next thing to speak, which is
           precisely the case this rule exists for.  Settle it here, where
           the cost is not on any switch path: detach is called when a
           partition has left its window early or the frame has ended, and
           in both the run is about to print rather than to schedule.  */

        zx_guest_console_close_owed_line();
    }

    zx_console_guest_attached = 0U;
    zx_console_guest_name     = (const CHAR *)0;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_guest_console_release                             PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Hand the console back WITHOUT writing anything.                     */
/*                                                                        */
/*    The window-boundary version of detach, and the difference between   */
/*    them is a measured one rather than a stylistic one -- see the note  */
/*    on zx_console_guest_line_owed above.  A boundary must not write to  */
/*    a polled UART: it runs at EL2 with FIQ masked, on the path whose    */
/*    cost the whole determinism claim is about, and what it would write  */
/*    depends on what the outgoing GUEST happened to be printing.         */
/*                                                                        */
/*    Use detach, not this, wherever the hypervisor is about to speak.    */
/*    The distinction is which side of the switch the two characters are  */
/*    charged to, and both callers are in zx_frame.c a few lines apart.   */
/*                                                                        */
/**************************************************************************/

void zx_guest_console_release(void)
{
    if (zx_console_guest_at_line_start == 0U)
    {
        zx_console_guest_line_owed     = 1U;
        zx_console_guest_at_line_start = 1U;
    }

    zx_console_guest_attached = 0U;
    zx_console_guest_name     = (const CHAR *)0;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_guest_console_putc                                PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    One character, tagged if it opens a line.                            */
/*                                                                        */
/*    A carriage return is dropped rather than forwarded.  A guest that    */
/*    ends its lines with CR LF -- which a UART-oriented one reasonably     */
/*    does -- would otherwise leave a CR before every tag, and the tag     */
/*    would be overprinted on a terminal and invisible in a captured log.  */
/*    Dropping it loses nothing: the newline that follows is what ends the  */
/*    line here.                                                           */
/*                                                                        */
/**************************************************************************/

void zx_guest_console_putc(CHAR character)
{
    CHAR text[2];

    zx_console_guest_characters++;

    if (zx_console_guest_attached == 0U)
    {
        zx_console_guest_orphans++;
    }

    if (character == '\r')
    {
        return;
    }

    if (zx_console_guest_at_line_start != 0U)
    {
        zx_guest_console_tag();
        zx_console_guest_at_line_start = 0U;
    }

    text[0] = character;
    text[1] = '\0';
    zx_console_puts(text);

    if (character == '\n')
    {
        zx_console_guest_at_line_start = 1U;
    }
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_guest_console_characters                          PORTABLE C     */
/*                                                                        */
/**************************************************************************/

UINT zx_guest_console_characters(void)
{
    return zx_console_guest_characters;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_guest_console_orphans                             PORTABLE C     */
/*                                                                        */
/**************************************************************************/

UINT zx_guest_console_orphans(void)
{
    return zx_console_guest_orphans;
}


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_guest_console_reset                               PORTABLE C     */
/*                                                                        */
/**************************************************************************/

void zx_guest_console_reset(void)
{
    zx_console_guest_attached      = 0U;
    zx_console_guest_id            = 0U;
    zx_console_guest_name          = (const CHAR *)0;
    zx_console_guest_at_line_start = 1U;
    zx_console_guest_line_owed     = 0U;
    zx_console_guest_characters    = 0U;
    zx_console_guest_orphans       = 0U;
}
