/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_manifest_verify.c                                 PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The partition manifest validator: one pure function that decides    */
/*    whether a manifest describes a system the hardware can actually be  */
/*    programmed to enforce.                                              */
/*                                                                        */
/*  WHY A VALIDATOR AND NOT JUST CAREFUL MANIFESTS                        */
/*                                                                        */
/*    Almost none of what can be wrong with a manifest FAULTS.  PMSAv8-R  */
/*    has no region priority, so two enabled regions covering one address */
/*    is CONSTRAINED UNPREDICTABLE -- it aborts on the S32Z280 and might  */
/*    not elsewhere.  An under-aligned base does not fault at all: its    */
/*    low bits land on the SH, AP and XN fields and silently change the   */
/*    region's attributes.  An unmasked limit lands on AttrIndx and       */
/*    selects an unwritten MAIR byte, which reads as Device-nGnRnE --     */
/*    memory that works, slowly, and passes a careless test.  A wrong     */
/*    entry point by four bytes costs a hardware session to find.         */
/*                                                                        */
/*    So the defects worth catching are exactly the ones that produce no  */
/*    symptom.  A validator is the only place they can be caught, and it  */
/*    has to run before the regions are programmed rather than after.     */
/*                                                                        */
/*  SHAPE                                                                 */
/*                                                                        */
/*    Every condition is its own if with a single predicate.  That costs  */
/*    nothing at run time and it is what makes MC/DC coverage achievable  */
/*    later, on a codebase whose certification back end is funded.  There */
/*    are no compound predicates and no side effects inside a condition.  */
/*                                                                        */
/*    There is no goto: project policy forbids it.  The function returns  */
/*    on first failure instead, which is also the behaviour the callers   */
/*    want -- a manifest with two errors gets fixed one at a time.        */
/*                                                                        */
/**************************************************************************/

#include "zx_manifest.h"

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_manifest_fault_set                                PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Records where a failure was found, and returns its status so that   */
/*    every rule below can be one line: return zx_manifest_fault_set(...) */
/*                                                                        */
/*    Tolerates a null fault pointer, because a caller that wants only    */
/*    the status should not have to supply storage it will not read.      */
/*                                                                        */
/**************************************************************************/

static UINT zx_manifest_fault_set(ZX_MANIFEST_FAULT *fault_ptr,
                                  UINT status,
                                  UINT partition_index,
                                  UINT region_index,
                                  UINT other_partition_index,
                                  UINT other_region_index)
{
    if (fault_ptr != (ZX_MANIFEST_FAULT *)0)
    {
        fault_ptr->zx_fault_status           = status;
        fault_ptr->zx_fault_partition        = partition_index;
        fault_ptr->zx_fault_region           = region_index;
        fault_ptr->zx_fault_other_partition  = other_partition_index;
        fault_ptr->zx_fault_other_region     = other_region_index;
    }

    return status;
}

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_manifest_ranges_overlap                           PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    True when two INCLUSIVE ranges share at least one byte.             */
/*                                                                        */
/*    Two comparisons, and deliberately no arithmetic.  The tempting      */
/*    forms all compute something: a length (limit - base + 1), or an     */
/*    exclusive end (limit + 1).  Both wrap to zero for a range that      */
/*    reaches the top of the address space, and a wrapped length makes a  */
/*    real overlap look like none -- a hole in the isolation rules at the */
/*    one address where a test is least likely to look.  Comparing the    */
/*    endpoints directly cannot wrap because it never adds.               */
/*                                                                        */
/*    Adjacency is NOT overlap: a.limit + 1 == b.base is two regions      */
/*    that touch, which is legal and common -- it is how a partition's    */
/*    code and data windows sit next to each other.  With inclusive       */
/*    endpoints that falls out of the comparison rather than needing a    */
/*    special case: first_base <= second_limit is false exactly when the  */
/*    ranges are disjoint, touching or not.                               */
/*                                                                        */
/**************************************************************************/

UINT zx_manifest_ranges_overlap(zx_addr_t first_base,
                                zx_addr_t first_limit,
                                zx_addr_t second_base,
                                zx_addr_t second_limit)
{
    if (first_base > second_limit)
    {
        return 0U;
    }

    if (second_base > first_limit)
    {
        return 0U;
    }

    return 1U;
}

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_manifest_region_check                             PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Everything checkable about one region on its own: alignment, the    */
/*    ordering of its endpoints, and whether its attribute fields hold    */
/*    legal encodings that the hypervisor has actually programmed.        */
/*                                                                        */
/*    The limit test is written as "all the low bits are SET" rather      */
/*    than "limit + 1 is aligned".  They are equivalent for every value   */
/*    except the top of the address space, where limit + 1 wraps to zero  */
/*    -- which happens to be aligned, so that form gets the right answer  */
/*    by luck.  Relying on luck in an alignment check that guards an      */
/*    attribute-corrupting bug is not worth the two characters saved.     */
/*                                                                        */
/**************************************************************************/

static UINT zx_manifest_region_check(const ZX_REGION *region_ptr,
                                     const ZX_MANIFEST_ENV *env_ptr,
                                     ZX_MANIFEST_FAULT *fault_ptr,
                                     UINT partition_index,
                                     UINT region_index)
{
    if ((region_ptr->zx_region_base & (zx_addr_t)(ZX_MPU_GRANULE - 1U)) != 0U)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_BASE_UNALIGNED,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if ((region_ptr->zx_region_limit & (zx_addr_t)(ZX_MPU_GRANULE - 1U))
            != (zx_addr_t)(ZX_MPU_GRANULE - 1U))
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_LIMIT_UNALIGNED,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    /* Checked after alignment on purpose.  A region with base and limit
       transposed is far more likely to be a typo than a deliberate empty
       region, and reporting the alignment of a transposed pair first would
       send the reader to the wrong half of the line.  */
    if (region_ptr->zx_region_limit < region_ptr->zx_region_base)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_LIMIT_BELOW_BASE,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (region_ptr->zx_region_ap > ZX_AP_EL2_RO_GUEST_RO)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_BAD_AP,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (region_ptr->zx_region_xn > ZX_XN_NEVER)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_BAD_XN,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    /* SH 0b01 is UNPREDICTABLE for Normal memory, so it is rejected here
       rather than merely range-checked.  A manifest asking for it is asking
       for behaviour the architecture declines to define.  */
    if (region_ptr->zx_region_sh == 0x01U)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_BAD_SH,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (region_ptr->zx_region_sh > ZX_SH_INNER_SHAREABLE)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_BAD_SH,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if ((UINT)region_ptr->zx_region_attr_index >= ZX_ATTR_INDEX_COUNT)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_ATTR_OUT_OF_RANGE,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    /* The check the hardware cannot make.  An index inside the architectural
       range but outside what the hypervisor programmed selects a zero MAIR
       byte, which is Device-nGnRnE -- a plausible-looking attribute nobody
       asked for, on memory that still works.  */
    if ((env_ptr->zx_env_attr_written_mask
            & (1U << (UINT)region_ptr->zx_region_attr_index)) == 0U)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_ATTR_NOT_WRITTEN,
                                     partition_index, region_index,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    return ZX_MANIFEST_SUCCESS;
}

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_manifest_shared_lookup                            PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Finds the declared shared range a region EXACTLY covers, or returns */
/*    ZX_MANIFEST_NO_INDEX.                                               */
/*                                                                        */
/*    Exactly, not merely overlapping, and that is the whole point of the */
/*    function.  The cross-partition overlap rule is waived only for      */
/*    regions whose endpoints match a declared range, so a region that    */
/*    reaches one byte past a shared granule into a neighbour's memory is */
/*    still an overlap and is still rejected.  Waiving the rule for       */
/*    anything that merely touched a declared range would turn one        */
/*    published granule into a licence to overlap around it.              */
/*                                                                        */
/**************************************************************************/

static UINT zx_manifest_shared_lookup(const ZX_MANIFEST *manifest_ptr,
                                      const ZX_REGION *region_ptr)
{
    UINT index;

    for (index = 0U; index < manifest_ptr->zx_manifest_shared_count; index++)
    {
        const ZX_SHARED *shared_ptr = &manifest_ptr->zx_manifest_shared[index];

        if (region_ptr->zx_region_base != shared_ptr->zx_shared_base)
        {
            continue;
        }

        if (region_ptr->zx_region_limit != shared_ptr->zx_shared_limit)
        {
            continue;
        }

        return index;
    }

    return ZX_MANIFEST_NO_INDEX;
}

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_manifest_shared_check                             PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Checks the declared shared ranges themselves, and then checks that  */
/*    every region covering one carries the permission its owner should   */
/*    have: the publisher writable, everybody else read-only.             */
/*                                                                        */
/*    That second half is the part with teeth.  A shared range declared   */
/*    read-only whose reader was given a writable region would be a       */
/*    two-way channel described in the manifest as a one-way one, and     */
/*    nothing at run time would say so -- both partitions would simply    */
/*    work.  The declaration and the regions have to be checked against   */
/*    each other or the declaration is decoration.                        */
/*                                                                        */
/**************************************************************************/

static UINT zx_manifest_shared_check(const ZX_MANIFEST *manifest_ptr,
                                     ZX_MANIFEST_FAULT *fault_ptr)
{
    UINT shared_index;

    if (manifest_ptr->zx_manifest_shared_count > ZX_MAX_SHARED_RANGES)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_TOO_MANY_SHARED,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    for (shared_index = 0U;
         shared_index < manifest_ptr->zx_manifest_shared_count;
         shared_index++)
    {
        const ZX_SHARED *shared_ptr =
            &manifest_ptr->zx_manifest_shared[shared_index];
        UINT publisher_found = 0U;
        UINT partition_index;

        /* Exactly one granule in Phase 0.  Not an arbitrary restriction: the
           isolation claim is qualified by how much memory is shared, and a
           bound the validator enforces is worth more to a reviewer than a
           sentence saying the demonstrator only shares a little.  Relaxing
           it later is a change to this one condition, in the open.  */
        if ((shared_ptr->zx_shared_base
                & (zx_addr_t)(ZX_MPU_GRANULE - 1U)) != 0U)
        {
            return zx_manifest_fault_set(fault_ptr,
                                         ZX_MANIFEST_SHARED_NOT_ONE_GRANULE,
                                         ZX_MANIFEST_NO_INDEX, shared_index,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX);
        }

        if (shared_ptr->zx_shared_limit
                != (shared_ptr->zx_shared_base
                    + (zx_addr_t)(ZX_MPU_GRANULE - 1U)))
        {
            return zx_manifest_fault_set(fault_ptr,
                                         ZX_MANIFEST_SHARED_NOT_ONE_GRANULE,
                                         ZX_MANIFEST_NO_INDEX, shared_index,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX);
        }

        /* Every region covering the range must match its owner's role.  */
        for (partition_index = 0U;
             partition_index < manifest_ptr->zx_manifest_partition_count;
             partition_index++)
        {
            const ZX_PARTITION *partition_ptr =
                &manifest_ptr->zx_manifest_partitions[partition_index];
            UINT region_index;

            for (region_index = 0U;
                 region_index < partition_ptr->zx_partition_region_count;
                 region_index++)
            {
                const ZX_REGION *region_ptr =
                    &partition_ptr->zx_partition_regions[region_index];

                if (zx_manifest_shared_lookup(manifest_ptr, region_ptr)
                        != shared_index)
                {
                    continue;
                }

                if (partition_ptr->zx_partition_id
                        == shared_ptr->zx_shared_publisher_id)
                {
                    publisher_found = 1U;

                    if (region_ptr->zx_region_ap != ZX_AP_EL2_RW_GUEST_RW)
                    {
                        return zx_manifest_fault_set(
                            fault_ptr, ZX_MANIFEST_SHARED_BAD_AP,
                            partition_index, region_index,
                            ZX_MANIFEST_NO_INDEX, shared_index);
                    }
                }
                else
                {
                    if (region_ptr->zx_region_ap != ZX_AP_EL2_RO_GUEST_RO)
                    {
                        return zx_manifest_fault_set(
                            fault_ptr, ZX_MANIFEST_SHARED_BAD_AP,
                            partition_index, region_index,
                            ZX_MANIFEST_NO_INDEX, shared_index);
                    }
                }
            }
        }

        /* A range nobody publishes is memory two partitions can read and
           nothing writes.  Harmless, and almost certainly a mistake in the
           publisher id, which is worth saying rather than tolerating.  */
        if (publisher_found == 0U)
        {
            return zx_manifest_fault_set(fault_ptr,
                                         ZX_MANIFEST_SHARED_NO_PUBLISHER,
                                         ZX_MANIFEST_NO_INDEX, shared_index,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX);
        }
    }

    return ZX_MANIFEST_SUCCESS;
}

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_manifest_partition_check                          PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    One partition on its own: its regions individually, its regions     */
/*    against each other and against the hypervisor's MMIO, and the       */
/*    properties that make it a partition that can actually run.          */
/*                                                                        */
/*    "Can actually run" is three separate rules, and each of them was a  */
/*    real bug somewhere before it was a rule here.  A partition with no  */
/*    executable region cannot start.  One with no writable region cannot */
/*    keep a stack.  One whose entry point is outside its executable      */
/*    regions faults on its first instruction, and the four-byte version  */
/*    of that mistake is invisible in a manifest and costs a hardware     */
/*    session to find.  None of the three is a runtime mystery worth      */
/*    having when they are all decidable here.                            */
/*                                                                        */
/**************************************************************************/

static UINT zx_manifest_partition_check(const ZX_MANIFEST *manifest_ptr,
                                        const ZX_MANIFEST_ENV *env_ptr,
                                        ZX_MANIFEST_FAULT *fault_ptr,
                                        UINT partition_index)
{
    const ZX_PARTITION *partition_ptr =
        &manifest_ptr->zx_manifest_partitions[partition_index];
    UINT executable_regions = 0U;
    UINT writable_regions = 0U;
    UINT entry_is_executable = 0U;
    UINT image_fits = 0U;
    UINT region_index;
    UINT status;

    if (partition_ptr->zx_partition_regions == (const ZX_REGION *)0)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_NULL_POINTER,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (partition_ptr->zx_partition_region_count == 0U)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_NO_REGIONS,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (partition_ptr->zx_partition_region_count
            > ZX_MAX_REGIONS_PER_PARTITION)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_TOO_MANY_REGIONS,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (partition_ptr->zx_partition_image_end
            < partition_ptr->zx_partition_image_start)
    {
        return zx_manifest_fault_set(fault_ptr,
                                     ZX_MANIFEST_IMAGE_RANGE_INVALID,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    /* An image of ZERO bytes, which is a separate rule from a reversed range
       and catches a different mistake.

       A guest image reaches the hypervisor as a section pulled in with
       .incbin, and the manifest names that section's start and end symbols.
       When the linker script's input pattern matches nothing -- a pattern
       missing the object-file suffix does exactly this -- the output section
       is created EMPTY at whatever address the location counter happened to
       hold, and the two symbols come out equal.  The image then builds,
       links, reports a plausible size in the map file, and contains no
       guest; the run copies nothing and ERETs into whatever the window held.
       That failure cost real time during the Cortex-R52 Modules port work,
       and it is decidable here in one comparison.

       A partition that genuinely has no image to copy -- code already
       resident in ROM, say -- is a case Phase 0 does not have and would need
       an explicit declaration rather than an empty range, because an empty
       range is indistinguishable from the mistake above.  */

    if (partition_ptr->zx_partition_image_end
            == partition_ptr->zx_partition_image_start)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_IMAGE_EMPTY,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (partition_ptr->zx_partition_window_ticks == 0U)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_ZERO_WINDOW,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    for (region_index = 0U;
         region_index < partition_ptr->zx_partition_region_count;
         region_index++)
    {
        const ZX_REGION *region_ptr =
            &partition_ptr->zx_partition_regions[region_index];
        UINT other_index;
        UINT mmio_index;

        status = zx_manifest_region_check(region_ptr, env_ptr, fault_ptr,
                                          partition_index, region_index);

        if (status != ZX_MANIFEST_SUCCESS)
        {
            return status;
        }

        /* Against this partition's own other regions.  Only the pairs above
           this index, so each pair is tested once and the two indices in the
           report are always in ascending order.  */
        for (other_index = region_index + 1U;
             other_index < partition_ptr->zx_partition_region_count;
             other_index++)
        {
            const ZX_REGION *other_ptr =
                &partition_ptr->zx_partition_regions[other_index];

            if (zx_manifest_ranges_overlap(region_ptr->zx_region_base,
                                           region_ptr->zx_region_limit,
                                           other_ptr->zx_region_base,
                                           other_ptr->zx_region_limit) != 0U)
            {
                return zx_manifest_fault_set(fault_ptr,
                                             ZX_MANIFEST_SELF_OVERLAP,
                                             partition_index, region_index,
                                             partition_index, other_index);
            }
        }

        /* Against the hypervisor's own MMIO.  These regions stay enabled
           while a partition runs -- they are the console and the interrupt
           controller -- so a partition region overlapping one is two enabled
           regions on one address, which is the CONSTRAINED UNPREDICTABLE
           case and not a permissions question.  */
        for (mmio_index = 0U;
             mmio_index < env_ptr->zx_env_mmio_region_count;
             mmio_index++)
        {
            const ZX_REGION *mmio_ptr =
                &env_ptr->zx_env_mmio_regions[mmio_index];

            if (zx_manifest_ranges_overlap(region_ptr->zx_region_base,
                                           region_ptr->zx_region_limit,
                                           mmio_ptr->zx_region_base,
                                           mmio_ptr->zx_region_limit) != 0U)
            {
                return zx_manifest_fault_set(fault_ptr,
                                             ZX_MANIFEST_MMIO_OVERLAP,
                                             partition_index, region_index,
                                             ZX_MANIFEST_NO_INDEX,
                                             mmio_index);
            }
        }

        if (region_ptr->zx_region_xn == ZX_XN_EXECUTABLE)
        {
            executable_regions++;

            if (partition_ptr->zx_partition_entry
                    >= region_ptr->zx_region_base)
            {
                if (partition_ptr->zx_partition_entry
                        <= region_ptr->zx_region_limit)
                {
                    entry_is_executable = 1U;

                    /* THE IMAGE IS CHECKED AGAINST THIS REGION AND NO
                       OTHER, because this is the one it will be loaded
                       into: the loader copies to the base of the
                       executable region that holds the entry point.

                       The weaker rule -- "the image fits SOME executable
                       region" -- is the one this replaces, and it passes a
                       manifest whose entry sits in a small region while a
                       large one elsewhere absorbs the size.  The copy then
                       overruns the window it actually targets, into
                       whatever is next in the address space, and the first
                       symptom is a neighbouring partition behaving oddly.
                       Naming the window makes the rule mean what a reader
                       assumes it means.

                       Both subtractions are safe without a guard:
                       image_end > start was established before this loop,
                       and limit >= base by the per-region check just
                       above.  No guard is added for them on purpose -- a
                       condition that cannot be false is dead code, and
                       dead code in a function with a coverage floor is a
                       branch nobody can ever cover.

                       THE LENGTH IS REDUCED BY ONE AND THE LIMIT IS NOT,
                       and getting that backwards is worth a paragraph
                       because it was wrong here and right in the loader.
                       The limit is INCLUSIVE, so a window holds
                       limit - base + 1 bytes; a rule written as
                       length <= (limit - base) therefore refuses an image
                       that EXACTLY FILLS its window.  That is a manifest
                       the loader accepts -- zx_partition_prepare asks
                       whether (length - 1) > (limit - base) -- so the two
                       disagreed about one byte, and the disagreement had
                       the validator refusing at boot with a message saying
                       the image was too large for a window it fits
                       perfectly.  The forms are now identical on purpose:
                       the subtraction moves to the LENGTH, where it cannot
                       overflow (length >= 1 above), rather than to the
                       limit, where base + length - 1 would wrap for a
                       window reaching the top of the address space and
                       report a real overrun as a fit.  */

                    if (((partition_ptr->zx_partition_image_end
                          - partition_ptr->zx_partition_image_start) - 1U)
                            <= (region_ptr->zx_region_limit
                                - region_ptr->zx_region_base))
                    {
                        image_fits = 1U;
                    }
                }
            }
        }

        if (region_ptr->zx_region_ap == ZX_AP_EL2_RW_GUEST_RW)
        {
            writable_regions++;
        }
    }

    if (executable_regions == 0U)
    {
        return zx_manifest_fault_set(fault_ptr,
                                     ZX_MANIFEST_NO_EXECUTABLE_REGION,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (writable_regions == 0U)
    {
        return zx_manifest_fault_set(fault_ptr,
                                     ZX_MANIFEST_NO_WRITABLE_REGION,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (entry_is_executable == 0U)
    {
        return zx_manifest_fault_set(fault_ptr,
                                     ZX_MANIFEST_ENTRY_NOT_EXECUTABLE,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (image_fits == 0U)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_IMAGE_TOO_LARGE,
                                     partition_index, ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    return ZX_MANIFEST_SUCCESS;
}

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_manifest_cross_check                              PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Regions of DIFFERENT partitions against each other.                 */
/*                                                                        */
/*    Two partitions' regions are never enabled at the same time, so this */
/*    rule is not about CONSTRAINED UNPREDICTABLE the way the others are. */
/*    It is the isolation claim itself: if two partitions' regions cover   */
/*    one address then whichever partition is running can reach the       */
/*    other's memory, and the fact that only one region set is enabled at  */
/*    a time is exactly what makes that reachable rather than aborting.    */
/*    This is the rule a reviewer is really asking about.                  */
/*                                                                        */
/*    Waived only for a pair that BOTH exactly cover the same declared    */
/*    shared range.  A region matching a declared range while its partner */
/*    merely overlaps it is still a violation -- see                       */
/*    zx_manifest_shared_lookup.                                          */
/*                                                                        */
/**************************************************************************/

static UINT zx_manifest_cross_check(const ZX_MANIFEST *manifest_ptr,
                                    ZX_MANIFEST_FAULT *fault_ptr)
{
    UINT first_partition;

    for (first_partition = 0U;
         first_partition < manifest_ptr->zx_manifest_partition_count;
         first_partition++)
    {
        const ZX_PARTITION *first_ptr =
            &manifest_ptr->zx_manifest_partitions[first_partition];
        UINT second_partition;

        for (second_partition = first_partition + 1U;
             second_partition < manifest_ptr->zx_manifest_partition_count;
             second_partition++)
        {
            const ZX_PARTITION *second_ptr =
                &manifest_ptr->zx_manifest_partitions[second_partition];
            UINT first_region;

            for (first_region = 0U;
                 first_region < first_ptr->zx_partition_region_count;
                 first_region++)
            {
                const ZX_REGION *first_region_ptr =
                    &first_ptr->zx_partition_regions[first_region];
                UINT first_shared =
                    zx_manifest_shared_lookup(manifest_ptr, first_region_ptr);
                UINT second_region;

                for (second_region = 0U;
                     second_region < second_ptr->zx_partition_region_count;
                     second_region++)
                {
                    const ZX_REGION *second_region_ptr =
                        &second_ptr->zx_partition_regions[second_region];
                    UINT second_shared;

                    if (zx_manifest_ranges_overlap(
                            first_region_ptr->zx_region_base,
                            first_region_ptr->zx_region_limit,
                            second_region_ptr->zx_region_base,
                            second_region_ptr->zx_region_limit) == 0U)
                    {
                        continue;
                    }

                    second_shared = zx_manifest_shared_lookup(
                        manifest_ptr, second_region_ptr);

                    if (first_shared == ZX_MANIFEST_NO_INDEX)
                    {
                        return zx_manifest_fault_set(
                            fault_ptr, ZX_MANIFEST_PARTITION_OVERLAP,
                            first_partition, first_region,
                            second_partition, second_region);
                    }

                    if (first_shared != second_shared)
                    {
                        return zx_manifest_fault_set(
                            fault_ptr, ZX_MANIFEST_PARTITION_OVERLAP,
                            first_partition, first_region,
                            second_partition, second_region);
                    }
                }
            }
        }
    }

    return ZX_MANIFEST_SUCCESS;
}

/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    zx_manifest_verify                                   PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Checks a manifest against every rule and returns the first failure. */
/*                                                                        */
/*    The order the rules run in is chosen so that the FIRST message a    */
/*    reader gets is the most useful one.  Structural checks come before  */
/*    content checks, because a null pointer reported as an alignment     */
/*    error sends the reader to the wrong place entirely.  Per-partition  */
/*    checks come before cross-partition ones, because an overlap between */
/*    two partitions is much harder to read than an unaligned base in one */
/*    of them, and fixing the alignment sometimes removes the overlap.    */
/*    The region budget is checked last: it is the only rule that depends */
/*    on the hardware, and reporting "this needs more regions than the    */
/*    part has" about a manifest that is also malformed is misleading.    */
/*                                                                        */
/**************************************************************************/

UINT zx_manifest_verify(const ZX_MANIFEST *manifest_ptr,
                        const ZX_MANIFEST_ENV *env_ptr,
                        ZX_MANIFEST_FAULT *fault_ptr)
{
    UINT regions_needed;
    UINT partition_index;
    UINT status;

    if (manifest_ptr == (const ZX_MANIFEST *)0)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_NULL_POINTER,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (env_ptr == (const ZX_MANIFEST_ENV *)0)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_NULL_POINTER,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (manifest_ptr->zx_manifest_partitions == (const ZX_PARTITION *)0)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_NULL_POINTER,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    /* A shared-range array is optional; a count without one is not.  */
    if (manifest_ptr->zx_manifest_shared_count != 0U)
    {
        if (manifest_ptr->zx_manifest_shared == (const ZX_SHARED *)0)
        {
            return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_NULL_POINTER,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX);
        }
    }

    /* Likewise for the hypervisor's MMIO list: zero regions is the FVP's
       honest answer, a count with no array is a caller bug.  */
    if (env_ptr->zx_env_mmio_region_count != 0U)
    {
        if (env_ptr->zx_env_mmio_regions == (const ZX_REGION *)0)
        {
            return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_NULL_POINTER,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX);
        }
    }

    if (manifest_ptr->zx_manifest_partition_count == 0U)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_NO_PARTITIONS,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    if (manifest_ptr->zx_manifest_partition_count > ZX_MAX_PARTITIONS)
    {
        return zx_manifest_fault_set(fault_ptr,
                                     ZX_MANIFEST_TOO_MANY_PARTITIONS,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    /* Identifiers must be unique, because everything else keys off them --
       the shared ranges name a publisher by id, and a scheduler will name a
       partition by id.  Two partitions sharing one id makes both of those
       silently pick whichever comes first.  */
    for (partition_index = 0U;
         partition_index < manifest_ptr->zx_manifest_partition_count;
         partition_index++)
    {
        UINT other_index;

        for (other_index = partition_index + 1U;
             other_index < manifest_ptr->zx_manifest_partition_count;
             other_index++)
        {
            if (manifest_ptr->zx_manifest_partitions[partition_index]
                    .zx_partition_id
                == manifest_ptr->zx_manifest_partitions[other_index]
                    .zx_partition_id)
            {
                return zx_manifest_fault_set(fault_ptr,
                                             ZX_MANIFEST_DUPLICATE_ID,
                                             partition_index,
                                             ZX_MANIFEST_NO_INDEX,
                                             other_index,
                                             ZX_MANIFEST_NO_INDEX);
            }
        }
    }

    for (partition_index = 0U;
         partition_index < manifest_ptr->zx_manifest_partition_count;
         partition_index++)
    {
        status = zx_manifest_partition_check(manifest_ptr, env_ptr, fault_ptr,
                                             partition_index);

        if (status != ZX_MANIFEST_SUCCESS)
        {
            return status;
        }
    }

    status = zx_manifest_shared_check(manifest_ptr, fault_ptr);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        return status;
    }

    status = zx_manifest_cross_check(manifest_ptr, fault_ptr);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        return status;
    }

    /* The major frame is the sum of the windows.  Carried in the manifest
       AND checked, rather than computed, so that a manifest whose frame
       disagrees with its parts is an error the author gets told about
       instead of a number that quietly follows whatever the windows say.  */
    {
        ULONG frame_total = 0U;

        for (partition_index = 0U;
             partition_index < manifest_ptr->zx_manifest_partition_count;
             partition_index++)
        {
            frame_total += manifest_ptr->zx_manifest_partitions[partition_index]
                               .zx_partition_window_ticks;
        }

        if (frame_total != manifest_ptr->zx_manifest_major_frame_ticks)
        {
            return zx_manifest_fault_set(fault_ptr,
                                         ZX_MANIFEST_FRAME_MISMATCH,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX,
                                         ZX_MANIFEST_NO_INDEX);
        }
    }

    /* Last, and the only rule that depends on the part.  The model reports
       32 EL2 regions, which is not an architecturally legal Cortex-R52
       value, so a manifest that fits the model proves nothing about any real
       device -- which is exactly why this is checked against the register
       rather than against a constant.  */
    regions_needed = env_ptr->zx_env_mmio_region_count;

    for (partition_index = 0U;
         partition_index < manifest_ptr->zx_manifest_partition_count;
         partition_index++)
    {
        regions_needed += manifest_ptr->zx_manifest_partitions[partition_index]
                              .zx_partition_region_count;
    }

    if (regions_needed > env_ptr->zx_env_region_budget)
    {
        return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_REGION_BUDGET,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX,
                                     ZX_MANIFEST_NO_INDEX);
    }

    return zx_manifest_fault_set(fault_ptr, ZX_MANIFEST_SUCCESS,
                                 ZX_MANIFEST_NO_INDEX, ZX_MANIFEST_NO_INDEX,
                                 ZX_MANIFEST_NO_INDEX,
                                 ZX_MANIFEST_NO_INDEX);
}
