/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_mm_setup.c                                        PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Stage-2 memory setup: translating the manifest's memory             */
/*    declarations into MPU region descriptors, and enabling the set      */
/*    belonging to the partition about to run.                            */
/*                                                                        */
/*    This translation unit is deliberately empty of implementation.      */
/*    The change that founded this repository builds the repository, not  */
/*    the hypervisor; the unit exists so that the change which writes the */
/*    code opens a tree that already configures, compiles and links.      */
/*                                                                        */
/**************************************************************************/

#include "zx_mm.h"
