/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_frame_setup.h                                        SHARED      */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The one routine every image that runs a major frame calls before it */
/*    starts one.  Why it is shared rather than copied, and which of its  */
/*    checks exist because something went wrong once, is in               */
/*    zx_frame_setup.c.                                                   */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_FRAME_SETUP_H
#define ZX_FRAME_SETUP_H

#include "zx_port.h"

#ifdef __cplusplus
extern "C" {
#endif

/* THE COUNTER, then the GIC, then the two interrupts -- one for the
 * partitions and one for the hypervisor -- and then the ROUTING, and then
 * EL2's own CPU interface.  In that order, because several steps of it fail
 * SILENTLY on their own and the last two only matter once the ones before
 * have changed where a guest's own writes go.
 *
 * `enable_hyp_tick` is zero in exactly one build, which deliberately leaves
 * the hypervisor's own timer PPI disabled at the GIC so that no window can
 * end.  That build is what makes every preemption claim in this suite
 * evidence rather than observation, and it is an argument rather than a
 * compile-time test inside the shared file because the negative build
 * belongs to one image.
 *
 * Returns non-zero when all three things a window boundary depends on are in
 * place: the counter is moving, the redistributor is awake, and the
 * hypervisor's own tick is deliverable.  ONE answer, so that the caller has
 * one decision to make -- and the caller's decision is to REFUSE rather than
 * to start a frame whose windows could never end, because a frame started in
 * that state does not fail, it HANGS.  */

ZX_NODISCARD uint32_t zx_frame_grant_the_clocks(ZX_GIC_LAYOUT *gic_ptr,
                                                uint32_t guest_timer_priority,
                                                uint32_t enable_hyp_tick);

#ifdef __cplusplus
}
#endif

#endif /* ZX_FRAME_SETUP_H */
