/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_guest_launch.h                                      SHARED       */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Everything two example images do IDENTICALLY when they launch a     */
/*    real ThreadX guest: check the image's header, copy it into the      */
/*    window, write the handover mailbox, run one excursion, and read the */
/*    guest's sealed report back afterwards.                              */
/*                                                                        */
/*  WHY THIS IS A FILE AND NOT A COPY                                     */
/*                                                                        */
/*    Two experiments now launch the same guest: one shows a kernel       */
/*    confined by stage 2 and stopped at its boundary, the other shows a  */
/*    PREEMPTIVE kernel with a timer interrupt of its own.  They differ   */
/*    in what the hypervisor CONFIGURES and in what they claim -- not in  */
/*    how a guest is loaded.                                              */
/*                                                                        */
/*    Copying the loader into the second image would have been shorter to */
/*    write and would have created the failure this suite is least able   */
/*    to catch: two loaders that agree today, one of them fixed later,    */
/*    and an isolation claim still being made by the other.  The mailbox  */
/*    layout, the header check and the seal are a CONTRACT with the guest */
/*    image, and a contract with two implementations has two versions.    */
/*                                                                        */
/*  WHAT IS DELIBERATELY *NOT* HERE                                       */
/*                                                                        */
/*    The manifest.  Each image declares its own, because the manifest is */
/*    the statement of what the experiment grants -- windows, attributes, */
/*    how many partitions -- and that is the experiment rather than its   */
/*    plumbing.  Sharing it would make the two images agree about the one */
/*    thing they most need to be able to differ about.                    */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_GUEST_LAUNCH_H
#define ZX_GUEST_LAUNCH_H

#include "zx_api.h"
#include "zx_partition.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************/
/*  ZX_GUEST_LAUNCH -- where one partition's guest lives.                 */
/*                                                                        */
/*  Four addresses and a sentinel, all of them known to the image from    */
/*  its own linker script.  Passed as a structure rather than read from   */
/*  linker symbols in this file, because these symbols are named by the   */
/*  EXAMPLE's linker script and a shared translation unit that referred   */
/*  to them by name could only ever serve one example.                    */
/**************************************************************************/

typedef struct ZX_GUEST_LAUNCH_STRUCT
{
    /* The partition window: where the guest is copied to and runs.  */
    zx_addr_t   zx_launch_window_base;
    zx_addr_t   zx_launch_window_end;       /* one past the last byte      */

    /* The embedded blob, in the hypervisor's own memory.  */
    zx_addr_t   zx_launch_image_start;
    zx_addr_t   zx_launch_image_end;

    /* What the hypervisor plants in the guest's mailbox, and which the
       guest folds into every checksum -- so a report read out of the WRONG
       window is detectable rather than merely unlucky.  */
    uint32_t    zx_launch_sentinel;

    /* The partition this guest belongs to, as the hypervisor knows it.
       The console tag comes from HERE and never from the guest, so a guest
       cannot claim to be another partition.  */
    uint32_t    zx_launch_partition_id;
    const char *zx_launch_partition_name;

    /* WHETHER TO GIVE THIS PARTITION BACK THE TIME IT SPENT DESCHEDULED.
       Non-zero is the only setting a hypervisor would ever ship, and the
       field exists so that a build can turn the mechanism off and
       demonstrate what that costs.
     *
     * It gates the CORRECTION -- the CNTVOFF write on the way back in --
     * and not the bookkeeping that records when the partition stopped.
     * That split is deliberate: the bookkeeping is what the CHECK is
     * measured against, so switching it off too would move the measurement
     * instead of breaking the mechanism, and a negative build has to break
     * the mechanism.
     *
     * A claim whose pass condition is "the guest could not tell it was
     * descheduled" has to be capable of failing, or a green run shows only
     * that the arithmetic did not crash.  With this clear, the partition's
     * clock counts every cycle the hypervisor spent between two excursions
     * and the run reports FAILED -- which is what makes the positive run
     * evidence.  See docs/decisions.md D7.  */
    uint32_t    zx_launch_freeze_time;

} ZX_GUEST_LAUNCH;

/**************************************************************************/
/*  The mailbox, as the hypervisor sees it.                               */
/*                                                                        */
/*  EL2 can read and write a partition's memory because stage-2 AP cannot  */
/*  deny EL2 (docs/decisions.md D3) -- the same property that stops AP     */
/*  from isolating partitions is what makes a hypervisor-to-guest mailbox  */
/*  free.  It is at a fixed offset in the window rather than passed in a   */
/*  register because a real kernel's reset path clobbers r0 long before    */
/*  any of its C runs.                                                    */
/**************************************************************************/

ZX_NODISCARD uint32_t zx_guest_mailbox_read(const ZX_GUEST_LAUNCH *launch_ptr,
                                            uint32_t offset);

void zx_guest_mailbox_write(const ZX_GUEST_LAUNCH *launch_ptr,
                            uint32_t offset, uint32_t value);

/* THE CHECK THAT CATCHES A GUEST BUILT FOR SOMEWHERE ELSE.  Reads the
   header out of the SOURCE blob and not out of the window: the point is to
   refuse before anything is copied, and a check performed on the copy would
   already have overwritten whatever was there.  Reports what it found and
   returns non-zero only if every field agrees.  */

ZX_NODISCARD uint32_t zx_guest_image_check(const ZX_GUEST_LAUNCH *launch_ptr);

/* Copy the image into the window, then make the instruction side see it.  */

void zx_guest_image_load(const ZX_PARTITION_LOAD *load_ptr);

/* What the hypervisor tells the guest before it runs.  AFTER the copy,
   never before: the mailbox is a LOADED section in the guest image, zeroed
   by the copy, so a handover written first would be copied over.  */

void zx_guest_hand_over(const ZX_GUEST_LAUNCH *launch_ptr,
                        uint32_t probe_target, uint32_t options);

/* One excursion, measured in PMU cycles.  Returns ZX_RUN_*.  */

ZX_NODISCARD uint32_t zx_guest_run(const ZX_GUEST_LAUNCH *launch_ptr,
                                   ZX_PARTITION_CB *partition_ptr,
                                   uint32_t *cycles_ptr);

/* Read the guest's report back and say whether it is SEALED -- the
   sequence advanced and the checksum agrees, with the hypervisor's own
   sentinel folded into it.  Returns the progress bits.  */

ZX_NODISCARD uint32_t zx_guest_report(const ZX_GUEST_LAUNCH *launch_ptr);

#ifdef __cplusplus
}
#endif

#endif /* ZX_GUEST_LAUNCH_H */
