/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_guest_abi.h                                       EXAMPLE        */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The contract between the hypervisor and a guest image: where each   */
/*    entry point sits, and what each word of the readback mailbox means. */
/*                                                                        */
/*    TWO KINDS OF GUEST SHARE THIS FILE, and the difference is worth      */
/*    stating before either section is read.                              */
/*                                                                        */
/*      * The RELOCATABLE BLOB -- a few dozen instructions, assembled     */
/*        once and copied into two partitions, which is what makes "set   */
/*        A denies B and set B denies A" demonstrable.  Its entry points  */
/*        are at fixed offsets and it reaches its data through a base     */
/*        pointer handed to it in r0.                                     */
/*      * A REAL KERNEL IMAGE -- a whole ThreadX, linked for one          */
/*        partition's window, which owns its own vectors, stacks and      */
/*        stage-1 MPU.  It cannot take a base pointer in r0, because its  */
/*        reset path clobbers r0 long before any C runs, so its mailbox   */
/*        is at a FIXED OFFSET IN ITS OWN WINDOW that both sides know.    */
/*                                                                        */
/*    The mailbox layout is shared between them deliberately: one         */
/*    vocabulary for "what a partition reported" means one reader at the  */
/*    hypervisor end, whichever kind of guest produced it.                */
/*                                                                        */
/*  WHY A RELOCATABLE BLOB AT ALL                                         */
/*                                                                        */
/*    Two partitions have to run the same program in DIFFERENT memory, or */
/*    "set A denies B and set B denies A" cannot be demonstrated -- one   */
/*    of the two halves would have no code to execute.  The blob is       */
/*    therefore assembled once, kept in the hypervisor's own memory, and  */
/*    COPIED into each partition's code window at boot.  That is the same */
/*    path a real guest image takes, which is why the manifest's          */
/*    image_start and image_end are load-bearing here rather than         */
/*    decorative.                                                         */
/*                                                                        */
/*    Relocatable, not position-independent-by-arithmetic.  The blob       */
/*    reaches its data through a BASE POINTER the hypervisor hands it in   */
/*    r0, not through PC-relative address computation, so there is no      */
/*    relocation to apply and no literal pool holding an absolute address. */
/*    Branches inside the blob are already PC-relative and survive the     */
/*    copy untouched; a literal pool holding a CONSTANT survives too.      */
/*    The one thing that cannot survive is a literal holding an ADDRESS,   */
/*    and that is precisely what the base pointer removes.                 */
/*                                                                        */
/*  WHY THE OFFSETS ARE FIXED CONSTANTS                                    */
/*                                                                        */
/*    The hypervisor computes an entry point as window_base + offset, so  */
/*    it needs the offsets at compile time.  Exporting them as link-time   */
/*    symbols would work and would be silently wrong the first time an     */
/*    entry grew past its slot; declaring them here and having the         */
/*    assembler ASSERT each one fits fails the build instead.  See the     */
/*    .if/.error guards in zx_payload.S.                                   */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_GUEST_ABI_H
#define ZX_GUEST_ABI_H

/**************************************************************************/
/*                    Entry points, as blob offsets                      */
/**************************************************************************/

/* Offset 0 is the EL1 vector table, so VBAR is simply the window base.
   Eight AArch32 vectors of four bytes each need 32; the slot is 64 so the
   first entry point starts on a granule boundary and the map file reads
   as the region layout rather than as an accident of instruction count.  */
#define ZX_GUEST_OFF_VECTORS        0x000U

/* Writes a sentinel into its own data window and reads it back.  Both
   halves matter: a write that went nowhere and a read returning a stale
   value are different failures, and only the comparison separates them
   from success.  */
#define ZX_GUEST_OFF_GRANT          0x040U

/* Reads the address the hypervisor left in ZX_GD_TARGET.  Used against
   the OTHER partition's memory, and against the ungranted granule next
   door to a granted one.  */
#define ZX_GUEST_OFF_PROBE          0x080U

/* Publishes a value into the shared granule.  Only the publisher can do
   this; a reader attempting it takes a stage-2 permission fault, which is
   itself one of the checks.  */
#define ZX_GUEST_OFF_PUBLISH        0x0C0U

/* Reads the shared granule.  Every partition may do this.  */
#define ZX_GUEST_OFF_CONSUME        0x100U

/* Total size the blob occupies.  The assembler checks it.  */
#define ZX_GUEST_BLOB_SIZE          0x140U

/**************************************************************************/
/*                   The partition's data window                          */
/**************************************************************************/

/* Offsets from the base pointer the hypervisor passes in r0.
 *
 * This is a MAILBOX and not a parameter list, and the difference matters:
 * zx_el2_run_payload passes exactly one argument, while a probe needs both
 * somewhere to report and something to aim at.  The hypervisor can write
 * this window because stage-2 AP cannot deny EL2 (D3) -- so the same
 * property that stops AP from isolating partitions is what makes a
 * hypervisor-to-guest mailbox free.  */

#define ZX_GD_PROGRESS              0x00U   /* guest writes, EL2 reads      */
#define ZX_GD_SCRATCH               0x04U   /* the guest's own sentinel     */
#define ZX_GD_TARGET                0x08U   /* EL2 writes: what to probe    */
#define ZX_GD_PROBED                0x0CU   /* guest writes: what it read   */
#define ZX_GD_SHARED                0x10U   /* EL2 writes: shared granule   */
#define ZX_GD_PUBLISH_VALUE         0x14U   /* EL2 writes: what to publish  */

/* THE SAME WORD, UNDER A SECOND NAME, for a kernel guest.
 *
 * A kernel guest has no publisher role -- the shared granule and its
 * heartbeat belong to the relocatable blob, which is what needs two
 * partitions running the same code.  So this word is free at that end, and
 * it carries run options instead.
 *
 * Two names for one offset is worth one sentence of explanation and no more:
 * each has exactly one reader, and both are in this file where a reader of
 * either can see the other.  It is also the LAST alias in this layout: the
 * kernel guest's later fields went into a second granule instead, and the
 * note there says why one alias is explicable and six would not be.  */

#define ZX_GD_OPTIONS               0x14U   /* EL2 writes: ZX_GO_*          */

/* ZX_GO_QUIET exists so that "what does stage 2 cost a guest" can be
   measured at all.
 *
 * The guest's console is one hypercall PER CHARACTER through a polled UART,
 * which on silicon is several million cycles for a few hundred lines -- three
 * orders of magnitude more than everything else the guest does.  A run with
 * the console on cannot resolve the cost of stage 2 from noise; it can only
 * bound it from above, which is a different and much weaker statement.
 *
 * So the measured passes run quiet and the demonstration pass runs loud.
 * Both are the same guest image: the option is a word in the mailbox, not a
 * build, precisely so that the run being measured is the run being
 * demonstrated.  */

#define ZX_GO_QUIET                 0x00000001U

/* ZX_GO_TICK asks the guest to run PREEMPTIVELY: to bring up its own GICv3
 * CPU interface, arm the virtual timer the hypervisor granted it, and run the
 * checks that only a kernel with a tick can pass.
 *
 * IT IS A MAILBOX WORD AND NOT A BUILD OPTION, and that is the whole point.
 * The image is built once, with the port's own IRQ path linked in, and the
 * hypervisor decides per excursion whether a partition gets a clock.  So the
 * cooperative run and the preemptive run are literally the same bytes, and
 * "the kernel that boots under stage 2" and "the kernel that is preempted
 * under stage 2" cannot drift apart into two binaries where only one of them
 * is the one being demonstrated.
 *
 * With the bit CLEAR the guest touches no interrupt controller and arms no
 * timer at all -- its IRQ vector is installed and simply never taken -- which
 * is what keeps a cooperative excursion exactly as cheap, and exactly as
 * measurable, as it was before a tick existed.  */

#define ZX_GO_TICK                  0x00000002U

/* ZX_GO_FOREVER asks the guest NOT to hand the machine back when it has
 * finished its programme, and it is what makes a MAJOR FRAME demonstrable.
 *
 * A guest that yields is a guest that has finished.  With one partition that
 * was exactly the right ending -- the hypervisor took the core back, read
 * the sealed report and printed it.  With a frame it is the wrong one: a
 * schedule can only be shown to preempt partitions that are still trying to
 * run, and a partition that stopped after its first window would spend every
 * later window being politely idled through.
 *
 * So with this bit set the guest keeps working after its verdict: it stays
 * runnable, keeps taking its own ticks, and keeps republishing its tick count
 * and its own virtual counter into the mailbox.  The hypervisor then reads,
 * at the end of the run, what each partition's clock did -- which is the
 * evidence for the claim the whole step exists to make.
 *
 * The verdict is published BEFORE the endless phase begins, so a run that is
 * stopped at any point afterwards still carries a sealed report.  */

#define ZX_GO_FOREVER               0x00000004U

/* ZX_GO_HOG asks the guest to be as uncooperative as an EL1 program can be:
 * after its verdict it masks IRQ and FIQ at EL1 and spins for ever, making
 * no kernel call and giving nothing back.
 *
 * IT IS THE DEMONSTRATION AND NOT A HAZARD, and the distinction is the whole
 * design.  With HCR.FMO set, PSTATE.F is IGNORED at EL0 and EL1 -- so the
 * interrupt that ends this partition's window is delivered to EL2 whatever
 * the guest has masked, and there is nothing a partition can do about it.
 * Masking its own IRQ costs it only its own kernel's tick.
 *
 * A run of this build must therefore look exactly like a run without it,
 * except that the hogging partition stops ticking.  If the frame were driven
 * by an interrupt taken at EL1 instead, this build would hang -- which is
 * why it exists as a build rather than as a paragraph.  */

#define ZX_GO_HOG                   0x00000008U

/* THE READBACK CONVENTION, and why it is a structure rather than one word.
 *
 * A single progress word is enough to say "the guest got somewhere".  It is
 * not enough for a regression to BELIEVE what it read, and three separate
 * failures make that difference concrete:
 *
 *   * A window nobody ever wrote reads as zero, and zero is a perfectly
 *     plausible progress value.  "The guest never started" and "the guest
 *     started and reported nothing" are different diagnoses.
 *   * A run that reads a partition's memory AFTER the fact attributes the
 *     last writer's value to everyone who shared the address.  That cost a
 *     wrong conclusion during the Cortex-R52 Modules port work, where a
 *     progress word in a shared granule was read back as one module's when
 *     it was another's.
 *   * A guest torn off mid-update -- descheduled, or faulted -- leaves a
 *     half-written set of words that is individually valid and jointly
 *     nonsense.
 *
 * So the guest publishes a SEQUENCE it increments on every update and a
 * CHECKSUM over everything it reported, and the sentinel that identifies
 * which partition wrote it is folded INTO that checksum.  A reader then has
 * three independent things to check: the sequence advanced, the checksum
 * agrees, and the identity inside it is the partition it thinks it is
 * reading.  Cheap for a guest -- one add per field -- and it is what lets a
 * later determinism regression compare two runs rather than merely observe
 * one.
 *
 * The order matters at the guest end and is stated where it is implemented:
 * every reported field is written BEFORE the sequence, and the sequence
 * before the checksum, so a torn update fails the checksum instead of
 * passing with stale content.  */

#define ZX_GD_SEQUENCE              0x18U   /* guest writes: update count   */
#define ZX_GD_CHECKSUM              0x1CU   /* guest writes: over the above */
#define ZX_GD_TICKS                 0x20U   /* guest writes: its own ticks  */
#define ZX_GD_THREAD_A              0x24U   /* guest writes: thread A count */
#define ZX_GD_THREAD_B              0x28U   /* guest writes: thread B count */
#define ZX_GD_MESSAGES              0x2CU   /* guest writes: queue traffic  */
#define ZX_GD_VERDICT               0x30U   /* guest writes: ZX_GV_*        */

/* What the guest's OWN vectors saw, when a stage-1 fault took it.
 *
 * A stage-1 fault never reaches EL2 -- that is the whole difference between
 * the two stages, and it is what makes them distinguishable in a log -- so
 * the only way the hypervisor learns of one is if the guest tells it.  These
 * two words are DFSR and DFAR as the guest's abort handler read them, and
 * they are the evidence that the guest's own MPU is live underneath stage 2
 * rather than merely programmed.  */

#define ZX_GD_FAULT_STATUS          0x34U   /* guest writes: its own DFSR    */
#define ZX_GD_FAULT_ADDRESS         0x38U   /* guest writes: its own DFAR    */
#define ZX_GD_STAGE1                0x3CU   /* guest writes: ZX_GS_* vector  */

/* THESE THREE WORDS ARE DELIBERATELY OUTSIDE THE CHECKSUM, and the reason is
   who writes them.  They are written by the guest's own exception vector,
   which runs with no stack, no literal pool beyond the mailbox address, and
   an obligation to disturb as little as possible -- computing a checksum
   there would be absurd.  So the sealed snapshot covers what a THREAD
   reported, and these carry what a HANDLER saw afterwards.

   That is not a hole.  ZX_GD_STAGE1 is a single word naming which vector
   fired, so a torn write of the three leaves it zero and the hypervisor
   reads "no stage-1 fault" rather than a half-described one.  */

/**************************************************************************/
/*             THE SECOND GRANULE: what a PREEMPTIVE guest reports         */
/**************************************************************************/

/* WHY THE MAILBOX IS TWO GRANULES AND NOT ONE.
 *
 * The words above fill sixteen exactly, and a guest with a timer of its own
 * has six more things to say.  Widening the mailbox costs one thing and not
 * the thing it looks like it should cost: the guest's stage-1 MPU region for
 * the mailbox goes from 64 bytes to 128, and NOTHING at stage 2 changes,
 * because the partition window is one region covering the whole of it.  It
 * does move the entry branch, which is why ZX_GUEST_IMAGE_OFF_ENTRY below is
 * a compile-time constant every linker script asserts.  (It has since grown
 * a THIRD granule, for the isolation matrix; the note there says what that
 * cost and why the alternative was refused a second time.)
 *
 * The alternative -- overloading words that a kernel guest happens not to use
 * -- was rejected after ZX_GD_OPTIONS.  One alias, with one reader at each
 * end and both spellings in this file, is explicable.  Six would be a layout
 * that only makes sense to whoever wrote it.
 *
 * THESE SIX ARE OUTSIDE THE SEALED SNAPSHOT, and for the same reason the
 * stage-1 words are: four of them are written by the guest's TIMER INTERRUPT
 * HANDLER, which runs on every tick and must not compute a checksum, and the
 * other two are written by threads that never yield and so could not order
 * their writes against a seal either.
 *
 * That is not a hole in the evidence, because the claims do not rest on
 * them.  "The tick advanced" is ZX_GD_TICKS, which is tx_time_get() and is
 * INSIDE the seal; "a thread was preempted" and "two threads were time
 * sliced" are progress BITS, and progress is inside the seal too.  The six
 * words below are the detail that makes a FAILING run diagnosable -- which
 * INTID actually arrived, how many times, and how far each spinner got --
 * and a run that fails is exactly the run where a checksum would be
 * least informative anyway.  */

#define ZX_GD_IRQ_COUNT             0x40U   /* handler: interrupts serviced */
#define ZX_GD_TIMER_INTID           0x44U   /* handler: the INTID it saw    */
#define ZX_GD_ODD_INTID             0x48U   /* handler: any OTHER INTID     */
#define ZX_GD_SPIN_A                0x4CU   /* spinner A's loop count       */
#define ZX_GD_SPIN_B                0x50U   /* spinner B's loop count       */
#define ZX_GD_WAKES                 0x54U   /* times the sleeper woke       */

/* WHAT A GUEST REPORTS WHILE IT IS STILL RUNNING, which is the other half
 * of the temporal claim.
 *
 * The sealed snapshot says what a partition ACHIEVED.  These four say what
 * its clock did, and they are refreshed continuously by the endless phase
 * ZX_GO_FOREVER asks for -- so the hypervisor can read them at the end of a
 * run and compare each partition's own elapsed time against the windows it
 * was actually given.
 *
 * THE COMPARISON IS THE POINT AND IT ONLY WORKS FROM BOTH SIDES.  ZoneX
 * knows how much of the physical counter each partition spent on the core;
 * only the guest can say what its OWN counter did over the same span.  A
 * partition whose virtual time matched WALL CLOCK rather than its own
 * windows would be a partition that could see its neighbour's time, and it
 * is precisely the failure that leaves a system running perfectly while
 * lying about time.
 *
 * OUTSIDE THE SEAL, like the rest of this granule, because they are written
 * by a loop that must not stop to checksum anything.  Nothing rests on them
 * that the sealed words do not also carry: ZX_GD_TICKS is tx_time_get() and
 * IS sealed, and these are the running version of it plus the counter
 * underneath.
 *
 * LOW HALVES ONLY.  At the S32Z280's 8 MHz a 32-bit virtual count wraps in
 * nine minutes and a frame demonstration is seconds long, so the low half is
 * both sufficient and honest about what it is -- see guest_virtual_count.  */

#define ZX_GD_LIVE                  0x5CU   /* the endless loop's own count */
#define ZX_GD_VCT_START             0x60U   /* CNTVCT when the guest began  */
#define ZX_GD_VCT_NOW               0x64U   /* CNTVCT, refreshed            */
#define ZX_GD_TICKS_NOW             0x68U   /* tx_time_get(), refreshed     */

/* 0x6C to 0x7C are spare, and are zeroed by the handover like everything
   else.  A word nobody wrote reads as whatever the image was built with,
   which for a loaded, zero-filled section is zero -- but only until somebody
   changes the section, so the handover writes them rather than relying on
   it.  */

/* A WORD THAT MEANS NOTHING, ON PURPOSE.
 *
 * One build asks the guest to probe an address it genuinely IS granted, so
 * that a check whose pass condition is the absence of something can be seen
 * to fail.  Somewhere inside the partition is the obvious target and the
 * mailbox is the obvious part of it -- but the probe WRITES a sentinel to
 * whatever it is aimed at, so aiming it at a word the guest reports through
 * corrupts the report.
 *
 * That was not hypothetical and it was not harmless.  The target was mailbox
 * offset zero, which is ZX_GD_PROGRESS, so the sentinel 0xA5A50001 was ORed
 * into the progress word and the seal then certified it -- and once the
 * preemptive bits were added, two of them (ZX_GP_PREEMPTED at 0x010000 and
 * ZX_GP_NO_CLOCK at 0x040000) fall on bits the sentinel sets.  A cooperative
 * build with no clock at all reported both.  The corruption had been there
 * all along and was invisible until new bits gave those positions meaning,
 * which is the worst way for a defect to become visible.
 *
 * So the probe gets a word of its own, which nothing reads and nothing folds
 * into a checksum.  */

#define ZX_GD_PROBE_SCRATCH         0x58U   /* written by the probe, read by
                                               nobody                       */

/**************************************************************************/
/*        THE THIRD GRANULE: the isolation matrix and the behaviour        */
/**************************************************************************/

/* WHY THE MAILBOX IS THREE GRANULES AND NOT TWO.
 *
 * The same reason it went from one to two, and the note above says what that
 * cost: the guest's stage-1 MPU region for the mailbox grows by 64 bytes,
 * NOTHING at stage 2 changes because the partition window is one region
 * covering the whole of it, and the entry branch moves -- so
 * ZX_GUEST_IMAGE_OFF_ENTRY is 0xC0 and every linker script asserts it.
 *
 * THE ALTERNATIVE WAS OVERLOADING, AND IT WAS REJECTED FOR THE SECOND TIME.
 * Five words of the second granule were spare, and the matrix needs six from
 * the hypervisor and six back.  Aliasing eleven words onto the spares and
 * onto fields "a kernel guest happens not to use" is precisely the layout
 * this file already refused to build once: one alias with one reader at each
 * end is explicable, eleven is a map only its author can read.  Sixty-four
 * bytes of a 256 KB window is the cheaper price.
 *
 * THE IMAGE MAGIC IS BUMPED WITH IT, which is what the note beside
 * ZX_GUEST_IMAGE_MAGIC asked for and the first occasion to use it.  Moving
 * the entry branch is an ABI change: a guest built against the old layout
 * and loaded by a hypervisor expecting the new one would be ERETed into the
 * middle of its own mailbox, which is a jump to whatever the handover last
 * wrote there.  A version in the header turns that into a refusal naming
 * both numbers.  */

/* WHAT THE HYPERVISOR ASKS FOR.  Six addresses and a mask, because the
 * matrix is "one address per case, one case per bit" and the address IS the
 * case's name -- it is what the fault log is searched by afterwards.
 *
 * EVERY ADDRESS COMES FROM EL2 AND NOT FROM THE GUEST'S OWN LINKER, with one
 * exception noted below, and that is the point rather than an inconvenience.
 * A guest computing its neighbour's window from its own base would be a
 * guest that had been TOLD the layout; a guest handed an address it cannot
 * derive is a guest being asked to reach somewhere it has no business
 * knowing about, which is the situation the isolation claim is about.  */

#define ZX_GD_M_CASES               0x80U   /* EL2 writes: ZX_MC_* to run   */
#define ZX_GD_M_NEIGHBOUR           0x84U   /* EL2: the other partition's
                                               data, read AND written       */
#define ZX_GD_M_NEIGHBOUR_CODE      0x88U   /* EL2: the other partition's
                                               code, BRANCHED to            */
#define ZX_GD_M_HOLE                0x8CU   /* EL2: the ungranted granule
                                               ADJACENT to this window      */
#define ZX_GD_M_HYP_DATA            0x90U   /* EL2: hypervisor .data/.bss   */
#define ZX_GD_M_HYP_MMIO            0x94U   /* EL2: the console or the GIC  */
#define ZX_GD_M_MARK_BASE           0x98U   /* EL2: first granule to mark   */
#define ZX_GD_M_MARK_COUNT          0x9CU   /* EL2: how many to mark        */

/* WHAT THE GUEST REPORTS BACK.
 *
 * NONE OF THESE IS A CLAIM THAT A CASE WAS DENIED, and that is deliberate to
 * the point of being the most important thing in this block.
 *
 * Under the test-only continue mode the hypervisor resumes a faulting
 * partition PAST the faulting instruction -- so the store that would have
 * recorded "this case survived" executes anyway, one instruction later, on
 * a case that was refused.  A guest cannot report its own denial: it is not
 * conscious of having been denied.  Every "it faulted" judgement therefore
 * belongs to EL2 and comes out of the fault log, matched by address.
 *
 * What the guest CAN say honestly is what it ATTEMPTED, which EL2 cannot
 * know -- a case skipped because the guest refused it and a case denied by
 * stage 2 both leave a hypervisor with no fault to look at, and only the
 * guest can tell them apart.  That asymmetry is why both halves exist.  */

#define ZX_GD_M_ATTEMPTED           0xA0U   /* guest: ZX_MC_* it tried      */
#define ZX_GD_M_REFUSED             0xA4U   /* guest: ZX_MC_* it would not  */
#define ZX_GD_M_RESUME              0xA8U   /* guest: where to put it back
                                               after a failed BRANCH        */
#define ZX_GD_M_READ_VALUE          0xACU   /* guest: what the read case
                                               returned, poison if denied   */
#define ZX_GD_M_MARKS_WRITTEN       0xB0U   /* guest: marks it wrote        */
#define ZX_GD_M_MARKS_OK            0xB4U   /* guest: its own readback      */

/* What a partition is doing while its neighbour is being measured.
 *
 * A WORD AND NOT A BUILD OPTION, and the reason is the whole shape of the
 * determinism run.  Six behaviours as six images is six boots, six epochs
 * and six sets of switch measurements, and comparing the critical
 * partition's period ACROSS them then compares runs rather than phases.
 * Re-read on every iteration of the endless loop, so one run can put the
 * untrusted partition through every behaviour in turn while the critical
 * one is measured continuously -- which is a strictly stronger comparison
 * and a sixth of the model time.  */

#define ZX_GD_M_BEHAVIOUR           0xB8U   /* EL2 writes: ZX_GB_*          */
#define ZX_GD_M_PHASE_SEEN          0xBCU   /* guest: behaviours it obeyed  */

#define ZX_GD_WINDOW_SIZE           0xC0U

/**************************************************************************/
/*                     The isolation matrix, as bits                      */
/**************************************************************************/

/* One bit per case, in the order the sweep runs them.
 *
 * THE ORDER IS NOT ARBITRARY: the cases that must SUCCEED come last.  A
 * sweep that marked its own window first and then went on to be denied six
 * times would leave a reader unable to say whether the marks were written
 * before or after the denials, and "the partition still owned its memory
 * after being refused six times" is part of what case 7 asserts.
 *
 * THE BRANCH CASE IS LAST OF THE DENIALS for a different reason.  A
 * prefetch abort cannot be resumed by stepping over the faulting
 * instruction -- the instruction was never fetched -- so it is the one case
 * whose continuation depends on the guest having published a resume
 * address.  Running it after the data cases means a defect in that path
 * costs the sweep one case rather than all of them.  */

#define ZX_MC_NEIGHBOUR_READ        0x01U   /* case 1 */
#define ZX_MC_NEIGHBOUR_WRITE       0x02U   /* case 2 */
#define ZX_MC_HOLE_WRITE            0x04U   /* case 4 -- the ADJACENT one   */
#define ZX_MC_HYP_DATA              0x08U   /* case 5 -- read and write     */
#define ZX_MC_HYP_MMIO              0x10U   /* case 6 */
#define ZX_MC_NEIGHBOUR_EXEC        0x20U   /* case 3 -- a BRANCH           */
#define ZX_MC_OWN_MARKS             0x40U   /* case 7 -- must SUCCEED       */

#define ZX_MC_ALL                   0x7FU

/* Why the guest would refuse a case.  Reported in ZX_GD_M_REFUSED so that a
   case which never ran is distinguishable from one that was denied, which
   from EL2 look identical: both leave the guest reporting nothing.  */

#define ZX_MR_NO_ADDRESS            0x0100U /* EL2 left the word zero       */
#define ZX_MR_NO_REGION             0x0200U /* no spare stage-1 region      */
#define ZX_MR_INSIDE_ITSELF         0x0400U /* the address is its own, so
                                               the case would prove nothing */

/* The mark a granule carries: whose window it is in the middle byte, and
 * the granule's index in the low one.
 *
 * DISTINCT PER GRANULE, because five copies of one value in five granules
 * proves one extent was programmed five times over -- a region whose base
 * is wrong accepts every store and puts them all somewhere else, and every
 * readback of an identical mark agrees.  Only distinct marks read back at
 * distinct addresses catch it.
 *
 * AND DISTINCT PER PARTITION, from the SENTINEL the handover already gives
 * each guest, so that a mark read out of the wrong window is attributable
 * rather than merely present.  Its low byte is what varies -- 0x11 and
 * 0x22 -- and folding the whole sentinel in would overflow the field for
 * no gain.
 *
 * UNSIGNED LONG AND NOT uint32_t, because this header is the CONTRACT and
 * both sides of it spell their types differently: the hypervisor is ZoneX
 * C17 with stdint, the guest is ThreadX C99 with ULONG, and the file is
 * also included by assembly, which has no types at all.  So it names the
 * one spelling that is 32-bit and available on every side.  A uint32_t here
 * failed the guest's build, which is the header doing its job.  */

#define ZX_MARK_BASE                0x5A5A0000UL
#define ZX_MARK_FOR(sentinel, index)                                          \
    (ZX_MARK_BASE | (((unsigned long)(sentinel) & 0xFFUL) << 8)               \
     | ((unsigned long)(index) & 0xFFUL))

/* What EL2 writes into a granule that belongs to NOBODY, before the run.
 * It has to be a value no mark can take and no zeroed window can hold: a
 * hole reading as zero after the run is indistinguishable from a hole
 * nobody looked at.  */

#define ZX_HOLE_POISON              0xDEAD00FFU

/* What the guest leaves in ZX_GD_M_READ_VALUE before it attempts the read,
   so that a denied load -- whose destination register is never written --
   reports this rather than a stale value that reads like an answer.  */

#define ZX_READ_POISON              0xBAD0BAD0U

/**************************************************************************/
/*               What an untrusted partition is asked to do               */
/**************************************************************************/

/* Re-read on every iteration of the endless loop.  Each of these is one row
   of the determinism table, and the critical partition's period is measured
   across all of them in one run.  */

#define ZX_GB_QUIET                 0x00U   /* republish, and nothing else  */
#define ZX_GB_SPIN                  0x01U   /* compute, never yield         */
#define ZX_GB_MASKED                0x02U   /* CPSID if, then compute       */
#define ZX_GB_STORM                 0x03U   /* a hypercall per character    */
#define ZX_GB_FAULT                 0x04U   /* violate, over and over       */

/**************************************************************************/
/*                            Progress bits                              */
/**************************************************************************/

/* Set by the guest as it gets somewhere.  Read by EL2 afterwards.
 *
 * ZX_GP_PROBE_SURVIVED is the one that carries the isolation claim, and it
 * carries it NEGATIVELY: the bit being CLEAR after a probe is the evidence
 * that stage 2 stopped the access.  A test whose pass condition is the
 * absence of something must be able to fail, which is why the negative
 * builds aim the same probe at an address the guest IS granted.  */

#define ZX_GP_ENTERED               0x01U
#define ZX_GP_OWN_DATA_OK           0x02U
#define ZX_GP_PROBE_SURVIVED        0x04U
#define ZX_GP_PUBLISHED             0x08U
#define ZX_GP_CONSUMED              0x10U

/* The bits a REAL kernel guest sets, as it gets further.  Each one is a
   milestone the one before it cannot fake: reaching bsp_main proves the
   ERET landed and the boot path ran, reaching tx_application_define proves
   the kernel initialised, and a thread running proves the ported context
   switch works underneath stage 2.  A run that stops between two of them
   says where it stopped, which a single "did it work" bit cannot.  */

#define ZX_GP_BSP_MAIN              0x0100U /* the boot path reached C      */
#define ZX_GP_KERNEL_ENTERED        0x0200U /* tx_application_define ran    */
#define ZX_GP_THREADS_RAN           0x0400U /* both threads took a slice    */
#define ZX_GP_QUEUE_OK              0x0800U /* the queue carried every item */
#define ZX_GP_SEMAPHORE_OK          0x1000U /* the semaphore handed off     */
#define ZX_GP_TICKING               0x2000U /* the guest's own tick advanced */
#define ZX_GP_FINISHED              0x4000U /* the guest reached its verdict */

/* The bits a PREEMPTIVE kernel guest sets, and each of them is a thing a
   cooperative guest cannot fake:

     COUNTING     the guest's own virtual counter was seen to ADVANCE before
                  it blocked on anything.  This is the pre-flight, and it
                  exists because the alternative to it is a hang: on a target
                  whose system counter was never started, a guest that goes
                  straight to tx_thread_sleep waits for ever and the run ends
                  in a harness timeout that names nothing.
     TICKING      tx_time_get() advanced, so _tx_timer_interrupt ran, so the
                  virtual timer PPI was delivered to EL1 and serviced.
     PREEMPTED    a thread that never yielded was DISPLACED by a
                  higher-priority thread waking from a timed sleep.  Only an
                  interrupt can do that.
     TIMESLICED   two equal-priority threads that never yielded BOTH
                  advanced, which is the kernel's time slice and not merely
                  its scheduler.

   TICKING is deliberately kept at the value the cooperative build already
   defined for it -- it was declared with the rest of the milestones before
   there was a tick to set it.  */

#define ZX_GP_COUNTING              0x8000U  /* the virtual counter moves   */
#define ZX_GP_PREEMPTED           0x010000U  /* a spinner was displaced     */
#define ZX_GP_TIMESLICED          0x020000U  /* two spinners both advanced  */
#define ZX_GP_NO_CLOCK            0x040000U  /* refused to block: no counter */

/* THE ONE THING THE ISOLATION SWEEP CAN CLAIM FOR ITSELF, and it is inside
   the seal because it is a claim about what the partition ACHIEVED rather
   than about what it was refused.  Set when every granule of its own window
   that the hypervisor pointed it at took a distinct mark and read that mark
   back -- which is the sweep's one positive case, and the reason a
   regression that only proved things fault would not pass with every region
   disabled.
 *
   NOT a bit meaning "the sweep ran".  The sweep's attempted set is a word
   of its own, ZX_GD_M_ATTEMPTED, and it is a word rather than a bit for the
   reason the whole third granule exists: a guest cannot report having been
   denied, so "ran" and "was refused" are the hypervisor's to distinguish
   and only the attempted set helps it.  */

#define ZX_GP_MARKS_OK            0x080000U  /* its own window, marked and
                                                read back, every granule    */

/* WHAT THE GUEST'S OWN VECTORS SAW, in ZX_GD_STAGE1.
 *
 * A stage-1 fault is taken to EL1 and never reaches the hypervisor, which is
 * the whole difference between the two stages -- so this word is the only
 * channel by which one becomes visible at EL2, and a report of one is
 * evidence that the guest's own MPU is LIVE rather than merely programmed.
 *
 * One value per vector rather than one "the guest faulted" flag, because a
 * data abort, a prefetch abort and an undefined instruction send a reader to
 * three different halves of a kernel.  Each is a single bit so that an ORR
 * with an immediate assembles: the handlers that set them run before
 * anything else, with no stack and no literal pool beyond the mailbox
 * address.  */

#define ZX_GS_NONE                  0x00000000U /* no stage-1 fault         */
#define ZX_GS_DABT                  0x00000001U /* data abort at EL1        */
#define ZX_GS_PABT                  0x00000002U /* prefetch abort at EL1    */
#define ZX_GS_UNDEF                 0x00000004U /* undefined instruction    */
#define ZX_GS_IRQ                   0x00000008U /* an IRQ with no handler   */
#define ZX_GS_OTHER                 0x00000010U /* a vector nothing expects */

/* The sentinel a guest writes into its own scratch word.  Distinct per
   partition so that EL2 reading both back cannot mistake one for the
   other -- which is the failure a single shared sentinel would hide.  */
#define ZX_GUEST_SENTINEL_A         0xA5A50001U
#define ZX_GUEST_SENTINEL_B         0xA5A50002U

/* What the publisher puts in the shared granule.  */
#define ZX_GUEST_HEARTBEAT          0x48420000U

/**************************************************************************/
/*                    A REAL KERNEL IMAGE IN A WINDOW                     */
/**************************************************************************/

/* Where things sit inside a partition window that holds a whole kernel.
 *
 * WHY A TRAMPOLINE AT OFFSET ZERO RATHER THAN THE KERNEL'S OWN _start.
 * The hypervisor computes the ERET target as window_base + a constant, so it
 * needs that constant at compile time.  A real kernel's reset symbol is
 * wherever its linker put it, after its vector tables, and its address is
 * therefore neither zero nor predictable.  Three ways out were considered:
 *
 *   * extract the ELF entry point at build time into a generated header --
 *     works, and makes the hypervisor's manifest depend on a build step
 *     whose output nothing checks;
 *   * match the boot object's .text by input pattern in the linker script so
 *     that _start lands first -- the pattern has to name an object file
 *     suffix, which differs between toolchains, and a pattern that matches
 *     nothing produces an empty section at whatever address the location
 *     counter held rather than an error;
 *   * put ONE BRANCH at the window base and let it reach the kernel's own
 *     reset symbol PC-relatively.
 *
 * The third is four bytes, needs no build step, and its correctness is
 * asserted by the guest's own linker script.  It is also the thing a real
 * boot ROM does, which is a reasonable sign it is not a trick.
 *
 * WHY THE MAILBOX IS NOT IN .bss.  The kernel's reset path zeroes .bss
 * before any C runs.  The hypervisor writes the mailbox before it ERETs --
 * it has to, that is how the guest is told which partition it is -- so a
 * mailbox in .bss would be handed over and then wiped by its recipient.  It
 * therefore gets a section of its own, placed before .data, and the guest's
 * linker script asserts it is outside the range the reset path clears.  */

/* THE MAILBOX COMES FIRST, AND THE ORDER IS FORCED.
 *
 * Two constraints point the same way and a third decides between the
 * remaining options.
 *
 *   * The mailbox may not sit INSIDE the guest's own executable region.
 *     PMSAv8-R has no region priority at either stage, so a writable
 *     granule overlapping a read-only executable region is two enabled
 *     regions on one address -- CONSTRAINED UNPREDICTABLE, and an abort on
 *     the S32Z280.  So the mailbox cannot be tucked between the entry
 *     branch and the vector table.
 *   * The mailbox may not be in .bss.  The kernel's reset path zeroes .bss
 *     before any C runs, and the hypervisor writes the mailbox BEFORE it
 *     ERETs -- that is how the guest is told which partition it is -- so a
 *     mailbox in .bss would be handed over and then wiped by its recipient.
 *   * It is LOADED rather than NOLOAD, which is what settles its position.
 *     objcopy -O binary emits only sections with contents, so a NOLOAD
 *     section at the front of the window would be skipped and the blob's
 *     first byte would correspond to the SECOND section -- the whole image
 *     shifted by a granule, copied to the window base, and executed from
 *     the wrong place.  A loaded, zero-filled granule keeps the blob's
 *     offset zero equal to the window's offset zero, which is the property
 *     the loader's arithmetic rests on.
 *
 * Being loaded also means the copy leaves the mailbox ZEROED, which is a
 * defined starting state rather than whatever the window held before.  The
 * hypervisor writes its handover fields after the copy, never before.  */

#define ZX_GUEST_IMAGE_OFF_MAILBOX  0x00U   /* THREE granules, ZX_GD_* in   */
#define ZX_GUEST_IMAGE_OFF_ENTRY    0xC0U   /* the branch the ERET lands on */

/* THE IMAGE HEADER, three words after the entry branch.
 *
 * A guest is LINKED for one window: every absolute address in it is baked
 * in.  The hypervisor holds a raw blob with no symbol table, so without
 * these words it has no way to know which window that was -- and the failure
 * is slow rather than immediate, because the entry branch is PC-relative.
 * A guest copied into the wrong window STARTS, runs to its first literal
 * pool load, and then faults at an address that looks entirely reasonable in
 * the report.
 *
 * The magic is worth its four bytes twice: an unwritten window reads as
 * zero, and an .incbin whose linker input pattern matched nothing produces
 * an EMPTY section rather than an error, so "the header does not carry the
 * magic" catches both a missing guest and a wrong one.  */

#define ZX_GUEST_IMAGE_OFF_LINK_BASE 0xC4U  /* the window it was linked for */
#define ZX_GUEST_IMAGE_OFF_LINK_SIZE 0xC8U  /* the size it was linked to fit */
#define ZX_GUEST_IMAGE_OFF_MAGIC     0xCCU  /* ZX_GUEST_IMAGE_MAGIC          */

/* AND THE FIRST BYTE PAST THE HEADER, which is the smallest blob that can
   carry one.  Every hypervisor linker script asserts its embedded guest is
   at least this big, because a blob too small to hold its own header makes
   the loader's magic check an out-of-bounds read of whatever follows the
   section -- and an .incbin whose file was missing produces exactly that.
   The number lived as a literal in four linker scripts and was WRONG in all
   four the day the mailbox grew from one granule to two: it stayed at 0x50
   while the header moved to 0x8C, so a blob of 0x51 to 0x8F bytes linked
   cleanly and read past its own section.  It is a named constant now, and
   the scripts still restate it -- a linker script cannot include a C header
   -- but there is one place to look when it moves again.  */

#define ZX_GUEST_IMAGE_MIN_SIZE      0xD0U

/* "ZXG" and a version.  The version is here so that a later ABI change is a
   REFUSAL rather than a guest that starts and misbehaves: the loader can say
   "this image was built against a different contract" and name both
   numbers.  */

/* "ZXG2".  Version 1 had the entry branch at 0x80 and a two-granule
   mailbox; a version-1 blob loaded by this hypervisor would be ERETed into
   the middle of its own mailbox.  */

#define ZX_GUEST_IMAGE_MAGIC        0x5A584732

/* The verdict a kernel guest publishes into ZX_GD_VERDICT.  Distinct
   non-zero values, so that an unwritten word -- zero -- is neither a pass
   nor a fail but the absence of a verdict, which is what it actually is.  */

#define ZX_GV_NONE                  0x00000000U
#define ZX_GV_PASSED                0x600DBEEFU
#define ZX_GV_FAILED                0x0BADBEEFU

/**************************************************************************/
/*                        The hypercalls a guest makes                    */
/**************************************************************************/

/* The HVC immediates, spelled WITHOUT an integer suffix so that the guest's
   own assembly can write "hvc #ZX_HVC_GUEST_YIELD" directly.
 *
 * These are the same three values the hypervisor decodes, where they are
 * called ZX_HVC_NOP, ZX_HVC_YIELD and ZX_HVC_PUTC.  Two spellings is one
 * more than nobody wants, and it is unavoidable: the guest cannot include
 * the hypervisor's own headers -- it is a separate program with a separate
 * toolchain invocation and its own type vocabulary -- so the contract has to
 * be restated at this end.
 *
 * What makes that safe rather than a latent divergence is that the ZoneX
 * example which includes BOTH headers asserts they agree, at compile time.
 * A guest built against a renumbered immediate would then fail the
 * hypervisor's build rather than fail on the model.  */

#define ZX_HVC_GUEST_NOP            0x0000
#define ZX_HVC_GUEST_YIELD          0x0001
#define ZX_HVC_GUEST_PUTC           0x0002

/**************************************************************************/
/*                    The interrupt a partition is granted                */
/**************************************************************************/

/* THE VIRTUAL TIMER'S PPI, and the two sides have to agree about it for
 * different reasons.  The hypervisor ENABLES this INTID in the
 * redistributor -- which the guest cannot reach -- and the guest
 * ACKNOWLEDGES it through its own CPU interface, which is system registers
 * and needs no device at all.  A disagreement would present as a guest that
 * takes an interrupt it does not recognise, records an unexpected INTID and
 * never ticks, which is a good failure and still a failure.
 *
 * Three timer interrupts arrive as PPIs on this core: physical 30, virtual
 * 27, hypervisor 26.  A partition gets the VIRTUAL one, because its counter
 * can be frozen with CNTVOFF while the partition is descheduled and the
 * physical one cannot.  See docs/decisions.md D7.
 *
 * Spelled without a suffix so the guest's assembly could use it directly if
 * it ever needed to, like the HVC immediates above.  The ZoneX side spells
 * it ZX_PPI_VIRTUAL_TIMER, and the example that includes both headers
 * asserts they agree at compile time.  */

#define ZX_GUEST_TIMER_INTID        27

/* The GIC's spurious INTID: what ICC_IAR1 returns when nothing was actually
   pending.  It must NOT be given an end-of-interrupt, which is why the guest
   checks for it rather than treating every read as an interrupt.  */

#define ZX_GUEST_SPURIOUS_INTID     1023

/**************************************************************************/
/*                     The readback checksum                              */
/**************************************************************************/

/* Folded over every field the guest reports, plus the sentinel that says
   WHICH partition reported it.  Defined here, as one function, so that the
   guest computing it and the hypervisor checking it cannot drift: two
   implementations of a checksum agree until the day they do not, and the
   day they do not looks exactly like a corrupted guest.

   Deliberately additive and deliberately weak.  This is not a defence
   against a hostile guest -- a partition can write whatever it likes into
   its own window, and no checksum changes that.  It defends against three
   accidents: a window nobody wrote (every field zero, which the magic makes
   fail), a torn update (the sequence is folded in and is written last but
   one), and a value read out of the WRONG partition's window (the sentinel
   is folded in).  A stronger function would cost the guest more and catch
   nothing further.

   ZX_ASSEMBLER guard: this file is included from zx_payload.S, and an
   assembler cannot read a function definition.  */

#ifndef __ASSEMBLER__

#define ZX_GUEST_REPORT_MAGIC       0x5A58F00DU

static inline unsigned long zx_guest_report_checksum(unsigned long sentinel,
                                                     unsigned long progress,
                                                     unsigned long sequence,
                                                     unsigned long ticks,
                                                     unsigned long thread_a,
                                                     unsigned long thread_b,
                                                     unsigned long messages,
                                                     unsigned long verdict)
{
    unsigned long sum = (unsigned long) ZX_GUEST_REPORT_MAGIC;

    sum += sentinel;
    sum += progress;
    sum += sequence;
    sum += ticks;
    sum += thread_a;
    sum += thread_b;
    sum += messages;
    sum += verdict;

    return sum & 0xFFFFFFFFUL;
}

#endif /* __ASSEMBLER__ */

#endif /* ZX_GUEST_ABI_H */
