/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_guest_abi.h                                       EXAMPLE        */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The contract between the hypervisor and the RELOCATABLE guest blob: */
/*    where each entry point sits inside the blob, and what each word of  */
/*    the partition's data window means.                                  */
/*                                                                        */
/*  WHY A RELOCATABLE BLOB AT ALL                                         */
/*                                                                        */
/*    Two partitions have to run the same program in DIFFERENT memory, or */
/*    "set A denies B and set B denies A" cannot be demonstrated -- one   */
/*    of the two halves would have no code to execute.  The blob is       */
/*    therefore assembled once, kept in the hypervisor's own memory, and  */
/*    COPIED into each partition's code window at boot.  That is the same */
/*    path a real guest image takes, which is why the manifest's          */
/*    image_start and image_end are load-bearing here rather than         */
/*    decorative.                                                         */
/*                                                                        */
/*    Relocatable, not position-independent-by-arithmetic.  The blob       */
/*    reaches its data through a BASE POINTER the hypervisor hands it in   */
/*    r0, not through PC-relative address computation, so there is no      */
/*    relocation to apply and no literal pool holding an absolute address. */
/*    Branches inside the blob are already PC-relative and survive the     */
/*    copy untouched; a literal pool holding a CONSTANT survives too.      */
/*    The one thing that cannot survive is a literal holding an ADDRESS,   */
/*    and that is precisely what the base pointer removes.                 */
/*                                                                        */
/*  WHY THE OFFSETS ARE FIXED CONSTANTS                                    */
/*                                                                        */
/*    The hypervisor computes an entry point as window_base + offset, so  */
/*    it needs the offsets at compile time.  Exporting them as link-time   */
/*    symbols would work and would be silently wrong the first time an     */
/*    entry grew past its slot; declaring them here and having the         */
/*    assembler ASSERT each one fits fails the build instead.  See the     */
/*    .if/.error guards in zx_payload.S.                                   */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_GUEST_ABI_H
#define ZX_GUEST_ABI_H

/**************************************************************************/
/*                    Entry points, as blob offsets                      */
/**************************************************************************/

/* Offset 0 is the EL1 vector table, so VBAR is simply the window base.
   Eight AArch32 vectors of four bytes each need 32; the slot is 64 so the
   first entry point starts on a granule boundary and the map file reads
   as the region layout rather than as an accident of instruction count.  */
#define ZX_GUEST_OFF_VECTORS        0x000U

/* Writes a sentinel into its own data window and reads it back.  Both
   halves matter: a write that went nowhere and a read returning a stale
   value are different failures, and only the comparison separates them
   from success.  */
#define ZX_GUEST_OFF_GRANT          0x040U

/* Reads the address the hypervisor left in ZX_GD_TARGET.  Used against
   the OTHER partition's memory, and against the ungranted granule next
   door to a granted one.  */
#define ZX_GUEST_OFF_PROBE          0x080U

/* Publishes a value into the shared granule.  Only the publisher can do
   this; a reader attempting it takes a stage-2 permission fault, which is
   itself one of the checks.  */
#define ZX_GUEST_OFF_PUBLISH        0x0C0U

/* Reads the shared granule.  Every partition may do this.  */
#define ZX_GUEST_OFF_CONSUME        0x100U

/* Total size the blob occupies.  The assembler checks it.  */
#define ZX_GUEST_BLOB_SIZE          0x140U

/**************************************************************************/
/*                   The partition's data window                          */
/**************************************************************************/

/* Offsets from the base pointer the hypervisor passes in r0.
 *
 * This is a MAILBOX and not a parameter list, and the difference matters:
 * zx_el2_run_payload passes exactly one argument, while a probe needs both
 * somewhere to report and something to aim at.  The hypervisor can write
 * this window because stage-2 AP cannot deny EL2 (D3) -- so the same
 * property that stops AP from isolating partitions is what makes a
 * hypervisor-to-guest mailbox free.  */

#define ZX_GD_PROGRESS              0x00U   /* guest writes, EL2 reads      */
#define ZX_GD_SCRATCH               0x04U   /* the guest's own sentinel     */
#define ZX_GD_TARGET                0x08U   /* EL2 writes: what to probe    */
#define ZX_GD_PROBED                0x0CU   /* guest writes: what it read   */
#define ZX_GD_SHARED                0x10U   /* EL2 writes: shared granule   */
#define ZX_GD_PUBLISH_VALUE         0x14U   /* EL2 writes: what to publish  */

#define ZX_GD_WINDOW_SIZE           0x40U

/**************************************************************************/
/*                            Progress bits                              */
/**************************************************************************/

/* Set by the guest as it gets somewhere.  Read by EL2 afterwards.
 *
 * ZX_GP_PROBE_SURVIVED is the one that carries the isolation claim, and it
 * carries it NEGATIVELY: the bit being CLEAR after a probe is the evidence
 * that stage 2 stopped the access.  A test whose pass condition is the
 * absence of something must be able to fail, which is why the negative
 * builds aim the same probe at an address the guest IS granted.  */

#define ZX_GP_ENTERED               0x01U
#define ZX_GP_OWN_DATA_OK           0x02U
#define ZX_GP_PROBE_SURVIVED        0x04U
#define ZX_GP_PUBLISHED             0x08U
#define ZX_GP_CONSUMED              0x10U

/* The sentinel a guest writes into its own scratch word.  Distinct per
   partition so that EL2 reading both back cannot mistake one for the
   other -- which is the failure a single shared sentinel would hide.  */
#define ZX_GUEST_SENTINEL_A         0xA5A50001U
#define ZX_GUEST_SENTINEL_B         0xA5A50002U

/* What the publisher puts in the shared granule.  */
#define ZX_GUEST_HEARTBEAT          0x48420000U

#endif /* ZX_GUEST_ABI_H */
