/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_guest_launch.c                                      SHARED       */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The loader half of launching a real ThreadX guest, shared by every  */
/*    example image that launches one.  See zx_guest_launch.h for why it  */
/*    is shared and what is deliberately left with each experiment.       */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Rule 11.4/11.6 -- casting a partition window's address to a         */
/*      volatile pointer is inherent to a hypervisor writing a guest's    */
/*      memory; confined to the two accessors at the top of this file.    */
/*    Directive 4.3 -- the one asm statement below is a barrier in a      */
/*      function that does nothing else.                                  */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"
#include "zx_guest_abi.h"
#include "zx_guest_launch.h"
#include "zx_guest_console.h"


/**************************************************************************/
/*                              The mailbox                               */
/**************************************************************************/

static volatile uint32_t *zx_mailbox(const ZX_GUEST_LAUNCH *launch_ptr)
{
    return (volatile uint32_t *)(uintptr_t)
        (launch_ptr->zx_launch_window_base + ZX_GUEST_IMAGE_OFF_MAILBOX);
}


uint32_t zx_guest_mailbox_read(const ZX_GUEST_LAUNCH *launch_ptr,
                               uint32_t offset)
{
    return zx_mailbox(launch_ptr)[offset / 4U];
}


void zx_guest_mailbox_write(const ZX_GUEST_LAUNCH *launch_ptr,
                            uint32_t offset, uint32_t value)
{
    zx_mailbox(launch_ptr)[offset / 4U] = value;
}


/**************************************************************************/
/*  zx_image_word -- one word out of the embedded guest image.            */
/*                                                                        */
/*  Read from the SOURCE and not from the window, deliberately: the point  */
/*  of the header check is to refuse before anything is copied, and a      */
/*  check performed on the copy would already have overwritten whatever    */
/*  was there.                                                            */
/**************************************************************************/

static uint32_t zx_image_word(const ZX_GUEST_LAUNCH *launch_ptr,
                              uint32_t offset)
{
    const volatile uint32_t *image = (const volatile uint32_t *)(uintptr_t)
        launch_ptr->zx_launch_image_start;

    return image[offset / 4U];
}


/**************************************************************************/
/*  zx_guest_image_check                                                  */
/*                                                                        */
/*  THE CHECK THAT CATCHES A GUEST BUILT FOR SOMEWHERE ELSE.              */
/*                                                                        */
/*  A guest is LINKED for one window; every absolute address inside it is  */
/*  baked in.  The hypervisor holds a raw blob with no symbol table, so     */
/*  without the header the guest carries there is no way to know which     */
/*  window that was -- and the failure is slow, not immediate: the entry   */
/*  branch is PC-relative, so a guest copied into the wrong window STARTS,  */
/*  runs to its first literal pool load, and then faults at an address     */
/*  that looks entirely reasonable in the report.                          */
/*                                                                        */
/*  The magic earns its four bytes twice over: an unwritten window         */
/*  reads as zero, and an .incbin whose linker input pattern matched       */
/*  nothing produces an EMPTY section rather than an error -- so "the      */
/*  header does not carry the magic" catches both a missing guest and a    */
/*  wrong one.                                                             */
/**************************************************************************/

uint32_t zx_guest_image_check(const ZX_GUEST_LAUNCH *launch_ptr)
{
    uint32_t magic     = zx_image_word(launch_ptr, ZX_GUEST_IMAGE_OFF_MAGIC);
    uint32_t link_base = zx_image_word(launch_ptr, ZX_GUEST_IMAGE_OFF_LINK_BASE);
    uint32_t link_size = zx_image_word(launch_ptr, ZX_GUEST_IMAGE_OFF_LINK_SIZE);
    uint32_t window_base = (uint32_t)launch_ptr->zx_launch_window_base;
    uint32_t window_size = (uint32_t)(launch_ptr->zx_launch_window_end
                                      - launch_ptr->zx_launch_window_base);

    zx_console_puts("\n--- the guest image declares what it was built for ---\n");
    zx_note("magic                 ", magic);
    zx_note("linked for base       ", link_base);
    zx_note("linked for size       ", link_size);
    zx_note("this window's base    ", window_base);
    zx_note("this window's size    ", window_size);

    zx_check("the embedded image carries the ZoneX guest magic, so a missing\n"
             "         .incbin or an empty section is caught before anything runs",
             (magic == (uint32_t)ZX_GUEST_IMAGE_MAGIC) ? 1U : 0U);

    zx_check("the guest was linked for THIS window's base -- a guest built\n"
             "         for another address starts and then faults at an\n"
             "         address that looks perfectly reasonable",
             (link_base == window_base) ? 1U : 0U);

    zx_check("and for this window's size, so a guest that expected more room\n"
             "         than the manifest grants is refused rather than\n"
             "         discovered at its first stack overflow",
             (link_size == window_size) ? 1U : 0U);

    return ((magic == (uint32_t)ZX_GUEST_IMAGE_MAGIC)
            && (link_base == window_base)
            && (link_size == window_size)) ? 1U : 0U;
}


/**************************************************************************/
/*  zx_guest_image_load -- copy the image and make it executable.          */
/*                                                                        */
/*  The COPY is here and the DECISION about where to copy is in            */
/*  core/src/zx_partition_manager.c, which is the split zx_partition.h     */
/*  describes: the arithmetic is testable on a workstation, the copy is    */
/*  not.                                                                   */
/*                                                                        */
/*  A word copy, not a byte copy, and both ends are granule aligned by     */
/*  construction -- the linker script asserts it at each end -- so the     */
/*  alignment the word copy needs is a property of the build rather than   */
/*  a run-time hope.  The length is rounded UP to a word because a blob     */
/*  ending mid-word would otherwise lose its last bytes, and objcopy has    */
/*  no obligation to pad.                                                  */
/**************************************************************************/

void zx_guest_image_load(const ZX_PARTITION_LOAD *load_ptr)
{
    const volatile uint32_t *source = (const volatile uint32_t *)(uintptr_t)
        load_ptr->zx_load_image_source;
    volatile uint32_t *destination = (volatile uint32_t *)(uintptr_t)
        load_ptr->zx_load_window_base;
    uint32_t words = (uint32_t)((load_ptr->zx_load_image_length + 3U) / 4U);
    uint32_t index;

    for (index = 0U; index < words; index++)
    {
        destination[index] = source[index];
    }

    /* The bytes just written will be FETCHED as instructions, and on this
       core the instruction side is not coherent with the data cache.  ZoneX
       runs with its caches off today, so this is currently redundant -- and
       it is here anyway, because the change that turns caches on will be one
       line in the reset path made by somebody with no reason to think about
       the loader.  A cold instruction cache over an address nothing has
       executed HAPPENS TO WORK until an eviction lands differently.  */

    zx_cache_sync_after_load(load_ptr->zx_load_window_base,
                             load_ptr->zx_load_image_length);
}


/**************************************************************************/
/*  zx_guest_hand_over -- what the hypervisor tells the guest.            */
/*                                                                        */
/*  AFTER the copy, never before.  The mailbox is a LOADED section in the  */
/*  guest image -- zeroed by the copy -- which is what keeps the blob's    */
/*  offset zero equal to the window's offset zero.  Writing the handover   */
/*  first would have it copied over.                                       */
/*                                                                        */
/*  EVERY WORD IS WRITTEN, including the ones being set to zero.  A        */
/*  handover that only wrote the fields it cared about would leave the     */
/*  rest holding whatever the copy put there, and "the guest reported      */
/*  nothing" and "the guest reported what the previous pass left" are      */
/*  different diagnoses that would look identical.                         */
/**************************************************************************/

void zx_guest_hand_over(const ZX_GUEST_LAUNCH *launch_ptr,
                        uint32_t probe_target, uint32_t options)
{
    zx_guest_mailbox_write(launch_ptr, ZX_GD_PROGRESS, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_SCRATCH,
                           launch_ptr->zx_launch_sentinel);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_TARGET, probe_target);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_PROBED, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_SHARED, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_OPTIONS, options);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_SEQUENCE, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_CHECKSUM, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_TICKS, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_THREAD_A, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_THREAD_B, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_MESSAGES, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_VERDICT, ZX_GV_NONE);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_FAULT_STATUS, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_FAULT_ADDRESS, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_STAGE1, ZX_GS_NONE);

    /* The second granule: what a preemptive guest's timer interrupt
       reports.  Zeroed here for the same reason as everything above, and it
       matters more here than anywhere else -- these words are written by a
       HANDLER and are outside the guest's sealed snapshot, so a stale value
       has nothing to fail against.  */

    zx_guest_mailbox_write(launch_ptr, ZX_GD_IRQ_COUNT, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_TIMER_INTID, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_ODD_INTID, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_SPIN_A, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_SPIN_B, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_WAKES, 0U);

    /* And what a guest that keeps running after its verdict reports: its
       own liveness counter, and the two clocks it is the only party able to
       read.  Zeroed for the same reason as everything above, and it matters
       most here: "this partition's clock did not move" and "this partition
       never wrote its clock" are different findings, and a stale value from
       a previous excursion would make the first look like the second.  */

    zx_guest_mailbox_write(launch_ptr, ZX_GD_LIVE, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_VCT_START, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_VCT_NOW, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_TICKS_NOW, 0U);

    /* The third granule: the isolation matrix, and what a partition is
       doing while its neighbour is being measured.
     *
       ZEROED HERE AND ASKED FOR SEPARATELY.  Every one of these is either
       an address only the hypervisor can supply or a report only the guest
       can make, and none belongs in this function's argument list: a
       handover taking eight more addresses would be a handover most images
       passed eight zeroes to.  The regression image calls
       zx_guest_ask_for_matrix after this, and every other image simply
       does not -- so a zero here is what "no sweep was asked for" means,
       and the guest's own first test is that the case mask is non-zero.
     *
       ZERO IS THE RIGHT ABSENT VALUE FOR ALL OF THEM.  An address of zero
       is refused by the sweep with ZX_MR_NO_ADDRESS rather than probed,
       which matters: the alternative -- leaving whatever the copy put there
       -- would have a guest reach for an address nobody chose and report a
       fault nobody can attribute.  */

    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_CASES, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_NEIGHBOUR, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_NEIGHBOUR_CODE, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_HOLE, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_HYP_DATA, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_HYP_MMIO, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_MARK_BASE, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_MARK_COUNT, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_ATTEMPTED, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_REFUSED, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_RESUME, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_READ_VALUE, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_MARKS_WRITTEN, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_MARKS_OK, 0U);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_BEHAVIOUR, ZX_GB_QUIET);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_PHASE_SEEN, 0U);

    __asm__ volatile("dsb" ::: "memory");
}


/**************************************************************************/
/*  zx_guest_ask_for_matrix -- the isolation sweep, described.            */
/*                                                                        */
/*  SEPARATE FROM THE HANDOVER, and deliberately.  Only one image asks     */
/*  for a sweep; folding six addresses into zx_guest_hand_over would make  */
/*  every other image pass six zeroes to say it did not want one, and a    */
/*  parameter that is zero at almost every call site is a parameter nobody */
/*  reads.  Called after the handover, which has already zeroed all of     */
/*  these, so the words this does not set stay absent rather than stale.   */
/*                                                                        */
/*  A DSB AT THE END, because the guest is ERETed into after this and the  */
/*  first thing its sweep does is read these words.  The hypervisor's own  */
/*  caches are off, so this is currently redundant -- and it is here       */
/*  anyway, for the same reason the loader's cache maintenance is: the     */
/*  change that turns caches on will be made by somebody with no reason to */
/*  think about a mailbox.                                                 */
/**************************************************************************/

void zx_guest_ask_for_matrix(const ZX_GUEST_LAUNCH *launch_ptr,
                             const ZX_GUEST_MATRIX *matrix_ptr)
{
    if ((launch_ptr == (const ZX_GUEST_LAUNCH *)0)
        || (matrix_ptr == (const ZX_GUEST_MATRIX *)0))
    {
        return;
    }

    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_NEIGHBOUR,
                           matrix_ptr->zx_matrix_neighbour);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_NEIGHBOUR_CODE,
                           matrix_ptr->zx_matrix_neighbour_code);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_HOLE,
                           matrix_ptr->zx_matrix_hole);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_HYP_DATA,
                           matrix_ptr->zx_matrix_hyp_data);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_HYP_MMIO,
                           matrix_ptr->zx_matrix_hyp_mmio);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_MARK_BASE,
                           matrix_ptr->zx_matrix_mark_base);
    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_MARK_COUNT,
                           matrix_ptr->zx_matrix_mark_count);

    /* THE CASE MASK LAST, and it is the only word whose order matters.  It
       is what the guest tests before it reads any of the others, so writing
       it first would leave a window -- if a partition somehow ran between
       the two -- in which the sweep was asked for and its addresses were
       still zero.  Nothing can run between them today; the ordering costs
       one line and removes the question.  */

    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_CASES,
                           matrix_ptr->zx_matrix_cases);

    __asm__ volatile("dsb" ::: "memory");
}


/**************************************************************************/
/*  zx_guest_set_behaviour -- what an untrusted partition does next.      */
/*                                                                        */
/*  ONE WORD, RE-READ BY THE GUEST ON EVERY ITERATION of its endless       */
/*  phase, which is what lets one run put a partition through every row of */
/*  the determinism table while its neighbour is measured continuously.    */
/*  Six builds would have been the obvious shape and it is the weaker one: */
/*  comparing the critical partition's period across six runs compares     */
/*  RUNS, and a difference between two runs has a dozen explanations a     */
/*  difference between two phases of one run does not.                     */
/**************************************************************************/

void zx_guest_set_behaviour(const ZX_GUEST_LAUNCH *launch_ptr,
                            uint32_t behaviour)
{
    if (launch_ptr == (const ZX_GUEST_LAUNCH *)0)
    {
        return;
    }

    zx_guest_mailbox_write(launch_ptr, ZX_GD_M_BEHAVIOUR, behaviour);

    __asm__ volatile("dsb" ::: "memory");
}


/**************************************************************************/
/*  zx_guest_run -- one excursion, measured.                              */
/*                                                                        */
/*  The PMU counter is read either side rather than a timer, because       */
/*  CNTFRQ reads zero on both ZoneX targets and there is nothing to        */
/*  convert with.  Cycles are also the unit a worst-case-execution-time    */
/*  argument is made in, so no conversion is wanted.                       */
/**************************************************************************/

uint32_t zx_guest_run(const ZX_GUEST_LAUNCH *launch_ptr,
                      ZX_PARTITION_CB *partition_ptr,
                      uint32_t *cycles_ptr)
{
    zx_addr_t entry = partition_ptr->zx_partition_load.zx_load_entry;
    uint32_t  start;
    uint32_t  outcome;

    zx_fault_record_reset(zx_el2_fault_record());

    /* The tag comes from the partition the hypervisor SCHEDULED, which is
       the only party that knows it.  A guest that prefixed its own lines
       could claim to be another partition, and every line of a captured log
       would then be evidence of nothing.  */

    zx_guest_console_attach(launch_ptr->zx_launch_partition_id,
                            launch_ptr->zx_launch_partition_name);

    /* The guest's virtual clock starts running again HERE and is frozen
       again below, so that the time a partition can observe is the time it
       actually spent on the core.  With one partition the gap being closed
       is the hypervisor's own printing between passes; with two it is the
       other partition's window.  See docs/decisions.md D7.  */

    if (launch_ptr->zx_launch_freeze_time != 0U)
    {
        zx_el2_guest_time_resume();
    }
    else
    {
        zx_el2_guest_time_resume_uncredited();
    }

    start = zx_pmu_cycles();

    /* The argument is zero and is not a mailbox pointer.  A real kernel's
       reset path clobbers r0 within two instructions of the ERET, so
       anything passed in it would be gone before any C ran -- which is
       exactly why the mailbox is at a fixed offset in the window instead.  */

    outcome = zx_el2_run_payload(entry, 0U);

    *cycles_ptr = zx_pmu_cycles() - start;

    /* THE GUEST'S TIMER IS STOPPED BEFORE ANYTHING ELSE RUNS.  A partition
       that yielded with its virtual timer armed has left a level asserted at
       the GIC; the hypervisor runs with interrupts masked so it would not be
       taken here, but it would still be pending at the next ERET into a
       guest that has not yet reinitialised its own kernel.  Stopping it is
       one register write and it is per-guest state a partition switch has to
       handle anyway.  */

    zx_el2_guest_timer_stop();

    /* ALWAYS, even in a build whose freeze is switched off.  This records
       WHEN the partition stopped and what its own clock read then, which is
       what the freeze is checked against -- a build that skipped it would
       have moved the measurement rather than broken the mechanism.  */

    zx_el2_guest_time_suspend();

    zx_guest_console_detach();

    zx_partition_returned(partition_ptr, zx_el2_fault_record());

    return outcome;
}


/**************************************************************************/
/*  zx_guest_report                                                       */
/*                                                                        */
/*  The checksum is verified before anything the guest reported is         */
/*  believed, and that ordering is the point.  Three failures it catches:  */
/*  a window nobody ever wrote (every field zero, which the magic in the   */
/*  checksum makes fail), a guest torn off mid-update, and a value read    */
/*  out of the WRONG partition's window -- the sentinel the hypervisor     */
/*  itself planted is folded in, so a report can be attributed.           */
/**************************************************************************/

uint32_t zx_guest_report(const ZX_GUEST_LAUNCH *launch_ptr)
{
    uint32_t progress = zx_guest_mailbox_read(launch_ptr, ZX_GD_PROGRESS);
    uint32_t sequence = zx_guest_mailbox_read(launch_ptr, ZX_GD_SEQUENCE);
    uint32_t checksum = zx_guest_mailbox_read(launch_ptr, ZX_GD_CHECKSUM);
    uint32_t expected = (uint32_t)zx_guest_report_checksum(
        zx_guest_mailbox_read(launch_ptr, ZX_GD_SCRATCH), progress, sequence,
        zx_guest_mailbox_read(launch_ptr, ZX_GD_TICKS),
        zx_guest_mailbox_read(launch_ptr, ZX_GD_THREAD_A),
        zx_guest_mailbox_read(launch_ptr, ZX_GD_THREAD_B),
        zx_guest_mailbox_read(launch_ptr, ZX_GD_MESSAGES),
        zx_guest_mailbox_read(launch_ptr, ZX_GD_VERDICT));

    zx_console_puts("\n--- what the guest reported, read out of its own "
                    "memory ---\n");
    zx_note("progress bits   ", progress);
    zx_note("sequence        ", sequence);
    zx_note("checksum        ", checksum);
    zx_note("checksum expected", expected);
    zx_note("sentinel        ", zx_guest_mailbox_read(launch_ptr, ZX_GD_SCRATCH));
    zx_note("guest ticks     ", zx_guest_mailbox_read(launch_ptr, ZX_GD_TICKS));
    zx_note("producer slices ", zx_guest_mailbox_read(launch_ptr, ZX_GD_THREAD_A));
    zx_note("consumer slices ", zx_guest_mailbox_read(launch_ptr, ZX_GD_THREAD_B));
    zx_note("messages carried", zx_guest_mailbox_read(launch_ptr, ZX_GD_MESSAGES));
    zx_note("guest verdict   ", zx_guest_mailbox_read(launch_ptr, ZX_GD_VERDICT));
    zx_note("stage-1 vector  ", zx_guest_mailbox_read(launch_ptr, ZX_GD_STAGE1));
    zx_note("stage-1 DFSR    ", zx_guest_mailbox_read(launch_ptr,
                                                      ZX_GD_FAULT_STATUS));
    zx_note("stage-1 DFAR    ", zx_guest_mailbox_read(launch_ptr,
                                                      ZX_GD_FAULT_ADDRESS));

    zx_check("the guest's report is sealed: the sequence advanced and the\n"
             "         checksum agrees, with the hypervisor's own sentinel\n"
             "         folded into it -- so this is THIS partition's report,\n"
             "         whole, and not a torn or misattributed one",
             ((sequence != 0U) && (checksum == expected)) ? 1U : 0U);

    return progress;
}
