/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_one_partition.c                                     SHARED       */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    One REAL ThreadX kernel, booting at EL1 inside a stage-2 confined   */
/*    partition that ZoneX loaded and launched.                           */
/*                                                                        */
/*    Everything before this image ran a payload written to be run: a few */
/*    dozen instructions with no kernel, no stack use worth the name and  */
/*    no vectors of its own.  This one loads a whole kernel, which is the */
/*    difference between "stage 2 works" and "a hypervisor works".        */
/*                                                                        */
/*  THE FIVE THINGS THIS IMAGE PROVES, AND HOW                            */
/*                                                                        */
/*    1.  A real kernel BOOTS in a partition.  The guest sets progress    */
/*        bits at four milestones, each of which the one before it        */
/*        cannot fake, and the hypervisor reads them out of the guest's   */
/*        memory afterwards rather than trusting anything the guest       */
/*        printed.                                                        */
/*                                                                        */
/*    2.  It SCHEDULES.  Two threads, a queue between them and a          */
/*        semaphore -- the ported context switch running underneath a     */
/*        stage-2 MPU, with every message checked by value and not by     */
/*        count.                                                          */
/*                                                                        */
/*    3.  It PRINTS through the hypervisor.  One hypercall per character, */
/*        tagged with the partition the hypervisor scheduled, so a guest  */
/*        cannot claim to be another one.                                 */
/*                                                                        */
/*    4.  ITS OWN MPU IS LIVE UNDERNEATH STAGE 2, and the two stages are  */
/*        distinguishable.  A stage-1 fault is taken to EL1 and reaches   */
/*        the hypervisor only because the guest's own vector tells it; a  */
/*        stage-2 violation is taken to EL2 and reported there.  Two      */
/*        different reports from two different privilege levels.          */
/*                                                                        */
/*    5.  WHAT ZONEX COSTS.  The guest is run twice, once with HCR.VM     */
/*        clear and once set, and the difference is the first honest      */
/*        number for "what does the hypervisor cost" -- which somebody    */
/*        will ask.                                                       */
/*                                                                        */
/*  WHAT A PASS DOES NOT MEAN                                             */
/*                                                                        */
/*    On the Armv8-R AEM FVP a pass proves the code is right and says     */
/*    NOTHING about timing: the model is functional, not cycle-accurate,  */
/*    and it reports a region count no Cortex-R52 can have.  Every        */
/*    number this image prints has to come from silicon before it is      */
/*    quoted.  The image says so in its own output rather than leaving it */
/*    to this comment.                                                    */
/*                                                                        */
/*    On lockstep silicon it demonstrates memory isolation on ONE logical */
/*    core.  It does not demonstrate spatial multicore partitioning.      */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"
#include "zx_platform.h"
#include "zx_guest_abi.h"
#include "zx_manifest.h"
#include "zx_mm.h"
#include "zx_partition.h"
#include "zx_guest_console.h"
#include "zx_guest_launch.h"

/* THE GUEST'S HYPERCALL NUMBERS AND THE HYPERVISOR'S MUST AGREE, and this
   is the only translation unit that can see both spellings.  The guest is a
   separate program with its own toolchain invocation and cannot include
   zx_fault.h; it restates the contract in zx_guest_abi.h.  Asserting the two
   against each other here turns a renumbered immediate into a failed BUILD
   rather than a guest whose console output vanishes on the model.  */

_Static_assert(ZX_HVC_GUEST_NOP == (int)ZX_HVC_NOP,
               "the guest and the hypervisor disagree about HVC #0");
_Static_assert(ZX_HVC_GUEST_YIELD == (int)ZX_HVC_YIELD,
               "the guest and the hypervisor disagree about the yield HVC");
_Static_assert(ZX_HVC_GUEST_PUTC == (int)ZX_HVC_PUTC,
               "the guest and the hypervisor disagree about the console HVC");

/* The embedded guest image and partition A's window, from the linker
   script.  */

extern char __zx_guest_a_blob_start[];
extern char __zx_guest_a_blob_end[];
extern char __zx_partition_a_start[];
extern char __zx_partition_a_end[];
extern char __zx_partition_a_hole_start[];

#define ZX_PARTITION_A_ID       1U
#define ZX_PARTITION_A_INDEX    0U

/* The sentinel the hypervisor leaves in the guest's mailbox, and which the
   guest folds into every checksum.  Distinct from the probe payload's so
   that a log from one image cannot be misread as the other's.  */

#define ZX_GUEST_A_SENTINEL     0xA5A5000AU

static ZX_REGION        zx_regions_a[1];
static ZX_PARTITION     zx_partitions[1];
static ZX_MANIFEST      zx_manifest;
static ZX_MM_LAYOUT     zx_layout;
static ZX_MANIFEST_ENV  zx_env;
static ZX_PARTITION_CB  zx_partition_a;
static ZX_REGION        zx_mmio[ZX_BOARD_MAX_MMIO_REGIONS];

/* Where partition A's guest lives, for the shared launcher in
   zx_guest_launch.c.  Filled at run time rather than being a static
   initialiser, because every field is the address of a LINKER symbol and the
   address of a linker symbol is not a constant expression.  */

static ZX_GUEST_LAUNCH  zx_launch;


static void zx_describe_launch(void)
{
    zx_launch.zx_launch_window_base   =
        zx_symbol_address(__zx_partition_a_start);
    zx_launch.zx_launch_window_end    =
        zx_symbol_address(__zx_partition_a_end);
    zx_launch.zx_launch_image_start   =
        zx_symbol_address(__zx_guest_a_blob_start);
    zx_launch.zx_launch_image_end     =
        zx_symbol_address(__zx_guest_a_blob_end);
    zx_launch.zx_launch_sentinel      = ZX_GUEST_A_SENTINEL;
    zx_launch.zx_launch_partition_id  = ZX_PARTITION_A_ID;
    zx_launch.zx_launch_partition_name = zx_partitions[0].zx_partition_name;

    /* This guest has no clock and reads none, so the freeze has nothing to
       freeze -- and it is switched ON anyway, because the code path that
       runs in every image is the code path that stays correct.  */
    zx_launch.zx_launch_freeze_time   = 1U;
}


/**************************************************************************/
/*  zx_build_manifest                                                     */
/*                                                                        */
/*  ONE PARTITION, ONE REGION, and both of those are worth a sentence.     */
/*                                                                        */
/*  One partition because two are the next step and adding them here      */
/*  would mean debugging a launch path and a time-partition scheduler at   */
/*  once.  One region because the guest's code and data are CONTIGUOUS in  */
/*  a single window: a partition split across two far-apart areas produces */
/*  a blob the size of the gap between them under objcopy -O binary, which */
/*  on the silicon target is 1.2 GB.                                      */
/*                                                                        */
/*  The window is therefore both executable and writable at stage 2, and   */
/*  that is not a weakness in the isolation claim -- it is where the       */
/*  division of labour between the two stages shows.  Stage 2 says which   */
/*  MEMORY a partition owns; the guest's own stage-1 MPU says which parts  */
/*  of it are code.  The loader needs the window writable anyway.          */
/**************************************************************************/

static void zx_build_manifest(uint32_t board_regions)
{
    zx_regions_a[0].zx_region_base  =
        zx_symbol_address(__zx_partition_a_start);
    zx_regions_a[0].zx_region_limit =
        zx_symbol_address(__zx_partition_a_end) - 1U;
    zx_regions_a[0].zx_region_ap    = ZX_AP_EL2_RW_GUEST_RW;
    zx_regions_a[0].zx_region_xn    = ZX_XN_EXECUTABLE;
    zx_regions_a[0].zx_region_sh    = ZX_SH_NON_SHAREABLE;
    zx_regions_a[0].zx_region_attr_index = (UCHAR)ZX_ATTR_NORMAL_WB;

    zx_partitions[0].zx_partition_id           = ZX_PARTITION_A_ID;
    zx_partitions[0].zx_partition_name         = "ThreadX guest A";
    zx_partitions[0].zx_partition_image_start  =
        zx_symbol_address(__zx_guest_a_blob_start);
    zx_partitions[0].zx_partition_image_end    =
        zx_symbol_address(__zx_guest_a_blob_end);
    zx_partitions[0].zx_partition_entry        =
        zx_symbol_address(__zx_partition_a_start) + ZX_GUEST_IMAGE_OFF_ENTRY;
    zx_partitions[0].zx_partition_regions      = zx_regions_a;
    zx_partitions[0].zx_partition_region_count = 1U;
    zx_partitions[0].zx_partition_window_ticks = 10U;

    zx_manifest.zx_manifest_partitions        = zx_partitions;
    zx_manifest.zx_manifest_partition_count   = 1U;
    zx_manifest.zx_manifest_shared            = (const ZX_SHARED *)0;
    zx_manifest.zx_manifest_shared_count      = 0U;
    zx_manifest.zx_manifest_major_frame_ticks = 10U;

    zx_board_describe_mmio_regions(zx_mmio);

    zx_env.zx_env_mmio_regions      = zx_mmio;
    zx_env.zx_env_mmio_region_count = board_regions;

    /* HMAIR indices this image programmed -- 0, 1 and 2.  A region naming
       any other index would get a zero MAIR byte, which is Device-nGnRnE:
       memory that works, slowly, with nothing to fault on.  */
    zx_env.zx_env_attr_written_mask = 0x07U;
}


/**************************************************************************/
/*  zx_el2_main -- entered from zx_el2_entry.S at EL2.  Does not return.  */
/**************************************************************************/

ZX_NORETURN void zx_el2_main(void)
{
    uint32_t board_regions;
    uint32_t el2_regions;
    uint32_t status;
    uint32_t outcome;
    uint32_t progress;
    uint32_t cycles_without_stage2 = 0U;
    uint32_t cycles_with_stage2 = 0U;
    uint32_t probe_target = 0U;
    ZX_MANIFEST_FAULT fault;

    /* ---------------------------------------------------------------- */
    /*  BEFORE THE FIRST PRINT.                                        */
    /*                                                                  */
    /*  On a board whose console sits below 0x60000000 the background   */
    /*  map reaches it as NORMAL memory, and Normal memory permits the  */
    /*  gathering and reordering that corrupts a polled UART -- with    */
    /*  caches off, and regardless of HSCTLR.BR, because BR grants      */
    /*  permission and not attributes.  So HMAIR, the hypervisor's own  */
    /*  MMIO regions and HSCTLR.M come up FIRST.  Measured on the       */
    /*  S32Z280; see docs/decisions.md D15.                            */
    /* ---------------------------------------------------------------- */

    el2_regions   = zx_el2_region_count();
    board_regions = zx_board_mmio_region_count();

    if (el2_regions >= board_regions)
    {
        zx_mair_program();

        if (board_regions > 0U)
        {
            zx_board_program_mmio_regions(0U);
        }

        zx_el2_mpu_enable();
    }

    zx_board_init();

    zx_console_puts(
        "\n"
        "=========================================================\n"
        " Eclipse ThreadX ZoneX -- one ThreadX guest at EL1\n"
        " " ZX_PLATFORM_NAME "\n"
        " Armv8-R AArch32, EL2, PMSAv8-R at both stages\n"
        "=========================================================\n"
        "\n"
        " ZoneX is resident at EL2.  It reads a manifest, validates it,\n"
        " turns it into one stage-2 region, copies a REAL ThreadX kernel\n"
        " into that region, and ERETs into it.  The guest runs threads,\n"
        " passes messages, prints through the hypervisor and reports\n"
        " back through a mailbox in its own memory.\n"
        "\n"
        " One partition.  Time partitioning and a second guest come\n"
        " later, and each of them assumes what this image establishes.\n");

    zx_fault_record_reset(zx_el2_fault_record());
    zx_guest_console_reset();

    zx_console_puts("\n--- the EL2 MPU is already on ---\n");
    zx_note("HSCTLR now", zx_read_hsctlr());
    zx_check("HSCTLR.M is set, so the EL2 MPU is live",
             ((zx_read_hsctlr() & ZX_HSCTLR_M) != 0U) ? 1U : 0U);
    zx_check("HSCTLR.BR is set, so EL2's own code and data fall back to the\n"
             "         background map and cost no region",
             ((zx_read_hsctlr() & ZX_HSCTLR_BR) != 0U) ? 1U : 0U);

    zx_console_puts("\n--- identity, as the core reports it ---\n");
    zx_note("MIDR         ", zx_read_midr());
    zx_note("EL2 regions  ", el2_regions);
    zx_note("EL1 regions  ", zx_el1_region_count());
    zx_note("CNTFRQ       ", zx_read_cntfrq());
    zx_note("D-cache line ", zx_cache_dcache_line_bytes());
    zx_note("I-cache line ", zx_cache_icache_line_bytes());
    zx_console_puts("               the stride the loader's maintenance loop\n"
                    "               uses.  A loop that strode wrongly does not\n"
                    "               fail -- it leaves lines untouched -- so the\n"
                    "               number belongs in the log.\n");
    zx_board_report();

    if (el2_regions == 0U)
    {
        zx_console_puts("\n  *** HMPUIR reports ZERO EL2 regions, so this "
                        "target cannot host\n  *** stage 2 at all.  Refusing "
                        "to go on.\n"
                        "\nZONEX RESULT: FAILED -- the target cannot host "
                        "stage 2\n");
        zx_console_exit(1U);
    }

    /* ---------------------------------------------------------------- */
    /*  The manifest, and the plan it produces.                        */
    /* ---------------------------------------------------------------- */

    zx_build_manifest(board_regions);
    zx_describe_launch();
    zx_env.zx_env_region_budget = el2_regions;

    status = zx_manifest_verify(&zx_manifest, &zx_env, &fault);

    zx_console_puts("\n--- the manifest, checked before anything is "
                    "programmed ---\n");
    zx_note("zx_manifest_verify", status);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_note("  offending partition", fault.zx_fault_partition);
        zx_note("  offending region   ", fault.zx_fault_region);
        zx_check("the manifest passes every rule", 0U);
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_check("the manifest passes every rule", 1U);

    status = zx_mm_plan(&zx_manifest, board_regions, el2_regions, &zx_layout);
    zx_note("zx_mm_plan", status);
    zx_check("the layout fits this part's region budget",
             (status == ZX_MANIFEST_SUCCESS) ? 1U : 0U);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_mm_report(&zx_layout, &zx_manifest);

    /* ---------------------------------------------------------------- */
    /*  The loader: decide, check, copy.                               */
    /* ---------------------------------------------------------------- */

    zx_partition_reset(&zx_partition_a, &zx_partitions[0]);

    status = zx_partition_prepare(&zx_partition_a);
    zx_note("zx_partition_prepare", status);
    zx_check("the loader located the window the entry point is in, and the\n"
             "         image fits THAT window rather than merely some\n"
             "         executable region of the partition",
             (status == ZX_MANIFEST_SUCCESS) ? 1U : 0U);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_partition_report(&zx_partition_a);
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    if (zx_guest_image_check(&zx_launch) == 0U)
    {
        zx_console_puts("\n  *** REFUSING to launch this image.  It is either\n"
                        "  *** absent, truncated, or built for a different\n"
                        "  *** window -- and a guest built for a different\n"
                        "  *** window STARTS before it goes wrong.\n"
                        "\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_partition_report(&zx_partition_a);

    /* ---------------------------------------------------------------- */
    /*  Region programming, and read-back.                             */
    /*                                                                  */
    /*  The read-back is not ceremony.  A region whose base was          */
    /*  under-aligned programs successfully with its low bits landing on */
    /*  SH, AP and XN, and neither faults.  Comparing what the register  */
    /*  holds against what was asked for is the only way either becomes  */
    /*  visible, and it costs one read per region once at boot.         */
    /* ---------------------------------------------------------------- */

    {
        uint32_t index =
            (uint32_t)zx_layout.zx_layout_partition_first[ZX_PARTITION_A_INDEX];

        zx_stage2_region_program(index, &zx_regions_a[0]);

        zx_console_puts("\n--- the region set, programmed and read back ---\n");
        zx_note("partition A region index", index);
        zx_check("partition A's window reads back as the manifest declared it",
                 zx_stage2_region_matches(index, &zx_regions_a[0]));

        zx_stage2_enable_set(
            zx_mm_partition_mask(&zx_layout, ZX_PARTITION_A_INDEX));
        zx_note("HPRENR now", zx_hprenr_read());
    }

    zx_console_puts("\n  the ungranted granule immediately after the window "
                    "is at ");
    zx_console_puthex(zx_symbol_address(__zx_partition_a_hole_start));
    zx_console_puts("\n  it begins at the byte after the window's limit, "
                    "which is what\n  makes a limit one granule too generous "
                    "visible\n");

    /* ---------------------------------------------------------------- */
    /*  The EL2-only configuration the guest cannot do for itself.      */
    /*                                                                  */
    /*  A standalone Cortex-R52 kernel resets INTO EL2 and does this in  */
    /*  its own boot path.  Built as a guest it skips that block, which  */
    /*  is exactly what the port's TX_R52_BOOT_AT_EL1 option is for, so  */
    /*  the work changes owner rather than ceasing to be necessary.      */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- what ZoneX takes over from the guest's boot path "
                    "---\n");
    zx_note("CNTFRQ before", zx_read_cntfrq());
    zx_el2_prepare_guest_el1(zx_board_counter_hz());
    zx_note("CNTFRQ after ", zx_read_cntfrq());
    zx_check("CNTFRQ is programmed, because it is writable only at the\n"
             "         highest implemented exception level -- a guest booting\n"
             "         at EL1 cannot write it and would read zero, and any\n"
             "         tick interval derived from that divides by zero",
             (zx_read_cntfrq() == zx_board_counter_hz()) ? 1U : 0U);
    zx_console_puts("  HCPTR.TCP10/TCP11 cleared, so a guest may use its FPU\n"
                    "  without every access trapping to EL2.  ZoneX does NOT\n"
                    "  yet save or restore floating-point state across a\n"
                    "  partition switch, which is correct with one partition\n"
                    "  and a defect with two.\n"
                    "  CNTHCTL.PL1PCTEN/PL1PCEN left CLEAR on purpose: a\n"
                    "  partition must not reach the PHYSICAL counter, whose\n"
                    "  time keeps running while the partition is descheduled.\n"
                    "  Guests get the virtual timer and a per-partition\n"
                    "  CNTVOFF instead, which is what freezes a descheduled\n"
                    "  partition's clock.\n");

    /* CNTVOFF, set so that the partition's own clock reads zero when it
       starts.  This guest never reads it -- it takes no interrupts and asks
       for no tick -- and the offset is programmed anyway, because CNTVOFF is
       UNKNOWN out of reset and a register a guest can read must not be left
       holding whatever the part came up with.  What it is FOR is next door,
       in the preemptive image.  */

    zx_el2_guest_time_reset();

    zx_pmu_enable();

    /* ---------------------------------------------------------------- */
    /*  PASS ONE: the guest with stage 2 OFF.                          */
    /*                                                                  */
    /*  This is the "what does ZoneX cost" measurement, and it is run    */
    /*  FIRST so that the number is taken before the run that may fault. */
    /*  No probe target: the cost of running a guest and the cost of     */
    /*  stopping one are different questions.                           */
    /* ---------------------------------------------------------------- */

    /* ---------------------------------------------------------------- */
    /*  PASS ZERO: a WARM-UP that is deliberately not measured.         */
    /*                                                                  */
    /*  MEASURED, THEN THROWN AWAY, and the reason is a real result      */
    /*  rather than caution.  The first version of this image measured   */
    /*  two passes and no more, and on silicon the pass WITH stage 2     */
    /*  came out 28% FASTER than the pass without it -- 27,202 cycles    */
    /*  against 38,002.  A hypervisor does not give cycles back, so the  */
    /*  difference was not stage 2 at all: it was that the two passes    */
    /*  differed in ORDER as well as in HCR.VM, and on a real core the   */
    /*  first execution of anything is not comparable to the second.     */
    /*  Branch prediction and the instruction path are warm the second   */
    /*  time and cold the first.                                        */
    /*                                                                  */
    /*  A pair that differs in two things measures neither.  So the      */
    /*  first excursion is spent warming the core and its result is      */
    /*  discarded, which leaves the two measured passes differing in     */
    /*  exactly one bit of hypervisor configuration.                     */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- a warm-up excursion, measured and discarded ---\n"
                    "  On a real core the FIRST execution of anything is not\n"
                    "  comparable to the second, so a pair of passes that\n"
                    "  differed in order as well as in HCR.VM would measure\n"
                    "  neither.  This pass exists to be thrown away.\n");

    zx_guest_image_load(&zx_partition_a.zx_partition_load);
    zx_guest_hand_over(&zx_launch, 0U, ZX_GO_QUIET);
    zx_partition_loaded(&zx_partition_a);

    zx_check("the partition may be entered now that its image is loaded",
             zx_partition_enter(&zx_partition_a));

    {
        uint32_t warm_cycles = 0U;

        outcome = zx_guest_run(&zx_launch, &zx_partition_a, &warm_cycles);
        zx_note("warm-up excursion, cycles (discarded)", warm_cycles);
    }

    zx_check("the warm-up guest reached its own verdict, which rules out the\n"
             "         loader, the entry point and the kernel before stage 2\n"
             "         is added as a variable",
             ((zx_guest_mailbox_read(&zx_launch, ZX_GD_PROGRESS)
               & (uint32_t)ZX_GP_FINISHED) != 0U) ? 1U : 0U);

    zx_console_puts("\n=========================================================\n"
                    " PASS 1 of 3: the guest with HCR.VM CLEAR, and QUIET\n"
                    "=========================================================\n"
                    "  Stage 2 does not apply, so the guest is confined only\n"
                    "  by its OWN MPU.  This is the baseline the cost of\n"
                    "  stage 2 is measured against; it is not a mode ZoneX\n"
                    "  would ever run a partition in.\n"
                    "\n"
                    "  THE CONSOLE IS OFF FOR THIS PASS AND THE NEXT, and that\n"
                    "  is what makes the measurement mean anything.  The\n"
                    "  guest's console is one hypercall PER CHARACTER through\n"
                    "  a polled UART: on silicon that is three orders of\n"
                    "  magnitude more work than everything else the guest\n"
                    "  does, so a loud run can only BOUND the cost of stage 2\n"
                    "  from above and cannot resolve it.  Same image, one word\n"
                    "  in the mailbox -- so the run being measured is the run\n"
                    "  being demonstrated in pass 3.\n");

    zx_guest_image_load(&zx_partition_a.zx_partition_load);
    zx_guest_hand_over(&zx_launch, 0U, ZX_GO_QUIET);

    zx_check("the partition may be entered again after yielding",
             zx_partition_enter(&zx_partition_a));

    outcome = zx_guest_run(&zx_launch, &zx_partition_a, &cycles_without_stage2);
    zx_note("outcome", outcome);
    progress = zx_guest_report(&zx_launch);

    zx_check("with stage 2 off, the guest reached its own verdict",
             (((progress & (uint32_t)ZX_GP_FINISHED) != 0U)
              && (outcome == ZX_RUN_YIELDED)) ? 1U : 0U);
    zx_check("and nothing has printed yet, so the quiet option really is\n"
             "         quiet and the cycles above are the guest's own work",
             (zx_guest_console_characters() == 0U) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  PASS TWO: stage 2 on, and whatever this build was built to      */
    /*  demonstrate.                                                    */
    /* ---------------------------------------------------------------- */

#ifdef ZX_ONE_PROBE_OUTSIDE
    probe_target = (uint32_t)zx_symbol_address(__zx_partition_a_hole_start);
#endif
#ifdef ZX_ONE_PROBE_STAGE1
    probe_target = (uint32_t)(zx_symbol_address(__zx_partition_a_start)
                              + ZX_GUEST_IMAGE_OFF_ENTRY);
#endif
#ifdef ZX_ONE_PROBE_GRANTED

    /* ZX_GD_PROBE_SCRATCH and not offset zero, which is ZX_GD_PROGRESS.  The
       probe WRITES a sentinel to whatever it is aimed at, so a target inside
       the guest's own report corrupts the report -- and the seal then
       certifies the corrupted value, which is worse than not checking at
       all.  See the note on ZX_GD_PROBE_SCRATCH in zx_guest_abi.h.  */

    probe_target = (uint32_t)(zx_symbol_address(__zx_partition_a_start)
                              + ZX_GUEST_IMAGE_OFF_MAILBOX
                              + ZX_GD_PROBE_SCRATCH);
#endif

    zx_console_puts("\n=========================================================\n"
                    " PASS 2 of 3: the same guest with HCR.VM SET, still QUIET\n"
                    "=========================================================\n"
                    "  The same work as pass 1, with stage 2 in force.  The\n"
                    "  difference between the two figures is what stage 2\n"
                    "  costs a guest, and it is the only pair in this run\n"
                    "  that is comparable: identical work, identical console\n"
                    "  traffic (none), one bit of hypervisor configuration\n"
                    "  apart.\n");

    zx_guest_image_load(&zx_partition_a.zx_partition_load);
    zx_guest_hand_over(&zx_launch, 0U, ZX_GO_QUIET);

    zx_stage2_enable();
    zx_note("HCR now", zx_read_hcr());
    zx_check("HCR.VM is set, so stage 2 applies to EL0/EL1",
             ((zx_read_hcr() & ZX_HCR_VM) != 0U) ? 1U : 0U);
    zx_check("HCR.HCD is clear, so HVC is still available -- which the guest's\n"
             "         console depends on, one hypercall per character",
             ((zx_read_hcr() & ZX_HCR_HCD) == 0U) ? 1U : 0U);
    zx_check("HCR.TGE is clear, so the guest keeps its own exception vectors\n"
             "         -- without which a stage-1 fault could not be taken to\n"
             "         EL1 and the two stages would be indistinguishable",
             ((zx_read_hcr() & ZX_HCR_TGE) == 0U) ? 1U : 0U);

    zx_check("the partition may be entered again after yielding",
             zx_partition_enter(&zx_partition_a));

    outcome = zx_guest_run(&zx_launch, &zx_partition_a, &cycles_with_stage2);
    zx_note("outcome", outcome);
    progress = zx_guest_report(&zx_launch);

    zx_check("with stage 2 in force, the guest did the same work and reached\n"
             "         the same verdict",
             (((progress & (uint32_t)ZX_GP_FINISHED) != 0U)
              && (outcome == ZX_RUN_YIELDED)) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  PASS THREE: loud, and carrying whatever this build was built to  */
    /*  demonstrate.                                                    */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n=========================================================\n"
                    " PASS 3 of 3: the same guest, LOUD\n"
                    "=========================================================\n"
                    "  Everything below the guest's own output is judged on\n"
                    "  THIS pass.  It is the same image the two measured\n"
                    "  passes ran, printing through the hypervisor one\n"
                    "  hypercall per character, with each line tagged by the\n"
                    "  partition ZoneX scheduled rather than by the guest --\n"
                    "  which is why a guest cannot claim to be another one.\n");

    if (probe_target != 0U)
    {
        zx_console_puts("\n  THIS BUILD ASKS THE GUEST TO PROBE ");
        zx_console_puthex(probe_target);
        zx_console_puts("\n");
    }

    zx_guest_image_load(&zx_partition_a.zx_partition_load);
    zx_guest_hand_over(&zx_launch, probe_target, 0U);

    zx_check("the partition may be entered a third time",
             zx_partition_enter(&zx_partition_a));

    {
        uint32_t loud_cycles = 0U;

        outcome = zx_guest_run(&zx_launch, &zx_partition_a, &loud_cycles);
        zx_note("outcome", outcome);
        zx_note("loud excursion, cycles", loud_cycles);
    }

    progress = zx_guest_report(&zx_launch);

    zx_partition_report(&zx_partition_a);

    if (outcome == ZX_RUN_FAULTED)
    {
        zx_fault_report(zx_el2_fault_record());
    }

    /* ---------------------------------------------------------------- */
    /*  What this build was built to demonstrate.                      */
    /* ---------------------------------------------------------------- */

#if defined(ZX_ONE_PROBE_OUTSIDE)

    zx_console_puts("\n=========================================================\n"
                    " THE DEMONSTRANDUM: a REAL KERNEL stopped at its boundary\n"
                    "=========================================================\n"
                    "  The guest granted ITSELF the granule immediately after\n"
                    "  its window -- its own MPU says it owns memory the\n"
                    "  manifest never gave it -- and then wrote to it.  Stage 2\n"
                    "  refused anyway, which is what \"the stricter of the two\n"
                    "  stages wins\" means when the two disagree.\n");

    zx_check("the guest was taken from at its boundary rather than yielding",
             (outcome == ZX_RUN_FAULTED) ? 1U : 0U);
    zx_check("the probe did NOT survive, so the write genuinely did not\n"
             "         complete",
             ((progress & (uint32_t)ZX_GP_PROBE_SURVIVED) == 0U) ? 1U : 0U);
    zx_check("the fault is classified as a GUEST violation, not a hypervisor\n"
             "         one -- EC 0x24 and not EC 0x25",
             (zx_fault_classify(zx_el2_fault_record()->zx_fault_hsr)
              == ZX_FAULT_GUEST_VIOLATION) ? 1U : 0U);
    zx_check("HSR.EC is 0x24, a data abort ROUTED to Hyp",
             (zx_fault_ec(zx_el2_fault_record()->zx_fault_hsr)
              == ZX_EC_DABT_ROUTED) ? 1U : 0U);
    zx_check("HDFAR is EXACTLY the address the guest touched, which is what\n"
             "         catches a window whose limit is one granule out",
             (zx_el2_fault_record()->zx_fault_hdfar == probe_target) ? 1U : 0U);
    zx_check("DFSC says NO enabled region covered it, rather than a region\n"
             "         matching and refusing -- 0x04 and not 0x0C",
             (zx_fault_dabt_dfsc(zx_el2_fault_record()->zx_fault_hsr)
              == ZX_DFSC_MPU_MISS) ? 1U : 0U);
    zx_check("and the guest's OWN vectors saw nothing, so this was stage 2\n"
             "         and not stage 1 -- the two are reported by different\n"
             "         code at different privilege levels",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_STAGE1)
              == ZX_GS_NONE) ? 1U : 0U);
    zx_check("the guest PC is inside the partition's window, so it resolves\n"
             "         against guest_a.map by hand",
             ((zx_el2_fault_record()->zx_fault_elr
               >= (uint32_t)zx_symbol_address(__zx_partition_a_start))
              && (zx_el2_fault_record()->zx_fault_elr
                  < (uint32_t)zx_symbol_address(__zx_partition_a_end)))
                 ? 1U : 0U);

#elif defined(ZX_ONE_PROBE_STAGE1)

    zx_console_puts("\n=========================================================\n"
                    " THE DEMONSTRANDUM: a STAGE-1 fault, which EL2 never saw\n"
                    "=========================================================\n"
                    "  The guest wrote to its OWN CODE.  Stage 2 permits that\n"
                    "  -- the loader had to be able to write the window -- and\n"
                    "  the guest's own MPU makes its code read-only, so this is\n"
                    "  the case where the two stages disagree and the STRICTER\n"
                    "  one is stage 1.\n"
                    "\n"
                    "  The abort was therefore taken to EL1, not to EL2.  The\n"
                    "  hypervisor knows about it only because the guest's own\n"
                    "  vector recorded it and handed control back.  That is the\n"
                    "  difference between the two stages, and it is why they\n"
                    "  cannot be confused in this output.\n");

    zx_check("the guest handed control back rather than being taken from at\n"
             "         its stage-2 boundary",
             (outcome == ZX_RUN_YIELDED) ? 1U : 0U);
    zx_check("NO stage-2 fault was captured, so EL2 never saw this at all",
             (zx_fault_classify(zx_el2_fault_record()->zx_fault_hsr)
              == ZX_FAULT_HYPERCALL) ? 1U : 0U);
    zx_check("the guest's own vector reports a DATA ABORT at EL1",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_STAGE1)
              == ZX_GS_DABT) ? 1U : 0U);
    zx_check("its DFAR is exactly the address it was asked to touch",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_FAULT_ADDRESS)
              == probe_target) ? 1U : 0U);
    zx_check("its DFSR is non-zero, so the syndrome was captured rather than\n"
             "         the word merely being written",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_FAULT_STATUS)
              != 0U) ? 1U : 0U);
    zx_check("the probe did NOT survive",
             ((progress & (uint32_t)ZX_GP_PROBE_SURVIVED) == 0U) ? 1U : 0U);

#elif defined(ZX_ONE_PROBE_GRANTED)

    zx_console_puts("\n=========================================================\n"
                    " NEGATIVE BUILD: the probe is aimed somewhere it IS granted\n"
                    "=========================================================\n"
                    "  The guest was asked to write to its own mailbox, which\n"
                    "  both stages permit.  It must SUCCEED, and this run must\n"
                    "  report FAILED.  That is the point: it proves the two\n"
                    "  builds above are capable of failing, and a check whose\n"
                    "  pass condition is the ABSENCE of something has to be.\n"
                    "\n"
                    "  The CTest entry for this build expects FAILED, so this\n"
                    "  build starting to PASS -- meaning the violation stopped\n"
                    "  being detected -- fails the suite.\n");

    zx_check("the probe did not survive an access it IS granted (this check\n"
             "         is EXPECTED TO FAIL, and its failing is the evidence)",
             ((progress & (uint32_t)ZX_GP_PROBE_SURVIVED) == 0U) ? 1U : 0U);
    zx_check("no stage-2 fault was taken (this one is expected to pass: the\n"
             "         access was permitted)",
             (outcome == ZX_RUN_YIELDED) ? 1U : 0U);

#else

    zx_console_puts("\n=========================================================\n"
                    " A REAL THREADX KERNEL, RUNNING UNDER STAGE 2\n"
                    "=========================================================\n");

    zx_check("the guest yielded rather than faulting",
             (outcome == ZX_RUN_YIELDED) ? 1U : 0U);
    zx_check("it reached bsp_main, so the ERET landed and the port's boot\n"
             "         path ran to C",
             ((progress & (uint32_t)ZX_GP_BSP_MAIN) != 0U) ? 1U : 0U);
    zx_check("tx_application_define ran, so the kernel initialised inside a\n"
             "         stage-2 confined window",
             ((progress & (uint32_t)ZX_GP_KERNEL_ENTERED) != 0U) ? 1U : 0U);
    zx_check("both threads took slices, so the ported context switch works\n"
             "         underneath stage 2",
             ((progress & (uint32_t)ZX_GP_THREADS_RAN) != 0U) ? 1U : 0U);
    zx_check("the queue carried every message, checked by VALUE and in order\n"
             "         -- four deliveries of the wrong thing would satisfy a\n"
             "         count",
             ((progress & (uint32_t)ZX_GP_QUEUE_OK) != 0U) ? 1U : 0U);
    zx_check("the semaphore granted once and refused the second get",
             ((progress & (uint32_t)ZX_GP_SEMAPHORE_OK) != 0U) ? 1U : 0U);
    zx_check("the guest published its own verdict, and it is PASSED",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_VERDICT)
              == ZX_GV_PASSED) ? 1U : 0U);
    zx_check("no stage-1 fault was taken, so the guest's own MPU permitted\n"
             "         everything the kernel legitimately did",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_STAGE1)
              == ZX_GS_NONE) ? 1U : 0U);

    zx_console_puts("\n--- the guest printed through the hypervisor ---\n");
    zx_note("characters forwarded", zx_guest_console_characters());
    zx_note("characters with no partition attached",
            zx_guest_console_orphans());
    zx_check("the guest really did print through the hypervisor, one\n"
             "         hypercall per character",
             (zx_guest_console_characters() > 100U) ? 1U : 0U);
    zx_check("and no character arrived while NO partition was attached, which\n"
             "         would mean the run loop and the console disagree about\n"
             "         what is executing",
             (zx_guest_console_orphans() == 0U) ? 1U : 0U);

#endif

    /* ---------------------------------------------------------------- */
    /*  What stage 2 cost.                                             */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- what stage 2 costs a guest ---\n");

    if (zx_pmu_is_running() == 0U)
    {
        zx_console_puts("  the PMU cycle counter is not advancing, so no\n"
                        "  timing is reported.  This is not a check failure:\n"
                        "  a number from a counter that is not running would\n"
                        "  be a very convincing wrong answer.\n");
    }
    else
    {
        zx_note("quiet excursion, HCR.VM clear, cycles", cycles_without_stage2);
        zx_note("quiet excursion, HCR.VM set,   cycles", cycles_with_stage2);

        if (cycles_with_stage2 >= cycles_without_stage2)
        {
            zx_note("stage 2 cost, cycles                ",
                    cycles_with_stage2 - cycles_without_stage2);
        }
        else
        {
            zx_note("stage 2 cost, cycles SAVED          ",
                    cycles_without_stage2 - cycles_with_stage2);
            zx_console_puts(
                "  The run WITH stage 2 was the faster of the two, which is\n"
                "  not a hypervisor that gives cycles back: it means the\n"
                "  difference is below this measurement's noise floor.  Read\n"
                "  it as \"no cost resolvable here\" and not as a saving.\n");
        }

        zx_console_puts(
            "\n"
            "  WHAT THE PAIR IS.  Two excursions of the same guest image doing\n"
            "  the same work with its console suppressed, ERET to hand-back,\n"
            "  differing in one bit of hypervisor configuration: HCR.VM.  So\n"
            "  the difference is attributable, which is the whole reason the\n"
            "  measured passes are quiet.\n"
            "\n"
            "  WHAT IT IS NOT.  It is not \"boot to first thread\": nothing at\n"
            "  EL1 can read PMCCNTR, so the hypervisor can only measure what\n"
            "  it can see either side of the transfer.  And it is not a\n"
            "  per-access figure -- stage 2 is checked by hardware on every\n"
            "  access, so what is being measured is the whole of a real\n"
            "  kernel's boot and scheduling under it, not one lookup.\n"
            "\n"
            "  WHY IT COMES OUT SMALL.  Region descriptors are programmed ONCE\n"
            "  at boot; stage 2 then costs a guest nothing per access that the\n"
            "  MPU was not already going to spend.  The cost that a partition\n"
            "  SWITCH carries is a different number, measured by the two-\n"
            "  partition image, and it is one HPRENR write plus its barriers.\n"
            "\n"
            "  ON A FUNCTIONAL MODEL BOTH NUMBERS MEAN NOTHING.  The FVP does\n"
            "  not model timing; they are printed anyway so that the\n"
            "  measurement path is exercised on every run rather than only\n"
            "  when a board is attached.  The number to quote comes from\n"
            "  silicon.\n");
    }

    /* ---------------------------------------------------------------- */
    /*  Verdict.  The exact strings are what the runners grep for.      */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n=========================================================\n"
                    " what this run does and does not prove\n"
                    "=========================================================\n"
                    " " ZX_PLATFORM_NAME "\n"
                    " EL2 regions available: ");
    zx_console_putdec(el2_regions);
    zx_console_puts("\n"
        "\n"
        " A green run here proves the CODE is right.  It proves nothing\n"
        " about the region budget, the MMIO attributes or ANY TIMING on a\n"
        " real part: the Armv8-R AEM FVP reports a region count no\n"
        " Cortex-R52 can have, its console and GIC land in the Device band\n"
        " of the background map where the S32Z280's do not, and it is a\n"
        " functional model with no notion of cycles.  Both targets have to\n"
        " be run.\n"
        "\n"
        " THE GUEST IS A REAL, UNMODIFIED THREADX.  The kernel sources and\n"
        " the Cortex-R52 port are built exactly as they are built\n"
        " standalone; what differs is one existing build option that skips\n"
        " the port's own EL2 configuration, a linker script describing one\n"
        " partition window, and a board file with no devices in it.\n"
        "\n"
        " On lockstep silicon this demonstrates memory isolation on ONE\n"
        " logical core.  It does NOT demonstrate spatial multicore\n"
        " partitioning, and it does not yet demonstrate TIME partitioning\n"
        " at all -- this guest takes no interrupts.\n");

    zx_console_puts("\n  checks failed: ");
    zx_console_putdec(zx_probe_failures());
    zx_console_puts("\n");

    if (zx_probe_failures() == 0U)
    {
        zx_console_puts("\nZONEX RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
    }

    zx_console_exit(zx_probe_failures());
}
