/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_probe.h                                            SHARED        */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The seam between the stage-2 probe image and the board it runs on.  */
/*                                                                        */
/*    The probe itself -- zx_probe_main.c and zx_payload.S -- is shared    */
/*    between the Armv8-R AEM FVP and the S32Z280-594EVB deliberately.    */
/*    The whole value of running it on both is that the SAME program       */
/*    answers the same questions differently, and two copies of it would   */
/*    let the two answers diverge for reasons that had nothing to do with  */
/*    the hardware.                                                       */
/*                                                                        */
/*    What each board supplies is below, and it is exactly the set of      */
/*    things that genuinely differ.                                       */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_PROBE_H
#define ZX_PROBE_H

#include "zx_port.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Region indices the probe uses.  Fixed rather than allocated, because the
   whole point of ZX_REGION_HIGH_PROBE being 16 is that 16 is the first index
   where the TRM contradicts itself about how a region can be reached.  */

#define ZX_REGION_PAYLOAD_CODE  0U
#define ZX_REGION_PAYLOAD_DATA  1U
#define ZX_REGION_BOARD_FIRST   2U
#define ZX_REGION_HIGH_PROBE    16U

/* Progress bits the payload records in zx_payload_result.  Mirrored from
   zx_payload.S, spelled identically so that a grep finds both.  */

#define ZX_PAYLOAD_RAN          0x01U
#define ZX_PAYLOAD_OWN_DATA_OK  0x02U
#define ZX_PAYLOAD_HVC_RETURNED 0x04U
#define ZX_PAYLOAD_PROBE_OK     0x08U
#define ZX_PAYLOAD_ATTEMPTED    0x10U
#define ZX_PAYLOAD_SURVIVED     0x20U

#define ZX_PAYLOAD_SENTINEL     0xA5A5A5A5U
#define ZX_HIGH_PROBE_SENTINEL  0x5A5AC0DEU

/**************************************************************************/
/*                      What each board must supply                       */
/**************************************************************************/

/* A name for the report, so a captured log says which target produced it.
   Defined by each board's zx_platform.h.  */

/* Bring up whatever has to exist before the first line is printed.  Nothing
   on the model, where semihosting needs no peripheral; the console on
   silicon.  */

/* The shared reporting helpers.  Not static, because the two-partition
   experiment lives in its own translation unit: a single example main
   carrying both the stage-2 bring-up and the partition proof would be the
   longest file in the repository and the least readable.  */

void zx_check(const char *label, uint32_t passed);
void zx_note(const char *label, uint32_t value);
ZX_NODISCARD zx_addr_t zx_symbol_address(const char *symbol);
ZX_NODISCARD uint32_t zx_probe_failures(void);
void zx_probe_fail(void);

/* The two-partition experiment.  Runs after the single-payload phases and
   reprograms the region set from a manifest, so it must come last.  */

void zx_phase_two_partitions(uint32_t board_regions, uint32_t el2_regions);

/* zx_board_init is NOT declared here.  It is the reset path's entry into the
   board, so it belongs to zx_port.h -- which this header includes -- and a
   second declaration of it here was one, in violation of MISRA C:2012
   Rule 8.5 (an external function shall be declared in one and only one
   file).  Two declarations of the same function agree until somebody
   changes one of them.  */

/* How many EL2 regions the hypervisor's own MMIO needs on this board, and
   the code that programs them starting at first_index.

   This is the shape docs/decisions.md D2 forces.  HSCTLR.BR=1 costs no
   region for ordinary hypervisor code and data, but BR grants PERMISSION,
   not ATTRIBUTES: the background map is Normal cacheable below 0x60000000,
   so a device the hypervisor owns down there is reachable with the wrong
   attributes and still needs a Device-attributed region.  On the S32Z280
   that is the console at 0x42980000 and the GIC.  On the FVP both sit in the
   Device band, so the count is zero and THE MODEL CANNOT SHOW YOU THAT THE
   FUNCTION IS NEEDED.  It exists so that the model's answer and the board's
   answer come out of the same program.  */

ZX_NODISCARD uint32_t zx_board_mmio_region_count(void);
void zx_board_program_mmio_regions(uint32_t first_index);

/* Reprogram the region covering the hypervisor's OWN CONSOLE so that EL2 may
   read it and not write it, and return non-zero if that was possible.

   IT EXISTS FOR EXACTLY ONE BUILD, and that build's purpose is to make the
   fault report itself fault -- so that the guards on the unresumable vectors
   are a path something has taken rather than a path somebody wrote.  See
   docs/decisions.md D30.

   Returns zero on a target whose console is not reached through an EL2 MPU
   region at all, which is the model: its console is semihosting and no
   region covers it, so there is nothing to deny and the build says so
   rather than reporting a success it did not achieve.

   AP can do this and cannot do the opposite.  At EL2 the access permissions
   cannot deny EL2 outright, but they can make a region READ-ONLY to it --
   which is enough, because a console write is a store to the data register.
   The same mechanism is what zx_phase_provoke_el2_fault uses.  */

ZX_NODISCARD uint32_t zx_board_deny_console_writes(uint32_t first_index);

/* The SAME geometry, described rather than programmed, so the manifest
   validator can reject a partition window that overlaps the hypervisor's own
   console or interrupt controller.  Those regions stay enabled while a
   partition runs, so an overlap there is two enabled regions on one address
   -- CONSTRAINED UNPREDICTABLE, and an abort on the S32Z280.  Writes exactly
   zx_board_mmio_region_count() entries.  */

void zx_board_describe_mmio_regions(ZX_REGION *region_ptr);

/* Print whatever the board knows about itself that the architecture cannot
   report -- which peripheral the console is, which memory the image is in.
   Called from the identity block.  */

void zx_board_report(void);

/* What this board's system counter runs at, in Hz.
 *
 * A SOFTWARE-DECLARED CONSTANT, not something read from the hardware.  CNTFRQ
 * reads ZERO out of reset on both ZoneX targets and nothing else reports the
 * frequency, so the number has to come from the board's own knowledge -- the
 * counter control frame on the model, and a measured-and-cross-checked clock
 * tree on silicon.  ZoneX programs CNTFRQ from it before entering a guest,
 * because CNTFRQ is writable only at the highest implemented exception level
 * and a guest deriving a tick interval from a zero would divide by zero.  */

ZX_NODISCARD uint32_t zx_board_counter_hz(void);

/* START this board's system counter, if starting it is a thing this board
 * needs.
 *
 * PROGRAMMING CNTFRQ DOES NOT START THE COUNTER, and the two are separate
 * hooks because on the two ZoneX targets they have opposite answers.  The
 * Armv8-R AEM FVP leaves its counter STOPPED at reset and documents that
 * firmware is expected to start it, through a memory-mapped counter control
 * frame; the S32Z280's runs out of reset, clocked through the RTU's own
 * divider, and has no frame for a hypervisor to write.
 *
 * IT IS EL2'S JOB EITHER WAY.  The system counter is one per system: it is
 * not a partition's to start, and a partition that could start or stop it
 * would be deciding how fast time ran for every other partition.  This is the
 * same division of labour as the GIC, and it arrives at the same place from a
 * different direction.
 *
 * Whether it worked is NOT this function's answer.  zx_counter_is_running
 * reads the counter twice and says whether it moved, which is the question
 * that matters and is answered identically on both boards.  */

void zx_board_counter_start(void);

/* Where this board's GICv3 frames are.
 *
 * The Cortex-R52 layer knows the register offsets inside a GICv3, which are
 * architectural; it does not and must not know where the frames sit, which is
 * a board fact.  A board that had no GIC at all would leave the structure
 * zeroed and zx_gic_el2_init would refuse -- which is a reported failure
 * rather than three writes into address zero.  */

void zx_board_gic_layout(ZX_GIC_LAYOUT *layout_ptr);

/**************************************************************************/
/*                    Symbols the linker script defines                   */
/**************************************************************************/

/* Declared as arrays of unknown size, which is the portable way to name a
   linker symbol whose ADDRESS is the value wanted.  Declaring one as a
   uint32_t and taking &symbol works too and reads as though the symbol had
   contents, which these do not.  */

extern char __zx_payload_code_start[];
extern char __zx_payload_code_end[];
extern char __zx_payload_data_start[];
extern char __zx_payload_data_end[];
extern char __zx_forbidden_start[];
extern char __zx_forbidden_end[];
extern char __zx_high_probe_start[];
extern char __zx_high_probe_end[];

/* Payload entry points and the words it reports through, from zx_payload.S. */

/* The two-partition experiment's windows.  NOLOAD sections: a partition's
   code window has nothing in the ELF to load, because its contents arrive
   at run time when the hypervisor copies the guest blob in.  */

extern char __zx_guest_blob_start[];
extern char __zx_guest_blob_end[];
extern char __zx_p0_code_start[];
extern char __zx_p0_code_end[];
extern char __zx_p0_data_start[];
extern char __zx_p0_data_end[];
extern char __zx_p0_hole_start[];
extern char __zx_p0_hole_end[];
extern char __zx_p1_code_start[];
extern char __zx_p1_code_end[];
extern char __zx_p1_data_start[];
extern char __zx_p1_data_end[];
extern char __zx_shared_start[];
extern char __zx_shared_end[];

extern char zx_payload_vectors[];
extern char zx_payload_grant_check[];
extern char zx_payload_hvc_check[];
extern char zx_payload_probe_read[];
extern char zx_payload_violation[];
extern char zx_payload_read_id_register[];

extern uint32_t zx_payload_result;
extern uint32_t zx_payload_scratch;
extern uint32_t zx_payload_probe_value;
extern uint32_t zx_high_probe_word;

#ifdef __cplusplus
}
#endif

#endif /* ZX_PROBE_H */
