/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_preemptive_partition.c                               SHARED      */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    A PREEMPTIVE ThreadX kernel, running at EL1 inside a stage-2        */
/*    confined partition, with a timer interrupt the hypervisor granted   */
/*    it and a clock the hypervisor freezes while it is not running.      */
/*                                                                        */
/*    The image next door showed that a real kernel BOOTS and SCHEDULES   */
/*    under stage 2, cooperatively.  A cooperative kernel is a kernel     */
/*    with the interesting half removed: nothing takes the core from a    */
/*    thread, so nothing can go wrong in the place where a partitioning   */
/*    hypervisor most needs nothing to go wrong.  This image adds the     */
/*    interrupt.                                                         */
/*                                                                        */
/*  THE THREE CLAIMS                                                      */
/*                                                                        */
/*    1.  A PARTITION RECEIVES AN INTERRUPT IT WAS GRANTED, and only      */
/*        that one.  ZoneX enables the virtual timer's PPI in a           */
/*        redistributor no partition can reach; the guest brings up its   */
/*        own CPU interface, which is system registers, and acknowledges. */
/*                                                                        */
/*    2.  A REAL KERNEL IS PREEMPTED UNDER STAGE 2.  A thread that never  */
/*        yields is displaced; two equal-priority threads that never      */
/*        yield are time sliced.  Neither is possible without an          */
/*        interrupt reaching EL1 and running the kernel's own handler.    */
/*                                                                        */
/*    3.  A DESCHEDULED PARTITION'S CLOCK IS FROZEN.  Between two         */
/*        excursions the hypervisor does a great deal of work -- on       */
/*        silicon, millions of cycles of polled UART -- and the           */
/*        partition's virtual counter does not advance by any of it.      */
/*        That is CNTVOFF, and it is the difference between temporal      */
/*        partitioning and time slicing that a guest can observe.         */
/*                                                                        */
/*  WHAT THIS IMAGE DELIBERATELY DOES NOT MEASURE                         */
/*                                                                        */
/*    "What a clock costs a partition."  The obvious pair -- one          */
/*    cooperative excursion against one preemptive one -- differs in the  */
/*    thing being measured AND in the fact that the preemptive guest      */
/*    spends three ticks deliberately waiting.  The difference would be   */
/*    dominated by the waiting and would be quoted as the cost of an      */
/*    interrupt, which is the same mistake as measuring two passes that   */
/*    differ in execution order and calling the difference stage 2.       */
/*                                                                        */
/*    What IS comparable is two excursions of the SAME preemptive guest   */
/*    doing the SAME work with the SAME console traffic, one after the    */
/*    other, and that pair is measured: it is a repeatability number,     */
/*    which is the honest determinism claim available on one core with    */
/*    one partition.                                                     */
/*                                                                        */
/*  WHAT A PASS DOES NOT MEAN                                             */
/*                                                                        */
/*    On the Armv8-R AEM FVP a pass proves the code is right and says     */
/*    NOTHING about timing: the model is functional, not cycle-accurate.  */
/*    Every number this image prints has to come from silicon before it   */
/*    is quoted, and the image says so in its own output.                 */
/*                                                                        */
/*    On lockstep silicon it demonstrates preemption and a frozen clock   */
/*    for ONE partition on ONE logical core.  Time PARTITIONING -- a      */
/*    hypervisor tick that ENDS a partition's window -- is not this and   */
/*    is not here.  It needs HCR.FMO and the hypervisor's own timer in    */
/*    GROUP 0, so that its tick arrives as an FIQ at EL2 while every      */
/*    guest interrupt stays an IRQ delivered straight to EL1, exactly as  */
/*    it is here.  See docs/decisions.md D24.                             */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"
#include "zx_platform.h"
#include "zx_guest_abi.h"
#include "zx_guest_launch.h"
#include "zx_manifest.h"
#include "zx_mm.h"
#include "zx_partition.h"
#include "zx_guest_console.h"

/* THE GUEST'S CONTRACT AND THE HYPERVISOR'S MUST AGREE, and this is one of
   only two translation units that can see both spellings.  The guest is a
   separate program with its own toolchain invocation and cannot include
   zx_port.h; it restates what it needs in zx_guest_abi.h.  Asserting the two
   against each other here turns a renumbered constant into a failed BUILD
   rather than a partition that takes an interrupt it does not recognise.  */

_Static_assert(ZX_HVC_GUEST_NOP == (int)ZX_HVC_NOP,
               "the guest and the hypervisor disagree about HVC #0");
_Static_assert(ZX_HVC_GUEST_YIELD == (int)ZX_HVC_YIELD,
               "the guest and the hypervisor disagree about the yield HVC");
_Static_assert(ZX_HVC_GUEST_PUTC == (int)ZX_HVC_PUTC,
               "the guest and the hypervisor disagree about the console HVC");
_Static_assert(ZX_GUEST_TIMER_INTID == (int)ZX_PPI_VIRTUAL_TIMER,
               "the guest acknowledges a different INTID from the one ZoneX "
               "enables for it");
_Static_assert(ZX_GUEST_SPURIOUS_INTID == (int)ZX_INTID_SPURIOUS,
               "the guest and the hypervisor disagree about the spurious "
               "INTID, which must never be given an end-of-interrupt");

/* The embedded guest image and partition A's window, from the linker
   script.  */

extern char __zx_guest_a_blob_start[];
extern char __zx_guest_a_blob_end[];
extern char __zx_partition_a_start[];
extern char __zx_partition_a_end[];
extern char __zx_partition_a_hole_start[];

#define ZX_PARTITION_A_ID       1U
#define ZX_PARTITION_A_INDEX    0U

/* The sentinel the hypervisor leaves in the guest's mailbox, and which the
   guest folds into every checksum.  Distinct from the other images' so that
   a log from one cannot be misread as another's.  */

#define ZX_GUEST_A_SENTINEL     0xA5A5000BU

/* The priority the partition's timer is given.
 *
 * A GIC compares priorities NUMERICALLY and lower wins, and only the top
 * bits of the byte are implemented -- this image discovers how many and
 * reports it, because two values differing only in the vanished bits are
 * the SAME priority and cannot preempt one another.
 *
 * 0xA0 leaves the whole upper half of the range above it, which is where a
 * hypervisor tick will have to go once there is one: ZoneX's own timer must
 * be able to preempt a partition's, or a partition could delay the end of
 * its own window by taking a long interrupt.  That is not yet built -- it
 * needs HCR.FMO and the hypervisor's tick in Group 0 -- and the number is
 * chosen now so that it does not have to change then.  */

#define ZX_GUEST_TIMER_PRIORITY 0xA0U

/* How long the hypervisor deliberately dwells between two excursions,
 * expressed as a divisor of the counter frequency: 20 says a fiftieth of a
 * second, which is TWO of the guest's ticks at ThreadX's default rate.
 *
 * Two rather than one, because the claim is about a clock that a guest can
 * READ: a gap shorter than a tick could be frozen or merely rounded away,
 * and the difference would not be visible in the guest's own tick count.
 * Two ticks is long enough that a partition whose clock was NOT frozen would
 * come back to find its own time had jumped, which is exactly the
 * observation temporal partitioning exists to prevent.  */

#define ZX_DWELL_DIVISOR        50U

static ZX_REGION        zx_regions_a[1];
static ZX_PARTITION     zx_partitions[1];
static ZX_MANIFEST      zx_manifest;
static ZX_MM_LAYOUT     zx_layout;
static ZX_MANIFEST_ENV  zx_env;
static ZX_PARTITION_CB  zx_partition_a;
static ZX_REGION        zx_mmio[ZX_BOARD_MAX_MMIO_REGIONS];
static ZX_GIC_LAYOUT    zx_gic;
static ZX_GUEST_LAUNCH  zx_launch;


/**************************************************************************/
/*  zx_describe_launch                                                    */
/*                                                                        */
/*  Filled at run time rather than being a static initialiser, because     */
/*  every field is the address of a LINKER symbol and the address of a     */
/*  linker symbol is not a constant expression.                            */
/**************************************************************************/

static void zx_describe_launch(void)
{
    zx_launch.zx_launch_window_base   =
        zx_symbol_address(__zx_partition_a_start);
    zx_launch.zx_launch_window_end    =
        zx_symbol_address(__zx_partition_a_end);
    zx_launch.zx_launch_image_start   =
        zx_symbol_address(__zx_guest_a_blob_start);
    zx_launch.zx_launch_image_end     =
        zx_symbol_address(__zx_guest_a_blob_end);
    zx_launch.zx_launch_sentinel      = ZX_GUEST_A_SENTINEL;
    zx_launch.zx_launch_partition_id  = ZX_PARTITION_A_ID;
    zx_launch.zx_launch_partition_name = zx_partitions[0].zx_partition_name;

#ifdef ZX_PREEMPT_NO_FREEZE
    zx_launch.zx_launch_freeze_time   = 0U;
#else
    zx_launch.zx_launch_freeze_time   = 1U;
#endif
}


/**************************************************************************/
/*  zx_build_manifest                                                     */
/*                                                                        */
/*  ONE PARTITION, ONE REGION, exactly as the cooperative image declares   */
/*  them -- and that is worth stating rather than merely doing.  Granting  */
/*  a partition an interrupt changed NOTHING about the memory it owns:     */
/*  no region for a GIC, no region for a timer, no device of any kind.     */
/*  The whole of a partition's interrupt capability is system-register     */
/*  state, plus one bit the hypervisor set on its behalf in a frame the    */
/*  partition cannot address.                                             */
/*                                                                        */
/*  That is the strongest form the claim could take.  A partition that     */
/*  needed the redistributor mapped would need it WRITABLE -- the enable,  */
/*  priority and group bits are all in one frame -- and that frame also    */
/*  holds the enable for PPI 26, the hypervisor's own timer.  The isolation*/
/*  argument would then have a hole in it that no region set could close.  */
/**************************************************************************/

static void zx_build_manifest(uint32_t board_regions)
{
    zx_regions_a[0].zx_region_base  =
        zx_symbol_address(__zx_partition_a_start);
    zx_regions_a[0].zx_region_limit =
        zx_symbol_address(__zx_partition_a_end) - 1U;
    zx_regions_a[0].zx_region_ap    = ZX_AP_EL2_RW_GUEST_RW;
    zx_regions_a[0].zx_region_xn    = ZX_XN_EXECUTABLE;
    zx_regions_a[0].zx_region_sh    = ZX_SH_NON_SHAREABLE;
    zx_regions_a[0].zx_region_attr_index = (UCHAR)ZX_ATTR_NORMAL_WB;

    zx_partitions[0].zx_partition_id           = ZX_PARTITION_A_ID;
    zx_partitions[0].zx_partition_name         = "ThreadX guest A";
    zx_partitions[0].zx_partition_image_start  =
        zx_symbol_address(__zx_guest_a_blob_start);
    zx_partitions[0].zx_partition_image_end    =
        zx_symbol_address(__zx_guest_a_blob_end);
    zx_partitions[0].zx_partition_entry        =
        zx_symbol_address(__zx_partition_a_start) + ZX_GUEST_IMAGE_OFF_ENTRY;
    zx_partitions[0].zx_partition_regions      = zx_regions_a;
    zx_partitions[0].zx_partition_region_count = 1U;
    zx_partitions[0].zx_partition_window_ticks = 10U;

    zx_manifest.zx_manifest_partitions        = zx_partitions;
    zx_manifest.zx_manifest_partition_count   = 1U;
    zx_manifest.zx_manifest_shared            = (const ZX_SHARED *)0;
    zx_manifest.zx_manifest_shared_count      = 0U;
    zx_manifest.zx_manifest_major_frame_ticks = 10U;

    zx_board_describe_mmio_regions(zx_mmio);

    zx_env.zx_env_mmio_regions      = zx_mmio;
    zx_env.zx_env_mmio_region_count = board_regions;
    zx_env.zx_env_attr_written_mask = 0x07U;
}


/**************************************************************************/
/*  zx_grant_the_clock                                                    */
/*                                                                        */
/*  EVERYTHING THE HYPERVISOR DOES SO THAT A PARTITION CAN HAVE A TICK,    */
/*  in one place, because the order matters and every step of it fails     */
/*  silently on its own.                                                   */
/*                                                                        */
/*    THE SYSTEM COUNTER IS STARTED FIRST.  Programming CNTFRQ does not    */
/*    start it -- CNTFRQ is a software-declared constant that says what    */
/*    the counter WOULD run at -- and one of the two ZoneX targets leaves  */
/*    its counter stopped at reset.  A timer armed against a stopped       */
/*    counter never expires, and a guest that blocked on it would end the  */
/*    run in a harness timeout rather than a report.                       */
/*                                                                        */
/*    THEN THE GIC.  The distributor's affinity routing and group enables, */
/*    then this core's redistributor woken out of ProcessorSleep.  Nothing */
/*    can be delivered to this core until the redistributor reports its    */
/*    children awake, and a configuration written into a sleeping frame is */
/*    written into a frame that is not listening.                          */
/*                                                                        */
/*    THEN THE PARTITION'S ONE INTERRUPT.  Group 1, level-triggered, at a  */
/*    priority chosen to leave room above it.  This is the only INTID the  */
/*    partition is given, and it is given in a frame the partition cannot  */
/*    address.                                                             */
/*                                                                        */
/*    AND EVERY STEP IS READ BACK.  A GIC write that landed at the wrong   */
/*    offset does not fault -- it does nothing -- and a partition that     */
/*    silently never receives its timer is indistinguishable from a kernel */
/*    whose scheduler does not work.  Three reads at boot are cheap next   */
/*    to that hour.                                                        */
/*                                                                        */
/*  Returns non-zero when everything the guest depends on is in place.     */
/**************************************************************************/

static uint32_t zx_grant_the_clock(void)
{
    uint32_t awake;
    uint32_t running;

    zx_console_puts("\n--- the clock and the interrupt ZoneX grants a "
                    "partition ---\n");

    zx_board_counter_start();
    running = zx_counter_is_running();

    zx_note("CNTFRQ         ", zx_read_cntfrq());
    zx_check("the system counter is RUNNING, not merely declared.  CNTFRQ is\n"
             "         a software-written constant and says nothing about\n"
             "         whether the counter moves; this is two reads of\n"
             "         CNTPCT, and on a target whose counter was never\n"
             "         started a guest waiting on a timer would wait for ever",
             running);

#ifdef ZX_PREEMPT_NO_PPI

    zx_console_puts("\n  THIS BUILD DELIBERATELY DOES NOT ENABLE THE "
                    "PARTITION'S PPI.\n"
                    "  The GIC is brought up and the interrupt is left\n"
                    "  disabled, so the guest arms a timer whose interrupt\n"
                    "  can never be delivered.  It must report that it never\n"
                    "  ticked, and this run must report FAILED.\n");

    awake = zx_gic_el2_init(&zx_gic);
    zx_check("the redistributor woke", awake);

    zx_note("PPI enabled (must be 0)",
            zx_gic_ppi_is_enabled(&zx_gic, ZX_PPI_VIRTUAL_TIMER));

    return (running != 0U) ? awake : 0U;

#else

    uint32_t priority_bits;
    uint32_t enabled;
    uint32_t group1;
    uint32_t priority;

    awake = zx_gic_el2_init(&zx_gic);

    zx_note("GIC distributor", (uint32_t)zx_gic.zx_gic_dist_base);
    zx_note("GIC redistributor, RD frame ",
            (uint32_t)zx_gic.zx_gic_rd_base);
    zx_note("GIC redistributor, SGI frame",
            (uint32_t)zx_gic.zx_gic_sgi_base);
    zx_check("the redistributor cleared ProcessorSleep and reports its\n"
             "         children awake, so this core can be delivered to at\n"
             "         all.  Bounded rather than spun on for ever: a GIC that\n"
             "         never wakes has to be a report and not a silent boot",
             awake);

    priority_bits = zx_gic_priority_bits(&zx_gic, ZX_PPI_VIRTUAL_TIMER);
    zx_note("implemented priority bits", priority_bits);
    zx_console_puts("               Only the top bits of a priority byte\n"
                    "               exist; the rest read back as zero.  Two\n"
                    "               priorities differing only there are the\n"
                    "               SAME priority to the hardware, and equal\n"
                    "               priorities do not preempt -- which is\n"
                    "               what a hypervisor tick will need to do to\n"
                    "               a partition's.\n");
    zx_check("this GIC implements at least three priority bits, so a\n"
             "         hypervisor tick can be given a priority a partition's\n"
             "         timer cannot collide with",
             (priority_bits >= 3U) ? 1U : 0U);

    zx_gic_enable_guest_ppi(&zx_gic, ZX_PPI_VIRTUAL_TIMER,
                            ZX_GUEST_TIMER_PRIORITY);

    enabled  = zx_gic_ppi_is_enabled(&zx_gic, ZX_PPI_VIRTUAL_TIMER);
    group1   = zx_gic_ppi_is_group1(&zx_gic, ZX_PPI_VIRTUAL_TIMER);
    priority = zx_gic_ppi_priority(&zx_gic, ZX_PPI_VIRTUAL_TIMER);

    zx_note("granted INTID  ", ZX_PPI_VIRTUAL_TIMER);
    zx_note("  enabled      ", enabled);
    zx_note("  group 1      ", group1);
    zx_note("  priority     ", priority);

    zx_check("the partition's virtual-timer PPI reads back ENABLED, so the\n"
             "         write reached the register rather than a plausible\n"
             "         offset next to it",
             enabled);
    zx_check("and in GROUP 1, which is what the GIC delivers as an IRQ.\n"
             "         Group 0 arrives as an FIQ and this partition is\n"
             "         granted none",
             group1);
    zx_check("and at the priority it was given, with the bits this GIC does\n"
             "         not implement read back as zero",
             (priority == (ZX_GUEST_TIMER_PRIORITY
                           & (uint32_t)(0xFFU << (8U - priority_bits))))
                 ? 1U : 0U);

    zx_check("the HYPERVISOR's own timer PPI is NOT enabled.  Every SGI and\n"
             "         PPI was disabled during bring-up before this one was\n"
             "         granted, because on silicon ZoneX is not the first\n"
             "         thing to run and an enable bit is not reset state a\n"
             "         hypervisor may assume -- with HCR.IMO clear, anything\n"
             "         left enabled by an earlier stage would be delivered to\n"
             "         the partition",
             (zx_gic_ppi_is_enabled(&zx_gic, ZX_PPI_HYPERVISOR_TIMER) == 0U)
                 ? 1U : 0U);
    zx_check("and neither is the PHYSICAL timer's, which a partition could\n"
             "         not read anyway: CNTHCTL.PL1PCTEN and PL1PCEN are\n"
             "         left clear on purpose",
             (zx_gic_ppi_is_enabled(&zx_gic, ZX_PPI_PHYSICAL_TIMER) == 0U)
                 ? 1U : 0U);

    zx_console_puts(
        "\n"
        "  NOT ONE BYTE OF THIS IS MAPPED INTO THE PARTITION.  The\n"
        "  distributor and both redistributor frames stay at\n"
        "  EL2-read-write, guest-no-access, and the guest needs none of\n"
        "  them: its CPU interface is system registers.  The frame it is\n"
        "  denied holds the enable bit for the interrupt above AND for the\n"
        "  hypervisor's own timer, which is what will end a partition's\n"
        "  window -- a partition able to write it could refuse to be\n"
        "  descheduled, and no region set would show that.\n");

    return (running != 0U) ? awake : 0U;

#endif
}


/**************************************************************************/
/*  zx_report_tick                                                        */
/*                                                                        */
/*  What the partition's interrupt handler recorded.  OUTSIDE the guest's  */
/*  sealed snapshot, and the report says so: these words are written by a  */
/*  handler that runs on every tick and must not stop to compute a         */
/*  checksum.  The claims do not rest on them -- the tick count inside the */
/*  seal is tx_time_get(), and the preemption bits are progress bits,      */
/*  which are sealed.  These are the detail that makes a FAILING run       */
/*  diagnosable.                                                          */
/**************************************************************************/

static void zx_report_tick(void)
{
    zx_console_puts("\n--- what the partition's own interrupt handler "
                    "recorded ---\n");
    zx_note("interrupts serviced", zx_guest_mailbox_read(&zx_launch,
                                                         ZX_GD_IRQ_COUNT));
    zx_note("timer INTID seen   ", zx_guest_mailbox_read(&zx_launch,
                                                         ZX_GD_TIMER_INTID));
    zx_note("unexpected INTID   ", zx_guest_mailbox_read(&zx_launch,
                                                         ZX_GD_ODD_INTID));
    zx_note("spinner A loops    ", zx_guest_mailbox_read(&zx_launch,
                                                         ZX_GD_SPIN_A));
    zx_note("spinner B loops    ", zx_guest_mailbox_read(&zx_launch,
                                                         ZX_GD_SPIN_B));
    zx_note("sleeps completed   ", zx_guest_mailbox_read(&zx_launch,
                                                         ZX_GD_WAKES));
    zx_console_puts("               These six are OUTSIDE the guest's sealed\n"
                    "               report, because four of them are written\n"
                    "               by a handler that runs on every tick and\n"
                    "               must not stop to checksum anything.  The\n"
                    "               claims rest on the sealed words: the tick\n"
                    "               count is tx_time_get(), and preemption\n"
                    "               and time slicing are progress bits.\n");
}


/**************************************************************************/
/*  zx_el2_main -- entered from zx_el2_entry.S at EL2.  Does not return.  */
/**************************************************************************/

ZX_NORETURN void zx_el2_main(void)
{
    uint32_t board_regions;
    uint32_t el2_regions;
    uint32_t status;
    uint32_t outcome;
    uint32_t progress;
    uint32_t granted;
    uint32_t cycles_first = 0U;
    uint32_t cycles_second = 0U;
    uint64_t away_from;
    uint64_t virtual_then;
    uint64_t offset_before;
    uint32_t excluded_for;
    uint32_t credited;
    uint32_t physical_gap;
    uint32_t virtual_gap;
    ZX_MANIFEST_FAULT fault;

    /* ---------------------------------------------------------------- */
    /*  BEFORE THE FIRST PRINT.  On a board whose console sits below     */
    /*  0x60000000 the background map reaches it as NORMAL memory, and   */
    /*  Normal memory permits the gathering and reordering that corrupts */
    /*  a polled UART.  So HMAIR, the hypervisor's own MMIO regions and  */
    /*  HSCTLR.M come up FIRST.  See docs/decisions.md D15.              */
    /* ---------------------------------------------------------------- */

    el2_regions   = zx_el2_region_count();
    board_regions = zx_board_mmio_region_count();

    if (el2_regions >= board_regions)
    {
        zx_mair_program();

        if (board_regions > 0U)
        {
            zx_board_program_mmio_regions(0U);
        }

        zx_el2_mpu_enable();
    }

    zx_board_init();

    zx_console_puts(
        "\n"
        "=========================================================\n"
        " Eclipse ThreadX ZoneX -- a PREEMPTIVE ThreadX guest\n"
        " " ZX_PLATFORM_NAME "\n"
        " Armv8-R AArch32, EL2, PMSAv8-R at both stages\n"
        "=========================================================\n"
        "\n"
        " The image next door showed a real kernel BOOT and SCHEDULE\n"
        " inside a stage-2 window, cooperatively.  This one gives that\n"
        " partition a CLOCK.\n"
        "\n"
        " ZoneX starts the system counter, takes the whole GIC, and\n"
        " enables ONE interrupt for the partition -- the virtual timer's\n"
        " PPI -- in a redistributor frame the partition cannot address.\n"
        " The guest brings up only its own CPU interface, which is system\n"
        " registers and touches no device, and is then preempted by its\n"
        " own kernel underneath stage 2.\n"
        "\n"
        " Between excursions the hypervisor moves CNTVOFF, so the time it\n"
        " spends here does not happen to the partition.\n");

    zx_fault_record_reset(zx_el2_fault_record());
    zx_guest_console_reset();

    zx_console_puts("\n--- the EL2 MPU is already on ---\n");
    zx_note("HSCTLR now", zx_read_hsctlr());
    zx_check("HSCTLR.M is set, so the EL2 MPU is live",
             ((zx_read_hsctlr() & ZX_HSCTLR_M) != 0U) ? 1U : 0U);

    zx_console_puts("\n--- identity, as the core reports it ---\n");
    zx_note("MIDR         ", zx_read_midr());
    zx_note("EL2 regions  ", el2_regions);
    zx_note("EL1 regions  ", zx_el1_region_count());
    zx_note("ICH_VTR      ", zx_read_ich_vtr());
    zx_console_puts("               The virtual CPU interface, which this\n"
                    "               image does NOT use: with HCR.IMO clear a\n"
                    "               physical interrupt taken while a\n"
                    "               partition runs is delivered straight to\n"
                    "               EL1, and the hypervisor is not involved\n"
                    "               in a tick at all.  The List Registers are\n"
                    "               reported because the phase that sets IMO\n"
                    "               will need every one of them.\n");
    zx_board_report();

    if (el2_regions == 0U)
    {
        zx_console_puts("\n  *** HMPUIR reports ZERO EL2 regions, so this "
                        "target cannot host\n  *** stage 2 at all.  Refusing "
                        "to go on.\n"
                        "\nZONEX RESULT: FAILED -- the target cannot host "
                        "stage 2\n");
        zx_console_exit(1U);
    }

    /* ---------------------------------------------------------------- */
    /*  The manifest, the plan, and the loader.                         */
    /* ---------------------------------------------------------------- */

    zx_build_manifest(board_regions);
    zx_describe_launch();
    zx_board_gic_layout(&zx_gic);
    zx_env.zx_env_region_budget = el2_regions;

    status = zx_manifest_verify(&zx_manifest, &zx_env, &fault);

    zx_console_puts("\n--- the manifest, checked before anything is "
                    "programmed ---\n");
    zx_note("zx_manifest_verify", status);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_note("  offending partition", fault.zx_fault_partition);
        zx_note("  offending region   ", fault.zx_fault_region);
        zx_check("the manifest passes every rule", 0U);
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_check("the manifest passes every rule", 1U);
    zx_check("and it grants the partition NO device region at all, even now\n"
             "         that the partition has an interrupt -- a partition's\n"
             "         whole interrupt capability is system-register state",
             (zx_partitions[0].zx_partition_region_count == 1U) ? 1U : 0U);

    status = zx_mm_plan(&zx_manifest, board_regions, el2_regions,
                        zx_hprenr_implemented_bits, &zx_layout);
    zx_note("zx_mm_plan", status);
    zx_check("the layout fits this part's region budget",
             (status == ZX_MANIFEST_SUCCESS) ? 1U : 0U);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_mm_report(&zx_layout, &zx_manifest);

    zx_partition_reset(&zx_partition_a, &zx_partitions[0]);

    status = zx_partition_prepare(&zx_partition_a);
    zx_note("zx_partition_prepare", status);
    zx_check("the loader located the window the entry point is in, and the\n"
             "         image fits THAT window",
             (status == ZX_MANIFEST_SUCCESS) ? 1U : 0U);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_partition_report(&zx_partition_a);
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    if (zx_guest_image_check(&zx_launch) == 0U)
    {
        zx_console_puts("\n  *** REFUSING to launch this image.  It is either\n"
                        "  *** absent, truncated, or built for a different\n"
                        "  *** window.\n"
                        "\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_partition_report(&zx_partition_a);

    /* ---------------------------------------------------------------- */
    /*  The region set, and stage 2 ON for every pass in this image.    */
    /*                                                                  */
    /*  What stage 2 COSTS is the other image's question and is measured */
    /*  there, by a pair that differs in HCR.VM and nothing else.  Here  */
    /*  stage 2 is simply on, because the claim is about a preemptive    */
    /*  kernel UNDER it and a pass with it off would prove nothing about */
    /*  that.                                                            */
    /* ---------------------------------------------------------------- */

    {
        uint32_t index =
            (uint32_t)zx_layout.zx_layout_partition_first[ZX_PARTITION_A_INDEX];

        zx_stage2_region_program(index, &zx_regions_a[0]);

        zx_console_puts("\n--- the region set, programmed and read back ---\n");
        zx_note("partition A region index", index);
        zx_check("partition A's window reads back as the manifest declared it",
                 zx_stage2_region_matches(index, &zx_regions_a[0]));

        zx_stage2_enable_set(
            zx_mm_partition_mask(&zx_layout, ZX_PARTITION_A_INDEX));
        zx_note("HPRENR now", zx_hprenr_read());
    }

    zx_console_puts("\n  the ungranted granule immediately after the window "
                    "is at ");
    zx_console_puthex(zx_symbol_address(__zx_partition_a_hole_start));
    zx_console_puts("\n");

    /* ---------------------------------------------------------------- */
    /*  What ZoneX takes over from the guest's boot path.               */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- what ZoneX takes over from the guest's boot path "
                    "---\n");
    zx_el2_prepare_guest_el1(zx_board_counter_hz());
    zx_note("CNTFRQ after ", zx_read_cntfrq());
    zx_check("CNTFRQ is programmed, because it is writable only at the\n"
             "         highest implemented exception level -- and a guest\n"
             "         deriving a tick interval from a zero divides by zero,\n"
             "         which is exactly what this image asks it to do",
             (zx_read_cntfrq() == zx_board_counter_hz()) ? 1U : 0U);

    granted = zx_grant_the_clock();

    zx_el2_guest_time_reset();
    zx_note("CNTVOFF now, low word",
            (uint32_t)(zx_el2_guest_time_offset() & 0xFFFFFFFFU));
    zx_console_puts("               The partition's virtual counter now reads\n"
                    "               zero.  CNTVOFF is writable only at EL2, so\n"
                    "               where a partition's clock STARTS is the\n"
                    "               hypervisor's to decide -- and so is\n"
                    "               whether it advances while the partition is\n"
                    "               not running.\n");

    zx_stage2_enable();
    zx_note("HCR now", zx_read_hcr());
    zx_check("HCR.VM is set, so stage 2 applies to EL0/EL1 for every pass\n"
             "         in this image",
             ((zx_read_hcr() & ZX_HCR_VM) != 0U) ? 1U : 0U);
    zx_check("HCR.IMO is CLEAR, so a physical interrupt taken while the\n"
             "         partition runs is delivered STRAIGHT to EL1 -- no\n"
             "         injection, no List Register, and no EL2 work per tick.\n"
             "         The cost of that is stated in the verdict below",
             ((zx_read_hcr() & ZX_HCR_IMO) == 0U) ? 1U : 0U);
    zx_check("HCR.TGE is clear, so the guest keeps its own exception\n"
             "         vectors -- without which its IRQ vector could not be\n"
             "         the thing that runs",
             ((zx_read_hcr() & ZX_HCR_TGE) == 0U) ? 1U : 0U);

    zx_pmu_enable();

    /* ---------------------------------------------------------------- */
    /*  A WARM-UP EXCURSION, measured and discarded.                    */
    /*                                                                  */
    /*  On a real core the FIRST execution of anything is not           */
    /*  comparable to the second: branch prediction and the instruction */
    /*  path are cold.  Measuring a pair whose members differ in order  */
    /*  as well as in configuration measures neither -- which is not a  */
    /*  caution but a result, and it was paid for by the cooperative    */
    /*  image reporting stage 2 as 28% FASTER than no stage 2 before    */
    /*  this pass existed.                                             */
    /*                                                                  */
    /*  It is also the first excursion that proves the tick works, so a */
    /*  target whose GIC or counter is wrong fails HERE, before any     */
    /*  number has been printed that somebody might quote.              */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- a warm-up excursion, measured and discarded ---\n");

    zx_guest_image_load(&zx_partition_a.zx_partition_load);
    zx_guest_hand_over(&zx_launch, 0U, ZX_GO_QUIET | ZX_GO_TICK);
    zx_partition_loaded(&zx_partition_a);

    zx_check("the partition may be entered now that its image is loaded",
             zx_partition_enter(&zx_partition_a));

    {
        uint32_t warm_cycles = 0U;

        outcome = zx_guest_run(&zx_launch, &zx_partition_a, &warm_cycles);
        zx_note("warm-up excursion, cycles (discarded)", warm_cycles);
        zx_note("outcome", outcome);
    }

    progress = zx_guest_report(&zx_launch);
    zx_report_tick();

    zx_check("the warm-up guest reached its own verdict, which rules out the\n"
             "         loader, the entry point, the GIC and the counter\n"
             "         before anything is measured",
             ((progress & (uint32_t)ZX_GP_FINISHED) != 0U) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  PASS 1 of 3: quiet, preemptive, measured.                       */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n====================================================="
                    "====\n"
                    " PASS 1 of 3: the preemptive guest, QUIET\n"
                    "====================================================="
                    "====\n"
                    "  THE CONSOLE IS OFF FOR THIS PASS AND THE NEXT.  A\n"
                    "  guest's console is one hypercall PER CHARACTER through\n"
                    "  a polled UART, which on silicon is three orders of\n"
                    "  magnitude more work than everything else the guest\n"
                    "  does -- so a loud pair could only bound a difference\n"
                    "  from above and never resolve one.  Same image, one\n"
                    "  word in the mailbox.\n");

    zx_guest_image_load(&zx_partition_a.zx_partition_load);
    zx_guest_hand_over(&zx_launch, 0U, ZX_GO_QUIET | ZX_GO_TICK);

    zx_check("the partition may be entered again after yielding",
             zx_partition_enter(&zx_partition_a));

    outcome  = zx_guest_run(&zx_launch, &zx_partition_a, &cycles_first);
    progress = zx_guest_report(&zx_launch);
    zx_report_tick();

    zx_check("the guest yielded rather than faulting", 
             (outcome == ZX_RUN_YIELDED) ? 1U : 0U);
    zx_check("and nothing has printed yet, so the quiet option really is\n"
             "         quiet and the cycles below are the guest's own work",
             (zx_guest_console_characters() == 0U) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  THE GAP.  The whole of the frozen-clock claim is measured here.  */
    /*                                                                  */
    /*  Between the two excursions the hypervisor does a great deal of   */
    /*  work.  Physical time passes, and a great deal of it on silicon:  */
    /*  every line below is a polled UART transaction.  The partition's  */
    /*  virtual time must not move by any of it.                        */
    /*                                                                  */
    /*  Measured as two 64-bit deltas rather than by asking the guest,   */
    /*  because the guest is not running: the point of the claim is that */
    /*  a partition CANNOT observe this interval, so the evidence has to */
    /*  come from the side that can.                                    */
    /* ---------------------------------------------------------------- */

    /* WHERE THE PARTITION STOPPED, taken BEFORE anything below can move it.
       The resume further down updates both of these -- that is what a
       resume IS -- so reading them afterwards would compare the partition's
       restart against itself and report a gap of zero on every build,
       including the one that has no freeze at all.  */

    away_from     = zx_el2_guest_time_suspended_at();
    virtual_then  = zx_el2_guest_virtual_when_suspended();
    offset_before = zx_el2_guest_time_offset();

    zx_console_puts("\n--- the gap between two excursions ---\n"
                    "  The partition is not running.  The hypervisor spends a\n"
                    "  DELIBERATE interval here, measured on the physical\n"
                    "  counter, standing in for the work a real hypervisor\n"
                    "  does between two windows -- and, once there are two\n"
                    "  partitions, for the other partition's window.\n"
                    "\n"
                    "  IT IS DELIBERATE BECAUSE THE FIRST VERSION WAS NOT.\n"
                    "  That one measured the gap across a block of console\n"
                    "  output, on the grounds that a polled UART is millions\n"
                    "  of cycles.  It is -- on silicon.  On a model whose\n"
                    "  console is semihosting it costs no simulated time at\n"
                    "  all, so the physical counter advanced by ZERO and the\n"
                    "  virtual counter did too, for the wrong reason.  The\n"
                    "  check was green, and so was the build that\n"
                    "  deliberately breaks the freeze.\n");

    zx_el2_dwell(zx_board_counter_hz() / ZX_DWELL_DIVISOR);

    /* THE FREEZE IS APPLIED HERE, ON THE WAY BACK IN, AND THAT IS WHERE IT
       HAS TO BE MEASURED.
     *
     * CNTVOFF is a static offset: while a partition is suspended the
     * physical counter keeps moving and the offset does not, so the
     * subtraction drifts for exactly as long as the partition is away.  What
     * closes the gap is the write on RESUME, which jumps CNTVOFF forward by
     * everything that elapsed.  Sampling the virtual counter before that
     * write therefore measures the drift and not the correction, which is
     * what the first version of this check did -- it reported the partition's
     * clock advancing by the whole gap on a run where the freeze was working
     * perfectly.
     *
     * So the two samples bracket the instants the PARTITION experiences: the
     * moment it stopped, and the moment it is about to start again.  Between
     * them the hypervisor did a measurable amount of work, and the partition
     * is entitled to see none of it.
     *
     * The build that breaks the freeze skips this exactly as it skips the
     * one inside the excursion, so it is the MECHANISM that is switched off
     * rather than the measurement being rearranged around it.  */

    if (zx_launch.zx_launch_freeze_time != 0U)
    {
        zx_el2_guest_time_resume();
    }
    else
    {
        zx_el2_guest_time_resume_uncredited();
    }

    /* The two instants the PARTITION experiences: the moment it stopped,
       recorded by the launcher, and now -- the moment it is about to start
       again.  Physical time separates them; the partition's own clock must
       not.  */

    /* THE INTERVAL, as the mechanism itself measured it: the counter at the
       instant the partition stopped, and at the instant it was given the
       core back.  Both taken by the freeze, so the comparison below is not
       measuring the cost of measuring.  */

    excluded_for = (uint32_t)((zx_el2_guest_time_resumed_at() - away_from)
                              & 0xFFFFFFFFU);
    credited     = (uint32_t)((zx_el2_guest_time_offset() - offset_before)
                              & 0xFFFFFFFFU);

    /* And the same interval as an OUTSIDE observer measures it afterwards,
       which is longer by however much the reads themselves cost.  */

    physical_gap = (uint32_t)((zx_read_cntpct() - away_from) & 0xFFFFFFFFU);
    virtual_gap  = (uint32_t)((zx_el2_guest_virtual_count() - virtual_then)
                              & 0xFFFFFFFFU);

    zx_note("counts the partition was excluded from", excluded_for);
    zx_note("counts credited to CNTVOFF            ", credited);
    zx_note("the same interval measured afterwards ", physical_gap);
    zx_note("the partition's virtual clock moved by", virtual_gap);

    zx_check("there was a REAL interval for the partition to be excluded\n"
             "         from.  Without this the check below would be satisfied\n"
             "         by nothing having happened, which is how it was\n"
             "         satisfied the first time it was written: the gap was\n"
             "         measured across console output, and on a model whose\n"
             "         console is semihosting that costs no simulated time",
             (excluded_for > 0U) ? 1U : 0U);

    zx_check("CNTVOFF was credited with EXACTLY the interval the partition\n"
             "         was away for -- not approximately, and not according\n"
             "         to the arithmetic that computed it: the offset is READ\n"
             "         BACK out of the register and compared against the two\n"
             "         counter reads the freeze took, so a CNTVOFF write that\n"
             "         had silently not landed would fail here",
             (credited == excluded_for) ? 1U : 0U);

    zx_check("so the partition's own clock cannot have advanced by anything\n"
             "         it could observe: the residue below is a fraction of a\n"
             "         thousandth of the interval, and it is the HYPERVISOR'S\n"
             "         OWN counter reads between the resume and this check --\n"
             "         on the S32Z280 a CNTPCT read crosses into an 8 MHz\n"
             "         clock domain and costs real time.  This is why a guest\n"
             "         gets the VIRTUAL timer: there is no CNTPOFF on this\n"
             "         architecture, so physical time cannot be given a\n"
             "         per-partition origin at all.  Written as a DIVISION and\n"
             "         not a multiplication: a residue times a thousand\n"
             "         overflows a 32-bit word once the gap passes four\n"
             "         million counts, and it would wrap to a small number and\n"
             "         pass",
             (virtual_gap < (physical_gap / 1000U)) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  PASS 2 of 3: the same work again, and the only honest pair.      */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n====================================================="
                    "====\n"
                    " PASS 2 of 3: the same guest, the same work, QUIET\n"
                    "====================================================="
                    "====\n"
                    "  Identical to pass 1 in every respect: same image, same\n"
                    "  options, same console traffic (none), stage 2 in force\n"
                    "  for both.  The difference between the two figures is\n"
                    "  therefore REPEATABILITY and not the cost of anything,\n"
                    "  which is the determinism claim that one partition on\n"
                    "  one core can actually support.\n");

    zx_guest_image_load(&zx_partition_a.zx_partition_load);
    zx_guest_hand_over(&zx_launch, 0U, ZX_GO_QUIET | ZX_GO_TICK);

    zx_check("the partition may be entered a third time",
             zx_partition_enter(&zx_partition_a));

    outcome  = zx_guest_run(&zx_launch, &zx_partition_a, &cycles_second);
    progress = zx_guest_report(&zx_launch);
    zx_report_tick();

    zx_check("the guest did the same work again and reached the same verdict",
             (((progress & (uint32_t)ZX_GP_FINISHED) != 0U)
              && (outcome == ZX_RUN_YIELDED)) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  PASS 3 of 3: loud, and the demonstration.                       */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n====================================================="
                    "====\n"
                    " PASS 3 of 3: the same guest, LOUD\n"
                    "====================================================="
                    "====\n"
                    "  Everything below the guest's own output is judged on\n"
                    "  THIS pass.  Each line is tagged by the partition ZoneX\n"
                    "  scheduled rather than by the guest, which is why a\n"
                    "  guest cannot claim to be another one.\n");

    zx_guest_image_load(&zx_partition_a.zx_partition_load);
    zx_guest_hand_over(&zx_launch, 0U, ZX_GO_TICK);

    zx_check("the partition may be entered a fourth time",
             zx_partition_enter(&zx_partition_a));

    {
        uint32_t loud_cycles = 0U;

        outcome = zx_guest_run(&zx_launch, &zx_partition_a, &loud_cycles);
        zx_note("outcome", outcome);
        zx_note("loud excursion, cycles", loud_cycles);
    }

    progress = zx_guest_report(&zx_launch);
    zx_report_tick();
    zx_partition_report(&zx_partition_a);

    if (outcome == ZX_RUN_FAULTED)
    {
        zx_fault_report(zx_el2_fault_record());
    }

    /* ---------------------------------------------------------------- */
    /*  The demonstrandum.                                              */
    /* ---------------------------------------------------------------- */

#ifdef ZX_PREEMPT_NO_PPI

    zx_console_puts("\n====================================================="
                    "====\n"
                    " NEGATIVE BUILD: the partition's PPI was never enabled\n"
                    "====================================================="
                    "====\n"
                    "  The counter runs, the GIC is awake, and the guest arms\n"
                    "  its virtual timer against a comparator that will\n"
                    "  expire -- but the interrupt is disabled in a frame the\n"
                    "  guest cannot reach, so nothing is ever delivered.\n"
                    "\n"
                    "  It must therefore report that it never ticked, and\n"
                    "  this run must report FAILED.  That is what proves the\n"
                    "  positive run's tick checks are capable of failing --\n"
                    "  and it proves something else that matters more: the\n"
                    "  guest could NOT enable its own interrupt.  A partition\n"
                    "  that could reach the redistributor would simply have\n"
                    "  turned it on.\n");

    zx_check("the counter and the GIC both came up, so nothing below is\n"
             "         explained by either of them failing (this check is\n"
             "         EXPECTED TO PASS)",
             granted);
    zx_check("the guest saw its virtual counter advance, so this is not the\n"
             "         counter and the failure below is the GIC (this check\n"
             "         is EXPECTED TO PASS)",
             ((progress & (uint32_t)ZX_GP_COUNTING) != 0U) ? 1U : 0U);
    zx_check("no tick reached the partition (this check is EXPECTED TO FAIL,\n"
             "         and its failing is the evidence)",
             ((progress & (uint32_t)ZX_GP_TICKING) != 0U) ? 1U : 0U);

#elif defined(ZX_PREEMPT_NO_FREEZE)

    zx_console_puts("\n====================================================="
                    "====\n"
                    " NEGATIVE BUILD: CNTVOFF is left alone across the gap\n"
                    "====================================================="
                    "====\n"
                    "  Everything else is identical.  The hypervisor simply\n"
                    "  does not advance CNTVOFF while the partition is not\n"
                    "  running, so the partition's virtual clock counts every\n"
                    "  cycle the hypervisor spent printing between passes.\n"
                    "\n"
                    "  The frozen-clock check above must therefore FAIL, and\n"
                    "  this run must report FAILED.  A claim whose pass\n"
                    "  condition is 'the guest could not tell' has to be seen\n"
                    "  to fail, or a green run shows only that the\n"
                    "  arithmetic did not crash.\n");

    zx_check("the counter and the GIC both came up, so this build breaks\n"
             "         nothing they are responsible for (expected to pass)",
             granted);
    zx_check("the guest still ticked and was still preempted, so this build\n"
             "         breaks the CLOCK and not the interrupt (expected to\n"
             "         pass)",
             ((progress & (uint32_t)(ZX_GP_TICKING | ZX_GP_PREEMPTED))
              == (uint32_t)(ZX_GP_TICKING | ZX_GP_PREEMPTED)) ? 1U : 0U);

#else

    zx_console_puts("\n====================================================="
                    "====\n"
                    " A REAL THREADX KERNEL, PREEMPTED UNDER STAGE 2\n"
                    "====================================================="
                    "====\n");

    zx_check("the guest yielded rather than faulting",
             (outcome == ZX_RUN_YIELDED) ? 1U : 0U);
    zx_check("it reached bsp_main and entered its kernel, so the loader and\n"
             "         the entry point are not what is being tested here",
             ((progress & (uint32_t)(ZX_GP_BSP_MAIN | ZX_GP_KERNEL_ENTERED))
              == (uint32_t)(ZX_GP_BSP_MAIN | ZX_GP_KERNEL_ENTERED))
                 ? 1U : 0U);
    zx_check("the partition's own VIRTUAL counter advances, which is a\n"
             "         different register from the one ZoneX checked: it is\n"
             "         the physical counter seen past CNTVOFF, and it is the\n"
             "         one the partition can actually reach",
             ((progress & (uint32_t)ZX_GP_COUNTING) != 0U) ? 1U : 0U);
    zx_check("A TICK REACHED THE PARTITION.  End to end: ZoneX enabled the\n"
             "         PPI in a redistributor the guest cannot address, the\n"
             "         guest enabled its own CPU interface, the GIC delivered\n"
             "         to EL1 and not to EL2, the guest's OWN vector table\n"
             "         sent it into the port's context save, and\n"
             "         _tx_timer_interrupt advanced tx_time_get()",
             ((progress & (uint32_t)ZX_GP_TICKING) != 0U) ? 1U : 0U);
    zx_check("A THREAD THAT NEVER YIELDS WAS DISPLACED.  The spinner makes\n"
             "         no kernel call in its loop, so there is no point at\n"
             "         which the kernel could have taken the core from it\n"
             "         cooperatively.  Something did anyway",
             ((progress & (uint32_t)ZX_GP_PREEMPTED) != 0U) ? 1U : 0U);
    zx_check("TWO EQUAL-PRIORITY THREADS WERE TIME SLICED.  Neither can\n"
             "         yield to the other and neither ever does, so the only\n"
             "         thing that can have interleaved them is the kernel\n"
             "         counting their slice down on a tick",
             ((progress & (uint32_t)ZX_GP_TIMESLICED) != 0U) ? 1U : 0U);
    zx_check("the partition received ONLY the interrupt it was granted -- no\n"
             "         unexpected INTID reached it, so it did not see the\n"
             "         hypervisor's own timer or anything else",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_ODD_INTID) == 0U)
                 ? 1U : 0U);
    zx_check("the guest's own vectors report no stage-1 fault, so a kernel\n"
             "         taking interrupts did nothing its own MPU refused",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_STAGE1)
              == ZX_GS_NONE) ? 1U : 0U);
    zx_check("the guest published its own verdict, and it is PASSED",
             (zx_guest_mailbox_read(&zx_launch, ZX_GD_VERDICT)
              == ZX_GV_PASSED) ? 1U : 0U);
    zx_check("the GIC and the counter were both brought up successfully",
             granted);

    zx_console_puts("\n--- the guest printed through the hypervisor ---\n");
    zx_note("characters forwarded", zx_guest_console_characters());
    zx_check("and no character arrived while NO partition was attached",
             (zx_guest_console_orphans() == 0U) ? 1U : 0U);

#endif

    /* ---------------------------------------------------------------- */
    /*  Repeatability.                                                  */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- two identical excursions ---\n");

    if (zx_pmu_is_running() == 0U)
    {
        zx_console_puts("  the PMU cycle counter is not advancing, so no\n"
                        "  timing is reported.  A number from a counter that\n"
                        "  is not running would be a very convincing wrong\n"
                        "  answer.\n");
    }
    else
    {
        uint32_t spread = (cycles_second >= cycles_first)
                              ? (cycles_second - cycles_first)
                              : (cycles_first - cycles_second);

        zx_note("first  quiet excursion, cycles", cycles_first);
        zx_note("second quiet excursion, cycles", cycles_second);
        zx_note("spread                        ", spread);

        zx_console_puts(
            "\n"
            "  WHAT THE PAIR IS.  Two excursions of one image doing one\n"
            "  program's worth of work with its console suppressed, ERET to\n"
            "  hand-back, with stage 2 in force for both and a tick arriving\n"
            "  throughout both.  They differ in NOTHING, which is what makes\n"
            "  the spread a measurement rather than a comparison.\n"
            "\n"
            "  WHAT IT IS NOT.  It is not the cost of an interrupt, and this\n"
            "  image deliberately does not offer one.  The obvious pair --\n"
            "  cooperative against preemptive -- differs in the tick AND in\n"
            "  the fact that the preemptive guest spends three ticks\n"
            "  deliberately waiting, so its difference would be dominated by\n"
            "  the waiting and quoted as the cost of an interrupt.  That is\n"
            "  the same error as measuring two passes that differ in\n"
            "  execution order and calling the difference stage 2, which\n"
            "  this suite has already made once.\n"
            "\n"
            "  ON A FUNCTIONAL MODEL BOTH NUMBERS MEAN NOTHING.  The FVP does\n"
            "  not model timing; they are printed anyway so that the\n"
            "  measurement path is exercised on every run.  The number to\n"
            "  quote comes from silicon.\n");
    }

    /* ---------------------------------------------------------------- */
    /*  Verdict.  The exact strings are what the runners grep for.      */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n====================================================="
                    "====\n"
                    " what this run does and does not prove\n"
                    "====================================================="
                    "====\n"
                    " " ZX_PLATFORM_NAME "\n"
                    "\n"
                    " PROVED, if the checks above are green: a real ThreadX\n"
                    " kernel is PREEMPTED inside a stage-2 confined window by\n"
                    " an interrupt the hypervisor granted it and that it\n"
                    " could not have granted itself; it receives that one and\n"
                    " no other; and its clock does not advance while it is\n"
                    " not running.\n"
                    "\n"
                    " NOT PROVED, and the omission is deliberate rather than\n"
                    " pending: this is not TIME PARTITIONING.  ZoneX cannot\n"
                    " yet END a partition's window, because nothing here\n"
                    " routes an interrupt to EL2 at all -- every physical\n"
                    " interrupt taken while a partition runs goes to EL1,\n"
                    " including the hypervisor's own timer.\n"
                    "\n"
                    " WHAT IT TAKES IS FIQ, NOT INJECTION, and the difference\n"
                    " is a rewrite against two register writes.  Routing is\n"
                    " by exception TYPE and not by INTID: HCR.FMO sends\n"
                    " physical FIQ to EL2 while HCR.IMO, left clear, leaves\n"
                    " IRQ with EL1.  So the hypervisor's tick goes in GROUP 0\n"
                    " -- which the GIC delivers as an FIQ -- and every guest\n"
                    " interrupt stays Group 1, stays an IRQ, and is still\n"
                    " delivered straight to EL1 exactly as it is here, with\n"
                    " no List Register anywhere.  See docs/decisions.md D24,\n"
                    " whose first version concluded the opposite and says so.\n"
                    "\n"
                    " NOT PROVED: anything about timing on a functional\n"
                    " model, and anything about more than one partition or\n"
                    " more than one logical core.\n");

    zx_console_puts("\n  checks failed: ");
    zx_console_putdec(zx_probe_failures());
    zx_console_puts("\n");

    if (zx_probe_failures() == 0U)
    {
        zx_console_puts("\nZONEX RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
    }

    zx_console_exit(zx_probe_failures());
}
