/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_partitions.c                                      EXAMPLE        */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    TWO partitions, from a manifest, proving each other's memory is     */
/*    unreachable.                                                        */
/*                                                                        */
/*  WHY BOTH DIRECTIONS ARE RUN                                           */
/*                                                                        */
/*    A run in which partition A reaches its own memory and faults on B's */
/*    is consistent with isolation.  It is equally consistent with B's    */
/*    memory simply not being mapped by anybody -- which is not           */
/*    isolation, it is an empty address space with one tenant.  Only the  */
/*    mirror settles it: B must then run, in ITS own memory, and fault on */
/*    A's.  The same address has to be reachable in one region set and    */
/*    unreachable in the other, and that is what a partition switch is.   */
/*                                                                        */
/*  WHY THE HOLE MATTERS MORE THAN THE NEIGHBOUR                          */
/*                                                                        */
/*    Faulting on the other partition's data proves the sets differ.  It  */
/*    does not prove the boundaries are right: two region sets a whole    */
/*    kilobyte apart would pass it.  The ungranted granule sits           */
/*    IMMEDIATELY after partition 0's data window, so touching it catches */
/*    a limit that is one granule too generous -- the defect that         */
/*    otherwise reads as a working system.                                */
/*                                                                        */
/*  WHAT THE SHARED GRANULE COSTS                                        */
/*                                                                        */
/*    One granule is readable by both partitions and writable by one.     */
/*    That is a deliberate, declared exception -- see the note on         */
/*    ZX_SHARED in core/inc/zx_manifest.h -- and the run demonstrates     */
/*    both halves of it: the reader can read it, and the reader CANNOT    */
/*    write it.  The second half is checked by fault status code, because */
/*    a permission failure and a region miss are different claims and     */
/*    only one of them means "read-only".                                 */
/*                                                                        */
/**************************************************************************/

#include "zx_platform.h"
#include "zx_probe.h"
#include "zx_guest_abi.h"
#include "zx_port.h"
#include "zx_manifest.h"
#include "zx_mm.h"

#define ZX_PARTITION_A          0U
#define ZX_PARTITION_B          1U

#define ZX_PARTITION_A_ID       1U
#define ZX_PARTITION_B_ID       2U

/* Region order within a partition's block.  Fixed so that a fault naming a
   region index can be read back to a window without counting.  */
#define ZX_PART_REGION_CODE     0U
#define ZX_PART_REGION_DATA     1U
#define ZX_PART_REGION_SHARED   2U
#define ZX_PART_REGION_COUNT    3U

static ZX_REGION        zx_regions_a[ZX_PART_REGION_COUNT];
static ZX_REGION        zx_regions_b[ZX_PART_REGION_COUNT];
static ZX_SHARED        zx_shared[1];
static ZX_PARTITION     zx_partitions[2];
static ZX_MANIFEST      zx_manifest;
static ZX_MM_LAYOUT     zx_layout;
static ZX_MANIFEST_ENV  zx_env;

/* The hypervisor's own MMIO, as the validator needs to see it.  The board
   programs these regions itself; this is the same geometry declared so that
   a partition window overlapping the console is rejected rather than
   discovered as CONSTRAINED UNPREDICTABLE.  */
static ZX_REGION        zx_mmio[ZX_BOARD_MAX_MMIO_REGIONS];


/**************************************************************************/
/*  zx_window -- fill in one region descriptor from a linker window.       */
/**************************************************************************/

static void zx_window(ZX_REGION *region_ptr, const char *start,
                      const char *end, UCHAR ap, UCHAR xn)
{
    region_ptr->zx_region_base       = zx_symbol_address(start);
    region_ptr->zx_region_limit      = zx_symbol_address(end) - 1U;
    region_ptr->zx_region_ap         = ap;
    region_ptr->zx_region_xn         = xn;
    region_ptr->zx_region_sh         = ZX_SH_NON_SHAREABLE;
    region_ptr->zx_region_attr_index = (UCHAR)ZX_ATTR_NORMAL_WB;
}


/**************************************************************************/
/*  zx_build_manifest -- the whole system, declared.                       */
/*                                                                        */
/*  Built at run time from linker symbols rather than written out as a     */
/*  initialised constant, because the windows' addresses are the linker's  */
/*  to choose and a manifest repeating them by hand would be a second      */
/*  source of truth that drifts.  A real system's manifest is a constant;  */
/*  this one describes a layout the linker script asserts.                 */
/**************************************************************************/

static void zx_build_manifest(uint32_t board_regions)
{
    /* Partition A: its own code and data, plus the shared granule it
       PUBLISHES -- so its copy is writable.  */
    zx_window(&zx_regions_a[ZX_PART_REGION_CODE],
              __zx_p0_code_start, __zx_p0_code_end,
              ZX_AP_EL2_RW_GUEST_RW, ZX_XN_EXECUTABLE);
    zx_window(&zx_regions_a[ZX_PART_REGION_DATA],
              __zx_p0_data_start, __zx_p0_data_end,
              ZX_AP_EL2_RW_GUEST_RW, ZX_XN_NEVER);
    zx_window(&zx_regions_a[ZX_PART_REGION_SHARED],
              __zx_shared_start, __zx_shared_end,
              ZX_AP_EL2_RW_GUEST_RW, ZX_XN_NEVER);

    /* Partition B: the mirror, except that its copy of the shared granule
       is READ-ONLY at any level.  Same range, different permission -- which
       is the whole reason a single shared region cannot express this.  */
    zx_window(&zx_regions_b[ZX_PART_REGION_CODE],
              __zx_p1_code_start, __zx_p1_code_end,
              ZX_AP_EL2_RW_GUEST_RW, ZX_XN_EXECUTABLE);
    zx_window(&zx_regions_b[ZX_PART_REGION_DATA],
              __zx_p1_data_start, __zx_p1_data_end,
              ZX_AP_EL2_RW_GUEST_RW, ZX_XN_NEVER);
    zx_window(&zx_regions_b[ZX_PART_REGION_SHARED],
              __zx_shared_start, __zx_shared_end,
              ZX_AP_EL2_RO_GUEST_RO, ZX_XN_NEVER);

    zx_shared[0].zx_shared_base         = zx_symbol_address(__zx_shared_start);
    zx_shared[0].zx_shared_limit        = zx_symbol_address(__zx_shared_end) - 1U;
    zx_shared[0].zx_shared_publisher_id = ZX_PARTITION_A_ID;

    zx_partitions[ZX_PARTITION_A].zx_partition_id           = ZX_PARTITION_A_ID;
    zx_partitions[ZX_PARTITION_A].zx_partition_name         = "partition A";
    zx_partitions[ZX_PARTITION_A].zx_partition_image_start  =
        zx_symbol_address(__zx_guest_blob_start);
    zx_partitions[ZX_PARTITION_A].zx_partition_image_end    =
        zx_symbol_address(__zx_guest_blob_end);
    zx_partitions[ZX_PARTITION_A].zx_partition_entry        =
        zx_symbol_address(__zx_p0_code_start) + ZX_GUEST_OFF_GRANT;
    zx_partitions[ZX_PARTITION_A].zx_partition_regions      = zx_regions_a;
    zx_partitions[ZX_PARTITION_A].zx_partition_region_count =
        ZX_PART_REGION_COUNT;
    zx_partitions[ZX_PARTITION_A].zx_partition_window_ticks = 7U;

    zx_partitions[ZX_PARTITION_B].zx_partition_id           = ZX_PARTITION_B_ID;
    zx_partitions[ZX_PARTITION_B].zx_partition_name         = "partition B";
    zx_partitions[ZX_PARTITION_B].zx_partition_image_start  =
        zx_symbol_address(__zx_guest_blob_start);
    zx_partitions[ZX_PARTITION_B].zx_partition_image_end    =
        zx_symbol_address(__zx_guest_blob_end);
    zx_partitions[ZX_PARTITION_B].zx_partition_entry        =
        zx_symbol_address(__zx_p1_code_start) + ZX_GUEST_OFF_GRANT;
    zx_partitions[ZX_PARTITION_B].zx_partition_regions      = zx_regions_b;
    zx_partitions[ZX_PARTITION_B].zx_partition_region_count =
        ZX_PART_REGION_COUNT;
    zx_partitions[ZX_PARTITION_B].zx_partition_window_ticks = 3U;

    zx_manifest.zx_manifest_partitions        = zx_partitions;
    zx_manifest.zx_manifest_partition_count   = 2U;
    zx_manifest.zx_manifest_shared            = zx_shared;
    zx_manifest.zx_manifest_shared_count      = 1U;
    zx_manifest.zx_manifest_major_frame_ticks = 10U;

    /* The environment: what the hypervisor knows and the manifest cannot.  */
    zx_board_describe_mmio_regions(zx_mmio);

    zx_env.zx_env_mmio_regions      = zx_mmio;
    zx_env.zx_env_mmio_region_count = board_regions;

    /* HMAIR indices this image actually programmed -- 0, 1 and 2.  A region
       naming any other index would get a zero MAIR byte, which is
       Device-nGnRnE: memory that works, slowly, with nothing to fault on.  */
    zx_env.zx_env_attr_written_mask = 0x07U;
}


/**************************************************************************/
/*  zx_program_from_plan -- write every region, then read it back.         */
/*                                                                        */
/*  The readback is not ceremony.  A region whose base was under-aligned   */
/*  programs successfully with its low bits landing on SH, AP and XN, and  */
/*  a region written at an index the implementation does not have is       */
/*  UNPREDICTABLE and may not stick at all.  Neither faults.  Comparing    */
/*  what the register holds against what was asked for is the only way     */
/*  either becomes visible, and it costs one read per region once at boot. */
/**************************************************************************/

static uint32_t zx_program_from_plan(void)
{
    uint32_t all_matched = 1U;
    UINT partition_index;

    for (partition_index = 0U;
         partition_index < zx_layout.zx_layout_partitions;
         partition_index++)
    {
        const ZX_PARTITION *partition_ptr =
            &zx_manifest.zx_manifest_partitions[partition_index];
        UINT first = zx_layout.zx_layout_partition_first[partition_index];
        UINT region_index;

        for (region_index = 0U;
             region_index < partition_ptr->zx_partition_region_count;
             region_index++)
        {
            const ZX_REGION *region_ptr =
                &partition_ptr->zx_partition_regions[region_index];
            uint32_t index = (uint32_t)(first + region_index);

            zx_stage2_region_program(index, region_ptr);

            if (zx_stage2_region_matches(index, region_ptr) == 0U)
            {
                zx_console_puts("  [FAIL] region ");
                zx_console_putdec(index);
                zx_console_puts(" did not read back as programmed\n");
                all_matched = 0U;
                zx_probe_fail();
            }
        }
    }

    return all_matched;
}


/**************************************************************************/
/*  The mailbox.  EL2 can write a partition's data window because stage-2  */
/*  AP cannot deny EL2 -- the same property that stops AP from isolating   */
/*  partitions is what makes a hypervisor-to-guest mailbox free.           */
/**************************************************************************/

static volatile uint32_t *zx_mailbox(const char *window_start)
{
    return (volatile uint32_t *)(uintptr_t)window_start;
}


static void zx_mailbox_reset(const char *window_start, uint32_t sentinel)
{
    volatile uint32_t *box = zx_mailbox(window_start);

    box[ZX_GD_PROGRESS / 4U]      = 0U;
    box[ZX_GD_SCRATCH / 4U]       = 0U;
    box[ZX_GD_TARGET / 4U]        = 0U;
    box[ZX_GD_PROBED / 4U]        = 0U;
    box[ZX_GD_SHARED / 4U]        = (uint32_t)zx_symbol_address(__zx_shared_start);
    box[ZX_GD_PUBLISH_VALUE / 4U] = sentinel;
}


/**************************************************************************/
/*  zx_enter -- switch to a partition's region set and run one entry.      */
/*                                                                        */
/*  Three things happen per switch and the ORDER is the interesting part:  */
/*  the enable mask, then VBAR, then the ERET.  VBAR has to be set while   */
/*  the incoming partition's code region is already enabled, because the   */
/*  vector table it points at lives inside that region -- installing it    */
/*  first would leave a window in which an exception would vector into     */
/*  memory the running context cannot reach.                               */
/**************************************************************************/

static uint32_t zx_enter(UINT partition_index, uint32_t entry_offset,
                         const char *code_window, const char *data_window,
                         const char *what)
{
    uint32_t mask = zx_mm_partition_mask(&zx_layout, partition_index);
    uint32_t outcome;

    zx_console_puts("\n--- ");
    zx_console_puts(zx_manifest.zx_manifest_partitions[partition_index]
                        .zx_partition_name);
    zx_console_puts(": ");
    zx_console_puts(what);
    zx_console_puts(" ---\n");

    zx_stage2_enable_set(mask);
    zx_note("HPRENR now", zx_hprenr_read());

    {
        uint32_t vbar = (uint32_t)zx_symbol_address(code_window)
                        + ZX_GUEST_OFF_VECTORS;

        __asm__ volatile("mcr p15, 0, %0, c12, c0, 0" : : "r"(vbar) : "memory");
        __asm__ volatile("isb");
    }

    zx_fault_record_reset(zx_el2_fault_record());

    outcome = zx_el2_run_payload(zx_symbol_address(code_window) + entry_offset,
                                 (uint32_t)zx_symbol_address(data_window));

    zx_note("progress", zx_mailbox(data_window)[ZX_GD_PROGRESS / 4U]);

    return outcome;
}


/**************************************************************************/
/*  zx_expect_fault -- a check whose PASS condition is an access failing.  */
/*                                                                        */
/*  Four things have to hold, and dropping any of them weakens the claim:  */
/*  the excursion came back as a fault rather than a yield; the guest's    */
/*  survival bit is clear, so the load genuinely did not complete; the     */
/*  syndrome is a stage-2 data abort routed to EL2 and not something else; */
/*  and HDFAR names the address that was aimed at.                        */
/*                                                                        */
/*  HDFAR and not HPFAR.  The two registers do not mean the same thing on  */
/*  the two targets -- the model returns a 4 KB page number where silicon  */
/*  returns the full address -- so a check written against HPFAR would be  */
/*  wrong by a factor of 256 on one of them.  HDFAR carries the full       */
/*  faulting address on both, and it is also the only one with the         */
/*  resolution to identify a 64-byte granule.  See docs/decisions.md D18.  */
/**************************************************************************/

static void zx_expect_fault(const char *what, uint32_t outcome,
                            const char *data_window, zx_addr_t target,
                            uint32_t expected_dfsc)
{
    const zx_fault_record_t *record = zx_el2_fault_record();
    uint32_t progress = zx_mailbox(data_window)[ZX_GD_PROGRESS / 4U];
    uint32_t hsr = record->zx_fault_hsr;

    zx_note("HDFAR", record->zx_fault_hdfar);
    zx_note("HSR  ", hsr);

    zx_check(what, ((outcome == ZX_RUN_FAULTED)
                    && ((progress & ZX_GP_PROBE_SURVIVED) == 0U)
                    && (zx_fault_ec(hsr) == ZX_EC_DABT_ROUTED)
                    && (record->zx_fault_hdfar == (uint32_t)target))
                       ? 1U : 0U);

    zx_check((expected_dfsc == ZX_DFSC_MPU_PERMISSION)
                 ? "         and DFSC says a region MATCHED and its AP refused\n"
                   "         the access -- read-only, not absent"
                 : "         and DFSC says NO enabled region covered it",
             (zx_fault_dabt_dfsc(hsr) == expected_dfsc) ? 1U : 0U);
}


/**************************************************************************/
/*  zx_phase_two_partitions                                                */
/**************************************************************************/

void zx_phase_two_partitions(uint32_t board_regions, uint32_t el2_regions)
{
    UINT status;
    ZX_MANIFEST_FAULT fault;
    uint32_t outcome;
    volatile uint32_t *shared =
        (volatile uint32_t *)(uintptr_t)__zx_shared_start;

    zx_console_puts(
        "\n=========================================================\n"
        " TWO PARTITIONS, FROM A MANIFEST\n"
        "=========================================================\n"
        "  Everything above ran ONE payload against one region set.\n"
        "  What follows declares two partitions in a manifest, has the\n"
        "  validator check it, turns it into a region layout, and runs\n"
        "  the same guest blob inside each partition's own memory.\n"
        "\n"
        "  A run where A reaches its own memory and faults on B's is\n"
        "  also consistent with B's memory being mapped by nobody, so\n"
        "  both directions are run: the same address has to be\n"
        "  reachable in one region set and unreachable in the other.\n");

    zx_build_manifest(board_regions);

#ifdef ZX_PROBE_MANIFEST_OVERLAP

    /* Aim partition B's data window at partition A's.  The validator must
       refuse BY NAME rather than the run discovering it: two enabled
       regions on one address is CONSTRAINED UNPREDICTABLE, and on the
       S32Z280 it aborts.  */
    zx_console_puts("\n  OVERLAP BUILD: partition B's data window has been\n"
                    "  aimed at partition A's, so the validator must refuse.\n");
    zx_regions_b[ZX_PART_REGION_DATA].zx_region_base =
        zx_symbol_address(__zx_p0_data_start);
    zx_regions_b[ZX_PART_REGION_DATA].zx_region_limit =
        zx_symbol_address(__zx_p0_data_end) - 1U;
#endif

#ifdef ZX_PROBE_BAD_ATTR

    /* An AttrIndx inside the architectural range that this image never
       wrote into HMAIR.  The hardware will not object: the region gets a
       zero MAIR byte, which is Device-nGnRnE, and works slowly.  */
    zx_console_puts("\n  BAD-ATTRIBUTE BUILD: partition A's data window names\n"
                    "  an HMAIR index this image never programmed, so the\n"
                    "  validator must refuse -- the hardware would not.\n");
    zx_regions_a[ZX_PART_REGION_DATA].zx_region_attr_index = 5U;
#endif

#ifdef ZX_PROBE_WIDEN_REGION

    /* Widen partition A's data window by exactly one granule, which
       swallows the ungranted hole next door.  The adjacent-granule probe
       must then SURVIVE and the run must report FAILED.  This is the
       negative verification of the boundary check itself: without it, a
       green run proves only that the probe address faults, not that the
       boundary is where the manifest says.  */
    zx_console_puts("\n  WIDENED-REGION BUILD: partition A's data window has\n"
                    "  been extended by one granule over the ungranted hole,\n"
                    "  so the adjacent-granule probe must SURVIVE and this\n"
                    "  run must report FAILED.\n");
    zx_regions_a[ZX_PART_REGION_DATA].zx_region_limit +=
        (zx_addr_t)ZX_MPU_GRANULE;
#endif

    /* ---------------------------------------------------------------- */
    /*  The validator, at boot.                                        */
    /* ---------------------------------------------------------------- */

    zx_env.zx_env_region_budget = el2_regions;

    status = zx_manifest_verify(&zx_manifest, &zx_env, &fault);

    zx_console_puts("\n--- the manifest, checked before anything is "
                    "programmed ---\n");
    zx_note("zx_manifest_verify", status);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_note("  offending partition", fault.zx_fault_partition);
        zx_note("  offending region   ", fault.zx_fault_region);
        zx_note("  second offender    ", fault.zx_fault_other_region);
        zx_console_puts("  the manifest was REFUSED, so no region was "
                        "programmed from it\n");
        zx_check("the manifest is valid", 0U);
        return;
    }

    zx_check("the manifest passes every rule", 1U);

    /* ---------------------------------------------------------------- */
    /*  The plan.                                                      */
    /* ---------------------------------------------------------------- */

    status = zx_mm_plan(&zx_manifest, board_regions, el2_regions, &zx_layout);
    zx_note("zx_mm_plan", status);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_check("the layout fits this part's region budget", 0U);
        return;
    }

    zx_check("the layout fits this part's region budget", 1U);
    zx_mm_report(&zx_layout, &zx_manifest);

    /* ---------------------------------------------------------------- */
    /*  Copy the guest into each partition, the way a real image goes.  */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- copying the guest blob into both windows ---\n");
    zx_note("blob source", zx_symbol_address(__zx_guest_blob_start));
    zx_note("blob length", (uint32_t)(zx_symbol_address(__zx_guest_blob_end)
                                      - zx_symbol_address(__zx_guest_blob_start)));

    {
        const uint32_t *source = (const uint32_t *)(uintptr_t)__zx_guest_blob_start;
        uint32_t *dest_a = (uint32_t *)(uintptr_t)__zx_p0_code_start;
        uint32_t *dest_b = (uint32_t *)(uintptr_t)__zx_p1_code_start;
        uint32_t words = (uint32_t)(ZX_GUEST_BLOB_SIZE / 4U);
        uint32_t index;

        for (index = 0U; index < words; index++)
        {
            dest_a[index] = source[index];
            dest_b[index] = source[index];
        }
    }

    /* The copies are data writes and will be FETCHED as instructions, so
       the instruction stream has to be told.  Caches are off in this image,
       which is exactly why this is written down: turning them on later
       without this would work on the model and fail on silicon.  */
    __asm__ volatile("dsb");
    __asm__ volatile("isb");

    zx_mailbox_reset(__zx_p0_data_start, ZX_GUEST_SENTINEL_A);
    zx_mailbox_reset(__zx_p1_data_start, ZX_GUEST_SENTINEL_B);
    *shared = 0U;

    /* ---------------------------------------------------------------- */
    /*  Program the regions the plan assigned, and check they stuck.    */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- programming the region set, and reading it back ---\n");
    zx_check("every region reads back as the manifest declared it",
             zx_program_from_plan());

    /* ---------------------------------------------------------------- */
    /*  PARTITION A.                                                   */
    /* ---------------------------------------------------------------- */

    outcome = zx_enter(ZX_PARTITION_A, ZX_GUEST_OFF_GRANT,
                       __zx_p0_code_start, __zx_p0_data_start,
                       "reaching its OWN data");
    zx_check("partition A ran, in its own copy of the guest, and reached its\n"
             "         own data window",
             ((outcome == ZX_RUN_YIELDED)
              && ((zx_mailbox(__zx_p0_data_start)[ZX_GD_PROGRESS / 4U]
                   & ZX_GP_OWN_DATA_OK) != 0U)
              && (zx_mailbox(__zx_p0_data_start)[ZX_GD_SCRATCH / 4U]
                  == ZX_GUEST_SENTINEL_A)) ? 1U : 0U);

    zx_mailbox(__zx_p0_data_start)[ZX_GD_TARGET / 4U] =
        (uint32_t)zx_symbol_address(__zx_p1_data_start);
    outcome = zx_enter(ZX_PARTITION_A, ZX_GUEST_OFF_PROBE,
                       __zx_p0_code_start, __zx_p0_data_start,
                       "reaching partition B's data");
    zx_expect_fault("partition A CANNOT reach partition B's data window",
                    outcome, __zx_p0_data_start,
                    zx_symbol_address(__zx_p1_data_start),
                    ZX_DFSC_MPU_MISS);

    /* The adjacent granule.  This is the check that says the BOUNDARY is
       right rather than merely that some far-away address faults.  */
    zx_mailbox(__zx_p0_data_start)[ZX_GD_TARGET / 4U] =
        (uint32_t)zx_symbol_address(__zx_p0_hole_start);
    outcome = zx_enter(ZX_PARTITION_A, ZX_GUEST_OFF_PROBE,
                       __zx_p0_code_start, __zx_p0_data_start,
                       "reaching the granule immediately after its own data");
    zx_console_puts("  this granule begins at the byte after partition A's\n"
                    "  data limit, so a limit one granule too generous is\n"
                    "  caught here and nowhere else\n");
    zx_expect_fault("the granule adjacent to partition A's data is NOT\n"
                    "         reachable, so the region's limit is exact",
                    outcome, __zx_p0_data_start,
                    zx_symbol_address(__zx_p0_hole_start),
                    ZX_DFSC_MPU_MISS);

    /* A publishes to the shared granule.  */
    zx_mailbox(__zx_p0_data_start)[ZX_GD_PUBLISH_VALUE / 4U] =
        ZX_GUEST_HEARTBEAT;
    outcome = zx_enter(ZX_PARTITION_A, ZX_GUEST_OFF_PUBLISH,
                       __zx_p0_code_start, __zx_p0_data_start,
                       "publishing to the shared granule");
    zx_check("partition A, the declared publisher, can WRITE the shared\n"
             "         granule",
             ((outcome == ZX_RUN_YIELDED)
              && ((zx_mailbox(__zx_p0_data_start)[ZX_GD_PROGRESS / 4U]
                   & ZX_GP_PUBLISHED) != 0U)
              && (*shared == ZX_GUEST_HEARTBEAT)) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  PARTITION B -- the mirror.                                     */
    /* ---------------------------------------------------------------- */

    outcome = zx_enter(ZX_PARTITION_B, ZX_GUEST_OFF_GRANT,
                       __zx_p1_code_start, __zx_p1_data_start,
                       "reaching its OWN data");
    zx_check("partition B ran, in its own copy of the guest, and reached its\n"
             "         own data window",
             ((outcome == ZX_RUN_YIELDED)
              && ((zx_mailbox(__zx_p1_data_start)[ZX_GD_PROGRESS / 4U]
                   & ZX_GP_OWN_DATA_OK) != 0U)
              && (zx_mailbox(__zx_p1_data_start)[ZX_GD_SCRATCH / 4U]
                  == ZX_GUEST_SENTINEL_B)) ? 1U : 0U);

    zx_mailbox(__zx_p1_data_start)[ZX_GD_TARGET / 4U] =
        (uint32_t)zx_symbol_address(__zx_p0_data_start);
    outcome = zx_enter(ZX_PARTITION_B, ZX_GUEST_OFF_PROBE,
                       __zx_p1_code_start, __zx_p1_data_start,
                       "reaching partition A's data");
    zx_console_puts("  the SAME address partition A read successfully a few\n"
                    "  lines ago.  One region set granted it and the other\n"
                    "  denies it, which is what a partition switch is.\n");
    zx_expect_fault("partition B CANNOT reach partition A's data window",
                    outcome, __zx_p1_data_start,
                    zx_symbol_address(__zx_p0_data_start),
                    ZX_DFSC_MPU_MISS);

    /* B reads what A published: the declared, deliberate exception.  */
    outcome = zx_enter(ZX_PARTITION_B, ZX_GUEST_OFF_CONSUME,
                       __zx_p1_code_start, __zx_p1_data_start,
                       "reading the shared granule");
    zx_check("partition B can READ the granule partition A published, and\n"
             "         reads back the value A wrote",
             ((outcome == ZX_RUN_YIELDED)
              && ((zx_mailbox(__zx_p1_data_start)[ZX_GD_PROGRESS / 4U]
                   & ZX_GP_CONSUMED) != 0U)
              && (zx_mailbox(__zx_p1_data_start)[ZX_GD_PROBED / 4U]
                  == ZX_GUEST_HEARTBEAT)) ? 1U : 0U);

    /* And cannot write it.  Checked by fault status code, because
       "read-only" and "not mapped here at all" are different claims.  */
    zx_mailbox(__zx_p1_data_start)[ZX_GD_PUBLISH_VALUE / 4U] = 0xDEADBEEFU;
    outcome = zx_enter(ZX_PARTITION_B, ZX_GUEST_OFF_PUBLISH,
                       __zx_p1_code_start, __zx_p1_data_start,
                       "trying to WRITE the shared granule");
    zx_expect_fault("partition B CANNOT write the shared granule",
                    outcome, __zx_p1_data_start,
                    zx_symbol_address(__zx_shared_start),
                    ZX_DFSC_MPU_PERMISSION);
    zx_check("and the granule still holds partition A's value, so the\n"
             "         refused write changed nothing",
             (*shared == ZX_GUEST_HEARTBEAT) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  What EL2 can see, which is everything.                         */
    /* ---------------------------------------------------------------- */

    /* ---------------------------------------------------------------- */
    /*  What a partition switch COSTS.                                  */
    /*                                                                  */
    /*  Reported in cycles because that is the unit a WCET argument is   */
    /*  made in, and because there is no alternative here: CNTFRQ reads  */
    /*  zero on both targets, so nothing can convert to seconds.        */
    /*                                                                  */
    /*  The measurement overhead is measured too and subtracted.  A      */
    /*  switch is a single register write and two barriers, so the cost  */
    /*  of reading the counter twice is not a rounding error against it  */
    /*  -- it is potentially most of the number.                        */
    /*                                                                  */
    /*  ON THE MODEL THIS NUMBER MEANS NOTHING.  The FVP is a functional */
    /*  model, not a timing model; it is printed anyway so that the      */
    /*  measurement path itself is exercised on every run rather than    */
    /*  only when a board is attached.  The number to quote comes from   */
    /*  silicon.                                                        */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- what a partition switch costs ---\n");

    zx_pmu_enable();

    if (zx_pmu_is_running() == 0U)
    {
        zx_console_puts("  the PMU cycle counter is not advancing, so no\n"
                        "  timing is reported.  This is not a check failure:\n"
                        "  a number from a counter that is not running would\n"
                        "  be a very convincing wrong answer.\n");
    }
    else
    {
        uint32_t mask_a = zx_mm_partition_mask(&zx_layout, ZX_PARTITION_A);
        uint32_t mask_b = zx_mm_partition_mask(&zx_layout, ZX_PARTITION_B);
        uint32_t overhead;
        uint32_t switch_cost;
        uint32_t region_cost;
        uint32_t start;
        uint32_t index;

        /* The cost of asking, with nothing between the two reads.  */
        start = zx_pmu_cycles();
        overhead = zx_pmu_cycles() - start;

        /* Eight switches, alternating, so that no run is measuring a
           no-op: writing the mask that is already in force could be
           optimised by an implementation in a way a real switch is not.  */
        start = zx_pmu_cycles();
        for (index = 0U; index < 4U; index++)
        {
            zx_stage2_enable_set(mask_b);
            zx_stage2_enable_set(mask_a);
        }
        switch_cost = ((zx_pmu_cycles() - start) - overhead) / 8U;

        /* And one region descriptor write, for comparison.  This is the
           cost a switch would carry PER REGION if the region block were
           rewritten instead of the mask being changed, which is the
           alternative design and the reason the mask was chosen.  */
        start = zx_pmu_cycles();
        for (index = 0U; index < 8U; index++)
        {
            zx_stage2_region_program(
                (uint32_t)zx_layout.zx_layout_partition_first[ZX_PARTITION_A],
                &zx_regions_a[ZX_PART_REGION_CODE]);
        }
        region_cost = ((zx_pmu_cycles() - start) - overhead) / 8U;

        zx_note("counter read overhead, cycles", overhead);
        zx_note("HPRENR mask switch, cycles   ", switch_cost);
        zx_note("one region write, cycles     ", region_cost);

        zx_console_puts(
            "  the mask switch is the whole cost of changing partitions:\n"
            "  region descriptors are programmed once at boot, so the\n"
            "  per-region figure is what the alternative design would pay\n"
            "  for EVERY region on EVERY switch.\n"
            "  ON THIS TARGET the figures are only meaningful if it is\n"
            "  silicon.  A functional model does not model timing.\n");

        /* Restore partition A's set, so the state at the end of the phase
           is the one the report above describes.  */
        zx_stage2_enable_set(mask_a);
    }

    zx_console_puts("\n--- what the hypervisor can read, from EL2 ---\n");
    zx_note("partition A scratch", zx_mailbox(__zx_p0_data_start)[ZX_GD_SCRATCH / 4U]);
    zx_note("partition B scratch", zx_mailbox(__zx_p1_data_start)[ZX_GD_SCRATCH / 4U]);
    zx_check("EL2 reads BOTH partitions' memory, and the two sentinels\n"
             "         differ -- stage-2 AP cannot deny EL2, so a partition\n"
             "         is never hidden from the hypervisor that owns it",
             ((zx_mailbox(__zx_p0_data_start)[ZX_GD_SCRATCH / 4U]
               == ZX_GUEST_SENTINEL_A)
              && (zx_mailbox(__zx_p1_data_start)[ZX_GD_SCRATCH / 4U]
                  == ZX_GUEST_SENTINEL_B)) ? 1U : 0U);
}
