/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_probe_main.c                                       SHARED        */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Stage-2 first light.  One EL2 program, one trivial EL1 payload, and */
/*    one deliberate fault.                                              */
/*                                                                        */
/*    What this image is for, in one sentence: an EL2-resident ZoneX       */
/*    programs a stage-2 MPU region, drops to EL1, and a stage-2 violation */
/*    by the EL1 payload is taken to EL2, decoded, and reported by name.   */
/*    Nothing else in ZoneX is worth building until that works, because    */
/*    everything else assumes it.                                        */
/*                                                                        */
/*    It also settles four things that were open before it ran, and each   */
/*    of them changes the design of what comes next:                      */
/*                                                                        */
/*      1.  Does the target implement an EL2 MPU at all, and how many      */
/*          regions?  HMPUIR may legally read 0.                          */
/*      2.  Is HPRENR really wider than 16 bits?  Answered FUNCTIONALLY,   */
/*          by disabling a region above 15 and proving the memory it       */
/*          covered stops being reachable -- not by reading the register   */
/*          back, which a register that accepted the bit and ignored it    */
/*          would pass.                                                   */
/*      3.  Can a region above 15 be reached DIRECTLY, at opc1 = 5?  If it */
/*          can, the EL2 MPU escapes the selection-register penalty        */
/*          measured at EL1, which is a worst-case-execution-time fact.    */
/*      4.  What exactly is HPFAR's relationship to the faulting address?  */
/*          Measured against an address this image chose itself.          */
/*                                                                        */
/*  WHAT A PASS MEANS, AND WHAT IT DOES NOT                               */
/*                                                                        */
/*    A pass on the Armv8-R AEM FVP proves the code is right.  It proves   */
/*    NOTHING about the region budget or the MMIO attributes on a real     */
/*    part: the model reports 32 EL2 regions, which no Cortex-R52 can      */
/*    have, and its console and GIC sit in the Device band of the          */
/*    background map where the S32Z280's do not.  Both of those are said   */
/*    out loud in the image's own output rather than left in a document.   */
/*                                                                        */
/*    On lockstep silicon this image demonstrates memory isolation on ONE  */
/*    logical core.  It does not demonstrate spatial multicore            */
/*    partitioning.                                                       */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                    */
/*                                                                        */
/*    Rule 11.4/11.6 -- casting a linker symbol's address to an integer    */
/*      address is inherent to describing memory to an MPU.  Confined to   */
/*      zx_symbol_address below.                                          */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"
#include "zx_platform.h"

/* How many checks failed.  Accumulated rather than returned, because the
   image reports EVERY check and then its verdict: stopping at the first
   failure would hide the identity block that explains it.  */

static uint32_t zx_failures;

/* Region 16's descriptor is kept because two phases need it -- the enabled
   probe and, when the deliberate EL2 fault is built in, a reprogramming of
   the same region with EL2 read-only permissions.  */

static ZX_REGION zx_high_probe_region;


/**************************************************************************/
/*  zx_symbol_address -- a linker symbol's address as an MPU address.      */
/**************************************************************************/

static zx_addr_t zx_symbol_address(const char *symbol)
{
    return (zx_addr_t)(uintptr_t)symbol;
}


/**************************************************************************/
/*  zx_report / zx_check -- one labelled line each.                       */
/*                                                                        */
/*  Fixed-width labels so that a captured log lines up and a missing       */
/*  result is visible as a gap rather than having to be counted.          */
/**************************************************************************/

static void zx_check(const char *label, uint32_t passed)
{
    zx_console_puts("  [");
    zx_console_puts((passed != 0U) ? "PASS" : "FAIL");
    zx_console_puts("] ");
    zx_console_puts(label);
    zx_console_puts("\n");

    if (passed == 0U)
    {
        zx_failures++;
    }
}


static void zx_note(const char *label, uint32_t value)
{
    zx_console_puts("  ");
    zx_console_puts(label);
    zx_console_puts(" = ");
    zx_console_puthex(value);
    zx_console_puts("\n");
}


/**************************************************************************/
/*  zx_identity_block -- T2.                                              */
/*                                                                        */
/*  Reads and prints what the core says about itself, then ASSERTS the     */
/*  parts that a later step would otherwise assume.  The region count is   */
/*  the one that matters: refusing to enable stage 2 when the count is too */
/*  low is the difference between a clear message and a hang, and it is    */
/*  exactly what the EL1 MPU initialisation already does in the           */
/*  Cortex-R52 port.                                                      */
/**************************************************************************/

static uint32_t zx_identity_block(uint32_t regions_required)
{
    uint32_t el2_regions = zx_el2_region_count();
    uint32_t el1_regions = zx_el1_region_count();
    uint32_t ich_vtr     = zx_read_ich_vtr();
    uint32_t cpsr        = zx_read_cpsr();
    uint32_t midr        = zx_read_midr();

    zx_console_puts("\n--- identity, as the core reports it ---\n");

    zx_note("MIDR         ", midr);
    zx_console_puts("               part ");
    zx_console_puthex((midr >> 4U) & 0xFFFU);
    zx_console_puts(" (0xD13 = Cortex-R52, 0xD16 = Cortex-R52+)\n");

    zx_note("MPIDR        ", zx_read_mpidr());
    zx_note("CPSR (now)   ", cpsr);
    zx_console_puts("               mode ");
    zx_console_puthex(cpsr & ZX_MODE_MASK);
    zx_console_puts((( cpsr & ZX_MODE_MASK) == ZX_MODE_HYP)
                    ? " = Hyp, which is EL2\n" : " = NOT Hyp\n");

    zx_note("CPSR at reset", zx_reset_cpsr);
    zx_console_puts("               read by the FIRST instruction executed.  "
                    "Its mode\n"
                    "               field is the useful part; PSTATE.T is NOT "
                    "readable\n"
                    "               through MRS and always reads 0 here, on "
                    "both a\n"
                    "               target that starts in A32 and one that "
                    "starts in T32.\n"
                    "               Use HSCTLR.TE and SCTLR.TE below, and a "
                    "debugger.\n");
    zx_note("HSCTLR reset ", zx_reset_hsctlr);
    zx_console_puts("               TE at reset was ");
    zx_console_puts(((zx_reset_hsctlr & ZX_HSCTLR_TE) != 0U) ? "SET" : "clear");
    zx_console_puts(" -- set means EL2 exceptions are\n"
                    "               entered in T32 and an A32 vector table "
                    "never runs\n");
    zx_note("SCTLR reset  ", zx_reset_sctlr);
    zx_note("HSCTLR (now) ", zx_read_hsctlr());
    zx_note("HCR (now)    ", zx_read_hcr());
    zx_note("HSR (now)    ", zx_read_hsr());
    zx_note("HVBAR        ", zx_read_hvbar());
    zx_note("CNTFRQ       ", zx_read_cntfrq());
    zx_note("HPRENR reset ", zx_reset_hprenr);
    zx_note("HPRENR bits  ", zx_hprenr_implemented_bits);
    zx_console_puts("               what stuck when all ones were written "
                    "before any\n"
                    "               region existed, so these are the "
                    "IMPLEMENTED enable\n"
                    "               bits.  Whether one above 15 really "
                    "disables its\n"
                    "               region is tested functionally further "
                    "down.\n");
    zx_note("ICH_VTR      ", ich_vtr);
    zx_console_puts("               ListRegs field ");
    zx_console_putdec(ich_vtr & 0x1FU);
    zx_console_puts(", so ");
    zx_console_putdec((ich_vtr & 0x1FU) + 1U);
    zx_console_puts(" List Registers -- interrupt\n"
                    "               injection is available on this part\n");

    zx_board_report();

    /* ---------------------------------------------------------------- */
    /*  The region budget.  Both numbers, side by side, always.         */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- the EL2 region budget ---\n");
    zx_note("MPUIR        ", zx_read_mpuir());
    zx_note("HMPUIR       ", zx_read_hmpuir());

    zx_console_puts("  EL1 regions (MPUIR[15:8])  = ");
    zx_console_putdec(el1_regions);
    zx_console_puts("\n  EL2 regions (HMPUIR[7:0])  = ");
    zx_console_putdec(el2_regions);
    zx_console_puts("\n  EL2 regions this image NEEDS = ");
    zx_console_putdec(regions_required);
    zx_console_puts("\n");

    if (zx_el2_region_count_is_legal(el2_regions) == 0U)
    {
        zx_console_puts(
            "\n  *** HMPUIR reports ");
        zx_console_putdec(el2_regions);
        zx_console_puts(" EL2 regions.  TRM Table 3-79 permits only\n"
            "  *** 0, 16, 20 or 24, so THIS TARGET IS NOT AN ARCHITECTURALLY\n"
            "  *** LEGAL Cortex-R52 CONFIGURATION.  That is expected of the\n"
            "  *** Armv8-R AEM FVP, which reported 32 EL1 regions during the\n"
            "  *** Cortex-R52 port work as well.  It is recorded rather than\n"
            "  *** failed, and it is the reason a green run of this image on\n"
            "  *** the model says NOTHING about any real part's budget.\n");
    }
    else
    {
        zx_check("HMPUIR reports an architecturally legal region count", 1U);
    }

    if (el2_regions == 0U)
    {
        zx_console_puts(
            "\n  *** HMPUIR reports ZERO EL2 regions.  That is a legal\n"
            "  *** configuration -- \"no EL2-controlled MPU\" -- and it means\n"
            "  *** this target cannot host stage 2 at all.  Refusing to go on.\n");
        return 0U;
    }

    if (el2_regions < regions_required)
    {
        zx_console_puts(
            "\n  *** This target has fewer EL2 regions than this image needs.\n"
            "  *** REFUSING to enable stage 2: programming a region that does\n"
            "  *** not exist is UNPREDICTABLE, and the failure would present\n"
            "  *** as a hang rather than as a message.\n");
        return 0U;
    }

    return 1U;
}


/**************************************************************************/
/*  zx_program_regions -- T4.                                             */
/*                                                                        */
/*  The smallest honest region set: the payload's code, the payload's      */
/*  data, whatever MMIO the hypervisor itself owns on this board, and the  */
/*  granule region 16 covers for the high-region experiments.             */
/*                                                                        */
/*  What is deliberately NOT here is a region for the granule immediately  */
/*  after the payload's data.  An address far away from every grant proves */
/*  only that unmapped memory faults; the defect class worth catching is a */
/*  limit or a base off by ONE GRANULE, and only an adjacent hole catches  */
/*  it.                                                                    */
/**************************************************************************/

static void zx_program_regions(uint32_t board_regions)
{
    ZX_REGION region;
    uint32_t    direct_base  = 0U;
    uint32_t    direct_limit = 0U;
    uint32_t    select_base  = 0U;
    uint32_t    select_limit = 0U;

    zx_console_puts("\n--- programming stage 2 ---\n");

    /* HMAIR was programmed before the console, along with the hypervisor's
       own MMIO regions; the values are reported here, where they can be read
       next to the regions that index them.  */

    zx_note("HMAIR0 (already written)", ZX_HMAIR0_VALUE);
    zx_note("HMAIR1 (already written)", ZX_HMAIR1_VALUE);

    /* Region 0: the payload's code.  Executable, and readable so its own
       literal pool works.  AP grants EL1 read/write, which is more than
       code needs -- but there is no EL2 AP encoding that is read-only to a
       guest and writable to EL2, and the loader needs to be able to write
       it.  Write protection of guest code is a stage-1 job, and stage 1 is
       deliberately off in this image.  */

    region.zx_region_base     = zx_symbol_address(__zx_payload_code_start);
    region.zx_region_limit    = zx_symbol_address(__zx_payload_code_end) - 1U;
    region.zx_region_ap       = ZX_AP_EL2_RW_GUEST_RW;
    region.zx_region_xn       = ZX_XN_EXECUTABLE;
    region.zx_region_sh       = ZX_SH_NON_SHAREABLE;
    region.zx_region_attr_index = ZX_ATTR_NORMAL_WB;
    zx_stage2_region_program(ZX_REGION_PAYLOAD_CODE, &region);

    zx_console_puts("  region  0  payload code  ");
    zx_console_puthex(region.zx_region_base);
    zx_console_puts(" .. ");
    zx_console_puthex(region.zx_region_limit);
    zx_console_puts("  RW, executable\n");

    /* Region 1: the payload's data.  Execute-never.  */

    region.zx_region_base     = zx_symbol_address(__zx_payload_data_start);
    region.zx_region_limit    = zx_symbol_address(__zx_payload_data_end) - 1U;
    region.zx_region_ap       = ZX_AP_EL2_RW_GUEST_RW;
    region.zx_region_xn       = ZX_XN_NEVER;
    region.zx_region_sh       = ZX_SH_NON_SHAREABLE;
    region.zx_region_attr_index = ZX_ATTR_NORMAL_WB;
    zx_stage2_region_program(ZX_REGION_PAYLOAD_DATA, &region);

    zx_console_puts("  region  1  payload data  ");
    zx_console_puthex(region.zx_region_base);
    zx_console_puts(" .. ");
    zx_console_puthex(region.zx_region_limit);
    zx_console_puts("  RW, execute-never\n");

    /* The board's own MMIO, already programmed before the console.  */

    if (board_regions > 0U)
    {
        zx_console_puts("  regions ");
        zx_console_putdec(ZX_REGION_BOARD_FIRST);
        zx_console_puts("..");
        zx_console_putdec((ZX_REGION_BOARD_FIRST + board_regions) - 1U);
        zx_console_puts("  the hypervisor's own MMIO, Device attributes,\n"
                        "             programmed before this console was used\n");
    }
    else
    {
        zx_console_puts("  no hypervisor MMIO regions on this target: its\n"
                        "  console and GIC fall in the Device band of the\n"
                        "  background map, so HSCTLR.BR serves them.  A board\n"
                        "  whose devices sit below 0x60000000 needs regions\n"
                        "  here and THIS TARGET CANNOT SHOW YOU THAT.\n");
    }

    /* Region 16: the high-region probe.  Programmed through the DIRECT
       encoding at opc1 = 5, then read back through HPRSELR/HPRBAR -- the
       other path -- so that agreement between them is what settles whether
       TRM 8.4 or TRM 3.3.48's prose is right about direct access above
       region 15.  */

    zx_high_probe_region.zx_region_base  =
        zx_symbol_address(__zx_high_probe_start);
    zx_high_probe_region.zx_region_limit =
        zx_symbol_address(__zx_high_probe_end) - 1U;
    zx_high_probe_region.zx_region_ap       = ZX_AP_EL2_RW_GUEST_RW;
    zx_high_probe_region.zx_region_xn       = ZX_XN_NEVER;
    zx_high_probe_region.zx_region_sh       = ZX_SH_NON_SHAREABLE;
    zx_high_probe_region.zx_region_attr_index = ZX_ATTR_NORMAL_WB;

    zx_stage2_region_program_direct16(&zx_high_probe_region);

    zx_console_puts("  region 16  high probe    ");
    zx_console_puthex(zx_high_probe_region.zx_region_base);
    zx_console_puts(" .. ");
    zx_console_puthex(zx_high_probe_region.zx_region_limit);
    zx_console_puts("  written DIRECTLY, opc1 = 5\n");

    zx_stage2_region_read_direct16(&direct_base, &direct_limit);
    zx_stage2_region_read(ZX_REGION_HIGH_PROBE, &select_base, &select_limit);

    zx_console_puts("\n--- open question: direct access above region 15 ---\n");
    zx_note("HPRBAR16 via opc1 = 5   ", direct_base);
    zx_note("HPRBAR16 via HPRSELR    ", select_base);
    zx_note("HPRLAR16 via opc1 = 5   ", direct_limit);
    zx_note("HPRLAR16 via HPRSELR    ", select_limit);

    zx_check("HPRBAR16/HPRLAR16 read the same through both access paths, so\n"
             "         a region above 15 is directly addressable at opc1 = 5\n"
             "         (TRM 8.4 is right and 3.3.48's prose is stale)",
             ((direct_base == select_base) && (direct_limit == select_limit))
                 ? 1U : 0U);

    zx_note("HPRENR after programming", zx_hprenr_read());

    /* The granule that is deliberately NOT covered.  Printed so that a
       reader of a captured log can see it is adjacent to region 1 rather
       than having to take that on trust.  */

    zx_console_puts("\n  ungranted granule (no region covers it) ");
    zx_console_puthex(zx_symbol_address(__zx_forbidden_start));
    zx_console_puts(" .. ");
    zx_console_puthex(zx_symbol_address(__zx_forbidden_end) - 1U);
    zx_console_puts("\n  it begins at the byte after region 1's limit, which\n"
                    "  is what makes an off-by-one-granule region bug visible\n");
}


/**************************************************************************/
/*  zx_run_phase -- one excursion to EL1, with its outcome named.          */
/**************************************************************************/

static uint32_t zx_run_phase(const char *name, char *entry, uint32_t argument)
{
    uint32_t outcome;

    zx_console_puts("\n--- EL1 phase: ");
    zx_console_puts(name);
    zx_console_puts(" ---\n");

    outcome = zx_el2_run_payload(zx_symbol_address(entry), argument);

    zx_console_puts("  the payload came back as ");
    switch (outcome)
    {
    case ZX_RUN_YIELDED:
        zx_console_puts("ZX_RUN_YIELDED (HVC #1)\n");
        break;
    case ZX_RUN_FAULTED:
        zx_console_puts("ZX_RUN_FAULTED (a stage-2 violation)\n");
        break;
    case ZX_RUN_TRAPPED:
        zx_console_puts("ZX_RUN_TRAPPED (something else reached EL2)\n");
        break;
    default:
        zx_console_puts("an UNKNOWN outcome, which is a ZoneX bug\n");
        break;
    }

    zx_note("zx_payload_result", zx_payload_result);

    return outcome;
}


/**************************************************************************/
/*  zx_phase_grant -- stage 2 grants what it should.                      */
/**************************************************************************/

static void zx_phase_grant(void)
{
    uint32_t outcome = zx_run_phase("does stage 2 GRANT what it should?",
                                    zx_payload_grant_check, 0U);

    zx_check("the payload reached EL1 and ran",
             ((zx_payload_result & ZX_PAYLOAD_RAN) != 0U) ? 1U : 0U);
    zx_check("the payload wrote and read back its own data region",
             ((zx_payload_result & ZX_PAYLOAD_OWN_DATA_OK) != 0U) ? 1U : 0U);
    zx_check("the payload yielded rather than faulting",
             (outcome == ZX_RUN_YIELDED) ? 1U : 0U);

    /* The EXACT value, not just the bits of interest.  The progress bits are
       spelled in two places -- ZX_PAYLOAD_* here and .equ directives in
       zx_payload.S -- because no header can be read by both an assembler and
       a compiler without inventing one for six constants.  Checking the whole
       word after a phase whose outcome is fully known turns that duplication
       from a comment asking for care into a test: a bit renumbered on one
       side and not the other fails here, on both targets, in the first
       phase.  */

    zx_check("zx_payload_result is EXACTLY the two bits this phase sets, which\n"
             "         is what keeps the progress bits in zx_payload.S and in\n"
             "         zx_probe.h from drifting apart",
             (zx_payload_result
              == (ZX_PAYLOAD_RAN | ZX_PAYLOAD_OWN_DATA_OK)) ? 1U : 0U);

    zx_note("zx_payload_scratch, read from EL2", zx_payload_scratch);
    zx_check("EL2 can read the partition's memory, which no AP encoding at\n"
             "         EL2 can deny it (docs/decisions.md D3)",
             (zx_payload_scratch == ZX_PAYLOAD_SENTINEL) ? 1U : 0U);
}


/**************************************************************************/
/*  zx_phase_hypercall -- the empty Phase-0 hypercall vector.             */
/**************************************************************************/

static void zx_phase_hypercall(void)
{
    uint32_t before = zx_el2_hypercall_count();
    uint32_t outcome;

    outcome = zx_run_phase("is the HVC seam live and transparent?",
                           zx_payload_hvc_check, 0U);

    zx_console_puts("  HVC #0 count before/after = ");
    zx_console_putdec(before);
    zx_console_puts(" / ");
    zx_console_putdec(zx_el2_hypercall_count());
    zx_console_puts("\n");

    zx_check("HVC #0 was counted at EL2",
             (zx_el2_hypercall_count() == (before + 1U)) ? 1U : 0U);
    zx_check("HVC #0 RETURNED to the payload, so EL2 can be entered and left\n"
             "         without disturbing the guest",
             ((zx_payload_result & ZX_PAYLOAD_HVC_RETURNED) != 0U) ? 1U : 0U);
    zx_check("the payload yielded rather than faulting",
             (outcome == ZX_RUN_YIELDED) ? 1U : 0U);
}


/**************************************************************************/
/*  zx_phase_hprenr -- T3, the HPRENR width question, answered            */
/*                     functionally.                                      */
/*                                                                        */
/*  The same address is read twice: once with region 16 enabled and once   */
/*  with HPRENR bit 16 cleared.  If bits above 15 are read/write but       */
/*  ignored -- the worst possible outcome, and the one a read-back test    */
/*  would miss -- the second read succeeds and this reports it.           */
/**************************************************************************/

static void zx_phase_hprenr(uint32_t el2_regions)
{
    zx_addr_t probe_address = zx_symbol_address(__zx_high_probe_start);
    uint32_t  outcome;
    uint32_t  enr_before;
    uint32_t  enr_after;

    zx_console_puts("\n=========================================================\n"
                    " OPEN QUESTION: is HPRENR wider than 16 bits?\n"
                    "=========================================================\n");

    if (el2_regions <= ZX_REGION_HIGH_PROBE)
    {
        zx_console_puts(
            "  SKIPPED.  This target has ");
        zx_console_putdec(el2_regions);
        zx_console_puts(" EL2 regions, so index 16 does not\n"
            "  exist here and the question cannot be asked on it.  This is a\n"
            "  legal configuration, not a failure -- but the question stays\n"
            "  OPEN, and D4's one-write partition switch stays unproven.\n");
        return;
    }

    /* With the region enabled, the read must succeed and must return the
       sentinel.  Returning the right VALUE is what distinguishes a region
       that maps the intended memory from one that merely permits an
       access.  */

    enr_before = zx_hprenr_read();
    zx_note("HPRENR with region 16 enabled ", enr_before);

    outcome = zx_run_phase("read the granule region 16 covers, ENABLED",
                           zx_payload_probe_read, probe_address);

    zx_note("value the payload read", zx_payload_probe_value);
    zx_check("with HPRENR bit 16 SET, the payload can read the granule",
             ((outcome == ZX_RUN_YIELDED)
              && ((zx_payload_result & ZX_PAYLOAD_PROBE_OK) != 0U)) ? 1U : 0U);
    zx_check("and it read the SENTINEL, so region 16 maps the memory it was\n"
             "         programmed for rather than merely permitting an access",
             (zx_payload_probe_value == ZX_HIGH_PROBE_SENTINEL) ? 1U : 0U);

    /* Now clear bit 16 and read the same address again.  */

    zx_hprenr_disable(ZX_REGION_HIGH_PROBE);
    enr_after = zx_hprenr_read();
    zx_note("HPRENR with bit 16 cleared    ", enr_after);

    zx_check("clearing bit 16 of HPRENR changed the register, so the bit is\n"
             "         at least WRITABLE above 15",
             (enr_after != enr_before) ? 1U : 0U);

    outcome = zx_run_phase("read the same granule, region 16 DISABLED",
                           zx_payload_probe_read, probe_address);

    if ((outcome == ZX_RUN_YIELDED)
        && ((zx_payload_result & ZX_PAYLOAD_PROBE_OK) != 0U))
    {
        zx_console_puts(
            "\n  *** THE READ SUCCEEDED WITH THE REGION DISABLED.\n"
            "  *** HPRENR accepted a bit above 15 and IGNORED it.  That is\n"
            "  *** the worst of the three possible answers: a read-back test\n"
            "  *** would have passed, and a partition switch implemented as a\n"
            "  *** single HPRENR write would silently leave the outgoing\n"
            "  *** partition's regions live.  docs/decisions.md D4 must not\n"
            "  *** take the one-write option on this target.\n");
        zx_check("HPRENR bit 16 actually disables region 16", 0U);
    }
    else
    {
        zx_check("HPRENR bit 16 actually DISABLES region 16, so HPRENR is\n"
                 "         wider than 16 bits on this target and TRM 3.3.46's\n"
                 "         prose is stale where its bit tables are right",
                 (outcome == ZX_RUN_FAULTED) ? 1U : 0U);
        zx_fault_report(zx_el2_fault_record());
    }

    /* Put it back, so that later phases start from a known region set.  */

    zx_hprenr_enable(ZX_REGION_HIGH_PROBE);
    zx_note("HPRENR restored               ", zx_hprenr_read());
}


/**************************************************************************/
/*  zx_phase_violation -- T5, and the point of the whole image.            */
/*                                                                        */
/*  ZX_PROBE_NEGATIVE_TEST aims the same write at an address the payload   */
/*  IS granted.  The payload then survives, reports SURVIVED, and this     */
/*  image reports FAILED -- which is how the regression is proved able to  */
/*  fail.  A regression that has never been seen to fail is not evidence,  */
/*  and it is kept as a build option rather than as a temporary edit so    */
/*  that the demonstration stays reproducible.                            */
/**************************************************************************/

static void zx_phase_violation(void)
{
#ifdef ZX_PROBE_NEGATIVE_TEST

    /* zx_payload_scratch, not __zx_payload_data_start.  The first word of the
       payload's data region IS zx_payload_result, so aiming the write there
       overwrote the progress bits with the sentinel and the run then reported
       that the payload had never attempted the access -- a true statement
       about a word that had been scribbled on, and a misleading one about
       what happened.  Aiming at the scratch word instead leaves the progress
       bits alone, and nothing later in the run reads scratch.  */

    zx_addr_t target       = (zx_addr_t)(uintptr_t)&zx_payload_scratch;
    uint32_t  expect_fault = 0U;
#else
    zx_addr_t target       = zx_symbol_address(__zx_forbidden_start);
    uint32_t  expect_fault = 1U;
#endif
    uint32_t  outcome;
    const zx_fault_record_t *record;

    zx_console_puts("\n=========================================================\n"
                    " THE DEMONSTRANDUM: a stage-2 violation, taken to EL2\n"
                    "=========================================================\n");

#ifdef ZX_PROBE_NEGATIVE_TEST
    zx_console_puts(
        "  NEGATIVE TEST BUILD.  The write below is aimed at an address the\n"
        "  payload IS granted, so it must SUCCEED and this run must report\n"
        "  FAILED.  That is the point: it proves the check can fail.\n"
        "\n"
        "  Expected here: ATTEMPTED set, SURVIVED set, two failing checks,\n"
        "  no stage-2 fault from this phase, and ZONEX RESULT: FAILED.  The\n"
        "  CTest entry for this build expects FAILED, so this build\n"
        "  starting to PASS -- meaning the violation stopped being detected\n"
        "  -- fails the suite.\n");
#endif

    zx_console_puts("  target address ");
    zx_console_puthex(target);
    zx_console_puts("\n");

    outcome = zx_run_phase("write to the ungranted granule", zx_payload_violation,
                           target);
    record  = zx_el2_fault_record();

    zx_check("the payload got as far as attempting the access",
             ((zx_payload_result & ZX_PAYLOAD_ATTEMPTED) != 0U) ? 1U : 0U);

    if ((zx_payload_result & ZX_PAYLOAD_SURVIVED) != 0U)
    {
        zx_console_puts(
            "\n  *** THE PAYLOAD SURVIVED ITS VIOLATION.  It wrote to memory\n"
            "  *** stage 2 was meant to deny it and carried on.  IT IS NOT\n"
            "  *** PROTECTED.\n");
    }

    zx_check("the payload did NOT survive the access",
             ((zx_payload_result & ZX_PAYLOAD_SURVIVED) == 0U) ? 1U : 0U);

    if (expect_fault != 0U)
    {
        zx_check("a stage-2 fault was taken and captured",
                 (outcome == ZX_RUN_FAULTED) ? 1U : 0U);
    }

    if (outcome != ZX_RUN_FAULTED)
    {
        return;
    }

    zx_fault_report(record);

    zx_check("the fault is classified as a GUEST violation, not a hypervisor\n"
             "         one -- EC 0x24 and not EC 0x25",
             (zx_fault_classify(record->zx_fault_hsr)
              == ZX_FAULT_GUEST_VIOLATION) ? 1U : 0U);
    zx_check("HSR.EC is 0x24, a data abort ROUTED to Hyp",
             (zx_fault_ec(record->zx_fault_hsr) == ZX_EC_DABT_ROUTED)
                 ? 1U : 0U);
    zx_check("the syndrome says the access was a WRITE, which it was",
             (zx_fault_dabt_is_write(record->zx_fault_hsr) != 0U) ? 1U : 0U);
    zx_check("the vector taken and HSR.EC agree with each other",
             zx_fault_vector_agrees(record->zx_fault_vector,
                                    record->zx_fault_hsr));
    zx_check("HDFAR is EXACTLY the address the payload touched, which is what\n"
             "         catches a region whose limit is one granule out",
             (record->zx_fault_hdfar == target) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  The HPFAR measurement.  This is the register whose relationship  */
    /*  to the faulting address the TRM describes two different ways.    */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- open question: what does HPFAR hold? ---\n"
        "  The TRM describes HPFAR TWO WAYS: Figure 3-32 draws FIPA[39:12] at\n"
        "  HPFAR[31:4], while Table 3-69's row beside it says \"Bits [31:4] of\n"
        "  the faulting address\".  Those are different by a factor of 256.\n"
        "  Both are computed below and compared against an address this image\n"
        "  chose itself, so the answer is measured rather than picked.\n");
    zx_note("HPFAR raw                    ", record->zx_fault_hpfar);
    zx_note("HDFAR (the address touched)  ", record->zx_fault_hdfar);
    zx_note("as FIPA[39:12] at [31:4]     ",
            zx_fault_hpfar_page(record->zx_fault_hpfar));
    zx_note("HDFAR, 4 KB aligned          ",
            record->zx_fault_hdfar & ~(uint32_t)(ZX_HPFAR_PAGE_SIZE - 1U));
    zx_note("as the address itself        ",
            zx_fault_hpfar_as_address(record->zx_fault_hpfar));
    zx_note("HDFAR, low 4 bits cleared    ",
            record->zx_fault_hdfar & 0xFFFFFFF0U);
    zx_note("FIPA[39:32] from HPFAR[31:24]",
            zx_fault_hpfar_high(record->zx_fault_hpfar));

    {
        zx_hpfar_reading_t reading =
            zx_fault_hpfar_reading(record->zx_fault_hpfar,
                                   record->zx_fault_hdfar);

        zx_console_puts("\n  ON THIS TARGET, HPFAR holds:\n    ");
        zx_console_puts(zx_fault_hpfar_reading_name(reading));
        zx_console_puts("\n");

        zx_check("HPFAR matches HDFAR under one of the TWO documented\n"
                 "         readings, and this run says which",
                 ((reading == ZX_HPFAR_AS_FIPA)
                  || (reading == ZX_HPFAR_AS_ADDRESS)) ? 1U : 0U);

        if (reading == ZX_HPFAR_AS_FIPA)
        {
            zx_console_puts(
                "\n  NOTE: under this reading HPFAR resolves to 4 KB, not to the\n"
                "  64-byte MPU granule, so HPFAR ALONE CANNOT SAY WHICH GRANULE\n"
                "  FAULTED.\n");
        }
        else if (reading == ZX_HPFAR_AS_ADDRESS)
        {
            zx_console_puts(
                "\n  NOTE: under this reading HPFAR resolves to 16 bytes, which is\n"
                "  finer than the 64-byte MPU granule -- but it is NOT the reading\n"
                "  the Armv8-R AEM FVP implements.\n");
        }
        else
        {
            /* Ambiguous or unrecognised; the name above already said so and
               inventing a NOTE for it would be inventing a conclusion.  */
        }

        zx_console_puts(
            "\n  EITHER WAY: THE TWO ZONEX TARGETS DISAGREE ABOUT HPFAR, measured\n"
            "  on 2 September 2026.  There is therefore NO PORTABLE DECODE of it\n"
            "  on this architecture, and ZoneX uses HDFAR -- which carries the\n"
            "  full faulting virtual address on both, and is also what catches a\n"
            "  region whose limit is one granule out.\n");
    }
}


/**************************************************************************/
/*  zx_phase_provoke_el2_fault                                            */
/*                                                                        */
/*  Deliberately makes ZONEX ITSELF fault, to prove the EC 0x25 path       */
/*  exists and reports differently from a guest violation.  Region 16 is   */
/*  reprogrammed read-only AT EL2 -- AP 0b10 -- and then written from EL2. */
/*                                                                        */
/*  There is no way back from this: a fault taken from Hyp mode leaves     */
/*  nothing safe to resume, so zx_el2_hypervisor_fault reports and stops.  */
/*  It is therefore the LAST thing the image does, it is behind a build    */
/*  option, and the build is deliberately not in CTest -- the run's        */
/*  expected outcome is a failure report, which is exactly what a suite    */
/*  that judges runs by their verdict must not be taught to accept.       */
/**************************************************************************/

#ifdef ZX_PROBE_PROVOKE_EL2_FAULT
static void zx_phase_provoke_el2_fault(void)
{
    volatile uint32_t *target = &zx_high_probe_word;

    zx_console_puts("\n=========================================================\n"
                    " PROVOKING A FAULT AT EL2, DELIBERATELY\n"
                    "\n"
                    " Region 16 is about to be reprogrammed read-only at EL2\n"
                    " (AP 0b10) and then WRITTEN from EL2.  The hypervisor\n"
                    " fault report that follows is EXPECTED, and the point is\n"
                    " that it is a DIFFERENT report from a guest violation:\n"
                    " a different vector, EC 0x25 rather than 0x24, and its\n"
                    " own exit code.  This run ends here and ends failing.\n"
                    "=========================================================\n");

    zx_high_probe_region.zx_region_ap = ZX_AP_EL2_RO_GUEST_NONE;
    zx_stage2_region_program_direct16(&zx_high_probe_region);

    *target = 0xDEADBEEFU;

    /* Not reached.  If it is, the region did not deny the write, which is
       itself worth reporting rather than passing over in silence.  */

    zx_console_puts("\n  *** THE WRITE SUCCEEDED.  A region marked read-only at\n"
                    "  *** EL2 did not deny an EL2 write, so AP 0b10 does not\n"
                    "  *** mean what TRM Table 3-82 says it means.\n");
    zx_failures++;
}
#endif


/**************************************************************************/
/*  zx_el2_main -- entered from zx_el2_entry.S at EL2.  Does not return.  */
/**************************************************************************/

ZX_NORETURN void zx_el2_main(void)
{
    uint32_t board_regions;
    uint32_t regions_required;
    uint32_t el2_regions;

    /* ---------------------------------------------------------------- */
    /*  BEFORE THE FIRST PRINT.                                        */
    /*                                                                  */
    /*  On a board whose console sits below 0x60000000 the background   */
    /*  map reaches it as NORMAL memory, and Normal memory permits the  */
    /*  gathering and reordering that corrupts a polled UART -- with    */
    /*  caches off, and regardless of HSCTLR.BR, because BR grants      */
    /*  permission and not attributes.  Measured on the S32Z280: the    */
    /*  whole identity block printed as legible-but-wrong text, looking */
    /*  exactly like a marginal baud rate.                             */
    /*                                                                  */
    /*  So the hypervisor's own MMIO regions and the EL2 MPU come up    */
    /*  FIRST, before anything is printed.  The order is the same on    */
    /*  both targets even though only one of them needs it, because a   */
    /*  program that took a different path on the model would be        */
    /*  proving something about a path silicon does not run.           */
    /*                                                                  */
    /*  The region count is read before any region is written, since    */
    /*  writing HPRSELR with a value at or above the implemented count  */
    /*  is UNPREDICTABLE.                                              */
    /* ---------------------------------------------------------------- */

    el2_regions      = zx_el2_region_count();
    board_regions    = zx_board_mmio_region_count();
    regions_required = ZX_REGION_BOARD_FIRST + board_regions;

#ifdef ZX_PROBE_STARVE_REGIONS

    /* Claim to need more regions than any Armv8-R implementation can have, to
       exercise the REFUSAL path.  Same discipline as ZX_PROBE_NEGATIVE_TEST:
       "the image refuses rather than hanging when the region budget is too
       small" is a claim, and a claim about a branch nobody has taken is not
       evidence.  Refusing is the difference between a clear message and a
       region programmed at an index the implementation does not have, which
       is UNPREDICTABLE and presents as a hang.  */

    regions_required += 64U;
#endif

    if (el2_regions >= board_regions)
    {
        zx_mair_program();

        if (board_regions > 0U)
        {
            zx_board_program_mmio_regions(ZX_REGION_BOARD_FIRST);
        }

        zx_el2_mpu_enable();
    }

    zx_board_init();

    zx_console_puts(
        "\n"
        "=========================================================\n"
        " Eclipse ThreadX ZoneX -- stage-2 first light\n"
        " " ZX_PLATFORM_NAME "\n"
        " Armv8-R AArch32, EL2, PMSAv8-R at both stages\n"
        "=========================================================\n"
        "\n"
        " ZoneX is resident at EL2.  It programs stage-2 MPU regions,\n"
        " drops to EL1, and reports what the EL1 payload can and\n"
        " cannot reach.  There is no ThreadX here, no partition\n"
        " manifest and no scheduler: those arrive later, and each\n"
        " assumes what this image is here to establish.\n");

    zx_fault_record_reset(zx_el2_fault_record());

    zx_console_puts(
        "\n--- the EL2 MPU is already on ---\n"
        "  HSCTLR.BR and HSCTLR.M were set BEFORE this console was used,\n"
        "  together with any Device-attributed region the hypervisor's own\n"
        "  MMIO needs.  On a board whose console sits below 0x60000000 the\n"
        "  background map reaches it as NORMAL memory, and Normal memory\n"
        "  reorders and gathers -- which corrupts a polled UART even with\n"
        "  caches off.  This text arriving intact is itself the evidence.\n");
    zx_note("HSCTLR now", zx_read_hsctlr());
    zx_check("HSCTLR.M is set, so the EL2 MPU is live",
             ((zx_read_hsctlr() & ZX_HSCTLR_M) != 0U) ? 1U : 0U);
    zx_check("HSCTLR.BR is set, so EL2's own code and data fall back to the\n"
             "         background map and cost no region",
             ((zx_read_hsctlr() & ZX_HSCTLR_BR) != 0U) ? 1U : 0U);

#ifdef ZX_PROBE_STARVE_REGIONS
    zx_console_puts(
        "\n  REGION-STARVATION BUILD.  This image has been told it needs more\n"
        "  EL2 regions than any Armv8-R implementation can have, so it must\n"
        "  REFUSE to enable stage 2 and report FAILED.  That is the point: it\n"
        "  proves the refusal happens rather than a region being programmed at\n"
        "  an index that does not exist -- which is UNPREDICTABLE and presents\n"
        "  as a hang.\n");
#endif

    if (zx_identity_block(regions_required) == 0U)
    {
        zx_console_puts("\nZONEX RESULT: FAILED -- the target cannot host "
                        "stage 2 as this image needs it\n");
        zx_console_exit(1U);
    }

    /* VBAR before the first ERET: the payload's own EL1 vector table lives
       inside the payload's code region, so an exception taken AT EL1 rather
       than routed to EL2 lands somewhere that can identify itself.  */

    zx_console_puts("\n--- the payload's own EL1 vectors ---\n");
    zx_note("VBAR installed at", zx_symbol_address(zx_payload_vectors));
    zx_console_puts("  they live inside the payload's CODE region, so an\n"
                    "  exception taken at EL1 rather than routed to EL2 lands\n"
                    "  somewhere reachable that can identify itself\n");
    {
        uint32_t vbar = (uint32_t)zx_symbol_address(zx_payload_vectors);

        __asm__ volatile("mcr p15, 0, %0, c12, c0, 0" : : "r"(vbar) : "memory");
        __asm__ volatile("isb");
    }

    zx_program_regions(board_regions);

    zx_console_puts("\n--- enabling stage 2 for EL0/EL1 ---\n"
                    "  the EL2 MPU has been on since before the console;\n"
                    "  what is left is HCR.VM.  Order: DSB, HCR.VM, ISB.\n");
    zx_stage2_enable();
    zx_note("HSCTLR now", zx_read_hsctlr());
    zx_note("HCR now   ", zx_read_hcr());
    zx_check("HCR.VM is set, so stage 2 applies to EL0/EL1",
             ((zx_read_hcr() & ZX_HCR_VM) != 0U) ? 1U : 0U);
    zx_check("HCR.HCD is clear, so HVC is still available to a guest",
             ((zx_read_hcr() & ZX_HCR_HCD) == 0U) ? 1U : 0U);
    zx_check("HCR.TGE is clear, so a guest keeps its own exception vectors",
             ((zx_read_hcr() & ZX_HCR_TGE) == 0U) ? 1U : 0U);

    zx_phase_grant();
    zx_phase_hypercall();
    zx_phase_hprenr(el2_regions);
    zx_phase_violation();

#ifdef ZX_PROBE_PROVOKE_EL2_FAULT
    zx_phase_provoke_el2_fault();
#endif

    /* ---------------------------------------------------------------- */
    /*  Verdict.  The exact strings are what the runners grep for.      */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n=========================================================\n"
                    " what this run does and does not prove\n"
                    "=========================================================\n"
                    " " ZX_PLATFORM_NAME "\n"
                    " EL2 regions available: ");
    zx_console_putdec(el2_regions);
    zx_console_puts(", needed by this image: ");
    zx_console_putdec(regions_required);
    zx_console_puts("\n"
        "\n"
        " A green run here proves the CODE is right.  It proves nothing\n"
        " about the region budget or the MMIO attributes on a different\n"
        " part: the Armv8-R AEM FVP reports a region count no Cortex-R52\n"
        " can have, and its console and GIC land in the Device band of\n"
        " the background map where the S32Z280's do not.  Both targets\n"
        " have to be run.\n"
        "\n"
        " On lockstep silicon this demonstrates memory isolation on ONE\n"
        " logical core.  It does NOT demonstrate spatial multicore\n"
        " partitioning.\n");

    zx_console_puts("\n  checks failed: ");
    zx_console_putdec(zx_failures);
    zx_console_puts("\n");

    if (zx_failures == 0U)
    {
        zx_console_puts("\nZONEX RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
    }

    zx_console_exit(zx_failures);
}
