/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_report.c                                            SHARED       */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    How every ZoneX image reports a check, a value and its verdict.      */
/*                                                                        */
/*  WHY THIS IS ONE FILE AND NOT ONE PER IMAGE                            */
/*                                                                        */
/*    Because the automated runner greps for this text.  It judges a run   */
/*    on the verdict line and lists the lines beginning "  [FAIL]", so     */
/*    the FORMAT is an interface between the images and the suite -- and   */
/*    two images with their own copies of it would be two images free to   */
/*    drift apart, one of them silently stopping being judged.            */
/*                                                                        */
/*    The failure count lives here for the same reason.  It is the number  */
/*    the verdict is computed from, and a second image with a second       */
/*    counter would be an image whose verdict could disagree with its own  */
/*    reported failures.                                                   */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Rule 11.4/11.6 -- casting a linker symbol's address to an integer    */
/*      address is inherent to describing memory to an MPU.  Confined to   */
/*      zx_symbol_address below.                                          */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"

/* How many checks failed.  Accumulated rather than returned, because an
   image reports EVERY check and then its verdict: stopping at the first
   failure would hide the identity block that explains it.  */

static uint32_t zx_failures;


/**************************************************************************/
/*  zx_symbol_address -- a linker symbol's address as an MPU address.      */
/**************************************************************************/

zx_addr_t zx_symbol_address(const char *symbol)
{
    return (zx_addr_t)(uintptr_t)symbol;
}


/**************************************************************************/
/*  zx_report / zx_check -- one labelled line each.                       */
/*                                                                        */
/*  Fixed-width labels so that a captured log lines up and a missing       */
/*  result is visible as a gap rather than having to be counted.          */
/**************************************************************************/

void zx_check(const char *label, uint32_t passed)
{
    zx_console_puts("  [");
    zx_console_puts((passed != 0U) ? "PASS" : "FAIL");
    zx_console_puts("] ");
    zx_console_puts(label);
    zx_console_puts("\n");

    if (passed == 0U)
    {
        zx_failures++;
    }
}


uint32_t zx_probe_failures(void)
{
    return zx_failures;
}


void zx_probe_fail(void)
{
    zx_failures++;
}


void zx_note(const char *label, uint32_t value)
{
    zx_console_puts("  ");
    zx_console_puts(label);
    zx_console_puts(" = ");
    zx_console_puthex(value);
    zx_console_puts("\n");
}
