/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  EXAMPLE                                                DESCRIPTION    */
/*                                                                        */
/*    zx_two_partitions.c                                     SHARED      */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    TWO ThreadX partitions time-sharing one logical core under a static */
/*    major frame, each with its own stage-2 region set, its own frozen   */
/*    virtual time, and a bounded, measured switch between them.          */
/*                                                                        */
/*    This is the image that makes ZoneX a hypervisor rather than a       */
/*    loader.  Everything under it was already demonstrated with ONE      */
/*    partition: a real kernel confined by stage 2, granted an interrupt  */
/*    it could not have granted itself, with a clock the hypervisor       */
/*    freezes while it is not running.  What one partition cannot show is */
/*    the thing that matters -- that a window ENDS whether the partition  */
/*    agrees or not, and that the next one resumes exactly where it was.  */
/*                                                                        */
/*  THE FOUR CLAIMS                                                       */
/*                                                                        */
/*    1.  TWO PARTITIONS RUN FROM ONE MANIFEST, each in its own window,   */
/*        each running its own kernel, neither able to reach the other's  */
/*        memory or the ungranted granule between them.                   */
/*                                                                        */
/*    2.  A WINDOW ENDS WHETHER THE PARTITION AGREES OR NOT.  The         */
/*        hypervisor's own timer is in GIC Group 0, so it arrives as an   */
/*        FIQ at EL2 -- and with HCR.FMO set, PSTATE.F is IGNORED at EL0  */
/*        and EL1.  A partition cannot mask the interrupt that ends its   */
/*        own window.  The hogging build proves it by trying.             */
/*                                                                        */
/*    3.  EACH PARTITION'S CLOCK ADVANCES BY ITS OWN WINDOWS AND BY       */
/*        NOTHING ELSE.  Measured from both sides, which is the only way  */
/*        it means anything: the hypervisor knows how much of the         */
/*        physical counter each partition was given, and only the guest   */
/*        can say what its own counter did over the same span.  A guest   */
/*        that saw wall-clock time would be a system that runs perfectly  */
/*        and lies about time -- invisible to every other check here.     */
/*                                                                        */
/*    4.  THE SWITCH IS BOUNDED AND MEASURED, by group, with its jitter   */
/*        reported as a MAXIMUM and not only as a mean.  A safety         */
/*        audience reads the maximum, because that is what a schedule has */
/*        to be built to survive.                                         */
/*                                                                        */
/*  THE ASYMMETRY IS DELIBERATE                                           */
/*                                                                        */
/*    Partition A is the critical one: the larger window, and a guest     */
/*    that keeps working after its verdict so that there is always        */
/*    something to preempt.  Partition B is the untrusted one: the        */
/*    smaller window, chattier, and in one build actively hostile.  The   */
/*    windows differ so that "a partition given a third of the frame sees */
/*    a third of the ticks" is a claim with two different numbers in it   */
/*    rather than a symmetry that would hold by accident.                 */
/*                                                                        */
/*  WHAT A PASS DOES NOT MEAN                                             */
/*                                                                        */
/*    On the Armv8-R AEM FVP a pass proves the code is right and says     */
/*    NOTHING about timing: the model is functional, not cycle-accurate.  */
/*    Every cycle count this image prints has to come from silicon before */
/*    it is quoted, and the image says so in its own output.              */
/*                                                                        */
/*    On lockstep silicon the two partitions TIME-SHARE ONE LOGICAL CORE. */
/*    What this earns is memory isolation plus temporal determinism on    */
/*    that core.  It is not spatial multicore partitioning and must never */
/*    be shown as if it were.                                             */
/*                                                                        */
/**************************************************************************/

#include "zx_probe.h"
#include "zx_platform.h"
#include "zx_guest_abi.h"
#include "zx_guest_launch.h"
#include "zx_manifest.h"
#include "zx_mm.h"
#include "zx_partition.h"
#include "zx_schedule.h"
#include "zx_guest_console.h"

/* THE GUEST'S CONTRACT AND THE HYPERVISOR'S MUST AGREE, and this is one of
   the few translation units that can see both spellings.  The guest is a
   separate program with its own toolchain invocation and cannot include
   zx_port.h; it restates what it needs in zx_guest_abi.h.  Asserting the two
   against each other here turns a renumbered constant into a failed BUILD
   rather than a partition that takes an interrupt it does not recognise.  */

_Static_assert(ZX_HVC_GUEST_NOP == (int)ZX_HVC_NOP,
               "the guest and the hypervisor disagree about HVC #0");
_Static_assert(ZX_HVC_GUEST_YIELD == (int)ZX_HVC_YIELD,
               "the guest and the hypervisor disagree about the yield HVC");
_Static_assert(ZX_HVC_GUEST_PUTC == (int)ZX_HVC_PUTC,
               "the guest and the hypervisor disagree about the console HVC");
_Static_assert(ZX_GUEST_TIMER_INTID == (int)ZX_PPI_VIRTUAL_TIMER,
               "the guest acknowledges a different INTID from the one ZoneX "
               "enables for it");
_Static_assert(ZX_GUEST_SPURIOUS_INTID == (int)ZX_INTID_SPURIOUS,
               "the guest and the hypervisor disagree about the spurious "
               "INTID, which must never be given an end-of-interrupt");

/* The two windows and the two embedded guests, from the linker script.  */

extern char __zx_guest_a_blob_start[];
extern char __zx_guest_a_blob_end[];
extern char __zx_guest_b_blob_start[];
extern char __zx_guest_b_blob_end[];
extern char __zx_partition_a_start[];
extern char __zx_partition_a_end[];
extern char __zx_partition_a_hole_start[];
extern char __zx_partition_b_start[];
extern char __zx_partition_b_end[];
extern char __zx_partition_b_hole_start[];

#define ZX_PART_A               0U
#define ZX_PART_B               1U
#define ZX_PART_COUNT           2U

#define ZX_PARTITION_A_ID       1U
#define ZX_PARTITION_B_ID       2U

/* The sentinels the hypervisor plants, and which each guest folds into every
   checksum.  DISTINCT, because that is what makes a report attributable: a
   value read out of the wrong partition's window looks exactly like a
   report, and only the sentinel inside the sum says whose it is.  With two
   partitions that stops being a precaution and becomes the point.  */

#define ZX_GUEST_A_SENTINEL     0xA5A50011U
#define ZX_GUEST_B_SENTINEL     0xA5A50022U

/* THE MAJOR FRAME, in scheduling ticks.
 *
 * A tick is a hundredth of a second, which is ThreadX's own default rate, so
 * a partition's window is a whole number of the ticks its kernel counts.
 * That is what makes the tick-budget claim legible: a partition given seven
 * of the ten ticks in a frame should see about seven tenths of the ticks a
 * standalone kernel would, and both numbers are integers a reader can check.
 *
 * SEVEN AND THREE RATHER THAN FIVE AND FIVE.  Equal windows would make every
 * ratio in the run come out as one half, and a great many arithmetic
 * mistakes also come out as one half.  Unequal windows mean the two
 * partitions' numbers cannot be swapped without the run noticing.  */

#define ZX_TICK_HZ              100U
#define ZX_WINDOW_A_TICKS       7UL
#define ZX_WINDOW_B_TICKS       3UL
#define ZX_FRAME_TICKS          (ZX_WINDOW_A_TICKS + ZX_WINDOW_B_TICKS)

/* How many major frames the run lasts.
 *
 * BOUNDED, because a regression has to be able to assert on a total, and
 * "the harness timed out" is not a result.
 *
 * TWENTY, AND THE NUMBER IS SET BY THE CHATTY PARTITION ON THE SLOWER
 * CONSOLE -- which is one of the more instructive things this demonstration
 * shows, so it is written down rather than tuned away.
 *
 * Partition B prints, and a guest's console is one hypercall PER CHARACTER
 * through whatever console the board has.  On the Armv8-R AEM FVP that is
 * semihosting and costs no simulated time at all; on the S32Z280 it is a
 * polled UART and costs about 1,500 counter counts a character -- measured,
 * 952 characters in the 1,453,400 counts B was given by a six-frame run.
 * B's whole programme is roughly 1,430 characters, so on silicon it spends
 * the better part of THREE FRAMES' worth of its own window simply talking.
 *
 * That is not an artefact to be hidden.  IT IS WHAT TIME PARTITIONING DOES:
 * a partition that spends its window printing gets its window's worth of
 * printing and no more, and its neighbour is completely unaffected -- which
 * is visible here as partition A finishing its programme in four ticks
 * while B is still mid-sentence.  What it costs is that a run has to be
 * long enough for the slow partition to reach its verdict, or the
 * demonstration ends before its own evidence does.
 *
 * Twenty frames is two hundred ticks: two seconds of wall clock on silicon,
 * giving B sixty ticks of its own time against the roughly thirty-four it
 * needs.  The margin is deliberate -- a run that only just finishes would
 * start failing the first time somebody added a line of guest output.  */

#define ZX_FRAME_LIMIT          20UL

/* The priority a partition's timer is given.  The same value the
   single-partition image uses, and the hypervisor's own tick sits well above
   it -- see zx_frame_hyp_tick_priority.  */

#define ZX_GUEST_TIMER_PRIORITY 0xA0U

/* How many rounds the switch measurement averages over.  Eight, matching the
   method the region-set switch was first measured with: enough to average
   out a single anomaly, few enough that the whole measurement is a fraction
   of one window.  */

#define ZX_MEASURE_ROUNDS       8U

static ZX_REGION        zx_regions_a[1];
static ZX_REGION        zx_regions_b[1];
static ZX_PARTITION     zx_partitions[ZX_PART_COUNT];
static ZX_MANIFEST      zx_manifest;
static ZX_MM_LAYOUT     zx_layout;
static ZX_MANIFEST_ENV  zx_env;
static ZX_PARTITION_CB  zx_partition_cb[ZX_PART_COUNT];
static ZX_REGION        zx_mmio[ZX_BOARD_MAX_MMIO_REGIONS];
static ZX_GIC_LAYOUT    zx_gic;
static ZX_GUEST_LAUNCH  zx_launch[ZX_PART_COUNT];
static ZX_SCHEDULE      zx_schedule;
static ZX_FRAME         zx_frame;

/* ONE CONTEXT BLOCK PER PARTITION, STATICALLY ALLOCATED.  No allocation and
   no list: a partition switch indexes an array, which is what makes its cost
   independent of how many partitions exist and of which one is next.  */

static ZX_GUEST_CONTEXT zx_context[ZX_PART_COUNT];

/* And two more for the measurement, which must not be the running ones.
   Timing a save into a partition's own block would overwrite the state that
   partition is about to be resumed with -- the measurement destroying its
   subject, which is a class of mistake this suite has already paid for
   once.  */

static ZX_GUEST_CONTEXT zx_scratch[2];
static ZX_SWITCH_COST   zx_cost;


/**************************************************************************/
/*  zx_describe_launches                                                  */
/*                                                                        */
/*  Filled at run time rather than as static initialisers, because every  */
/*  field is the address of a LINKER symbol and the address of a linker   */
/*  symbol is not a constant expression.                                  */
/*                                                                        */
/*  zx_launch_freeze_time is set for BOTH partitions in every build.  The */
/*  single-partition image has a build that turns it off, to show the     */
/*  freeze failing; here the equivalent negative build breaks the         */
/*  SCHEDULE instead, because with two partitions the interesting failure */
/*  is not "a clock advanced" but "a clock advanced by its neighbour's    */
/*  window".                                                              */
/**************************************************************************/

static void zx_describe_launches(void)
{
    zx_launch[ZX_PART_A].zx_launch_window_base   =
        zx_symbol_address(__zx_partition_a_start);
    zx_launch[ZX_PART_A].zx_launch_window_end    =
        zx_symbol_address(__zx_partition_a_end);
    zx_launch[ZX_PART_A].zx_launch_image_start   =
        zx_symbol_address(__zx_guest_a_blob_start);
    zx_launch[ZX_PART_A].zx_launch_image_end     =
        zx_symbol_address(__zx_guest_a_blob_end);
    zx_launch[ZX_PART_A].zx_launch_sentinel      = ZX_GUEST_A_SENTINEL;
    zx_launch[ZX_PART_A].zx_launch_partition_id  = ZX_PARTITION_A_ID;
    zx_launch[ZX_PART_A].zx_launch_partition_name =
        zx_partitions[ZX_PART_A].zx_partition_name;
    zx_launch[ZX_PART_A].zx_launch_freeze_time   = 1U;

    zx_launch[ZX_PART_B].zx_launch_window_base   =
        zx_symbol_address(__zx_partition_b_start);
    zx_launch[ZX_PART_B].zx_launch_window_end    =
        zx_symbol_address(__zx_partition_b_end);
    zx_launch[ZX_PART_B].zx_launch_image_start   =
        zx_symbol_address(__zx_guest_b_blob_start);
    zx_launch[ZX_PART_B].zx_launch_image_end     =
        zx_symbol_address(__zx_guest_b_blob_end);
    zx_launch[ZX_PART_B].zx_launch_sentinel      = ZX_GUEST_B_SENTINEL;
    zx_launch[ZX_PART_B].zx_launch_partition_id  = ZX_PARTITION_B_ID;
    zx_launch[ZX_PART_B].zx_launch_partition_name =
        zx_partitions[ZX_PART_B].zx_partition_name;
    zx_launch[ZX_PART_B].zx_launch_freeze_time   = 1U;
}


/**************************************************************************/
/*  zx_build_manifest                                                     */
/*                                                                        */
/*  TWO PARTITIONS, ONE REGION EACH, AND NO DEVICE OF ANY KIND.           */
/*                                                                        */
/*  A second partition costs exactly one more window and one more region. */
/*  It costs no GIC mapping, no timer mapping and no shared page: a       */
/*  partition's whole interrupt capability is system-register state, and  */
/*  its whole clock is a register only EL2 can write.  That is the        */
/*  strongest form this claim could take, and it is worth restating with  */
/*  two partitions because the obvious design -- give each guest its own  */
/*  view of the interrupt controller -- would have cost regions AND       */
/*  handed each partition the enable bit for the interrupt that ends its  */
/*  own window.                                                           */
/*                                                                        */
/*  NO SHARED GRANULE EITHER, and that is a decision rather than an       */
/*  omission.  The manifest can declare one -- the stage-2 probe image    */
/*  demonstrates both halves of it -- and this image deliberately does    */
/*  not, so that the two partitions are disjoint with no exceptions at    */
/*  all.  Every temporal number below is then a number about two          */
/*  partitions that share nothing but a core.                             */
/**************************************************************************/

static void zx_build_manifest(uint32_t board_regions)
{
    zx_regions_a[0].zx_region_base  =
        zx_symbol_address(__zx_partition_a_start);
    zx_regions_a[0].zx_region_limit =
        zx_symbol_address(__zx_partition_a_end) - 1U;
    zx_regions_a[0].zx_region_ap    = ZX_AP_EL2_RW_GUEST_RW;
    zx_regions_a[0].zx_region_xn    = ZX_XN_EXECUTABLE;
    zx_regions_a[0].zx_region_sh    = ZX_SH_NON_SHAREABLE;
    zx_regions_a[0].zx_region_attr_index = (UCHAR)ZX_ATTR_NORMAL_WB;

    zx_regions_b[0].zx_region_base  =
        zx_symbol_address(__zx_partition_b_start);
    zx_regions_b[0].zx_region_limit =
        zx_symbol_address(__zx_partition_b_end) - 1U;
    zx_regions_b[0].zx_region_ap    = ZX_AP_EL2_RW_GUEST_RW;
    zx_regions_b[0].zx_region_xn    = ZX_XN_EXECUTABLE;
    zx_regions_b[0].zx_region_sh    = ZX_SH_NON_SHAREABLE;
    zx_regions_b[0].zx_region_attr_index = (UCHAR)ZX_ATTR_NORMAL_WB;

#ifdef ZX_TWO_OVERLAP

    /* THE NEGATIVE BUILD FOR ISOLATION: partition B's window is widened to
       swallow the ungranted granule and reach into partition A's.  Two
       enabled regions on one address is CONSTRAINED UNPREDICTABLE and
       aborts on the S32Z280, so the validator must refuse this BY NAME
       before a single region is programmed.  */

    zx_regions_b[0].zx_region_base =
        zx_symbol_address(__zx_partition_a_start);

#endif

    zx_partitions[ZX_PART_A].zx_partition_id           = ZX_PARTITION_A_ID;
    zx_partitions[ZX_PART_A].zx_partition_name         = "A (critical)";
    zx_partitions[ZX_PART_A].zx_partition_image_start  =
        zx_symbol_address(__zx_guest_a_blob_start);
    zx_partitions[ZX_PART_A].zx_partition_image_end    =
        zx_symbol_address(__zx_guest_a_blob_end);
    zx_partitions[ZX_PART_A].zx_partition_entry        =
        zx_symbol_address(__zx_partition_a_start) + ZX_GUEST_IMAGE_OFF_ENTRY;
    zx_partitions[ZX_PART_A].zx_partition_regions      = zx_regions_a;
    zx_partitions[ZX_PART_A].zx_partition_region_count = 1U;
    zx_partitions[ZX_PART_A].zx_partition_window_ticks = ZX_WINDOW_A_TICKS;

    zx_partitions[ZX_PART_B].zx_partition_id           = ZX_PARTITION_B_ID;
    zx_partitions[ZX_PART_B].zx_partition_name         = "B (untrusted)";
    zx_partitions[ZX_PART_B].zx_partition_image_start  =
        zx_symbol_address(__zx_guest_b_blob_start);
    zx_partitions[ZX_PART_B].zx_partition_image_end    =
        zx_symbol_address(__zx_guest_b_blob_end);
    zx_partitions[ZX_PART_B].zx_partition_entry        =
        zx_symbol_address(__zx_partition_b_start) + ZX_GUEST_IMAGE_OFF_ENTRY;
    zx_partitions[ZX_PART_B].zx_partition_regions      = zx_regions_b;
    zx_partitions[ZX_PART_B].zx_partition_region_count = 1U;
    zx_partitions[ZX_PART_B].zx_partition_window_ticks = ZX_WINDOW_B_TICKS;

    zx_manifest.zx_manifest_partitions        = zx_partitions;
    zx_manifest.zx_manifest_partition_count   = ZX_PART_COUNT;
    zx_manifest.zx_manifest_shared            = (const ZX_SHARED *)0;
    zx_manifest.zx_manifest_shared_count      = 0U;
    zx_manifest.zx_manifest_major_frame_ticks = ZX_FRAME_TICKS;

    zx_board_describe_mmio_regions(zx_mmio);

    zx_env.zx_env_mmio_regions      = zx_mmio;
    zx_env.zx_env_mmio_region_count = board_regions;
    zx_env.zx_env_attr_written_mask = 0x07U;
}


/**************************************************************************/
/*  zx_grant_the_clocks                                                   */
/*                                                                        */
/*  EVERYTHING AT EL2 THAT MAKES A TIME-PARTITIONED SYSTEM POSSIBLE, in   */
/*  one place, because the order matters and several steps of it fail     */
/*  silently on their own.                                                */
/*                                                                        */
/*    THE COUNTER, then the GIC, then the two interrupts -- one for the   */
/*    partitions and one for the hypervisor -- and then the ROUTING.      */
/*                                                                        */
/*    THE PARTITIONS' TIMER IS ONE INTID FOR BOTH OF THEM.  They never    */
/*    run at once, and its meaning is switched with everything else a     */
/*    switch switches: the outgoing partition's comparator is saved and   */
/*    DISARMED, the incoming one's is restored.  Two INTIDs would make    */
/*    "which PPIs are enabled" guest state and grow the switch by a       */
/*    register write for no gain; one INTID keeps it hypervisor state     */
/*    that never changes.  This is open question 2 of the step this image */
/*    was written for, answered the way it recommended, and recorded here */
/*    rather than only in the manifest's comments.                        */
/*                                                                        */
/*    THE HYPERVISOR'S TIMER GOES IN GROUP 0, which is what makes the     */
/*    whole design work: routing is by exception TYPE, so Group 0 arrives */
/*    as an FIQ and HCR.FMO brings FIQ to EL2, while every partition      */
/*    interrupt stays Group 1, stays an IRQ, and is delivered straight to */
/*    EL1 exactly as it was before this image existed.                    */
/*                                                                        */
/*    AND EL2'S OWN CPU INTERFACE COMES UP LAST, AFTER FMO IS SET,        */
/*    because that is where the trap is.  See zx_gic_el2_cpu_interface_   */
/*    init: setting FMO redirects the guest's ICC_PMR writes to the       */
/*    VIRTUAL interface, so the physical priority mask -- which resets to */
/*    zero, masking everything -- becomes the hypervisor's to open.  A    */
/*    partition that was receiving its timer perfectly well stops         */
/*    receiving anything, with no fault and no message.                   */
/*                                                                        */
/*  Returns non-zero when everything both partitions depend on is up.     */
/**************************************************************************/

static uint32_t zx_grant_the_clocks(void)
{
    uint32_t running;
    uint32_t awake;
    uint32_t priority_bits;
    uint32_t hyp_priority;
    uint32_t tick_deliverable;

    zx_console_puts("\n--- the clocks and the interrupts ZoneX grants ---\n");

    zx_board_counter_start();
    running = zx_counter_is_running();

    zx_note("CNTFRQ         ", zx_read_cntfrq());
    zx_check("the system counter is RUNNING, not merely declared.  Every\n"
             "         window boundary in this run is an absolute comparison\n"
             "         against it, so a counter that does not move is a frame\n"
             "         that never turns",
             running);

    awake = zx_gic_el2_init(&zx_gic);
    zx_check("the redistributor cleared ProcessorSleep and reports its\n"
             "         children awake, so this core can be delivered to",
             awake);

    priority_bits = zx_gic_priority_bits(&zx_gic, ZX_PPI_VIRTUAL_TIMER);
    hyp_priority  = zx_frame_hyp_tick_priority();

    zx_note("implemented priority bits", priority_bits);
    zx_note("partition timer priority ", ZX_GUEST_TIMER_PRIORITY);
    zx_note("hypervisor tick priority ", hyp_priority);

    /* THE TWO PRIORITIES MUST STILL DIFFER AFTER THE PART HAS THROWN AWAY
       THE BITS IT DOES NOT IMPLEMENT.  Both targets keep only the top five,
       so two values differing below that are the SAME priority -- and equal
       priorities do not preempt.  A hypervisor tick that could not preempt
       a partition's timer handler would let a guest defer the end of its
       own window for as long as its handler ran, which is the masking hole
       wearing a different hat.  */

    {
        uint32_t keep = (uint32_t)(0xFFU << (8U - priority_bits));

        zx_check("the hypervisor's tick is a HIGHER priority than a\n"
                 "         partition's timer even after this part has\n"
                 "         discarded the priority bits it does not implement --\n"
                 "         numerically lower wins, and equal priorities do not\n"
                 "         preempt at all",
                 ((hyp_priority & keep) < (ZX_GUEST_TIMER_PRIORITY & keep))
                     ? 1U : 0U);
    }

    /* ONE INTID FOR BOTH PARTITIONS.  Enabled once, here, and never touched
       by a switch: the comparator behind it is what changes hands.  */

    zx_gic_enable_guest_ppi(&zx_gic, ZX_PPI_VIRTUAL_TIMER,
                            ZX_GUEST_TIMER_PRIORITY);

#ifndef ZX_TWO_NO_TICK

    zx_gic_enable_hyp_ppi(&zx_gic, ZX_PPI_HYPERVISOR_TIMER, hyp_priority);

#else

    zx_console_puts("\n  NEGATIVE BUILD: the HYPERVISOR's own timer PPI is\n"
                    "  deliberately NOT enabled.  The comparator is still\n"
                    "  armed at every boundary and still expires; the GIC is\n"
                    "  simply never told to deliver it.  No window can then\n"
                    "  end, partition A runs for ever, and partition B never\n"
                    "  runs at all -- so this run must report FAILED.\n");

#endif

    zx_check("the partitions' virtual-timer PPI reads back ENABLED and in\n"
             "         GROUP 1, which is what the GIC delivers as an IRQ,\n"
             "         straight to EL1 with no injection and no List Register",
             (zx_gic_ppi_is_enabled(&zx_gic, ZX_PPI_VIRTUAL_TIMER)
              && zx_gic_ppi_is_group1(&zx_gic, ZX_PPI_VIRTUAL_TIMER))
                 ? 1U : 0U);

    zx_check("and the HYPERVISOR's own timer PPI is in GROUP 0, which is\n"
             "         what the GIC delivers as an FIQ.  Routing is by\n"
             "         exception TYPE and not by INTID: that one bit is the\n"
             "         whole difference between a tick that reaches EL2 and a\n"
             "         tick that would have to be injected into a List\n"
             "         Register",
             (zx_gic_ppi_is_group1(&zx_gic, ZX_PPI_HYPERVISOR_TIMER) == 0U)
                 ? 1U : 0U);

    /* AND THAT IT IS ENABLED, which is the check the whole refusal below
       rests on.  A hypervisor whose own tick is not deliverable cannot end
       a window, and a frame started in that state does not fail -- it
       HANGS, with the first partition running until something outside the
       image stops it.  That is the least informative outcome this suite can
       produce and it names nothing at all.  */

    tick_deliverable = zx_gic_ppi_is_enabled(&zx_gic,
                                             ZX_PPI_HYPERVISOR_TIMER);
    zx_note("hypervisor tick PPI enabled", tick_deliverable);

    zx_check("and the PHYSICAL timer's PPI is enabled for nobody.  A\n"
             "         partition could not read it anyway -- CNTHCTL.PL1PCTEN\n"
             "         and PL1PCEN are left clear on purpose -- because\n"
             "         physical time keeps running while a partition is\n"
             "         descheduled, and a guest that can read it can see that\n"
             "         it was not running",
             (zx_gic_ppi_is_enabled(&zx_gic, ZX_PPI_PHYSICAL_TIMER) == 0U)
                 ? 1U : 0U);

    /* ROUTING, AND THEN EL2's OWN CPU INTERFACE.  In that order, because
       the second only matters once the first has changed where the guest's
       own writes go.  */

    zx_el2_route_fiq();

    zx_note("HCR after routing", zx_read_hcr());

    /* THE BIT, BY POSITION, AND NOT BY NAME.  This port had ZX_HCR_FMO and
       ZX_HCR_AMO defined the other way round, and a check written as
       "(HCR & ZX_HCR_FMO) != 0" passes cheerfully against either
       definition -- it is the same symbol on both sides of the comparison.
       What it cost was a run in which every set-up check was green, the
       comparator expired, the GIC made the interrupt pending, and no window
       ever ended: bit 5 is AMO, and physical FIQ had never been routed
       anywhere.  Bit 3 is FMO on this architecture and on this part, TRM
       Table 3-70, and comparing against the NUMBER is the only form of this
       check a swapped definition cannot satisfy.  */

    zx_check("HCR bit 3 -- FMO, by position and not by the name this port\n"
             "         happens to give it -- is SET, so a physical FIQ is\n"
             "         taken to EL2.  And with it set, PSTATE.F is IGNORED at\n"
             "         EL0 and EL1: a partition cannot mask the interrupt\n"
             "         that ends its own window, whatever its kernel does\n"
             "         with its own masks",
             ((zx_read_hcr() & 0x8U) != 0U) ? 1U : 0U);
    zx_check("and HCR bit 5 -- AMO -- is CLEAR.  Routing asynchronous aborts\n"
             "         to EL2 would send them to the vector that today means\n"
             "         'ZoneX faulted on its own access', so a guest's abort\n"
             "         would be reported as a hypervisor bug.  Not needed for\n"
             "         a window to end, and deliberately deferred",
             ((zx_read_hcr() & 0x20U) == 0U) ? 1U : 0U);
    zx_check("and HCR bit 4 -- IMO -- is CLEAR, so every partition interrupt\n"
             "         is still a physical IRQ delivered straight to EL1.  The\n"
             "         guest side of this arrangement needed no change\n"
             "         whatever, which is the strongest argument the design\n"
             "         has",
             ((zx_read_hcr() & 0x10U) == 0U) ? 1U : 0U);

    zx_gic_el2_cpu_interface_init();

    zx_note("EL2 ICC_PMR    ", zx_gic_el2_priority_mask());
    zx_note("EL2 ICC_IGRPEN0", zx_gic_el2_group0_enabled());

    zx_check("the PHYSICAL priority mask is open, and it is the\n"
             "         HYPERVISOR'S to open now.  Setting HCR.FMO redirects an\n"
             "         EL1 write of ICC_PMR to the VIRTUAL interface, so the\n"
             "         guest's own 'unmask everything' stops affecting\n"
             "         physical delivery -- and the physical mask resets to\n"
             "         zero, which masks it all.  A partition that received\n"
             "         its timer end to end a moment ago would stop receiving\n"
             "         anything, with nothing to fault on",
             (zx_gic_el2_priority_mask() != 0U) ? 1U : 0U);

    zx_check("and Group 0 is enabled at EL2's own CPU interface, without\n"
             "         which an FIQ could not be signalled to the core at all",
             zx_gic_el2_group0_enabled());

    /* ---------------------------------------------------------------- */
    /*  A PRE-FLIGHT, BEFORE ANY PARTITION RUNS.                        */
    /*                                                                  */
    /*  A window that never ends has three possible causes in three     */
    /*  different places, and they present identically: a hypervisor    */
    /*  that starts a frame and is never heard from again, with no      */
    /*  fault, no message and a harness timeout that names nothing.     */
    /*  That is the least informative failure this suite can produce.   */
    /*                                                                  */
    /*  So the comparator is armed for a short interval HERE, with no   */
    /*  partition running and FIQ still masked at EL2, and two          */
    /*  questions are asked separately: did it expire, and did the GIC  */
    /*  make the interrupt pending.  A run that fails either of them    */
    /*  says which half is broken instead of hanging.                   */
    /*                                                                  */
    /*  The same discipline as zx_counter_is_running, one level up:     */
    /*  a guest that armed a timer against a stopped counter was the    */
    /*  failure that check was written for, and this is the             */
    /*  hypervisor's own version of it.                                 */
    /* ---------------------------------------------------------------- */

    {
        uint64_t soon  = zx_read_cntpct() + (uint64_t)(zx_board_counter_hz()
                                                       / 1000U);
        uint32_t armed = zx_el2_hyp_timer_arm(soon);

        zx_el2_dwell_until(soon + (uint64_t)(zx_board_counter_hz() / 1000U));

        zx_console_puts("\n--- the hypervisor's own tick, before any "
                        "partition runs ---\n");
        zx_note("armed for a future deadline", armed);
        zx_note("CNTHP expired (ISTATUS)    ", zx_el2_hyp_timer_fired());
        zx_note("GIC has PPI 26 pending     ",
                zx_gic_ppi_is_pending(&zx_gic, ZX_PPI_HYPERVISOR_TIMER));

        zx_check("the hypervisor's own comparator EXPIRED.  This is the\n"
                 "         first of three questions a window that never ends\n"
                 "         raises, and the only one that is about the timer\n"
                 "         rather than about the interrupt controller",
                 zx_el2_hyp_timer_fired());

#ifndef ZX_TWO_NO_TICK

        zx_check("and the GIC made it PENDING, which is the second: a\n"
                 "         comparator that expires into a controller that was\n"
                 "         never told is indistinguishable, from the outside,\n"
                 "         from a core that never took the exception",
                 zx_gic_ppi_is_pending(&zx_gic, ZX_PPI_HYPERVISOR_TIMER));

#endif

        zx_el2_hyp_timer_stop();
    }

    zx_console_puts(
        "\n"
        "  AND THE SAME REDIRECTION IS WHAT MAKES THIS AIRTIGHT RATHER THAN\n"
        "  MERELY CHEAP.  ICC_IGRPEN0 is redirected too, so a partition\n"
        "  cannot reach the physical Group 0 enable to switch off the\n"
        "  interrupt that ends its window: it writes the virtual copy and\n"
        "  nothing happens.  Before FMO was set that register was genuinely\n"
        "  shared, and the argument had to be that a partition was granted\n"
        "  no Group 0 interrupt worth enabling.  Now it cannot reach the\n"
        "  enable at all.\n");

    /* THREE THINGS, AND A FRAME NEEDS ALL OF THEM.  The counter has to be
       moving, the GIC has to be awake, and the hypervisor's own tick has to
       be deliverable.  Returned as one answer so that the caller has one
       decision to make, and the caller's decision is to REFUSE rather than
       to start a frame whose windows could never end.  */

    return ((running != 0U) && (awake != 0U) && (tick_deliverable != 0U))
               ? 1U : 0U;
}


/**************************************************************************/
/*  zx_prepare_partition -- validate, load and hand over one guest.       */
/*                                                                        */
/*  Returns non-zero when the partition is ready to be scheduled.         */
/**************************************************************************/

static uint32_t zx_prepare_partition(UINT index, uint32_t options,
                                     uint32_t probe_target)
{
    UINT status;

    zx_partition_reset(&zx_partition_cb[index], &zx_partitions[index]);

    status = zx_partition_prepare(&zx_partition_cb[index]);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_note("zx_partition_prepare", status);
        zx_check("the loader located this partition's window and the image\n"
                 "         fits it", 0U);
        zx_partition_report(&zx_partition_cb[index]);

        return 0U;
    }

    if (zx_guest_image_check(&zx_launch[index]) == 0U)
    {
        zx_console_puts("\n  *** REFUSING to launch this image.  It is either\n"
                        "  *** absent, truncated, or built for a different\n"
                        "  *** window.\n");

        return 0U;
    }

    zx_partition_report(&zx_partition_cb[index]);

    zx_guest_image_load(&zx_partition_cb[index].zx_partition_load);
    zx_guest_hand_over(&zx_launch[index], probe_target, options);
    zx_partition_loaded(&zx_partition_cb[index]);

    zx_check("the partition may be entered now that its image is loaded",
             zx_partition_enter(&zx_partition_cb[index]));

    /* ITS OWN CLOCK STARTS AT ZERO, and each partition's starts
       independently.  Where a partition's time begins is the hypervisor's
       to decide, which is the same property that lets it decide the time
       does not advance while the partition is not running.  */

    zx_context_init(&zx_context[index],
                    zx_partition_cb[index].zx_partition_load.zx_load_entry);
    zx_context_time_reset(&zx_context[index]);

    return 1U;
}


/**************************************************************************/
/*  zx_report_partition -- what one partition did, read at a point where  */
/*                         neither of them is running.                    */
/*                                                                        */
/*  THE SYNCHRONISATION POINT MATTERS AND IT IS NOT THE OBVIOUS ONE.      */
/*  A post-mortem read of a partition's memory attributes the last        */
/*  writer's value to everyone who shared the address -- which cost a     */
/*  wrong conclusion during the Cortex-R52 Modules port work.  Here the   */
/*  two windows are DISJOINT, so no address is shared and the hazard      */
/*  cannot arise by aliasing; what remains is attribution, and the        */
/*  sentinel folded into each guest's checksum is what answers it.  Both  */
/*  are read after the frame has stopped and before anything else runs,   */
/*  so each partition's words are the ones it left behind.                */
/**************************************************************************/

static void zx_report_partition(UINT index)
{
    zx_console_puts("\n=========================================================\n"
                    " PARTITION ");
    zx_console_puts(zx_partitions[index].zx_partition_name);
    zx_console_puts("\n=========================================================\n");

    if (zx_guest_report(&zx_launch[index]) == 0U)
    {
        zx_console_puts("  this partition reported NO progress bits at all,\n"
                        "  which is not the same as reporting failure: it is\n"
                        "  a window nobody wrote.\n");
    }

    zx_console_puts("\n--- and what it kept doing after its verdict ---\n");
    zx_note("liveness counter      ",
            zx_guest_mailbox_read(&zx_launch[index], ZX_GD_LIVE));
    zx_note("its own ticks, running",
            zx_guest_mailbox_read(&zx_launch[index], ZX_GD_TICKS_NOW));
    zx_note("its CNTVCT at the start",
            zx_guest_mailbox_read(&zx_launch[index], ZX_GD_VCT_START));
    zx_note("its CNTVCT now        ",
            zx_guest_mailbox_read(&zx_launch[index], ZX_GD_VCT_NOW));
    zx_note("interrupts it serviced",
            zx_guest_mailbox_read(&zx_launch[index], ZX_GD_IRQ_COUNT));
    zx_note("unexpected INTID      ",
            zx_guest_mailbox_read(&zx_launch[index], ZX_GD_ODD_INTID));

    zx_context_report(&zx_context[index],
                      zx_partitions[index].zx_partition_name);
}


/**************************************************************************/
/*  zx_report_switch_cost                                                 */
/**************************************************************************/

static void zx_report_switch_cost(uint32_t core_hz)
{
    zx_console_puts("\n--- what a partition switch costs, by group ---\n");

    /* THE CONDITIONS COME FIRST, ABOVE THE NUMBERS, and they are printed on
       every run rather than kept in a document.
     *
       A cycle count is quoted back at people.  It travels out of this log
       into a slide, and the four facts that decide what it MEANS do not
       travel with it unless they are attached to it: what the core is
       clocked at, whether the caches were on, what optimisation the image
       was built at, and how many samples the spread came from.  A reader
       who has all four can argue with the number, and a reader who has to
       ask for them is entitled to assume the answer was inconvenient.  */

    zx_console_puts("  the conditions these were measured under:\n");
    zx_console_puts("    core clock, measured against the system counter = ");
    zx_console_putdec(core_hz / 1000000U);
    zx_console_puts(" MHz\n");
    zx_console_puts("    EL2 caches: OFF.  HSCTLR.C and .I are cleared in\n"
                    "      the reset path, so every figure below is a\n"
                    "      CACHE-COLD cost and a warm switch can only be\n"
                    "      faster.  Conservative.\n");
    zx_console_puts("    optimisation: -Og, not -O2.  Conservative again.\n");
    zx_console_puts("    one board, one part, one run.  Reproducible on this\n"
                    "      bench is not the same claim as characterised\n"
                    "      across a population, and nothing here supports\n"
                    "      the second.\n");

    /* AND THE ONE THAT CUTS THE OTHER WAY, which is the reason this block
       exists at all.

       It would be easy to list only the conditions that make the figure
       conservative and let a reader conclude it is an upper bound.  It is
       not.  ZoneX configures no clock tree, so the core runs on the part's
       power-up default -- the internal RC oscillator, which the reference
       manual gives as 48 MHz and names as the default clock for the entire
       system at power-up.  At that clock the memory this switch touches is
       CHEAP in core cycles.  Raise the core clock without raising the
       memory's and the same code costs MORE cycles, not fewer.

       So: cache-cold and unoptimised make this an over-estimate, and a
       backup-clocked core makes it an under-estimate, and nobody should
       quote it as a worst case in either direction until it has been
       measured again with the clock tree configured.  Saying so here is
       cheaper than having it pointed out.  */

    zx_console_puts("\n"
                    "    AND ONE CONDITION THAT CUTS THE OTHER WAY.  ZoneX\n"
                    "      configures no clock tree, so the core runs on\n"
                    "      this part's POWER-UP DEFAULT -- the internal RC\n"
                    "      oscillator, 48 MHz nominal, which the reference\n"
                    "      manual names as the default clock for the whole\n"
                    "      system at power-up.  At that clock the memory this\n"
                    "      switch touches is cheap in CORE CYCLES; raise the\n"
                    "      core clock without raising the memory's and the\n"
                    "      same code costs MORE cycles, not fewer.\n"
                    "\n"
                    "      So this figure is an over-estimate for two reasons\n"
                    "      and an under-estimate for a third.  It is a real\n"
                    "      measurement of a real switch on real silicon, and\n"
                    "      it is NOT a worst case in either direction until\n"
                    "      it has been taken again with the clock tree\n"
                    "      configured.\n");

    if (core_hz != 0U)
    {
        zx_console_puts("    at that clock, one thousand cycles is about ");
        zx_console_putdec(1000000000U / (core_hz / 1000U));
        zx_console_puts(" ns\n");
    }

    zx_console_puts("\n");

    if (zx_pmu_is_running() == 0U)
    {
        zx_console_puts("  the PMU cycle counter is not advancing, so no\n"
                        "  timing is reported.  A number from a counter that\n"
                        "  is not running would be a very convincing wrong\n"
                        "  answer.\n");

        return;
    }

    zx_note("EL1 MPU regions walked    ", zx_cost.zx_cost_el1_regions);
    zx_note("counter read, subtracted  ", zx_cost.zx_cost_counter_read);
    zx_note("save, everything          ", zx_cost.zx_cost_save_full);
    zx_note("  of which the EL1 MPU    ", zx_cost.zx_cost_save_mpu);
    zx_note("restore, everything       ", zx_cost.zx_cost_restore_full);
    zx_note("  of which the EL1 MPU    ", zx_cost.zx_cost_restore_mpu);
    zx_note("stage-2 region set, HPRENR", zx_cost.zx_cost_region_mask);
    zx_note("the time freeze, CNTVOFF  ", zx_cost.zx_cost_time_freeze);
    zx_note("arming the next boundary  ", zx_cost.zx_cost_deadline);

    zx_console_puts(
        "\n"
        "  AND WHAT IS DELIBERATELY NOT IN THE TOTAL, said here rather than\n"
        "  somewhere a reader has to go and look for it.  Two things are\n"
        "  excluded from the per-switch figures, and both would inflate them\n"
        "  for reasons that are not a partition switch:\n"
        "\n"
        "    the guest CONSOLE.  Handing the console back closes a partial\n"
        "    line, which on this board is characters through a polled UART.\n"
        "    A product switch has no console in it; leaving it in made the\n"
        "    published figure describe what a guest had been printing, and\n"
        "    it showed up as a spread of 9,562 cycles against the 190 below.\n"
        "\n"
        "    BURNING A STOPPED PARTITION'S WINDOW.  A boundary that has to\n"
        "    wait out a dead neighbour's slot is a switch plus a wait of up\n"
        "    to a whole window.  Such boundaries are COUNTED and not timed;\n"
        "    the two counts are printed above and are equal in any run where\n"
        "    both partitions live to the end.\n"
        "\n"
        "  Nothing else is excluded.  The groups above sum to the whole\n"
        "  switch, and the per-boundary figures are taken around the real\n"
        "  thing rather than around a reconstruction of it.\n");

    zx_console_puts(
        "\n"
        "  THE EL1 MPU DOMINATES, and that is the answer to the question a\n"
        "  safety customer asks.  A partition switch is not expensive\n"
        "  because the hypervisor does much: its own per-partition state is\n"
        "  three register writes -- one HPRENR mask, one CNTVOFF, one\n"
        "  comparator.  It is expensive because a GUEST has a lot of\n"
        "  registers, and most of them are its memory protection unit.\n"
        "\n"
        "  THE WAY TO MAKE IT CHEAPER IS KNOWN AND IS NOT TAKEN HERE.  HSTR\n"
        "  can trap a guest's own CP15 accesses by register group, so a\n"
        "  hypervisor could shadow the guest's MPU writes and skip the save\n"
        "  half entirely.  That trades a bounded cost at every switch for an\n"
        "  unbounded number of traps while a guest runs, which is the wrong\n"
        "  trade for a static frame and the right one for something else.\n"
        "  The naive version is measured first so that a later phase has a\n"
        "  number to beat.\n");
}


/**************************************************************************/
/*  zx_report_frame                                                       */
/**************************************************************************/

static void zx_report_frame(uint32_t outcome)
{
    zx_console_puts("\n--- the frame, as it ran ---\n");

    zx_note("outcome              ", outcome);
    zx_note("major frames completed", zx_schedule.zx_schedule_frames);
    zx_note("window boundaries    ", zx_frame.zx_frame_switches);
    zx_note("missed deadlines     ", zx_schedule.zx_schedule_missed);
    zx_note("unexplained FIQs     ", zx_frame.zx_frame_spurious);

    zx_note("boundaries timed     ", zx_frame.zx_frame_timed);

    if ((zx_pmu_is_running() != 0U) && (zx_frame.zx_frame_timed != 0U))
    {
        uint32_t mean = (uint32_t)(zx_frame.zx_frame_switch_total
                                   / (uint64_t)zx_frame.zx_frame_timed);

        zx_note("switch cycles, min   ", zx_frame.zx_frame_switch_min);
        zx_note("switch cycles, mean  ", mean);
        zx_note("switch cycles, max   ", zx_frame.zx_frame_switch_max);
        zx_note("switch cycles, spread",
                zx_frame.zx_frame_switch_max - zx_frame.zx_frame_switch_min);

        zx_console_puts(
            "\n"
            "  THE MAXIMUM IS THE NUMBER, not the mean.  A schedule has to be\n"
            "  built to survive the worst switch it will ever take, so a mean\n"
            "  quoted alone hides exactly the excursion a safety reviewer is\n"
            "  asking about.  Both are printed, with the spread between them,\n"
            "  because the SHAPE is the claim: a switch whose cost depended on\n"
            "  what a guest had been doing would show it here.\n"
            "\n"
            "  BOUNDARIES THAT HAD TO BURN A STOPPED PARTITION'S WINDOW ARE\n"
            "  COUNTED AND NOT TIMED.  Such a boundary is a switch plus a\n"
            "  wait of up to a whole window, and averaging the two together\n"
            "  describes neither -- it turned a switch of a few thousand\n"
            "  cycles into one of three million and reported the difference\n"
            "  as jitter.  In a run where both partitions live to the end,\n"
            "  the two counts above are equal.\n");
    }
}


/**************************************************************************/
/*  zx_el2_main -- entered from zx_el2_entry.S at EL2.  Does not return.  */
/**************************************************************************/

ZX_NORETURN void zx_el2_main(void)
{
    uint32_t board_regions;
    uint32_t el2_regions;
    uint32_t status;
    uint32_t granted;
    uint32_t outcome;
    uint32_t options_a;
    uint32_t options_b;
    uint32_t probe_b;
    uint32_t ticks_a;
    uint32_t ticks_b;
    uint32_t core_hz;
    ZX_MANIFEST_FAULT fault;

    /* ---------------------------------------------------------------- */
    /*  BEFORE THE FIRST PRINT.  On a board whose console sits below     */
    /*  0x60000000 the background map reaches it as NORMAL memory, and   */
    /*  Normal memory permits the gathering and reordering that corrupts */
    /*  a polled UART.  So HMAIR, the hypervisor's own MMIO regions and  */
    /*  HSCTLR.M come up FIRST.  See docs/decisions.md D15.              */
    /* ---------------------------------------------------------------- */

    el2_regions   = zx_el2_region_count();
    board_regions = zx_board_mmio_region_count();

    if (el2_regions >= board_regions)
    {
        zx_mair_program();

        if (board_regions > 0U)
        {
            zx_board_program_mmio_regions(0U);
        }

        zx_el2_mpu_enable();
    }

    zx_board_init();

    zx_console_puts(
        "\n"
        "=========================================================\n"
        " Eclipse ThreadX ZoneX -- TWO PARTITIONS, ONE CORE\n"
        " " ZX_PLATFORM_NAME "\n"
        " Armv8-R AArch32, EL2, PMSAv8-R at both stages\n"
        "=========================================================\n"
        "\n"
        " Two ThreadX kernels, each in its own stage-2 window, time-\n"
        " sharing one logical core under a STATIC MAJOR FRAME taken\n"
        " from the manifest.\n"
        "\n"
        " Partition A gets seven ticks of every ten and partition B\n"
        " gets three.  Neither can reach the other's memory, neither\n"
        " can reach the ungranted granule between them, and neither\n"
        " can prevent its own window from ending: the hypervisor's\n"
        " timer is in GIC Group 0, so it arrives as an FIQ at EL2 --\n"
        " and with HCR.FMO set, PSTATE.F is IGNORED at EL1.\n"
        "\n"
        " Each partition's clock advances by its own windows and by\n"
        " nothing else.  That is CNTVOFF, one value per partition,\n"
        " and it is the difference between temporal partitioning and\n"
        " time slicing a guest can observe.\n");

    zx_fault_record_reset(zx_el2_fault_record());
    zx_guest_console_reset();

    zx_console_puts("\n--- identity, as the core reports it ---\n");
    zx_note("MIDR         ", zx_read_midr());
    zx_note("EL2 regions  ", el2_regions);
    zx_note("EL1 regions  ", zx_el1_region_count());
    zx_note("HPRENR bits  ", zx_hprenr_implemented_bits);
    zx_board_report();

    zx_check("HSCTLR.M is set, so the EL2 MPU is live",
             ((zx_read_hsctlr() & ZX_HSCTLR_M) != 0U) ? 1U : 0U);

    if (el2_regions == 0U)
    {
        zx_console_puts("\n  *** HMPUIR reports ZERO EL2 regions, so this "
                        "target cannot host\n  *** stage 2 at all.  Refusing "
                        "to go on.\n"
                        "\nZONEX RESULT: FAILED -- the target cannot host "
                        "stage 2\n");
        zx_console_exit(1U);
    }

    /* ---------------------------------------------------------------- */
    /*  HOW MANY EL1 MPU REGIONS A SWITCH HAS TO CARRY.                 */
    /*                                                                  */
    /*  Read once, here, because the count is fixed for the run and a   */
    /*  coprocessor read inside the switch would cost the path this     */
    /*  image exists to measure -- for an answer that cannot change.    */
    /* ---------------------------------------------------------------- */

    zx_context_probe_el1_regions();

    zx_note("EL1 regions a switch carries", zx_context_el1_regions());
    zx_check("no EL1 MPU region was left out of the switch.  A part with\n"
             "         more regions than a context block can hold would have\n"
             "         its highest ones silently dropped from every save --\n"
             "         so the outgoing partition's last windows would stay\n"
             "         programmed and the incoming one would inherit them,\n"
             "         which is an isolation failure at stage ONE that every\n"
             "         stage-2 check in this suite would miss",
             (zx_context_el1_regions_clamped() == 0U) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  The manifest, the plan, the schedule.                           */
    /* ---------------------------------------------------------------- */

    zx_build_manifest(board_regions);
    zx_describe_launches();
    zx_board_gic_layout(&zx_gic);
    zx_env.zx_env_region_budget = el2_regions;

    status = zx_manifest_verify(&zx_manifest, &zx_env, &fault);

    zx_console_puts("\n--- the manifest, checked before anything is "
                    "programmed ---\n");
    zx_note("zx_manifest_verify", status);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_note("  offending partition", fault.zx_fault_partition);
        zx_note("  offending region   ", fault.zx_fault_region);
        zx_note("  the other offender ", fault.zx_fault_other_partition);
        zx_check("the manifest passes every rule", 0U);
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_check("the manifest passes every rule, including the one that makes\n"
             "         two partitions possible at all: their windows do not\n"
             "         overlap.  PMSAv8-R has no region priority, so two\n"
             "         enabled regions on one address is CONSTRAINED\n"
             "         UNPREDICTABLE and aborts on silicon",
             1U);

    zx_check("and NEITHER partition is granted a device region of any kind,\n"
             "         even though both have an interrupt and a clock.  A\n"
             "         partition's whole interrupt capability is\n"
             "         system-register state and its whole clock is a\n"
             "         register only EL2 can write",
             ((zx_partitions[ZX_PART_A].zx_partition_region_count == 1U)
              && (zx_partitions[ZX_PART_B].zx_partition_region_count == 1U))
                 ? 1U : 0U);

    status = zx_mm_plan(&zx_manifest, board_regions, el2_regions,
                        zx_hprenr_implemented_bits, &zx_layout);
    zx_note("zx_mm_plan", status);
    zx_check("the layout fits this part's region budget AND every region it\n"
             "         assigned has an HPRENR enable bit, so the one-write\n"
             "         partition switch can reach all of them",
             (status == ZX_MANIFEST_SUCCESS) ? 1U : 0U);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_mm_report(&zx_layout, &zx_manifest);

    status = zx_schedule_build(&zx_manifest,
                               (uint64_t)(zx_board_counter_hz() / ZX_TICK_HZ),
                               ZX_FRAME_LIMIT, &zx_schedule);

    zx_console_puts("\n--- the major frame ---\n");
    zx_note("zx_schedule_build", status);
    zx_check("the schedule was built, and the major frame equals the sum of\n"
             "         its windows -- a manifest carries the total explicitly\n"
             "         so that it CAN disagree, and a disagreement means\n"
             "         somebody changed a window and not the total",
             (status == ZX_MANIFEST_SUCCESS) ? 1U : 0U);

    if (status != ZX_MANIFEST_SUCCESS)
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_schedule_report(&zx_schedule, &zx_manifest);

    /* ---------------------------------------------------------------- */
    /*  The region set, programmed once and never again.                */
    /*                                                                  */
    /*  Both partitions' descriptors are written at boot and a switch    */
    /*  changes which are ENABLED.  That is what makes the switch one    */
    /*  register write of bounded cost instead of a loop whose length    */
    /*  depends on the incoming partition -- see docs/decisions.md D4.   */
    /* ---------------------------------------------------------------- */

    {
        UINT part;

        zx_console_puts("\n--- the region set, programmed and read back ---\n");

        for (part = 0U; part < ZX_PART_COUNT; part++)
        {
            uint32_t index =
                (uint32_t)zx_layout.zx_layout_partition_first[part];
            const ZX_REGION *region = (part == ZX_PART_A)
                                          ? &zx_regions_a[0] : &zx_regions_b[0];

            zx_stage2_region_program(index, region);

            zx_note("region index", index);
            zx_check("this partition's window reads back as the manifest\n"
                     "         declared it -- an under-aligned base does not\n"
                     "         fault, its low bits land on SH, AP and XN and\n"
                     "         silently change what it grants",
                     zx_stage2_region_matches(index, region));
        }
    }

    zx_console_puts("\n  the ungranted granule between the two windows is at ");
    zx_console_puthex(zx_symbol_address(__zx_partition_a_hole_start));
    zx_console_puts("\n  and the one after partition B is at ");
    zx_console_puthex(zx_symbol_address(__zx_partition_b_hole_start));
    zx_console_puts("\n");

    /* ---------------------------------------------------------------- */
    /*  What ZoneX takes over from each guest's boot path.              */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- what ZoneX takes over from a guest's boot path "
                    "---\n");
    zx_el2_prepare_guest_el1(zx_board_counter_hz());
    zx_note("CNTFRQ after ", zx_read_cntfrq());
    zx_check("CNTFRQ is programmed, because it is writable only at the\n"
             "         highest implemented exception level and a guest\n"
             "         deriving a tick interval from a zero divides by zero",
             (zx_read_cntfrq() == zx_board_counter_hz()) ? 1U : 0U);

    granted = zx_grant_the_clocks();

    /* ---------------------------------------------------------------- */
    /*  REFUSE TO START A FRAME WHOSE WINDOWS COULD NEVER END.          */
    /*                                                                  */
    /*  Everything a partition needs is up, or it is not, and the        */
    /*  difference decides whether the next few hundred milliseconds are */
    /*  a demonstration or a hang.  A frame started without a            */
    /*  deliverable tick does not fail: the first partition simply runs  */
    /*  until something outside this image stops it, and the log ends    */
    /*  mid-sentence with no verdict, no fault and nothing to point at.  */
    /*                                                                  */
    /*  THIS IS THE SAME RULE AS zx_counter_is_running, ONE LEVEL UP.    */
    /*  That check exists because a GUEST that arms a timer against a    */
    /*  stopped counter waits for ever and ends the run in a harness     */
    /*  timeout naming nothing.  This is the hypervisor's own version of */
    /*  exactly that failure, and it deserves exactly that answer.       */
    /*                                                                  */
    /*  It is also what makes the negative build a TEST rather than a    */
    /*  hang.  zx_two_partitions_no_tick.elf deliberately leaves the     */
    /*  hypervisor's PPI disabled; without this it would prove its point */
    /*  by never finishing, and a negative run that produces no verdict  */
    /*  is indistinguishable from an image that was never built.         */
    /* ---------------------------------------------------------------- */

    if (granted == 0U)
    {
        zx_console_puts(
            "\n  *** REFUSING TO START THE FRAME.  Something a window\n"
            "  *** boundary depends on is not in place: the system counter,\n"
            "  *** the redistributor, or the hypervisor's own timer PPI.\n"
            "  *** Starting anyway would run the first partition until\n"
            "  *** something outside this image stopped it, and the log\n"
            "  *** would end mid-sentence with no verdict to read.\n");

        zx_check("everything a window boundary depends on is in place", 0U);
        zx_console_puts("\nZONEX RESULT: FAILED -- the hypervisor's own tick "
                        "cannot be delivered\n");
        zx_console_exit(zx_probe_failures());
    }

    /* ---------------------------------------------------------------- */
    /*  Load both guests, and hand each one its options.                */
    /* ---------------------------------------------------------------- */

    zx_stage2_enable();
    zx_note("HCR now", zx_read_hcr());
    zx_check("HCR.VM is set, so stage 2 applies to EL0/EL1 for the whole of\n"
             "         this run",
             ((zx_read_hcr() & ZX_HCR_VM) != 0U) ? 1U : 0U);
    zx_check("HCR.TGE is clear, so each guest keeps its own exception\n"
             "         vectors -- without which its IRQ vector could not be\n"
             "         the thing that runs",
             ((zx_read_hcr() & ZX_HCR_TGE) == 0U) ? 1U : 0U);

    zx_pmu_enable();

    /* WHAT THE CORE IS CLOCKED AT, measured against the system counter --
       whose own frequency is the one number in this system that has
       actually been established.  Every switch figure below is in core
       CYCLES, and a cycle count nobody can convert into a duration is a
       number nobody can argue with, which is not the same as one they
       should accept.  */

    core_hz = zx_pmu_core_hz(zx_board_counter_hz(), zx_board_counter_hz()
                                                        / 1000U);

    zx_note("core clock, Hz, measured", core_hz);
    zx_check("the core clock could be measured against the system counter,\n"
             "         so every cycle figure in this run converts to a\n"
             "         duration.  It is measured rather than read out of a\n"
             "         clock-tree register, which would report what somebody\n"
             "         programmed rather than what the core is doing",
             (core_hz > 0U) ? 1U : 0U);

    /* PARTITION A IS QUIET AND PARTITION B IS LOUD, and the asymmetry is
       the demonstration rather than a saving.  A guest's console is one
       hypercall PER CHARACTER through a polled UART, which on silicon is
       three orders of magnitude more work than everything else it does --
       so a run with both partitions printing could not resolve anything
       about either.  One quiet partition and one chatty one is also the
       mixed-criticality shape the demonstrator is for: the critical one
       does its work, the untrusted one makes noise, and the frame does not
       care.

       BOTH RUN FOR EVER, because a schedule can only be shown to preempt
       partitions that are still trying to run.  */

    options_a = ZX_GO_TICK | ZX_GO_QUIET | ZX_GO_FOREVER;
    options_b = ZX_GO_TICK | ZX_GO_FOREVER;
    probe_b   = 0U;

#ifdef ZX_TWO_CROSS

    /* THE ISOLATION CLAIM BETWEEN TWO LIVE PARTITIONS, and it is the one
       thing a single partition cannot demonstrate however hard it tries.
     *
     * Partition B is handed an address inside partition A's window and told
     * to write to it.  Its guest first GRANTS ITSELF that granule in its own
     * EL1 MPU -- so stage 1 permits the access and B genuinely believes it
     * owns the memory -- and then writes.
     *
     * Stage 2 must refuse, because A's region is not in B's enabled set and
     * PMSAv8-R gives EL0/EL1 no background map: an access that hits no
     * enabled region faults regardless of HSCTLR.BR.  That is "the stricter
     * of the two stages wins" with the two stages genuinely disagreeing,
     * between two partitions that are both alive.
     *
     * The address is well past A's mailbox, inside its code, so that a run
     * in which the write DID succeed would be visibly catastrophic rather
     * than quietly wrong.  Nothing is written on a correct run.
     *
     * AND THE REST OF THE RUN IS THE SECOND HALF OF THE CLAIM.  B is
     * stopped, and partition A carries on to the end of the frame with its
     * own schedule untouched -- which is what "a partition cannot harm its
     * neighbour" has to mean if it means anything.  B's windows are still
     * SPENT, because a static frame does not give a dead partition's time
     * away, and that path is exercised nowhere else in this suite.  */

    probe_b   = (uint32_t)zx_symbol_address(__zx_partition_a_start) + 0x1000U;
    options_b = ZX_GO_TICK | ZX_GO_QUIET;

    zx_console_puts("\n=========================================================\n"
                    " CROSS-PARTITION BUILD: B reaches into A's window\n"
                    "=========================================================\n"
                    "  Partition B is told to write to ");
    zx_console_puthex(probe_b);
    zx_console_puts(", which is\n"
                    "  inside partition A's window and inside nothing B was\n"
                    "  granted.  B's guest GRANTS ITSELF that granule in its\n"
                    "  own EL1 MPU first, so stage 1 permits it and B\n"
                    "  genuinely believes it owns the memory.\n"
                    "\n"
                    "  Stage 2 must refuse anyway, and this run must PASS:\n"
                    "  the violation is detected, named, and B is stopped --\n"
                    "  while partition A runs to the end of the frame with\n"
                    "  its own schedule completely untouched.  That second\n"
                    "  half is what 'a partition cannot harm its neighbour'\n"
                    "  has to mean if it means anything.\n");

#endif

#ifdef ZX_TWO_HOG

    /* THE DEMONSTRATION THIS DESIGN EXISTS FOR.  Partition B masks IRQ and
       FIQ at EL1 and spins for ever, making no kernel call and giving
       nothing back.  It must be preempted anyway, and the only thing its
       masking may cost it is its OWN kernel's tick.

       Quiet as well, because a hogging partition that also printed would
       be handing the machine back through a hypercall on every character,
       which is the opposite of hogging.  */

    options_b = ZX_GO_TICK | ZX_GO_QUIET | ZX_GO_FOREVER | ZX_GO_HOG;

    zx_console_puts("\n=========================================================\n"
                    " HOSTILE BUILD: partition B masks its interrupts and\n"
                    " spins for ever\n"
                    "=========================================================\n"
                    "  It makes no kernel call, asks the hypervisor for\n"
                    "  nothing, and disables both IRQ and FIQ at EL1.  That\n"
                    "  is as uncooperative as an EL1 program can be.\n"
                    "\n"
                    "  IT MUST BE PREEMPTED ANYWAY, and this run must PASS.\n"
                    "  With HCR.FMO set, PSTATE.F is ignored at EL0 and EL1,\n"
                    "  so the FIQ that ends B's window reaches EL2 whatever B\n"
                    "  has masked -- and B cannot reach the bit that would\n"
                    "  change that, because ICC_IGRPEN0 is redirected to the\n"
                    "  virtual interface the moment FMO is set.\n"
                    "\n"
                    "  What the masking DOES cost B is its own kernel's tick,\n"
                    "  and that shows: B's liveness counter keeps rising while\n"
                    "  its tick count stops.  A frame driven by an interrupt\n"
                    "  taken at EL1 would hang here instead, which is why this\n"
                    "  is a build and not a paragraph.\n");

#endif

    zx_console_puts("\n--- loading partition A ---\n");

    if (zx_prepare_partition(ZX_PART_A, options_a, 0U) == 0U)
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    zx_console_puts("\n--- loading partition B ---\n");

    if (zx_prepare_partition(ZX_PART_B, options_b, probe_b) == 0U)
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
        zx_console_exit(zx_probe_failures());
    }

    /* ---------------------------------------------------------------- */
    /*  MEASURE THE SWITCH BEFORE RUNNING THE FRAME.                    */
    /*                                                                  */
    /*  Before, because the measurement writes into scratch contexts     */
    /*  and reads the machine's current EL1 state -- which after a       */
    /*  frame would be whichever partition happened to stop last.       */
    /*  Measuring here means every group is timed against the same,      */
    /*  known, quiescent state.                                          */
    /* ---------------------------------------------------------------- */

    zx_frame_measure_switch(&zx_scratch[0], &zx_scratch[1],
                            zx_mm_partition_mask(&zx_layout, ZX_PART_A),
                            zx_mm_partition_mask(&zx_layout, ZX_PART_B),
                            ZX_MEASURE_ROUNDS, &zx_cost);

    /* ---------------------------------------------------------------- */
    /*  RUN THE FRAME.                                                  */
    /* ---------------------------------------------------------------- */

    /* THE FLOATING-POINT TRAPS GO ON HERE, AND COME OFF THE MOMENT THE
       FRAME ENDS.  They bracket exactly the interval they protect, and
       nothing else.
     *
     * zx_el2_prepare_guest_el1 OPENS the FPU, which was exactly right while
     * there was one partition: there was nobody to share the register bank
     * with.  With two it is two guests reading each other's registers, and
     * nothing in ZoneX saves FPEXC, FPSCR or the D-registers across a
     * switch -- so the failure mode is a WRONG ANSWER and not a fault.
     * Closing the traps turns that into an exception at EL2 with a syndrome
     * naming the cause.  See D23 and D25.
     *
     * WHY THE BRACKET IS TIGHT RATHER THAN COVERING THE WHOLE RUN.  With
     * the traps set, the S32Z280's debug probe cannot read the core's
     * register file at all: the harness exits non-zero on a run whose own
     * console said ALL CHECKS PASSED, and every refusal path that stops
     * before a frame starts would fail the same way.  Setting them here and
     * lifting them the moment zx_frame_run returns means every exit path
     * except the one with partitions actually running is unaffected --
     * which is also the clearest statement of what the traps are for.  */

    zx_el2_deny_guest_fp();

    zx_console_puts("\n  the FPU is now DENIED to both partitions, which is\n"
                    "  the opposite of what a one-partition image does.\n"
                    "  Nothing here saves the floating-point register bank\n"
                    "  across a switch, so two guests would share it -- and\n"
                    "  that failure is a wrong number rather than a fault.\n"
                    "  A trap is a diagnosis; a shared bank is not.\n");

    zx_frame_configure(&zx_frame, &zx_schedule, zx_context, &zx_layout,
                       &zx_manifest, ZX_PART_COUNT);

    zx_console_puts("\n=========================================================\n"
                    " THE FRAME STARTS HERE\n"
                    "=========================================================\n"
                    "  Everything below the guests' own output happened under\n"
                    "  a static schedule.  Partition B prints; partition A is\n"
                    "  quiet so that a measured run is measurable.  Each line\n"
                    "  is tagged by the partition ZoneX SCHEDULED and never by\n"
                    "  the guest, which is why a guest cannot claim to be its\n"
                    "  neighbour.\n\n");

    /* THE CONSOLE TAG FOLLOWS THE SCHEDULE and is not set here.  With one
       partition the image attached once around the whole excursion; with a
       frame the partition that owns the console changes several times a
       second, so the SWITCH attaches and detaches -- see zx_frame_enter.
       The tag therefore always names the partition ZoneX scheduled, which
       is the only party that knows it, and a guest cannot claim to be its
       neighbour even while their output interleaves.  */

    outcome = zx_frame_run(&zx_frame);

    /* THE LAST WINDOW HAS CLOSED, so the floating-point traps come off.
       There are no more switches and nothing left to share.  See the note
       where they went on: leaving them set costs the silicon harness its
       ability to read the core's registers at all.  */

    zx_el2_allow_guest_fp();

    /* ---------------------------------------------------------------- */
    /*  What happened.                                                  */
    /* ---------------------------------------------------------------- */

    zx_report_frame(outcome);
    zx_report_switch_cost(core_hz);

    zx_report_partition(ZX_PART_A);
    zx_report_partition(ZX_PART_B);

    if (outcome == ZX_RUN_FAULTED)
    {
        zx_fault_report(zx_el2_fault_record());
    }

    ticks_a = zx_guest_mailbox_read(&zx_launch[ZX_PART_A], ZX_GD_TICKS_NOW);
    ticks_b = zx_guest_mailbox_read(&zx_launch[ZX_PART_B], ZX_GD_TICKS_NOW);

    /* PRINTED IN EVERY BUILD, INCLUDING THE ONES THAT FAIL.  The negative
       builds are where these three numbers are most worth having: a run in
       which no window ended needs to show that partition A ticked and
       partition B did not, and a run refused by the validator needs to show
       that the clocks came up before the refusal.  A value printed only on
       the passing path is a value missing from every log worth reading.  */

    zx_console_puts("\n--- the three numbers every build reports ---\n");
    zx_note("counter and GIC came up", granted);
    zx_note("partition A's own ticks ", ticks_a);
    zx_note("partition B's own ticks ", ticks_b);

    /* ---------------------------------------------------------------- */
    /*  The demonstrandum.                                              */
    /* ---------------------------------------------------------------- */

#ifdef ZX_TWO_OVERLAP

    zx_console_puts("\n  This build should never have reached here: its\n"
                    "  manifest declares two overlapping windows and the\n"
                    "  validator must refuse it.\n");
    zx_check("the validator refused the overlapping manifest (this check is\n"
             "         EXPECTED TO FAIL if it is ever reached at all)", 0U);

#elif defined(ZX_TWO_NO_TICK)

    /* THIS POINT IS UNREACHABLE IN THIS BUILD, and reaching it is itself a
       failure worth reporting.
     *
       The negative build leaves the hypervisor's own PPI disabled, so the
       refusal above stops the run before a frame is ever started: the whole
       point of that refusal is that a frame which cannot end a window must
       not be started, because it would prove its point by never finishing
       and a negative run producing no verdict is indistinguishable from an
       image that was never built.
     *
       So the check below exists to catch the refusal having been removed or
       weakened.  If control gets here, a frame ran without a deliverable
       tick -- which means it hung and was interrupted, or the precondition
       stopped being checked.  */

    zx_console_puts("\n  *** The frame was started in a build whose tick\n"
                    "  *** cannot be delivered.  The precondition that was\n"
                    "  *** supposed to refuse it did not.\n");
    zx_check("a frame is never started without a deliverable tick", 0U);

#else

    zx_console_puts("\n=========================================================\n"
                    " TWO THREADX PARTITIONS UNDER A STATIC MAJOR FRAME\n"
                    "=========================================================\n");

    zx_check("the counter, the GIC and the routing all came up BEFORE the\n"
             "         frame started -- checked as a precondition and not as\n"
             "         an observation, because a frame that cannot end a\n"
             "         window does not fail, it hangs",
             granted);

    zx_check("the frame ran to its declared limit rather than stopping\n"
             "         early.  A bounded run is what lets this be asserted on\n"
             "         at all -- 'the harness timed out' is not a result",
             ((outcome == ZX_RUN_FRAME_DONE)
              && (zx_schedule.zx_schedule_frames == ZX_FRAME_LIMIT))
                 ? 1U : 0U);

#ifndef ZX_TWO_CROSS

    /* THE CHECKS THAT ONLY MEAN ANYTHING WHEN BOTH PARTITIONS SURVIVE.
     *
     * The cross-partition build deliberately kills one of them, so a frame
     * in which one partition stopped is the RESULT there and would be a
     * failure here.  Separating them is not bookkeeping: a check skipped in
     * the build it cannot hold for is honest, and a check loosened until it
     * holds everywhere has stopped saying anything.  */

    zx_check("EVERY WINDOW ENDED AT A BOUNDARY.  Two windows per frame for\n"
             "         the whole run, and each one was taken from a partition\n"
             "         that had not asked to give it up -- by an FIQ delivered\n"
             "         to EL2 through a redistributor no partition can address",
             (zx_frame.zx_frame_switches
              >= ((uint32_t)ZX_FRAME_LIMIT * ZX_PART_COUNT) - 1U) ? 1U : 0U);

    zx_check("no window boundary was MISSED.  A missed deadline means a\n"
             "         window was shorter than its own partition switch: the\n"
             "         schedule would keep turning, in the right order and the\n"
             "         right proportions, with every frame longer than it was\n"
             "         declared to be.  Nothing else in this run would show it",
             (zx_schedule.zx_schedule_missed == 0UL) ? 1U : 0U);

    zx_check("and no FIQ arrived that the hypervisor's own timer had not\n"
             "         raised, so every switch above was performed for a\n"
             "         reason somebody can name",
             (zx_frame.zx_frame_spurious == 0U) ? 1U : 0U);

    zx_check("BOTH partitions were entered, more than once each.  One\n"
             "         partition running many times and the other never is a\n"
             "         perfectly plausible-looking log, and it is not time\n"
             "         partitioning",
             ((zx_context[ZX_PART_A].zx_ctx_entries > 1U)
              && (zx_context[ZX_PART_B].zx_ctx_entries > 1U)) ? 1U : 0U);

    zx_check("both reached their own verdicts, so the loader, the entry\n"
             "         points and both guests' kernels are not what is being\n"
             "         tested here",
             ((zx_guest_mailbox_read(&zx_launch[ZX_PART_A], ZX_GD_VERDICT)
               == ZX_GV_PASSED)
              && (zx_guest_mailbox_read(&zx_launch[ZX_PART_B], ZX_GD_VERDICT)
                  == ZX_GV_PASSED)) ? 1U : 0U);

    zx_check("BOTH KEPT RUNNING AFTERWARDS, so every window after their\n"
             "         verdicts was taken from a partition that was genuinely\n"
             "         using it.  A partition that had finished would be idled\n"
             "         through its windows and would prove nothing about\n"
             "         preemption",
             ((zx_guest_mailbox_read(&zx_launch[ZX_PART_A], ZX_GD_LIVE) > 0U)
              && (zx_guest_mailbox_read(&zx_launch[ZX_PART_B], ZX_GD_LIVE)
                  > 0U)) ? 1U : 0U);

    zx_check("neither partition saw an INTID it was not granted -- so\n"
             "         neither received the hypervisor's own timer, nor the\n"
             "         other's, nor anything else",
             ((zx_guest_mailbox_read(&zx_launch[ZX_PART_A], ZX_GD_ODD_INTID)
               == 0U)
              && (zx_guest_mailbox_read(&zx_launch[ZX_PART_B], ZX_GD_ODD_INTID)
                  == 0U)) ? 1U : 0U);

    zx_check("and neither guest's own vectors reported a stage-1 fault, so\n"
             "         neither kernel did anything its OWN MPU refused --\n"
             "         which is a different claim from stage 2 and is made by\n"
             "         a different mechanism",
             ((zx_guest_mailbox_read(&zx_launch[ZX_PART_A], ZX_GD_STAGE1)
               == ZX_GS_NONE)
              && (zx_guest_mailbox_read(&zx_launch[ZX_PART_B], ZX_GD_STAGE1)
                  == ZX_GS_NONE)) ? 1U : 0U);

    /* ---------------------------------------------------------------- */
    /*  THE TEMPORAL CLAIM, from both sides.                            */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n--- each partition's own time, against its budget ---\n");

    zx_note("A: counts on the core",
            (uint32_t)(zx_context[ZX_PART_A].zx_ctx_time_on_core
                       & 0xFFFFFFFFU));
    zx_note("A: its own ticks     ", ticks_a);
    zx_note("B: counts on the core",
            (uint32_t)(zx_context[ZX_PART_B].zx_ctx_time_on_core
                       & 0xFFFFFFFFU));
    zx_note("B: its own ticks     ", ticks_b);

    zx_console_puts(
        "\n"
        "  A HAS SEVEN TICKS OF EVERY TEN AND B HAS THREE, so A's own clock\n"
        "  must have advanced by more than B's -- and by roughly the ratio\n"
        "  of their windows rather than by the ratio of anything else.  The\n"
        "  check below is deliberately loose about the exact figure and\n"
        "  strict about the ORDER: a run in which B's clock had caught A's\n"
        "  would be a run in which a partition could see time it was not\n"
        "  given, and that is the failure this whole mechanism exists to\n"
        "  prevent.  It leaves the system running perfectly and lying about\n"
        "  time, which nothing else here would notice.\n");

    zx_check("BOTH partitions' clocks advanced, so neither was frozen out\n"
             "         of its own windows as well as out of its neighbour's",
             ((ticks_a > 0U) && (ticks_b > 0U)) ? 1U : 0U);

    zx_check("and PARTITION A'S CLOCK RAN AHEAD OF PARTITION B'S, in the\n"
             "         direction their window budgets say it must.  Each\n"
             "         partition's virtual counter advanced by the counts it\n"
             "         spent on the core and by none of the counts it did\n"
             "         not: that is CNTVOFF, one value per partition, moved\n"
             "         by exactly the interval each was away",
             (ticks_a > ticks_b) ? 1U : 0U);

    /* AND THE RATIO, WHICH IS THE CLAIM ITSELF RATHER THAN A SYMPTOM OF IT.
     *
     * If each partition's clock advances by exactly the counts it spent on
     * the core, then A's total and B's total stand in the ratio of their
     * declared windows -- seven to three -- and that is an equality with no
     * slack in it: A x 3 must equal B x 7.
     *
     * IT IS WRITTEN AS TWO PRODUCTS AND NOT AS A DIVISION.  Integer division
     * of two counts throws away exactly the precision the check needs, and a
     * ratio computed as A/B on numbers this size is a small integer whose
     * error bars are wider than the defect being looked for.
     *
     * IN 64-BIT, because each product is a count of counter counts times a
     * window length: at the model's 100 MHz a six-frame run already reaches
     * 1.3 x 10^8 in each factor, and a longer run or a faster counter passes
     * 2^32 without anything appearing to be wrong.
     *
     * THE TOLERANCE IS 2% AND IT IS NOT ARBITRARY.  Two things legitimately
     * perturb the ratio and neither is a defect: the FIRST window is
     * entered from a cold start rather than from a switch, and the last one
     * is cut short by the frame limit rather than by a boundary.  Both are
     * one window out of twelve.  What 2% will not absorb is a partition
     * seeing its neighbour's time at all -- that is a factor of three.
     *
     * A NOTE ON WHAT THIS REPLACED, because it is the mistake this file is
     * most at risk of repeating.  The check here used to compare A's time
     * against A's plus B's and conclude that A had not seen wall clock.
     * That is arithmetically true for any positive B: it was a tautology
     * wearing the words of a claim, and it would have passed on a run where
     * CNTVOFF was never written at all.  */

    {
        uint64_t a_scaled = zx_context[ZX_PART_A].zx_ctx_time_on_core
                            * (uint64_t)ZX_WINDOW_B_TICKS;
        uint64_t b_scaled = zx_context[ZX_PART_B].zx_ctx_time_on_core
                            * (uint64_t)ZX_WINDOW_A_TICKS;
        uint64_t apart    = (a_scaled > b_scaled)
                                ? (a_scaled - b_scaled) : (b_scaled - a_scaled);
        uint64_t allowed  = a_scaled / 50U;     /* two per cent */

        zx_note("A's counts x B's window ticks", (uint32_t)(a_scaled
                                                            & 0xFFFFFFFFU));
        zx_note("B's counts x A's window ticks", (uint32_t)(b_scaled
                                                            & 0xFFFFFFFFU));

        zx_check("AND THE TWO CLOCKS STAND IN THE RATIO OF THEIR DECLARED\n"
                 "         WINDOWS, seven to three, to within two per cent.\n"
                 "         This is the temporal claim itself and not a\n"
                 "         symptom of it: each partition's virtual counter\n"
                 "         advanced by the counts it spent on the core and by\n"
                 "         none of the counts it did not.  A partition that\n"
                 "         could see wall clock would be out by a FACTOR of\n"
                 "         three here, not by a percentage",
                 ((a_scaled > 0U) && (apart <= allowed)) ? 1U : 0U);
    }

#endif  /* the both-survive block */

#ifdef ZX_TWO_CROSS

    /* THE OTHER HALF OF THE CROSS-PARTITION CLAIM, and the half that a
       single partition could never make: partition B tried to write inside
       partition A's window, stage 2 refused, B was stopped -- AND A RAN TO
       THE END OF THE FRAME WITH ITS OWN SCHEDULE UNTOUCHED.
     *
     * "A partition cannot reach its neighbour's memory" is only half of
     * what isolation has to mean.  The other half is that being attacked
     * costs the neighbour nothing: not a window, not a tick, not a
     * boundary.  A run in which A's clock had slowed because B misbehaved
     * would satisfy every memory check above and would not be temporal
     * partitioning.  */

    zx_check("PARTITION B WAS STOPPED AT ITS BOUNDARY, and by a stage-2\n"
             "         fault rather than by anything it asked for.  Its own\n"
             "         EL1 MPU said it owned the granule -- the guest granted\n"
             "         itself that region before writing -- and the stricter\n"
             "         of the two stages won",
             ((zx_frame.zx_frame_stopped_index == ZX_PART_B)
              && (zx_frame.zx_frame_stop_outcome == ZX_RUN_FAULTED))
                 ? 1U : 0U);

    zx_check("and the syndrome is a data abort ROUTED to EL2, which is a\n"
             "         stage-2 violation and not the guest's own MPU\n"
             "         complaining -- a stage-1 fault never reaches the\n"
             "         hypervisor at all, and that difference is what makes\n"
             "         the two stages distinguishable in a log",
             (zx_fault_ec(zx_el2_fault_record()->zx_fault_hsr)
              == ZX_EC_DABT_ROUTED) ? 1U : 0U);

    zx_check("and HDFAR names the address B aimed at, inside A's window, so\n"
             "         the fault is attributable to the access and not merely\n"
             "         coincident with it",
             (zx_el2_fault_record()->zx_fault_hdfar == probe_b) ? 1U : 0U);

    zx_check("PARTITION A WAS UNAFFECTED.  It ran every one of its windows,\n"
             "         to the end of the frame, while its neighbour was\n"
             "         faulting and then dead.  Being attacked cost it\n"
             "         nothing -- not a window, not a tick, not a boundary",
             ((zx_context[ZX_PART_A].zx_ctx_entries >= ZX_FRAME_LIMIT)
              && (outcome == ZX_RUN_FRAME_DONE)) ? 1U : 0U);

    zx_check("and B's windows were still SPENT rather than given away.  A\n"
             "         static frame does not hand a dead partition's time to\n"
             "         its neighbour: doing so would make A's schedule depend\n"
             "         on B's behaviour, which is the coupling temporal\n"
             "         partitioning is bought to remove.  A's own clock is\n"
             "         still seven tenths of the frame and not all of it",
             (zx_context[ZX_PART_A].zx_ctx_time_on_core
              < (uint64_t)ZX_FRAME_LIMIT * (uint64_t)ZX_FRAME_TICKS
                    * (uint64_t)(zx_board_counter_hz() / ZX_TICK_HZ)
                    * 4U / 5U) ? 1U : 0U);

#endif

#ifdef ZX_TWO_HOG

    zx_check("THE HOGGING PARTITION WAS PREEMPTED ANYWAY.  It masked IRQ\n"
             "         and FIQ at EL1 and never made another kernel call, and\n"
             "         its window ended on time regardless -- because with\n"
             "         HCR.FMO set, PSTATE.F is IGNORED at EL0 and EL1 and a\n"
             "         partition cannot reach the physical Group 0 enable",
             (zx_context[ZX_PART_B].zx_ctx_preemptions > 1U) ? 1U : 0U);

    zx_check("and the masking cost it exactly what it should have cost: its\n"
             "         OWN kernel's tick stopped while its liveness counter\n"
             "         kept rising.  That pair is the evidence that the\n"
             "         masking really took effect at EL1 and really did\n"
             "         nothing to the hypervisor",
             ((zx_guest_mailbox_read(&zx_launch[ZX_PART_B], ZX_GD_LIVE) > 0U)
              && (ticks_b < ticks_a)) ? 1U : 0U);

#endif

    zx_console_puts("\n--- the guests printed through the hypervisor ---\n");
    zx_note("characters forwarded", zx_guest_console_characters());
    zx_check("and no character arrived while NO partition was attached",
             (zx_guest_console_orphans() == 0U) ? 1U : 0U);

#endif

    /* ---------------------------------------------------------------- */
    /*  Verdict.  The exact strings are what the runners grep for.      */
    /* ---------------------------------------------------------------- */

    zx_console_puts("\n=========================================================\n"
                    " what this run does and does not prove\n"
                    "=========================================================\n"
                    " " ZX_PLATFORM_NAME "\n"
                    "\n"
                    " PROVED, if the checks above are green: two ThreadX\n"
                    " partitions time-share one logical core under a static\n"
                    " major frame; each is confined to its own window at\n"
                    " stage 2; each window ends at a boundary the partition\n"
                    " cannot defer or mask; each partition's clock advances\n"
                    " by its own windows and by nothing else; and the switch\n"
                    " between them is bounded, measured, and broken down by\n"
                    " group.\n"
                    "\n"
                    " NOT PROVED, and the omissions are deliberate rather\n"
                    " than pending:\n"
                    "\n"
                    "   * This is TIME partitioning on ONE logical core, not\n"
                    "     spatial partitioning across several.  On lockstep\n"
                    "     silicon there is one core to share.\n"
                    "\n"
                    "   * Interrupt LATENCY is not a hypervisor-controlled\n"
                    "     quantity here.  Guest interrupts go straight to\n"
                    "     EL1, which is why they cost what they always did --\n"
                    "     and why bounding them needs the List Registers this\n"
                    "     core has and this phase does not use.\n"
                    "\n"
                    "   * A faulted partition is STOPPED, not restarted.\n"
                    "     Supervised restart is a later phase and a\n"
                    "     hypervisor that quietly re-entered a partition\n"
                    "     which had just violated its boundary would be doing\n"
                    "     the easy half of it.\n"
                    "\n"
                    "   * Nothing about timing on a functional model.  Every\n"
                    "     cycle count above has to come from silicon before\n"
                    "     it is quoted.\n"
                    "\n"
                    " ONE FAILURE MODE IS DELIBERATELY NOT A BUILD, and it is\n"
                    " worth saying why rather than leaving a gap: a partition\n"
                    " faulting at the exact instant of a frame boundary.  It\n"
                    " cannot be arranged reproducibly -- it is a race whose\n"
                    " window is a few cycles wide -- and a test that provoked\n"
                    " it once would not be a regression, it would be an\n"
                    " anecdote.\n"
                    "\n"
                    " What can be said instead is structural.  The two events\n"
                    " arrive at DIFFERENT VECTORS -- a fault at the Hyp trap\n"
                    " entry, a boundary at the FIQ vector -- and a core takes\n"
                    " one exception at a time.  Whichever arrives first is\n"
                    " taken, and the other is still pending afterwards: a\n"
                    " fault taken first comes back to the hypervisor with the\n"
                    " boundary's FIQ still asserted at the GIC, and a boundary\n"
                    " taken first re-enters the faulting partition, which\n"
                    " faults again on the same instruction.  Neither order\n"
                    " loses an event, because neither event is edge-triggered\n"
                    " and neither is acknowledged until it is handled.\n");

    zx_console_puts("\n  checks failed: ");
    zx_console_putdec(zx_probe_failures());
    zx_console_puts("\n");

    if (zx_probe_failures() == 0U)
    {
        zx_console_puts("\nZONEX RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        zx_console_puts("\nZONEX RESULT: FAILED\n");
    }

    zx_console_exit(zx_probe_failures());
}
