/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/
// Some portions generated by Claude Code (Opus 5).

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_fault.h                                           PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Fault decoding and reporting: reading HSR.EC to classify an         */
/*    exception taken to EL2, and reporting a stage-2 access violation    */
/*    with the faulting address from HPFAR.                               */
/*                                                                        */
/*    Every exception routed to EL2 from EL0/EL1 arrives at one vector,   */
/*    HVBAR + 0x14, so decoding HSR.EC is not an optimisation -- it is    */
/*    the only way to know what happened.  Two classes must be reported   */
/*    differently and never conflated: EC 0x24 is a data abort ROUTED to  */
/*    Hyp, which is a guest violating its partition and the event the     */
/*    Phase-0 demonstrator exists to show; EC 0x25 is a data abort TAKEN  */
/*    FROM Hyp, which is a ZoneX bug.                                     */
/*                                                                        */
/*    Nothing here touches a register.  The port reads HSR, HPFAR, HDFAR, */
/*    HIFAR, ELR_hyp and SPSR_hyp into a zx_fault_record_t and hands it   */
/*    over; everything below is arithmetic on those words, which is what  */
/*    lets the host suite exercise the decode without a model or a board. */
/*                                                                        */
/*    Encodings are from docs/armv8r-el2-reference.md, which is the       */
/*    authority.  Table 3-88 of the Cortex-R52 TRM (100026_0103_00_en) is */
/*    the source for the exception classes.                               */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_FAULT_H
#define ZX_FAULT_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************/
/*                        HSR layout and field access                     */
/**************************************************************************/

#define ZX_HSR_EC_SHIFT             26U
#define ZX_HSR_EC_MASK              0x3FU
#define ZX_HSR_IL_MASK              0x02000000U
#define ZX_HSR_ISS_MASK             0x01FFFFFFU

/* Exception classes, TRM Table 3-88.  The whole table is spelled out, not
   just the classes Phase 0 handles: an unexpected trap must be reported by
   NAME, and a numeric EC in a log is a value somebody then has to look up
   while the board is still on the bench.  */

#define ZX_EC_UNKNOWN               0x00U   /* unknown reason               */
#define ZX_EC_WFI_WFE               0x01U   /* trapped WFI or WFE           */
#define ZX_EC_MCR_MRC_CP15          0x03U   /* trapped MCR/MRC, coproc 15   */
#define ZX_EC_MCRR_MRRC_CP15        0x04U   /* trapped MCRR/MRRC, coproc 15 */
#define ZX_EC_MCR_MRC_CP14          0x05U   /* trapped MCR/MRC, coproc 14   */
#define ZX_EC_LDC_STC_CP14          0x06U   /* trapped LDC/STC, coproc 14   */
#define ZX_EC_SIMD_FP               0x07U   /* SIMD/FP access, from HCPTR   */
#define ZX_EC_VMRS                  0x08U   /* trapped VMRS, ID group trap  */
#define ZX_EC_MCRR_MRRC_CP14        0x0CU   /* trapped MCRR/MRRC, coproc 14 */
#define ZX_EC_ILLEGAL_STATE         0x0EU   /* illegal state exception      */
#define ZX_EC_SVC                   0x11U   /* SVC taken to Hyp mode        */
#define ZX_EC_HVC                   0x12U   /* HVC executed                 */
#define ZX_EC_PABT_ROUTED           0x20U   /* prefetch abort ROUTED to Hyp */
#define ZX_EC_PABT_FROM_HYP         0x21U   /* prefetch abort FROM Hyp      */
#define ZX_EC_PC_ALIGNMENT          0x22U   /* PC alignment fault           */
#define ZX_EC_DABT_ROUTED           0x24U   /* data abort ROUTED to Hyp     */
#define ZX_EC_DABT_FROM_HYP         0x25U   /* data abort FROM Hyp          */

/* Data-abort ISS fields.  The TRM defers the ISS layout to the Armv8-R
   architecture supplement, which was not available when this was written, so
   these are the AArch32 data-abort ISS positions common to Armv8 and they are
   MEASURED rather than trusted: zx_fault_report prints the raw ISS beside the
   decoded fields for exactly that reason.  See docs/armv8r-el2-reference.md.  */

#define ZX_ISS_DFSC_MASK            0x3FU       /* [5:0]  fault status code */

/* The two DFSC values a stage-2 MPU produces, both measured on the FVP and
   on S32Z280 silicon.  Telling them apart is the difference between two
   distinct claims: MISS says no enabled region covered the address, while
   PERMISSION says one did and its AP refused the access.  A check that
   accepted either would call a read-only region and an absent one the same
   thing, which is exactly the confusion a shared read-only granule has to
   be able to rule out.  */
#define ZX_DFSC_MPU_MISS            0x04U
#define ZX_DFSC_MPU_PERMISSION      0x0CU
#define ZX_ISS_WNR_MASK             0x00000040U /* [6]    1 = write         */
#define ZX_ISS_S1PTW_MASK           0x00000080U /* [7]    stage-1 walk      */
#define ZX_ISS_CM_MASK              0x00000100U /* [8]    cache maintenance */
#define ZX_ISS_EA_MASK              0x00000200U /* [9]    external abort    */
#define ZX_ISS_FNV_MASK             0x00000400U /* [10]   FAR not valid     */
#define ZX_ISS_ISV_MASK             0x01000000U /* [24]   ISS[23:14] valid  */

/* HVC immediate: HSR.ISS[15:0].  ZoneX gives every immediate it uses a name,
   because "HVC #1" in a trace says nothing about what was asked.

   ZX_HVC_NOP is the empty hypercall vector Phase 0 promises: counted at EL2
   and returned from, which proves the seam is live without giving a guest
   anything to call.  ZX_HVC_YIELD is how a Phase-0 test payload hands control
   back to EL2 on purpose, as opposed to being taken from it by a fault.  The
   distinction is what lets a run say "the payload survived its violation"
   instead of only "no fault was captured".

   ZX_HVC_PUTC is one character for the hypervisor to print, in r0.

   THE IMMEDIATE IS THE FUNCTION SELECTOR, and a register is not.  A general
   hypercall ABI usually puts a function id in a register so that the vector
   can dispatch through a table, and that is the right shape for one with
   dozens of calls.  This one has three, the vector already compares
   immediates to tell a yield from a transparent return, and the immediate
   costs a guest nothing: a console backend receives its character in r0
   under AAPCS and can issue the HVC with no register shuffling at all.  An
   id in r0 would mean moving the character to r1 and loading a constant into
   r0 on every character of a path that is already the slowest thing a guest
   does.  When a fourth call arrives this stays; when a fortieth does, the
   selector moves to a register and this comment is the record of why it was
   not there to begin with.  */

#define ZX_HSR_HVC_IMM_MASK         0x0000FFFFU
#define ZX_HVC_NOP                  0x0000U
#define ZX_HVC_YIELD                0x0001U
#define ZX_HVC_PUTC                 0x0002U

/**************************************************************************/
/*                                HPFAR                                   */
/**************************************************************************/

/* HPFAR IS NOT THE SAME REGISTER ON THE TWO ZONEX TARGETS.  Measured, on
   2 September 2026, by the stage-2 probe faulting on an address it chose:

     Armv8-R AEM FVP   HDFAR 0x000065C0  ->  HPFAR 0x00000060
                       which is FIPA[39:12] placed at HPFAR[31:4] -- the
                       shape TRM Figure 3-32 draws, and the A-profile shape.

     S32Z280-594EVB    HDFAR 0x31781200  ->  HPFAR 0x31781200
                       which is the faulting address itself with [3:0] RES0
                       -- the shape the TRM's own Table 3-69 row describes,
                       "Bits [31:4] of the faulting address".

   The TRM contradicts itself between a figure and the table beside it, and
   the model and the silicon each implement a different one of the two.  So
   there is NO PORTABLE DECODE OF HPFAR on this architecture, and a
   hypervisor that computed a faulting address from it would be right on one
   target and wrong on the other -- by a factor of 256, silently, producing a
   plausible address either way.

   HDFAR CARRIES THE FULL FAULTING VIRTUAL ADDRESS ON BOTH, and is what ZoneX
   uses.  The HPFAR functions below exist to REPORT the register and to say
   which reading a target implements, not to be relied on.  See
   docs/armv8r-el2-reference.md.

   Under the figure's reading there is a further consequence:

     * the faulting address is reported to 4 KB, NOT to the 64-byte MPU
       granule.  Armv8-R has no translation structure at either stage, so the
       4 KB quantum is inherited from the A-profile register layout rather than
       from anything in this architecture -- and it means HPFAR ALONE CANNOT
       SAY WHICH GRANULE FAULTED.  HDFAR carries the full virtual address and
       is what an off-by-one-granule region bug is caught with.

     * FIPA[39:32] does not fit in a 32-bit address.  On every ZoneX target
       those bits are zero; zx_fault_hpfar_high exists so that a target where
       they are not says so rather than reporting a silently truncated
       address.

   Both consequences belong to the figure's reading only.  Under the table
   row's reading -- which is what the S32Z280 does -- HPFAR resolves to 16
   bytes and carries no bits above 32 at all.  */

#define ZX_HPFAR_FIPA_SHIFT         4U
#define ZX_HPFAR_PAGE_SIZE          0x1000U

/**************************************************************************/
/*                            The fault record                            */
/**************************************************************************/

/* Statically allocated by the port and filled in by the trap handler before
   anything else runs.  The earliest evidence is the only trustworthy
   evidence: a handler that prints first and captures afterwards can lose the
   syndrome to its own console driver taking a second fault.

   zx_fault_captures counts every capture, NOT every fault.  A payload
   yielding through HVC #1 is captured too, deliberately: "the payload came
   back" is evidence, and a regression that can only report the ABSENCE of a
   fault cannot tell a working protection failure from a broken test.  The
   field is named for what it counts so that nobody reads a run's capture
   total as a fault total.  */

typedef struct zx_fault_record_struct
{
    uint32_t zx_fault_captures;     /* captures since reset -- see below    */
    uint32_t zx_fault_vector;       /* HVBAR offset of the vector taken     */
    uint32_t zx_fault_hsr;          /* HSR                                  */
    uint32_t zx_fault_hpfar;        /* HPFAR -- stage-2 faulting address    */
    uint32_t zx_fault_hdfar;        /* HDFAR -- data fault virtual address  */
    uint32_t zx_fault_hifar;        /* HIFAR -- instruction fault address   */
    uint32_t zx_fault_elr;          /* ELR_hyp -- where the guest was       */
    uint32_t zx_fault_spsr;         /* SPSR_hyp -- the mode it was in       */
} zx_fault_record_t;

/* The vector offsets in the EL2 table, as captured in zx_fault_vector.  A
   guest's fault arrives at 0x14 and ZoneX's own at 0x0C or 0x10, so the
   vector is an INDEPENDENT witness to what HSR.EC claims.  The report
   cross-checks the two, because a handler that trusts one register to
   describe an event has no way to notice that register being wrong.  */

#define ZX_VECTOR_RESET             0x00U
#define ZX_VECTOR_UNDEF             0x04U
#define ZX_VECTOR_SVC               0x08U
#define ZX_VECTOR_PABT_HYP          0x0CU
#define ZX_VECTOR_DABT_HYP          0x10U
#define ZX_VECTOR_HYP_TRAP          0x14U
#define ZX_VECTOR_IRQ               0x18U
#define ZX_VECTOR_FIQ               0x1CU

/* What kind of event a captured record describes.  The two that must never be
   conflated are the first two.  */

typedef enum zx_fault_class_enum
{
    ZX_FAULT_GUEST_VIOLATION = 0,   /* EC 0x24/0x20 -- a guest overstepped  */
    ZX_FAULT_HYPERVISOR_BUG,        /* EC 0x25/0x21 -- ZoneX faulted itself */
    ZX_FAULT_HYPERCALL,             /* EC 0x12 -- HVC, an intentional entry */
    ZX_FAULT_UNEXPECTED_TRAP        /* anything else routed to EL2          */
} zx_fault_class_t;

/**************************************************************************/
/*                              Decoding                                  */
/**************************************************************************/

ZX_NODISCARD uint32_t zx_fault_ec(uint32_t hsr);
ZX_NODISCARD uint32_t zx_fault_iss(uint32_t hsr);
ZX_NODISCARD zx_fault_class_t zx_fault_classify(uint32_t hsr);
ZX_NODISCARD const char *zx_fault_ec_name(uint32_t ec);
ZX_NODISCARD const char *zx_fault_class_name(zx_fault_class_t fault_class);
ZX_NODISCARD const char *zx_fault_vector_name(uint32_t vector);

/* True when the record's vector and HSR.EC tell the same story.  A guest
   fault must arrive at 0x14 and a hypervisor fault at 0x0C or 0x10; anything
   else means one of the two registers is not what it is documented to be, and
   that is worth a line of its own in the report.  */

ZX_NODISCARD uint32_t zx_fault_vector_agrees(uint32_t vector, uint32_t hsr);

/* True when the vector is one for which HSR carries a syndrome at all.
   Only +0x0C, +0x10 and +0x14 do.  Reset, undefined instruction, SVC from
   Hyp, IRQ and FIQ leave HSR holding whatever the last syndrome-bearing
   exception left there, so HSR read after one of those is STALE, not wrong.

   This distinction was measured rather than assumed: an ICH_VTR read with
   ICC_HSRE.SRE clear took an Undefined Instruction exception at EL2 on the
   Armv8-R AEM FVP, and HSR still held EC 0x03 from earlier -- which the
   vector-versus-EC cross-check duly reported as a disagreement.  It was
   right to flag it and wrong to imply one of the registers was broken.
   Without this function the report has to accuse the hardware of something
   the architecture never promised.  */

ZX_NODISCARD uint32_t zx_fault_vector_has_syndrome(uint32_t vector);

/* Data-abort ISS accessors.  Valid only when zx_fault_ec is a data abort;
   the caller checks, because a decoder that silently returns zero for the
   wrong class hides the mistake.  */

ZX_NODISCARD uint32_t zx_fault_dabt_dfsc(uint32_t hsr);
ZX_NODISCARD uint32_t zx_fault_dabt_is_write(uint32_t hsr);

/* HVC immediate, valid only when zx_fault_ec(hsr) == ZX_EC_HVC.  */

ZX_NODISCARD uint32_t zx_fault_hvc_immediate(uint32_t hsr);

/* The 4 KB page HPFAR names under the FIGURE's reading, as a 32-bit address,
   and the FIPA bits above 32 that a 32-bit address cannot carry.  */

ZX_NODISCARD uint32_t zx_fault_hpfar_page(uint32_t hpfar);
ZX_NODISCARD uint32_t zx_fault_hpfar_high(uint32_t hpfar);

/* The address HPFAR names under the TABLE ROW's reading: the faulting address
   itself, with its low four bits RES0.  */

ZX_NODISCARD uint32_t zx_fault_hpfar_as_address(uint32_t hpfar);

/* True when HPFAR and HDFAR agree under each reading, respectively.  */

ZX_NODISCARD uint32_t zx_fault_hpfar_matches_hdfar(uint32_t hpfar,
                                                   uint32_t hdfar);
ZX_NODISCARD uint32_t zx_fault_hpfar_matches_as_address(uint32_t hpfar,
                                                        uint32_t hdfar);

/* Which reading this target implements, decided by comparing HPFAR against a
   faulting address the caller already knows.

   THE TWO ZONEX TARGETS DISAGREE, and that is a measured fact rather than a
   worry.  See the HPFAR note above and docs/armv8r-el2-reference.md.  */

typedef enum zx_hpfar_reading_enum
{
    ZX_HPFAR_UNRECOGNISED = 0,  /* neither reading explains the value        */
    ZX_HPFAR_AS_FIPA,           /* FIPA[39:12] in HPFAR[31:4] -- the figure  */
    ZX_HPFAR_AS_ADDRESS,        /* the address itself, [3:0] RES0 -- the row  */
    ZX_HPFAR_AMBIGUOUS          /* both fit; this address cannot tell them   */
                                /* apart, so measure with another one        */
} zx_hpfar_reading_t;

ZX_NODISCARD zx_hpfar_reading_t zx_fault_hpfar_reading(uint32_t hpfar,
                                                       uint32_t hdfar);
ZX_NODISCARD const char *zx_fault_hpfar_reading_name(
    zx_hpfar_reading_t reading);

/**************************************************************************/
/*                              Reporting                                 */
/**************************************************************************/

void zx_fault_record_reset(zx_fault_record_t *record_ptr);

/* Print the record.  Prints HPFAR raw AND decoded, next to HDFAR, so that a
   reader can check the decode rather than take it on trust.  */

void zx_fault_report(const zx_fault_record_t *record_ptr);

#ifdef __cplusplus
}
#endif

#endif /* ZX_FAULT_H */
