/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_fault_log.h                                       PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    MANY faults, kept, attributed and searchable -- as against the      */
/*    single zx_fault_record_t, which holds the LAST capture.             */
/*                                                                        */
/*    The single record is right for a hypervisor whose policy is to stop */
/*    on the first violation, and that is still the shipping policy.  It  */
/*    is not enough for a regression that has to show a whole matrix of   */
/*    violations detected, because each one overwrites the evidence of    */
/*    the last -- so a sweep of twelve cases could only ever report the   */
/*    twelfth.                                                            */
/*                                                                        */
/*  WHY IT KEEPS THE FIRST ENTRIES AND NOT THE LAST                       */
/*                                                                        */
/*    A ring buffer is the reflex and it is wrong here.  A determinism    */
/*    run has a phase in which a partition faults on every iteration of   */
/*    its own loop -- thousands of times in one window -- and a ring      */
/*    would let that phase evict every entry the isolation matrix had     */
/*    carefully recorded before it.  The evidence would be destroyed by   */
/*    the part of the run that needs it least: repeated faults are        */
/*    interesting only as a COUNT, and their count is kept separately.    */
/*                                                                        */
/*    So the array fills once and then stops accepting entries, while     */
/*    the totals keep rising.  A reader gets "these are the first N       */
/*    distinct violations, and there were M in total", which is what both */
/*    halves of the regression actually claim.                            */
/*                                                                        */
/*  WHY ATTRIBUTION IS BY PARTITION AND ADDRESS                           */
/*                                                                        */
/*    Every case in the matrix aims at a DIFFERENT address, on purpose,   */
/*    so the address is the case's name and the partition is the          */
/*    direction.  A regression that counted faults without attributing    */
/*    them would pass on a run where one case faulted twelve times and    */
/*    eleven never ran -- which is exactly the failure mode a sweep       */
/*    invites, because a skipped case and a denied case both leave a      */
/*    guest that reported nothing.                                        */
/*                                                                        */
/*    Nothing here touches a register.  The port captures the words and   */
/*    hands them over, so the host suite exercises the whole of this file */
/*    without a model or a board.                                         */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_FAULT_LOG_H
#define ZX_FAULT_LOG_H

#include "zx_fault.h"
#include "zx_manifest.h"

#ifdef __cplusplus
extern "C" {
#endif

/* HOW MANY ENTRIES.  The isolation matrix is six violating cases in each
   direction, so twelve is the whole of what a two-partition sweep produces
   and thirty-two leaves room for a third partition's sweep plus a margin
   that makes a surprise VISIBLE rather than silently dropped.  It is a
   static array in a hypervisor with no allocator, so the number is a
   deliberate budget: 32 entries at 28 bytes is 896 bytes of .bss.  */

#define ZX_FAULT_LOG_ENTRIES        32U

/* How a partition was let go after its fault was recorded.  A log that did
   not carry this could not distinguish the shipping policy from the
   test-only one, and the whole point of recording a swept matrix is that
   the sweep only happens under the second.  */

#define ZX_FAULT_RESUMED_STOPPED    0U  /* halt: the partition was stopped */
#define ZX_FAULT_RESUMED_SKIPPED    1U  /* continue: past the instruction  */
#define ZX_FAULT_RESUMED_REDIRECTED 2U  /* continue: to a guest-named PC   */

typedef struct zx_fault_log_entry_struct
{
    uint32_t    zx_log_hsr;         /* HSR, so EC and DFSC are recoverable  */
    uint32_t    zx_log_hdfar;       /* the data-abort virtual address       */
    uint32_t    zx_log_hifar;       /* the prefetch-abort virtual address   */
    uint32_t    zx_log_elr;         /* where the partition was              */
    uint32_t    zx_log_spsr;        /* and in what mode, with what masks    */
    UINT        zx_log_partition;   /* whose window it happened in          */
    uint32_t    zx_log_resumed;     /* ZX_FAULT_RESUMED_*                   */
} ZX_FAULT_LOG_ENTRY;

typedef struct zx_fault_log_struct
{
    ZX_FAULT_LOG_ENTRY  zx_log_entries[ZX_FAULT_LOG_ENTRIES];

    /* KEPT and TOTAL are different numbers and both are printed.  A run
       where they differ is a run whose array filled, which is information
       rather than an error -- but a report showing only one of them would
       let a reader believe the log was complete.  */

    uint32_t            zx_log_kept;
    uint32_t            zx_log_total;
    uint32_t            zx_log_dropped;

    /* Per partition, because "which partition faulted, how often" is the
       determinism claim's own number: a phase in which one partition
       faults on every iteration has to be shown to have happened at all
       before "and its neighbour's period did not move" means anything.  */

    uint32_t            zx_log_partition_total[ZX_MAX_PARTITIONS];
} ZX_FAULT_LOG;

/**************************************************************************/
/*                              Recording                                 */
/**************************************************************************/

void zx_fault_log_reset(ZX_FAULT_LOG *log_ptr);

/* Add one capture. `partition` is the index of the partition that was
   running; it is recorded even when it is out of range, because a fault
   attributed to nobody is a fact worth keeping rather than one to discard.
   Only the per-partition total is guarded, since that one indexes.  */

void zx_fault_log_add(ZX_FAULT_LOG *log_ptr, UINT partition,
                      const zx_fault_record_t *record_ptr,
                      uint32_t resumed);

/**************************************************************************/
/*                              Reading back                              */
/**************************************************************************/

/* The virtual address an entry faulted on: HDFAR for a data abort, HIFAR
   for a prefetch abort.  A single accessor because a caller asking "did
   this address fault" must not have to know which kind of access it was --
   and because reading HDFAR after a prefetch abort returns whatever the
   last data abort left there, which is stale rather than wrong and reads
   like a plausible answer.  */

ZX_NODISCARD uint32_t zx_fault_log_entry_address(
    const ZX_FAULT_LOG_ENTRY *entry_ptr);

/* The first entry in which `partition` faulted on `address`, or a null
   pointer.  This is how one row of the isolation matrix is judged: the case
   aimed at that address, in that direction, and the fault that came back
   names both.  */

ZX_NODISCARD const ZX_FAULT_LOG_ENTRY *zx_fault_log_find(
    const ZX_FAULT_LOG *log_ptr, UINT partition, uint32_t address);

/* How many KEPT entries match, which is not the same question. A case that
   faulted twice is a case whose partition was resumed onto the same
   instruction, and that is a defect in the continue path rather than in
   isolation.  */

ZX_NODISCARD uint32_t zx_fault_log_count_at(const ZX_FAULT_LOG *log_ptr,
                                            UINT partition,
                                            uint32_t address);

ZX_NODISCARD uint32_t zx_fault_log_partition_total(
    const ZX_FAULT_LOG *log_ptr, UINT partition);

/* True when every kept entry is a GUEST violation -- EC 0x24 or 0x20 -- and
   none is ZoneX faulting on its own access.  A matrix that had provoked one
   hypervisor fault among its twelve guest ones would otherwise report
   twelve violations detected and hide the one that mattered.  */

ZX_NODISCARD uint32_t zx_fault_log_all_guest_violations(
    const ZX_FAULT_LOG *log_ptr);

/**************************************************************************/
/*                              Reporting                                 */
/**************************************************************************/

void zx_fault_log_report(const ZX_FAULT_LOG *log_ptr);

ZX_NODISCARD const char *zx_fault_resumed_name(uint32_t resumed);

#ifdef __cplusplus
}
#endif

#endif /* ZX_FAULT_LOG_H */
