/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_fault.h                                           PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Fault decoding and reporting: reading HSR.EC to classify an         */
/*    exception taken to EL2, and reporting a stage-2 access violation    */
/*    with the faulting address from HPFAR.                               */
/*                                                                        */
/*    Every exception routed to EL2 from EL0/EL1 arrives at one vector,   */
/*    HVBAR + 0x14, so decoding HSR.EC is not an optimisation -- it is    */
/*    the only way to know what happened.  Two classes must be reported   */
/*    differently and never conflated: EC 0x24 is a data abort ROUTED to  */
/*    Hyp, which is a guest violating its partition and the event the     */
/*    Phase-0 demonstrator exists to show; EC 0x25 is a data abort TAKEN  */
/*    FROM Hyp, which is a ZoneX bug.                                     */
/*                                                                        */
/*  STATUS                                                                */
/*                                                                        */
/*    Declared empty.  The first stage-2 fault is decoded by the EL2      */
/*    bring-up work.  The EC values are tabulated in                      */
/*    docs/armv8r-el2-reference.md.                                       */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_FAULT_H
#define ZX_FAULT_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* ZX_FAULT_H */
