/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_guest_console.h                                   PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The hypervisor end of the guest console: one character at a time,   */
/*    tagged with the partition that is running.                          */
/*                                                                        */
/*  WHY THE HYPERVISOR OWNS THE CONSOLE                                   */
/*                                                                        */
/*    There is one UART and there will be more than one partition.  Three */
/*    ways to divide it were available and only one of them survives the  */
/*    arrival of the second partition:                                    */
/*                                                                        */
/*      * give the device to one partition and leave the other mute --    */
/*        cheapest, and it makes the demonstrator show half of what it    */
/*        is for;                                                         */
/*      * map the device into both partitions, which is honest about      */
/*        there being no device isolation in Phase 0 and puts MMIO into   */
/*        every partition's region set, lengthening the isolation claim   */
/*        the whole component exists to make;                             */
/*      * have the guest ASK, and let the hypervisor write.               */
/*                                                                        */
/*    The third is what this file is.  It costs a trap per character,     */
/*    which is a real cost and is stated rather than hidden: a partition  */
/*    that is printing is not a partition whose timing should be          */
/*    measured, and a later phase that needs both will buffer per         */
/*    partition and flush at a window boundary.  What it buys is that the */
/*    device stays out of every partition's region set, that the          */
/*    hypercall seam is exercised by something real rather than by a      */
/*    counter, and that two partitions' output can be read side by side.  */
/*                                                                        */
/*  WHY THE TAG IS APPLIED HERE AND NOT BY THE GUEST                      */
/*                                                                        */
/*    Because a guest must not be able to lie about who it is.  A         */
/*    partition that prefixed its own lines could claim to be another     */
/*    one, and every line of a captured log would then be evidence of     */
/*    nothing.  The identity comes from the partition the hypervisor      */
/*    SCHEDULED, which is the only party that knows it.                   */
/*                                                                        */
/*    This is a small thing that a safety reviewer notices, and it is     */
/*    free: the hypervisor is already in the loop for every character.    */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_GUEST_CONSOLE_H
#define ZX_GUEST_CONSOLE_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Say which partition is about to run, so that its output can be tagged.
   Called by whatever drives the partition, immediately before the transfer
   to EL1 -- not when the manifest is read, because what matters is which
   partition is CURRENT and not which ones exist.

   name_ptr may be a null pointer; the tag then carries the id alone.  The
   id is what identifies a partition in a manifest, and a name is a
   convenience for a reader.  */

void zx_guest_console_attach(UINT partition_id, const CHAR *name_ptr);

/* Terminate a partial line and stop tagging.  Called after the partition has
   given control back, however it gave it back.

   Terminating the line matters more than it looks.  A guest that printed
   without a trailing newline -- because it faulted mid-line, which is
   exactly when a log is read most carefully -- would otherwise have the
   hypervisor's next line appended to its own, and the reader would attribute
   a hypervisor message to the guest.  */

void zx_guest_console_detach(void);

/* One character from the running guest.  Called from the hypercall path, so
   it must be safe to call with a guest's registers still live and must not
   itself be able to fault: it touches no guest memory at all -- the
   character arrives in a register.  */

void zx_guest_console_putc(CHAR character);

/* How many characters the guests have asked to print since the last reset.
   Exists so that "the guest really did print through the hypervisor" is a
   number a regression can assert on rather than a shape somebody eyeballs
   in a log.  */

ZX_NODISCARD UINT zx_guest_console_characters(void);

/* How many characters arrived while NO partition was attached.  Never zero
   for an innocent reason: an HVC console call reaching EL2 with no current
   partition means the run loop and the console disagree about what is
   executing, and that is a hypervisor bug rather than a guest one.  Counted
   separately so it cannot hide inside the total.  */

ZX_NODISCARD UINT zx_guest_console_orphans(void);

void zx_guest_console_reset(void);

#ifdef __cplusplus
}
#endif

#endif /* ZX_GUEST_CONSOLE_H */
