/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_manifest.h                                        PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The partition manifest: the static, build-time declaration of how   */
/*    many partitions exist, which memory each one owns, and how much     */
/*    time each one is given.  A ZoneX system is entirely described by    */
/*    its manifest; there is no dynamic partition creation in Phase 0.    */
/*                                                                        */
/*    The manifest is architecture-independent by construction, which is  */
/*    what makes it the part of ZoneX the host test suite can validate    */
/*    without a model or a board (docs/decisions.md D11).                 */
/*                                                                        */
/*  STATUS                                                                */
/*                                                                        */
/*    Declared empty.  The manifest types and the validator arrive        */
/*    together, and the host suite under test/host grows with them.       */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_MANIFEST_H
#define ZX_MANIFEST_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* ZX_MANIFEST_H */
