/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_mm.h                                              PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Memory management: turning a validated manifest into stage-2 MPU    */
/*    region programming, and switching the enabled region set as         */
/*    partitions are scheduled.                                           */
/*                                                                        */
/*    "Memory management" here does not mean paging.  Armv8-R has no page */
/*    tables at either stage of translation; stage 2 is a region-based    */
/*    MPU with a 64-byte granule and no region priority, so two enabled   */
/*    regions covering one address is CONSTRAINED UNPREDICTABLE and       */
/*    aborts on the S32Z280.  A hypervisor cannot map everything and then */
/*    override parts of it -- the regions must be disjoint by             */
/*    construction, which is a property the manifest validator enforces.  */
/*                                                                        */
/*  STATUS                                                                */
/*                                                                        */
/*    Declared empty.  The EL2 bring-up work programs the first region by */
/*    hand; driving the programming from the manifest comes after that.   */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_MM_H
#define ZX_MM_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* ZX_MM_H */
