/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_partition.h                                       PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The partition: a guest's identity, its lifecycle state, and the     */
/*    control block the hypervisor keeps for it.  A partition owns EL1    */
/*    and EL0 execution for the whole of its time window, and owns        */
/*    nothing outside it.                                                 */
/*                                                                        */
/*    Isolation between partitions comes from WHICH stage-2 regions are   */
/*    enabled while a partition runs, never from the permission bits.     */
/*    Armv8-R offers no HPRBAR.AP encoding that grants EL0/EL1 access     */
/*    while denying EL2, so a partition's memory is always reachable from */
/*    the hypervisor.  See docs/decisions.md D3 and the AP table in       */
/*    docs/armv8r-el2-reference.md.                                       */
/*                                                                        */
/*  STATUS                                                                */
/*                                                                        */
/*    Declared empty.  The control block is defined alongside the         */
/*    manifest, and the first guest partition boots into it after that.   */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_PARTITION_H
#define ZX_PARTITION_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* ZX_PARTITION_H */
