/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_schedule.h                                        PORTABLE C     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Time partitioning: the fixed, cyclic window schedule that decides   */
/*    which partition owns the core, and the hypervisor-timer tick that   */
/*    ends each window.                                                   */
/*                                                                        */
/*    Guests read time through the VIRTUAL timer, with a per-partition    */
/*    CNTVOFF, so that a descheduled partition's clock is frozen rather   */
/*    than merely unread.  The hypervisor keeps the hypervisor timer for  */
/*    itself.  See docs/decisions.md D7: leaving guests on the physical   */
/*    timer is simpler and undermines the determinism claim, which is the */
/*    point of the demonstrator.                                          */
/*                                                                        */
/*  STATUS                                                                */
/*                                                                        */
/*    Declared empty.  The second partition brings with it the first      */
/*    schedule worth the name; one partition needs no scheduler.          */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_SCHEDULE_H
#define ZX_SCHEDULE_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* ZX_SCHEDULE_H */
