#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Fail the build if A-profile or RISC-V terminology has leaked into ZoneX.
#
# This is not pedantry.  ZoneX targets Armv8-R AArch32, where BOTH stages of
# address control are region-based MPUs and there are no page tables anywhere.
# The failure mode this guards against is a real one and it is cheap to fall
# into: a contributor -- or a model -- reaches for the A-profile spelling of a
# register, or shapes stage 2 like a KVM/Xen translation table, and the result
# reads plausibly, compiles on a host, and is wrong about the hardware.
# Terminology bleed is the single easiest way to get this architecture wrong,
# so it is checked mechanically rather than left to review.
#
# The names below are wrong BY CONSTRUCTION for this target:
#
#   *_EL2, *_EL1, *_EL0   AArch64 system-register spellings.  The R52 is
#                         AArch32-only; the Hyp-bank names are HVBAR, HCR,
#                         HSCTLR, HSR, HMAIR0/1 and so on.
#   DAIF, DAIFSet, ...    AArch64 interrupt-mask spellings.  AArch32 masks
#                         live in CPSR.
#   VTTBR, VTCR, TTBR     Translation-table base and control registers.  There
#                         is no translation table at either stage here.
#   MAIR_EL2              The AArch64 spelling of HMAIR0/HMAIR1.
#   NAPOT, PMP            RISC-V physical-memory-protection vocabulary.
#   page table            The concept itself.
#
# A line that must name one of these -- the reference sheet does, to say they
# are wrong -- carries the marker "zx-terminology-allow" and is skipped.  The
# marker is deliberately ugly so that using it is a visible decision.

set -euo pipefail

readonly ROOT="$(cd "$(dirname "$(realpath "$0")")/.." && pwd)"
readonly MARKER='zx-terminology-allow'

# Word boundaries matter here.  "MAIR_EL2" must be caught while "HMAIR0" must
# not, and a bare "PMP" must be caught while "PMPU" -- were anything ever named
# that -- must not.
#
# The _EL<n> rule carries an exception, and it is not a loophole.  What is
# forbidden is an AArch64 SYSTEM REGISTER spelling: MAIR_EL2, SCTLR_EL2,
# HCR_EL2.  Suite build-option names end the same way and are perfectly
# legitimate -- TX_R52_BOOT_AT_EL1 is the real ThreadX CMake option that builds
# a guest starting at EL1, and the guest work has to name it repeatedly.  A
# system
# register never carries a component prefix, so requiring the absence of one is
# enough to tell them apart.
#
# This needs grep -P for the negative lookahead.  GNU grep has it; a build
# environment without it should fail loudly rather than silently checking
# nothing, which is why the invocation below does not fall back to -E.
readonly PROJECT_PREFIXES='TX|ZX|NX|FX|UX|GX|LX'
readonly PATTERN="\\b(?!(?:${PROJECT_PREFIXES})_)[A-Z][A-Z0-9_]*_EL[0-3]\\b|\\bDAIF[A-Za-z]*\\b|\\bVTTBR[A-Z0-9_]*\\b|\\bVTCR[A-Z0-9_]*\\b|\\bTTBR[0-9A-Z_]*\\b|\\bNAPOT\\b|\\bPMP\\b|\\bpage[ -]tables?\\b"

cd "${ROOT}"

# Tracked files only.  A build tree full of toolchain headers is not ZoneX's
# terminology to police, and scanning one would make this check depend on
# whether somebody had built first.
#
# This script is excluded by name: it has to spell every forbidden term in
# order to look for it.
findings="$(git ls-files -z \
    | grep -zZv '^scripts/check_terminology\.sh$' \
    | xargs -0 grep -nPI "${PATTERN}" 2>/dev/null \
    | grep -v "${MARKER}" || true)"

if [ -n "${findings}" ]; then
    echo "ZoneX terminology check FAILED." >&2
    echo "" >&2
    echo "These lines use a register or concept name that does not exist on" >&2
    echo "Armv8-R AArch32.  See platform/cortex_r52/inc/zx_port.h and" >&2
    echo "docs/armv8r-el2-reference.md for the correct spellings." >&2
    echo "" >&2
    echo "${findings}" >&2
    exit 1
fi

echo "ZoneX terminology check passed."
