#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Fail the build if the repository cites something a reader of it cannot see.
#
# Three things, all of them ordinary hygiene and all of them easy to write by
# accident while the work is fresh:
#
#   1. A LOCAL ABSOLUTE PATH.  "/home/someone/toolchains/..." or "~/work/..."
#      means nothing to anybody else, and in a build script it means the
#      script only runs on one machine.  Paths belong in variables the reader
#      can set, which is why the board harness under examples/ takes its
#      locations from the environment and refuses to guess.
#
#   2. A NUMBERED STEP OF A DOCUMENT THAT IS NOT IN THE REPOSITORY.  A comment
#      saying "step 4 brings a real guest" is useless to a contributor who has
#      no step 4 to read, and it dates badly besides.  The FACT such a comment
#      carries is almost always worth keeping -- say "a real guest comes
#      later", and the sentence survives both the reader and the schedule.
#
#   3. AN AGENT-INSTRUCTION FILE.  No Eclipse ThreadX repository carries one.
#      Development-environment instructions are not project documentation, and
#      a committed one starts being treated as though it were.
#
# Deliberately narrow.  It catches the shapes that have actually gone wrong
# rather than trying to be a general secret scanner, because a check that
# cries wolf gets bypassed and then catches nothing at all.
#
# A line that must contain one of these carries the marker
# "zx-references-allow" and is skipped.  As with the terminology check, the
# marker is ugly on purpose: using it should be a visible decision.

set -euo pipefail

readonly ROOT="$(cd "$(dirname "$(realpath "$0")")/.." && pwd)"
readonly MARKER='zx-references-allow'

cd "${ROOT}"

readonly FORBIDDEN_FILES='^(AGENTS|CLAUDE)\.md$|/(AGENTS|CLAUDE)\.md$'

# "~/" only when it opens a path, so that prose using a tilde is not caught.
# "step <n>" case-insensitively, because "Step 5" reads as naturally as
# "step 5" and both are the same mistake.
readonly PATTERN='(^|[^A-Za-z0-9_.-])(/home/[A-Za-z0-9._-]+|~/[A-Za-z0-9._-])|\bstep[ -][0-9]+\b'

status=0

# This script is excluded by name: it has to spell the patterns to look for
# them.  Tracked files only -- a build tree is not this repository's content.
findings="$(git ls-files -z \
    | grep -zZv '^scripts/check_references\.sh$' \
    | xargs -0 grep -nEiI "${PATTERN}" 2>/dev/null \
    | grep -v "${MARKER}" || true)"

if [ -n "${findings}" ]; then
    echo "ZoneX reference check FAILED." >&2
    echo "" >&2
    echo "These lines name a local path, or a numbered step of a document" >&2
    echo "that is not in this repository. Keep the fact and drop the" >&2
    echo "citation: a reader cannot follow either one." >&2
    echo "" >&2
    echo "${findings}" >&2
    status=1
fi

tracked_agent_files="$(git ls-files | grep -E "${FORBIDDEN_FILES}" || true)"

if [ -n "${tracked_agent_files}" ]; then
    echo "" >&2
    echo "ZoneX reference check FAILED: an agent-instruction file is" >&2
    echo "tracked. No Eclipse ThreadX repository carries one." >&2
    echo "" >&2
    echo "${tracked_agent_files}" >&2
    status=1
fi

if [ "${status}" -ne 0 ]; then
    exit 1
fi

echo "ZoneX reference check passed."
