#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Install the ZoneX build and test dependencies on Ubuntu.
#
# The retry and timeout handling below is copied from threadx's
# scripts/install.sh rather than written fresh, and the reason is worth keeping
# with it.  Everything here reaches the network, and on the hosted runner pool
# that is not dependable: apt-get update stalled seven times in a single day
# there, once for more than two hours, each time with the mirror returning
# nothing and the fallback going silent.  Nothing bounded a fetch and nothing
# retried one, so a mirror being down cost a whole run rather than a few
# seconds.
#
# Each command is wrapped in timeout rather than left to bound itself.  apt's
# own Acquire timeouts were tried there first and did not help: a run still sat
# inside a single apt-get update for nine and a half minutes without producing
# a line.  Whatever apt waits on is not something Acquire::http::Timeout
# covers.  timeout does not care where the wait is.
#
# The Acquire options are kept anyway, since they make a slow mirror give up
# sooner.  set -e is on -- threadx's copy has no set -e, which let a failed
# update be carried forward into an install from a stale index, and the run
# then failed later somewhere less obvious.

set -euo pipefail

APT_OPTIONS=(-o Acquire::Retries=3
             -o Acquire::http::Timeout=20
             -o Acquire::https::Timeout=20)

# Two minutes per attempt, killed outright if it ignores the first signal.
# Three attempts plus backoff bounds a command at about six and a half minutes.
#
# timeout goes under sudo, not over it, so that it signals apt itself.
# Signalling sudo instead risks the kill landing on sudo while apt carries on
# holding the dpkg lock, which would leave every retry failing for a different
# reason than the one being retried.
TIMEOUT=(timeout --kill-after=10 120)

retry() {
    local attempt
    for attempt in 1 2 3; do
        if "$@"; then
            return 0
        fi
        echo "install.sh: '$*' failed or timed out on attempt ${attempt}"
        sleep $((attempt * 10))
    done
    echo "install.sh: '$*' failed after 3 attempts"
    return 1
}

retry sudo "${TIMEOUT[@]}" apt-get "${APT_OPTIONS[@]}" update
retry sudo "${TIMEOUT[@]}" apt-get "${APT_OPTIONS[@]}" install -y \
    --no-install-recommends \
    build-essential \
    cmake \
    git \
    ninja-build \
    python3 \
    python3-pip

# gcovr is pinned exactly rather than floated.  The coverage percentage has to
# stay comparable between runs, and the denominator is a property of the tool
# as much as of the tree, so a tool that moves on its own makes every reported
# movement ambiguous.  It is moved by hand: this is a shell script, and no
# Dependabot ecosystem parses one.
#
# 8.6 is the version ThreadX pins, deliberately -- the two repositories report
# coverage against the same tool so the numbers can be compared.
retry "${TIMEOUT[@]}" python3 -m pip install --break-system-packages \
    --retries 3 --timeout 30 gcovr==8.6

# The Arm GNU Toolchain is NOT installed here.  It is fetched, checksum-checked
# and cached by the workflow that needs it, because a 500MB download does not
# belong in the step that installs six apt packages, and because CI and a
# developer machine want it in different places.  CONTRIBUTING.md names the
# pinned version; cmake/cortex_r52.cmake expects it under
# $HOME/toolchains/arm-gnu-toolchain-<version>-x86_64-arm-none-eabi.
