#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Run the ZoneX host unit-test target.  Pass "coverage" through to run.sh to
# produce a gcovr report as well.

set -euo pipefail

# "$@" replaces the default rather than following it, so that
# "scripts/test_host.sh coverage" reaches run.sh as "coverage" and not as
# "test coverage", which run.sh would silently ignore.
exec "$(dirname "$(realpath "$0")")/../test/host/run.sh" "${@:-test}"
