###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# CMake toolchain file for Arm Cortex-R52 (Armv8-R, AArch32) with the GNU
# toolchain.  Use it as:
#
#     cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=cmake/cortex_r52.cmake
#
# Derived from threadx's cmake/cortex_r52.cmake and folded into a single file
# rather than shared with it.  ZoneX and ThreadX are separate repositories with
# separate release trains; a shared toolchain file would have to be vendored or
# symlinked either way, and a copy that can diverge deliberately is easier to
# reason about than one that diverges by accident.

set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-r52)

# Read by the root CMakeLists.txt to select platform/<ZX_ARCH>.  It is a normal
# variable rather than a cache entry because a toolchain file is re-read on every
# configure, and because the root project must be able to fail loudly when no
# toolchain file was given at all.
set(ZX_ARCH      "cortex_r52")
set(ZX_TOOLCHAIN "gnu")

# Floating-point ABI.  Every Cortex-R52 implements at least a single-precision
# FPU -- GCC rejects "+nofp" for this core and offers only "+nofp.dp" -- so the
# soft-float baseline selects the soft *ABI* rather than removing the FPU.
#
# ZoneX itself uses no floating point at EL2 and does not care.  The option
# exists because the guest images built under examples/ do, and because a guest
# built hard-float cannot be linked against soft-float objects.
if(NOT DEFINED ZX_R52_FLOAT_ABI)
    set(ZX_R52_FLOAT_ABI "soft" CACHE STRING "R52 float ABI: soft | hard")
endif()
set_property(CACHE ZX_R52_FLOAT_ABI PROPERTY STRINGS soft hard)

set(ZX_MCPU_FLAGS "-marm -mcpu=cortex-r52")
if(ZX_R52_FLOAT_ABI STREQUAL "hard")
    set(ZX_VFP_FLAGS "-mfpu=fpv5-d16 -mfloat-abi=hard")
else()
    set(ZX_VFP_FLAGS "-mfloat-abi=soft")
endif()

set(CMAKE_C_COMPILER   arm-none-eabi-gcc)
set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
set(CMAKE_AR           arm-none-eabi-ar)
set(CMAKE_OBJCOPY      arm-none-eabi-objcopy)
set(CMAKE_OBJDUMP      arm-none-eabi-objdump)
set(CMAKE_SIZE         arm-none-eabi-size)

# Pin the reference cross toolchain (CONTRIBUTING.md, "Required tooling").
# Absolute paths are used deliberately so the build does not depend on PATH
# ordering.  Override with -DZX_ARM_TOOLCHAIN_PATH=<dir containing the binaries>
# to build with a different compiler.
if(NOT DEFINED ZX_ARM_TOOLCHAIN_PATH)
    set(ZX_ARM_TOOLCHAIN_PATH
        "$ENV{HOME}/toolchains/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi/bin")
endif()
if(EXISTS "${ZX_ARM_TOOLCHAIN_PATH}/arm-none-eabi-gcc")
    set(CMAKE_C_COMPILER   "${ZX_ARM_TOOLCHAIN_PATH}/arm-none-eabi-gcc")
    set(CMAKE_ASM_COMPILER "${ZX_ARM_TOOLCHAIN_PATH}/arm-none-eabi-gcc")
    set(CMAKE_AR           "${ZX_ARM_TOOLCHAIN_PATH}/arm-none-eabi-ar")
    set(CMAKE_OBJCOPY      "${ZX_ARM_TOOLCHAIN_PATH}/arm-none-eabi-objcopy")
    set(CMAKE_OBJDUMP      "${ZX_ARM_TOOLCHAIN_PATH}/arm-none-eabi-objdump")
    set(CMAKE_SIZE         "${ZX_ARM_TOOLCHAIN_PATH}/arm-none-eabi-size")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# The compiler check builds a static library rather than an executable, so that
# configuring does not need a linker script.  ZoneX has no linker script until
# the first image is produced.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# -std= is deliberately absent: the C standard is set once, in the root
# CMakeLists.txt, through CMAKE_C_STANDARD.  Spelling it here as well would let
# the two drift apart and the toolchain file would silently win.
set(CMAKE_C_FLAGS
    "${ZX_MCPU_FLAGS} ${ZX_VFP_FLAGS} --specs=nosys.specs -fdata-sections -ffunction-sections"
    CACHE INTERNAL "c compiler flags")
set(CMAKE_ASM_FLAGS
    "${ZX_MCPU_FLAGS} ${ZX_VFP_FLAGS} -x assembler-with-cpp"
    CACHE INTERNAL "asm compiler flags")
set(CMAKE_EXE_LINKER_FLAGS
    "${ZX_MCPU_FLAGS} ${ZX_VFP_FLAGS} -Wl,--gc-sections"
    CACHE INTERNAL "exe link flags")

set(CMAKE_C_FLAGS_DEBUG     "-Og -g -ggdb3" CACHE INTERNAL "c debug flags")
set(CMAKE_ASM_FLAGS_DEBUG   "-g -ggdb3"     CACHE INTERNAL "asm debug flags")
set(CMAKE_C_FLAGS_RELEASE   "-O2 -g"        CACHE INTERNAL "c release flags")
set(CMAKE_ASM_FLAGS_RELEASE "-g"            CACHE INTERNAL "asm release flags")
