###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# CMake toolchain file for Arm Cortex-R52 (Armv8-R, AArch32) with Arm Toolchain
# for Embedded, which is LLVM based and is the successor to Arm Compiler 6.
#
#     cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=cmake/cortex_r52_clang.cmake
#
# There is no separate clang port: this builds the same sources with a different
# compiler.  ZX_TOOLCHAIN therefore stays "gnu" -- it names the port directory,
# not the compiler.
#
# Why ZoneX bothers with a second toolchain at all: GNU as accepts several
# non-canonical assembly forms that LLVM's assembler rejects, and ZoneX will be
# mostly assembly at the point where that starts to matter.  Catching those one
# at a time as they are written is far cheaper than finding forty of them the
# first time somebody tries an LLVM build.

set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-r52)

set(ZX_ARCH      "cortex_r52")
set(ZX_TOOLCHAIN "gnu")

if(NOT DEFINED ZX_R52_FLOAT_ABI)
    set(ZX_R52_FLOAT_ABI "soft" CACHE STRING "R52 float ABI: soft | hard")
endif()
set_property(CACHE ZX_R52_FLOAT_ABI PROPERTY STRINGS soft hard)

# Tool names as found on PATH, which is what CI uses.
set(CMAKE_C_COMPILER   clang)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_AR           llvm-ar)
set(CMAKE_RANLIB       llvm-ranlib)
set(CMAKE_OBJCOPY      llvm-objcopy)
set(CMAKE_OBJDUMP      llvm-objdump)
set(CMAKE_SIZE         llvm-size)

# Then pin a specific install if one is present, as cmake/cortex_r52.cmake pins
# the GNU toolchain and for the same reason: a local build should not depend on
# PATH ordering.  Absent that directory this falls back to the names above
# rather than failing, so the file still works on a machine that keeps clang
# somewhere else.  Override with -DZX_ATFE_TOOLCHAIN_PATH=<dir containing clang>.
if(NOT DEFINED ZX_ATFE_TOOLCHAIN_PATH)
    set(ZX_ATFE_TOOLCHAIN_PATH "$ENV{HOME}/toolchains/ATfE-22.1.0-Linux-x86_64/bin")
endif()
if(EXISTS "${ZX_ATFE_TOOLCHAIN_PATH}/clang")
    set(CMAKE_C_COMPILER   "${ZX_ATFE_TOOLCHAIN_PATH}/clang")
    set(CMAKE_ASM_COMPILER "${ZX_ATFE_TOOLCHAIN_PATH}/clang")
    set(CMAKE_AR           "${ZX_ATFE_TOOLCHAIN_PATH}/llvm-ar")
    set(CMAKE_RANLIB       "${ZX_ATFE_TOOLCHAIN_PATH}/llvm-ranlib")
    set(CMAKE_OBJCOPY      "${ZX_ATFE_TOOLCHAIN_PATH}/llvm-objcopy")
    set(CMAKE_OBJDUMP      "${ZX_ATFE_TOOLCHAIN_PATH}/llvm-objdump")
    set(CMAKE_SIZE         "${ZX_ATFE_TOOLCHAIN_PATH}/llvm-size")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(ZX_MCPU_FLAGS "--target=arm-none-eabi -marm -mcpu=cortex-r52")
if(ZX_R52_FLOAT_ABI STREQUAL "hard")
    set(ZX_VFP_FLAGS "-mfpu=fpv5-d16 -mfloat-abi=hard")
else()
    set(ZX_VFP_FLAGS "-mfloat-abi=soft")
endif()

set(CMAKE_C_FLAGS
    "${ZX_MCPU_FLAGS} ${ZX_VFP_FLAGS} -fdata-sections -ffunction-sections"
    CACHE INTERNAL "c compiler flags")
set(CMAKE_ASM_FLAGS
    "${ZX_MCPU_FLAGS} ${ZX_VFP_FLAGS} -x assembler-with-cpp"
    CACHE INTERNAL "asm compiler flags")
set(CMAKE_EXE_LINKER_FLAGS
    "${ZX_MCPU_FLAGS} ${ZX_VFP_FLAGS} -fuse-ld=lld -Wl,--gc-sections"
    CACHE INTERNAL "exe link flags")

set(CMAKE_C_FLAGS_DEBUG     "-Og -g" CACHE INTERNAL "c debug flags")
set(CMAKE_ASM_FLAGS_DEBUG   "-g"     CACHE INTERNAL "asm debug flags")
set(CMAKE_C_FLAGS_RELEASE   "-O2 -g" CACHE INTERNAL "c release flags")
set(CMAKE_ASM_FLAGS_RELEASE "-g"     CACHE INTERNAL "asm release flags")
