###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# CMake toolchain file for the host build.
#
# The host build compiles the architecture-independent half of ZoneX -- the
# manifest, the partition tables, the scheduling logic -- and the unit tests
# under test/host that exercise it.  It links no assembly, programs no MPU and
# never reaches EL2; see docs/decisions.md D11 for what the host suite is
# expected to cover and what it deliberately is not.

set(CMAKE_SYSTEM_NAME      ${CMAKE_HOST_SYSTEM_NAME})
set(CMAKE_SYSTEM_PROCESSOR ${CMAKE_HOST_SYSTEM_PROCESSOR})

set(ZX_ARCH      "host")
set(ZX_TOOLCHAIN "gnu")

# Let the compiler be chosen on the command line or from the environment, for
# example -DCMAKE_C_COMPILER=gcc-14 or CC=gcc-14.  CMake reads a toolchain file
# before it consults CC, so setting this unconditionally would quietly override
# the environment and leave no way to build with anything but the
# distribution's default compiler.  (Same reasoning, and the same wording, as
# threadx's cmake/linux.cmake, where it was first needed.)
if(NOT DEFINED CMAKE_C_COMPILER)
    if(DEFINED ENV{CC})
        set(CMAKE_C_COMPILER $ENV{CC})
    else()
        set(CMAKE_C_COMPILER gcc)
    endif()
endif()

# -std= is deliberately absent here too; see the note in cortex_r52.cmake.
set(CMAKE_C_FLAGS         ""              CACHE INTERNAL "c compiler flags")
set(CMAKE_C_FLAGS_DEBUG   "-Og -g -ggdb3" CACHE INTERNAL "c debug flags")
set(CMAKE_C_FLAGS_RELEASE "-O2 -g"        CACHE INTERNAL "c release flags")
