###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# The strict warning set, as an INTERFACE library every ZoneX target links.
#
# This is upstream ThreadX's kernel warning set -- the one in
# threadx/test/tx/cmake/CMakeLists.txt -- plus -Wmissing-prototypes, which is
# the flag that found the MISRA Rule 8.4 findings in the Cortex-R52 port and
# Modules port work.  It is applied
# from the first commit rather than bolted on during the hardening step,
# because retrofitting a codebase to a warning set costs far more than building
# to one, and because ZoneX has a certification back end that will ask.
#
# Warnings become errors under the ci-strict configure preset, through CMake's
# own CMAKE_COMPILE_WARNING_AS_ERROR.  A developer build stays warning-tolerant
# so that a half-finished change can still be compiled and looked at.

add_library(zx_warnings INTERFACE)
add_library(zonex::warnings ALIAS zx_warnings)

target_compile_options(zx_warnings INTERFACE
    -Wall
    -Wextra
    -Wpedantic
    -Wunused
    -Wuninitialized
    -Wmissing-declarations
    -Wmissing-prototypes
    -Wconversion
    -Wpointer-arith
    -Waggregate-return
    -Wfloat-equal
)

# -Wlogical-op is a GNU extension.  Clang does not implement it: it has
# -Wlogical-op-parentheses, which is a different check, and rejects the GNU
# spelling as an unknown warning.  That is merely noisy until
# CMAKE_COMPILE_WARNING_AS_ERROR turns it into a failed build for every ZoneX
# source under the ATfE lane, so it is selected by compiler rather than
# spelled unconditionally.
target_compile_options(zx_warnings INTERFACE
    $<$<C_COMPILER_ID:GNU>:-Wlogical-op>
)
