###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# The strict warning set, as an INTERFACE library every ZoneX target links.
#
# This is upstream ThreadX's kernel warning set -- the one in
# threadx/test/tx/cmake/CMakeLists.txt -- plus -Wmissing-prototypes, which is
# the flag that found the MISRA Rule 8.4 findings in the Cortex-R52 port and
# Modules port work.  It is applied
# from the first commit rather than bolted on during the hardening step,
# because retrofitting a codebase to a warning set costs far more than building
# to one, and because ZoneX has a certification back end that will ask.
#
# Warnings become errors under the ci-strict configure preset, through CMake's
# own CMAKE_COMPILE_WARNING_AS_ERROR.  A developer build stays warning-tolerant
# so that a half-finished change can still be compiled and looked at.
#
# THE FLAGS ARE A VARIABLE AS WELL AS A TARGET, and the second form is not
# redundant.  ZoneX's guest support -- examples/guest_common -- is ZoneX's own
# code that is compiled into a THREADX image, by a separate CMake invocation
# with ThreadX's toolchain file, so it cannot see this project's targets at
# all.  Restating the list over there would be a second source of truth that
# agrees until the day it does not; including this file and reading the
# variable is one.
#
# It is a variable and not just a target for exactly one consumer, and that
# consumer applies it PER SOURCE FILE rather than per target.  The reason is in
# examples/*/guest_a/CMakeLists.txt: the guest executable also contains two
# files from ports/cortex_r52, and ZoneX does not get to decide how the port is
# compiled.

set(ZX_WARNING_FLAGS
    -Wall
    -Wextra
    -Wpedantic
    -Wunused
    -Wuninitialized
    -Wmissing-declarations
    -Wmissing-prototypes
    -Wconversion
    -Wpointer-arith
    -Waggregate-return
    -Wfloat-equal
)

add_library(zx_warnings INTERFACE)
add_library(zonex::warnings ALIAS zx_warnings)

target_compile_options(zx_warnings INTERFACE ${ZX_WARNING_FLAGS})

# -Wlogical-op is a GNU extension.  Clang does not implement it: it has
# -Wlogical-op-parentheses, which is a different check, and rejects the GNU
# spelling as an unknown warning.  That is merely noisy until
# CMAKE_COMPILE_WARNING_AS_ERROR turns it into a failed build for every ZoneX
# source under the ATfE lane, so it is selected by compiler rather than
# spelled unconditionally.
target_compile_options(zx_warnings INTERFACE
    $<$<C_COMPILER_ID:GNU>:-Wlogical-op>
)
