/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/
// Some portions generated by Claude Code (Opus 5).

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_port.h                                            Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The Cortex-R52 port interface: everything ZoneX needs that is       */
/*    specific to Armv8-R AArch32 at EL2.                                 */
/*                                                                        */
/*    This header is included from BOTH C and preprocessed assembly, so   */
/*    that a bit position cannot be spelled one way in zx_el2_entry.S and */
/*    another way in zx_stage2_mpu.c.  Everything above the __ASSEMBLER__ */
/*    guard is therefore preprocessor-only; the ZX_BIT and ZX_C32 macros  */
/*    exist so that the same definition can carry a U suffix in C, where  */
/*    -Wconversion is in force, and no suffix in assembly, where the      */
/*    assembler would reject it.                                          */
/*                                                                        */
/*  TERMINOLOGY -- READ THIS BEFORE ADDING ANYTHING BELOW                 */
/*                                                                        */
/*    The Cortex-R52 is AArch32-only and Armv8-R has NO PAGE TABLES at    */
/*    either stage of translation.  Both stages are region-based MPUs     */
/*    (PMSAv8-R).  The registers this port uses are therefore the         */
/*    AArch32 Hyp-mode ones, reached through MRC/MCR p15, 4, <Rt>, ...    */
/*    (opc1 = 4 is the Hyp bank; opc1 = 5 reaches HPRBAR16 and above):    */
/*                                                                        */
/*      HVBAR    EL2 vector base            HSR      syndrome             */
/*      HCR      hypervisor configuration   HDFAR    data fault address   */
/*      HSCTLR   EL2 system control         HIFAR    instruction fault    */
/*      HMPUIR   EL2 region count           HPFAR    stage-2 fault addr   */
/*      HPRSELR  region select              HMAIR0   memory attributes    */
/*      HPRENR   region enables             HMAIR1   memory attributes    */
/*      HPRBAR   region base                CNTHCTL  timer access control */
/*      HPRLAR   region limit               CNTVOFF  virtual time offset  */
/*      ICC_HSRE GICv3 sysreg interface      ICH_VTR  List Register count  */
/*                                                                        */
/*    A second family of names is WRONG BY CONSTRUCTION for this target   */
/*    and must not appear anywhere in this repository: the AArch64        */
/*    system-register spellings, the translation-table registers, and the */
/*    RISC-V memory-protection vocabulary.  Using one of them means the   */
/*    code was written against the wrong architecture, and the result     */
/*    reads plausibly while being wrong about the hardware.               */
/*                                                                        */
/*    scripts/check_terminology.sh holds the exact list and enforces it   */
/*    in CI.  It is the single place that spells those names, so that     */
/*    the list cannot drift away from what is actually checked.           */
/*                                                                        */
/*    The verified encodings, field layouts and exception-class values    */
/*    are in docs/armv8r-el2-reference.md, which is the authority.  Take  */
/*    them from there rather than from memory or from an A-profile        */
/*    hypervisor; the AP field in particular does NOT mean at EL2 what it */
/*    means at EL1, which is why the AP encodings below are named for    */
/*    what they grant rather than numbered.                               */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_PORT_H
#define ZX_PORT_H

/* One definition, two languages.  The assembler tolerates no integer suffix
   and C under -Wconversion wants one on every constant that reaches a
   uint32_t, so the suffix is applied by macro rather than by writing each
   constant twice.  ZX_C32 pastes the suffix, so its argument must be a single
   literal token; a composite value is written as (ZX_C32(0x3) << 3).  */

#ifdef __ASSEMBLER__
#  define ZX_BIT(n)     (1 << (n))
#  define ZX_C32(v)     v
#else
#  define ZX_BIT(n)     (1U << (n))
#  define ZX_C32(v)     v ## U
#endif

/**************************************************************************/
/*                      AArch32 processor modes and masks                 */
/**************************************************************************/

#define ZX_MODE_USR             ZX_C32(0x10)
#define ZX_MODE_FIQ             ZX_C32(0x11)
#define ZX_MODE_IRQ             ZX_C32(0x12)
#define ZX_MODE_SVC             ZX_C32(0x13)    /* an EL1 mode              */
#define ZX_MODE_ABT             ZX_C32(0x17)
#define ZX_MODE_HYP             ZX_C32(0x1A)    /* EL2                      */
#define ZX_MODE_UND             ZX_C32(0x1B)
#define ZX_MODE_SYS             ZX_C32(0x1F)
#define ZX_MODE_MASK            ZX_C32(0x1F)

#define ZX_PSR_A                ZX_BIT(8)       /* asynchronous abort mask  */
#define ZX_PSR_I                ZX_BIT(7)       /* IRQ mask                 */
#define ZX_PSR_F                ZX_BIT(6)       /* FIQ mask                 */

/**************************************************************************/
/*                                  HCR                                   */
/**************************************************************************/

#define ZX_HCR_VM               ZX_BIT(0)       /* stage-2 MPU enable       */
#define ZX_HCR_AMO              ZX_BIT(3)       /* route aborts to EL2      */
#define ZX_HCR_IMO              ZX_BIT(4)       /* route IRQ to EL2         */
#define ZX_HCR_FMO              ZX_BIT(5)       /* route FIQ to EL2         */
#define ZX_HCR_DC               ZX_BIT(12)      /* default cacheable        */
#define ZX_HCR_TGE              ZX_BIT(27)      /* trap general exceptions  */
#define ZX_HCR_HCD              ZX_BIT(29)      /* HVC disable -- keep CLEAR */

/**************************************************************************/
/*                                HSCTLR                                  */
/**************************************************************************/

#define ZX_HSCTLR_M             ZX_BIT(0)       /* EL2 MPU enable           */
#define ZX_HSCTLR_A             ZX_BIT(1)       /* alignment check          */
#define ZX_HSCTLR_C             ZX_BIT(2)       /* data cache              */
#define ZX_HSCTLR_I             ZX_BIT(12)      /* instruction cache        */
#define ZX_HSCTLR_BR            ZX_BIT(17)      /* background region enable */
#define ZX_HSCTLR_TE            ZX_BIT(30)      /* Thumb exception entry    */

/**************************************************************************/
/*                                SCTLR                                   */
/**************************************************************************/

/* Needed at EL2 because ZoneX must leave the EL1 MPU in a known state before
   handing a payload the machine.  Stage-2 bring-up leaves SCTLR.M CLEAR:
   with stage 1 disabled the payload runs on the EL1 background map and the
   only thing under test is stage 2.  One variable at a time.  */

#define ZX_SCTLR_M              ZX_BIT(0)
#define ZX_SCTLR_C              ZX_BIT(2)
#define ZX_SCTLR_I              ZX_BIT(12)
#define ZX_SCTLR_BR             ZX_BIT(17)
#define ZX_SCTLR_TE             ZX_BIT(30)

/**************************************************************************/
/*                          Region descriptor fields                      */
/**************************************************************************/

/* HPRBAR: BASE[31:6], RES0[5], SH[4:3], AP[2:1], XN[0]   (TRM Table 3-80)
   HPRLAR: LIMIT[31:6], RES0[5:4], AttrIndx[3:1], EN[0]   (TRM Table 3-83)

   Both address fields are bits [31:6] of an address, which is the whole
   reason ZX_MPU_GRANULE exists: an under-aligned base does not fault, its low
   bits land on SH, AP and XN and silently change the region's attributes.  A
   limit computed as base + size - 1 already ends in 0x3F, and those bits land
   on AttrIndx and select an unwritten HMAIR byte.  MASK BOTH before ORing
   anything in.  */

#define ZX_REGION_ADDR_MASK     ZX_C32(0xFFFFFFC0)

#define ZX_HPRBAR_XN            ZX_BIT(0)
#define ZX_HPRBAR_AP_SHIFT      1U
#define ZX_HPRBAR_SH_SHIFT      3U

#define ZX_HPRLAR_EN            ZX_BIT(0)
#define ZX_HPRLAR_ATTRINDX_SHIFT 1U

/* The AP, SH and XN ENCODINGS are not here.  They live in core/inc/
   zx_manifest.h, with the region descriptor whose fields hold them, because
   a manifest author needs them and the host-side validator needs them, and
   neither can include a Cortex-R52 port header.  Nothing in assembly uses
   them, which is what makes the move free.

   What stays here is everything the encodings are shifted INTO -- the field
   positions above -- plus the HMAIR byte layout below, which is this port's
   choice of what each attribute index means rather than an architectural
   fact.  */

/**************************************************************************/
/*                        Memory attributes: HMAIR0/1                     */
/**************************************************************************/

/* Attribute indices ZoneX programs, and the byte each one holds.
   AttrIndx 0-3 index HMAIR0 bytes 0-3; 4-7 index HMAIR1.

   Index 1 is spelled 0x00 EXPLICITLY even though an unwritten HMAIR byte
   already reads as zero, which is Device-nGnRnE.  Relying on that is how a
   masking bug in the limit field survived at EL1: the wrong AttrIndx selected
   an unwritten byte, got Device-nGnRnE, and the region still worked well
   enough to pass a careless test.  Programming every index ZoneX names means
   a wrong index produces a WRONG ATTRIBUTE rather than a plausible one.  */

#define ZX_ATTR_NORMAL_WB       ZX_C32(0x0)     /* Normal, write-back, RW-alloc */
#define ZX_ATTR_DEVICE          ZX_C32(0x1)     /* Device-nGnRnE                */
#define ZX_ATTR_NORMAL_NC       ZX_C32(0x2)     /* Normal, non-cacheable        */

#define ZX_MAIR_BYTE_NORMAL_WB  ZX_C32(0xFF)
#define ZX_MAIR_BYTE_DEVICE     ZX_C32(0x00)
#define ZX_MAIR_BYTE_NORMAL_NC  ZX_C32(0x44)

/* HMAIR0 = byte3:byte2:byte1:byte0 for indices 3, 2, 1, 0.  Index 3 is left
   zero -- Device-nGnRnE -- because it is unused and Device is the
   conservative value for an index nothing should be selecting.  */

#define ZX_HMAIR0_VALUE         ZX_C32(0x004400FF)
#define ZX_HMAIR1_VALUE         ZX_C32(0x00000000)

/**************************************************************************/
/*                          Region count limits                           */
/**************************************************************************/

/* HMPUIR[7:0] must read 0, 16, 20 or 24 (TRM Table 3-79).  Anything else
   means the target is not an architecturally legal Cortex-R52 configuration,
   which the Armv8-R AEM FVP is not: it reported 32 EL1 regions during the
   Cortex-R52 port work and reports 32 at EL2 as well.  ZoneX therefore
   asserts the value LOUDLY and names it rather than trusting it.  */

#define ZX_EL2_REGIONS_NONE     16U
#define ZX_EL2_REGIONS_MAX      24U

/**************************************************************************/
/*                            GICv3 at EL2                                */
/**************************************************************************/

/* ICC_HSRE (p15, 4, c12, c9, 5) enables the GICv3 SYSTEM REGISTER interface.
   Until SRE is set, every other ICC_* and ICH_* system register is
   UNDEFINED -- which is not a documentation nicety: reading ICH_VTR before
   setting this takes an Undefined Instruction exception at EL2, measured on
   the Armv8-R AEM FVP on 2 September 2026.  So the reset path sets it before
   the identity block reads anything GIC-shaped, and EL1 needs it set anyway
   to acknowledge an interrupt at all.  */

#define ZX_ICC_HSRE_SRE         ZX_BIT(0)
#define ZX_ICC_HSRE_ENABLE      ZX_BIT(3)

/**************************************************************************/
/*                     Semihosting (FVP console and exit)                 */
/**************************************************************************/

#define ZX_SYS_WRITE0           ZX_C32(0x04)
#define ZX_SYS_EXIT             ZX_C32(0x18)

/* AArch32 SYS_EXIT takes a REASON, not an exit status, which is why every
   ZoneX image is judged on its printed verdict rather than on a host exit
   code.  Both reasons are passed anyway so that a run which stops for the
   wrong reason is distinguishable in the model's own trace.  */

#define ZX_ADP_STOPPED_APPLICATION_EXIT ZX_C32(0x20026)
#define ZX_ADP_STOPPED_RUN_TIME_ERROR   ZX_C32(0x20023)

/**************************************************************************/
/*                     Outcome of running an EL1 payload                  */
/**************************************************************************/

/* What zx_el2_run_payload returns.  It is a real return: the trap handler
   restores the EL2 context that zx_el2_run_payload saved and resumes it, so a
   guest fault comes back to the hypervisor as a VALUE rather than as a jump
   into a handler that has to decide policy with no context.  This shape is
   kept as partitions arrive; it is how a partition switch will be driven.  */

#define ZX_RUN_YIELDED          ZX_C32(0x0)  /* payload returned, HVC #1     */
#define ZX_RUN_FAULTED          ZX_C32(0x1)  /* stage-2 fault, EC 0x24/0x20  */
#define ZX_RUN_TRAPPED          ZX_C32(0x2)  /* something else reached EL2   */

/**************************************************************************/
/*         Constants the assembly needs, mirrored -- and asserted          */
/**************************************************************************/

/* zx_el2_entry.S and zx_trap_handler.S need exception classes, vector
   offsets and structure offsets that are otherwise declared in core/'s
   zx_fault.h -- a portable header that includes <stdint.h> and so cannot be
   read by the assembler.  They are therefore mirrored here, without suffixes,
   under a ZX_ASM_ prefix.
   
   Mirroring a constant is how two definitions drift apart, so each one is
   checked against its original by a _Static_assert in
   platform/cortex_r52/src/zx_stage2_mpu.c.  The structure offsets are checked
   against offsetof, which means a field inserted into zx_fault_record_t
   breaks the BUILD rather than the fault report -- and a fault report that
   quietly writes HDFAR into the HPFAR slot is the worst possible outcome for
   a file whose entire job is to be believed.  */

#define ZX_ASM_EC_SHIFT             26
#define ZX_ASM_EC_HVC               0x12
#define ZX_ASM_EC_PABT_ROUTED       0x20
#define ZX_ASM_EC_DABT_ROUTED       0x24

#define ZX_ASM_HVC_IMM_NOP          0x0000
#define ZX_ASM_HVC_IMM_YIELD        0x0001

#define ZX_ASM_VEC_RESET            0x00
#define ZX_ASM_VEC_UNDEF            0x04
#define ZX_ASM_VEC_SVC              0x08
#define ZX_ASM_VEC_PABT_HYP         0x0C
#define ZX_ASM_VEC_DABT_HYP         0x10
#define ZX_ASM_VEC_HYP_TRAP         0x14
#define ZX_ASM_VEC_IRQ              0x18
#define ZX_ASM_VEC_FIQ              0x1C

#define ZX_ASM_FAULT_OFF_CAPTURES      0
#define ZX_ASM_FAULT_OFF_VECTOR     4
#define ZX_ASM_FAULT_OFF_HSR        8
#define ZX_ASM_FAULT_OFF_HPFAR      12
#define ZX_ASM_FAULT_OFF_HDFAR      16
#define ZX_ASM_FAULT_OFF_HIFAR      20
#define ZX_ASM_FAULT_OFF_ELR        24
#define ZX_ASM_FAULT_OFF_SPSR       28

/* The EL2 context zx_el2_run_payload saves so that the trap handler can
   resume it: SP, LR, then the eight callee-saved registers r4-r11.  */

#define ZX_ASM_RESUME_OFF_SP        0
#define ZX_ASM_RESUME_OFF_LR        4
#define ZX_ASM_RESUME_OFF_R4        8
#define ZX_ASM_RESUME_WORDS         10

#ifndef __ASSEMBLER__

#include "zx_api.h"
#include "zx_console.h"
#include "zx_fault.h"

/* The region descriptor (ZX_REGION) and the AP/SH/XN encodings it holds come
   from here.  The port programs what a manifest declares, so the descriptor
   belongs to the manifest and not to this port: the host-side validator has
   to build and check the same objects with no Cortex-R52 header in reach.  */
#include "zx_manifest.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************/
/*                          Identity and capability                       */
/**************************************************************************/

ZX_NODISCARD uint32_t zx_read_midr(void);
ZX_NODISCARD uint32_t zx_read_mpidr(void);
ZX_NODISCARD uint32_t zx_read_cntfrq(void);
ZX_NODISCARD uint32_t zx_read_mpuir(void);
ZX_NODISCARD uint32_t zx_read_hmpuir(void);
ZX_NODISCARD uint32_t zx_read_hsctlr(void);
ZX_NODISCARD uint32_t zx_read_hcr(void);
ZX_NODISCARD uint32_t zx_read_hsr(void);
ZX_NODISCARD uint32_t zx_read_hvbar(void);
ZX_NODISCARD uint32_t zx_read_ich_vtr(void);
ZX_NODISCARD uint32_t zx_read_cpsr(void);

/* Region counts, extracted from the two type registers.  They are different
   FIELDS in the two registers -- MPUIR keeps the EL1 count in bits [15:8] and
   HMPUIR the EL2 count in bits [7:0] -- which is exactly the kind of detail
   that is wrong once and then copied.  */

ZX_NODISCARD uint32_t zx_el1_region_count(void);
ZX_NODISCARD uint32_t zx_el2_region_count(void);

/* True when count is one of the values TRM Table 3-79 permits.  */

ZX_NODISCARD uint32_t zx_el2_region_count_is_legal(uint32_t count);

/**************************************************************************/
/*                          Stage-2 MPU programming                       */
/**************************************************************************/

void zx_mair_program(void);

/* Program one region through HPRSELR/HPRBAR/HPRLAR and leave it ENABLED.
   Masks base and limit to the granule before ORing attributes in, which is
   the whole reason this is a function rather than two stores.  */

void zx_stage2_region_program(uint32_t index, const ZX_REGION *region_ptr);

/* Read one region back through HPRSELR/HPRBAR/HPRLAR.  Read-back is not
   paranoia here: a region programmed at an index the implementation does not
   have is UNPREDICTABLE, and a value that did not stick is the difference
   between a wrong region and no region.  */

void zx_stage2_region_read(uint32_t index, uint32_t *base_ptr,
                           uint32_t *limit_ptr);

/* Program region 16 through the DIRECT encoding, MCR p15, 5, <Rt>, c6, c8, 0
   and 1.  Separate from the indirect path on purpose: TRM 3.3.48's prose says
   direct access stops at region 15 while 8.4 lists HPRBAR16-HPRBAR24 at
   opc1 = 5, and this function is how that contradiction is settled on the
   part rather than on paper.  Region 16 specifically, because that is the
   first index where the two readings differ.  The generalisation follows once
   the answer is known; guessing it first would be building on the thing
   under test.  */

void zx_stage2_region_program_direct16(const ZX_REGION *region_ptr);
void zx_stage2_region_read_direct16(uint32_t *base_ptr, uint32_t *limit_ptr);

/* Read one region back and DECOMPOSE it into the descriptor a manifest would
   have declared, so that a caller can compare what the hardware holds against
   what it asked for.

   This exists because the whole class of alignment bug at stage 2 fails in the
   ATTRIBUTES and not in the address: an under-aligned base does not fault, its
   low bits land on SH, AP and XN, and the partition runs with permissions
   nobody asked for.  Nothing will ever report that.  The only defence is to
   read the registers back and look, which is what this and
   zx_stage2_region_matches are for.  */

void zx_stage2_region_readback(uint32_t index, ZX_REGION *region_ptr);

/* Non-zero when a region reads back as the descriptor asked for.  Compares
   the granule-masked base and limit, because the programmer masks before
   writing and a caller comparing raw values would fail on its own rounding
   rather than on a real mismatch.  */

ZX_NODISCARD uint32_t zx_stage2_region_matches(uint32_t index,
                                               const ZX_REGION *region_ptr);

/* HPRENR: one enable bit per region, and the register whose width the TRM
   contradicts itself about.  */

ZX_NODISCARD uint32_t zx_hprenr_read(void);
void zx_hprenr_write(uint32_t value);
void zx_hprenr_enable(uint32_t index);
void zx_hprenr_disable(uint32_t index);

/* THE PARTITION SWITCH.  Replaces the whole enable mask in one write, with
   ONE barrier pair at the end rather than one per region.
 *
 * This is the function a safety customer's question resolves to -- "how long
 * does a partition switch take" is mostly this -- so the barrier policy lives
 * here and nowhere else.  Per-region barriers were measured to be most of a
 * per-region cost during the Cortex-R52 Modules port work; a mask write needs
 * exactly one DSB to retire and one ISB before the next instruction fetch can
 * depend on the new permissions.
 *
 * WHY A MASK AND NOT A BLOCK REWRITE.  Region descriptors are programmed once
 * at boot and never again: each partition owns a fixed block of indices, and
 * switching partitions changes which blocks are ENABLED.  That is what makes
 * the switch one register write of bounded cost instead of a loop whose
 * length depends on how many regions the incoming partition has.  It is also
 * why the direct region encodings above index 15, though proven to work, are
 * not generalised: they would speed up an operation that happens once.
 *
 * The cost of a block rewrite is the alternative worth measuring only if two
 * partitions ever need different ATTRIBUTES on one address, which no manifest
 * the validator accepts can ask for today.  See docs/decisions.md D4.  */

void zx_stage2_enable_set(uint32_t mask);

/* Turning protection on is TWO steps, and separating them is not tidiness.

   zx_el2_mpu_enable sets HSCTLR.BR and HSCTLR.M: the EL2-controlled MPU,
   which governs EL2's OWN accesses.  zx_stage2_enable then sets HCR.VM,
   which is what makes that same region set apply to EL0/EL1 as stage 2.

   They are separate because the hypervisor needs the first one BEFORE it can
   trust its own console.  On a board whose console sits below 0x60000000 the
   background map reaches it as NORMAL memory, which permits the gathering and
   reordering that corrupts a polled UART -- measured on the S32Z280, where
   the identity block printed as legible-but-wrong text until its Device
   region was in place and HSCTLR.M was set.  So the order is: HMAIR, the
   hypervisor's own MMIO regions, zx_el2_mpu_enable, THEN the console, then
   the partition regions, then zx_stage2_enable.

   Enabling HCR.VM with no region covering the payload's code faults at the
   ERET target, which presents as "the guest never started" and looks nothing
   like a memory-protection problem -- which is why the partition regions are
   a precondition of the second step rather than part of it.  */

void zx_el2_mpu_enable(void);
void zx_stage2_enable(void);
void zx_stage2_disable(void);

/**************************************************************************/
/*                        Running an EL1 payload                          */
/**************************************************************************/

/* Drop to EL1 at entry_address with argument in r0, and return when the
   payload yields (HVC #1) or is taken from by a fault.  Returns ZX_RUN_*.

   Implemented in zx_trap_handler.S.  It does not return through the ERET it
   performed: the trap handler restores the context saved here and resumes it,
   so this is a one-way transfer out and a resume back in.  */

ZX_NODISCARD uint32_t zx_el2_run_payload(zx_addr_t entry_address,
                                         uint32_t argument);

/* The statically allocated fault record the trap handler fills in.  Static,
   and filled in before anything else runs, because the earliest evidence is
   the only evidence that cannot have been damaged by the handler itself.

   The object is declared here rather than hidden behind the accessor because
   zx_trap_handler.S writes it directly, by name, at the ZX_ASM_FAULT_OFF_*
   offsets above.  A reader of that assembly needs to be able to find the
   declaration it is writing through.  */

extern zx_fault_record_t zx_el2_fault_storage;

ZX_NODISCARD zx_fault_record_t *zx_el2_fault_record(void);

/* How many times HVC #0 -- the empty Phase-0 hypercall vector -- has been
   taken.  Counted rather than ignored so that "the seam is live" is a number
   a test can assert on.  */

extern uint32_t zx_el2_hypercall_counter;

ZX_NODISCARD uint32_t zx_el2_hypercall_count(void);

/* Snapshots the reset path takes before it changes anything, so that the
   identity block can report what the PART reset to rather than what ZoneX
   left behind.  HSCTLR.TE and SCTLR.TE reset SET on the S32Z280 and clear on
   the Armv8-R AEM FVP; a report that read them after the reset path had
   cleared them would show the same value on both targets and hide the single
   most expensive difference between them.  */

extern uint32_t zx_reset_hsctlr;
extern uint32_t zx_reset_sctlr;
extern uint32_t zx_reset_cpsr;
extern uint32_t zx_reset_hprenr;

/* What sticks in HPRENR when all ones are written, taken by the reset path
   before any region exists.  This says which bits are IMPLEMENTED; whether a
   bit above 15 actually disables its region is a different question and is
   answered functionally by the probe image.  Both are needed: a register that
   accepted the bit and ignored it would pass this test and fail that one, and
   that is the outcome that would make a one-write partition switch silently
   wrong.  */

extern uint32_t zx_hprenr_implemented_bits;

/* The run's verdict, as an object as well as a printed line, so that a
   silicon run with no console capture is still judgeable.  0xFFFFFFFF until
   zx_console_exit sets it, because zero would be a plausible reading of a
   run that never reached its verdict at all.  */

extern uint32_t zx_run_failures;

/**************************************************************************/
/*                    Entry points the reset path calls                   */
/**************************************************************************/

/* zx_el2_main is where zx_el2_entry.S hands over, and it does not return.
   The board provides zx_board_init, called first: on the FVP it has nothing
   to do, and on silicon it brings up the console the rest of the run reports
   through.  */

ZX_NORETURN void zx_el2_main(void);
void zx_board_init(void);

/* Called from the vectors that mean ZoneX itself faulted, or that mean an
   exception nothing was expecting reached EL2.  Both report and stop; neither
   can safely resume, and pretending otherwise would turn a diagnosable bug
   into a corrupted run.  */

ZX_NORETURN void zx_el2_hypervisor_fault(void);
ZX_NORETURN void zx_el2_unexpected_vector(void);

#ifdef __cplusplus
}
#endif

#endif /* __ASSEMBLER__ */

#endif /* ZX_PORT_H */
