/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/
// Some portions generated by Claude Code (Opus 5).

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_port.h                                            Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The Cortex-R52 port interface: everything ZoneX needs that is       */
/*    specific to Armv8-R AArch32 at EL2.                                 */
/*                                                                        */
/*    This header is included from BOTH C and preprocessed assembly, so   */
/*    that a bit position cannot be spelled one way in zx_el2_entry.S and */
/*    another way in zx_stage2_mpu.c.  Everything above the __ASSEMBLER__ */
/*    guard is therefore preprocessor-only; the ZX_BIT and ZX_C32 macros  */
/*    exist so that the same definition can carry a U suffix in C, where  */
/*    -Wconversion is in force, and no suffix in assembly, where the      */
/*    assembler would reject it.                                          */
/*                                                                        */
/*  TERMINOLOGY -- READ THIS BEFORE ADDING ANYTHING BELOW                 */
/*                                                                        */
/*    The Cortex-R52 is AArch32-only and Armv8-R has NO PAGE TABLES at    */
/*    either stage of translation.  Both stages are region-based MPUs     */
/*    (PMSAv8-R).  The registers this port uses are therefore the         */
/*    AArch32 Hyp-mode ones, reached through MRC/MCR p15, 4, <Rt>, ...    */
/*    (opc1 = 4 is the Hyp bank; opc1 = 5 reaches HPRBAR16 and above):    */
/*                                                                        */
/*      HVBAR    EL2 vector base            HSR      syndrome             */
/*      HCR      hypervisor configuration   HDFAR    data fault address   */
/*      HSCTLR   EL2 system control         HIFAR    instruction fault    */
/*      HMPUIR   EL2 region count           HPFAR    stage-2 fault addr   */
/*      HPRSELR  region select              HMAIR0   memory attributes    */
/*      HPRENR   region enables             HMAIR1   memory attributes    */
/*      HPRBAR   region base                CNTHCTL  timer access control */
/*      HPRLAR   region limit               CNTVOFF  virtual time offset  */
/*      ICC_HSRE GICv3 sysreg interface      ICH_VTR  List Register count  */
/*                                                                        */
/*    A second family of names is WRONG BY CONSTRUCTION for this target   */
/*    and must not appear anywhere in this repository: the AArch64        */
/*    system-register spellings, the translation-table registers, and the */
/*    RISC-V memory-protection vocabulary.  Using one of them means the   */
/*    code was written against the wrong architecture, and the result     */
/*    reads plausibly while being wrong about the hardware.               */
/*                                                                        */
/*    scripts/check_terminology.sh holds the exact list and enforces it   */
/*    in CI.  It is the single place that spells those names, so that     */
/*    the list cannot drift away from what is actually checked.           */
/*                                                                        */
/*    The verified encodings, field layouts and exception-class values    */
/*    are in docs/armv8r-el2-reference.md, which is the authority.  Take  */
/*    them from there rather than from memory or from an A-profile        */
/*    hypervisor; the AP field in particular does NOT mean at EL2 what it */
/*    means at EL1, which is why the AP encodings below are named for    */
/*    what they grant rather than numbered.                               */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_PORT_H
#define ZX_PORT_H

/* One definition, two languages.  The assembler tolerates no integer suffix
   and C under -Wconversion wants one on every constant that reaches a
   uint32_t, so the suffix is applied by macro rather than by writing each
   constant twice.  ZX_C32 pastes the suffix, so its argument must be a single
   literal token; a composite value is written as (ZX_C32(0x3) << 3).  */

#ifdef __ASSEMBLER__
#  define ZX_BIT(n)     (1 << (n))
#  define ZX_C32(v)     v
#else
#  define ZX_BIT(n)     (1U << (n))
#  define ZX_C32(v)     v ## U
#endif

/**************************************************************************/
/*                      AArch32 processor modes and masks                 */
/**************************************************************************/

#define ZX_MODE_USR             ZX_C32(0x10)
#define ZX_MODE_FIQ             ZX_C32(0x11)
#define ZX_MODE_IRQ             ZX_C32(0x12)
#define ZX_MODE_SVC             ZX_C32(0x13)    /* an EL1 mode              */
#define ZX_MODE_ABT             ZX_C32(0x17)
#define ZX_MODE_HYP             ZX_C32(0x1A)    /* EL2                      */
#define ZX_MODE_UND             ZX_C32(0x1B)
#define ZX_MODE_SYS             ZX_C32(0x1F)
#define ZX_MODE_MASK            ZX_C32(0x1F)

#define ZX_PSR_A                ZX_BIT(8)       /* asynchronous abort mask  */
#define ZX_PSR_I                ZX_BIT(7)       /* IRQ mask                 */
#define ZX_PSR_F                ZX_BIT(6)       /* FIQ mask                 */

/**************************************************************************/
/*                                  HCR                                   */
/**************************************************************************/

#define ZX_HCR_VM               ZX_BIT(0)       /* stage-2 MPU enable       */
#define ZX_HCR_FMO              ZX_BIT(3)       /* route FIQ to EL2         */
#define ZX_HCR_IMO              ZX_BIT(4)       /* route IRQ to EL2         */
#define ZX_HCR_AMO              ZX_BIT(5)       /* route aborts to EL2      */

/* ⚠ FMO IS BIT 3 AND AMO IS BIT 5, AND THIS FILE HAD THEM THE OTHER WAY
   ROUND until the first image that SET one of them.
 *
 * The order in the register is FMO, IMO, AMO going up from bit 3 -- TRM
 * Table 3-70 and the architecture agree -- and the mnemonic order somebody
 * reaches for is the alphabetical one, AMO first.  IMO is bit 4 either way,
 * which is exactly why the mistake survived: every use of these three until
 * now was a single BIC of all three at once, where a swap between two of
 * them changes nothing at all.
 *
 * What it cost when it finally mattered: zx_el2_route_fiq set bit 5, which
 * is AMO, so physical FIQ was never routed to EL2 and a partition's window
 * never ended.  Every other check passed -- the comparator expired, the GIC
 * made the interrupt pending, and the guest's PSTATE.F then masked it as an
 * ordinary EL1 FIQ.  The run printed a perfect setup and then went quiet.
 *
 * Two things now make it hard to repeat.  The positions are asserted, in
 * platform/cortex_r52/src/zx_context.c rather than here -- everything above
 * the __ASSEMBLER__ guard in this file is read by the assembler as well, and
 * an assembler cannot read a _Static_assert.  And the image that sets one of
 * them now CHECKS THE BIT rather than the name it used to set it, which is
 * the only form of that check a swapped definition cannot satisfy.  */
#define ZX_HCR_DC               ZX_BIT(12)      /* default cacheable        */
#define ZX_HCR_TGE              ZX_BIT(27)      /* trap general exceptions  */
#define ZX_HCR_HCD              ZX_BIT(29)      /* HVC disable -- keep CLEAR */

/**************************************************************************/
/*                                HSCTLR                                  */
/**************************************************************************/

#define ZX_HSCTLR_M             ZX_BIT(0)       /* EL2 MPU enable           */
#define ZX_HSCTLR_A             ZX_BIT(1)       /* alignment check          */
#define ZX_HSCTLR_C             ZX_BIT(2)       /* data cache              */
#define ZX_HSCTLR_I             ZX_BIT(12)      /* instruction cache        */
#define ZX_HSCTLR_BR            ZX_BIT(17)      /* background region enable */
#define ZX_HSCTLR_TE            ZX_BIT(30)      /* Thumb exception entry    */

/**************************************************************************/
/*                                SCTLR                                   */
/**************************************************************************/

/* Needed at EL2 because ZoneX must leave the EL1 MPU in a known state before
   handing a payload the machine.  Stage-2 bring-up leaves SCTLR.M CLEAR:
   with stage 1 disabled the payload runs on the EL1 background map and the
   only thing under test is stage 2.  One variable at a time.  */

#define ZX_SCTLR_M              ZX_BIT(0)
#define ZX_SCTLR_C              ZX_BIT(2)
#define ZX_SCTLR_I              ZX_BIT(12)
#define ZX_SCTLR_BR             ZX_BIT(17)
#define ZX_SCTLR_TE             ZX_BIT(30)

/**************************************************************************/
/*                          Region descriptor fields                      */
/**************************************************************************/

/* HPRBAR: BASE[31:6], RES0[5], SH[4:3], AP[2:1], XN[0]   (TRM Table 3-80)
   HPRLAR: LIMIT[31:6], RES0[5:4], AttrIndx[3:1], EN[0]   (TRM Table 3-83)

   Both address fields are bits [31:6] of an address, which is the whole
   reason ZX_MPU_GRANULE exists: an under-aligned base does not fault, its low
   bits land on SH, AP and XN and silently change the region's attributes.  A
   limit computed as base + size - 1 already ends in 0x3F, and those bits land
   on AttrIndx and select an unwritten HMAIR byte.  MASK BOTH before ORing
   anything in.  */

#define ZX_REGION_ADDR_MASK     ZX_C32(0xFFFFFFC0)

#define ZX_HPRBAR_XN            ZX_BIT(0)
#define ZX_HPRBAR_AP_SHIFT      1U
#define ZX_HPRBAR_SH_SHIFT      3U

#define ZX_HPRLAR_EN            ZX_BIT(0)
#define ZX_HPRLAR_ATTRINDX_SHIFT 1U

/* The AP, SH and XN ENCODINGS are not here.  They live in core/inc/
   zx_manifest.h, with the region descriptor whose fields hold them, because
   a manifest author needs them and the host-side validator needs them, and
   neither can include a Cortex-R52 port header.  Nothing in assembly uses
   them, which is what makes the move free.

   What stays here is everything the encodings are shifted INTO -- the field
   positions above -- plus the HMAIR byte layout below, which is this port's
   choice of what each attribute index means rather than an architectural
   fact.  */

/**************************************************************************/
/*                        Memory attributes: HMAIR0/1                     */
/**************************************************************************/

/* Attribute indices ZoneX programs, and the byte each one holds.
   AttrIndx 0-3 index HMAIR0 bytes 0-3; 4-7 index HMAIR1.

   Index 1 is spelled 0x00 EXPLICITLY even though an unwritten HMAIR byte
   already reads as zero, which is Device-nGnRnE.  Relying on that is how a
   masking bug in the limit field survived at EL1: the wrong AttrIndx selected
   an unwritten byte, got Device-nGnRnE, and the region still worked well
   enough to pass a careless test.  Programming every index ZoneX names means
   a wrong index produces a WRONG ATTRIBUTE rather than a plausible one.  */

#define ZX_ATTR_NORMAL_WB       ZX_C32(0x0)     /* Normal, write-back, RW-alloc */
#define ZX_ATTR_DEVICE          ZX_C32(0x1)     /* Device-nGnRnE                */
#define ZX_ATTR_NORMAL_NC       ZX_C32(0x2)     /* Normal, non-cacheable        */

#define ZX_MAIR_BYTE_NORMAL_WB  ZX_C32(0xFF)
#define ZX_MAIR_BYTE_DEVICE     ZX_C32(0x00)
#define ZX_MAIR_BYTE_NORMAL_NC  ZX_C32(0x44)

/* HMAIR0 = byte3:byte2:byte1:byte0 for indices 3, 2, 1, 0.  Index 3 is left
   zero -- Device-nGnRnE -- because it is unused and Device is the
   conservative value for an index nothing should be selecting.  */

#define ZX_HMAIR0_VALUE         ZX_C32(0x004400FF)
#define ZX_HMAIR1_VALUE         ZX_C32(0x00000000)

/**************************************************************************/
/*                          Region count limits                           */
/**************************************************************************/

/* HMPUIR[7:0] must read 0, 16, 20 or 24 (TRM Table 3-79).  Anything else
   means the target is not an architecturally legal Cortex-R52 configuration,
   which the Armv8-R AEM FVP is not: it reported 32 EL1 regions during the
   Cortex-R52 port work and reports 32 at EL2 as well.  ZoneX therefore
   asserts the value LOUDLY and names it rather than trusting it.  */

#define ZX_EL2_REGIONS_NONE     16U
#define ZX_EL2_REGIONS_MAX      24U

/**************************************************************************/
/*                            GICv3 at EL2                                */
/**************************************************************************/

/* ICC_HSRE (p15, 4, c12, c9, 5) enables the GICv3 SYSTEM REGISTER interface.
   Until SRE is set, every other ICC_* and ICH_* system register is
   UNDEFINED -- which is not a documentation nicety: reading ICH_VTR before
   setting this takes an Undefined Instruction exception at EL2, measured on
   the Armv8-R AEM FVP on 2 September 2026.  So the reset path sets it before
   the identity block reads anything GIC-shaped, and EL1 needs it set anyway
   to acknowledge an interrupt at all.  */

#define ZX_ICC_HSRE_SRE         ZX_BIT(0)
#define ZX_ICC_HSRE_ENABLE      ZX_BIT(3)

/**************************************************************************/
/*                    The interrupts ZoneX knows about                    */
/**************************************************************************/

/* Three timer interrupts arrive as PPIs on this core (TRM section 9), and
   which one a partition gets is a design decision rather than a detail:

     30  the PHYSICAL timer.  A partition must not have it -- its time keeps
         running while the partition is descheduled, and a guest reading it
         can therefore observe that it was not running.
     27  the VIRTUAL timer.  What a partition gets, because CNTVOFF freezes
         its counter while the partition is off the core.
     26  the HYPERVISOR timer.  ZoneX's own, and the reason a partition may
         not reach the redistributor: the enable bit for this INTID lives in
         the same frame as the enable bit for INTID 27.

   See docs/decisions.md D7.  The guest restates INTID 27 as
   ZX_GUEST_TIMER_INTID in examples/common/zx_guest_abi.h -- it is a separate
   program and cannot include this header -- and the example that includes
   both asserts the two agree at compile time.  */

#define ZX_PPI_PHYSICAL_TIMER   30U
#define ZX_PPI_VIRTUAL_TIMER    27U
#define ZX_PPI_HYPERVISOR_TIMER 26U

/* What ICC_IAR1 returns when nothing was pending.  It must NOT be given an
   end-of-interrupt.  */

#define ZX_INTID_SPURIOUS       1023U


/**************************************************************************/
/*                     Semihosting (FVP console and exit)                 */
/**************************************************************************/

#define ZX_SYS_WRITE0           ZX_C32(0x04)
#define ZX_SYS_EXIT             ZX_C32(0x18)

/* AArch32 SYS_EXIT takes a REASON, not an exit status, which is why every
   ZoneX image is judged on its printed verdict rather than on a host exit
   code.  Both reasons are passed anyway so that a run which stops for the
   wrong reason is distinguishable in the model's own trace.  */

#define ZX_ADP_STOPPED_APPLICATION_EXIT ZX_C32(0x20026)
#define ZX_ADP_STOPPED_RUN_TIME_ERROR   ZX_C32(0x20023)

/**************************************************************************/
/*                     Outcome of running an EL1 payload                  */
/**************************************************************************/

/* What zx_el2_run_payload returns.  It is a real return: the trap handler
   restores the EL2 context that zx_el2_run_payload saved and resumes it, so a
   guest fault comes back to the hypervisor as a VALUE rather than as a jump
   into a handler that has to decide policy with no context.  This shape is
   kept as partitions arrive; it is how a partition switch will be driven.  */

#define ZX_RUN_YIELDED          ZX_C32(0x0)  /* payload returned, HVC #1     */
#define ZX_RUN_FAULTED          ZX_C32(0x1)  /* stage-2 fault, EC 0x24/0x20  */
#define ZX_RUN_TRAPPED          ZX_C32(0x2)  /* something else reached EL2   */

/* AND THE TWO A TIME-PARTITIONED RUN ADDS.  A window boundary does NOT come
   back here: the boundary handler switches partitions and ERETs into the
   next one without ever leaving EL2's exception path, which is what makes
   the switch a bounded operation rather than a return through C.  These two
   are the ways a FRAME ends.

     ZX_RUN_FRAME_DONE   the schedule reached its frame limit.  A bounded
                         run, which is what a regression can assert a total
                         against -- "the harness timed out" is not a result.
     ZX_RUN_OVERRUN      too many window boundaries had already passed by
                         the time they were computed, so at least one window
                         is shorter than its own partition switch.  The
                         schedule would keep turning and every frame would
                         be longer than declared; stopping and saying so is
                         the only way that becomes visible.  */

#define ZX_RUN_FRAME_DONE       ZX_C32(0x3)  /* the frame limit was reached  */
#define ZX_RUN_OVERRUN          ZX_C32(0x4)  /* windows shorter than a switch */

/**************************************************************************/
/*         Constants the assembly needs, mirrored -- and asserted          */
/**************************************************************************/

/* zx_el2_entry.S and zx_trap_handler.S need exception classes, vector
   offsets and structure offsets that are otherwise declared in core/'s
   zx_fault.h -- a portable header that includes <stdint.h> and so cannot be
   read by the assembler.  They are therefore mirrored here, without suffixes,
   under a ZX_ASM_ prefix.
   
   Mirroring a constant is how two definitions drift apart, so each one is
   checked against its original by a _Static_assert in
   platform/cortex_r52/src/zx_stage2_mpu.c.  The structure offsets are checked
   against offsetof, which means a field inserted into zx_fault_record_t
   breaks the BUILD rather than the fault report -- and a fault report that
   quietly writes HDFAR into the HPFAR slot is the worst possible outcome for
   a file whose entire job is to be believed.  */

#define ZX_ASM_EC_SHIFT             26
#define ZX_ASM_EC_HVC               0x12
#define ZX_ASM_EC_PABT_ROUTED       0x20
#define ZX_ASM_EC_DABT_ROUTED       0x24

#define ZX_ASM_HVC_IMM_NOP          0x0000
#define ZX_ASM_HVC_IMM_YIELD        0x0001
#define ZX_ASM_HVC_IMM_PUTC         0x0002

#define ZX_ASM_VEC_RESET            0x00
#define ZX_ASM_VEC_UNDEF            0x04
#define ZX_ASM_VEC_SVC              0x08
#define ZX_ASM_VEC_PABT_HYP         0x0C
#define ZX_ASM_VEC_DABT_HYP         0x10
#define ZX_ASM_VEC_HYP_TRAP         0x14
#define ZX_ASM_VEC_IRQ              0x18
#define ZX_ASM_VEC_FIQ              0x1C

#define ZX_ASM_FAULT_OFF_CAPTURES      0
#define ZX_ASM_FAULT_OFF_VECTOR     4
#define ZX_ASM_FAULT_OFF_HSR        8
#define ZX_ASM_FAULT_OFF_HPFAR      12
#define ZX_ASM_FAULT_OFF_HDFAR      16
#define ZX_ASM_FAULT_OFF_HIFAR      20
#define ZX_ASM_FAULT_OFF_ELR        24
#define ZX_ASM_FAULT_OFF_SPSR       28

/* The EL2 context zx_el2_run_payload saves so that the trap handler can
   resume it: SP, LR, then the eight callee-saved registers r4-r11.  */

#define ZX_ASM_RESUME_OFF_SP        0
#define ZX_ASM_RESUME_OFF_LR        4
#define ZX_ASM_RESUME_OFF_R4        8
#define ZX_ASM_RESUME_WORDS         10

/* THE PART OF A PARTITION'S CONTEXT THAT ASSEMBLY TOUCHES, and it is
   deliberately the smallest part.
 *
 * Hyp mode banks only SP, LR and SPSR, so while the hypervisor runs, almost
 * all of a guest's state is STILL IN THE MACHINE: its banked SPs and LRs,
 * its EL1 system registers, its whole EL1 MPU region set.  Every one of
 * those can be read and written from C at EL2 exactly as it stands.
 *
 * What cannot wait is r0-r12, which Hyp mode SHARES with EL1 and which the
 * first C instruction would destroy, and ELR_hyp/SPSR_hyp, which say where
 * the guest was and in what state.  Those fifteen words are captured in the
 * vector, before anything else runs, and they are why this block starts
 * with them: the offsets below are what the assembly indexes by, so they are
 * kept at the front where they are constants a reader can check by counting.
 *
 * The rest of the structure is C's and has no offsets here.  That split is
 * the whole reason the largest and most error-prone half of a partition
 * switch -- twenty MPU regions, two registers each -- is a readable loop
 * rather than a page of MCR/MRC pairs.  Every one of these offsets is
 * checked against offsetof by a _Static_assert in
 * platform/cortex_r52/src/zx_context.c.  */

#define ZX_ASM_CTX_OFF_R0           0
#define ZX_ASM_CTX_OFF_R12          48
#define ZX_ASM_CTX_OFF_ELR          52
#define ZX_ASM_CTX_OFF_SPSR         56

#ifndef __ASSEMBLER__

#include "zx_api.h"
#include "zx_console.h"
#include "zx_fault.h"

/* The region descriptor (ZX_REGION) and the AP/SH/XN encodings it holds come
   from here.  The port programs what a manifest declares, so the descriptor
   belongs to the manifest and not to this port: the host-side validator has
   to build and check the same objects with no Cortex-R52 header in reach.  */
#include "zx_manifest.h"
#include "zx_mm.h"
#include "zx_schedule.h"

/**************************************************************************/
/*                 Where a board's GICv3 frames actually are              */
/*                                                                        */
/*  PASSED IN RATHER THAN COMPILED IN, because this translation unit is    */
/*  the PART's and not a board's.  The Cortex-R52 layer knows the register */
/*  offsets inside a GICv3 -- which are architectural -- and knows nothing */
/*  about where the frames sit, which is a board fact and lives in the     */
/*  example's zx_platform.h.  A #include of a board header here is how a   */
/*  port stops being portable between the two targets it already has.      */
/*                                                                        */
/*  A redistributor is TWO consecutive 64 KB frames per core: the RD frame */
/*  carries GICR_WAKER, and the SGI frame carries the enable, group,       */
/*  priority and configuration bits for INTIDs 0 to 31.  Both are needed   */
/*  and they are named separately because getting them the wrong way round */
/*  writes plausible values into the wrong registers and reads back zero.  */
/**************************************************************************/

typedef struct ZX_GIC_LAYOUT_STRUCT
{
    zx_addr_t   zx_gic_dist_base;       /* GICD                            */
    zx_addr_t   zx_gic_rd_base;         /* GICR, the RD frame              */
    zx_addr_t   zx_gic_sgi_base;        /* GICR, the SGI frame             */

} ZX_GIC_LAYOUT;

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************/
/*                          Identity and capability                       */
/**************************************************************************/

ZX_NODISCARD uint32_t zx_read_midr(void);
ZX_NODISCARD uint32_t zx_read_mpidr(void);
ZX_NODISCARD uint32_t zx_read_cntfrq(void);
ZX_NODISCARD uint32_t zx_read_mpuir(void);
ZX_NODISCARD uint32_t zx_read_hmpuir(void);
ZX_NODISCARD uint32_t zx_read_hsctlr(void);
ZX_NODISCARD uint32_t zx_read_hcr(void);
ZX_NODISCARD uint32_t zx_read_hsr(void);
ZX_NODISCARD uint32_t zx_read_hvbar(void);
ZX_NODISCARD uint32_t zx_read_ich_vtr(void);
ZX_NODISCARD uint32_t zx_read_cpsr(void);

/* Region counts, extracted from the two type registers.  They are different
   FIELDS in the two registers -- MPUIR keeps the EL1 count in bits [15:8] and
   HMPUIR the EL2 count in bits [7:0] -- which is exactly the kind of detail
   that is wrong once and then copied.  */

ZX_NODISCARD uint32_t zx_el1_region_count(void);
ZX_NODISCARD uint32_t zx_el2_region_count(void);

/* True when count is one of the values TRM Table 3-79 permits.  */

ZX_NODISCARD uint32_t zx_el2_region_count_is_legal(uint32_t count);

/**************************************************************************/
/*                          Stage-2 MPU programming                       */
/**************************************************************************/

void zx_mair_program(void);

/* Program one region through HPRSELR/HPRBAR/HPRLAR and leave it ENABLED.
   Masks base and limit to the granule before ORing attributes in, which is
   the whole reason this is a function rather than two stores.  */

void zx_stage2_region_program(uint32_t index, const ZX_REGION *region_ptr);

/* Read one region back through HPRSELR/HPRBAR/HPRLAR.  Read-back is not
   paranoia here: a region programmed at an index the implementation does not
   have is UNPREDICTABLE, and a value that did not stick is the difference
   between a wrong region and no region.  */

void zx_stage2_region_read(uint32_t index, uint32_t *base_ptr,
                           uint32_t *limit_ptr);

/* Program region 16 through the DIRECT encoding, MCR p15, 5, <Rt>, c6, c8, 0
   and 1.  Separate from the indirect path on purpose: TRM 3.3.48's prose says
   direct access stops at region 15 while 8.4 lists HPRBAR16-HPRBAR24 at
   opc1 = 5, and this function is how that contradiction is settled on the
   part rather than on paper.  Region 16 specifically, because that is the
   first index where the two readings differ.  The generalisation follows once
   the answer is known; guessing it first would be building on the thing
   under test.  */

void zx_stage2_region_program_direct16(const ZX_REGION *region_ptr);
void zx_stage2_region_read_direct16(uint32_t *base_ptr, uint32_t *limit_ptr);

/* Read one region back and DECOMPOSE it into the descriptor a manifest would
   have declared, so that a caller can compare what the hardware holds against
   what it asked for.

   This exists because the whole class of alignment bug at stage 2 fails in the
   ATTRIBUTES and not in the address: an under-aligned base does not fault, its
   low bits land on SH, AP and XN, and the partition runs with permissions
   nobody asked for.  Nothing will ever report that.  The only defence is to
   read the registers back and look, which is what this and
   zx_stage2_region_matches are for.  */

void zx_stage2_region_readback(uint32_t index, ZX_REGION *region_ptr);

/* Non-zero when a region reads back as the descriptor asked for.  Compares
   the granule-masked base and limit, because the programmer masks before
   writing and a caller comparing raw values would fail on its own rounding
   rather than on a real mismatch.  */

ZX_NODISCARD uint32_t zx_stage2_region_matches(uint32_t index,
                                               const ZX_REGION *region_ptr);

/* HPRENR: one enable bit per region, and the register whose width the TRM
   contradicts itself about.  */

ZX_NODISCARD uint32_t zx_hprenr_read(void);
void zx_hprenr_write(uint32_t value);
void zx_hprenr_enable(uint32_t index);
void zx_hprenr_disable(uint32_t index);

/* THE PARTITION SWITCH.  Replaces the whole enable mask in one write, with
   ONE barrier pair at the end rather than one per region.
 *
 * This is the function a safety customer's question resolves to -- "how long
 * does a partition switch take" is mostly this -- so the barrier policy lives
 * here and nowhere else.  Per-region barriers were measured to be most of a
 * per-region cost during the Cortex-R52 Modules port work; a mask write needs
 * exactly one DSB to retire and one ISB before the next instruction fetch can
 * depend on the new permissions.
 *
 * WHY A MASK AND NOT A BLOCK REWRITE.  Region descriptors are programmed once
 * at boot and never again: each partition owns a fixed block of indices, and
 * switching partitions changes which blocks are ENABLED.  That is what makes
 * the switch one register write of bounded cost instead of a loop whose
 * length depends on how many regions the incoming partition has.  It is also
 * why the direct region encodings above index 15, though proven to work, are
 * not generalised: they would speed up an operation that happens once.
 *
 * The cost of a block rewrite is the alternative worth measuring only if two
 * partitions ever need different ATTRIBUTES on one address, which no manifest
 * the validator accepts can ask for today.  See docs/decisions.md D4.  */

void zx_stage2_enable_set(uint32_t mask);

/**************************************************************************/
/*                 Preparing EL1 for a guest that boots there             */
/**************************************************************************/

/* The EL2-only configuration a guest needs and cannot perform itself.
 *
 * A standalone Cortex-R52 kernel resets into EL2 and does this in its own boot
 * path.  Built as a guest it skips that block -- which is what the port's
 * TX_R52_BOOT_AT_EL1 option is for -- so the work changes owner rather than
 * ceasing to be necessary.  Clears HCPTR.TCP10/TCP11 and programs CNTFRQ from
 * the board's counter frequency, and deliberately does NOT open EL1 access to
 * the physical counter.  The reasoning for each, including the omission, is in
 * platform/cortex_r52/src/zx_timer.c.  */

void zx_el2_prepare_guest_el1(uint32_t counter_hz);

/**************************************************************************/
/*                       The GIC, which EL2 owns whole                    */
/*                                                                        */
/*  Implemented in zx_gic.c.  Every function here touches memory-mapped    */
/*  GIC state, which is exactly the state no partition is given: the       */
/*  distributor is one per system and the redistributor is one per CORE,   */
/*  so the frame that holds a partition's timer enable also holds the      */
/*  hypervisor's.  A guest reaches only its own CPU interface, which is    */
/*  system registers.                                                     */
/**************************************************************************/

/* Bring the distributor and this core's redistributor up.  Returns non-zero
   when the redistributor reported its children awake, zero when the bounded
   wait ran out -- which is a real outcome and not a hang, because a GIC that
   never wakes would otherwise stop the boot with nothing printed.  */

ZX_NODISCARD uint32_t zx_gic_el2_init(const ZX_GIC_LAYOUT *gic_ptr);

/* Enable one PPI for delivery to EL1: Group 1, level-triggered, at the given
   priority.  Level and not edge because the generic timer asserts a level.  */

void zx_gic_enable_guest_ppi(const ZX_GIC_LAYOUT *gic_ptr, uint32_t intid,
                             uint32_t priority);

/* Disable one PPI again.  A partition that is not running must not have an
   interrupt of its own delivered, and this is how a window ends cleanly.  */

void zx_gic_disable_guest_ppi(const ZX_GIC_LAYOUT *gic_ptr, uint32_t intid);

/* READ BACK what was programmed, for the same reason the region set is read
   back: a write that went to the wrong offset does not fault, it does
   nothing, and a partition that silently never receives its timer looks
   exactly like a kernel whose scheduler is broken.  */

ZX_NODISCARD uint32_t zx_gic_ppi_is_enabled(const ZX_GIC_LAYOUT *gic_ptr,
                                            uint32_t intid);
ZX_NODISCARD uint32_t zx_gic_ppi_is_group1(const ZX_GIC_LAYOUT *gic_ptr,
                                           uint32_t intid);
ZX_NODISCARD uint32_t zx_gic_ppi_priority(const ZX_GIC_LAYOUT *gic_ptr,
                                          uint32_t intid);

/* And whether the GIC has one PENDING, which is the middle of the three
   questions a window that never ends raises: the comparator may not have
   expired, the GIC may not have been told, or the core may not have taken
   the exception.  All three present identically -- a hypervisor that starts
   a frame and is never heard from again -- and only this one distinguishes
   the first from the third.  */

ZX_NODISCARD uint32_t zx_gic_ppi_is_pending(const ZX_GIC_LAYOUT *gic_ptr,
                                            uint32_t intid);

/* How many priority bits this GIC actually implements, discovered by writing
   all ones to one INTID's priority byte and reading back what stuck.  The low
   bits vanish, so two priorities differing only there collapse together --
   which is the difference between an interrupt that can preempt another and
   one that quietly cannot.  Restores the byte it borrowed.  */

ZX_NODISCARD uint32_t zx_gic_priority_bits(const ZX_GIC_LAYOUT *gic_ptr,
                                           uint32_t intid);

/**************************************************************************/
/*                  The clock a partition is allowed to see               */
/*                                                                        */
/*  Implemented in zx_timer.c.  A partition reads time through the VIRTUAL */
/*  counter, which is the physical one minus CNTVOFF, and CNTVOFF is the   */
/*  hypervisor's.  Advancing it by exactly the time a partition spent off   */
/*  the core is what makes a descheduled partition's clock FROZEN rather   */
/*  than merely unread -- the difference between temporal partitioning and */
/*  time slicing that a guest can observe.  See docs/decisions.md D7.      */
/**************************************************************************/

/* The physical counter, which no partition can reach.  64-bit, read as a
   pair.  */

ZX_NODISCARD uint64_t zx_read_cntpct(void);

/* Bounded: read the physical counter twice and say whether it moved.
   Programming CNTFRQ does not START the counter, and on one of the two ZoneX
   targets it is left stopped at reset -- so this is the check that stands
   between a partition granted a timer and a run that ends in a timeout.  */

ZX_NODISCARD uint32_t zx_counter_is_running(void);

/* Set this partition's virtual time to zero and start it running.  Called
   once, when a partition is (re)loaded, so that every excursion of a guest
   begins from the same point on its own clock -- which is what makes two
   runs of the same guest comparable.  */

void zx_el2_guest_time_reset(void);

/* Freeze and unfreeze the partition's virtual counter.  suspend() records
   the physical count; resume() adds everything that elapsed since to
   CNTVOFF, so the virtual counter never advanced.  With one partition the
   gap being closed is the hypervisor's own work between excursions; with
   more than one it is the other partitions' windows.  */

void zx_el2_guest_time_suspend(void);
void zx_el2_guest_time_resume(void);

/* A resume that does NOT give the time back.  It exists so that the freeze
   can be seen to FAIL, and it keeps the bookkeeping so that what breaks is
   the mechanism rather than the measurement.  */

void zx_el2_guest_time_resume_uncredited(void);

/* CNTVOFF as it stands, for reporting.  A number nobody can see is a
   mechanism nobody can check.  */

ZX_NODISCARD uint64_t zx_el2_guest_time_offset(void);

/* The partition's OWN clock, now: the physical counter seen past CNTVOFF,
   which is the number a guest reading CNTVCT would get.  */

ZX_NODISCARD uint64_t zx_el2_guest_virtual_count(void);

/* And the two halves of the last freeze point: the physical count when the
   partition stopped, and what its own clock read at that instant.
 *
 * These are what make the freeze CHECKABLE.  The invariant is exact --
 * after a resume, zx_el2_guest_virtual_count() equals
 * zx_el2_guest_virtual_when_suspended() -- and the physical distance between
 * the two instants is the interval the partition was excluded from.
 * Measuring either one anywhere else measures the drift that CNTVOFF has not
 * corrected yet, which looks exactly like a broken freeze.  */

ZX_NODISCARD uint64_t zx_el2_guest_time_suspended_at(void);
ZX_NODISCARD uint64_t zx_el2_guest_virtual_when_suspended(void);

/* And where the counter was when the partition was given the core back.
 *
 * (suspended_at, resumed_at) is the interval the partition was excluded
 * from, as the MECHANISM measured it, which is what CNTVOFF is credited
 * with.  A check of the freeze compares the offset's actual movement -- read
 * back out of the register -- against exactly this interval, and every term
 * in that comparison is then a hardware read rather than a restatement of
 * the arithmetic being checked.
 *
 * Reading the counter again from outside does not give the same number: on
 * the S32Z280 a CNTPCT read crosses into an 8 MHz clock domain, so the few
 * reads between a resume and a check cost 64 counts of real time.  Measured,
 * on the board.  */

ZX_NODISCARD uint64_t zx_el2_guest_time_resumed_at(void);

/* Stop a partition's virtual timer.  Per-guest state, and the reason it is
   here rather than left to the guest is that a partition can be taken from
   at any instant -- including with its timer armed and its level asserted at
   the GIC.  */

void zx_el2_guest_timer_stop(void);

/* Spend a known interval at EL2, measured in counter counts.
 *
 * A hypervisor has no reason to wait; this exists so that "a partition's
 * clock does not advance while it is not running" can be CHECKED, which
 * needs a real interval in which the partition is not running.  Measuring
 * the gap across whatever work happened to be there is not good enough and
 * was tried: the model's console costs it no simulated time, so the gap was
 * zero counts long and both the positive and the deliberately-broken build
 * reported the clock frozen.  */

void zx_el2_dwell(uint32_t counts);

/**************************************************************************/
/*                    Making a copied image executable                    */
/**************************************************************************/

/* Clean the bytes of a freshly copied guest image out of the data cache and
   invalidate the instruction cache, in that order and with the barriers
   between them.
 *
 * ONE FUNCTION AND NOT TWO, because the failure mode is doing one half.  An
 * image whose data side was cleaned and whose instruction side was not is
 * executable by luck: a cold instruction cache over an address nothing has
 * executed misses, fetches from memory and works, until an eviction lands
 * differently.  Nothing reports that, and the two-address module test during
 * the Cortex-R52 Modules port work passed before this maintenance existed.
 *
 * ZoneX runs with HSCTLR.C and HSCTLR.I clear today, so this is currently
 * redundant.  It is here anyway: the change that turns caches on will be one
 * line in the reset path, made by somebody with no reason to think about the
 * loader.  See platform/cortex_r52/src/zx_cache.c for why the data side is
 * cleaned by range and the instruction side invalidated whole.  */

void zx_cache_sync_after_load(zx_addr_t base, zx_size_t length);

/* The smallest cache line on each side, in bytes, across every level.
   Reported at boot rather than merely used, because a maintenance loop that
   strode wrongly does not fail -- it leaves lines untouched -- so the stride
   belongs in a log where it can be compared against the part.  */

ZX_NODISCARD uint32_t zx_cache_dcache_line_bytes(void);
ZX_NODISCARD uint32_t zx_cache_icache_line_bytes(void);

/**************************************************************************/
/*                        The PMU cycle counter                           */
/**************************************************************************/

/* Turns on PMCCNTR so that a partition switch can be MEASURED rather than
   estimated.
 *
 * This exists because the generic timer is not usable as a clock here:
 * CNTFRQ reads zero on both targets, so there is no frequency to convert
 * with and nothing has programmed one.  The PMU cycle counter needs no
 * frequency -- the unit that matters for a WCET argument is cycles, not
 * seconds.
 *
 * PMCCFILTR matters and is easy to miss: the cycle counter has per-mode
 * enables, and code running in Hyp mode is not counted unless the Hyp bit
 * is set.  A missing one presents as a counter that reads zero or never
 * advances, which looks exactly like a PMU that is not implemented.  */

void zx_pmu_enable(void);

ZX_NODISCARD uint32_t zx_pmu_cycles(void);

/* Non-zero when the counter actually advances.  Worth asking rather than
   assuming: a measurement taken from a counter that is not running reports
   zero cycles for everything, which is a very convincing wrong answer.  */

ZX_NODISCARD uint32_t zx_pmu_is_running(void);

/* What the CORE clock runs at, measured against the system counter over a
   short bounded interval.
 *
 * Every switch figure this suite publishes is in core CYCLES, which is the
 * right unit for a worst-case-execution-time argument and is not a
 * self-contained one: nobody can turn a cycle count into a duration without
 * knowing the core clock, and this part reports it nowhere.  Measured
 * against the counter because the counter's frequency is the one in this
 * system that has actually been established.  Returns zero when the counter
 * or the cycle counter did not move.  */

ZX_NODISCARD uint32_t zx_pmu_core_hz(uint32_t counter_hz, uint32_t counts);

/* Turning protection on is TWO steps, and separating them is not tidiness.

   zx_el2_mpu_enable sets HSCTLR.BR and HSCTLR.M: the EL2-controlled MPU,
   which governs EL2's OWN accesses.  zx_stage2_enable then sets HCR.VM,
   which is what makes that same region set apply to EL0/EL1 as stage 2.

   They are separate because the hypervisor needs the first one BEFORE it can
   trust its own console.  On a board whose console sits below 0x60000000 the
   background map reaches it as NORMAL memory, which permits the gathering and
   reordering that corrupts a polled UART -- measured on the S32Z280, where
   the identity block printed as legible-but-wrong text until its Device
   region was in place and HSCTLR.M was set.  So the order is: HMAIR, the
   hypervisor's own MMIO regions, zx_el2_mpu_enable, THEN the console, then
   the partition regions, then zx_stage2_enable.

   Enabling HCR.VM with no region covering the payload's code faults at the
   ERET target, which presents as "the guest never started" and looks nothing
   like a memory-protection problem -- which is why the partition regions are
   a precondition of the second step rather than part of it.  */

void zx_el2_mpu_enable(void);
void zx_stage2_enable(void);
void zx_stage2_disable(void);

/**************************************************************************/
/*                        Running an EL1 payload                          */
/**************************************************************************/

/* Drop to EL1 at entry_address with argument in r0, and return when the
   payload yields (HVC #1) or is taken from by a fault.  Returns ZX_RUN_*.

   Implemented in zx_trap_handler.S.  It does not return through the ERET it
   performed: the trap handler restores the context saved here and resumes it,
   so this is a one-way transfer out and a resume back in.  */

ZX_NODISCARD uint32_t zx_el2_run_payload(zx_addr_t entry_address,
                                         uint32_t argument);

/* The statically allocated fault record the trap handler fills in.  Static,
   and filled in before anything else runs, because the earliest evidence is
   the only evidence that cannot have been damaged by the handler itself.

   The object is declared here rather than hidden behind the accessor because
   zx_trap_handler.S writes it directly, by name, at the ZX_ASM_FAULT_OFF_*
   offsets above.  A reader of that assembly needs to be able to find the
   declaration it is writing through.  */

extern zx_fault_record_t zx_el2_fault_storage;

ZX_NODISCARD zx_fault_record_t *zx_el2_fault_record(void);

/* How many times HVC #0 -- the empty Phase-0 hypercall vector -- has been
   taken.  Counted rather than ignored so that "the seam is live" is a number
   a test can assert on.  */

extern uint32_t zx_el2_hypercall_counter;

ZX_NODISCARD uint32_t zx_el2_hypercall_count(void);

/* Snapshots the reset path takes before it changes anything, so that the
   identity block can report what the PART reset to rather than what ZoneX
   left behind.  HSCTLR.TE and SCTLR.TE reset SET on the S32Z280 and clear on
   the Armv8-R AEM FVP; a report that read them after the reset path had
   cleared them would show the same value on both targets and hide the single
   most expensive difference between them.  */

extern uint32_t zx_reset_hsctlr;
extern uint32_t zx_reset_sctlr;
extern uint32_t zx_reset_cpsr;
extern uint32_t zx_reset_hprenr;

/* What sticks in HPRENR when all ones are written, taken by the reset path
   before any region exists.  This says which bits are IMPLEMENTED; whether a
   bit above 15 actually disables its region is a different question and is
   answered functionally by the probe image.  Both are needed: a register that
   accepted the bit and ignored it would pass this test and fail that one, and
   that is the outcome that would make a one-write partition switch silently
   wrong.  */

extern uint32_t zx_hprenr_implemented_bits;

/* The run's verdict, as an object as well as a printed line, so that a
   silicon run with no console capture is still judgeable.  0xFFFFFFFF until
   zx_console_exit sets it, because zero would be a plausible reading of a
   run that never reached its verdict at all.  */

extern uint32_t zx_run_failures;

/**************************************************************************/
/*                  A PARTITION'S CONTEXT, AND THE SWITCH                 */
/**************************************************************************/

/* How many EL1 MPU regions a context block can hold.
 *
 * TWENTY-FOUR IS THE ARCHITECTURAL MAXIMUM AND THE MODEL REPORTS
 * THIRTY-TWO.  MPUIR[15:8] gives the EL1 count and TRM Table 3-79 permits
 * 0, 16, 20 and 24; the Armv8-R AEM FVP reports 32, which is not a legal
 * Cortex-R52 value and is one of the reasons a green model run says nothing
 * about a real part's region budget.  The array is sized for what the model
 * reports rather than for what the architecture permits, because a save
 * that stopped at 24 on a part claiming 32 would silently drop the
 * outgoing partition's last regions and hand them to its successor.
 *
 * The count actually saved is read from MPUIR once at boot and clamped to
 * this; zx_context_el1_regions reports it, and the two-partition image
 * checks that nothing was clamped away.  */

#define ZX_MAX_EL1_REGIONS      32U

/* EVERYTHING THAT MAKES ONE PARTITION DIFFERENT FROM ANOTHER, in one
 * statically allocated block per partition.  No allocation, no list, no
 * pointer chasing: a switch indexes an array.
 *
 * THE ORDER OF THE FIRST FIFTEEN WORDS IS A CONTRACT WITH ASSEMBLY.  They
 * are what the FIQ vector captures before any C can run, at the
 * ZX_ASM_CTX_OFF_* offsets above, and every one of those offsets is
 * asserted against offsetof in zx_context.c.  Everything after them is
 * saved and restored by C, because at EL2 it is all still sitting in the
 * machine: Hyp mode banks only SP, LR and SPSR, so a guest's banked
 * registers, its EL1 system registers and its entire EL1 MPU can be read
 * and written from ordinary C while the hypervisor runs.
 *
 * That is what keeps the largest and least reviewable part of a partition
 * switch -- twenty regions, two registers each, selected through PRSELR --
 * a readable loop instead of a page of coprocessor moves.  It costs
 * nothing: the registers are the same registers whichever language reaches
 * them.
 *
 * WHAT IS NOT HERE, AND WHY IT IS NOT A HOLE.  The FPU.  D23 recorded that
 * clearing HCPTR.TCP10/TCP11 lets a guest use floating point while nothing
 * saves FPEXC, FPSCR or the D-registers -- exactly correct with one
 * partition and a shared register bank with two.  ZoneX does not save them;
 * it DENIES them.  zx_el2_deny_guest_fp leaves the traps SET for a
 * time-partitioned system, so a guest that touches floating point takes an
 * exception to EL2 and is named, rather than quietly reading whatever its
 * neighbour left.  A later phase either saves the bank or keeps refusing
 * it, and both are defensible; sharing it silently is not.  */

typedef struct ZX_GUEST_CONTEXT_STRUCT
{
    /* ---- captured in the vector, before anything else runs ---- */
    uint32_t    zx_ctx_r[13];           /* r0-r12, SHARED with EL1        */
    uint32_t    zx_ctx_elr;             /* ELR_hyp: where EL1 was         */
    uint32_t    zx_ctx_spsr;            /* SPSR_hyp: mode, flags, masks   */

    /* ---- banked at EL1, still live while the hypervisor runs ---- */
    uint32_t    zx_ctx_sp_usr;          /* User AND System share these    */
    uint32_t    zx_ctx_lr_usr;
    uint32_t    zx_ctx_sp_svc;
    uint32_t    zx_ctx_lr_svc;
    uint32_t    zx_ctx_spsr_svc;
    uint32_t    zx_ctx_sp_irq;
    uint32_t    zx_ctx_lr_irq;
    uint32_t    zx_ctx_spsr_irq;
    uint32_t    zx_ctx_sp_abt;
    uint32_t    zx_ctx_lr_abt;
    uint32_t    zx_ctx_spsr_abt;
    uint32_t    zx_ctx_sp_und;
    uint32_t    zx_ctx_lr_und;
    uint32_t    zx_ctx_spsr_und;
    uint32_t    zx_ctx_sp_fiq;
    uint32_t    zx_ctx_lr_fiq;
    uint32_t    zx_ctx_spsr_fiq;
    uint32_t    zx_ctx_r_fiq[5];        /* r8_fiq to r12_fiq              */

    /* ---- EL1 system registers ---- */
    uint32_t    zx_ctx_sctlr;
    uint32_t    zx_ctx_vbar;
    uint32_t    zx_ctx_cpacr;
    uint32_t    zx_ctx_contextidr;
    uint32_t    zx_ctx_tpidrurw;
    uint32_t    zx_ctx_tpidruro;
    uint32_t    zx_ctx_tpidrprw;
    uint32_t    zx_ctx_mair0;
    uint32_t    zx_ctx_mair1;
    uint32_t    zx_ctx_amair0;
    uint32_t    zx_ctx_amair1;

    /* ---- the guest's own virtual timer ---- */
    uint32_t    zx_ctx_cntv_ctl;
    uint64_t    zx_ctx_cntv_cval;

    /* ---- the hypervisor's per-partition time, which is what freezes ----
       CNTVOFF is EL2's, one value per partition, and the two instants
       beside it are what a check of the freeze is measured against.  They
       are here rather than in a file-scope array in zx_timer.c because
       with more than one partition they ARE partition state, and the one
       place a partition's state belongs is its context block.  */
    uint64_t    zx_ctx_cntvoff;
    uint64_t    zx_ctx_suspended_at;    /* physical count when it stopped */
    uint64_t    zx_ctx_resumed_at;      /* and when it was given the core */
    uint64_t    zx_ctx_virtual_at_stop; /* its OWN clock at that instant  */
    uint64_t    zx_ctx_time_on_core;    /* counts it has actually run for */

    /* ---- the EL1 MPU: the dominant cost of the whole switch ---- */
    uint32_t    zx_ctx_prbar[ZX_MAX_EL1_REGIONS];
    uint32_t    zx_ctx_prlar[ZX_MAX_EL1_REGIONS];
    uint32_t    zx_ctx_prselr;

    /* ---- bookkeeping, not machine state ---- */
    uint32_t    zx_ctx_entries;         /* times this context was entered */
    uint32_t    zx_ctx_preemptions;     /* times a boundary took the core */
    uint32_t    zx_ctx_started;         /* zero until its first entry     */
} ZX_GUEST_CONTEXT;

/* How many EL1 MPU regions this part actually has, clamped to the array
   above, and whether anything had to be clamped away.  Read once at boot:
   the count is fixed for the life of the run, and reading MPUIR inside the
   switch would put a coprocessor read on a path whose cost is the number
   this step exists to measure.  */

void zx_context_probe_el1_regions(void);
ZX_NODISCARD uint32_t zx_context_el1_regions(void);
ZX_NODISCARD uint32_t zx_context_el1_regions_clamped(void);

/* Prepare a never-run partition: its entry point, and the state a fresh
   guest is entered with.  Everything else is zero, which is the right
   starting value for every banked register a reset path is about to set.  */

void zx_context_init(ZX_GUEST_CONTEXT *context_ptr, zx_addr_t entry);

/* SAVE AND RESTORE THE HALF THAT C CAN REACH: banked registers, EL1 system
   registers, the guest's virtual timer, and the whole EL1 MPU set.  Called
   from the boundary handler between the vector's capture and its ERET, and
   from nowhere else.

   Both are straight-line apart from one loop whose trip count is the part's
   region count, read at boot.  Nothing in either depends on anything a
   guest did, which is what makes a partition switch one number rather than
   a distribution.  */

void zx_context_save(ZX_GUEST_CONTEXT *context_ptr);
void zx_context_restore(const ZX_GUEST_CONTEXT *context_ptr);

/* The EL1 MPU half of each, separately, because the measurement needs them
   separately: "how much of a partition switch is the guest's MPU set" is
   one of the numbers this work exists to produce, and the honest way to
   produce it is to time the code the switch actually runs rather than a
   copy written for the occasion.  A second loop kept beside the first
   agrees until the day it does not, and that is the day the published
   figure stops describing the shipped switch.  The cost of the split --
   one call each way -- is inside every figure this suite prints, because
   it is inside every switch it performs.  */

void zx_context_save_mpu(ZX_GUEST_CONTEXT *context_ptr);
void zx_context_restore_mpu(const ZX_GUEST_CONTEXT *context_ptr);

/* THE TIME HALF, WHICH IS WHAT THE DETERMINISM CLAIM RESTS ON.
 *
 * suspend records where the physical counter was and what the partition's
 * own clock read there; resume advances that partition's CNTVOFF by
 * everything that elapsed and puts it back in the register.  Between the
 * two the partition's virtual counter does not move, because the offset
 * moved by exactly as much as the counter did.
 *
 * Per CONTEXT rather than per hypervisor, which is the difference between
 * one partition and several: with two partitions the interval being
 * credited is the OTHER partition's window, and each has its own offset to
 * be credited into.  See docs/decisions.md D7.  */

void zx_context_time_suspend(ZX_GUEST_CONTEXT *context_ptr);
void zx_context_time_resume(ZX_GUEST_CONTEXT *context_ptr);
void zx_context_time_reset(ZX_GUEST_CONTEXT *context_ptr);

/* Print one partition's context: what it cost, where it was, and how much
   of its own clock it has been given.  */

void zx_context_report(const ZX_GUEST_CONTEXT *context_ptr,
                       const char *name_ptr);

/**************************************************************************/
/*                     Entering a time-partitioned frame                  */
/**************************************************************************/

/* Hand the core to a partition and do not come back until the FRAME ends.
 *
 * This is zx_el2_run_payload's shape one level up: it saves EL2's own
 * resume context, restores the given partition's, and ERETs.  It does not
 * return through that ERET.  Window boundaries are handled entirely inside
 * EL2's exception path -- the FIQ vector saves the outgoing partition,
 * restores the incoming one and ERETs again -- so C sees none of them.
 *
 * It returns, through the same resume path a fault takes, when a guest
 * yields or faults, when the schedule reaches its frame limit, or when the
 * frame has overrun.  The value is one of the ZX_RUN_* codes above.
 *
 * WHY BOUNDARIES DO NOT COME BACK HERE.  A switch that returned to C and
 * was re-entered would pay for a return, a dispatch and a call on the path
 * whose cost is the whole subject of this step -- and it would make the
 * hypervisor's stack depth depend on how a guest left, which is the one
 * thing a bounded switch cannot have.  */

ZX_NODISCARD uint32_t zx_el2_enter_partition(ZX_GUEST_CONTEXT *context_ptr);

/* The context the boundary handler is currently saving into, and the
   schedule it consults.  Set by the caller before the frame starts.
 *
   File-scope because the FIQ vector reaches them with no argument to be
   passed one in: an exception arrives with nothing but the machine.  They
   are declared here rather than hidden because zx_context.S names the
   first of them directly.  */

extern ZX_GUEST_CONTEXT *zx_el2_current_context;

/**************************************************************************/
/*                             THE MAJOR FRAME                            */
/**************************************************************************/

/* Everything the boundary handler needs, in one object it can reach with no
 * argument -- because an exception arrives with nothing but the machine.
 *
 * The counters are not decoration.  A switch cost quoted as a MEAN is a
 * number a safety audience will not accept: what they read is the MAXIMUM,
 * because that is what a schedule has to be built to survive.  Min, max,
 * total and count are kept so that the run can print all four and let a
 * reader see the spread rather than a summary of it.
 *
 * PMCCNTR IS 32-BIT AND WRAPS, which is why the per-switch figures are
 * uint32_t and the total is not: a switch is a few thousand cycles so one
 * difference cannot wrap, and ten thousand of them summed comfortably can.  */

typedef struct ZX_FRAME_STRUCT
{
    ZX_SCHEDULE        *zx_frame_schedule;
    ZX_GUEST_CONTEXT   *zx_frame_contexts;      /* one per partition       */
    const ZX_MM_LAYOUT *zx_frame_layout;

    /* WHOSE LINE IS THIS?  The manifest, so that the switch can hand the
       guest console the identity of the partition it has just SCHEDULED.
       The tag on a forwarded character has to come from the hypervisor and
       never from the guest, or a partition could claim to be its neighbour
       and every line of a captured log would be evidence of nothing.  With
       one partition that was a single attach around the whole excursion;
       with a frame it has to follow the frame, because the partition that
       owns the console changes several times a second.

       A null pointer means no console tagging, which is what an image that
       runs no guest console wants.  */
    const ZX_MANIFEST  *zx_frame_manifest;

    UINT                zx_frame_partitions;

    /* A bit per partition that has left its window early -- yielded, or
       been taken from by a fault.  Such a partition is NOT entered again,
       and its windows are still SPENT: that is what a static frame means,
       and giving its time to a neighbour would make one partition's
       schedule depend on another's behaviour.  */
    uint32_t            zx_frame_stopped_mask;

    /* What ended the frame, left where zx_context.S can pick it up: the
       boundary handler is a vector and has no caller to return a value to. */
    uint32_t            zx_frame_result;

    uint32_t            zx_frame_switches;

    /* How many of those boundaries were TIMED, which is not the same
       number.  A boundary that had to burn a stopped partition's window is
       a switch plus a wait of up to a whole window, and averaging the two
       together describes neither -- so it is counted as a boundary and left
       out of the cost.  In a healthy run the two are equal.  */
    uint32_t            zx_frame_timed;

    uint32_t            zx_frame_switch_min;
    uint32_t            zx_frame_switch_max;
    uint32_t            zx_frame_switch_last;
    uint64_t            zx_frame_switch_total;

    /* An FIQ that arrived at a boundary with the hypervisor's own timer NOT
       expired.  Nothing else is routed to EL2, so this should be zero for
       the life of a run; it is counted because a non-zero value means the
       vector was reached by something nobody has identified, and a switch
       performed on that basis would be a switch performed for no reason.  */
    uint32_t            zx_frame_spurious;

    /* WHICH partition left its window early, and what took it.  A frame
       that ran to its limit with one partition stopped in the middle is a
       different system from one where both ran throughout, and "the frame
       completed" says the same thing about both.  ZX_MANIFEST_NO_INDEX and
       ZX_RUN_FRAME_DONE when nobody left early.  */
    UINT                zx_frame_stopped_index;
    uint32_t            zx_frame_stop_outcome;
} ZX_FRAME;

/* Wire the frame up.  Nothing is entered and no timer is armed: this only
   records what the boundary handler will need, so that a caller can build
   the whole system before committing to run it.  */

void zx_frame_configure(ZX_FRAME *frame_ptr,
                        ZX_SCHEDULE *schedule_ptr,
                        ZX_GUEST_CONTEXT *contexts_ptr,
                        const ZX_MM_LAYOUT *layout_ptr,
                        const ZX_MANIFEST *manifest_ptr,
                        UINT partition_count);

/* RUN THE FRAME.  Returns when the schedule reaches its limit, when a guest
   leaves its window early and no partition is left to enter, or when the
   frame has overrun.  One of the ZX_RUN_* codes.
 *
 * A guest that yields or faults inside its window does NOT end the run: the
 * rest of that window is spent where it was declared to be spent, the
 * partition is marked stopped, and the frame carries on with its
 * neighbours.  An idle partition burning its window is not a limitation to
 * be optimised away -- it is the property that makes each partition's
 * timing independent of the others', which is the whole purchase.  */

ZX_NODISCARD uint32_t zx_frame_run(ZX_FRAME *frame_ptr);

/* What the boundary handler calls, from zx_context.S, with the outgoing
   partition's fifteen shared words already captured.  Returns the context to
   resume, or a null pointer when the frame is over.  Not called from C. */

ZX_NODISCARD ZX_GUEST_CONTEXT *zx_el2_window_boundary(void);

/* Where the boundary handler leaves the reason a frame ended, because the
   vector it runs in has no caller to return one to.  */

extern uint32_t zx_el2_frame_result;

/* MEASURE THE SWITCH, BY GROUP, using the same code the switch runs.
 *
 * Averages `rounds` iterations of each group with the cost of reading the
 * cycle counter measured separately and subtracted, and alternates the two
 * contexts so that no iteration is restoring the state already in force --
 * an implementation is entitled to make that cheap in a way a real switch
 * is not.  Both disciplines were established when the region-set switch was
 * first measured; they are reused here rather than reinvented because the
 * first version of that measurement was wrong in exactly the ways they
 * prevent.  See docs/decisions.md D4.
 *
 * Every figure is written into the structure the caller passes, so the
 * reporting stays with the image and the measurement stays with the port. */

typedef struct ZX_SWITCH_COST_STRUCT
{
    uint32_t    zx_cost_counter_read;   /* subtracted from every row below */
    uint32_t    zx_cost_save_full;
    uint32_t    zx_cost_restore_full;
    uint32_t    zx_cost_save_mpu;
    uint32_t    zx_cost_restore_mpu;
    uint32_t    zx_cost_region_mask;    /* the stage-2 switch, one write   */
    uint32_t    zx_cost_time_freeze;    /* suspend and resume, CNTVOFF     */
    uint32_t    zx_cost_deadline;       /* arming CNTHP_CVAL               */
    uint32_t    zx_cost_el1_regions;    /* how many the loops walked       */
} ZX_SWITCH_COST;

void zx_frame_measure_switch(ZX_GUEST_CONTEXT *scratch_a,
                             ZX_GUEST_CONTEXT *scratch_b,
                             uint32_t mask_a, uint32_t mask_b,
                             uint32_t rounds,
                             ZX_SWITCH_COST *cost_ptr);

/* Spend counter counts at EL2 until an ABSOLUTE deadline, bounded.
 *
 * The hypervisor's answer to a partition that handed its window back early.
 * A static frame does not give that time away, so it is burned here -- and
 * burned by watching the same counter the deadline was computed against,
 * so that the window a yielding partition leaves behind is exactly as long
 * as the one it would have run out.  */

void zx_el2_dwell_until(uint64_t deadline);

/* The priority the hypervisor's tick is given, so an image can check what
   the GIC read back against what was asked for rather than against a
   constant it restated.  */

ZX_NODISCARD uint32_t zx_frame_hyp_tick_priority(void);

/**************************************************************************/
/*                    The hypervisor's own timer, PPI 26                  */
/**************************************************************************/

/* CNTHP: the comparator that ends a partition's window.
 *
 * AN ABSOLUTE DEADLINE, WRITTEN TO CNTHP_CVAL, and never a countdown into
 * CNTHP_TVAL.  A countdown re-armed inside the handler adds the handler's
 * own latency to every window, so a frame declared as 10 ms becomes 10 ms
 * plus the switch -- cumulatively, invisibly, for the life of the run.  The
 * comparator is 64-bit and compares against the PHYSICAL counter, which is
 * the one thing in the system no partition can move.
 *
 * arm() returns non-zero when the deadline it was given is still in the
 * future.  A zero return means the window was shorter than its own switch,
 * which the schedule counts and the run reports; it is the caller's answer
 * to give, so it is returned rather than acted on here.  */

ZX_NODISCARD uint32_t zx_el2_hyp_timer_arm(uint64_t deadline);
void zx_el2_hyp_timer_stop(void);
ZX_NODISCARD uint32_t zx_el2_hyp_timer_fired(void);
ZX_NODISCARD uint64_t zx_el2_hyp_timer_deadline(void);

/* Route physical FIQ to EL2, leaving IRQ with EL1.
 *
 * THE ONE BIT THE WHOLE OF TIME PARTITIONING RESTS ON.  With HCR.FMO set,
 * PSTATE.F is IGNORED at EL0 and EL1: a partition CANNOT mask the interrupt
 * that ends its own window, however it sets its own masks and whatever its
 * kernel does with them.  A tick delivered as an IRQ could be deferred by
 * any guest that disabled interrupts, which is precisely the property time
 * partitioning must not concede.
 *
 * HCR.IMO stays CLEAR, so every guest interrupt is still a physical IRQ
 * delivered straight to EL1 with no injection and no List Register -- the
 * arrangement the single-partition work already proved end to end.  HCR.AMO
 * stays clear too, and that omission is deliberate rather than pending: an
 * asynchronous abort routed to EL2 arrives at the vector that today means
 * "ZoneX faulted on its own access", so setting AMO without reworking that
 * vector would report a guest's abort as a hypervisor bug.  See
 * docs/decisions.md D25.  */

void zx_el2_route_fiq(void);

/* Leave HCPTR.TCP10/TCP11 SET, so a guest's floating-point access traps.
 *
 * The opposite of what zx_el2_prepare_guest_el1 does, and it exists because
 * nothing saves the FPU across a partition switch.  With one partition an
 * open FPU is exactly correct; with two it is two guests sharing a register
 * bank, which is found by a wrong ANSWER rather than by a fault.  Denying it
 * turns that into an exception at EL2 with a syndrome naming the cause.  */

void zx_el2_deny_guest_fp(void);

/* And lift them again once the last window has closed.
 *
 * MEASURED, not stylistic: with the floating-point traps set, the S32Z280's
 * debug probe cannot read the core's register file at all, and the harness
 * exits non-zero on a run whose own console said ALL CHECKS PASSED.  What
 * the traps protect is the interval in which PARTITIONS run, and that
 * interval ends when the frame does.  See zx_timer.c.  */

void zx_el2_allow_guest_fp(void);

/**************************************************************************/
/*             The EL2 CPU interface, and the trap FMO sets                */
/**************************************************************************/

/* Bring up EL2's own GICv3 CPU interface: the priority mask and the Group 0
 * enable.
 *
 * THIS IS NOT OPTIONAL HOUSEKEEPING, AND THE REASON IS A REDIRECTION THAT
 * IS EASY TO MISS.  Setting HCR.FMO does more than route FIQ: it makes EL1
 * accesses to the Group 0 CPU-interface registers, AND to the ones common
 * to both groups, go to the VIRTUAL interface instead of the physical one
 * (Cortex-R52 TRM 9.3.5).  ICC_PMR is one of the common ones.
 *
 * So the instant FMO is set, the guest's own `ICC_PMR = 0xFF` -- which
 * every guest writes at start-up to unmask its interrupts -- lands in
 * ICV_PMR and changes nothing about physical delivery.  The physical
 * priority mask resets to ZERO, which masks everything, and a partition
 * that received its timer perfectly well a moment ago stops receiving
 * anything at all.  Nothing faults; the guest simply never ticks.
 *
 * The hypervisor therefore owns the physical mask and sets it wide enough
 * for both its own tick and the partitions' timers.  Priority ORDER still
 * does the work it always did: the tick is numerically lower and preempts.
 *
 * The redirection is also what makes Design A airtight rather than merely
 * cheap.  ICC_IGRPEN0 is redirected too, so a guest cannot reach the
 * physical Group 0 enable to switch off the interrupt that ends its window
 * -- it writes ICV_IGRPEN0 and nothing happens.  Before FMO was set that
 * register was genuinely shared, and D24 could only argue that a partition
 * had no Group 0 interrupt worth enabling.  */

void zx_gic_el2_cpu_interface_init(void);

/* Acknowledge and complete an FIQ at EL2, through the GROUP 0 registers.
 *
 * ICC_IAR0 returning ZX_INTID_SPURIOUS means nothing was pending, and it
 * must NOT be given an end-of-interrupt: the running priority was never
 * raised, so dropping it corrupts the GIC's priority stack rather than
 * merely being redundant.  */

ZX_NODISCARD uint32_t zx_gic_el2_acknowledge(void);
void zx_gic_el2_end_of_interrupt(uint32_t intid);

ZX_NODISCARD uint32_t zx_gic_el2_priority_mask(void);
ZX_NODISCARD uint32_t zx_gic_el2_group0_enabled(void);

/* Enable one PPI in GROUP 0, which is what the GIC delivers as an FIQ, at
   the given priority.  The hypervisor's own timer and nothing else: a
   partition is granted no Group 0 interrupt, which is why nothing can
   deliver an FIQ to a guest even though FIQ is now routed to EL2.  */

void zx_gic_enable_hyp_ppi(const ZX_GIC_LAYOUT *gic_ptr, uint32_t intid,
                           uint32_t priority);

/**************************************************************************/
/*                    Entry points the reset path calls                   */
/**************************************************************************/

/* zx_el2_main is where zx_el2_entry.S hands over, and it does not return.
   The board provides zx_board_init, called first: on the FVP it has nothing
   to do, and on silicon it brings up the console the rest of the run reports
   through.  */

ZX_NORETURN void zx_el2_main(void);
void zx_board_init(void);

/* Called from the vectors that mean ZoneX itself faulted, or that mean an
   exception nothing was expecting reached EL2.  Both report and stop; neither
   can safely resume, and pretending otherwise would turn a diagnosable bug
   into a corrupted run.  */

ZX_NORETURN void zx_el2_hypervisor_fault(void);
ZX_NORETURN void zx_el2_unexpected_vector(void);

#ifdef __cplusplus
}
#endif

#endif /* __ASSEMBLER__ */

#endif /* ZX_PORT_H */
