/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  COMPONENT                                             DESCRIPTION     */
/*                                                                        */
/*    zx_port.h                                            Cortex-R52     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    The Cortex-R52 port interface: everything ZoneX needs that is       */
/*    specific to Armv8-R AArch32 at EL2.                                 */
/*                                                                        */
/*  TERMINOLOGY -- READ THIS BEFORE ADDING ANYTHING BELOW                 */
/*                                                                        */
/*    The Cortex-R52 is AArch32-only and Armv8-R has NO PAGE TABLES at    */
/*    either stage of translation.  Both stages are region-based MPUs     */
/*    (PMSAv8-R).  The registers this port uses are therefore the         */
/*    AArch32 Hyp-mode ones, reached through MRC/MCR p15, 4, <Rt>, ...    */
/*    (opc1 = 4 is the Hyp bank):                                         */
/*                                                                        */
/*      HVBAR    EL2 vector base            HSR      syndrome             */
/*      HCR      hypervisor configuration   HDFAR    data fault address   */
/*      HSCTLR   EL2 system control         HIFAR    instruction fault    */
/*      HMPUIR   EL2 region count           HPFAR    stage-2 fault addr   */
/*      HPRSELR  region select              HMAIR0   memory attributes    */
/*      HPRENR   region enables             HMAIR1   memory attributes    */
/*      HPRBAR   region base                CNTHCTL  timer access control */
/*      HPRLAR   region limit               CNTVOFF  virtual time offset  */
/*      ICC_HSRE GICv3 sysreg interface                                   */
/*                                                                        */
/*    A second family of names is WRONG BY CONSTRUCTION for this target   */
/*    and must not appear anywhere in this repository: the AArch64        */
/*    system-register spellings, the translation-table registers, and the */
/*    RISC-V memory-protection vocabulary.  Using one of them means the   */
/*    code was written against the wrong architecture, and the result     */
/*    reads plausibly while being wrong about the hardware.               */
/*                                                                        */
/*    scripts/check_terminology.sh holds the exact list and enforces it   */
/*    in CI.  It is the single place that spells those names, so that     */
/*    the list cannot drift away from what is actually checked.           */
/*                                                                        */
/*    The verified encodings, field layouts and exception-class values    */
/*    are in docs/armv8r-el2-reference.md, which is the authority.  Take  */
/*    them from there rather than from memory or from an A-profile        */
/*    hypervisor; the AP field in particular does NOT mean at EL2 what it */
/*    means at EL1.                                                       */
/*                                                                        */
/*  STATUS                                                                */
/*                                                                        */
/*    Declared empty.  The CP15 accessors and the first stage-2 region    */
/*    programming arrive with the EL2 bring-up work.                      */
/*                                                                        */
/**************************************************************************/

#ifndef ZX_PORT_H
#define ZX_PORT_H

#include "zx_api.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif /* ZX_PORT_H */
