#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Entry point for the ZoneX Armv8-R AEM FVP target.
#
#   run.sh build    cross-configure and build every image
#   run.sh test     build, then execute the images on the FVP through CTest
#
# The model is found by CMake, with $HOME/FVP_Base_AEMv8R_11.32_19/bin as the
# hint.  Point ZX_FVP at a different one to override it.
#
# The suite is three runs of the same program: zx_probe.elf, which must pass,
# and two builds that must FAIL -- zx_probe_negative.elf, whose deliberate
# violation is aimed at an address the payload IS granted, and
# zx_probe_starved.elf, which is told it needs more MPU regions than exist.
# Both are registered with "--expect fail" in CMake, because a check that has
# never been seen to fail is not evidence that it can.
#
# zx_probe_el2_fault.elf is built but not registered: it makes ZoneX fault at
# EL2 on purpose, so its expected outcome IS a failure report.  Run it with
# "ninja -C build/fvp zx-run-probe-el2-fault" and read the report.

set -euo pipefail

readonly ROOT="$(cd "$(dirname "$(realpath "$0")")/../.." && pwd)"
readonly BUILD="${ROOT}/build/fvp"

command="${1:-test}"

configure() {
    local args=()
    if [ -n "${ZX_FVP:-}" ]; then
        args+=("-DZX_FVP_BASER_AEMV8R=${ZX_FVP}")
    fi
    cmake -S "${ROOT}" -B "${BUILD}" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="${ROOT}/cmake/cortex_r52.cmake" \
        -DCMAKE_BUILD_TYPE=Debug \
        -DZX_BUILD_FVP_EXAMPLE=ON \
        -DZX_BUILD_S32Z280_EXAMPLE=OFF \
        "${args[@]}"
}

# Read from the generated ninja graph rather than from a list kept in this
# script.  Images are EXCLUDE_FROM_ALL, so a bare build reports "no work to
# do", and reading the graph means an image added to CMakeLists.txt cannot
# escape the run by nobody remembering to list it here.
images() {
    ninja -C "${BUILD}" -t targets all 2>/dev/null \
        | grep -oE '^[A-Za-z0-9_]+\.elf' \
        | grep -v '^cmake_' | sort -u || true
}

case "${command}" in
    build|test)
        configure
        cmake --build "${BUILD}"

        # An empty list is a FAILURE now that ZoneX has images: it means the
        # CMake graph broke.  It was a zero-status notice while the repository
        # genuinely had none.
        image_list="$(images)"
        if [ -z "${image_list}" ]; then
            echo "ZoneX: no FVP images were found in the ninja graph." >&2
            echo "ZoneX: ZoneX HAS images, so the build system is broken rather" >&2
            echo "ZoneX: than the tree being incomplete." >&2
            exit 1
        fi

        # shellcheck disable=SC2086
        cmake --build "${BUILD}" --target ${image_list}

        if [ "${command}" = "test" ]; then
            ctest --test-dir "${BUILD}" --output-on-failure
        fi
        ;;
    *)
        echo "Usage: $0 [build|test]" >&2
        exit 1
        ;;
esac
