#!/bin/bash
###############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
###############################################################################
#
# Entry point for the ZoneX Armv8-R AEM FVP target.
#
#   run.sh build    cross-configure and build every image
#   run.sh test     build, then execute the images on the FVP through CTest
#
# The model is found by CMake, with $HOME/FVP_Base_AEMv8R_11.32_19/bin as the
# hint.  Point ZX_FVP at a different one to override it.
#
# STATUS: there are no images yet.  "build" therefore configures and builds the
# hypervisor libraries, and "test" reports that there is nothing to execute --
# loudly, and with a zero status, because a foundation-only tree failing its own
# CI would say nothing useful.  Once the first image lands this script starts
# doing what its name says.

set -euo pipefail

readonly ROOT="$(cd "$(dirname "$(realpath "$0")")/../.." && pwd)"
readonly BUILD="${ROOT}/build/fvp"

command="${1:-test}"

configure() {
    local args=()
    if [ -n "${ZX_FVP:-}" ]; then
        args+=("-DZX_FVP_BASER_AEMV8R=${ZX_FVP}")
    fi
    cmake -S "${ROOT}" -B "${BUILD}" -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE="${ROOT}/cmake/cortex_r52.cmake" \
        -DCMAKE_BUILD_TYPE=Debug \
        -DZX_BUILD_FVP_EXAMPLE=ON \
        -DZX_BUILD_S32Z280_EXAMPLE=OFF \
        "${args[@]}"
}

# Read from the generated ninja graph rather than from a list kept in this
# script.  Images are EXCLUDE_FROM_ALL, so a bare build reports "no work to
# do", and reading the graph means an image added to CMakeLists.txt cannot
# escape the run by nobody remembering to list it here.
images() {
    ninja -C "${BUILD}" -t targets all 2>/dev/null \
        | grep -oE '^[A-Za-z0-9_]+\.elf' \
        | grep -v '^cmake_' | sort -u || true
}

case "${command}" in
    build|test)
        configure
        cmake --build "${BUILD}"

        image_list="$(images)"
        if [ -z "${image_list}" ]; then
            echo "ZoneX: no FVP images exist yet."
            echo "ZoneX: the hypervisor libraries were built; nothing was executed."
            exit 0
        fi

        # shellcheck disable=SC2086
        cmake --build "${BUILD}" --target ${image_list}

        if [ "${command}" = "test" ]; then
            ctest --test-dir "${BUILD}" --output-on-failure
        fi
        ;;
    *)
        echo "Usage: $0 [build|test]" >&2
        exit 1
        ;;
esac
